### ISSUE TITLE
Customization Question

### ISSUE THREAD

**Issue by Kwarlin** [pnp/custom-learning-office-365#100]
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

We don't use Yammer and I've edited the "your productivity experience" image showing the steps in a day to remove Yammer, but is it possible to replace that picture with the one I've edited?  I also need to remove Yammer where ever it appears. 

Also, I see that you have an upgrade that I believe removes references to Skype, is that correct?

**Comment by juliemturner** [comment]
To change anything about a playlist provided by the source you must create a custom playlists and then hide the one you're replacing, although there is no way to reorder and probably won't be soon as technically it's quite difficult to let you order content that can change at anytime.  

To your second question a content refresh is coming and yes I believe it will remove references to Skype.

**Comment by juliemturner** [comment]
closed to inactivity
