### ISSUE TITLE
Error with Javascript for Learning Pathways when provisioned

### ISSUE THREAD

**Issue by mgannotti** [pnp/custom-learning-office-365#103]
#### Category

- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Upon provisioning the Learning Pathways solution expect to see the webpart rendering with views to the training content

#### Observed Behavior

When accessing it content receive error listed below:
[SPLoaderError.loadComponentError]:
***Failed to load component "141d4ab7-b6ca-4bf4-ac59-25b7bf93642d" (CustomLearningWebPart). Original error: ***Failed to load path dependency "CustomLearningWebPartStrings" from component "141d4ab7-b6ca-4bf4-ac59-25b7bf93642d" (CustomLearningWebPart). Original error: Error loading https://component-id.invalid/141d4ab7-b6ca-4bf4-ac59-25b7bf93642d_2.0.15/CustomLearningWebPartStrings
Unable to load script https://labcorpdev01.sharepoint.com/sites/apps/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/v2-customlearningwebpartstrings_en-us_550d233e4c4642a78860ff6ed0424b18.js

***INNERERROR:
***Failed to load path dependency "CustomLearningWebPartStrings" from component "141d4ab7-b6ca-4bf4-ac59-25b7bf93642d" (CustomLearningWebPart). Original error: Error loading https://component-id.invalid/141d4ab7-b6ca-4bf4-ac59-25b7bf93642d_2.0.15/CustomLearningWebPartStrings
Unable to load script https://labcorpdev01.sharepoint.com/sites/apps/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/v2-customlearningwebpartstrings_en-us_550d233e4c4642a78860ff6ed0424b18.js
***CALLSTACK:
Error
at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-07-05.010/sp-pages-assembly_en-us_0b9c90a9424a41e57a3ad3be1f178c04.js:45:29877)
at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-07-05.010/sp-pages-assembly_en-us_0b9c90a9424a41e57a3ad3be1f178c04.js:169:74253)
at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-07-05.010/sp-pages-assembly_en-us_0b9c90a9424a41e57a3ad3be1f178c04.js:169:86503)
at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-07-05.010/sp-pages-assembly_en-us_0b9c90a9424a41e57a3ad3be1f178c04.js:169:82534)
at https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-07-05.010/sp-pages-assembly_en-us_0b9c90a9424a41e57a3ad3be1f178c04.js:169:103929

![errorlp](https://user-images.githubusercontent.com/32645585/61560729-198d6500-aa3b-11e9-8c55-560123a91f74.jpg)

#### Steps to Reproduce

Deleted Learning Pathway solution, deleted app catalog. Had global domain tenant admin recreate app catalog. Waited 30 minutes. He then re-provisioned. same error. Deleted all. Rechecked steps redid and same result. Appears to be issue with client side Javascript. We are checking to see if Intune rules are in fact blocking and causing the issue. You can see warning in attached image as well as some broken images

Thanks for your contribution! Sharing is caring.

**Comment by juliemturner** [comment]
@mgannotti -- Every time we've seen this issue it's because something is blocking downloading the content. Please check your browser network tab to see if any files are being blocked from being downloaded.

**Comment by mgannotti** [comment]
Thanks!

Michael Gannotti
Microsoft Teams Principal Technical Specialist
Microsoft
US – North East – National Health and Life Sciences
Mobile: 919-448-4107
Email: mgann@microsoft.com<mailto:mgann@microsoft.com>
Connect with me on LinkedIn<https://www.linkedin.com/in/mikegannotti/> | Twitter<https://twitter.com/gannotti> | Facebook<https://www.facebook.com/michaelgannotti> | Instagram<https://www.instagram.com/mgannotti/> | IGTV<https://www.instagram.com/mgannotti/channel/>
Visit the Microsoft Healthcare and Life Sciences Blog<https://aka.ms/HLSBlog>

**Comment by mgannotti** [comment]
The customer reviewed InTune Policy and found following, remediated, and now Learning Pathways functioning as expected :-)

**Comment by mgannotti** [comment]
I have confirmed the Azure AD Conditional Access policy that enforces the “Use app enforced restrictions” session control in SharePoint Online when connecting from a non-complaint or non-AAD joined device was causing this issue. I have disabled the policy and the site is showing up correctly!
