### ISSUE TITLE
403 forbidden on Set-PnPStorageEntity

### ISSUE THREAD

**Issue by tchinnin** [pnp/custom-learning-office-365#105]
#### Category

- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Deploy M365CL by executing the PowerShell script M365lpConfiguration.ps1 provided

#### Observed Behavior

Got a 403 Forbidden when trying to create the PnPStorageEntities

#### Steps to Reproduce

Try the GET/SET-PnPStorageEntity when connected to the central admin with Connect-PnPOnline https://<tenant>-admin.sharepoint.com

#### Submission Guidelines

Need to connect first to the AppCatalog site, as the PnPStorageEntities are stored on the appcatalog site PropertyBag, on the storageentitiesindex Key 

 $appcatalog = Get-PnPTenantAppCatalogUrl
  try {
    Connect-PnPOnline -Url $appcatalog -Credentials $Credentials
  }
  catch {
    Write-Host "Failed to authenticate to $appcatalog"
    Write-Host $_
    break
  }

Thanks for your contribution! Sharing is caring.

**Comment by juliemturner** [comment]
@tchinnin -- Please validate the account you're trying to use is a Site Collection Admin of the app catalog site collection.

**Comment by tchinnin** [comment]
My account is Global Admin and Site collection admin of the app catalog as well

**Comment by juliemturner** [comment]
@tchinnin the only reason I've ever seen for a forbidden error is if you're account doesn't have the right credentials to the app catalog site.  Maybe verify by going into the app catalog site collection and specifically look at the site collection admin list to verify that somehow it didn't get removed.

**Comment by tchinnin** [comment]
I've checked, my account is named into the site collection admin, there are alos Company admin and SharePoint Service Admin (groups that i'm part of as well).
My assumption is that we should execute the Set-PnPStorageEntity while connected the to App Catalog site and not the Central Admin site. 
I've updated the script as suggested and it works fine

**Comment by juliemturner** [comment]
@tchinnin I connect to the Central Admin site and execute Set-PnPStorageEntity almost daily. I'm not sure what is different about your configuration that it's causing an error but glad you found a way around it.

**Comment by bhlaws** [comment]
My coworker and I just received the exact same issue. We're SPO Admins and site collection admins. We can't have Global Admin due to company policy. This is a GCC tenant, so that might explain the issue (although unlikely). However, like @tchinnin , we were able to get the script to work by calling Connect-PnPOnline -Url $appcatalog before the calls to Set-PnPStorageEntity. Doing so allowed everything to work without requiring Global Admin. I highly recommend that the script be updated to make that call to explicitly connect to $appcatalog.

**Comment by juliemturner** [comment]
Issue has been fixed in an updated version of the powershell script.

**Comment by advdberg** [comment]
For those who might concern and run into the same issue but then with App-Only context (also with latest version of PnP), the workaround with using an App Catalog connection also works for this case
