### ISSUE TITLE
CustomLearningAdmin.aspx first use not working with Firefox

### ISSUE THREAD

**Issue by FranckyC** [pnp/custom-learning-office-365#109]
When running the manual installation procedure, going to CustomLearningAdmin.aspx leads to an error using Firefox. Works fine using Chrome. Not a big deal since there is a workaround then.

Error with Firefox:

![image](https://user-images.githubusercontent.com/5659122/63288100-eaf8e900-c289-11e9-8541-7b0f87e2a500.png)

![image](https://user-images.githubusercontent.com/5659122/63288361-7bcfc480-c28a-11e9-9494-7f78f7996748.png)

No error with Chrome:

![image](https://user-images.githubusercontent.com/5659122/63288166-0ebc2f00-c28a-11e9-9c66-f38e56e59956.png)

#### Category
- [x] Bug

Version used for the portal: 2.0.17.0
Firefox version: 68.0.2
Chrome version: 76.0.3809.100

Applied the following [procedure](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/README.md). The errors occurs when browsing the `CustomLearningAdmin.aspx` page for the first time.

**Comment by juliemturner** [comment]
@FranckyC -- Based on the console it looks like for some reason firefox is blocking you from downloading the manifest files from the CDN. Based on Chrome working for you that doesn't seem environmental. I tested the same version of firefox with that same version of the web part and it's loading ok for me so I do not think there is a bug with the code/browser combination. That I guess leaves browser configurations? Please take a look at the network tab as based on the error messages that's the only path I can see right now to diagnosing the issue you're having.

**Comment by FranckyC** [comment]
Thanks @juliemturner I will dig into the network tab. Like I said, this is not a major issue. Maybe it is a wrong browser configuration on my side. Thank you for confirming me it works with the same combination on your side!

**Comment by FranckyC** [comment]
Ok understood. It was a Firefox fox plugin blocking some content ;) Thanks!
