### ISSUE TITLE
after manual deployment, CustomLearningAdmin.aspx error

### ISSUE THREAD

**Issue by davepae** [pnp/custom-learning-office-365#11]
Using tenant admin that has site owner and site admin rights, I am getting this error when visiting the customlearningadmin.aspx page. 

The CustomLearningAdminWebPart has not been properly configured and you do not have Owner rights to complete the operation. Please contact the site administrator.

And here is the web call error:

(anonymous) @ CustomLearningAdmin.aspx:88
custom-learning-admin-web-part_e27bb1fbb909d3ee73c638c6169985bb.js:24 Message: [5e4f9bb0-8ad4-4aa6-ab69-b768143c85a4] (1552501512969) Completing GET request. Data: {}
custom-learning-admin-web-part_e27bb1fbb909d3ee73c638c6169985bb.js:24 Message: [5e4f9bb0-8ad4-4aa6-ab69-b768143c85a4] (1552501512980) Returning result from pipeline. Set logging to verbose to see data. Data: {}
custom-learning-admin-web-part_e27bb1fbb909d3ee73c638c6169985bb.js:24 Message: Microsoft Custom Learning Admin is not in the web defined by the tenant property MicrosoftCustomLearningSite: 'https://customlearningdemo.sharepoint.com/sites/O365CL3'. If the tenant property is correct than this web part cannot run in this web.
e.log @ custom-learning-admin-web-part_e27bb1fbb909d3ee73c638c6169985bb.js:24

**Comment by juliemturner** [comment]
I believe this was solved as it was determined that this was a new tenant and you need to wait at least 30 minutes after creating the tenant app catalog before trying to deploy.
