### ISSUE TITLE
Missing Default Content - Microsoft 365 learning pathways Site

### ISSUE THREAD

**Issue by DevSpMan** [pnp/custom-learning-office-365#114]
- [X] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

"Microsoft 365 learning pathways"

I have installed this solution using the SharePoint Online Provisioning Tool, the Microsoft 365 Learning area is blank. I am not able to get any of the default content to display. The tool installs the 2.0.15.0 version. I updated the app to the 2.17.0 with the same results. It appears like the app is trying to load then it appears to stop and no content is displayed. 

Chrome didn't load the content until after loading the content first using IE. Does this solution require the installation and setup in IE first? 

Chrome (Version 76.0.3809.132 64-bit) 
IE (IE 11 Version: 11.295.18362.0)
Fire Fox (Version: 68.0.2 64-bit)
Microsoft Edge (Version: 44.18362.267.0)

Thank You

**Comment by juliemturner** [comment]
@DevSpMan - The solution actually works much better in Chrome than IE. I suspect you had network problems downloading the content and may still have.  I suggest you go to the CustomLearningAdmin.aspx page and validate that you're not seeing any errors in the browser's developer tools, specifically the Console. If you are, validate those errors by also checking the Network tab to see if any of the calls are faling and what the errors are.  We have had people have firewalls or browser plug-in's block the download of the manifest files from the CDN source.

**Comment by juliemturner** [comment]
Closed to lack of activity
