### ISSUE TITLE
How frequently is the solution updated?

### ISSUE THREAD

**Issue by techieSudeep** [pnp/custom-learning-office-365#115]
Could you please let me know how frequently the solution is updated? We are currently rolling out Teams and the release of Learning Pathways is very timely. However, when looking at Teams content (for example), I see that the latest training videos that are mentioned here are not reflected in the app. https://support.office.com/en-us/article/Microsoft-Teams-video-training-4f108e54-240b-4351-8084-b1089f0d21d7. So, how frequently is the solution updated?

**Comment by peterjkrebs** [comment]
With regard to content updates, we are planning on Quarterly Updates. We are currently in the process of implementing our content update process. Our first Quarterly Update will happen in the November timeframe, and will include all the updated content, including Teams. We will have ongoing quarterly content updates after that.

**Comment by lwillison** [comment]
Hi. Can you please provide an update on when new content will be added to Learning Pathways? More advanced topics for Teams & SharePoint, as well as Stream and Flow content?
