### ISSUE TITLE
Are the missing standard products still being added to Microsoft 365 training?

### ISSUE THREAD

**Issue by jinnfaster** [pnp/custom-learning-office-365#117]
#### Category

- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Under Microsoft 365 training you will find very good instructions for the Microsoft programs (Word, Excel, OneDrive. . . ). 
For some programs there are no instructions (Stream, Visio etc. ). 
Is it planned that these programs will be included in the training or not?

**Comment by juliemturner** [comment]
Content was refreshed as of Ignite 2019
