### ISSUE TITLE
Want to point office 365 learning pathways to custom Git repository

### ISSUE THREAD

**Issue by kjediseh** [pnp/custom-learning-office-365#118]
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hey guys,

Really excited about discovering this today - I'm a L&D Manager here, so all the more appropriate! I'm in the process of getting this learning pathways site provisioned on our SharePoint online and go through all the steps. However, I'd like to customize the roll-out of the site well beyond what's out of the box. 

In that, I'm looking to leverage this learning pathways site as the means to deliver non-standard (non-Office 365) content such as internal policies/procedures/help files/manuals and all the support stuff in playlists and pathways, but still on the site as it's designed. I'm hoping someone can help me how to: modify the content in the GitHub repository so the pathways site still points to it or points to a different repository on GitHub. Ideally, I'm looking to store content I would author with Adobe Robohelp or MadCap Flare (like in the Tech Comm world) and store natively in GitHub either in ASPX or XHTML format; this way, I can do single-sourcing and a bunch of content curation/authoring stuff I can't do in SharePoint. But ultimately then, serve it up/point to it from the SharePoint Learning Pathways Site.

Please advise!

Thanks,

Karthik Jediseh

Senior Manager of Learning and Development

GoodLife Fitness

**Comment by kjediseh** [comment]
Hi Julie,

First of all, I wanted to humbly thank you for your prompt and detailed response! I see how you're really taking charge of all the questions and providing timely and useful answers - really commendable and overall awesome! In terms of follow-up, I'd probably prefer the latter where, once there is a newer release, I'd like to customize the entire site collection to be referencing assets I create and manage myself. Ideally, I'd like it all to be populated with content related to company-specific learning, i.e, policies, procedures, how-to guides, manuals, and other information that will be uploaded to a Git repository from Adobe Robohelp or MadCap Flare.

In terms of that method, I was wondering if you could provide some more insight. What sort of format would be the content that I'd reference as assets in the SharePoint learning site to be? ASPX (Robohelp can do this) or XHTML (Robohelp and Flare can both do this). The reason I choose those applications is, if you know anything about technical documentation, is that I can publish these assets using single-sourced methods and a superior document authoring experience than Word or SharePoint can provide.

If they reside there (in Git) as standalone XHTML/ASPX files, then can I simply just build out custom learning pathways in the SharePoint learning pathways site as per the link you shared in terms of the procedure? I hope you're understanding what I'm trying to achieve. I just want to know that it's technically achievable. Also, when do you suspect the next release/version will be out?

Thanks,
Karthik

**Comment by juliemturner** [comment]
All the content from the repositories are manifested inside an iframe, so if the content can be loaded in a browser, independent of SharePoint then yes, they can live wherever you want them and yes with this newer version coming in the next few months you can create and curate your own set of content separate from what Microsoft will provide.  I do not have exact dates on when this will be available but I think it's feasible to expect it before the end of the year.

**Comment by kjediseh** [comment]
Hi Julie,

Thank you again for the prompt and informative reply! That'd be great if it works out in this way that is envisioned - still waiting for the IT group to provision me this out-of-the-box site - so much red tape! (RFCs, blah blah). Anyway, will reach out if I need anything else!

Cheers,
Karthik

**Comment by juliemturner** [comment]
Your welcome.
