### ISSUE TITLE
Excel module [Create a drop-down list] has video link duplicate of [Fill data automatically]

### ISSUE THREAD

**Issue by bengtmoss** [pnp/custom-learning-office-365#119]
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
In Home > Excel > Intro to Excel > Create a drop-down list, the video should fit the module title.

#### Observed Behavior
In Home > Excel > Intro to Excel > Create a drop-down list, the video is "Fill data automatically":
![Excel-create-dropdown-duplicate-of-fill-data-automatically](https://user-images.githubusercontent.com/11742565/64852758-3f3d8180-d61a-11e9-898f-17908366e18b.png)

This is the video that obviously fits in Home > Excel > Intro to Excel > Fill data automatically.

#### Steps to Reproduce
In the MLP Viewer, navigate to Home > Excel > Intro to Excel > Create a drop-down list.

**Comment by juliemturner** [comment]
Content has been refreshed closing this issue.

**Comment by bengtmoss** [comment]
I have upgraded to 3.0.1.0, but the content is unchanged: The module _Create a download list_ still links to the video _Fill data automatically_. Am I missing something? If not, please reopen this ticket.

![MlpExcelIntroCreateADownloadList](https://user-images.githubusercontent.com/11742565/69010187-866b2a00-095d-11ea-92d2-51c56964a375.png)

**Comment by juliemturner** [comment]
For tracking purposes please open a new ticket if you feel there are still issuea
