### ISSUE TITLE
mixed languages in consent

### ISSUE THREAD

**Issue by ksagala** [pnp/custom-learning-office-365#12]
Some of information in consent window is in Polish (language set for tenant) some in English
![PnPConsent](https://user-images.githubusercontent.com/22879705/54307279-8abf9600-45cb-11e9-8a96-e6c49856d098.PNG).
Not an issue for me, just for information.

**Comment by davepae** [comment]
https://docs.microsoft.com/en-us/office365/customlearning/faq

Custom Learning for Office 365 is currently available only in English. Automatic end-to-end provisioning only works with English tenants. Additional languages may be added at in future releases.

**Comment by karuanag** [comment]
Ack to issue.  Transferring to PNP repo
