### ISSUE TITLE
LearningPathways takes up to 2+ hours to update edits using Playlist Administration

### ISSUE THREAD

**Issue by SJHCtrain** [pnp/custom-learning-office-365#120]
The issue we’re having is that:
•         edits made using the Playlist Administration can take up to two hours before we see the results take effect
•         We’ve deleted all cache, re-signed in, etc. and we’re experiencing this problem regardless of browser

**Comment by juliemturner** [comment]
@SJHCtrain  Please verify that you've got the most recent version of the web part installed in your tenant. The following documentation will help you assess: https://github.com/pnp/custom-learning-office-365#updating-the-solution

**Comment by SJHCtrain** [comment]
Thanks Julie! It's updating almost instantly now!!
Take care,
Craig
