### ISSUE TITLE
Sources that need to be open for content to display

### ISSUE THREAD

**Issue by jleporaj** [pnp/custom-learning-office-365#121]
#### Category

- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Question

Apologies if this is documented somewhere and I’m probably missing it. Looking for information documented that shows what sites / location needs to be opened for all content to display and render correctly. Site loads fine outside of network but internal we are seeing content missing and images missing on some of the areas. We can gather some of the sources from where the tool is pointing to load in images - but looking for a master list if that exists.

**Comment by juliemturner** [comment]
@jleporaj  -- You would need to whitelist the CDN source, which is https://pnp.github.io/custom-learning-office-365/. You would also need to whitelist https://docs.microsoft.com and https://support.office.com.  All the content the web part loads comes from one of those 3 sources.  If you have any other issues you probably can solve them by check in the browser developer tools and looking at the network tab, whatever is in red is most likely being blocked.

**Comment by jleporaj** [comment]
That’s awesome, thanks @juliemturner. I’ll relay that. 

Perhaps something that could be explained out in the docs site too in the future?  As we continue to expand the footprint of this toolset I see this as a common faq.
