### ISSUE TITLE
Unable to provision SharePoint Starter Kit or Microsoft 365 learning pathways

### ISSUE THREAD

**Issue by KrimsonAce** [pnp/custom-learning-office-365#122]
Hello, I was pointed to here to report my issue by Office 365 support. I hope you'll be able to help me as I'd like to push SharePoint within the business and I think these solutions will help greatly with that.

#### Category

- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Being able to provision both of the solutions available at https://provisioning.sharepointpnp.com/

#### Observed Behavior

Receiving an error that prerequisites are not fulfilled, requesting that I have full control permissions on the app catalog, which I do.

[FireShot Capture 018 - SharePoint Online Provisioning Service - provisioning.sharepointpnp.com.pdf](https://github.com/pnp/custom-learning-office-365/files/3626896/FireShot.Capture.018.-.SharePoint.Online.Provisioning.Service.-.provisioning.sharepointpnp.com.pdf)
[FireShot Capture 019 - Manage site collections - zeusjuice-admin.sharepoint.com.pdf](https://github.com/pnp/custom-learning-office-365/files/3626897/FireShot.Capture.019.-.Manage.site.collections.-.zeusjuice-admin.sharepoint.com.pdf)

#### Steps to Reproduce

- Visiting https://provisioning.sharepointpnp.com/
- Signing into my Office 365 Admin account
- Selecting the solutions tab
- Selecting either SharePoint Starter Kit or Microsoft 365 learning pathways
- Selecting add to tenant
- Filling out the required information and selecting provision

Many thanks

**Comment by juliemturner** [comment]
@KrimsonAce -- So I'm sorry you're having problems provisioning. I'm also sorry that office support told you to go here as support for the provisioning service, even though you're trying to provision learning pathways, actually goes in https://github.com/SharePoint/sp-dev-docs/issues.  I would if I could transfer your issue but unfortunately I don't have that ability.

**Comment by KrimsonAce** [comment]
No worries @juliemturner, I appreciate your response. I shall head over there. Thank you for pointing me in the right direction!

Kind regards

**Comment by juliemturner** [comment]
@KrimsonAce  -- I have communicated with the team in charge of the provisioning service and they've confirmed that what you're experiencing is a bug and have corrected it. The fix will go out shortly.  There is a work around but I hesitate to publically share it when the fix will render it invalid. If you can wait until the weekend or early next week then I'd say do that, if not DM me on twitter (jfj1997) and I'll share the work around with you.

**Comment by KrimsonAce** [comment]
Good morning @juliemturner, thank you so much for reaching out to them. I'm relieved to hear that it's not just an isolated case. I shall wait for the fix to be pushed out and give it another attempt. I can then start working on getting SharePoint deployed within the business!

Many thanks again for your time with this. I shall be closing this issue.
