### ISSUE TITLE
Question: linking directly to training material/playlist

### ISSUE THREAD

**Issue by Celestero** [pnp/custom-learning-office-365#127]
Is there a way to link specific playlist or training (i.e. Create a document) in email? When I try to copy the exact link from the learning pathways in email, it takes me directly to the learning pathway home page instead of the specific content I was trying to link.
- [x ] Question

**Comment by juliemturner** [comment]
@Celestero  -- have you tried the "link" functionality in the webpart?

![image](https://user-images.githubusercontent.com/7570936/65458515-bd203a80-de1b-11e9-87f8-f5c72db52918.png)

**Comment by kyleg11** [comment]
The promote button when at the page also works to give that direct URL
