### ISSUE TITLE
CustomConfig is refreshed automatically

### ISSUE THREAD

**Issue by VincentVidal-ext** [pnp/custom-learning-office-365#128]
#### Category

>**PROVISIONING NOTE**: If you are having issues with the provisioning service while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the provisioning service to [https://github.com/SharePoint/sp-dev-docs/issues](https://github.com/SharePoint/sp-dev-docs/issues).

- [ ] Question
- [x] Bug
- [ ] Content

>
> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Expected or Desired Behavior

When I make some changes in the CustomConfig, I need my changes remain as is. 

#### Observed Behavior

Currently, when I make some changes in CustomConfig, my changes are effective just after updated it. However, the day after, changes are not effective anymore and CustomConfig is like before my changes (return to the default CustomConfig). 

#### Steps to Reproduce

Go to "Site contents" --> "CustomConfig" --> "CustomConfig" --> make some changes in the "JSONData" section.
Go back to the "JSONData" data section the day after and changes have disappear.

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by juliemturner** [comment]
@VincentVidal-ext  -- Unfortunately what you're trying to do fundamentally goes against what that particular entry in that list is.  That entry is a cache for the work that goes on every time the web part reloads the manifest from the source repository. If you navigate to the admin experience the cached data is reloaded every time you reload the page and if you go to a page with the viewer web part it's refreshed after 24hours by the first person to hit the web part after that time has passed. It is meant to help speed up the load time of the web part as the merging of custom playlists, hidden playlists, custom subcategories, etc into the source manifest as that process is more intensive than you'd want to have run on every load. Therefore, fundamentally, you cannot edit it manually. There are a few things you can do to affect its values but those are all at the moment exposed by the UX.

**Comment by VincentVidal-ext** [comment]
Hello Julie,
Thank you for your responsiveness and your feedback. 
Actually, the idea is simply to be able to change the pictures and the wordings of "Categories" without being refreshed every day. We need to personalize some features to fit with our company.
So do we have a solution to customize these elements without being reloaded every time?
If we are not able to personalize those few things, unfortunately we will not use Learning Pathways.
Thank in advance for your inputs.
Regards.

**Comment by juliemturner** [comment]
At this time no there is no way to customize these things as the entire point is that Microsoft intends to keeps the content fresh. A feature will be coming soon to allow you to create your own content manifest and then in that case you could create a copy of Microsoft’s manifest files and the. Host them yourself in your own github repo or any other CDN endpoint but then keeping the content fresh will fall to you. There are currently no plans to allow the personalization of The downloaded content. If you feel strongly about that feature I’d encourage you to submit a user voice request. https://aka.ms/M365LPUserVoice
