### ISSUE TITLE
Relationship/Connection of the LearningPathways webpart

### ISSUE THREAD

**Issue by SJHCtrain** [pnp/custom-learning-office-365#129]
#### Category
- [x] Question
- [ ] Bug
- [ ] Content

#### Expected or Desired Behavior

If I have multiple LearningPathways webparts on my site, are they independent of each other?

I was hoping to tailor pages with different instances of the LearningPathways webpart. For example, I might just create a page devoted to Word and then edit the Playlist Administration to only show Word resources from Microsoft.

Currently I have two instances of the LearningPathways webpart on our site. When I edit one, it affects the other.

Can someone confirm if we can have multiple independant LearningPathways webparts, or only one webpart for the entire site.

**Comment by juliemturner** [comment]
@SJHCtrain  -- Playlist administration is to affect the overall configuration of the learning content available via the webpart. The webpart itself is configurable and can be place alone on a page or multiple instances can be added to a page and they can be tailored to display content in various different ways.  Please modify the administration section to show all content that could be relevant to your organization. Then create pages in your site (or in other sites -- you can add the M365 learning pathways app to any site collection in your tenant) and add the M365 learning pathways web part to those pages and edit the web part properties to customize what content is displayed. 

![image](https://user-images.githubusercontent.com/7570936/65636040-7e22ee00-dfaf-11e9-8787-ab16c0407294.png)

**Comment by SJHCtrain** [comment]
... so the **Playlist Administration** accessible  from **Home** > **Microsoft learning administration**
can be considered as the master list that controls, and overrides all content available to every other LearningPathways webpart on the site? Please let me know if I have this correct.

Thanks for the fasts response too Julie!

**Comment by juliemturner** [comment]
@SJHCtrain -- "overrides" is a strong word. It's the administration settings for the "viewer" web parts that can be added anywhere else on the site/tenant. The viewer web parts are really just filtered views of all the content the administrator has made available.

**Comment by juliemturner** [comment]
@SJHCtrain  -- You may want to watch this overview: https://youtu.be/S-QFDNRZkGE

**Comment by SJHCtrain** [comment]
Great answer!

**Comment by SJHCtrain** [comment]
Thanks Julie for taking the time to clarify my questions!
Craig
