### ISSUE TITLE
Webpart UX Feedback (MVP)

### ISSUE THREAD

**Issue by karuanag** [pnp/custom-learning-office-365#13]
From SMCollier in Teams MVP chat:  The only feedback I would say is whether the arrows for the next item in the lesson playlist aren't that obvious if you looking for the first time, will people miss that there's more than one page? Could that be made more clear, for example with a coachmark?

**Comment by peterjkrebs** [comment]
Thank you for the feedback. It's definitely something we're looking at for future releases. @StfBauer
