### ISSUE TITLE
Question: Catalog of all available trainings in the portal

### ISSUE THREAD

**Issue by Celestero** [pnp/custom-learning-office-365#130]
Is there a catalog that list all of the available trainings in the Learning Portal? I'd like to recommend specific trainings for a customer's custom playlist. It would be helpful to provide the customer direct links or recommend trainings I know are available within the portal.

#### Question 

- [X ] Question
- [ ] Bug
- [ ] Content

**Comment by juliemturner** [comment]
@Celestero  -- no, the best way to get a listing of all the playlists is to review the administration view... CustomLearningAdmin.aspx
