### ISSUE TITLE
Created custom playlist but content not shown

### ISSUE THREAD

**Issue by PriscillaWP** [pnp/custom-learning-office-365#131]
Created a custom playlist where playlist asset is pointing to the Microsoft websites (Eg https://products.office.com/en-my/business/microsoft-powerapps and https://docs.microsoft.com/en-us/office365/customlearning/) . Content is unable to display with the error below. HTML Field Security has been set to allow those domains.
![productofficecomblocked](https://user-images.githubusercontent.com/55975365/65860154-42679a00-e39c-11e9-8950-72d9fe1e4d2a.png)

products.office.com is blocked
products.office.com refused to connect.

ERR_BLOCKED_BY_RESPONSE

Is this a bug? How can I create a custom playlist to utilize other Microsoft website articles?

**Comment by juliemturner** [comment]
@PriscillaWP -- Sorry, unfortunately, products.office.com site does not allow their pages to be iFramed so we have no way of helping you link to that particular content. Currently, only support.office.com and docs.microsoft.com allow their content to be iFramed and even then you will need to append additional query string parameters to the end of the URL for it to be supported. In the case of
"support.office.com" that would be '?embed=true&ns=trainingservices&version=1'
and for 
"docs.microsoft.com" that would be '?context=context%2Fchromeless&linktarget=true'

**Comment by PriscillaWP** [comment]
Hi Julie,

               Thanks for your reply 😊 I have tried appending the ‘?context=context%2Fchromeless&linktarget=true'

               For example
               http://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq?context=context%2Fchromeless&linktarget=true

               Sorry for I still don’t get it working. What should I do? And where can I get the extension for each site? I would like to have custom playlist to point to linkedin too but it also disallow.

               Second question is, since MS learning pathways support custom playlist but it’s unable to load many sites to the created asset. May I know what can we do with custom playlist and what is it used mainly for? Thanks so much for your help.

Best Regards,

Priscilla Wong

**Comment by juliemturner** [comment]
@PriscillaWP -- So there are two issues... the first is that the URL must be https, not http... but the second is still that section of the documentation site is not allowed to be iFramed. We do not have authority over the content in docs so although I can look into it I cannot promise that I can get it changed to allow it.

**Comment by PriscillaWP** [comment]
Hi Julie,

               Thanks for your explanation. With this, may I know how do people normally use custom playlist? Appreciate your suggestions on this. Thanks.

Best Regards,
Priscilla Wong

Unless otherwise agreed in writing, all business is conducted in accordance with Wilhelmsen Ships Service Standard Terms and Conditions<https://www.wilhelmsen.com/terms-and-conditions/>

**Comment by juliemturner** [comment]
@PriscillaWP -- The intention for custom assets/playlists was for organizations that have their own training materials that they keep in SharePoint to be able to surface them either mixed with the content provided by Microsoft or as stand-alone playlists of content. You would do this by creating a SharePoint page, either in the same or a different site, then linking to that SharePoint page as an asset. As I'm assuming you know SharePoint pages are very rich canvases to combine content together to present to your consumers. By combining these assets together into a playlist, you can create your own internal training content, whatever that might be that would make sense for your organization.

**Comment by PriscillaWP** [comment]
Hi Julie,

               Thanks so much for your clarification. Now I see the usage. The only thing Is that if it could support the learning content at least directly from Microsoft will be even more beneficial. Wonder why MS doesn’t allow as those contents are open to public but restricted in the webpart.

Anyway, I am thankful to have you in this matter. Have a blessed day!

Best Regards,
Priscilla Wong




Unless otherwise agreed in writing, all business is conducted in accordance with Wilhelmsen Ships Service Standard Terms and Conditions<https://www.wilhelmsen.com/terms-and-conditions/>

**Comment by DarrellaaS** [comment]
Hi @juliemturner. The Stream landing pages in support.office.com direct to content that is stored in docs.microsoft.com. Who would we pass feedback onto so they create end-user content for the Stream product, within support.office.com? Ideally, all end-user content for M365 should be hosted in support.office.com, so it can be leveraged by Learning Pathways.

**Comment by juliemturner** [comment]
I don’t specifically work with the content so I cannot answer the question with authority but it’s my understanding Stream will be addressed on the next content update. Adding appropriate person.

**Comment by juliemturner** [comment]
Original question resolved
