### ISSUE TITLE
No way to restore a deleted playlist?

### ISSUE THREAD

**Issue by kyleg11** [pnp/custom-learning-office-365#133]
A playlist was accidentally deleted ...upon checking the trash under site contents, I see that it does not retain this information or any file (not sure the playlist makes a file). What is the process to restore other than re-creating all settings in the playlist?

**Comment by juliemturner** [comment]
@kyleg11 -- That's correct in the version of the webpart that's publically available we delete the item not recycle it so there is no way to restore it.  In the future version it will put the playlist in the recycle bin, so you will be able to restore it.

**Comment by juliemturner** [comment]
Deleted playlists will now show up in your site's recycle bin
