### ISSUE TITLE
Hide a custom playlist?

### ISSUE THREAD

**Issue by kyleg11** [pnp/custom-learning-office-365#134]
Developed a playlist and custom content and not ready to release it (need to hide), but it seems like only option is to delete? How do we setup in a current section but hide?

**Comment by juliemturner** [comment]
@kyleg11 - This is not a scenario we support currently. I can tag it as an enhancement request but cannot guarantee when/if it will make it onto the backlog.

**Comment by denzy134** [comment]
If you create the custom content in the backend you can hide it. That's a work around i used.

**Comment by FormerlyJelly** [comment]
Closing for lack of response or further requests; if additional assistance is required, please open a new Issue

**Comment by juliemturner** [comment]
This is an enhancement request and needs to remain open until Microsoft team has a chance to review and decide if the enhancement can be addressed.

**Comment by juliemturner** [comment]
Upon further review with the team, we are unable to see the value proposition in adding this feature. If you have a specific use case you're trying to address, which you believe this feature would assist with, please feel free to open a new issue and reference this one to ask for guidance on your scenario.
