### ISSUE TITLE
Wrong title on LearningPathways resources

### ISSUE THREAD

**Issue by SJHCtrain** [pnp/custom-learning-office-365#136]
While working to populate and configure our LearningPathways site, we've come across many mislabeled resources when building playlists.

One example: when searching for a OneNote resource, we selected **SharePoint OneNote Asset Page**, however, the entire playlist is dedicated to Outlook and categorizing emails.

How are these playlists vetted before they are available for us to use? Is there any way to ensure that what we select actually contains the content as labelled?

If you have any tips, that'd be great!

Take care,
Craig

**Comment by juliemturner** [comment]
@SJHCtrain -- No tips, I will pass along your feedback to the content crew who author the playlists.

**Comment by juliemturner** [comment]
Content refresh has gone out. Closing this issue, if you still have issues with the content please open a new issue.
