### ISSUE TITLE
Brainstorming question on expanding the functionality of LearningPathways

### ISSUE THREAD

**Issue by SJHCtrain** [pnp/custom-learning-office-365#138]
- [x] Question
- [ ] Bug
- [ ] Content

Thanks Julie for all your help! I'm not a SharePoint developer/designer/etc. I'm a trainer in a healthcare setting and LearningPathways is proving to be an invaluable tool as we prepare to launch 365.

However, I'm wondering if I can leverage LearningPathways to be a repository for our healthcare-related educational resources as well.

I'd like to take the idea of custom playlists and tailor them to medical content. Can I install a new LearningPathways site, turn off all MS resource linking via Playlist Administration, and then create new subcategories related to playlists? For example, create a subcategory for Nurses and then use the LearningPathways webpart to display clinical subcategories and playlists?

Or, can I just create a SharePoint Communications site and would it have webpart like the LearningPathways webpart for playlist creation and control?

Take care,
Craig

**Comment by juliemturner** [comment]
So the short answer is yes... based on what you imply your skillset is you may want to find some assistance building the pages, but in general you would build a bunch of pages in a SharePoint communication site (could be the one that has learning pathways in it now or another one) and then you would through the admin web part build probably at least 1 custom subcategory and a bunch of custom playlists where the assets for those playlists point to the SharePoint pages you create in either the same site collection or another one.  Then I would suspect you'd want to put at least 1 or more than one version of the web part on pages in the same  site collection where you created the pages and edit the properties to point to these custom subcategorie(s). 

For someone who understands SharePoint, this is a fairly straight forward process that you'd want to plan but would not be difficult.  If you have no real knowledge of creating pages in SharePoint you may want to find some help in your organization and/or do some research beforehand and/or find a consultant to help you build the content.

Some other community members can probably point you to other content but I know of Greg Zeflond -- aka SharePoint Maven who has a blog post about building a home page for an intranet, the upside is you can apply these learnings to building content pages. https://sharepointmaven.com/how-to-build-a-cool-intranet-landing-page-using-modern-page-experience-in-sharepoint/
