### ISSUE TITLE
Custom learning site provisioning failed

### ISSUE THREAD

**Issue by ManfredKochRBI** [pnp/custom-learning-office-365#14]
We did the provisioning procedure until the end 2 times. URL should be: https://rbinternational.sharepoint.com/sites/nwowlc but nothing is available. 
I got an error message "Access denied. You do not have permission to perform this action or access this resource." Details see below. I am a global admin in our tenant.

Unfortunately, your request to provision
"Custom learning for Office 365" 
template failed. 

Here is the exception that occurred:     Type =     System.Exception Message =     {"error":{"code":"-2147024891,     System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access     denied. You do not have permission to perform this action or access this     resource."}}} Source = OfficeDevPnP.Core TargetSite = Void MoveNext()     StackTrace = at     OfficeDevPnP.Core.ALM.AppManager.<BaseAddRequest>d__39.MoveNext() ---     End of stack trace from previous location where exception was thrown --- at     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at OfficeDevPnP.Core.ALM.AppManager.<AddAsync>d__5.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at OfficeDevPnP.Core.ALM.AppManager.Add(Byte[] file, String filename,     Boolean overwrite, AppCatalogScope scope, Int32 timeoutSeconds) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant     tenant, ProvisioningTenant provisioningTenant, FileConnectorBase connector,     TokenParser parser, PnPMonitoredScope scope,     ProvisioningTemplateApplyingInformation applyingInformation,     ProvisioningMessagesDelegate messagesDelegate) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser     parser, ProvisioningTemplateApplyingInformation applyingInformation) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation provisioningInfo) at     Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation applyingInformation) at     SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()     in     C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line     337 HResult = -2146233088 | Here is the exception that occurred:     Type =     System.Exception Message =     {"error":{"code":"-2147024891,     System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access     denied. You do not have permission to perform this action or access this     resource."}}} Source = OfficeDevPnP.Core TargetSite = Void MoveNext()     StackTrace = at     OfficeDevPnP.Core.ALM.AppManager.<BaseAddRequest>d__39.MoveNext() ---     End of stack trace from previous location where exception was thrown --- at     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at OfficeDevPnP.Core.ALM.AppManager.<AddAsync>d__5.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at OfficeDevPnP.Core.ALM.AppManager.Add(Byte[] file, String filename,     Boolean overwrite, AppCatalogScope scope, Int32 timeoutSeconds) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant     tenant, ProvisioningTenant provisioningTenant, FileConnectorBase connector,     TokenParser parser, PnPMonitoredScope scope,     ProvisioningTemplateApplyingInformation applyingInformation,     ProvisioningMessagesDelegate messagesDelegate) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser     parser, ProvisioningTemplateApplyingInformation applyingInformation) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation provisioningInfo) at     Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation applyingInformation) at     SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()     in     C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line     337 HResult = -2146233088
-- | --
Here is the exception that occurred:     Type =     System.Exception Message =     {"error":{"code":"-2147024891,     System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access     denied. You do not have permission to perform this action or access this     resource."}}} Source = OfficeDevPnP.Core TargetSite = Void MoveNext()     StackTrace = at     OfficeDevPnP.Core.ALM.AppManager.<BaseAddRequest>d__39.MoveNext() ---     End of stack trace from previous location where exception was thrown --- at     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at OfficeDevPnP.Core.ALM.AppManager.<AddAsync>d__5.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at OfficeDevPnP.Core.ALM.AppManager.Add(Byte[] file, String filename,     Boolean overwrite, AppCatalogScope scope, Int32 timeoutSeconds) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant     tenant, ProvisioningTenant provisioningTenant, FileConnectorBase connector,     TokenParser parser, PnPMonitoredScope scope,     ProvisioningTemplateApplyingInformation applyingInformation,     ProvisioningMessagesDelegate messagesDelegate) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser     parser, ProvisioningTemplateApplyingInformation applyingInformation) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation provisioningInfo) at     Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation applyingInformation) at     SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()     in     C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line     337 HResult = -2146233088

**Comment by JaredMatfess** [comment]
I'm having the exact same issue in my tenant.. Global Admin role set as well, so shouldn't be permissions related

**Comment by ManfredKochRBI** [comment]
Solution was: 
Turned out the global administrator logged into the SharePoint Provisioning Service hat no permission in the Site Collection App Catalog.
Once we added the permissions the provisioning worked.
