### ISSUE TITLE
No playlists display after editing a custom sub category

### ISSUE THREAD

**Issue by ian365** [pnp/custom-learning-office-365#141]
Hi, We have an issue where the web part displays the title and burger menu but below these is just a blank space without any playlists. I have added a custom subcategory and when the details of this are edited in CustomLearningAdmin.aspx it causes the issue.

The issue affects all the subcategories with none of the playlists displaying, not just the custom one that has been edited. A refresh of the CustomLearningAdmin.aspx page clears the issue. It has been seen in both Edge and IE11

**Comment by juliemturner** [comment]
First please validate that you have the most recent version of the web part by referring to the section of the ReadMe: https://github.com/pnp/custom-learning-office-365#current-release-version

**Comment by ian365** [comment]
We have now updated to the latest version and the issue seems to have been resolved. Thanks!
