### ISSUE TITLE
Update Office 365 product branding

### ISSUE THREAD

**Issue by stg365** [pnp/custom-learning-office-365#143]
Is there a way to update Office 365 product icons to the latest brand designs?
Might be an enhancement. Thanks.

https://fasttrack.microsoft.com/en-us/portal.html#/customer-dashboard/74320/resource/brandingkit

**Comment by juliemturner** [comment]
A content update will be forthcoming that will address icon updates, as well as a lot of other content issues. There is no way for you to override the content Microsoft delivers at this time.

**Comment by stg365** [comment]
Thanks Julie. Great news.
