### ISSUE TITLE
Multiple custom learning sites per Tenant

### ISSUE THREAD

**Issue by dankotsmith** [pnp/custom-learning-office-365#144]
- [X] Question
- [ ] Bug
- [ ] Content

#### Question / Expected or Desired Behavior

Can you create multiple custom learning sites per tenant?  We already had one site provisioned for Office365 Learning that the organization was using.  We just provisioned another site for non-O365 content, but when we did that it broke permissions on the initial site as far as the home page tile navigation.  

Thanks for your contribution! Sharing is caring.

**Comment by juliemturner** [comment]
You can only have 1 master learning site per tenant.  That site collection is where content is provisioned and administrated.  All users that you intend to view your content need to have view access to that site but they do not need to use it as their main learning site, although you can.  You can then use the learning pathways viewer web part in any other site collection and configure the web part to show all, or only a subset of content.  Please look for announcements about updates coming next week at Ignite.

Now that you've created a second site collection you've effectively taken control away from the original and it no longer serves up the content.  You can easily set it back but you will need to fix the tenant app property using powershell.  

If using PnP Powershell the command is:
`Set-PnPStorageEntity -Key MicrosoftCustomLearningSite -Value $clSite -Description "Custom Learning Site Collection"`

where $clSite is the url of the site collection you want to be the master.
