### ISSUE TITLE
Unable to retrieve metadata.json file from CDN

### ISSUE THREAD

**Issue by apeter48** [pnp/custom-learning-office-365#148]
#### Category

- [ ] Question
- [x] Bug
- [ ] Content

#### Question / Expected or Desired Behavior

The metadata.json file should load.

#### Observed Behavior

When loading the CustomLearningAdmin.aspx page for the first time, I receive the following error: 

> Microsoft 365 learning pathways has a configuration issue. Please see the browser console for detailed logs. For assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues. {CustomLearningAdminWebPart - TypeError: Cannot read property 'Categories' of undefined}

Looking at DevTools, the URL appears to be missing a slash after pathways. The request URL I get is https://pnp.github.io/custom-learning-office-365/learningpathwaysv3/metadata.json

#### Steps to Reproduce

Fresh install of Learning Pathways V3. Navigate to the CustomLearningAdmin.aspx page.

**Comment by plamber** [comment]
Can reproduce the issue on our tenant too. Using the version V3 and manual installation.

**Comment by juliemturner** [comment]
Can you verify how you provisioned it? I would like to correct the issue at the source.
The solution for this error is to run a line of PnP PowerShell:

Set-PnPStorageEntity -Key MicrosoftCustomLearningCdn -Value "https://pnp.github.io/custom-learning-office-365/learningpathways/" -Description "CDN source for Microsoft Content"

**Comment by apeter48** [comment]
I ran the M365IpConfirguration PS script.

I see on line 89 that it is missing the slash after pathways. I added the slash and reran the script and it works now.

**Comment by juliemturner** [comment]
Ok, the script has been fixed as well, just making sure you weren't using the provisioning service.
