### ISSUE TITLE
Please revisit M365lpConfiguration.ps1

### ISSUE THREAD

**Issue by plamber** [pnp/custom-learning-office-365#149]
#### Bug

- [ ] Question
- [x] Bug
- [ ] Content

#### Observed Behavior

Today I tried to manually install the package by using the [M365lpconfiguration.ps1](webpart/M365lpConfiguration.ps1) and failed since it connects to the wrong endpoints.

#### Steps to Reproduce

Just run the current version of the PowerShell. It will immediately fail with a SharePoint Online Administrator role and the necessary site collection admin permissions

**Comment by juliemturner** [comment]
Already fixed, but than you for your contribution.
