### ISSUE TITLE
Content stay in english in a french tenant

### ISSUE THREAD

**Issue by KevinTRELOHAN** [pnp/custom-learning-office-365#15]
I've installed the Custom learning for Office 365 portal but it stay in English language.  @karuanag

**Comment by SergePoint** [comment]
I have the same issue.   The Provisionning of the portal  language is English.  I switched my users favorite language to FR.  I opened the site with my user in FR,  Cirled in Blue in the attached image you can see the SharePoint action Menus are in FR.  The navigation menu are in English, I manually transtated a part of the navigation menu in FR, to test out (Circled In Yellow in the attached picture).  The content is also displayed in English (Circled in Red in attached email).  Is there a way to have the menus and content in FR.?
![Learning portal_LI](https://user-images.githubusercontent.com/12259535/54772777-5a788880-4bc5-11e9-9c76-1760e18a0fa2.jpg) thanks

**Comment by karuanag** [comment]
Validated solution navigation and chrome does not follow default language for Tenant or site collection.  Processing for further troubleshooting.

**Comment by KevinTRELOHAN** [comment]
Hello @karuanag any updates about this issue ? cc @SergePoint

**Comment by justin-lisi** [comment]
Hello,

We are currently working on multilingual support for the following languages and are looking to have this released for CY19 Q3 (French being among them):

Chinese (Simplified)
Dutch (Netherlands)
French
German
Italian (Italy)
Japanese (Japan)
Portuguese (Brazilian)
Russian (Russian)
Spanish

Please let us know if you have any other questions or concerns. Apologies for any inconvenience this may cause in the meantime. Thank you!

Regards,
Justin

**Comment by KevinTRELOHAN** [comment]
Oh great news Justin 😉


Kevin TRELOHAN
Consultant Freelance
Mobile. : 0611163281
Mél. :ktrelohan@dev-ds.fr<mailto:ktrelohan@dev-ds.fr>
Skype Entreprise : ktrelohan@dev-ds.fr<mailto:ktrelohan@dev-ds.fr>
[cid:cde47299-a641-4878-869a-b68fea980c90]

De : Justin Lisi <notifications@github.com>
Envoyé : mardi 28 mai 2019 14:00
À : pnp/custom-learning-office-365 <custom-learning-office-365@noreply.github.com>
Cc : Kevin TRELOHAN <ktrelohan@dev-ds.fr>; Author <author@noreply.github.com>
Objet : Re: [pnp/custom-learning-office-365] Content stay in english in a french tenant (#15)


Hello,

We are currently working on multilingual support for the following languages and are looking to have this released for CY19 Q3 (French being among them):

Chinese (Simplified)
Dutch (Netherlands)
French
German
Italian (Italy)
Japanese (Japan)
Portuguese (Brazilian)
Russian (Russian)
Spanish

Please let us know if you have any other questions or concerns. Apologies for any inconvenience this may cause in the meantime. Thank you!

Regards,
Justin

**Comment by SylvM1** [comment]
Dear Microsoft,

I saw on the Learning Pathways website that the new feature, multilingual support for the Dutch language (among aothers), is moved to Q4 2019. Because in a month's time, Q4 2019 will be over, can you give us the latest status? Do you plan on releasing this soon? My company is beginning the adoption of Office 365 so it would be great if this feature would be released soon, because then we can offer Learning Pathways in the native language (otherwise I will have to translate the lot). 

Thanks for letting me know.

Kind regards,

Sylvester

**Comment by emwes** [comment]
Could language be configurable? Or is there any plan for Swedish.... ?

**Comment by juliemturner** [comment]
If you have a desire to translate into your own language you could do so, but you'd have to maintain it yourself via a separate custom content pack.  I personally cannot answer if or when they might support Swedish.

**Comment by juliemturner** [comment]
This will be coming in the new Multilingual release of learning pathways. Look at the [Learning pathways Feature Updates](https://docs.microsoft.com/en-us/office365/customlearning/custom_featureupdates) and/or follow my [twitter](https://twitter.com/jfj1997) to keep up to date.
