### ISSUE TITLE
After installing M365LP version 3.0.0.0 our custom contents became hidden

### ISSUE THREAD

**Issue by pb03873** [pnp/custom-learning-office-365#151]
#### Category
- [ ] Question
- [x] Bug
- [ ] Content

#### Question / Expected or Desired Behavior
After installing M365LP version 3.0.0.0 our custom contents became hidden and some cannot be shown anymore.

#### Observed Behavior

All our custom contents (playlists and assets) lost their values for the "level" and "audience" fields.  

After retyping the values, most of them are visible again.  But some still remains hidden: 
- 1 whole custom playlist
- 2 custom assets added to a MS playlist (Microsoft Teams product)

For the custom assets, we deleted and recreated them => new items are now visible.
But by doing so I guess that the links to the underlying assets have changed => bad work-around.

Any idea how to make the custom playlist to appear again ?

**Comment by juliemturner** [comment]
This is a known bug that will be fixed as soon as possible. Basically the playlists "Level" and "Audience" fields are now required, which was an unintentional change. Because of this, the playlists that don't have those values set are not showing up.  If you set a value for them it will fix the problem.

**Comment by pb03873** [comment]
We had values before the upgrade but they were deleted when upgrading.
But real problem is than adding the value back does NOT solve the issue for all the item contents.
For most of them they show again but see my initial note: one whole playlist and two assets are no more showing up, even after retyping the values for the "level" and "audience" fields.

**Comment by juliemturner** [comment]
The recent version 3.0.1 release no longer requires audience and level for custom playlists.

With regard to your issue of some things are "not showing up" I need more detail to help you fix the issue. Not showing up where would be a good start. Can you see them in teh admin web part but not the viewer web part or they're not showing up in the admin web part either?

**Comment by juliemturner** [comment]
Closing issue due to lack of response.
