### ISSUE TITLE
permissions to edit, remove metadata

### ISSUE THREAD

**Issue by NaliTomar** [pnp/custom-learning-office-365#159]
- [x] Question
- [ ] Bug
- [ ] Content

One of the permissions requirements is to update and / or delete metadata. 
Should this be a concern that the install will overwrite, edit, or delete some custom metadata?

Thanks

**Comment by juliemturner** [comment]
I'm sorry but this question isn't specific enough for me to answer.  One of the "permission requirements"? Where?

**Comment by NaliTomar** [comment]
Thank you for the prompt reply. I have attached a snap shot of what I am referring to. 
Permissions requested -> This app would like to: -> Read and write managed metadata. Allow this app to read, create, update, and delete managed metadata...

![metadata](https://user-images.githubusercontent.com/27311121/69669800-687d8380-1047-11ea-955f-0cd4980d920b.PNG)

Thanks

**Comment by juliemturner** [comment]
Ok, well... this is the provisioning service that you're using then.  This is only appropriate if you have never installed learning pathways before or you don't have any customizations and you're ok with abandoning your existing learning pathways site. Given your question I'm going to guess that's not what you want. It won't delete any of your custom playlists and assets but they will no longer be available to learning pathways web part. To upgrade from version 2 of learning pathways you need to follow the update instructions here: https://github.com/pnp/custom-learning-office-365#updating-the-solution paying special attention to the version 3 upgrade notes.

**Comment by NaliTomar** [comment]
Ah, I think I understand. This is not referring to the tenant's custom metadata, as in the enterprise metadata hub for example? We have custom metadata navigation and more that we are publishing through that hub. 
I have not installed version 2 of the learning pathways. This is our first attempt.

**Comment by juliemturner** [comment]
Yes, it is but only if the solution your provisioning needs it, it's a blanket statement to support provisioning any of the templates the provisioning service utilizes, so it has all the permissions it needs to finish any of the deployments... this solution doesn't touch the metadata service. So if you have no existing version then using the provisioning service is a good way to go as it does all the work for you.

**Comment by NaliTomar** [comment]
Thanks for all your help. We have ran the installation and it looks great.
