### ISSUE TITLE
AAD permissions to be granted for solution

### ISSUE THREAD

**Issue by craigm26** [pnp/custom-learning-office-365#16]
I want to know exactly what resources AAD admin should grant to the user when consent to the application on behalf of the organization. After selecting "add to tenant", there isn't a display of what kind of resources it consent to. AAD admin needs to know what to grant before doing anything.

**Comment by juliemturner** [comment]
@craigm26 -- Your question needs to be directed at the PnP Provisioning team as all permissions needed are for that service not the custom learning solution itself. We use that service as a delivery mechanism and do not need AAD permissions to the tenant ourselves so I can't speak to it.  Please contact that team through this channel: https://github.com/SharePoint/sp-dev-docs/issues
