### ISSUE TITLE
CDN URL wrong after upgrading from 2.0.17.0 to 3.0.1.0

### ISSUE THREAD

**Issue by they007** [pnp/custom-learning-office-365#160]
#### Category
- [ ] Question
- [X] Bug
- [ ] Content

#### Question / Expected or Desired Behavior
> Upgrading from version 2.0.17.0 to 3.0.1.0 does not work correctly. 

#### Observed Behavior
The CDN URL changed and this breaks version 3 if you follow the upgrade steps only.
I was able to fix this by updating the CDN URL. The previous URL was 
"https://pnp.github.io/custom-learning-office-365/"
but the version 3 powershell sets it to:
"https://pnp.github.io/custom-learning-office-365/learningpathways/"
I manually used 
Set-PnPStorageEntity -Key MicrosoftCustomLearningCdn -Value "https://pnp.github.io/custom-learning-office-365/learningpathways/" -Description "CDN source for Microsoft Content"
to update the URL and fix the problem. 

The upgrade steps should include instructions on how to update the CDN URL.

#### Steps to Reproduce
Deploy version 2.0.17.0 and have it working.

follow update steps from github (summarized here)
Download version 3.0.1.0
Upload the sppkg file to the app catalog and deploy it.
go to the app in the site collection and view the details and click "get it" 

Try to browse the admin page. Receive an error.

**Comment by juliemturner** [comment]
If you were a very early adopter, the URL was "https://pnp.github.io/custom-learning-office-365/".  That was updated in June and the correct URL was "https://pnp.github.io/custom-learning-office-365/v2/". If you had that version, with v2/ in the URL then the upgrade works fine as described because the web part takes care of it for you. That said it's completely acceptable and even positive to update the CDN endpoint but not mandatory for those users. Given the lack of technical skills and access most users have, I have leaned towards not adding that step, but you are correct the PowerShell you ran fixes the issue. I will consider ways to update the documentation to point out the change if things are not working, but for the majority of users, the update works as described.

**Comment by they007** [comment]
I first deployed version 2.0.17.0 in October and it did not set the /v2 URL then. Looking back at the version history there is a check in that says "CDN URL Change" but the .ps1 in that version does not have /v2 appended and is what I used. I compared that version with the 3.0 version to find the correct URL today when troubleshooting. 
I think this is a link to that specific version: https://github.com/pnp/custom-learning-office-365/blob/edc2a92cfce49293a1562fcf880dda4fba3d0e1c/webpart/M365lpConfiguration.ps1

**Comment by juliemturner** [comment]
I'm sorry, but as you can clearly see from the link you sent me, the change for the CDN URL happened on June 27th... but it's absolutely irrelevant, the larger portion of installations use a CDN endpoint with v2/ on the end and version 3 of the web part corrects the URL for them if that's the case. You have clearly solved the problem but I do not want to confuse those that have a CDN endpoint with v2 by adding a step that's not necessary and that they may not be able to execute. I will, as I said, consider how I might add additional direction to help others that may have an older CDN version.

**Comment by they007** [comment]
Click the link and look at line 91. The comment on the check in says the CDN URL was updated, but on line 91 it does not contain /v2.

**Comment by juliemturner** [comment]
You are arguing the same point I'm making the change did not happen until June, 99.99% of installs have the v2/ url... I'm not going to issue a blanket statement for everyone to do something that <.01% of customers need to do.  I will, as I've said, look into updating the documentation to help those with an error correct the situation.

**Comment by they007** [comment]
I have each reviewed the installation .ps1 file and here are the URLs that I found. These were not what I was expecting based on your explanation so I fear I misunderstood your first post.

Commit | link | date | CDN URL (line 91 or 89 in later versions)
-- | -- | -- | --
Updates for renaming | [0582a70 ](https://github.com/pnp/custom-learning-office-365/blob/0582a70bcb27a5869d0470a4a35ca31399218694/webpart/M365lpConfiguration.ps1)| May 17 | https://pnp.github.io/custom-learning-office-365/v2/
Misnamed web part reference | [C96c4c1 ](https://github.com/pnp/custom-learning-office-365/blob/c96c4c123f2fed5506c56c785c195d1e377d3a68/webpart/M365lpConfiguration.ps1)| Jun 25 | https://pnp.github.io/custom-learning-office-365/v2/
Cdn url change | [421b770 ](https://github.com/pnp/custom-learning-office-365/blob/421b7704b14c01529fb939ac9715b0a4220127d2/webpart/M365lpConfiguration.ps1)| June 27 | https://pnp.github.io/custom-learning-office-365/
Pre-Ignite updates | [B450152 ](https://github.com/pnp/custom-learning-office-365/blob/b450152f29c0377b88932175c04aa86938577ba0/webpart/M365lpConfiguration.ps1)| Oct 25 | https://pnp.github.io/custom-learning-office-365/learningpathways
Missing end slash on cdn endpoint | [E2f8588 ](https://github.com/pnp/custom-learning-office-365/blob/e2f8588d299731f351a2264c5964b8482f2a12d6/webpart/M365lpConfiguration.ps1)| Nov 8 | https://pnp.github.io/custom-learning-office-365/learningpathways

When I installed in late October I used the 421b770 version of the PowerShell script, did not have /v2 at the end of my URL, and the upgrade to version 3 did not work. 
I do not have any idea what time frame would be considered early adopter or what version most people would have deployed. 
There may be very few people who are affected the way I was but if they're not technical enough to understand checking and updating the CDN URL then they may also not be technical enough to discover the fix the way I did so I hope they can find this thread and get it working again. I didn't do a very good job describing the behavior (like the exact error message) that I saw when the CDN URL was wrong so that may be unlikely they'll find this if they're searching for that error.
