### ISSUE TITLE
Multiple scroll bars displaying

### ISSUE THREAD

**Issue by ian365** [pnp/custom-learning-office-365#161]
- [ x] Bug
Since the v3 update scroll bars now display within the page because the length of the web part seems to be fixed. This means any long pages will have two scroll bars, one for the overall page, one in the nested web part. Please can this be resolved so that only one scroll bar displays

**Comment by juliemturner** [comment]
The size of the iFrame is set to the size of its internal content in the case of a support.office.com and a custom SharePoint page, however, docs.microsoft.com pages still do not support this setting so the iFrame height is set to 6000px.  In testing, where the iFrame size could be set, the scroll bars don't appear and we haven't found any problems with this, if you could provide more detail we can look into it further.

**Comment by ian365** [comment]
I have a custom page and playlist in the standard SharePoint subcategory, the white content bit is approx 2300px height. When we had the previous version v2 I remember seeing scroll bars display whilst all the page content was loading, then once fully loaded they would disappear. In v3 they seem to stay, same in both Chrome and Edge, see below.

![multi scroll bars](https://user-images.githubusercontent.com/56627514/70151157-17067180-16a3-11ea-96fd-16663673ff8c.gif)


For info the standard page for Yammer on https://support.office.com/ displays normally with just the one scroll bar but does cut off the last step,
![normal scrol](https://user-images.githubusercontent.com/56627514/70152767-b6c4ff00-16a5-11ea-8aa4-b92adee2aaa1.png)

**Comment by juliemturner** [comment]
Does the custom page by chance have multiple columns? There is a bug with this because the reported size of the page is incorrect on load until the page in the iFrame has a chance to respond to the width of the frame it's in.  This is an unfortunate side effect of how Microsoft has designed responsiveness into their pages and we are looking into ways we can handle this with as little overhead to the page performance as possible.

**Comment by ian365** [comment]
So, yes it did have columns, but i have now removed them so the page is sections of text, images and stream video and refreshed custom admin. The updated page pulls through but the double scrolls still remain.
