### ISSUE TITLE
Nested menu bar in all pages

### ISSUE THREAD

**Issue by ian365** [pnp/custom-learning-office-365#162]
- [x ] Bug
A menu bar (of a hub site) displays nested within all of the web part pages. Please can this be resolved as its confusing users. Currently using V3

**Comment by juliemturner** [comment]
I cannot replicate this issue. Here is a custom asset that is part of a hub site:

![image](https://user-images.githubusercontent.com/7570936/70075236-590fb480-15ca-11ea-82cf-a4e13e674481.png)

That page used as a custom asset in a custom playlists:

![image](https://user-images.githubusercontent.com/7570936/70075266-69c02a80-15ca-11ea-8930-91f5da2b0cd2.png)

Not the hub site menu is not displayed, nor is the header of the page.

**Comment by ian365** [comment]
Hi Julie,
So taking the example of a standard sub category with a custom playlist. When a page is loaded in the playlist the title of the page gets hidden and the nested menu displays, its does hide when I resize the page but its there otherwise. see attached, same in Chrome and Edge.

![nested menu](https://user-images.githubusercontent.com/56627514/70142452-2bda0980-1691-11ea-8165-d1e870c41938.gif)

**Comment by juliemturner** [comment]
Ok, I was able to replicate this in a web part on a normal page verses a single app part page and have created a fix that I will release as soon as I can.
