### ISSUE TITLE
[BUG] Minor error in working of out date solution

### ISSUE THREAD

**Issue by pkbullock** [pnp/custom-learning-office-365#168]
**Describe the bug**
Just a small working of out of date phrasing, in the admin centre for the solution. See screenshot.

![Minor wording error](https://user-images.githubusercontent.com/8781041/71092073-7170f900-219e-11ea-9da5-dec82b62f120.png)

**Learning Pathways version number:**
3.0.0

Is contribution going to open, i felt i could have just done a quick PR for this?

**Comment by juliemturner** [comment]
Thanks, I'll update it.  I can't comment on open-sourcing the source code.

**Comment by pkbullock** [comment]
Fair enough, great solution btw, will be looking into injecting into deployed portals some preselected content, do you have any guidance on this? If not no worries, just shortcut the research time.

**Comment by juliemturner** [comment]
So this is really a new issue, as a question that would be ideal if you could submit a new "question" issue with a little more detail as what you're asking isn't clear... define "deployed portal" and what you mean by "inject" and which content, content from learning pathways or your own content or some other 3rd party content.

**Comment by pkbullock** [comment]
Yeap sure, just though the same after my comment, will move to new thread.

**Comment by pkbullock** [comment]
In relation to the out of date message, it appears the provisioning service (lookbook.microsoft.com) doesn't provision the latest version e.g. provisions 3.0.0 when 3.0.2 is shown as latest. Is there a change log for the updates?

**Comment by pkbullock** [comment]
Ignore above i found it 🤦‍♂️

**Comment by juliemturner** [comment]
Fixed in version 3.0.1
