### ISSUE TITLE
Adding youtube video asset

### ISSUE THREAD

**Issue by SergePoint** [pnp/custom-learning-office-365#17]
Hi when I add a new asset that points to a youtube video URL, I get an error that content cannot be shown in frame.  If instead I create a new asset page(instead of url) and add the same url from youtube to embed the video in the new page, then the new assets works.  Any idea why? thanks

**Comment by juliemturner** [comment]
That behavior is by design. All custom assets need to be SharePoint pages, then you can embed whatever you like in them.
