### ISSUE TITLE
Rendering issue with multiple web parts on a page

### ISSUE THREAD

**Issue by 216rick** [pnp/custom-learning-office-365#171]
Steps to reproduce:

1. Create a new SharePoint page.
2. Add a Learning Pathways web part to a page and configure to display a specific playlist.
3. Add a second web part to the page and configure to display a Sub-Category.
4. Save the page.
5. Observe the height of the 2 web parts on the page - there is no extra space at the bottom of either web part..
6. Select a playlist in the second web part.

Expected: Height of the first web part remains the same.

Actual: Height of the first web part increases.

**Comment by juliemturner** [comment]
So I can only partially respond to this issue.  

With regards to #5, the spacing between the web parts, there is actually 24px of space between them which felt like enough but I'll discuss this issue with the designer to see if there is a different recommendation. 

With regard to your resizing web part issue this is an issue with support.office.com and the messaging service they are using to report the size of the content to the parent frame. For some reason that service is broken (and returning a height that's too tall) but learning pathways has no other way to get the height of the iFramed content so we're stuck until they fix it. And when they do this will just start working.

**Comment by dborchers-gc** [comment]
Hey Julie, 

do you know if there is any update with this bug in the support.office.com Site?

> With regard to your resizing web part issue this is an issue with support.office.com and the messaging service they are using to report the size of the content to the parent frame. For some reason that service is broken (and returning a height that's too tall) but learning pathways has no other way to get the height of the iFramed content so we're stuck until they fix it. And when they do this will just start working.

**Comment by juliemturner** [comment]
Unfortunately, no, they still have not fixed the bug. When there is one, I will update this issue with the fix being available and close it.

**Comment by FormerlyJelly** [comment]
Bugs / callouts within this thread are being actively worked and revisions exist to take care of the errant behavior. Documentation and further fixes of the UI continue. Closing for these reasons; if additional assistance is required, please open a new Issue

**Comment by juliemturner** [comment]
We will keep this open until the bug has been fixed on the support.office.com site.

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
