### ISSUE TITLE
Learning Pathways failing after duplicate installs

### ISSUE THREAD

**Issue by SorenPedersen** [pnp/custom-learning-office-365#172]
**What is the context of your question?**
- [ ] Installation
- [X] Administration
- [ ] Custom Content
- [ ] M365 learning pathways web part

**What is your question?**
We had one installation of Learning Pathways and it seemed to work. Another one was installed by a different admin. It was then deleted (the Site Collection), but now the original one is failing:
_Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.]_

How can we fix this?

**Provide related screen-shots to help us understand your question**

**Comment by juliemturner** [comment]
You can only have one instance of learning pathways per tenant.  So what effectively happened is that the second admin to install learning pathways took over as the home for learning pathways in your tenant and then when they deleted the site collection effectively abandoned learning pathways without a home.  You can fix it by running a PowerShell command to update the tenant app property to point to your old learning pathways site collection:

This is the command, where $clSite is the URL to the site collection you want to have as the home to learning pathways, from your message it looks like that would be the first one you provisioned.

Set-PnPStorageEntity -Key MicrosoftCustomLearningSite -Value $clSite -Description "Microsoft 365 learning pathways Site Collection"

**Comment by SorenPedersen** [comment]
That fixed it. Thanks!
