### ISSUE TITLE
Custom playlists - valid URLs

### ISSUE THREAD

**Issue by 67nmark** [pnp/custom-learning-office-365#173]
Hello, I am trying to understand why I cannot use some URLs as playlist assets. I need to be able to reference a number of https page URLs within a custom playlist. 
![learning-pathways-issue](https://user-images.githubusercontent.com/16998499/71648718-972bff80-2d53-11ea-82d0-4bb06bb6ffc7.png)
If I use https://www.bbc.com/ as the URL then the bbc homepage loads as expected. If I use https://www.google.com/maps/ then I get a grey box with a sad face/refused to connect icon at the center of the grey box. Most https URLs do not display. The behaviour described is the Chrome experience.
I'd be grateful if someone could confirm the expected behaviour and if there's anything I can do to make any https URL display.
Cheers,
Mark

**Comment by juliemturner** [comment]
Many websites don't allow their content to be iFramed.  This is not an issue with learning pathways but an issue with the site you are trying to link to.  So this isn't going to be something we can give you a definitive answer on as it's going to be a case by case basis.  That said we encourage you to create SharePoint pages for each of your assets instead, that way you can use embed code and other SharePoint web parts to build your content and then we can properly size the frame to the content. If you paste URLs to other sites we will default the height of the frame to 6000px which is likely to be too big, but could also be too small in certain cases.

**Comment by 67nmark** [comment]
Hi @juliemturner - thanks for the reply. I guess the problem we face is the we have a load of training material that is specific to our organisation that is stored on an on-prem SharePoint server (and we link out to a number of other sites directly as well). I am creating playlists that utilise resources from all of the place, so the resources that I display must appear on the page as part of the playlist - they cannot be links.

What I need to be able to do is use a classic page viewer web part. I believe I have a workaround - I have created a classic team site in our O365 tenant, then I'm building classic pages, inserting the page viewer web part and pointing to the on-prem pages. 

It's a little clunky but it allows me to stay within the playlist - I would be really appreciative if you have any insight on how I can insert a page viewer web part into a modern site.

Cheers,
Mark

**Comment by juliemturner** [comment]
Unfortunately, I do not know of a workaround for modern pages.

**Comment by 67nmark** [comment]
No probs - thanks for your assistance
