### ISSUE TITLE
Copy Link in custom content pack, takes you to a page referencing default pack

### ISSUE THREAD

**Issue by pkbullock** [pnp/custom-learning-office-365#174]
When using a custom content pack, the content shows as expected. 

When using the copy link function and loading into a separate window, the content doesn't load. The link refers to a page where the web part references the default content pack. I cannot see a setting to change this specifically for the custom content pack or cannot alter the link as an admin to specify an alternative page. 

**To Reproduce**

![83DEEB27-94A8-4386-8B09-15A3DF4E22F2](https://user-images.githubusercontent.com/8781041/71848493-823ecb80-30c7-11ea-990c-ae22c0c9c4c9.GIF)

**Expected behavior**
Either an alternative page for custom content packs or some setting introduced to point to a custom page for the copy link feature, or URL parameter for the content pack.

**Screenshots**
If applicable, add screenshots to help explain your problem. See Gif, if too blocky, i can provide full res video.

**Learning Pathways version number:**
3.0.3 

**Additional context**

URL generated in content link: https://capadevtest.sharepoint.com/sites/LearningPortal/SitePages/CustomLearningViewer.aspx?playlist=a8cbac83-f7e8-45ff-a4a6-6b04f31a5745&asset=28dad67b-adb8-4df5-822b-677d81968eda

**Comment by juliemturner** [comment]
Should be fixed with drop 3.0.3.
