### ISSUE TITLE
Will the source code be made available soon?

### ISSUE THREAD

**Issue by LukeBCI** [pnp/custom-learning-office-365#175]
- [ ] Installation
- [ ] Administration
- [ ] Custom Content
- [x] M365 learning pathways web part

As title asks, I understand that the source code was questioned back in May 2019, however I was curious to the status of the release of the source code as it's marked as an open source project?

Kind regards,
Luke

**Comment by juliemturner** [comment]
It’s my understanding that it is the intent to have the code become available, however I have no ability to give you a timeline and I don’t know if it will be source open or open source.

**Comment by russgove** [comment]
yeah, same question here. was hoping to install this for my employer but I want to see the source first.

**Comment by juliemturner** [comment]
Source code is now available.
