### ISSUE TITLE
[ENHANCEMENT] Ability to connect Office.com Tenant to Learning Pathways SharePoint Site

### ISSUE THREAD

**Issue by pb762** [pnp/custom-learning-office-365#177]
**Is your feature request related to a problem? Please describe.**
There is some concern that Office.com homepage is not connected to the learning Pathways page and it would be better if there is a one stop shop to all Office 365 needs. 

**Describe the solution you'd like**
Ability to configure Learning pathways SharePoint site to Office.com. This will show as a Tab or Tile on the homepage of Office.com. This should be able to be configured for the specific tenant.

**Describe alternatives you've considered**
Learning Pathways site as the starting point to link to Office.com. This is not effective since Office.com does  a better job of personalizing the user's experience and also has Tips/Tricks on Office.com website. So it may be better to link learning pathways in Office.com

**Additional context**
Is there already a workaround for this?

**Comment by juliemturner** [comment]
Office.com content is either apps or documents.  Microsoft 365 learning pathways is a SharePoint customization that is expressed via a SharePoint Communication site and doesn't fit either of those contexts so it's not even possible to bring it to that level.  I think the best you might be able to do is make it a featured link to the Communication site on SharePoint home.

**Comment by juliemturner** [comment]
I asked some other smart people and apparently you can add any app that you want to the app launcher bar... I tried it out but I didn't work for me, maybe you'll have more luck. https://docs.microsoft.com/en-us/office365/admin/manage/customize-the-app-launcher?view=o365-worldwide

**Comment by pb762** [comment]
Thank you. I will contact our Tenant Admin and see if he can do it as I believe this will need to be managed at the Tenant level.

**Comment by juliemturner** [comment]
You're correct. After a bit the app I created did show up, but be advised that it's in "all apps" and there is no way to make it pinned for everyone they'll have to find it and pin it themselves.
