### ISSUE TITLE
[BUG] Learning Pathways Administration page error

### ISSUE THREAD

**Issue by TickoBoston** [pnp/custom-learning-office-365#184]
**Describe the bug**
Learning Pathways Administration page's body is blank with the following error:

> Microsoft 365 learning pathways has a configuration issue. Please see the browser console for detailed logs. For assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.

**To Reproduce**
1. Go to Tenant's Learning Pathways site
2. Click on **Get Started with the Admin Success Center** button
3. Click on **Learning Pathways Administration** 

Error occurs in Edge, IE and mobile device.

**Expected behavior**
See the Pathways administration page.

**Screenshots**
![Pathways Admin Error 01](https://user-images.githubusercontent.com/13697069/72171859-ccfb6480-33a1-11ea-9989-1dbefe04d5fb.png)

**Learning Pathways version number:**
Updated to 3.0.3.0
Previously 3.0.0.0 generated same error

**Additional context**
- Provisioned using the MS provisioning tool
- Replaced CustomConfig and navigated to admin page. The newly generated list did not fix the issue

**Error Log Files**
[LearningPathwaysErrors-ConsoleLog.txt](https://github.com/pnp/custom-learning-office-365/files/4046772/LearningPathwaysErrors-ConsoleLog.txt) -Filtered for errors only
[LearningPathwaysErrors-NetworkLog.txt](https://github.com/pnp/custom-learning-office-365/files/4046773/LearningPathwaysErrors-NetworkLog.txt)

Thank you!

**Comment by juliemturner** [comment]
Based on the console log something in your network or proxy seems to be blocking you from downloading files from github pages.  You need to be able to download files from that base CDN path (https://pnp.github.io/custom-learning-office-365/learningpathways/v3/), specifically metadata.json, playlists.json, and assets.json. Unfortunately, this isn't something I can really help you with.

**Comment by TickoBoston** [comment]
Thank you,
When I attempt to navigate to [https://pnp.github.io/custom-learning-office-365/learningpathways/v3/](https://pnp.github.io/custom-learning-office-365/learningpathways/v3/) I receive a TLS error:

> Can’t connect securely to this page
> This might be because the site uses outdated or unsafe TLS security settings

Thanks again for your input.

**Comment by juliemturner** [comment]
That's because that's not a valid endpoint so you can't browse to it.  The path to the files are:
https://pnp.github.io/custom-learning-office-365/learningpathways/v3/metadata.json
https://pnp.github.io/custom-learning-office-365/learningpathways/v3/playlists.json
https://pnp.github.io/custom-learning-office-365/learningpathways/v3/assets.json

**Comment by TickoBoston** [comment]
Running the UpdateM365lpCDN.ps1 script fixed the issues. It seems that the provisioning service has the old CDNs.
Thank you Julie, I appreciate the assist.
