### ISSUE TITLE
[QUESTION] Is it possible to add cutom Technologies for use in custom content

### ISSUE THREAD

**Issue by TickoBoston** [pnp/custom-learning-office-365#185]
**What is the context of your question?**
- [ ] Installation
- [ ] Administration
- [x] Custom Content
- [ ] M365 learning pathways web part

**What is your question?**
Is it possible to create custom **Technologies** in order to categorize content specific to the organization, such as applications that we use. Examples would be TFS, Visual Studio, SalesForce, etc.?

**Comment by juliemturner** [comment]
No, we do not have a concept of custom technologies, but at the same time, there really is no use for having it as it doesn't manifest itself in any way other than to limit what is visible to the entire audience of learning pathways. If you want to make custom content for those topics then I would at them as custom subcategories.

Another option is to develop your own content set using the Custom Content Pack option available in version 3. This is a significantly more advanced option but you can see information about doing it in the [PnP demo](https://www.youtube.com/watch?v=-sLXl_rKGxQ) I did in December as well as see the [documentation ](https://docs.microsoft.com/en-us/office365/customlearning/custom_partnerguide_contint)

**Comment by TickoBoston** [comment]
Thank you Julie!
