### ISSUE TITLE
[QUESTION] Is it possible to restrict content by audience?

### ISSUE THREAD

**Issue by TickoBoston** [pnp/custom-learning-office-365#186]
**What is the context of your question?**
- [ ] Installation
- [x] Administration
- [ ] Custom Content
- [ ] M365 learning pathways web part

**What is your question?**
Is it possible to restrict playlists and content based on user login and/or audiences based on O3665 or AD groups? Examples would be targeted content for IT, HR, Compliance, etc.
If not, will it ever be possible?

Thank you

**Comment by juliemturner** [comment]
No, that is not currently possible.  I suspect you're looking for the concept of audience targeting and in this case, I think the more appropriate way to handle that would be by the use of sites/pages customized with the learning pathways web part filtered to show content only for certain sub-categories/playlists and then curated to those audiences.

**Comment by TickoBoston** [comment]
Thank you Julie!
