### ISSUE TITLE
Unable to access the CustomConfig list to add JSON 

### ISSUE THREAD

**Issue by ruenells** [pnp/custom-learning-office-365#188]
I am trying to add some JSON and unable to see the list is this locked down?  I am a tenant admin.

**Comment by juliemturner** [comment]
The CustomConfig list will be in the M365 learning pathways main site, where you would access the admin web part.  If that list doesn't exist then the solution won't work and yes, it's completely accessible to everyone as it has to be.

**Comment by ruenells** [comment]
> The CustomConfig list will be in the M365 learning pathways main site, where you would access the admin web part. If that list doesn't exist then the solution won't work and yes, it's completely accessible to everyone as it has to be.

When I go to site content and try to open the list it doesnt work, you are saying we access it a different way?
