### ISSUE TITLE
[ENHANCEMENT] 

### ISSUE THREAD

**Issue by johnravas** [pnp/custom-learning-office-365#189]
We have just installed Learning Pathways in our tenant.  We love the flexibility of adding custom content and playlists.  We are already starting to create our own.

We would like to be able to customize an existing sub-category, such as the one for Microsoft Teams.  We would like to be able to hide content that is not relevant to our usage as well as add content.

The one thing that we found is that we cannot re-order the playlists within a particular sub category.  We can reorder the playlist assets within a playlist, but not the playlists themselves.  Am I missing the option on the screen?

If it is not available, could this be added?

**Comment by JudiP53** [comment]
We are asking the same question.  I posted a comment in uservoice yesterday. Please go there and vote for this enhancement!
https://m365adoption.uservoice.com/forums/913429-adoption-and-training-content/filters/new

**Comment by juliemturner** [comment]
Dup #96

No, you currently cannot reorder the playlists in a sub-category.
