### ISSUE TITLE
Products images not showing depending on user

### ISSUE THREAD

**Issue by garyfrostncc** [pnp/custom-learning-office-365#191]
For certain users, on the Product page the images are not showing. The only images that these users can see are the one created within custom playlists.

The only difference between users that can and cannot see the images is that those that can't are in the sharepoint visitors group directly (e.g Sally Boote & Anthony Severn) whereas those that can see the images are in a o365 group (Core ICT Service Members) in the sharepoint visitors group.

![visitors group](https://user-images.githubusercontent.com/60133999/72800988-73682500-3c40-11ea-896c-b35562f228f7.JPG)
![missing product icons](https://user-images.githubusercontent.com/60133999/72801005-7cf18d00-3c40-11ea-8649-c2b5f1c60a51.png)

**Comment by garyfrostncc** [comment]
Thanks for the update. Our firewall blocks github for anyone outside ICT. The users that do not get the icons are those outside ICT.

Our security team are not willing to open up github for all the company and the firewall cannot be configured to just allow the path that the icons are located.

Can I request a change that the icons be located elsewhere on a non-github location?

**Comment by juliemturner** [comment]
If that's the case, then you actually have a bigger problem than you realize in that every 24h it would try and refresh the manifests for any new content.  If no users in the ICT group access the solution that refresh is going to fail too, so the entire solution is really not going to work for you. 

Long story short, at this time there's really no way I can accommodate you as this is the configured source for the manifests and icons. I suppose there is some chance that will change at some point in the future but currently, there are no plans to fund a more formal CDN.

**Comment by juliemturner** [comment]
It occurs to me that if you have a way to host a CDN endpoint yourself you could clone the repo and upload the docs folder to your own CDN and then add an additional custom content pack pointing at your CDN.  That would then allow you to get around the restriction, however, you would have to update the content yourself... not a terribly difficult thing as you could get alerts from the repo about updates.
