### ISSUE TITLE
Custom Content Packs, Categories, etc.

### ISSUE THREAD

**Issue by jeffwllms** [pnp/custom-learning-office-365#193]
**What is the context of your question?**
- [ ] Installation
- [ ] Administration
- [x] Custom Content
- [ ] M365 learning pathways web part

**What is your question?**
Is there any information or documentation on creating/adding/using custom content packs? Or is there a way to add additional categories (not subcategories) and/or technologies?

**Comment by juliemturner** [comment]
You are correct, there is no way to add custom categories or technologies... as you allude to we will be encouraging people to create their own custom content packs if they require that level of customization. As I see it, the code for merging the provided content with custom content at a certain point becomes too complex and brittle to be reliable.

The documentation on the manifests themselves can be found here: [Partner integration models](https://docs.microsoft.com/en-us/office365/customlearning/custom_partnerguide_contint)

The goal is basically to build your own CDN and find a place to host it.  You can follow the learning pathways model and simply create a GitHub repo with GitHub pages enabled or you can do something more formal. I give a demo of building one using GitHub pages on this [PnP Community Call](https://www.youtube.com/watch?v=-sLXl_rKGxQ).

**Comment by jeffwllms** [comment]
I believe this is what I am looking for.  I will be able to just keep all the corporate training looking the same utilizing this.  Thanks so much.
