### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by denzy134** [pnp/custom-learning-office-365#194]
**What is the context of your question?**

- [ ] Custom Content
- [ ] M365 learning pathways web part

**What is your question?**
Is there a way to add a picture or a logo to new products we add as sub categories which are not part of the learning pathways but products our organizations use.

**Provide related screen-shots to help us understand your question**
<img width="158" alt="issue" src="https://user-images.githubusercontent.com/35541187/73023871-9c77e980-3de9-11ea-849f-c0d7d0804248.PNG">

**Comment by juliemturner** [comment]
Duplicate #55 - please review this enhancement request. You can edit the json directly but currently no way to do this through the UI
