### ISSUE TITLE
OneDrive QuickStart Playlist - Duplicate Assets

### ISSUE THREAD

**Issue by newgardj** [pnp/custom-learning-office-365#195]
Both **Work on the go** and **Stay connected with OneDrive** assets show the same content and are the last two items in the playlist. Since both items are directly next to each other within the playlist, they are redundant and one should be removed.

![image](https://user-images.githubusercontent.com/34944901/73411451-a22a6f00-42c2-11ea-8cd9-4bf4f284f5a2.png)

![image](https://user-images.githubusercontent.com/34944901/73411458-a5bdf600-42c2-11ea-84d2-cc926f1d778f.png)

**Comment by juliemturner** [comment]
If you look without the query string parameters, these pages are actually different so I don't think this is a learning pathways bug but more of an issue with support.office.com.  I'm going to close it.
