### ISSUE TITLE
Users can't access the Microsoft 365 learning pathways web part

### ISSUE THREAD

**Issue by mtn303** [pnp/custom-learning-office-365#196]
After adding users to the Microsoft 365 learning pathways site, they are not able to see the content in the Microsoft 365 learning pathways web part.
The users gets the following error: 'Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.]
See error in Screenshot:
![M365LPerror](https://user-images.githubusercontent.com/60468954/73447551-4530c680-435f-11ea-8251-aa4a09482ce2.PNG)

Learning Pathways version number:
3.0.3.0

Note: Site Collection administrators are able to use the Microsoft 365 learning pathways web part

**Comment by juliemturner** [comment]
Did you review any errors in the browsers console log as the message indicates? It’s hard to help without that information. That said based purely on your description it feels like you haven’t added the users to the viewers group of the learning pathways site. Basically I’m speculating that they don’t have permissions to the content so the web part is failing to load it, but the console logs should help diagnose that.

**Comment by mtn303** [comment]
FYI, users are added to viewers group.

Here are the errors from the browsers console log:
Message: Error making HttpClient request in queryable [404]  ::> {"odata.error":{"code":"-1, System.ArgumentException","message":{"lang":"da-DK","value":"Listen 'CustomConfig' findes ikke p\u00e5 webstedet med URL-adressen 'https://aarhusuniversitet.sharepoint.com/sites/O365Learning'."}}} Data: {"response":{},"status":404,"statusText":"","isHttpRequestError":true}
custom-learning-web-part_f0430b908c40c0539f72fc0b8452d554.js (26,1867)

 Message: Error: Error making HttpClient request in queryable [404]  ::> {"odata.error":{"code":"-1, System.ArgumentException","message":{"lang":"da-DK","value":"Listen 'CustomConfig' findes ikke p\u00e5 webstedet med URL-adressen 'https://aarhusuniversitet.sharepoint.com/sites/O365Learning'."}}} - DataService (getCustomConfig)
custom-learning-web-part_f0430b908c40c0539f72fc0b8452d554.js (26,1867)

 HTTP404: IKKE FUNDET - Serveren har ikke fundet noget, der svarer til den ønskede URI (Uniform Resource Identifier).
(Fetch)GET - https://aarhusuniversitet.sharepoint.com/sites/O365Learning/_api/web/lists/getByTitle('CustomConfig')/items?$select=Id,Title,JSONData&$orderby=Id desc&$filter=(Title eq 'CustomConfig') and (CDN eq 'Default')&$top=1

 Key quickActions.screenReader does not exist in string map
chunk.vendors~sp-pages-search_be90b940be967f3d6253.js (1,381292)

 Key quickActions.suggestion does not exist in string map
chunk.vendors~sp-pages-search_be90b940be967f3d6253.js (1,381292)

 Message: Error making HttpClient request in queryable [404]  ::> {"odata.error":{"code":"-1, System.ArgumentException","message":{"lang":"da-DK","value":"Listen 'CustomConfig' findes ikke p\u00e5 webstedet med URL-adressen 'https://aarhusuniversitet.sharepoint.com/sites/O365Learning'."}}} Data: {"response":{},"status":404,"statusText":"","isHttpRequestError":true}
custom-learning-web-part_f0430b908c40c0539f72fc0b8452d554.js (26,1867)

 Message: Error: Error making HttpClient request in queryable [404]  ::> {"odata.error":{"code":"-1, System.ArgumentException","message":{"lang":"da-DK","value":"Listen 'CustomConfig' findes ikke p\u00e5 webstedet med URL-adressen 'https://aarhusuniversitet.sharepoint.com/sites/O365Learning'."}}} - DataService (getCustomCDN)
custom-learning-web-part_f0430b908c40c0539f72fc0b8452d554.js (26,1867)

 HTTP404: IKKE FUNDET - Serveren har ikke fundet noget, der svarer til den ønskede URI (Uniform Resource Identifier).
(Fetch)GET - https://aarhusuniversitet.sharepoint.com/sites/O365Learning/_api/web/lists/getByTitle('CustomConfig')/items?$select=Id,Title,JSONData&$filter=Title eq 'CustomCDN'&$top=1

 Message: Error making HttpClient request in queryable [404]  ::> {"odata.error":{"code":"-1, System.ArgumentException","message":{"lang":"da-DK","value":"Listen 'CustomConfig' findes ikke p\u00e5 webstedet med URL-adressen 'https://aarhusuniversitet.sharepoint.com/sites/O365Learning'."}}} Data: {"response":{},"status":404,"statusText":"","isHttpRequestError":true}
custom-learning-web-part_f0430b908c40c0539f72fc0b8452d554.js (26,1867)

 Message: ConfigService (validateConfig) -- User does not have appropriate rights to create custom config list.
custom-learning-web-part_f0430b908c40c0539f72fc0b8452d554.js (26,1867)

 HTTP404: IKKE FUNDET - Serveren har ikke fundet noget, der svarer til den ønskede URI (Uniform Resource Identifier).
(Fetch)GET - https://aarhusuniversitet.sharepoint.com/sites/O365Learning/_api/web/lists/getByTitle('CustomConfig')/fields?$select=Title&$filter=Title eq 'JSONData'

 SEC7120: [CORS] Kilden 'https://aarhusuniversitet.sharepoint.com' fandt ikke 'https://aarhusuniversitet.sharepoint.com' i response header Access-Control-Allow-Origin for -ressourcen fra cross-origin på 'https://waconatm.officeapps.live.com/apc/trans.gif?5bac9a5dfab491f1a0d1bd5284be7b54'.

**Comment by juliemturner** [comment]
So that error implies that there is no list item in your CustomConfig table with the title CustomConfig and the CDN equal to Default. So, this feels like you have a much bigger issue.  Did you upgrade from v2 to v3 or is this a new v3 install?

**Comment by mtn303** [comment]
I can confirm there is a list item with the title CustomConfig and CDN is set to default.
It is a new v3 installation.

**Comment by mtn303** [comment]
Permissions on the CustomConfig table was broken. I set it to en-heritage permissions, and it fixed the issue!

**Comment by juliemturner** [comment]
Ok sounds like you found the issue, glad you’re all set.
