### ISSUE TITLE
[BUG] Error when opening from SharePoint App

### ISSUE THREAD

**Issue by brunolanceleaux** [pnp/custom-learning-office-365#197]
**Describe the bug**
I have testing the experience from mobile devices. The Learning Pathways web part works well from a mobile browser however when opening using the SharePoint App itself, it fails with an error. This is a shame as the banner (from the browser) encourages the user to use the SharePoint App.

**To Reproduce**
1. Open your site collection from the SharePoint App. Click on any of the Hero links that take you to the web part (e.g. 6 simple steps)

**Expected behavior**
The web part/page to open within the SharePoint App.

**Screenshots**
![SharePointAppError](https://user-images.githubusercontent.com/34702914/73832990-25b30580-4859-11ea-91fc-028e0270e01e.jpg)

**Learning Pathways version number:**
[3.0.3.0]

**Comment by juliemturner** [comment]
So I have successfully viewed learning pathways in the SharePoint app, that said there are various caveats, none are related to learning pathways but rather related to the SharePoint framework and the mobile app, so none of these things I can do much about. 

I have found that I'm able to load learning pathways fine in a tenant with an account that doesn't have MFA and doesn't have the public CDN turned on. All of that said when it's not working for me the error message is quite different (see below). Also, I know that the admin page (CustomLearningAdmin.aspx) and the main viewer page (CustomLearningViewer.aspx) will not work in the SharePoint app as they are on what is known as "single app part pages" and they do not load in the SharePoint app.

![20200205_165623000_iOS](https://user-images.githubusercontent.com/7570936/73863881-c03a2700-480e-11ea-9324-8ee344cbb3db.png)

**Comment by juliemturner** [comment]
Update: after some more tinkering by resetting my credentials in the SharePoint app (the one that was previously giving me this error) I was able to successfully view the web part in both tenants.  Again this is not the Admin or Viewer page just pages with the web part on them, like Six Simple Steps.  Also, to clarify I'm using the iOS version of the SharePoint app.
