### ISSUE TITLE
[QUESTION] Should we expect to see changes in the Home page of the Learning Pathways site if we have to provision it manually with the script?

### ISSUE THREAD

**Issue by Ogresham** [pnp/custom-learning-office-365#198]
**What is the context of your question?**
- [ ] Installation
- [ ] Administration
- [ ] Custom Content
- [X ] M365 learning pathways web part

**What is your question?**
We attempted to provision Learning Pathways on our site and it would never work - no error, it would just spin, even after leaving it for hours it would never work.  We opened a few tickets with support and we were told to provision it manually using the script.  I did that, but we were expecting it to behave the same way as if it were provisioned the other way.  After we finished we expected the "home" page to change - but it has never changed.  I have opened another ticket with support and they are unable to tell me why it doesn't change or if it is even supposed to change since it was manually created with the script.  Should we expect a change in the home page when we provision with the script?

**Provide related screen-shots to help us understand your question**

**Comment by juliemturner** [comment]
Provisioning the site manually through the install scripts does not create the related "getting started" pages in your site collection, it only provisions the web part package and sets up various tenant app properties and configures the admin and viewer pages.  To get the pages you would have to provide through the provisioning service.  Support for the provisioning service is done through GitHub via the [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs/issues) repo, not a support ticket through Microsoft (not entirely clear if that's whom you mean when you reference support). 

That said the provisioning is simply creating a template of content to help you get started and it will not be updated after that first time it's provisioned.

**Comment by Ogresham** [comment]
Yes we were going through Microsoft support for assistance.  Thank you for the information this was very helpful.  We thought we had done something incorrectly.
