### ISSUE TITLE
[QUESTION] When will the other languages be avlaible?

### ISSUE THREAD

**Issue by io4master** [pnp/custom-learning-office-365#200]
This is a incredible adoption tool but according to Microsoft Docs https://docs.microsoft.com/en-us/office365/customlearning/faq the solution will be offered in other languages in 2020 Q1.  Do you have any idea on when the other languages will be released as we support different languages in our organization?
Thanks!

**Comment by juliemturner** [comment]
Unfortunately, that document is out of date and I do not have any more updated information that I can give you at this time.  I've tagged those that I think can answer it.

**Comment by pb762** [comment]
We are interested in this information as well. Thank you!

**Comment by micarrier** [comment]
We are interested. Thank you!

**Comment by jvondermans** [comment]
I'm interested in this info as well, hopefully this will be available in other languages soon!

**Comment by pb762** [comment]
Any update on this topic please?

**Comment by peterjkrebs** [comment]
What languages is Microsoft 365 learning pathways available in?
Microsoft 365 learning pathways is currently available only in English. Automatic end-to-end provisioning only works with English tenants. We plan on rolling out multilingual support for these nine languages in the second quarter of 2020.

Chinese (Simplified)
Dutch (Netherlands)
French
German
Italian (Italy)
Japanese (Japan)
Portuguese (Brazilian)
Russian (Russian)
Spanish

**Comment by Rafou2** [comment]
The FAQ https://docs.microsoft.com/en-us/office365/customlearning/faq now states that 'We plan on rolling out multilingual support for the following languages in the **second quarter of 2020**'.
Are you confident we are in line with meeting this target ? Can I plan a UK customer project with the multi-lingual version available before end of June ? Thank you

**Comment by juliemturner** [comment]
@Rafou2  -- in the future, please do not comment on closed issues, rather open a new issue and reference the closed one. Please see comments on #267
