### ISSUE TITLE
Playlist Content Delays And Load Failures In GCC

### ISSUE THREAD

**Issue by newgardj** [pnp/custom-learning-office-365#201]
Within a GCC tenant, loading Playlist Content takes longer than expected and can lead to load failures.

Chrome is the least impacted as content loads successfully after a short delay
![GCC-ContentSucceed-Duration-Chrome](https://user-images.githubusercontent.com/34944901/73957301-66dfff80-48c3-11ea-967b-f8240ce054b7.jpg)

Edge Chromium takes significantly longer and may fail to load videos or all content
![GCC-ContentFail-Duration-EdgeChromium](https://user-images.githubusercontent.com/34944901/73957351-76f7df00-48c3-11ea-93ed-4f0a054529b7.jpg)
![GCC-ContentFail-EdgeChromium](https://user-images.githubusercontent.com/34944901/73957368-7b23fc80-48c3-11ea-91ba-ac5d3af31ea9.jpg)

Internet Explorer behaves similarly to Edge Chromium
![GCC-ContentFail-InternetExplorer](https://user-images.githubusercontent.com/34944901/73957393-86772800-48c3-11ea-92a6-6da853ca8dc7.jpg)
![GCC-ContentSucceed-Duration-Chrome](https://user-images.githubusercontent.com/34944901/73957397-89721880-48c3-11ea-8b5e-55d97847752e.jpg)

**Comment by juliemturner** [comment]
So you're saying that this issue is ONLY in GCC tenant? Can you verify that there isn't any vpn/firewall/proxies involved in the network that could be causing delays or failures? 

Also, to help more I would need to actually see what the failure is. The screenshots you're showing here are listing a 200 status, which is not an error, so I'm not sure what exactly is happening.  Are there any console errors?

**Comment by newgardj** [comment]
Version: 3.0
![image](https://user-images.githubusercontent.com/34944901/73960900-e8865c00-48c8-11ea-83c0-5a43ca64745b.png)

Deployment Method: Provisioning Engine
https://provisioning.sharepointpnp.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239

No VPN or proxy is being used; this first showed up testing a GCC Tenant but I am able to reproduce in a Worldwide Tenant as well

Steps to Reproduce:
1. Provision Learning Pathways
2. Go to any playlist [Multiple assets in Teams and Outlook have been checked]
3. View any Default Content

Expectation: Content Loads
Behavior: Content sometimes loads after long delay, loads with delay and missing videos, or fails to load

Screenshots show long duration requests with 200s and long duration requests with 503s and an additional one with a 504
![GCC-ContentFail-Duration-EdgeChromium](https://user-images.githubusercontent.com/34944901/73961254-7c582800-48c9-11ea-9ed9-61e39f0380b6.jpg)

![GCC-ContentFail-Duration-InternetExplorerjpg](https://user-images.githubusercontent.com/34944901/73961249-795d3780-48c9-11ea-9992-7a3bbebfa803.jpg)

![image](https://user-images.githubusercontent.com/34944901/73961300-8ed26180-48c9-11ea-939d-88cfd5cca0d2.png)

--


[gcc-tenant-issue.zip](https://github.com/pnp/custom-learning-office-365/files/4166679/gcc-tenant-issue.zip)

**Comment by newgardj** [comment]
Will need to re-test once support.office.com comes back up as that is the likely source.

**Comment by newgardj** [comment]
Confirming this issue was due to the Support.Office.com outage.
