### ISSUE TITLE
SharePoint Online Management Shell Installation Question

### ISSUE THREAD

**Issue by DDewbre** [pnp/custom-learning-office-365#205]
**What is the context of your question?**
- [x ] Installation
- [ ] Administration
- [ ] Custom Content
- [x ] M365 learning pathways web part

**What is your question?**
I'm trying to install the .\M365lpconfiguration.ps1 using the SharePoint Online Management Shell, and I'm kinda new to it :-), and when I add the code per the instructions 

_".\M365lpConfiguration.ps1 -TenantName contoso -SiteCollectionName M365LP -AppCatalogAdminOnly"_

I have changed the tenant and site collection information but I get this error message:  

_".\M365lpConfiguration.ps1 : The term '.\M365lpConfiguration.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

What cmdlet am I missing in order to execute this?  Also, I'm assuming (I know, I know, not good) that the ".\" means that the ps1 is located on my local machine....is that correct?

Any help would be most appreciated!

Daren

**Comment by juliemturner** [comment]
So I'm going to ask first, is there a particular reason you wouldn't deploy it using the provisioning service instead, as this would be much easier for you.

Assuming you have some type of restriction what parts have you successfully implemented already?
But yes to answer your question you would have cloned or downloaded these scripts to your machine. Also, you need to be in the Windows PowerShell app, running as the administrator, and then be in the right directory. The error tome implies it can't find the PowerShell script, but I don't really have enough details so I'm guessing somewhat.

**Comment by DDewbre** [comment]
Thanks for responding Julie!  Yes, we are in MSFT GCC High environment which means we can't use the provisioning service....sure wish we could have as it would have made it easier for sure!   

We've successfully completed part 5 (https://docs.microsoft.com/en-us/office365/customlearning/custom_manualsetup). 

Ok, the file needs to be on my machine, which does make sense.    So, I didn't think you could connect to SPOL via Windows PowerShell app, so I'll try that as well.

**Comment by juliemturner** [comment]
Ok, so I'm going to stop you right there.  SharePoint framework solutions do not work in GCCH tenants because NoScripting is turned on and further you will not be able to access the CDN source as it's outside the tenant.  Please see the response in this issue: #199. But long story short you're not going to be able to use M365LP in a GCCH tenant.

**Comment by DDewbre** [comment]
Well, bummer bogs!! Thanks you so much for answering my questions!
