### ISSUE TITLE
[BUG] The Microsoft Stream Tile is not appearing in the solution

### ISSUE THREAD

**Issue by erictechtips** [pnp/custom-learning-office-365#207]
**Describe the bug**
In the following video: https://youtu.be/-sLXl_rKGxQ?t=651   You can clearly see a Microsoft Stream tile for learning about Microsoft Stream.  This tile is not visible in the solution when it has been deployed.  

**To Reproduce**
1. Go to https://tenantURL.sharepoint.com/sites/Microsoft365/SitePages/CustomLearningViewer.aspx
3. Scroll down to Products
4. See that Microsoft Stream is missing

**Expected behavior**
Microsoft Stream tile should appear as shown in the video

**Screenshots**
https://myitservices.adventhealth.com/wp-content/uploads/2020/02/Missing-Microsoft-Stream-Tile.png

**Learning Pathways version number:**
3.0.4

**Additional context**

**Comment by juliemturner** [comment]
Can you verify you didn't accidentally hide Stream in the Admin web part?

![image](https://user-images.githubusercontent.com/7570936/74544008-63c4bf00-4f14-11ea-9a0a-abdc1d8d4318.png)

**Comment by erictechtips** [comment]
Good Afternoon,

Yes I can verify it is not in the list of products.  https://myitservices.adventhealth.com/wp-content/uploads/2020/02/Microsoft-Stream-Missing-in-List-of-Products.png


[cid:image002.jpg@01D5E335.0194D2C0]

Eric Davis
AdventHealth
Systems Administrator, Enterprise Collaboration Services | AIT Technology Services
407-543-5826

**Comment by juliemturner** [comment]
If you're absolutely sure you're on version 3.0.4 of the web part (meaning you updated the web part after I released it yesterday?) then you clearly have some type of problem getting the updated content manifests from GitHub.  Please check out the network tab of the browsers developer console and verify that you're getting a valid response from the metadata.json, playlists.json, and assets.json calls when loading the admin page.

![image](https://user-images.githubusercontent.com/7570936/74555828-95e11b80-4f2a-11ea-9bcc-2990cfcc052c.png)

**Comment by erictechtips** [comment]
Good Afternoon,

I am quite sure I am running 3.0.4 (see screenshot below).

The metadata.json, playlists.json, and assets.json all responded with 200 OK.  See the attached .har file exported from the Network tab in the following link.  https://myitservices.adventhealth.com/wp-content/uploads/2020/02/Custom-Learning-Admin-Page-Network-Tab-Results.zip



[cid:image001.png@01D5E33D.AB01CDB0]



Eric Davis
AdventHealth
Systems Administrator, Enterprise Collaboration Services | AIT Technology Services
407-543-5826

**Comment by juliemturner** [comment]
First, let me remind you that you're exposing your PII when you respond via email. You might want to remove information from the email or respond via the web client.

Because you responded via email I can't see the screenshot, so you'd have to paste that into the browser, but, that said the HAR file shows that you're downloading the manifest from the right endpoint so I can confirm you're using version 3.

All this said I figured it out by going back. I'm pointing at a staging CDN. I didn't remember I was doing that when recording the videos but regardless that content has not been added to the public endpoints although I thought they had. I will research more and see if I can find out why and when that might happen.

**Comment by erictechtips** [comment]
Thank you for helping me find the root cause.  I appreciate your assistance.  Looking forward to any updates you may be able to share after you learn more.

**Comment by juliemturner** [comment]
Ok, so the long and short of this is that yes I'm pointing at staging but the reason those categories aren't in production is that there's some issues with the docs site and the way it opens videos/URLs.  They're working on the fix and hopefully, that content will be pushed out soon.
