### ISSUE TITLE
[BUG] CORS Issues with Videos

### ISSUE THREAD

**Issue by tseward** [pnp/custom-learning-office-365#209]
When visiting a page with videos embedded, such as `Get-Started-with-Microsoft-Teams.aspx`, I'm seeing a CORS issue preventing the video from loading.

`Load denied by X-Frame-Options: “SAMEORIGIN” from “https://www.microsoft.com/library/errorpages/smarterror.aspx?correlationId=FcaZliFxN0eTFfvY.0.3.0”, site does not permit cross-origin framing from “https://support.office.com/en-us/client/422bf3aa-9ae8-46f1-8…gservices&version=1&fromOrigin=https://tenantName.sharepoint.com”.
`

**Learning Pathways version number:**
3.0.4.0

**Comment by juliemturner** [comment]
Can you be a bit more specific on what exact playlists/asset as I'm not currently having any issues after trying out a few from the Teams playlists?

**Comment by tseward** [comment]
@juliemturner I'm going to the Microsoft 365 training -> Get started with Microsoft Teams ->What is Microsoft Teams? page. But it is happening on all pages.

**Comment by juliemturner** [comment]
Ok.  Well this is my tenant, with I think the same video you just referenced and it's playing:

![image](https://user-images.githubusercontent.com/7570936/74775858-846a7d00-5264-11ea-989c-8b665066416c.png)

Can you try just browsing to the page itself outside of LP: 
https://support.office.com/en-us/client/422bf3aa-9ae8-46f1-83a2-e65720e1a34d

**Comment by tseward** [comment]
Ah ha! This is an Edge Chromium issue (Canary, 82.0.425.0). Works fine in Chrome/FF current production.
