### ISSUE TITLE
[BUG] CustomLearningAdmin page not loading

### ISSUE THREAD

**Issue by cjknightFENZ** [pnp/custom-learning-office-365#211]
>**PROVISIONING NOTE**: If you are having issues with the provisioning service while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the provisioning service to [https://github.com/SharePoint/sp-dev-docs/issues](https://github.com/SharePoint/sp-dev-docs/issues).

**Describe the bug**
The site is provisioned but the admin pages aren't showing.  This is due to someone changing the url of the site from /sites/learning to /sites/learningO365

See screenshot for powershell get-spostorageentity.  Even after using set-spostorageentity, the value is sitll  /sites/learning, but it needs to be /sites/learningO365,   

Tryed renaming the site back to Learning but the name 'is not available'.  Should I delete the site collection and provision again?

Thanks

<img width="944" alt="powershell" src="https://user-images.githubusercontent.com/45815520/74883893-d3382400-53d6-11ea-9540-7230c06c3940.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Learning Pathways version number:**
Please share the version number of learning pathways in your tenant app catalog.

**Additional context**

**Comment by juliemturner** [comment]
Based on the screen shot above you set the value with spaces on either side and then checked it without the spaces... so you didn't set the one you checked.

**Comment by cjknightFENZ** [comment]
Thanks, sorry for wasting your time :)
