### ISSUE TITLE
[QUESTION] Other Apps

### ISSUE THREAD

**Issue by dirrcher** [pnp/custom-learning-office-365#212]
- [ ] Custom Content

Are there any plans to include these apps: Project, Visio, To-Do, Delve, Publisher

We've got a lot in here, I have users asking for the content for these apps as well.

**Comment by juliemturner** [comment]
Assigning to someone who can provide an answer

**Comment by pjherman** [comment]
powerbi would also be a nice include.

**Comment by dillydallan** [comment]
More on Stream too - lots of questions from business on how to manage who can view it

**Comment by juliemturner** [comment]
@ec-alm You can, there are various ways of doing so from custom sub categories to custom content packs, I suggest you watch the overview video for a complete rundown of all the ways to add custom content or build your own content. https://www.youtube.com/watch?v=-sLXl_rKGxQ

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
