### ISSUE TITLE
[BUG] - 3.0.4.0 - Error: File contains corrupted data.

### ISSUE THREAD

**Issue by robertcaretta** [pnp/custom-learning-office-365#215]
**Describe the bug**
 I am attempting to upgrade from 3.0.3.0. When uploading the point release 3.0.4.0 says "Invalid SharePoint app package. Error: File contains corrupted data." 

**To Reproduce**
1. Go to 'SharePoint App Catalog'
2. Upload customlearning.sppkg
3. See error

**Expected behavior**
Should upgrade without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/1613085/75797729-2eeda000-5d3b-11ea-9355-c025d8ac2a48.png)

**Learning Pathways version number:**
Current working is 3.0.3.0.  Upgrading to 3.0.4.0

**Comment by juliemturner** [comment]
I just downloaded the file and uploaded it into an app catalog and it worked fine. It sounds like your downloaded file is corrupted.  Did you download it by using the following button or did you sync the repo?

![image](https://user-images.githubusercontent.com/7570936/75801598-6a8f6680-5d49-11ea-802d-c88f29ebf008.png)

**Comment by robertcaretta** [comment]
I downloaded directly from links on README page.  Confusion was on my part. 
This is solved. Thank you!
