### ISSUE TITLE
[BUG] 365 Learning Pathways Provisioning Issues

### ISSUE THREAD

**Issue by nirmala-m** [pnp/custom-learning-office-365#216]
>**PROVISIONING NOTE**: If you are having issues with the provisioning service while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the provisioning service to [https://github.com/SharePoint/sp-dev-docs/issues](https://github.com/SharePoint/sp-dev-docs/issues).

**Describe the bug**
We tried to provision the 365 Learning Pathways in our PROD and we ran into provisioning error immediately once we click the "Add to your tenant". The person who tried provisioning has logged in to their global admin account and also has administrator permissions in the Tenant App Catalog.

**To Reproduce**
1) Sign into tenant as tenant admin.
2) Go to the Microsoft 365 learning pathways solution page: https://provisioning.sharepointpnp.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
3) Click Add to your tenant. The very first time when we tried , it did asked for "Consent on behalf of the organization to provision the app" .
We did not get the screen to provide consent when we tried subsequent trials
4) See error - 
Sorry, something went wrong. There was an unexpected issue. Please try again after a while.
Current site is not a tenant administration site.

**Expected behavior**
We should see the provision information screen which would get Email address, destination URL's and provision button to install the Learning Pathways into the Tenant App catalog

**Screenshots**
![PROD_ERROR](https://user-images.githubusercontent.com/51378965/75816335-ff528e00-5d62-11ea-80a5-8c073e27370a.PNG)

**Learning Pathways version number:**
Please share the version number of learning pathways in your tenant app catalog.
https://provisioning.sharepointpnp.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239

**Additional context**

**Comment by juliemturner** [comment]
Per the note at the very top of the bug template: "Please post all questions and issues for the provisioning service to https://github.com/SharePoint/sp-dev-docs/issues."
