### ISSUE TITLE
[BUG] Edge Browser Errors

### ISSUE THREAD

**Issue by kelzmc** [pnp/custom-learning-office-365#217]
>**PROVISIONING NOTE**: If you are having issues with the provisioning service while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the provisioning service to [https://github.com/SharePoint/sp-dev-docs/issues](https://github.com/SharePoint/sp-dev-docs/issues).

**Describe the bug**
When attempting to access https://phillips66.sharepoint.com/sites/O365Hub/SitePages/Get-started-with-Microsoft-365.aspx in Edge we are getting an error. "
Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.]"

**To Reproduce**
1. Go to https://phillips66.sharepoint.com/sites/O365Hub
2. Click on Microsoft 365 Training while using Edge browser.
3. See error"
Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.]"

**Expected behavior**
What we expect to see would be a list of all the products and links to training within that list.

**Screenshots**
Expected: 
![image](https://user-images.githubusercontent.com/61292342/75890540-24431180-5df4-11ea-8b2e-604ff8bcab5b.png)

Issue:
![image](https://user-images.githubusercontent.com/61292342/75890337-d6c6a480-5df3-11ea-8ba8-3cfd4908695d.png)

Console error:
![image](https://user-images.githubusercontent.com/61292342/75891697-c57e9780-5df5-11ea-9cb7-4b60a7528124.png)

**Learning Pathways version number:**
Please share the version number of learning pathways in your tenant app catalog.
3.0.0.0

**Additional context**
When checking the console the error shows access denied. However currently only the site owners have access and we all get the same error. See screenshots above.A

**Comment by juliemturner** [comment]
So a couple of things. 

First, can you please upgrade to the most recent version of the web part which is 3.0.4, that way we can be sure that we're all running the same and most up to date version of the code. 

Second, I've tested this on Edge (not Chromium Edge) and could not replicate the problem. Based on the error message there is clearly a security issue with whatever user is authenticated getting access to the three lists "CustomConfig", "CustomPlaylists" and "CustomAssets". Can you please verify the permissions for that user. Are they able to browse to those lists through the UI?

**Comment by kelzmc** [comment]
I updated the web part in our app catalog and the app on that site.  I am one of the users and the site admin; we haven’t updated to Chromium Edge.
I checked the list permissions and nothing is unique.
Same thing.

[cid:image001.jpg@01D5F21C.AAC43890]

**Comment by juliemturner** [comment]
Ok, so when you're in the Edge browser and the web part isn't working and then you navigate to site contents and then click on say CustomConfig list you're able to see all the entries in the list?

**Comment by kelzmc** [comment]
Yes.
[cid:image001.png@01D5F226.E1DCA330]

**Comment by juliemturner** [comment]
I'm at a complete loss, the message is extremely clear that the user does not have rights to read the list items.  If you log into the solution with the same user and another browser it works fine? What exact version of Edge? What is the security group is the user you're testing with in? Can you provive a screen capture of the security settings of those lists?

**Comment by kelzmc** [comment]
Here's the version of Edge; Microsoft Edge 44.17763.831.0
I was seeing limited access for everyone. So I deleted the unique permissions (I didn't put them there) now all the tiles are gone but so it the error. 
![image](https://user-images.githubusercontent.com/61292342/75916806-992b4100-5e1e-11ea-897c-1f7080ea89f6.png)

**Comment by juliemturner** [comment]
Based on that console log the learning pathways web part doesn't appear to be on that page. Can you edit the page and make sure you've added the M365 learning pathways web part to the page?

**Comment by kelzmc** [comment]
We removed and re-added the web part and now we are good in Chrome and IE again but not Edge. Same thing and I still have access to the list and list settings
[cid:image001.jpg@01D5F237.161D7510]

**Comment by kelzmc** [comment]
Chrome:
![image](https://user-images.githubusercontent.com/61292342/75926429-2925b680-5e30-11ea-963b-cb7df9e62184.png)

Edge:
![image](https://user-images.githubusercontent.com/61292342/75926480-3a6ec300-5e30-11ea-8ada-7486aa9c892d.png)

**Comment by juliemturner** [comment]
Ok, so I may have a bit of a lead.  The url that it seems to think is the learning pathways master site is:
`https://phillips66.sharepoint.com/sites/P660365LearningPathways`
but the site you're running on has the URL 
`https://phillips66.sharepoint.com/sites/O365Hub`

So my question is, is this a new site that you created after the learning pathways site was created and you've then enabled learning pathways in this site as well and are trying to run it there or did you perhaps try and change the URL of the master learning pathways site after you created it? If you click on the "gear" icon in the solution where does it take you?

**Comment by kelzmc** [comment]
I changed the site name in the SharePoint Admin Center.

**Comment by kelzmc** [comment]
My question is why will it work in Chrome and IE; if it’s as simple as a name change.

**Comment by juliemturner** [comment]
>Note: When you reply via email the entire email thread including all your PII ends up in the comment.  I've been removing them but it's best practice to respond via the web UI instead of via email unless you're going to delete the entire body of the email.

So the answer then is that you need to change the Tenant App Property that defines what the master site URL is so that the solution will work properly.  It's not actually completely working in Chrome or IE, but that particular aspect both of those browsers are supporting the 302 redirect that's being issued when you try and access the old URL on the XHR call to get data, and apparently Edge will not.  

So to properly get the solution working since you will need to run the following PowerShell commands:
 ```
   $clSite = "https://phillips66.sharepoint.com/sites/O365Hub"
   Connect-PnPOnline -Url $clSite -UseWebLogin
   Set-PnPStorageEntity -Key MicrosoftCustomLearningSite -Value $clSite -Description "Microsoft 365 learning pathways Site Collection"
 ```
Where $clSite = the URL of the master learning pathways site, I may be able to guess that it's 
`https://phillips66.sharepoint.com/sites/O365Hub`

When you run this PowerShell, please please make sure you log in using an account that has access to the tenant app catalog.

**Comment by kelzmc** [comment]
Thank  you, I'll get this ran and let you know.

**Comment by kelzmc** [comment]
That fixed it and another problem we were seeing. Thank you!
