### ISSUE TITLE
Is it safe to delete Azure app SharePointPnP.ProvisioningApp.Tenant?

### ISSUE THREAD

**Issue by robertcaretta** [pnp/custom-learning-office-365#218]
**What is the context of your question?**
- [X] Installation
- [ ] Administration
- [ ] Custom Content
- [ ] M365 learning pathways web part

**What is your question?**
1) Can the Azure enterprise application SharePointPnP.ProvisioningApp.Tenant be safely deleted after initial provisioning?

2) Does the Microsoft Learning Template use the Azure app in any way post installation? My understanding is it does NOT, but I just want to double-check.

**Provide related screen-shots to help us understand your question**
Azure administrator recognized that the app has a lot of permissions, and understandably does not want unnecessary apps in the system.

**Comment by juliemturner** [comment]
Yes, you can delete the enterprise application and no the template doesn't use the azure app in any way after installation.
