### ISSUE TITLE
[BUG]  365 Learning Pathways Provisioning Issues 

### ISSUE THREAD

**Issue by nirmala-m** [pnp/custom-learning-office-365#219]
>**PROVISIONING NOTE**: If you are having issues with the provisioning service while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the provisioning service to [https://github.com/SharePoint/sp-dev-docs/issues](https://github.com/SharePoint/sp-dev-docs/issues).

**Describe the bug**
We tried to provision the 365 Learning Pathways in our PROD and we ran into provisioning error immediately once we click the "Add to your tenant". The person who tried provisioning has logged in to their global admin account and also has administrator permissions in the Tenant App Catalog.

**To Reproduce**

Sign into tenant as tenant admin.
Go to the Microsoft 365 learning pathways solution page: https://provisioning.sharepointpnp.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
Click Add to your tenant. The very first time when we tried , it did asked for "Consent on behalf of the organization to provision the app" .
We did not get the screen to provide consent when we tried subsequent trials
See error -
Sorry, something went wrong. There was an unexpected issue. Please try again after a while.
Current site is not a tenant administration site.

**Expected behavior**
We should see the provision information screen which would get Email address, destination URL's and provision button to install the Learning Pathways into the Tenant App catalog

**Screenshots**
![PROD_ERROR](https://user-images.githubusercontent.com/51378965/76094516-c435a200-5f90-11ea-9cdd-6c0c661594c3.PNG)

**Learning Pathways version number:**
Please share the version number of learning pathways in your tenant app catalog.
https://provisioning.sharepointpnp.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239

**Additional context**

**Comment by nirmala-m** [comment]
Hi @juliemturner 
I have submitted the bug here https://github.com/SharePoint/sp-dev-docs/issues/5419 as suggested by you , and there Prasad has suggested to create issues at https://github.com/pnp/custom-learning-office-365/issues/219

**Comment by juliemturner** [comment]
I'm not sure who @Prasad is but I cannot help you with provisioning services issues as I already said. My colleagues in the PnP Team will respond to your issue when they can I will bring it to their attention.
