### ISSUE TITLE
Upgrade fails to load Web part on CustomLearningAdmin after running script

### ISSUE THREAD

**Issue by peterjkrebs** [pnp/custom-learning-office-365#22]
Repro
Customer has App Catalog, Site Collection Admin Perms
Customer uploads v49 package to Tenant App Catalog & deploys - no errors
Customer runs CustomLearningConfiguration.ps1 script without errors.
Customer with Tenant Admin perms goes to Custom Learning site. 
CustomLearningAdmin.aspx is in Site pages but doesn't load the Web part.

[1553813754155 - Copy.log](https://github.com/pnp/custom-learning-office-365/files/3049322/1553813754155.-.Copy.log)

**Comment by juliemturner** [comment]
Web parts were not loaded into the site when pages were first created, therefore the CustomLearningAdmin and CustomLearningViewer pages need to be deleted and then the powershell script (CustomLearningConfiguration.ps1) re-run to recreate those pages with the -SiteAdminOnly switch to add the webparts to them.
