### ISSUE TITLE
 [QUESTION] Use bitbucket instead of github for custom content

### ISSUE THREAD

**Issue by denzy134** [pnp/custom-learning-office-365#220]
**What is the context of your question?**
- [ ] Installation
- [ ] Administration
- [X] Custom Content
- [ ] M365 learning pathways web part

**What is your question?**
Can you use bitbucket instead of github as the location for your content configuration files?

**Provide related screen-shots to help us understand your question**

**Comment by juliemturner** [comment]
I'm not familiar enough with bitbucket to say difinitively but a quick google search turned up the following which seems encouraging: https://pages.bitbucket.io/
