### ISSUE TITLE
[QUESTION]Configuration Errors Opening Learning Pathways

### ISSUE THREAD

**Issue by RobbieMay** [pnp/custom-learning-office-365#221]
**What is the context of your question?**
- [ ]  Installation

When trying to open any of the tiles in Edge we are recieving an error:

Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.]

This is only happening when using Edge as the browser, the tiles are opening in Chrome - have not check IE or Mobile.

From the console one of the errors is related to renaming the URL to the site -  I updated this after the site was created.  I tried to change the URL back but it is no longer available.  Is there a way to get the names updated/synced in the tenant property MicrosoftCustomLearningSite.

How can I fix this - we are rolling out in 2 days and need this working.

Thank you

**Comment by juliemturner** [comment]
Duplicate #217 

If you changed the URL of the site then you've abandoned the tenant app property that indicates to the solution what is the master site, please see the answer in the above issue for the PowerShell you need to run to correct the situation.

**Comment by ehrlee** [comment]
I'm getting the same error. My site is working fine but when I try to access the Custom Learning Admin page to create some new playlists, I encounter the error: "Microsoft 365 learning pathways has a configuration issue. Please see the browser console for detailed logs. For assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues." This happens on both Edge (newest version) and Chrome. We have a zero trust policy in place but I've got SP Admin permissions checked out and I'm able to access the SP Admin center so I don't think it's an authentication error?

**Comment by juliemturner** [comment]
@ehrlee -- what you're describing is a different issue, unless you changed the URL of your site, but based on the fact that you say you can't access it in any browser I suspect it's different. 

So that I can provide the best possible assistance could you please open your own issue and provide detailed information including what errors you're seeing in the browser console log. Also, please provide more information on what you mean by "you have a zero trust policy".

**Comment by ehrlee** [comment]
Sure, thanks!
