### ISSUE TITLE
Minor Grammer Issues[BUG] 

### ISSUE THREAD

**Issue by pb762** [pnp/custom-learning-office-365#223]
We found some minor grammar errors in Office 365 Basics playlists
![error1](https://user-images.githubusercontent.com/59031625/76656152-5f0c1e80-6545-11ea-99dc-3468f5f8a90f.png)
![error2](https://user-images.githubusercontent.com/59031625/76656235-8cf16300-6545-11ea-8a0c-4bdb7c86a365.png)

**Comment by juliemturner** [comment]
Closed as the content was updated in the April 2020 release.
