### ISSUE TITLE
SharePoint Playlist shows header and web page navigation menus[BUG] 

### ISSUE THREAD

**Issue by pb762** [pnp/custom-learning-office-365#224]
>**PROVISIONING NOTE**: If you are having issues with the provisioning service while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the provisioning service to [https://github.com/SharePoint/sp-provisioning-service/issues](https://github.com/SharePoint/sp-provisioning-service/issues).

**Describe the bug**
The Share and Sync with SharePoint Navigation menu is showing some web-page and navigation menus within the playlist.
![image](https://user-images.githubusercontent.com/59031625/76717100-f7063580-6708-11ea-986f-867b34fa2e7e.png)

**To Reproduce**

**Expected behavior**

**Screenshots**
I
![image](https://user-images.githubusercontent.com/59031625/76717104-008f9d80-6709-11ea-9244-bb7d9a98c852.png)
f applicable, add screenshots to help explain your problem.

**Learning Pathways version number:**Version 3.0.4
**Additional context**

**Comment by peterjkrebs** [comment]
The bug has been fixed. 
1) To update Learning Pathways in your tenant,  from the Learning Pathways Home menu, click Learning Pathways Administration. Opening the Admin page reloads the Learning Pathways content set with the update. 
2) Go to the Microsoft 365 Training page, and refresh the page. 
3) Click SharePoint > Share and Sync with SharePoint. The updated page appears.

**Comment by pb762** [comment]
It works now! Thank you @peterjkrebs
