### ISSUE TITLE
[BUG] Can not embed the video from YouTube or Microsoft Stream

### ISSUE THREAD

**Issue by jvennur** [pnp/custom-learning-office-365#226]
>**PROVISIONING NOTE**: If you are having issues with the provisioning service while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the provisioning service to [https://github.com/SharePoint/sp-provisioning-service/issues](https://github.com/SharePoint/sp-provisioning-service/issues).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Learning Pathways version number:**
Please share the version number of learning pathways in your tenant app catalog.

**Additional context**
Attached is the re pro video please rename it .zip .

**Comment by juliemturner** [comment]
Duplicate #225

**Comment by jvennur** [comment]
> > **PROVISIONING NOTE**: If you are having issues with the provisioning service while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the provisioning service to https://github.com/SharePoint/sp-provisioning-service/issues.
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...' Play List Assets
> 2. Click on '....' New Asset
> 3. Scroll down to '....' Try to create a new Asset by entering the Title, select Technology ,3 Enter the URL.
> 4. See error : By Try to view the page with the video link
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Learning Pathways version number:**
> Please share the version number of learning pathways in your tenant app catalog.
> 
> **Additional context**
> Add any other context about the problem here.
> Attached is the re pro video please rename it .zip .
