### ISSUE TITLE
Can we please get early access of the multilingual webpart?

### ISSUE THREAD

**Issue by nicht01** [pnp/custom-learning-office-365#228]
**What is the context of your question?**
- [ ] Installation
- [ ] Administration
- [ ] Custom Content
- [x] M365 learning pathways web part

**What is your question?**
Dear Learning Pathways Team,

We already have multilingual enabled in Sharepoint Online for our Tenant, so i kindly ask you if there is a way that we get early access to the multilingual webpart? (We urgently need it...)

Thank you for your help,
Best regards,
Nico Weber

**Comment by juliemturner** [comment]
Unfortunately I do not have the ability to grant that request. I’ve tagged members of the team who can at least speak to it.

**Comment by nicht01** [comment]
Thank you for the fast answer.

**Comment by nicht01** [comment]
@peterjkrebs @karuanag 
Is it possible to get early access, or is there now a Date when it will be published?
Because for Q1 are only a few days left.

We would be more than happy if there is a way to get early access to it.

**Comment by mhollinshead** [comment]
Hello @nicht01 - the only way to gain preview access to the multi-lingual release of the webpart will be via the Learning Pathways [Early Adopter Program (EAP)](https://docs.microsoft.com/en-us/office365/customlearning/custom_partnerguide).  More details will be provided in that forum regarding how we manage access and solicit feedback.

**Comment by nicht01** [comment]
Hi @mhollinshead 
Thank you for your answer. I signed up and hopefully will get a response soon.

Do you know when it will be released?

**Comment by juliemturner** [comment]
Information about release timing can be found here: [Learning pathways Feature Updates](https://docs.microsoft.com/en-us/office365/customlearning/custom_featureupdates)  Please keep an eye on that "What's New" section or my [twitter](https://twitter.com/jfj1997) handle for updates. .
