### ISSUE TITLE
[QUESTION] Modify the Ask Questions and Get Help pages not in pages

### ISSUE THREAD

**Issue by sptechcat** [pnp/custom-learning-office-365#233]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [x] Installation
- [] Administration
- [] Custom Content
- [] M365 learning pathways web part

### What is your question

I deployed manually. Followed instructions. Site seems fine - but there is a reference in next steps to "Modify the Ask Questions and Get Help page to create your own Help Center". I don't see these pages. Should they  have been deployed with the app? 

>Provide related screen-shots to help us understand your question
![image](https://user-images.githubusercontent.com/43790284/78048227-6a35bb80-7347-11ea-86c4-fb0b4496aecc.png)

**Comment by juliemturner** [comment]
You only get the site template, and thereby these extra pages to customize, if you use the provisioning service to deploy the site vs manual deployment.

**Comment by sptechcat** [comment]
Is there other stuff that is not included in the manual deployment?

**Comment by juliemturner** [comment]
No just the template pages.

**Comment by sptechcat** [comment]
And is it just those 2 pages, or are there others. Thanks Julie.

**Comment by juliemturner** [comment]
![image](https://user-images.githubusercontent.com/7570936/78053253-55105b00-734e-11ea-9548-87c1e0e161a3.png)

**Comment by sptechcat** [comment]
Last two questions. Are there pictures of these anywhere? 
Second question - if I can talk my organization into letting me deploy using PNP, do I have to start over, or can  I redeploy over existing site? 
Thank you Julie. This tool is so helpful.

**Comment by juliemturner** [comment]
The pages are just templates to get you started.  If you're interested in seeing what that site looks like then I'd suggest you spin up a development tenant, create an app catalog in your SharePoint Admin Center, wait 1 hour and then try and use the provisioning service to provision to the dev tenant... then you'll see what the pages look like and if you want and have a tool you can copy the pages into your site collection.

If you did want to provision into your existing tenant then you would have to start over, you cannot provision over and existing deployment.

**Comment by sptechcat** [comment]
Thanks for your help Julie.
