### ISSUE TITLE
How do you copy a playlist?  Option doesn't seem to be appearing.

### ISSUE THREAD

**Issue by EdSynh** [pnp/custom-learning-office-365#238]
How do you copy a playlist?  Option doesn't seem to be appearing.

The article at the following link indicates you can copy a Microsoft-supplied playlist then remove steps from your copy.
https://docs.microsoft.com/en-us/office365/customlearning/custom_copyplaylist

This is exactly what I would like to do; however, I do not see a 'Copy Playlist' option anywhere when I am in administration mode.  After selecting a playlist, my option is to close it (see screenshot).

I noticed in the closed issue titled:  Customize the playlist administration playlist assets  #58, there was mention of this feature.  That comment was dated Dec 2019, so I'm hoping the capability still exists and I'm just overlooking something.

Thanks.

![image](https://user-images.githubusercontent.com/63246448/78570612-351be400-77f3-11ea-9f48-95d054868de7.png)

**Comment by juliemturner** [comment]
Please validate what version of learning pathways you're running by following the instructions outlined [here](https://github.com/pnp/custom-learning-office-365#updating-the-solution)

**Comment by EdSynh** [comment]
It appears our current version is 2.0.15.0.

**Comment by juliemturner** [comment]
Very good!
