### ISSUE TITLE
SPLoaderError.loadComponentError - Failed to load Custom Learning Web part

### ISSUE THREAD

**Issue by peterjkrebs** [pnp/custom-learning-office-365#24]
Custom Learning installed via modified CustomLearningConfiguration.ps1 script. CustomLearningAdmin pages loads for some people, but others get a "This may a problem with a HTTPS certificate. Make sure you have the right certificate."

**Comment by juliemturner** [comment]
Client has custom domain left over from dedicated tenant.
App Catalog is in x.clientdomain.com, Custom learning site was in y.clientdomain.com. Effectively this is a CORS issue and unsupported by SharePoint Framework solutions.  Need to create Custom Learning site in the same url as the App Catalog.
