### ISSUE TITLE
[BUG] Tiles are not loading on learning pages.

### ISSUE THREAD

**Issue by erictechtips** [pnp/custom-learning-office-365#240]
## Describe the bug

A clear and concise description of what the bug is.  Starting on April 7, the tiles are no longer loading on our learning pathways site such as the getting started with Microsoft Teams and the "Office 365 training" page.  

Examples of pages with issues not loading the content:
/SitePages/Get-started-with-Office-365.aspx
/SitePages/Get-started-with-Microsoft-Teams.aspx
### To Reproduce

>Steps to reproduce the behavior
I'm not sure how to reproduce it.  It is happening in one of our tenants and not in our test tenant.  No changes were made recently from what I am aware of. 

>A clear and concise description of what you expected to happen.
The tiles should load and be clickable as they used to be.  
### Screenshots of the problem
1.  https://myitservices.adventhealth.com/wp-content/uploads/2020/04/Getting-started-with-Microsoft-Teams-not-loading.png
2. https://myitservices.adventhealth.com/wp-content/uploads/2020/04/Getting-started-with-Office-365-not-loading-tiles.png
>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number
Version 3.0.4

>Please share the version number of learning pathways in your tenant app catalog.
3.0.4.0
### Additional context

>Add any other context about the problem here.
This was working fine last week with no issues.

**Comment by juliemturner** [comment]
Please try navigating to the admin page, and refreshing that page 1x after it loads... then navigate (by just editing the URL) to the CustomLearningViewer.aspx page from CustomLearningAdmin.aspx. Then validate if any of the "tiles" are missing.  

Do you have any custom content in the Teams product category?

**Comment by erictechtips** [comment]
I followed your directions and that magically fixed the issue.  I wish I understood why it fixed it, but the tiles are now working! Thank you so much for your speedy response!  It makes a big difference for our organization!

**Comment by juliemturner** [comment]
I believe your cache was out of date and so all products without a technology selected weren't showing up.  We have only seen this really with those that didn't have the most up to date web part before the April content update, but that may just be a coincidence.  It's always a good idea to go to the admin web part (which issues a hard rebuild of the cache) and then navigate to the CustomLearningViewer.aspx page to validate what you believe you should see.  You can't have the viewer open in a separate tab and switch between the tabs without refreshing, as the cache update is asynchronous (as is any web page content unless specifically built not to be).
