### ISSUE TITLE
Translation of Webpart

### ISSUE THREAD

**Issue by dborchers-gc** [pnp/custom-learning-office-365#243]
Hi, sorry that this is only a question but i dont know where to tell this ;-)

Is there anyway to translate the webpart to another question? For the content i can use my own repository but i would like to translate the Webpart.

Thanks

**Comment by juliemturner** [comment]
The code for the web part is not publically available so there is no way for you to translate it.  The version 4 release that includes multilingual capabilities will give you translation for 8 languages, details here: https://docs.microsoft.com/en-us/office365/customlearning/custom_featureupdates
