### ISSUE TITLE
[BUG] Missing playlists in the "Outlook" subcategory

### ISSUE THREAD

**Issue by jcwmoore** [pnp/custom-learning-office-365#244]
## Describe the bug

The Outlook sub-category includes 11 playlists.  Those playlists have the "Technology" field set as either "Outlook" or "Outlook for iOS and Android".  I needed to have a playlist about managing Distribution Groups, so I created it and set the "Technology" field "Outlook". All of the assets in the playlist also use the Outlook technology as well.  To my surprise, the new playlist never showed up for use in the web part.  I then changed the web part filter from playlist to Subcategory and select Outlook.  Only 4 of the now 12 playlists showed up, the ones with technology set to "Outlook for iOS and Android".  I then changed my custom playlist to blank out the technology and it started showing up as expected.

### To Reproduce

Create a custom playlist with the technology set as "Outlook"

### Expected behavior

All playlists (custom and included) with Outlook as the technology should be available in the webpart

### Screenshots

Expected Playlists
![image](https://user-images.githubusercontent.com/4412332/79916301-1b32f180-83ee-11ea-8f82-2c529481731e.png)

Actual Playlists
![image](https://user-images.githubusercontent.com/4412332/79916356-3271df00-83ee-11ea-8f9c-f56e9c6e8a57.png)

### Learning Pathways version number

3.0.4

### Additional context

I upgraded from v2 something last week, everything else looks fine so I don't think there were any issues with the schema changes.  I also see this behavior with playlists using the "OneDrive" and "OneDrive for Business" technology options.

**Comment by juliemturner** [comment]
Can you please validate on the Technology list that you haven't (accidentally or on purpose) hidden any of the technologies?

**Comment by jcwmoore** [comment]
I didn't realize there was an option to hide a technology group.  I did find that setting and Outlook was set hidden.  After changing that setting everything works as expected.  You can also disregard the OneDrive comment.  I think there was a caching issue on my quick edit test.  A fresh browser has cleared that out.  Thanks for pointing me in the right direction.
