### ISSUE TITLE
Cannot retrieve a valid access token

### ISSUE THREAD

**Issue by cstephens987** [pnp/custom-learning-office-365#245]
I have tried on two separate tenants to set up the Microsoft Learning Pathways and get the same error on both.
"Sorry, something went wrong
There was an unexpected issue. Please try again after a while.
Cannot retrieve a valid Access Token for user x in tenant xxx"
App Catalog was created prior to attempting to provision the service.
Using a GA account to perform the task.

**Comment by juliemturner** [comment]
@cstephens987 - I'm guessing here somewhat but are you reporting an issue with using the Provisioning Service? I've pasted in below the guidance on getting assistance with that. If you're speaking of a manual provision using PowerShell could you provide some more information about the steps you've taken?

>**PROVISIONING NOTE**: If you are having issues with the provisioning service while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the provisioning service to [https://github.com/SharePoint/sp-provisioning-service/issues](https://github.com/SharePoint/sp-provisioning-service/issues).
 
Thanks.

**Comment by cstephens987** [comment]
Hi Julie, yes the issue is with the provisioning service. Thank you for the link I will post my issue there. 

Thank you

**Comment by juliemturner** [comment]
Your welcome!
