### ISSUE TITLE
[BUG] Content from Microsoft which has embedded videos stopped loading today

### ISSUE THREAD

**Issue by jonthenerd** [pnp/custom-learning-office-365#246]
## Describe the bug

Starting this morning, videos that were embedded within content provided by default with the solution stopped loading. This looks like a problem with the underlying page from Microsoft.

As this is an open source project and not covered by any support from Microsoft, I'm not quite sure where to submit this. It seems to be that the pages used by the webpart are just URL changes substituting "article" for "client" in the URL and that Microsoft itself would support the pages on their site, but that only this webpart would be making use of them. Hopefully the project maintainers have contacts they can use within MS to sort this out.

### To Reproduce

1. Visit browsable page from Microsoft: [https://support.office.com/en-us/article/join-a-meeting-in-teams-1613bb53-f3fa-431e-85a9-d6a91e3468c9#ID0EAABAAA=Mobile](https://support.office.com/en-us/article/join-a-meeting-in-teams-1613bb53-f3fa-431e-85a9-d6a91e3468c9#ID0EAABAAA=Mobile) - this works and has an embedded video.

2. Visit page used by Learning Pathways (substitute "article" for "client" in URL): [https://support.office.com/en-us/client/join-a-meeting-in-teams-1613bb53-f3fa-431e-85a9-d6a91e3468c9#ID0EAABAAA=Mobile](https://support.office.com/en-us/client/join-a-meeting-in-teams-1613bb53-f3fa-431e-85a9-d6a91e3468c9#ID0EAABAAA=Mobile) - the video does not load. Web server returns a 302 response to an error page.

### Expected behavior

Video should load as expected.

### Screenshots

Not needed. Look at steps to reproduce.

### Learning Pathways version number

N/A. Issue is with Microsoft web server/responses.

### Additional context

>Add any other context about the problem here.

**Comment by Chris-Wales** [comment]
Same error most likely. I'm getting a "www.microsoft.com refused to connect" regardless of browser when attempting to view video content in our Learning pathways.

**Comment by RyanMc09** [comment]
I am experiencing the same issue within multiple tenants.

**Comment by juliemturner** [comment]
Yep, me too! I'll pass this on to the team. Thanks

**Comment by jonthenerd** [comment]
Workaround for those in a bind:
1. Find the CustomConfig list on the site where you're storing configuration of the solution
2. Edit the CustomConfig item
3. Copy all of the JSONData value into a text editor and do a find/replace all finding /client/ and replacing with /article/
4. Change the title of the item to "CustomConfig-Original"
5. Create a new item with title "CustomConfig", your custom JSON Data, and CDN set to Default or whatever your other item was
6. Refresh pages that use the solution. Should be working, except it will also show the Microsoft header/nav within the webpart. But the content is usable.
7. When this issue is resolved by MS, you can delete your custom item and rename the other one back to CustomConfig.

**NOTE** 
This worked in my tenant and it may not work in yours. You are responsible for your own environment and take whatever risks on your own. Additionally, I believe you should avoid visiting the CustomLearningAdmin page as it refreshes content from Microsoft and may override the data in your custom config. I haven't dug into this enough to know for sure, but this is definitely an "unusupported" situation (even though there's no real support for this).

**Comment by juliemturner** [comment]
Yeah not only is going to the CustomLearningAdmin.aspx page going to break this fix but every 24 hours the web part will refresh the cache as well so this isn't going to be a long term fix.  Glad it gets' you moving now, hopefully it will get fixed quickly.

**Comment by jonthenerd** [comment]
Thanks for the heads up Julie. We'll keep an eye on it. It should only update if someone who has rights to edit the backing list visits the site, so I'll tell those folks in my tenant to stay away from the site for now.

**Comment by juliemturner** [comment]
I do that on purpose so that when the cache needs to be refreshed the user can update it.  You will end up seeing slower performance because of this change, as the cache will have expired and every time the web part loads it's going to do all the work to update it and then will fail, but if you're ok with that then I guess it's fine.  I wouldn't keep this change in place after it's fixed and I can't guarantee you that I'll be informed that it's fixed and update this issue that it has been as this is outside of my visibility. Probably instead of changing the permissions, I would have set the "LastUpdated" date at the end of the JSON blob out into the future, although that won't protect you if you visit the admin page.

**Comment by jonthenerd** [comment]
@juliemturner Thanks. Any way we can make it a configuration setting in the future to allow visitors to the site to even perform this functionality? Would rather not have a list open to modification by visitors, but understand that some people would be okay with it. 

Get the code put in GitHub and I'll submit a PR :)

**Comment by juliemturner** [comment]
Are you asking me if you can set visitors to read-only on the list but then allow them to update the item in the list?  No there's no way to do that.

**Comment by jonthenerd** [comment]
I'll do that. Feel free to clean up this thread back to the core issue.

**Comment by kelzmc** [comment]
Same error most likely. I'm getting a "www.microsoft.com refused to connect" regardless of browser when attempting to view video content in our Learning pathways.

**Comment by peterjkrebs** [comment]
The Learning Pathways team is aware of the "www.microsoft.com refused to connect" issue and is actively investigating.

**Comment by AllanBourne** [comment]
Facing the same issue with multiple customers

**Comment by peterjkrebs** [comment]
The issue has been fixed. Please retry loading pages with the video.

**Comment by gagarine** [comment]
Firefox block video content apparently because of [x-frame options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options).

<img width="1223" alt="image" src="https://github.com/pnp/custom-learning-office-365/assets/164074/27a5898b-3746-4fbf-88a5-6cce1b09e7fa">

**Comment by dcashpeterson** [comment]
@gagarine Thanks for letting us know. @jhwang-ms can you please let the content team know that this is happening again?

**Comment by dcashpeterson** [comment]
closed as insactive
