### ISSUE TITLE
[ENHANCEMENT] Configuration option to prevent the WebPart from updating the configuration

### ISSUE THREAD

**Issue by jonthenerd** [pnp/custom-learning-office-365#247]
**Is your feature request related to a problem? Please describe.**
See #246 . 
Currently, the backing list **CustomConfig** has custom permissions, different than the site. It allows even visitors to update the config list item. This is by design, as the WebPart will make periodic requests to Microsoft to check for new content, then update the config list item. While this is convenient for those who wish auto-updating without admin involvement, it has the following issues for those who do not:
 - If/when issues like #246 occur, manual corrections to the config list item will be overridden by the WebPart.
 - Some customers do not wish for members of the SharePoint Visitors group to be able to add or edit any files or items on the site. Visiting the Admin page is preferred.

**Describe the solution you'd like**
The config item should be extended to provide a boolean which controls whether or not the WebPart attempts to refresh data from Microsoft and update the backing config item. The UI on the Admin page should be updated to control this boolean, as well as toggle the permissions on the underlying CustomConfig list to be consistent.

**Describe alternatives you've considered**
This could also be placed in the Tenant Properties, but having a UI for this is convenient.

**Additional context**
If the project puts the source files for the WebPart on GitHub, then contributors (like myself) would happily submit pull requests along with enhancement requests.

**Comment by juliemturner** [comment]
After discussing this in detail we don't feel there isn't a good way to implement this that doesn't potentially cause issues. That said if you're really against having the visitor's group be able to refresh the data cache (which is all their permissions are permitted to do as inheritance is only broken for that one ConfigCache list) you can certainly turn that off (by reverting the list to inherit permissions) and the web part will continue to work. If you look in the console certainly errors will be reported but the webpart will continue to work without issue.

I'm going to close this enhancement request. If you have further enhancement ideas or issues, please feel free to create a new issue and reference this one.
