### ISSUE TITLE
[QUESTION] Is provisioning of the M365 Learning Pathways allowed for multiple sites within one tenant?  

### ISSUE THREAD

**Issue by shandaross** [pnp/custom-learning-office-365#249]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [] Installation
- [] Administration
- [] Custom Content
- [] M365 learning pathways web part

### What is your question

>Provide related screen-shots to help us understand your question

**Comment by juliemturner** [comment]
No. Duplicate #242
