### ISSUE TITLE
Microsoft docs not working in iframe

### ISSUE THREAD

**Issue by denzy134** [pnp/custom-learning-office-365#250]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [] Installation
- [] Administration
- [] Custom Content
- [] M365 learning pathways web part

### What is your question
 Is It possible to link to another page not in SharePoint when creating assets in Learning pathways?. I try to link to Microsoft docs for the power platform content but it keeps on showing a grey space in infoHub. 

>Provide related screen-shots to help us understand your question
![image](https://user-images.githubusercontent.com/35541187/80720746-96fdff80-8aba-11ea-9ebf-bab79f11e9e4.png)

I checked to make sure the domain was present in assets and then i checked the developer tools and console. This was the output below.
![image](https://user-images.githubusercontent.com/35541187/80720563-543c2780-8aba-11ea-981b-74ae08c91b2e.png)

**Comment by juliemturner** [comment]
So the answer is yes, in that docs.microsoft.com is a host that Microsoft includes, but I know there are some issues with some of the sites, and I know they are working on it as there are more docs content that they want to include.  Anyway, you can follow the patterns that you'll find int he assets.json file

i.e.

`https://docs.microsoft.com/en-us/office365/customlearning/dayinthelife?context=context%2Fchromeless&linktarget=true`

**Comment by denzy134** [comment]
Should i add the domain in the way you mentioned in assets then?

**Comment by juliemturner** [comment]
Ok, I checked, yep, it looks like one of the pages docs doesn't allow iFraming.  Sadly this is mostly out of our hands as the docs team needs to fix their site to allow us to iFrame all of their content.
