### ISSUE TITLE
CustomLearningAdmin.aspx page not loading anymore

### ISSUE THREAD

**Issue by ChaDess** [pnp/custom-learning-office-365#252]
We have provisioned the 365 Leaning pathway on our site beginning of April. It has all been working fine but today the page CustomLearningAdmin.aspx is not accessible anymore.
I've tried disabling my Chrome Adblock, opening it on another browser, updating the package with the steps in ReadMe section to update the solution (https://github.com/pnp/custom-learning-office-365), nothing is working. The page keeps loading and remains blank

![image](https://user-images.githubusercontent.com/64793222/80981442-e11c1380-8e21-11ea-96af-d26ed4f2c1a6.png)

Learning Pathways version number: 3.0.4.0

Additional context: we have recently renamed the site and changed the URL. Would that be a possible explanation of the page being broken?
All the other pages work as expected.
We also have built many other pages for other internal training purpose, I can't delete the site and restart from scratch.

Thanks for your help

**Comment by juliemturner** [comment]
Yes, effectively if you rename a site you break the setup. To fix it please run the PowerShell script noted here: https://github.com/pnp/custom-learning-office-365/tree/master/webpart#execute-powershell-configuration-script using the -SiteAdminOnly option and make sure you specify the new site collection name in the SiteCollectionName property.

**Comment by ChaDess** [comment]
Hello Julie,

Thanks for your answer.
I’m very sorry but I’m only a beginner in Powershell and can’t find a way to run this command.
I used  connect-SPOService to connect to the tenant
But then running  .\M365lpConfiguration.ps1 -TenantName thermalenergy -SiteCollectionName TEILearning -SiteeAdminOnly doesn’t work.
ObjectNotFound: (.\M365lpConfiguration.ps1:String) [], CommandNotFoundException

Could you give me the steps for making it work please?

Thanks
Kind regards,

Charlotte Dessertenne
Operational Systems Manager



T: +44 (0)117 917 7010
W: www.thermalenergy.com<http://www.thermalenergy.com/>
E: charlotte.dessertenne@thermalenergy.com<mailto:charlotte.dessertenne@thermalenergy.com>

Thermal Energy International (UK) Ltd.,
1 John Street, Bristol, BS1 2HR

[cid:image002.jpg@01D62231.BA52D1A0]


[cid:image003.jpg@01D62231.BA52D1A0]<https://www.linkedin.com/company/thermal-energy-international/>[cid:image004.jpg@01D62231.BA52D1A0]<https://twitter.com/GoThermalEnergy>[cid:image005.jpg@01D62231.BA52D1A0]<http://www.thermalenergy.com/videos.html>

Information contained in this communication from Thermal Energy International may be confidential, proprietary copyrighted and/or legally privileged. It is intended solely for the use of the individual or entity named on this message. If you are not the intended recipient, and have received this message in error, please notify us immediately by reply e-mail and then delete it from your system

**Comment by ChaDess** [comment]
Hello Julie, I'm getting an error "Exception has been thrown by the target of an invocation." and can't run this script. I am site collection administration of the site I want to connect to and have RemoteSigned execution policy. I open Powershell as administrator, then connect to service with MFA thanks to this “connect-SPOService" but once I run the -SiteAdminOnly option it's reopening an authentication method window which is not modern this time and then get me the error. Any clue?
Many thanks for your help

**Comment by daveak01** [comment]
Hi ChaDess,

I facing the exact same problem you are in regards to URL renaming and the error (only getting the error in Edge not in Chrome oddly).

I've tried Julie's recommendation and I hit the connection hurdle as well, to overcome it I had to amend the authentication part of the script to force it to use MfA. I amended this part:

$clSite = "https://$TenantName.sharepoint.com/sites/$SiteCollectionName"
try {
  # If Credentials were passed, try them
  if ([string]::IsNullOrWhitespace($Credentials)) {
    Connect-PnPOnline -Url $clSite -Credentials $Credentials -ErrorAction Stop
  } else {
    # If not, prompt for authentication. This supports MFA
    Connect-PnPOnline -Url $clSite -UseWebLogin -ErrorAction Stop
  }
}


and replace it with this instead:


$clSite = "https://$TenantName.sharepoint.com/sites/$SiteCollectionName"
try {
  # If Credentials were passed, try them
    Connect-PnPOnline -Url $clSite -UseWebLogin -ErrorAction Stop
}


This dead allow me to successfully connect, however it unfortunately did not resolve the problem for me. I'm not sure if maybe there is a sync time perhaps so maybe changes take some time to take affect but I imagine not. Look forward to hearing guidance from Julie, I think it's likely I may have to start from scratch, trying desperately to avoid that haha!

**Comment by juliemturner** [comment]
@ChaDess @daveak01 If you look a little deeper into the PowerShell you're running I suspect maybe you're providing a $connection.  See lines 59-73 in the [M365lpConfiguration.ps1](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/M365lpConfiguration.ps1)

```
$clSite = "https://$TenantName.sharepoint.com/sites/$SiteCollectionName"
try {
  # If Credentials were passed, try them
  if ([string]::IsNullOrWhitespace($Credentials)) {
    Connect-PnPOnline -Url $clSite -Credentials $Credentials -ErrorAction Stop
  } else {
    # If not, prompt for authentication. This supports MFA
    Connect-PnPOnline -Url $clSite -UseWebLogin -ErrorAction Stop
  }
}
catch {
  Write-Host "Failed to authenticate to $clSite"
  Write-Host $_
  break
}
```

Regardless the reality is you really only need to fix one tenant app property. I pointed you to that script as it will do that if you pass the right parameters into it for you, but alas maybe that was too complicated.  All you really need to do is run the following where $clSite is the URL of the new site collection name that is your master learning pathways site, i.e. https://mytenant.sharepoint.com/sites/M365LP

`
Connect-PnPOnline -Url $clSite -UseWebLogin
Set-PnPStorageEntity -Key MicrosoftCustomLearningSite -Value $clSite -Description "Microsoft 365 learning pathways Site Collection"
`

You can also validate the URL that the solution uses by running the following line:
`Get-PnPStorageEntity -Key MicrosoftCustomLearningSite`

Once that tenant app property points to the right location and you've hard refreshed the page everything should begin working properly again. This is something we do regularly when testing so I'm absolutely sure it will fix the issue.

**Comment by daveak01** [comment]
Hey Julie,

You were quite right as expected :) ! Has done the job for us!

Thank you so much for all of your support, is highly appreciated.

**Comment by ChaDess** [comment]
Hi Julie, 
Thank you so SO much, your final tip did the trick! So glad I don't have to start everything over! 
Thanks also @daveak01 for your help
Have a good day all
