### ISSUE TITLE
[BUG] "Microsoft 365 learning pathways has a configuration issue" in Edge after SharePoint site URL change

### ISSUE THREAD

**Issue by daveak01** [pnp/custom-learning-office-365#253]
Hi team,

We wanted to rename the URL of our test Learning Pathway site after we got it configured and we went to SharePoint Online and renamed the URL. Everything appeared to be fine in Chrome with no issues however in Edge we get the error:

"Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.]"

<img width="494" alt="image" src="https://user-images.githubusercontent.com/23347617/81055833-6a365780-8ec1-11ea-92f5-4910b51af605.png">

I've attached an image of the error logs from the console and basically it seems that Edge is still trying to authenticate against the old URL which ended "testpathway". This has subsequently been changed. I've cleared all browsing history and reset Edge and there has been no change.

Edge details:
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363

Any help would be greatly appreciated :)

**Comment by daveak01** [comment]
Hi Julie,

Just an update, took your advice from case #252 in regards to running the PS script with SiteAdminOnly and managed to get this to run succesfully however I'm still getting the same error in Edge. It seems to still be trying to go to the old URL I think maybe just for the web parts.

**Comment by juliemturner** [comment]
I think I've answered your question now in #252. I'll leave this open, but assuming you check the setting per my answer there and it's pointing the new location then I'm not sure there is anything else I can do without further details.

**Comment by daveak01** [comment]
Hey Julie,

As per my note in #252 the solution in that thread has resolved this issue.
