### ISSUE TITLE
Any idea on this with Learning Pathways?  I think it's a Permission Issue Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs

### ISSUE THREAD

**Issue by GeorgePrior22180** [pnp/custom-learning-office-365#254]
Any idea on this with Learning Pathways?  I think it's a Permission Issue Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs

**Comment by juliemturner** [comment]
There is this section at the top of the Bug issue template to give you a getting started FAQ for the issue.  If you would like to try following that and then report back with some more information we can try to assist you further.

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

**Comment by juliemturner** [comment]
Assuming that you were able to solve this problem since we've not heard back from you. If you continue to have problems please feel free to open a new issue and reference this one including as much detail as you can. Thanks!
