### ISSUE TITLE
New April 2020 Content Update Issue 

### ISSUE THREAD

**Issue by tone-sutto** [pnp/custom-learning-office-365#257]
I can view the new April 2020 content update page summary attached but cannot see any of the updated content it refers to. 
Help would be appreciated in determing where this new content is andwhy it is not being displayed ni my Learning pathways site  [
![learning-pathways-april-2020-content-issue](https://user-images.githubusercontent.com/63009773/81692709-b7cd3a00-9456-11ea-8df6-7b06ecf0193f.PNG)
](url)

**Comment by juliemturner** [comment]
I'm sorry, I really don't have enough information about your environment to help yet.  Have you looked in the admin page (CustomLearningAdmin.aspx) in your site?

**Comment by tone-sutto** [comment]
Yes - see attached.
Can't see the new sub-category, Remote Working or any of the new content referenced in April's update
![custom-admin-aspx](https://user-images.githubusercontent.com/63009773/81701030-5bbbe300-9461-11ea-9d67-d33fd33e26fa.PNG)

**Comment by juliemturner** [comment]
What version of solution do you have?

**Comment by tone-sutto** [comment]
2.0.15.0

**Comment by tone-sutto** [comment]
I can see that I need to update our version deployed :-)
I have a demo to do tomorrow morning, so I'll update after that demo - will let you know if there are any issues.

**Comment by juliemturner** [comment]
Yeah you need to be in version 3 or you won't see the updated content, we're only supporting v3 right now for content updates.
