### ISSUE TITLE
 SPLoaderError.loadComponentError 

### ISSUE THREAD

**Issue by mm43838** [pnp/custom-learning-office-365#258]
>**PROVISIONING NOTE**: If you are having issues with the provisioning service while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the provisioning service to [https://github.com/SharePoint/sp-provisioning-service/issues](https://github.com/SharePoint/sp-provisioning-service/issues).
 
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

We have a report from 2 users who receive the following error in their browser when attempting to access the pages that contain the Learning content.  This is happening regardless of browser, but we have not been able to reproduce it ourselves or with other users.  One of the reports from our users indicates that this is happening with his "mortal" non-admin user account, but when he logs into the site using his "onmicrosoft" admin account, the issue does not occur.  

[SPLoaderError.loadComponentError]:
***Failed to load component "141d4ab7-b6ca-4bf4-ac59-25b7bf93642d" (CustomLearningWebPart). Original error: ***Failed to load path dependency "M365LPStrings" from component "141d4ab7-b6ca-4bf4-ac59-25b7bf93642d" (CustomLearningWebPart). Original error: Script error for: 141d4ab7-b6ca-4bf4-ac59-25b7bf93642d_3.0.4/M365LPStrings
http://requirejs.org/docs/errors.html#scripterror

***INNERERROR:
***Failed to load path dependency "M365LPStrings" from component "141d4ab7-b6ca-4bf4-ac59-25b7bf93642d" (CustomLearningWebPart). Original error: Script error for: 141d4ab7-b6ca-4bf4-ac59-25b7bf93642d_3.0.4/M365LPStrings
http://requirejs.org/docs/errors.html#scripterror
***CALLSTACK:
Error
at r.t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_2197c551855e7ba6726f44b56ae27200.js:1:1024802)
at new r (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_2197c551855e7ba6726f44b56ae27200.js:1:1374670)
at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_2197c551855e7ba6726f44b56ae27200.js:1:1412834)
at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_2197c551855e7ba6726f44b56ae27200.js:1:1408865)
at https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_2197c551855e7ba6726f44b56ae27200.js:1:1402491

### To Reproduce

User logs into the site and navigates to one of the content pages (regardless of content, Teams, Office 365, etc.)

### Expected behavior

User should be able to see the various learning content containers (e.g., Teams, Office 365, then click on them to see the individual content).  

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

Version 3.0.4.0

### Additional context

>Add any other context about the problem here.

**Comment by juliemturner** [comment]
This happens when the user doesn't have access to your Tenant App Catalog and you haven't turned on the SharePoint public CDN.  This is a common occurrence with Guest accounts as they would by default not have access to the Tenant App Catalog, so a common fix is to turn on the SharePoint public CDN but you can also just figure out why that user doesn't have read access to the tenant app catalog and correct that issue.

**Comment by mm43838** [comment]
Access to the tenant app catalog fixed this.  Thank you.

**Comment by arungoeler** [comment]
my solution is deployed on site collection level and i am not using cdn path... i am loading external .js file throw config file...
Few users are facing above error not all.....

TECHNICAL DETAILS

[SPLoaderError.loadComponentError]: Failed to load component "6a88ed57-c2b7-490d-9577-4453c793eb76" (ShowComplaintsAdminWebPart). Original error: Failed to load path dependency "spfxutility" from component "6a88ed57-c2b7-490d-9577-4453c793eb76" (ShowComplaintsAdminWebPart). Original error: Script error for: ff1e2716-0c03-4f79-bd6a-85ff4708911e_0.0.1/spfxutility http://requirejs.org/docs/errors.html#scripterror INNERERROR: Failed to load path dependency "spfxutility" from component "6a88ed57-c2b7-490d-9577-4453c793eb76" (ShowComplaintsAdminWebPart). Original error: Script error for: ff1e2716-0c03-4f79-bd6a-85ff4708911e_0.0.1/spfxutility http://requirejs.org/docs/errors.html#scripterror CALLSTACK: Error at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_71bc7f69b1dffbed8541ca78ae9e396c.js:1:856137) at new t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_71bc7f69b1dffbed8541ca78ae9e396c.js:1:1159600) at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_71bc7f69b1dffbed8541ca78ae9e396c.js:1:1212699) at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_71bc7f69b1dffbed8541ca78ae9e396c.js:1:1208744) at https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_71bc7f69b1dffbed8541ca78ae9e396c.js:1:1202498
