### ISSUE TITLE
[QUESTION] Is there a possibility to edit/change the image of a Custom SubCategory?

### ISSUE THREAD

**Issue by elterotero** [pnp/custom-learning-office-365#259]
### What is the context of your question
- [] Custom Content
### What is your question
Is it possible to change the image of a custom SubCategory
This is the pic you get by default (pointing into the GitHub
![image](https://user-images.githubusercontent.com/35706053/81790656-5ff20a00-950e-11ea-85be-8a5cec24b9c8.png)

**Comment by juliemturner** [comment]
You can but it's a bit technical.  You need to get the URL you want to use instead and edit the JSON for the content in the CustomConfig list, specifically the CustomSubCategories list item.  There will be an Image value for the subcategory that has a URL, replace that with the URL for the image you would like to use instead, but make sure everyone has read access to that image.  The next major release of the solution will have an image picker to change that value within the UX.
