### ISSUE TITLE
Custom categories not displaying correctly

### ISSUE THREAD

**Issue by phil-maynard** [pnp/custom-learning-office-365#26]
We've managed to deploy the custom Learning site beautifully using the PnP Provisioning service.

We're now trying to set up custom categories and playlists but this isn't working for us as we'd expect. We can create the custom playlist and this works fine within a Microsoft category. However, when we create a custom category, it the category doesn't appear in the main list and the playlist doesn't consistently appear when we use the Web part to filter to the new category - I have to  keep changing the category name and re-saving playlists to get them to appear.

**Specific scenario details**
- Custom playlist created in existing Microsoft category (successful)
- Custom sub-category created (successful)
- Custom playlist created in custom sub-category (successful)
- Custom sub-category displayed in un-filtered Web Part (failed - _sub-category not listed_)
- Custom sub-category displayed when Web Part filtered to custom category (intermittent - _filter applied but playlist doesn't always appear on first save attempt. This is sometimes resolved by re-applying the list to the custom category in at admin section_)

**Current work around for getting custom playlists to show**
- Rename the sub-category
- Edit each playlist to apply new sub-category name
- Refresh web page with filtered web part
- Custom playlists appear

**Screenshots**
![CustomPlaylist-ExistingSubCategory](https://user-images.githubusercontent.com/29703291/55820172-61bef200-5af2-11e9-89fe-923f0242dd73.png)
![CustomPlaylist-CustomSubCategory-Fail](https://user-images.githubusercontent.com/29703291/55820171-61bef200-5af2-11e9-8819-8f0a1e62f156.png)
![CustomPlaylist-CustomSubCategory-Reapplied](https://user-images.githubusercontent.com/29703291/55820174-61bef200-5af2-11e9-8128-933a963a0b7c.png)
![CustomSubCategory-MissingFromList](https://user-images.githubusercontent.com/29703291/55820173-61bef200-5af2-11e9-8be1-90b224d1ee4d.png)

**Comment by juliemturner** [comment]
Correct me if I'm wrong but do you have two windows open and are changing admin and then switching to a different tab or browser window to update the web part on the page? 

The web part does a lot of caching to try and deal with the fact that there would be a lot of data having to be correlated on each load. If you make change in the Admin and then don't refresh your page where your custom learning web part is it's holding the state of the configuration in memory things may not show up as you expect until the page is refreshed so it can pick up the changes that the admin web part made to the underlying list object. If that's not the case, we'll look into it more deeply.

**Comment by phil-maynard** [comment]
Hi Julie. Thanks for the comment. I did have multiple tabs open - mainly to capture the admin and the viewer page in the same screenshot. The pages were both refreshed a few times with no difference. There is of course allways the chance of human error but I've had multiple issues with the custom lists from the beginning - although it's sometimes hard to fully replicate them.

Thanks for looking into this. There's a chance a few of us may be having similar issues - here's a link to a thread in the Microsoft Tech community - https://techcommunity.microsoft.com/t5/Driving-Adoption/Using-the-Custom-Learning-Site/m-p/393105#M758

If there's anything I can do to help get to the bottom of this, please let me know.

**Comment by juliemturner** [comment]
Ok, thanks for the update.  I'm struggling to reproduce the problem but I'll work on it some more and see if I can figure out exactly what the problem is.

**Comment by juliemturner** [comment]
@phil-maynard I've figured out how to reproduce the issue and will fix it.
The issue is with creating a new custom sub-category and then adding a playlist to it.  That code has a bug about determining the number of playlists that exist under the sub-category. It believes, incorrectly that there are none and therefore won't show the new subcategory because it has no playlists.  An interim fix is that after you add at least 1 playlist to a new custom sub-category, refresh the admin page.  Doing so rebuilds the cache and corrects the count issue.

**Comment by juliemturner** [comment]
Temporary work around.  It appears that you can work around this bug by doing 2 things:
1. Select a Technology for your custom playlist, even though it doesn't necessarily have one.
2. After adding the playlist to the custom sub category, refresh the administration page which will reset the cache. 
Your sub category and playlist will now show up.
These bugs will be corrected in a future release.

**Comment by phil-maynard** [comment]
@juliemturner thanks. Those steps work perfectly! :-)

**Comment by susanlennon** [comment]
I'm not sure if this is related, but from the initial description it seems like it would be. My customer loves the idea of technical training being provided from Microsoft for all things Microsoft, but they're wanting to extend the site to all things training, e.g. new employee on-boarding, annual refresher training, etc. In order to do so we thought we'd want to add new categories for content not related to O365. Is that even possible? Thanks! Love the offering!
