### ISSUE TITLE
[Question] - Why doesn't all learning content appear

### ISSUE THREAD

**Issue by dillydallan** [pnp/custom-learning-office-365#260]
### What is your question

I'm a change manager and trying to set up learning pathways for users.  Why doesn't ALL of the Microsoft training articles appear here?  it is so frustrating with the huge gaps in materials when I know it exists in the Microsoft realm.,  Or how do I add that content to playlists?

**Comment by juliemturner** [comment]
I updated your question so that the actual question was in the issue and not in the title.  I will assign this to someone at Microsoft to address as I cannot answer questions about content.

**Comment by juliemturner** [comment]
@dillydallan - To answer part of your question about adding your own content please check out the [Community Demo - Microsoft 365 Learning Pathways Architectural Overview](https://www.youtube.com/watch?v=-sLXl_rKGxQ) video that shows how to add other assets from support.office.com to your custom playlists.
