### ISSUE TITLE
 Url issue

### ISSUE THREAD

**Issue by Durksweb** [pnp/custom-learning-office-365#264]
After we have configured MLP, we changed the url in SP Admin center. After that we can no longer access the admin pages. You can't go back to the old URL: he says it already exists.

Is there a solotion to go back to the old url?

**Comment by juliemturner** [comment]
Please review the documentation on how to manage [changing the URL of the learning pathways site](https://github.com/pnp/custom-learning-office-365#changing-the-url-of-your-microsoft-365-learning-pathways-site).

**Comment by Durksweb** [comment]
Issue still appears after running script.
Other pages who were not accessible are now accessible except /CustomLearningAdmin.aspx.

See screenshot.
![image](https://user-images.githubusercontent.com/65964495/83268847-8084ba00-a1c6-11ea-882a-4ea9f4cf411a.png)

**Comment by juliemturner** [comment]
So the error message says that the site that you blanked out is the URL of the site that is the declared as the learning pathways master site... is that site the correct URL of the site after you ran the script? You can check the tenant app property by commenting out the "Set" statement and just running the script to "get" the current value. Let me know if the current value of the property matches what you've blurred out in your screenshot.

**Comment by Durksweb** [comment]
The blanked out URL, https://univeservices.sharepoint.com/sites/Unive365-leeromgeving, is the site declared as  learning pathways master site. The URl before the url change was https://univeservices.sharepoint.com/sites/WMO-O365/. If i look at the error message is says:
**This site is not the Microsoft 365 learning pathways site as defined by the tenant property MicrosoftCustomLearningSite: 'https://univeservices.sharepoint.com/sites/Unive365-leeromgeving/'. If the tenant property is correct than this web part cannot run in this web.**

**Comment by juliemturner** [comment]
It's hard for me to be 100% sure because I'm not 100% sure if you have any typos but I think the issue you're having is because you have a trailing / in the URL.  Try running the script again but don't put the trailing / on the end of the URL.

**Comment by Durksweb** [comment]
Today we did run the script again and then without the forward slash. Also we did use the admin account from the tennant instead of our own O365 admin account. What solved the problem we don't know but after running the script we could access the admin part of learning pathways agian.

So problem solved.
I would like to thank you for your help and for the thinking along.
