### ISSUE TITLE
CORS policy issue when specifying base URL for custom content pack

### ISSUE THREAD

**Issue by timbo-design** [pnp/custom-learning-office-365#265]
### Context
- [X] Custom Content

### Question
I want to add a custom content pack to my environment and am having issues with using any content source other than github.io for my custom content.  Structurally I can import a custom content pack when hosted within github pages, however if I try and host these anywhere else (e.g. Azure blob/CDN) then I get console errors related to CORS policies from SharePoint e.g.

Access to fetch at 'https://[MY SOURCE]/docs/v3/metadata.json' from origin 'https://[TENANT].sharepoint.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Am I overlooking something obvious when trying to specify a source URL for a custom content pack?

**Comment by juliemturner** [comment]
The CORS error is not related to SharePoint or this solution. From the error message, it sounds like you haven't assigned a CORS policy to your Azure blob storage to allow your source.

**Comment by timbo-design** [comment]
Thanks for the quick response / steer on this!  I'll give that a try.
