### ISSUE TITLE
 [BUG] When displayed in a Learning Pathways webpart, a custom asset (sharepoint page) is hidden or covered up by the previous asset in the playlist.

### ISSUE THREAD

**Issue by awaller98** [pnp/custom-learning-office-365#266]
## Describe the bug

When displayed in a Learning Pathways webpart, a custom asset (sharepoint page) is hidden or covered up by the previous asset in the playlist. Scrolling or moving the mouse may cause the asset to appear briefly in a flickering fashion. 

UPDATE: This only occurs if comments are disabled on the custom Sharepoint page asset.

This behavior only exists in Google Chrome. Verified on two different devices issue does not exist in Safari, Firefox, or Edge.

### To Reproduce

1. Copy an existing playlist or create a new playlist which contains Microsoft Assets
2. Insert a new asset (sharepoint page) anywhere in the new playlist and save the changes.
3. Edit the new Sharepoint page and disable comments. ***updated**
3. Add the playlist in a Learning pathways webpart in any Sharepoint page.
4. Navigate to the page using google Chrome and use the Learning Pathways webpart navigation to load the custom asset.

### Expected behavior

The asset selected in the Learning Pathways webpart should be displayed

### Screenshots

[Screen capture](https://mymcpl-my.sharepoint.com/:v:/g/personal/awaller_mymcpl_org/EbFyHidXfI5GjBJ45Off4gQBuXZ-wJYbYUFkYKUj_suG7Q?e=gQVIei)

### Learning Pathways version number

3.0.4.0

### Additional Context

Issue only exists in Google Chrome

**Comment by juliemturner** [comment]
Well, that's an interesting one, can't say as I've heard of that before. Can I just confirm that it's a Microsoft playlist you're copying and then inserting 1 custom asset in the middle somewhere?

**Comment by awaller98** [comment]
Yes, but It has also happened in a custom playlist with mostly Microsoft assets. Thank you for the quick response. And many thanks for all that you do!

**Comment by juliemturner** [comment]
Well... I'm at a loss.  I tried a whole bunch of ways to recreate you issue and I just couldn't duplicate it.  This scenario is working fine for me. Maybe it has something to do with what's on the custom asset page.  I just created a blank page, and then I tried embedding a video in it... at this point I'm not sure how to help you.

I did notice your page looks somewhat special. Do you have the same issue if you view the playlist from the CustomLearningViewer.aspx page?  Do you have the same issue if you create a page with only that playlist on it and no other content on the page?

**Comment by juliemturner** [comment]
I just checked, my custom asset page has comments turned off, as does the page where the web part is added... maybe it's your build of Chrome. I'm running version 83.0.4103.61

**Comment by awaller98** [comment]
Darn, I’m on the same version :(. I updated just before I posted the issue. 

I’ll try some more things, but another common factor is that they all have a Text webpart with an H2 heading and some normal text.

**Comment by awaller98** [comment]
Sadly, that is precisely how I confirmed that it was comments (for me at least) that were causing the issue. Although I didn't create a new page on which to embed the webpart. Even with a completely blank asset I can toggle comment on or off and make the issue go away. Thankfully, this has given me a little breathing room as I can get my playlists functioning normally while we try to isolate this further.

I'll try starting with a completely fresh playlist, blank new asset, and blank view page and see if I can narrow it down further.

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity and that we are currently working on the issue as referenced above.  If you're still having issues, please feel free to contribute to #375,
