### ISSUE TITLE
[QUESTION] Can we start from current version and upgrade to multilanguage later?

### ISSUE THREAD

**Issue by benoitfournier** [pnp/custom-learning-office-365#268]
### What is the context of your question

- [x] Installation
- [] Administration
- [x] Custom Content
- [] M365 learning pathways web part

### What is your question

We have been waiting for the multilanguage for a long time and need to create our new training site asap. Can we provision a site today with current version and start editing it or should we wait for the v4 kit?

Will there be breaking changes or a different structure because of the different languages pages?

Thanks

**Comment by juliemturner** [comment]
See my comments on #267
