### ISSUE TITLE
[ENHANCEMENT] Analytics for the Subcategories and Playlists

### ISSUE THREAD

**Issue by elterotero** [pnp/custom-learning-office-365#269]
**Is your feature request related to a problem? Please describe.**
Are there any plans to implement analytics based on the usage of Subcategories, Playlists & Assets?

**Describe the solution you'd like**
It would be nice to know which of those are consumed and how much.

**Comment by juliemturner** [comment]
It is something that we've discussed and so I know it's on the radar but I think we've been very much concentrating on getting the multilingual release out the door so it's not something I can say more on at this time.  Assigning to other members of the v-team for consideration.

**Comment by benoitfournier** [comment]
Any update on the analytics? I understand that we can get stats about our internal content from SharePoint but how can we measure Microsoft's content usage?

Thanks

**Comment by dcashpeterson** [comment]
@benoitfournier We don't have an update on this just yet. We are working on the backlog of feature request and I will make sure that this gets on the list for discussion.

**Comment by dcashpeterson** [comment]
@benoitfournier and @elterotero we have released custom analytics with the V5 beta we have released today. This allows you to get custom analytics when users view an asset. This shows the asset and the playlist it is attached to. We invite you to try out the V5 beta and provide feedback.
