### ISSUE TITLE
Install Script Fails

### ISSUE THREAD

**Issue by peterjkrebs** [pnp/custom-learning-office-365#27]
Customer has Tenant App Catalog
Tenant has Site Collection Admin Rights
Tenant Admin runs CustomConfig Script
Script throws the following error.

Add-PnPClientSideWebPart : Value cannot be null.
Parameter name: Passed in component cannot be null
At line:147 char:13
+             Add-PnPClientSideWebPart -Page $clvPage -Component "Custo ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-PnPClientSideWebPart], ArgumentNullE 
   xception
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.WebParts.AddC 
   lientSideWebPart
 
 
Add-PnPClientSideWebPart : Value cannot be null.
Parameter name: Passed in component cannot be null
At line:159 char:13
+             Add-PnPClientSideWebPart -Page $claPage -Component "Custo ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-PnPClientSideWebPart], ArgumentNullE 
   xception
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.WebParts.AddC 
   lientSideWebPart 

Site owner can add the webpart to the page. However, I only see the pink error message below. 
 
![image](https://user-images.githubusercontent.com/19641831/55830922-e0059f00-5ac6-11e9-8555-7031a0b07d96.png)

The Tenant Admin can see the webpart that Owner added. He published from his end but Owner still sees the message above. When Tenant Admin clicks Playlist Administration, he sees a 404 error.

**Comment by juliemturner** [comment]
Closing this as we've resolved through script updates.
