### ISSUE TITLE
Custom Image for Sub Category 

### ISSUE THREAD

**Issue by ruenells** [pnp/custom-learning-office-365#274]
@juliemturner 

I am following up on another issue https://github.com/pnp/custom-learning-office-365/issues/55#issuecomment-578257843 where you say we need to update the custom config in the json with the full path to the new image, I have done this, however it is also stated to go to the "admin webpart" to have it cache it.  I am not following what that means.  Can you please clarify i really need to get these images to stick.

**Comment by juliemturner** [comment]
All it means is that after you update a list item directly through he SharePoint UI you need to visit the CustomLearningAdmin.aspx page which loads all the data in the lists and caches it in a separate list item that the web part's read from.

**Comment by ruenells** [comment]
Perfect ok that helps thank you :)
