### ISSUE TITLE
[QUESTION] Problem deploying customlearning.sppkg

### ISSUE THREAD

**Issue by ChrisCCorbett** [pnp/custom-learning-office-365#275]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [x] Installation
- [] Administration
- [] Custom Content
- [] M365 learning pathways web part

### What is your question
Cannot load the learning pathways administration page. It looks as though the app has not deployed properly so I added myself to the owners group but do not know what to do next to deploy the app in the app centre?.

**Comment by ChrisCCorbett** [comment]
![Capture of Apps Catalogue](https://user-images.githubusercontent.com/66834025/84512863-83040b00-acc0-11ea-90e7-ebb29c50ba15.JPG)
Screen shot of Apps catalogue. Seems problem is the yellow columns?

**Comment by juliemturner** [comment]
Given the version of the app, I'm gathering that you deployed this using the provisioning service?
If yes, can you confirm that the site collection for learning pathways was created with the content on it and for the most part seems like it's complete (like you can see in the site pages library that there is a CustomLearningAdmin.aspx and CustomLearningViewer.asp page)? If yes, then I'd say you could try redeploying the solution following these instructions: https://github.com/pnp/custom-learning-office-365#updating-the-solution which should fix those highlighted areas.

If not, then I would delete the site collection, if any exists, and also delete the app out of the tenant app catalog and try provisioning a second time.

**Comment by ChrisCCorbett** [comment]
![Capture of Apps Catalogue](https://user-images.githubusercontent.com/66834025/84531377-6e357080-acdc-11ea-8d03-b1777b958fd1.JPG)
![Capture - Learning Pathways Administration Button](https://user-images.githubusercontent.com/66834025/84531380-6ece0700-acdc-11ea-93b3-fd11b8023b0a.JPG)
![Capture - Updated App in Apps Store](https://user-images.githubusercontent.com/66834025/84531381-6f669d80-acdc-11ea-971b-726573a55767.JPG)




Hi Julie
YES - Used provisioning service.
YES - Content seems to be there.
YES - customlearningadmin.aspx
YES - customlearningviewer.aspx
Most of that was previously way over my head but I followed what I could & it has definetly got me a lot closer to resolving this.
3 of the errors have now gone & only 1 issue seems to remain so maybe I missed a part. Please see new screen shots.
The learning pathways administration quick links button still does not work & comes up with the error code in the attached.

**Comment by ChrisCCorbett** [comment]
![Capture - Updated App in Apps Store](https://user-images.githubusercontent.com/66834025/84531717-e4d26e00-acdc-11ea-8920-d60651d03a7c.JPG)

**Comment by ChrisCCorbett** [comment]
![Capture - After Click On Admin Button](https://user-images.githubusercontent.com/66834025/84531803-092e4a80-acdd-11ea-8334-c282259e8757.JPG)

**Comment by juliemturner** [comment]
I can't speak to that quick link, it's supposed to point to the CustomLearningAdmin.aspx page in the site pages library, if that's there just navigate to it directly, you can update the link later.

If the admin page loads without error you should be all set.  

If it does not work than the original deployment was really unsuccessful.  Given your commenting as if the technical aspects of this are over your head (which is absolutely fine) I might suggest that you may want to delete the site and remove the app from the tenant app catalog and try again.  If you feel like I'm misconstruing your technical acumen then I would suggest you delete the customlearningadmin.aspx and customlearningviewer.aspx pages and remove the Microsoft 365 learning pathways app from site contents and then run the PowerShell to do the [manual deployment](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/README.md) to the site, which would then "fix everything up"...

**Comment by juliemturner** [comment]
Since we haven't heard back I'm going to assume you either got it working or gave up.  If it's the latter, I'm sorry you had such difficulty.  I will close this issue for now but if you continue to have problems please feel free to open a new issue and reference this one with further information.
