### ISSUE TITLE
 Article name getting trimmed when you list the articles

### ISSUE THREAD

**Issue by arjunumenon** [pnp/custom-learning-office-365#277]
## Describe the bug

When click on the Playlist, the name of the article is getting trimmed due to the width restriction if the article name is lengthier

### To Reproduce

1. Click on the default Playlist named **Work with Posts and messages** which is part of **Microsoft Teams**
2. You can see that the second article name is trimmed
3. Based on the design we assume that the width is taken from the current article name
4. So if you have an article whose name is small and you have an article name which has lengthier name, the width is inconsistent

### Expected behavior

Expecting the width to be shown maximum of the listed article so that name will not be cut off

### Screenshots

**Screenshot which shows Issue**
![Issue Screen - Name - Trimmed](https://user-images.githubusercontent.com/10369964/84769841-253f2e00-aff4-11ea-93d8-dc02ccc75769.jpg)

**Ideal / Expected Screen**
![Recommended Solution](https://user-images.githubusercontent.com/10369964/84769915-430c9300-aff4-11ea-8304-aee69a72ba27.jpg)

### Learning Pathways version number

3.0.4.0

**Comment by juliemturner** [comment]
This bug will be fixed in version 4.

**Comment by arjunumenon** [comment]
Thanks @juliemturner  for the super quick response. Appreciate all your efforts.

**Comment by juliemturner** [comment]
Version 4 has been released, closing this issue.
