### ISSUE TITLE
[QUESTION] Backup and restore CustomLists

### ISSUE THREAD

**Issue by elterotero** [pnp/custom-learning-office-365#278]
### What is the context of your question

- [] Administration

### What is your question

We have made several customizations around the 3 CustomLists (Assets, Configs & Playlists) and at the moment backing them up with Power Automate Flow, using copy from SharePoint list into a CSV into a different location.
Question is that is there any recommendation around backing up using the default Microsoft products. Also, if such a case would occur, restoring from the CSV file back into CustomLists what could be the best way to do this?
Could this be documented somewhere also (at least I wasn't able to find any mention around this).

**Comment by juliemturner** [comment]
It's here: https://github.com/pnp/custom-learning-office-365/blob/master/webpart/BackupInstructions.md -- I've been told 'SaveSiteAsTemplate' won't work at all anymore even if you know the URL but I haven't tried it.  You could also obviously use a third party tool.

**Comment by elterotero** [comment]
Thank you, I had a faint memory that I saw something somewhere, but couldn't recall where it was.
