### ISSUE TITLE
Web part icon wrapping issue in Edge

### ISSUE THREAD

**Issue by phil-maynard** [pnp/custom-learning-office-365#28]
This is relatively minor but w're experiencing an icon wrapping issue in the Microsoft Edge browser - see image below.

The issue seems to be caused by the **.category-item** width calculation in the style sheet:
```
.customLearning_dd144b57 .category-item {
width: calc(32px + ((100% - 352px)/ 12 * 2));
}
```
In Edge, the 100/12 * 2 calculation is resolving to 16.6667% which is then causing an issue as the 6th icon div is pushed to the lower line, causing an overall wrapping issue.
```
.customLearning_dd144b57 .category-item {
width: calc(-26.6667px + 16.6667%);
}
```
You can of course do what you like to resolve this but changing the calculation to calc(32px + ((99% - 352px)/ 12 * 2) resolves the issue.

In my tests, this has only been an issue in Edge, Chrome resolves the calculation correctly. The other width options for different resolutions are all OK as it's only the 12 * 2 option that's being rounded up.

**Edge category icon wrapping issue**
![EdgeWrappingIssueFromWidthCalc](https://user-images.githubusercontent.com/29703291/55887470-77d9ba80-5ba5-11e9-84b2-0dfe9be1651f.PNG)

**Edge category icon wrapping with calc(32px + ((99% - 352px)/ 12 * 2)**
![EdgeWrappingIssueFromWidthCalc-fixed](https://user-images.githubusercontent.com/29703291/55887508-8d4ee480-5ba5-11e9-9206-72678bfdfe5d.PNG)

**Comment by StfBauer** [comment]
Thank you for letting us know. This bug will be fixed in an upcoming release.
