### ISSUE TITLE
April 2020 content update features not available

### ISSUE THREAD

**Issue by pambarber** [pnp/custom-learning-office-365#281]
>**PROVISIONING NOTE**: If you are having issues with the provisioning service while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the provisioning service to [https://github.com/SharePoint/sp-provisioning-service/issues](https://github.com/SharePoint/sp-provisioning-service/issues).
 
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug
April 2020 content update items are not available such as Work Remotely.

In the Admin Success Center the April 2020 content update is described, and lists many items such as Work Remotely, which are not available.

### To Reproduce

Go to Pathways administration, the  under Scenarios,, should have Work Remotely, it is not there.

>Steps to reproduce the behavior

### Expected behavior
Click on learning Pathways administration, the  under Scenarios, I clicked Work Remotely, and Work Remotely with Microsoft 

>A clear and concise description of what you expected to happen.

### Screenshots

>If applicable, add screenshots to help explain your problem.

![missingworkremotely](https://user-images.githubusercontent.com/43859024/85301497-82603700-b46d-11ea-9b82-a1a7361ca4d0.png)

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

2.0.15.0

### Additional context

>Add any other context about the problem here.

Also looking up the version, I noticed a deployment error:
![deperror](https://user-images.githubusercontent.com/43859024/85306392-05848b80-b474-11ea-8ba1-f35e3a368832.png)

**Comment by juliemturner** [comment]
You must be using version 3.x of the web part to see the updated content. We are not updating content for version 2.x any longer. Also, if you have a deployment error that is an issue in your tenant but I suggest you just follow the process outlined in the [Updating the Solution](https://github.com/pnp/custom-learning-office-365#updating-the-solution) documentation and see if that fixes the deployment issue.
