### ISSUE TITLE
[QUESTION] Changing the display text for Audiences

### ISSUE THREAD

**Issue by ross-i-g** [pnp/custom-learning-office-365#282]
### What is the context of your question
- [X] Administration
- [X] Custom Content

### What is your question
Is there a way to change the name of the default audiences In Learning Pathways?
For example changing it from End-user to Employee or Visitor
![Image](https://user-images.githubusercontent.com/67279133/85302594-063c1280-b4b2-11ea-96f8-7bcca41e8a40.JPG)
If not is there a way to hide the audience text?
Thank you !

**Comment by juliemturner** [comment]
No there is not. You can however make a copy of the playlist and then set the audience to blank, as it is an optional field on custom playlists.
