### ISSUE TITLE
SharePoint Learning Pathways - Playlist 

### ISSUE THREAD

**Issue by Flasharrow** [pnp/custom-learning-office-365#285]
- [] Custom Content
- [] M365 learning pathways web part

Hey!! Team I'm a noob SharePoint Developer 

I'm using Microsoft Learning Pathways Training to make a educational website for my organization. 

I created a playlist I'm looking for output like the playlist of six simple steps. But I'm getting a error (webpage not available) when I insert URL of Microsoft stream video. 

And I get a error (something went wrong) when I create asset page. I even tried using embedded code but it did not work. 

![20200629_005906](https://user-images.githubusercontent.com/22091075/85995811-16e01180-b9f9-11ea-9b1c-491cef0516fe.jpg)

**Comment by juliemturner** [comment]
You need to create a SharePoint page either in the learning pathways site or another site, put a Stream web part on the page to embed the Stream video, and then use the link to the page as the asset URL.

**Comment by Flasharrow** [comment]
Thanks Julie 🙏🏻

**Comment by Flasharrow** [comment]
Do I have to create separate page for all videos??
