### ISSUE TITLE
[BUG] Fixed height in webpart

### ISSUE THREAD

**Issue by dborchers-gc** [pnp/custom-learning-office-365#286]
I cant create a bug Issue with the github function and i dont know why. Cause fthat here with blank Issue. Hope its okay

## Describe the bug

When i open an asset page with less content i see a long scrollbar and a page with a big height-value. Maybe the i frame is setup with an fixed height value? Its a little bit confusing on pages with less content because i have to scroll down a very long time to come to the buttom

### To Reproduce

Open a asset page with less content

### Expected behavior

The webpart should change the height based on the content

### Screenshots

-

### Learning Pathways version number

3.0.4

### Additional context

-

**Comment by juliemturner** [comment]
No problem with creating a blank issue.

This issue is a duplicate of #171, and unfortunately, I have no fix or a timeline on a fix.
