### ISSUE TITLE
[QUESTION] Learning Pathways Playlist 

### ISSUE THREAD

**Issue by Flasharrow** [pnp/custom-learning-office-365#290]
Hello 

On my educational website I have different sections of content. 

As my user click on a specific section I want the user to see only the specific playlist not the other playlist present too in learning pathways 

How to do that?? 

As you can see in the screen shot it's the general audit section and I just the user to see that playlist only not the other playlist. 
![20200707_123111](https://user-images.githubusercontent.com/22091075/86773802-e37f3180-c04d-11ea-9a9c-4b7835a729b3.jpg)

**Comment by juliemturner** [comment]
I'm not 100% sure I'm following your question if so my apologies, but I believe you've added the learning pathways web part to another page?  If so, then have you taken a look at the web part properties?  If so you can then change the web part to start at any category, subcategory, or playlist you want... effectively pinning it to that specific entry.  If not, then I'd suggest doing so.  Create another page and add the web part to it configuring it specifically for what you want people to see.  Another option is to navigate to what you want people to see and then copy a link to that particular piece of content, you can do that by clicking on the interconnected links in the menu and then use that link as a quick link or a menu option or something else...

**Comment by Flasharrow** [comment]
Hey!! Julie Sorry for the late response

My question is from the Screenshot above as you can see it's a section of general audit. And I only want general audit playlist to be present and not the GDPR training. 

Can you tell me how to do that 😅 I know the last comment might have my answer to the query but can you simply the answer Plz. 

I'm a noob SharePoint Developer 🤷🏻‍♂️ 

Thanks

**Comment by juliemturner** [comment]
I think maybe you'd be better off starting by watching the video that explains all the features of learning pathways by visually demoing them... see if that doesn't help out.  https://www.youtube.com/watch?v=-sLXl_rKGxQ

**Comment by Flasharrow** [comment]
Thanks Julie

**Comment by Flasharrow** [comment]
Problem Solved 🤘🏻
