### ISSUE TITLE
 SPLoaderError.loadComponentError

### ISSUE THREAD

**Issue by arungoeler** [pnp/custom-learning-office-365#292]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

We have a report from 2 users who receive the following error in their browser when attempting to access the pages that contain the webpart. This is happening regardless of browser, but we have not been able to reproduce it ourselves or with other users.
Web part solution is deployed at site collection level and no CDN is beeing used.

TECHNICAL DETAILS

[SPLoaderError.loadComponentError]: Failed to load component "6a88ed57-c2b7-490d-9577-4453c793eb76" (ShowComplaintsAdminWebPart). Original error: Failed to load path dependency "spfxutility" from component "6a88ed57-c2b7-490d-9577-4453c793eb76" (ShowComplaintsAdminWebPart). Original error: Script error for: ff1e2716-0c03-4f79-bd6a-85ff4708911e_0.0.1/spfxutility http://requirejs.org/docs/errors.html#scripterror INNERERROR: Failed to load path dependency "spfxutility" from component "6a88ed57-c2b7-490d-9577-4453c793eb76" (ShowComplaintsAdminWebPart). Original error: Script error for: ff1e2716-0c03-4f79-bd6a-85ff4708911e_0.0.1/spfxutility http://requirejs.org/docs/errors.html#scripterror CALLSTACK: Error at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_71bc7f69b1dffbed8541ca78ae9e396c.js:1:856137) at new t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_71bc7f69b1dffbed8541ca78ae9e396c.js:1:1159600) at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_71bc7f69b1dffbed8541ca78ae9e396c.js:1:1212699) at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_71bc7f69b1dffbed8541ca78ae9e396c.js:1:1208744) at https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_71bc7f69b1dffbed8541ca78ae9e396c.js:1:1202498

### To Reproduce

>Steps to reproduce the behavior

### Expected behavior

>A clear and concise description of what you expected to happen.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.

**Comment by juliemturner** [comment]
Although I'd like to be able to help you, the error your reporting seems to be specific to your environment and the SharePoint framework, I'm not really sure what to suggest.  I guess to give you some direction I might test if you have any other SharePoint framework solutions in your tenant and put them on a page by themselves will these users still have issues?

**Comment by arungoeler** [comment]
Yes, you are right. It was environment specific. external utility reference was wrong. On Prod i was referring Dev js.
