### ISSUE TITLE
[ENHANCEMENT] Sub Category Translation Warning Message

### ISSUE THREAD

**Issue by newgardj** [pnp/custom-learning-office-365#294]
**Is your feature request related to a problem? Please describe.**

In version 4.0, when working with Translations for Playlists, there is a warning that indicates the Custom Sub-Category doesn't have a translation. The wording could suggest that the functionality is not available rather than that the Admin/Translators need to take action.

![image](https://user-images.githubusercontent.com/34944901/86944319-d2ddc280-c104-11ea-94cb-8ddd9d320159.png)

This is visible when selecting a Playlist and then Edit Detail.

**Describe the solution you'd like**

I am proposing the phrasing be changed to make it more apparent that action is required.

"You must create a **Some Language** Translation for the selected Sub-Category."

Possibly including a link to the documentation steps: https://docs.microsoft.com/en-us/office365/customlearning/custom_translate_pl_ml

**Describe alternatives you've considered**

**Additional context**

**Comment by dcashpeterson** [comment]
@newgardj we changed this message in the V5 release.

**Comment by dcashpeterson** [comment]
This has been resolved in the V5 release
