### ISSUE TITLE
How do I incorporate the Dynamics 365 Learning Pathways into our corporate Microsoft 365 learning pathways SharePoint site?

### ISSUE THREAD

**Issue by a-rahm** [pnp/custom-learning-office-365#295]
### What is the context of your question

- [] Custom Content

### What is your question

We have provisioned the M365 learning pathways solution into our SharePoint tenant, which offers training for the common products such as OneDrive, Teams, SharePoint, etc. How do we incorporate the learning modules from the Dynamics 365 learning pathways (https://docs.microsoft.com/en-us/learn/dynamics365/?tab=tab-start-a-learning-path) into our site?

**Comment by juliemturner** [comment]
Doc.microsoft.com content doesn't really play nice as an asset... but you can try it by making a custom asset and setting the URL of that asset to: <docs.microsoft.com path>/?context=context%2Fchromeless&linktarget=true

So for the above link try:
`https://docs.microsoft.com/en-us/learn/dynamics365?context=context%2Fchromeless&linktarget=true`

I will tell you that in my experience almost all docs content doesn't want to be iframed and unfortunately, I have no ETA on when they might fix that issue.

**Comment by a-rahm** [comment]
Thank you Julie. We will try that. I hope this becomes part of the roadmap as this product evolves.
