### ISSUE TITLE
Asset in Custom Content Pack will be lost after Saving Details 

### ISSUE THREAD

**Issue by dborchers-gc** [pnp/custom-learning-office-365#296]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

I´ve added a custom content pack from my own GitHub Repository
https://dborchers-gc.github.io/gc-adoption/v4/

I want to add Sub-Categories and Playlists and assets with the Learning Administration but everytime i configure a new Playlist and click on save, it is lost.

In my Custom Playlist List i can see the custom added playlist 

### To Reproduce

Add a custom content pack and add a new sucategorie and playlist to your sub categorie and edit details and click on save.

### Expected behavior

-

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.

**Comment by dborchers-gc** [comment]
sorry the Version number is 4.0.0.0

**Comment by dborchers-gc** [comment]
This appears after saving details:
![2020-07-09 09_18_39-CustomLearningAdmin und 2 weitere Seiten - Geschäftlich – Microsoft​ Edge](https://user-images.githubusercontent.com/63800439/87009326-4d6e1700-c1c5-11ea-80e3-2287a9beffa6.png)

And this is my erro log from browser session:
![2020-07-09 09_18_26-](https://user-images.githubusercontent.com/63800439/87009372-5bbc3300-c1c5-11ea-96db-d34430fd1bcd.png)

What i´m doing wrong?

**Comment by juliemturner** [comment]
So I just tested adding custom content to a custom content pack and everything went fine so I think you've got some issue specifically in your environment. The error implies that there is a problem with the cached Custom Config... so you've actually got a problem before the problem you're encountering (convoluted right).

If you look at the first line from the console log image in your post, note how it says "... no configuration found for cdn..." basically it's looking for an entry in the CustomConfig list with a title of CustomConfig and the CDN with the guid matching your content pack and then Language of en-us. Check out the screen capture of my test environment:

![image](https://user-images.githubusercontent.com/7570936/87047412-7a6ff900-c1c8-11ea-85ee-3aca98c5075d.png)

So... I think this is your first problem.  Can you first check that list and see what you see, you know you're looking for a CDN with guid starting with 'ef742...'. If there is an entry but it's incomplete, you might just try deleting it and refreshing the page.  If there isn't one then, with the browser console open, based on just doing the refresh of the CustomLearningAdmin.aspx page, click on your content pack in the header and see what errors show up, once we solve whatever problem that is I think everything else will start working.

**Comment by dborchers-gc** [comment]
Hey i have the entry with the custom-content-pack guid. Or what do you mean?
![2020-07-09 15_59_53-Microsoft 365-Lernpfade - CustomConfig - All Items und 19 weitere Seiten - Gesch](https://user-images.githubusercontent.com/63800439/87049687-95109500-c1fd-11ea-8f35-9bec1821759f.png)

Adding SubCategories is working good but adding CustomPlaylists to CustomSubCategories doesnt work

**Comment by juliemturner** [comment]
Adding a subcategory is totally unrelated to the config, so that doesn't surprise me... So there are no errors in the console related to learning pathways when you first load the custom content pack in admin?

**Comment by dborchers-gc** [comment]
what do you mean with this?
"So there are no errors in the console related to learning pathways when you first load the custom content pack in admin?"

**Comment by juliemturner** [comment]
> with the browser console open, based on just doing the refresh of the CustomLearningAdmin.aspx page, click on your content pack in the header and see what errors show up, once we solve whatever problem that is I think everything else will start working.

**Comment by dborchers-gc** [comment]
![2020-07-09 16_09_51-CustomLearningAdmin und 19 weitere Seiten - Geschäftlich – Microsoft​ Edge](https://user-images.githubusercontent.com/63800439/87050585-bde55a00-c1fe-11ea-9312-c6e359d3096f.png)

When i open the admin (1) i will see this logs
![2020-07-09 16_09_15-Posteingang - Daniel Borchers@gc-gruppe de - Outlook](https://user-images.githubusercontent.com/63800439/87050620-ca69b280-c1fe-11ea-9b45-85010b46de03.png)

When i click on my content pack (2) i will see this
![2020-07-09 16_09_35-Posteingang - Daniel Borchers@gc-gruppe de - Outlook](https://user-images.githubusercontent.com/63800439/87050658-d5244780-c1fe-11ea-897c-79bce3fb8a25.png)

But sorry i dont really know how to read the reason in this log messages

**Comment by dborchers-gc** [comment]
wait...maybe i found it.

I only have the metadata.json in my repo folder and no playlists or assets json files

is that the reason?

I want to add assests and playlits only by admin-page - cause of that i didnt create them in my repo

**Comment by dborchers-gc** [comment]
here you see
![2020-07-09 16_14_41-● Untitled-4 - Untitled (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/63800439/87051038-5b408e00-c1ff-11ea-8799-1edd52ce166c.png)

**Comment by juliemturner** [comment]
Yes... exactly... if you start with line 5 of your second screenshot, I think you're issue is you haven't configured your custom CDN source properly. You can review my demo one to assist you: https://github.com/juliemturner/LPCDNDemo/tree/master/docs/v4

You need to have those files and that in general is how you would configure your playlists and assets but you don't have to, you can do them all as custom and built them through the UI.  But those files need to be there, I think if you just put them there with [] -- an empty array that should work but honestly I've never tried it.

**Comment by dborchers-gc** [comment]
Thanks Julie it works!

I only had to add teh Files with [] in it
