### ISSUE TITLE
[QUESTION] Error when entering "Custom Learning"

### ISSUE THREAD

**Issue by CWPTrainer** [pnp/custom-learning-office-365#297]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [] Installation
- [] M365 learning pathways web part

### What is your question

We provisioned a Learning Pathways site yesterday. When doing so, we received the error "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". As such, we deleted the site, and re-provisioned it. This time around, we got the following error when attempting to enter the Custom Learning module:

"Error: The value for "_instanceId" must not be undefined
in t in t in o in t in t in t in t in t in section in div in div in t in Styledt in t in o in t in t in t"

Can someone please assist regarding what might be wrong? 

Thanks. 

>Provide related screen-shots to help us understand your question
![Error](https://user-images.githubusercontent.com/68064956/87042307-c84e2680-c1f3-11ea-980e-c6a0445bf163.PNG)

**Comment by juliemturner** [comment]
Can you validate how you provisioned it, was it using the lookbook service?  If so I would suggest that you delete the site collection again, but this time also delete the solution out of the tenant app catalog. Also, make sure you permanently delete the site collection in the admin center under "Deleted Sites".

**Comment by juliemturner** [comment]
Since we haven't heard back I'm going to assume that you've either corrected the issue or have moved on.  We'd be happy to help further if you are continuing to have an issue please open a new issue and reference this one. I'd also suggest you follow some of the guidance outlined here as that can help.

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.
