### ISSUE TITLE
 Learning Pathway App V4.0 is not working in Edge and IE11

### ISSUE THREAD

**Issue by PASA365** [pnp/custom-learning-office-365#300]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

 Learning Pathway App 4.0.0.0 is not working in Edge and IE11 browser

### To Reproduce

1.  Open SharePoint site in Edge or IE. Click on "Microsoft 365 training" --> "Getting started with Microsoft Teams" from Top Navigation menu
2.  Learning Pathway App is not showing any content (Blank)

It is working in Chrome and Firefox browser. But failing in Edge and IE

### Expected behavior

Learning Pathway App should display the topics and content. Please fix the issue ASAP.

### Screenshots

Screenshot and browser console log is attached here
[LearningPathwayIssueLog_Edge.txt](https://github.com/pnp/custom-learning-office-365/files/4898805/LearningPathwayIssueLog_Edge.txt)
![ScreenShot_LearningPathWayIssue_Edge](https://user-images.githubusercontent.com/67079122/87076557-efa2f480-c1ef-11ea-9a9a-c91976889554.png)

### Learning Pathways version number

4.0.0.0

### Additional context

I tried to restore previous solution version in App catalog which does not help.

**Comment by NicolasRoelofs** [comment]
Hi, 
same problem with this error message :

[object Error]: {description: "Object doesn't support property or method 'addEventListener'", message: "Object doesn't support property or method 'addEventListener'", number: -2146827850, stack: "TypeError: Object doesn't support property or method 'addEventListener' at t (https://ramery.sharepoint.com/sites/AppCatalog/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/custom-learning-web-part_0054ab263c6954422421f453074f96de.js:1:551337) at Kl (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr-fr_37703d8180a4c9faf70078ef1b0fa789.js:1:1643155) at aa (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr-fr_37703d8180a4c9faf70078ef1b0fa789.js:1:1658754) at Oo (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr-fr_37703d8180a4c9faf70078ef1b0fa789.js:1:1695378) at ko (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr-fr_37703d8180a4c9faf70078ef1b0fa789.js:1:1679763) at bo (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr-fr_37703d8180a4c9faf70078ef1b0fa789.js:1:1676804) at po (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr-fr_37703d8180a4c9faf70078ef1b0fa789.js:1:1675393) at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr-fr_37703d8180a4c9faf70078ef1b0fa789.js:1:1637898) at t.unstable_runWithPriority (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr-fr_37703d8180a4c9faf70078ef1b0fa789.js:1:1593769) at dl (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr-fr_37703d8180a4c9faf70078ef1b0fa789.js:1:1637614)"}



description: "Object doesn't support property or method 'addEventListener'"


message: "Object doesn't support property or method 'addEventListener'"


number: -2146827850


stack: "TypeError: Object doesn't support property or method 'addEventListener' at t (https://ramery.sharepoint.com/sites/AppCatalog/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/custom-learning-web-part_0054ab263c6954422421f453074f96de.js:1:551337) at Kl (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr-fr_37703d8180a4c9faf70078ef1b0fa789.js:1:1643155) at aa (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr-fr_37703d8180a4c9faf70078ef1b0fa789.js:1:1658754) at Oo (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr-fr_37703d8180a4c9faf70078ef1b0fa789.js:1:1695378) at ko (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr-fr_37703d8180a4c9faf70078ef1b0fa789.js:1:1679763) at bo (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr-fr_37703d8180a4c9faf70078ef1b0fa789.js:1:1676804) at po (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr-fr_37703d8180a4c9faf70078ef1b0fa789.js:1:1675393) at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr-fr_37703d8180a4c9faf70078ef1b0fa789.js:1:1637898) at t.unstable_runWithPriority (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr-fr_37703d8180a4c9faf70078ef1b0fa789.js:1:1593769) at dl (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_fr-fr_37703d8180a4c9faf70078ef1b0fa789.js:1:1637614)"


__proto__: Object

**Comment by juliemturner** [comment]
Unfortunately, I cannot replicate this issue for the web part(s) themselves, by that I mean I tested the web part in stand-alone mode on the CustomLearningViewer.aspx and CustomLearningAdmin.aspx page in IE11 (the trickiest to get working) and both are loading just fine. I also tested the webpart on a page with other content and it also worked fine. Can you please test at least the CustomLearningViewer.aspx page on IE11 and see if that loads for you?

**Comment by PASA365** [comment]
The web part is loading in CustomLearningViewer.aspx and CustomLearningAdmin.aspx pages on IE11 and Edge. If i try to click on any learning topics in CustomLearningViewer.aspx it goes blank. Were you able to click through training module?
