### ISSUE TITLE
when user click the first link on the home page, they get Microsoft 365 learning pathways has a configuration issue error 

### ISSUE THREAD

**Issue by jzhou888** [pnp/custom-learning-office-365#301]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

some users consistently get "Microsoft 365 learning pathways has a configuration issue error" when they click the link from the home page.  error details can be found from the attached file.
<img width="731" alt="365learning_error" src="https://user-images.githubusercontent.com/26903315/87092923-f20e4a00-c201-11ea-91f8-c0259cd8587e.PNG">
<img width="546" alt="webpart_error" src="https://user-images.githubusercontent.com/26903315/87092957-fe92a280-c201-11ea-9bad-2819bbdc64b0.PNG">

### To Reproduce
I am the site collection admin and I am not getting the error at all.  However the normal users can get that error every time when clicking "Get started with Microsoft Teams" link

>Steps to reproduce the behavior

### Expected behavior

>A clear and concise description of what you expected to happen.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number
3.0
>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.
We have originally provisioned this site called ".../sites/o365learning" and I can access the admin page without a problem.  Recently I was told to provision another site for the same tenant called ".../sites/o365learning2".  The provision service didn't block me from doing this and the site was created.  Now I can access the admin page from "o365learning2" site, but not the original site.  See the errors from the console...Does it only allow to provision one o365learning site per tenant?

![image](https://user-images.githubusercontent.com/26903315/87095291-1835e900-c206-11ea-95cd-176042abeeaa.png)

**Comment by juliemturner** [comment]
If you could following this guidance from the top of the issue template:

>WEB PART NOT LOADING: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the Diagnosing Pre-Check guidance before submitting your bug.

**Comment by juliemturner** [comment]
Yes, you can only provision one instance of learning pathways per tenant, as the learning pathways site is meant to be a "source of truth" for instances of the viewer web part that can then be enabled and used in any site collection. For a complete overview of the architecture and usage patterns for learning pathways, I recommend you watch this video: https://www.youtube.com/watch?v=-sLXl_rKGxQ

To your specific error, there is a fairly simple fix... you need to choose one of the site collections to be the primary site and then make sure that's the configuration is updated to reflect that.  So if you want to keep .../sites/o365learning as the main one then you just need to delete .../sites/o365learning2... if you want 2 to be the main one then you need to run a PowerShell script to change where learning pathways looks for the main site collection. https://github.com/pnp/custom-learning-office-365/blob/master/webpart/UpdateM365lpSiteUrl.ps1

**Comment by techieSudeep** [comment]
Dear Julie,

I do have the same error. However, we have only 1 M365 Learning Pathways solution deployed in our tenant. Please find the attached screenshots and error logs. I appreciate your help in this regard. 
![CustomConfig](https://user-images.githubusercontent.com/52350666/87568508-c1139680-c693-11ea-9937-5d0cf1782759.jpg)


Also, I noticed there were duplicate items in the CustomConfig list. Please see the screenshot. What should be the default no of items and values?

![Error1](https://user-images.githubusercontent.com/52350666/87568357-87429000-c693-11ea-9239-9e63d710e4cb.jpg)
![Error2](https://user-images.githubusercontent.com/52350666/87568358-87db2680-c693-11ea-8f05-41fb07a12362.jpg)
[fhi360web.sharepoint.com-1594829038422.log](https://github.com/pnp/custom-learning-office-365/files/4926397/fhi360web.sharepoint.com-1594829038422.log)
[fhi360web.sharepoint.com-1594829074793.log](https://github.com/pnp/custom-learning-office-365/files/4926398/fhi360web.sharepoint.com-1594829074793.log)
[fhi360web.sharepoint.com-1594829081793.log](https://github.com/pnp/custom-learning-office-365/files/4926399/fhi360web.sharepoint.com-1594829081793.log)
[fhi360web.sharepoint.com-1594829088443.log](https://github.com/pnp/custom-learning-office-365/files/4926400/fhi360web.sharepoint.com-1594829088443.log)

Regards,
Sudeep



.

**Comment by jzhou888** [comment]
Yes Julie.  I ran the PowerShell script you are referring and the issue is gone now.  Thank you very much!
