### ISSUE TITLE
Users Activity 

### ISSUE THREAD

**Issue by Flasharrow** [pnp/custom-learning-office-365#303]
I have a query 

I want to see users activities on my Microsoft Learning Pathways Training Site, like which playlist they have finished watching can an admin see that? 

Any suggestions?? 

What will be the best approach?? Import Power BI or something else?? 

Cheers

**Comment by juliemturner** [comment]
I'm sorry, we don't provide any metrics, you can only get pageviews from SharePoint itself but that won't get you information about playlists watched unless you find some other way to correlate the data together. https://support.microsoft.com/en-us/office/view-usage-data-for-your-sharepoint-site-2fa8ddc2-c4b3-4268-8d26-a772dc55779e

**Comment by Flasharrow** [comment]
Thanks!! Julie
