### ISSUE TITLE
Unable to provision O365 learning pathway Site in our Multi tenant SharePoint environment.

### ISSUE THREAD

**Issue by ram5555ster** [pnp/custom-learning-office-365#304]
Hello,

I am trying to provision the o365 learning pathways site using the following solution page: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239

We have multi tenant SharePoint Online environment with custom domains. I get the below error message when i try provisioning the site. The error message says "Current site is not a tenant admin site"  even though i logged in as tenant admin to the SP admin site .  Can you please help me identify the problem?

![image](https://user-images.githubusercontent.com/31449895/87352125-880ae300-c528-11ea-9bd4-c0918dd2b47b.png)

**Comment by juliemturner** [comment]
So it seems like you're having an issue with the provisioning service. Per our notes you need to submit issues with it to the appropriate repo:

>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

That said, I would caution you that you can only have one learning pathways main site per tenant.  Please see this video for a complete overview of the solution: https://www.youtube.com/watch?v=-sLXl_rKGxQ
