### ISSUE TITLE
Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance.

### ISSUE THREAD

**Issue by techieSudeep** [pnp/custom-learning-office-365#306]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Similar bug related to #301. However, we only have 1 M365 Learning Pathways solution deployed to our tenant. Please find the attached screenshots and error logs. 

### To Reproduce

I am unable to view any of the Learning pages including admin page. 

### Expected behavior

>A clear and concise description of what you expected to happen.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

4.0.2
![CustomConfig](https://user-images.githubusercontent.com/52350666/87573755-6716cf00-c69b-11ea-84c4-f4f3b2fa2f12.jpg)
![Error1](https://user-images.githubusercontent.com/52350666/87573756-67af6580-c69b-11ea-81d0-cf3bf318e7d6.jpg)
![Error2](https://user-images.githubusercontent.com/52350666/87573757-67af6580-c69b-11ea-81fb-992ccf10c12c.jpg)
[fhi360web.sharepoint.com-1594829038422.log](https://github.com/pnp/custom-learning-office-365/files/4926696/fhi360web.sharepoint.com-1594829038422.log)
[fhi360web.sharepoint.com-1594829074793.log](https://github.com/pnp/custom-learning-office-365/files/4926697/fhi360web.sharepoint.com-1594829074793.log)
[fhi360web.sharepoint.com-1594829081793.log](https://github.com/pnp/custom-learning-office-365/files/4926698/fhi360web.sharepoint.com-1594829081793.log)
[fhi360web.sharepoint.com-1594829088443.log](https://github.com/pnp/custom-learning-office-365/files/4926699/fhi360web.sharepoint.com-1594829088443.log)

### Additional context

>Add any other context about the problem here.

**Comment by juliemturner** [comment]
Delete all the entries from the above list with the title "CustomConfig".  Then navigate to the CustomLearningAdmin.aspx page and see if the admin page reloads.

**Comment by techieSudeep** [comment]
> Delete all the entries from the above list with the title "CustomConfig". Then navigate to the CustomLearningAdmin.aspx page and see if the admin page reloads.

Unfortunately, that didn't work Julie. A blank page loads.

**Comment by juliemturner** [comment]
That's actually more than we had before... so now if you have a blank page, what's the browser console return.

**Comment by techieSudeep** [comment]
Please see the attached
![Error3](https://user-images.githubusercontent.com/52350666/87597275-89224880-c6bf-11ea-85b0-04a23c58d89f.jpg)
[fhi360web.sharepoint.com-1594847998074.log](https://github.com/pnp/custom-learning-office-365/files/4928031/fhi360web.sharepoint.com-1594847998074.log)

**Comment by juliemturner** [comment]
Try putting the query string parameter ?forceUpdate=V3 at the end of the CustomLearningAdmin.aspx page url. Then run the update... see if that fixes it.

**Comment by techieSudeep** [comment]
I still ran into the same issue. However, what I tried was restoring the latest CustomConfig item from the recycle bin and then forceupdate and it worked. Thank you very much for pointing me in the right direction. Appreciate your prompt response.

**Comment by juliemturner** [comment]
Oh right, yes sorry that would have to be there.  Great, glad you're all set.
