### ISSUE TITLE
URLs for Installing Custom Learning

### ISSUE THREAD

**Issue by MichaelCarr-MLC** [pnp/custom-learning-office-365#31]
What Urls are required to be opened on the firewall in order to run the .PNP?

**Comment by juliemturner** [comment]
The custom learning solution is only available in SharePoint Online, therefore there shouldn't be any firewall requirements.

**Comment by MichaelCarr-MLC** [comment]
Here is the message from my customer trying to run the install - 

_The site install didn’t work due to a web filter blocking some script URL at the very beginning of the process. I had a similar issue with the web part tile images after the test tenant site install.  In the prod site install scenario, the site said it was being provisioned via the confirmation message, but in reality no site was created. 

 It would help me when submitting URLs to be unblocked if I had a list of URLs that Microsoft is using when provisioning the site and when operating it._

Any ideas as to why they would get that type of error?

**Comment by juliemturner** [comment]
Was the customer trying to provision using PnP provisioning site?

I'm somewhat confused in that the second question indicates they successfully installed the solution in a test tenant?  The web part's data and images come from github for the most part, specifically https://pnp.github.io/custom-learning-office-365.

**Comment by batilcl** [comment]
I got error 404 when accessing this link
https://pnp.github.io/custom-learning-office-365/

**Comment by juliemturner** [comment]
@batilcl -- you're supposed to as it's not a valid endpoint it's a partial url to answer @MichaelCarr-MLC question about what url's they need to open up through their firewall...

**Comment by juliemturner** [comment]
Closed due to inactivity
