### ISSUE TITLE
issue with deployment - no content

### ISSUE THREAD

**Issue by Nima0912** [pnp/custom-learning-office-365#313]
I have issue with installation.
after provisioning, i never received the email and the URL is not accessible and i cannot find the M365LP under Site Collections.

My account is Global administrator.
![image](https://user-images.githubusercontent.com/68592464/88046644-a7b99100-cb50-11ea-850b-e5b537ac1e54.png)

I created a App Catalog with the same account.
![image](https://user-images.githubusercontent.com/68592464/88046900-08e16480-cb51-11ea-96c1-00a901625dea.png)

I used the provisioning link.
![image](https://user-images.githubusercontent.com/68592464/88047133-6fff1900-cb51-11ea-86aa-378916cf82a1.png)

I watched this tutorial but i never get the permissions request windows.
https://www.youtube.com/watch?v=Rj3U6ds-x1c
![image](https://user-images.githubusercontent.com/68592464/88047894-a0938280-cb52-11ea-8896-5f1386d402d6.png)

**Comment by juliemturner** [comment]
Unfortunately, I cannot assist you with issues with the provisioning service specifically.  See the note we have about getting support for the provisioning service:

>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).
