### ISSUE TITLE
Page content missing in Edge

### ISSUE THREAD

**Issue by barryanderson** [pnp/custom-learning-office-365#314]
## Describe the bug

When using MS Edge web parts are missing from pages but these pages render correctly in Chrome and Firefox.  Pages affected:

- Learning%20pathways%20Admin%20Success%20Center.aspx
- Get-started-with-OneDrive.aspx
- ... and more

### To Reproduce

1. Successfully deploy via MS Look Book.

1. Open in Edge.

### Expected behavior

I would expect page content to work in Edge if it is working in Chrome and Firefox.

### Screenshots

**In chrome:**
![chrome_success](https://user-images.githubusercontent.com/7723995/88158584-24597780-cc04-11ea-9481-dcfeb1579465.png)

**In Edge:**
![edge_missing_elements](https://user-images.githubusercontent.com/7723995/88158838-6c789a00-cc04-11ea-848f-c4a792d21979.png)

**Edge Console Errors:**
![console_error](https://user-images.githubusercontent.com/7723995/88158883-7b5f4c80-cc04-11ea-8628-2bdd3bdad44f.png)

**Edge Network Errors:**
![network_error](https://user-images.githubusercontent.com/7723995/88158916-85814b00-cc04-11ea-9908-896706f2fb97.png)

### Learning Pathways version number

4.0.0.0

**Comment by barryanderson** [comment]
I found the solution was to manually update the App Catalog with the latest version from GitHub, from 4.0.0 to 4.1.1:

https://github.com/juliemturner/custom-learning-office-365/blob/master/webpart/customlearning.sppkg

Edge starting working after this.

**Comment by juliemturner** [comment]
Yes... i was typing that very answer.  Glad you're all set.
