### ISSUE TITLE
[QUESTION] Re-provision learning pathways site

### ISSUE THREAD

**Issue by thingslu** [pnp/custom-learning-office-365#315]
### What is the context of your question

- [] Installation

### What is your question

I did an upgrade from version 3 to 4.0 multilingual version, I see that by design the pages of my site are not automatically translated. https://docs.microsoft.com/en-us/office365/customlearning/custom_overview_ml

Can I remove everything and install again? If yes, what is the procedure to do so?
Would that create the pages in all the languages like a greenfield deployment?

**Comment by juliemturner** [comment]
If you don't have any custom content yes, that is a completely reasonable thing to do... however, if you want the same site URL then you will need to delete the site, delete the app from the app catalog, and then delete the site permanently through the admin center.  Once that's done you should be able to use the lookbook site to completely reprovision and then yes you'll get the translations. This response also assumes you want your default site collection language to be English.  Also, you'll want to go back and deactivate any languages that you don't want to support as it does improve performance somewhat.

**Comment by thingslu** [comment]
Thanks, indeed that is my scenario. I followed the instructions and everything is working now.
