### ISSUE TITLE
[ENHANCEMENT] Allow custom pictures for subCategories 

### ISSUE THREAD

**Issue by JcBrabant** [pnp/custom-learning-office-365#317]
Each new custom subCategory use the same image. 
As all M365 apps are not currently available, I would create a subCategory for each and display the logo of the application as for the others subCategories.

**Comment by juliemturner** [comment]
The sub category image could be customized through the list item (by directly modifying the JSONData payload), this was workable but unfortunate. In version 4.x of the web part we added a UI to make the modification.
