### ISSUE TITLE
[QUESTION] Now that multilingual is available, can I delete the master site and start fresh?

### ISSUE THREAD

**Issue by benoitfournier** [pnp/custom-learning-office-365#319]
- [x] Installation
- [] Administration
- [] Custom Content
- [] M365 learning pathways web part

I provisioned a site months ago in english. Since I want my base language to be french, I need to create a new site collection in this language by default. 

I created a new site as instructed, upgraded the package and ran the PowerShell. This is working fine but I end up with 2 sites, the master being the old one.

Since we just explored the solution and that nothing of value was added, can I:
- Simply delete everything and start clean? If so, how?
- Run a script to make the new site the master and delete the old one?

Thanks

**Comment by juliemturner** [comment]
Can I just ask if you followed these instructions for installing this new version: [AddingMultilingualSupport.md](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/AddingMultilingualSupport.md#scenario-3-we-need-multilingual-support-and-the-default-language-of-the-site-collection-is-not-our-default-language)?

If so then I'm concerned that something isn't explained well as this should have left you with, yes 2 sites, but the second one (in your case the French site as the main site. 

Anyway, to answer your question I would repeat step 4 (and then 5 as well) making sure that you point the PowerShell script at the French site, that way we can be sure that the site is properly configured as the new master site.  When everything is working then go ahead and delete the original, English site.

**Comment by benoitfournier** [comment]
I did follow the steps and the PowerShell ran without issue. I thought that I needed to keep the old one.

If I have nothing to do, it's even easier than I expected. 

In the new site, I only have 2 pages (admin and viewer) and 3 lists (custom assets, config, and playlist). Home page was not touched (nothing added to the hero web part).

If it is what is expected, I will delete the old site.

**Comment by juliemturner** [comment]
Ok, but you said:

> This is working fine but I end up with 2 sites, the master being the old one.

If the script was run as it should have been the new French site should have ended up as the master not the old English one. Maybe I'm just misunderstanding you.

**Comment by benoitfournier** [comment]
How can I tell? From the instruction I understood that I was creating a additional / linked site. 

There are more chances that I am the one that did not understand the process.

**Comment by juliemturner** [comment]
Whichever sites can successfully load the  CustomLearningAdmin.aspx page is the master site. You can also tell because the `About Web Part` screen on the admin web part will give you details about your installation:

![image](https://user-images.githubusercontent.com/7570936/88712855-6002ae80-d0e8-11ea-98fa-bc190464cae7.png)

**Comment by benoitfournier** [comment]
Perfect then. You did a great job automating the deployment / upgrade.

![image](https://user-images.githubusercontent.com/49032965/88713559-7cebb180-d0e9-11ea-951e-1e40b12f9b3f.png)

I was expecting more work.

Very good / immediate support too! Thanks a lot Julie!

Benoit

**Comment by juliemturner** [comment]
I appreciate the feedback and glad you're all set.
