### ISSUE TITLE
periodically we are getting the following error for the custom learning webpart when accessing the page from IE

### ISSUE THREAD

**Issue by peterjkrebs** [pnp/custom-learning-office-365#32]
Not sure what is going on, but periodically we are getting the following error for the custom learning webpart when accessing the page from IE.  I never see it when using Chrome.  It’s random, sometime I can close my browser and reopen and the webpart displays fine.  It‘s not just when I have the webpart configured to display a custom playlist, it occurs when I display Microsoft articles for a product as well.  I don’t know why sometimes it works and other times does not. Right now it is not working and nothing I do resolves the issue: clear cache, private browsing mode, …
![image](https://user-images.githubusercontent.com/19641831/56248593-7143bb00-605d-11e9-8d0b-dffa19561e90.png)

**Comment by juliemturner** [comment]
Duplicate #18
