### ISSUE TITLE
Issue with upgrade to latest sppkg

### ISSUE THREAD

**Issue by prvanbeek** [pnp/custom-learning-office-365#323]
After uploading and deploying the new version, all the site pages are presenting this error:

Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.]

I ran the  UpdateM365lpCDN.ps1 PowerShell script as well, but it did not help. 

I also restored the custom assets and custom subcategories, but had no custom playlists. 

Still no joy.

**Comment by juliemturner** [comment]
I suspect you updated the web part but then did not go to the CustomLearningAdmin.aspx page, ergo the upgrade didn't happen.  Please go to the customlearningadmin.aspx page.  Based on the version of learning pathways that you had before you updated please append the following query string to the URL -- ?forceUpdate=v3 where the number 3 is the version your coming from. If it was version 2, then change the 3 to a 2.  Run the update and assuming it's successful then the admin page should load properly after you click close and if so then the rest of the pages should load.

**Comment by prvanbeek** [comment]
Yep. Sorry, missed that last step. Thanks for the quick help.
