### ISSUE TITLE
 Navigation Bar for End Users and Admin not applying site Theme Colors

### ISSUE THREAD

**Issue by snailCorpse** [pnp/custom-learning-office-365#325]
When you change the theme colors to a dark theme, the navigation bar for admin and end users are not applying the theme correctly. 

In our case we have a gold and black themed color scheme. In these color scheme, the text on the navigation is white on a white background

![image](https://user-images.githubusercontent.com/25774180/88901593-44ff7e00-d251-11ea-8f87-2206d90fc761.png)

**Comment by juliemturner** [comment]
We should be able to fix the navigation bar, that looks like a bug but the contents of the playlist are iframed in from support.office.com or docs.microsoft.com so they're going to remain black with white background as those sites do not support dark mode through the browser.

**Comment by juliemturner** [comment]
Please update to the newest version to take advantage of the fix.
