### ISSUE TITLE
New installation version 4.1.2 - Learning pathway has configuration issue when initialize admin page

### ISSUE THREAD

**Issue by zeebote** [pnp/custom-learning-office-365#327]
## Describe the bug

We follow instruction install the webpart in App catalog, create communication site, add the app to this new site collection, and ran the  M365lpConfiguration.ps1 with options AppCatalogAdminOnly and SiteAdminOnly.
When initialize with CustomLearningAdmin.aspx we got error: 
Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.] {CustomLearningAdminWebPart}

### Screenshots

>If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/63021919/88965333-78e1a000-d25f-11ea-9dc0-4ed144afb443.png)

![image](https://user-images.githubusercontent.com/63021919/88965160-33bd6e00-d25f-11ea-8a3c-5f0c617cd7e5.png)
![image](https://user-images.githubusercontent.com/63021919/88965272-5ea7c200-d25f-11ea-9c25-3512c1092f64.png)

![image](https://user-images.githubusercontent.com/63021919/88964810-c01b6100-d25e-11ea-9a61-2d2081c78bcc.png)

### Learning Pathways version number

4.1.2.0

**Comment by juliemturner** [comment]
What I need is the complete console log from the last screen shot... basically, all the errors from trying to load the `CustomLearningAdmin.aspx` page.

**Comment by zeebote** [comment]
Attached console log 
[console.txt](https://github.com/pnp/custom-learning-office-365/files/5003514/console.txt)

**Comment by juliemturner** [comment]
If you look at your browser network tab, I think I'm seeing that you're not able to load contents from the GitHub repo... Can you look for errors in the network tab please?  Specifically trying to load the file manifest.json.

**Comment by zeebote** [comment]
Got it, add pnp.github.io to FW whitelist, working now. Thank you for your help.
