### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by Dannyvzon** [pnp/custom-learning-office-365#328]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [X] Installation
- [] Administration
- [] Custom Content
- [] M365 learning pathways web part

### What is your question

> If i try to Provision the Microsoft 365 Learning pathways site trought the website, The App will install in the App Catalog site corretly ( version 4.1.2.0 ) But the Site that needs to be created won't work. This did work with version 3.0.0 ( app ). So it's not able to create the site for the Learning Pathways.

**Comment by juliemturner** [comment]
Can you help me understand, by giving me some detail, on what you mean by "the site that needs to be created won't work"?

**Comment by Dannyvzon** [comment]
Sure, when i go to https://provisioning.sharepointpnp.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239 and click on "add to your tenant" and fill in the from and press "provision", the app for sahrepoint will be added, but the Sharepoint site isn't created. I tried this on 3 different tenants without success.

**Comment by juliemturner** [comment]
Ok, then you're having issues with the provisioning service itself. Unfortunately, we cannot help you with that here you need to submit an issue to the provisioning service.
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).
