### ISSUE TITLE
Navigation and technology specific content 

### ISSUE THREAD

**Issue by AAnkitaAswal** [pnp/custom-learning-office-365#33]
I have a question on the navigation. I see technology specific page created  e.g 
 - Getting started with Microsoft teams
 - Getting started with OneDrive
 So if you are on ' Getting started with Microsoft teams' and then click 'product' (under breadcrumb navigation) and then select 'OneDrive' , you notice that the page remain the same but it load content related to OneDrive. So what is the need of 'Getting started with OneDrive' page if it cannot be linked.
I wanted to add OOB webpart e.g contact webpart for each technology pages as it will be different for each technology area , doing so by creating multiple page ends with above issue

**Comment by juliemturner** [comment]
The web part has various functions that can be configured via the web part properties.  A viewer page (CustomLearningViewer.aspx) is created by default, as a fixed known location that can be redirected to either for the full browsing experience or with query string parameters to navigate to particular content. After that you can put an instance of the Custom Learning web part on any page and configure it as either the full web part that bahaves like the instance on the CustomLearningViewer page, or by configuring it to be pinned to a particular Category, SubCategory, or Playlist/Asset.  You can also set the webpart to Content Only mode which will remove the breadcrumb navigation as well as the search feature and will allow you to specify a web part title.  

This documentation might help you some: [https://docs.microsoft.com/en-us/office365/customlearning/custom_overview](https://docs.microsoft.com/en-us/office365/customlearning/custom_overview)

**Comment by juliemturner** [comment]
Closed due to inactivity.
