### ISSUE TITLE
The viewer display an empty page on IE 11 or Edge (non-chrome-based) browsers

### ISSUE THREAD

**Issue by hadwinfung-woodside** [pnp/custom-learning-office-365#330]
## Describe the bug

The SPFX web part (CustomLearningViewer.aspx) will display an empty page on older browsers like IE 11 or Edge (non-Chrome-based version)

### To Reproduce

Open an older browser - IE 11 or Edge 44.18362.449.0 
Navigate to [SiteName]/SitePages/CustomLearningViewer.aspx and notice the page do not load. If you open developer toolbar within the browser, can see a bunch of JavaScript errors appearing in the console

### Expected behavior

The SPFX web page should render, the same experience if the user is using Google Chrome or Modern Edge (Chrome-based) browsers.

### Screenshots

[IE 11]
![CustomLearningViewer_IE](https://user-images.githubusercontent.com/66932230/89271089-d1a1a600-d66e-11ea-821b-62d68346c141.JPG)
[Edge]
![CustomLearningViewer_Edge](https://user-images.githubusercontent.com/66932230/89271133-dfefc200-d66e-11ea-9ea0-fef036ec38c9.JPG)
[Chrome]
![CustomLearningViewer_Chrome](https://user-images.githubusercontent.com/66932230/89271559-77edab80-d66f-11ea-8937-0ec29b081bf6.JPG)

### Learning Pathways version number

4.0.0.0

### Additional context

Hard to roll out enterprise-wide training to users if the default browser on SOE are the 'older' browsers like IE 11 & Edge, which is very common across large enterprise due to backward compatibility reasons.

**Comment by juliemturner** [comment]
You need to update to the latest version (4.1.2), there was a bug, it was fixed.

**Comment by hadwinfung-woodside** [comment]
Thanks Julie. Updated to 4.1.2 today. Happy to confirm it is working.
[IE 11]
![CustomLearningViewer_Working_IE](https://user-images.githubusercontent.com/66932230/89376283-0d497800-d722-11ea-9149-89e87bf64e02.JPG)
[Edge]
![CustomLearningViewer_Working_Edge](https://user-images.githubusercontent.com/66932230/89376299-15091c80-d722-11ea-9551-d9f984dd0e05.JPG)

Did notice some other issue while testing but I will raise a separate issue/bug for that. Thanks!
