### ISSUE TITLE
Add custom audience entries?

### ISSUE THREAD

**Issue by ian365** [pnp/custom-learning-office-365#331]
- [Y] Administration

### What is your question

Is it possible to add custom audience entries so that some of the options match our organisation? 
 
I would then be able to offer playlists suited to different audiences about the same app. Without this would I have to add separate custom subcategories for different teams using the same app?

thanks, Ian

**Comment by juliemturner** [comment]
No, we do not have a way to customize the audience metadata for the content that Microsoft provides you.  You would need to create your own custom content pack to do that, which you could do by copying and customizing the Microsoft provided content in the docs library of this repo and hosting it yourself. More information on custom content packs can be found in the overview video: https://www.youtube.com/watch?v=-sLXl_rKGxQ
