### ISSUE TITLE
 Firefox Can't Open Page error on video content

### ISSUE THREAD

**Issue by barryanderson** [pnp/custom-learning-office-365#333]
## Describe the bug

Error viewing video content within Firefox.

### To Reproduce

Using Firefox open the site, visit any of the "Getting Started with pages", select a video.

### Expected behavior

I expect the video to play.

### Screenshots

![image](https://user-images.githubusercontent.com/7723995/89391159-b9c63280-d6ff-11ea-8470-48f0c1d1d186.png)

### Learning Pathways version number

4.1.2

**Comment by juliemturner** [comment]
I suspect that Firefox is not supported for these videos on support.office.com since we are just iFraming the content in, it's not an issue I can provide support for here. I will let the team know, and hopefully they can pass it on to that team to look into.
Thanks for reporting it.

**Comment by matthewjob** [comment]
@barryanderson same/similar issue with Edge/Chrome
https://github.com/pnp/custom-learning-office-365/issues/341

Could try changing the Firefox referrer policy https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy as a workaround.

**Comment by juliemturner** [comment]
This issue has been fixed. Thanks everyone.
