### ISSUE TITLE
 After provisioning all tenant sharing controls were changed to no external sharing

### ISSUE THREAD

**Issue by jkuter** [pnp/custom-learning-office-365#336]
## Describe the bug

After provisioning the tenant sharing settings were set back to internal only for sharepoint and onedrive, this was not expected and was confirmed by the audit logs

### To Reproduce

Sharing is set to Anyone for OneDrive and SharePoint
Deploy the solution
Sharing is set to internal only

### Expected behavior

I did not expect this solution to change my sharing settings for the tenant

### Learning Pathways version number

4.1.2.0

### Additional context

Just followed the instructions on the site, nothing special happened

**Comment by jgledhill79** [comment]
We have just had the exact same issue happen to us. Audit log shows my account changing the sharing permissions for the entire tenant at the exact time the learning pathways site was provisioned. 

I've raised a premier support call with Microsoft for this.

**Comment by juliemturner** [comment]
Unfortunately, this is not an issue with learning pathways but an issue with the lookbook.microsoft.com provisioning service. I believe it's fixed but not sure exactly of the status.

**Comment by juliemturner** [comment]
I've been informed that the bug has been fixed in the provisioning service.
