### ISSUE TITLE
Adjusting HTML Field Security

### ISSUE THREAD

**Issue by acxparrish** [pnp/custom-learning-office-365#338]
### What is the context of your question

- M365 learning pathways web part - Embed

Is there a way to access the site administration options under settings that would allow me to access the HTML Field Security section? There is content that I would like to embed, but can't because the sites need to be allowlisted.

**Comment by juliemturner** [comment]
So, learning pathways does not use HTML Field Security. I'm going to try and read between the lines of your question and assume your issue is you want to embed a URL to some piece of content as an asset in a playlist? The direct way to do that is to create a SharePoint page and use the embed web part...

![image](https://user-images.githubusercontent.com/7570936/90178842-8d9f5700-dd7a-11ea-8d12-0540273295de.png)

**Comment by acxparrish** [comment]
I am creating a news post or sharepoint page and want to embed a calendly.com link so people are able to click and schedule a time. However, when I paste the link into the embed field it says that “calendly.com” needs to be added to the approved list in the HTML field security section of the site settings. I am able to do this to all other sharepoint sites except this one which is a buzz kill because the IT dept just moved our whole knowledge base to learning pathways and I can’t generate the kind of news posts I’d like without having to create them from our intranet site.

v/r,
Andrew<https://www.aau.edu/who-we-are/leadership-staff/andrew-parrish>, AAU

**Comment by juliemturner** [comment]
Ok, now I understand what you're asking about, but there is nothing special about this site collection that would prevent you from making that adjustment. Here's a blog post by the SharePoint Maven that walks you through the setting: https://sharepointmaven.com/how-to-embed-content-from-other-websites-in-sharepoint-online/

You need to be a site administrator, maybe you do not have the permissions you need?

**Comment by acxparrish** [comment]
This is what it should look like: [cid:image001.png@01D67190.0388E1E0]

But this is what I see:
[cid:image002.png@01D67190.0388E1E0]


There is no site collection administration for the learning pathways site.

v/r,
Andrew<https://www.aau.edu/who-we-are/leadership-staff/andrew-parrish>, AAU

**Comment by juliemturner** [comment]
Right but that issue is because you're not a site collection admin, not because there is anything special about the site.

**Comment by acxparrish** [comment]
Sorry! Thank you for sticking with me there until I had the “a-ha!” moment. I get most of the keys to the kingdom, but it turns out I didn’t get this one.

v/r,
Andrew<https://www.aau.edu/who-we-are/leadership-staff/andrew-parrish>, AAU
