### ISSUE TITLE
 Disabling language translation support causes the home page news web part to populate with posts from every supported language

### ISSUE THREAD

**Issue by dfwlonghorn** [pnp/custom-learning-office-365#339]
## Describe the bug
Disabling language translation support causes the home page news web part to populate with posts from every supported language

### To Reproduce
Once the Microsoft 365 learning pathways site has been successfully provisioned, as a site owner

1. From the Home page open Site Settings (gear icon at top-right of page)
2. Click **Site Information**
3. Click **View all site settings**
4. Under Site Administration click **Language Settings**
5. Under Site languages toggle to **Off** the **Enable pages and news to be translated into multiple languages**

Once you return to the home page, instead of seeing just the default english news post of "Make a difference. Become a Champion" multiple instances of the same post are visible for each language supported.

### Expected behavior
The expectation was that the site would disable features to allow a user to translate the site from our default language, English and that all web parts would display English only content. For this issue, it seems the News web part is the only section exhibiting an unexpected behavior.

### Screenshots
![image](https://user-images.githubusercontent.com/26234965/90271467-7b2c2880-de21-11ea-83df-f222a6dbcf9a.png)

### Learning Pathways version number
App Version 4.1.2.0

**Comment by juliemturner** [comment]
Unfortunately, this is a OOB multilingual pages behavior and is not related to learning pathways itself. I know someone involved in that aspect of SharePoint so I can pass it on but I think the only solution is to delete those pages since you turned those languages off.

**Comment by dfwlonghorn** [comment]
@juliemturner If I delete those pages and we decide to re-enable multilingual support, I assume these pages would not somehow be restored?

**Comment by dfwlonghorn** [comment]
I went ahead and unpublished instead of deleting those pages so we have the option to re-enable multilingual support in the future if needed.
