### ISSUE TITLE
Playlist dropdown menu field length [ENHANCEMENT] 

### ISSUE THREAD

**Issue by joslange** [pnp/custom-learning-office-365#342]
**Is your feature request related to a problem? Please describe.**
The dropdown menu showing the different assets in a playlist is automatically adjusting to the length of the current article you're in. For short asset titles, if will only display the same amount of letters as the current name, making it very difficult to read.

**Describe the solution you'd like**
Either set a default length to the dropdown menu, or default it to the longest asset title in the list.

**Additional context**
Here's an image from one of the default playlists, with a very short asset title. All other pages in the list are impossible to read
![image](https://user-images.githubusercontent.com/57677822/90600683-4b9d6780-e1f7-11ea-94d3-d21b2fded915.png)

**Comment by juliemturner** [comment]
Can you please validate what version of the solution your using, this was updated in version 4... you may be using an outdated version?

**Comment by joslange** [comment]
Yes, thanks for clarifying, this seem to be fixed in v4, getting the solution updated now.
