### ISSUE TITLE
[QUESTION] Pathways performance in Teams

### ISSUE THREAD

**Issue by effothlo217** [pnp/custom-learning-office-365#343]
Has anyone come across the performance difference between opening up Pathways directly from the browser vs. opening it up in Teams.  We have notice that it can take up to 10-15 seconds to load in Teams.  Navigating to the different training tabs takes longer than expected too.  Is this normal behavior?

**Comment by juliemturner** [comment]
You're authenticating and then dynamically loading the SharePoint page into an iFrame so, yeah, I think it could absolutely take longer.
