### ISSUE TITLE
[I'm experiencing a config issue! I tried both install M365 learning path web part with Edge and chrome without success!] 

### ISSUE THREAD

**Issue by TestAppBakina** [pnp/custom-learning-office-365#344]
![Screenshot 2020-08-24 16 04 39](https://user-images.githubusercontent.com/50297316/91053831-b699d480-e623-11ea-824b-6a0492903683.png)
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [] Installation
- [] Administration
- [] Custom Content
- [] M365 learning pathways web part

### What is your question

>Provide related screen-shots to help us understand your question

**Comment by juliemturner** [comment]
I will need more information to assist you. Right under the image you posted is a message mentioning the error with a link to how to diagnose the issue and that link will tell you what information to post to help us assist you.  Thanks.

**Comment by TestAppBakina** [comment]
Thanks to reaching me once again!
The browser Console log provides the following error msg: "CustomLearningWebPart (configCDN) -- Could not get a valid configuration; Please contact your learning administrator." something not really explicit at all... 
![Screenshot 2020-08-24 18 00 47](https://user-images.githubusercontent.com/50297316/91069541-d639f880-e635-11ea-8587-b91460adcd9b.png)

**Comment by juliemturner** [comment]
Thanks for posting. Looking at the screen capture you included I can see 3 errors up from the one you highlighted shows that it cannot get the MicrosoftCustomLearningSite Tenant Property it needs to run the configuration.  Could you please help me understand how you provisioned learning pathways, did you use the [Microsoft Lookbook](http://lookbook.microsoft.com/) or do a manual provision using the PowerShell scripts and [manual instructions](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/README.md) in this repo?

**Comment by rhajj19** [comment]
Hello Team, what URLs need to be whitelisted for the above learning pathways solution to work ?

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
