### ISSUE TITLE
I just tried to upgrade version 4.1.3 and I got a configuration error

### ISSUE THREAD

**Issue by jamiet7611** [pnp/custom-learning-office-365#346]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [x
![pathways error log](https://user-images.githubusercontent.com/70286940/91340393-92fa9980-e79d-11ea-9471-4256ed609e70.png)
] Installation
- [] Administration
- [] Custom Content
- [] M365 learning pathways web part

### What is your question

>Provide related screen-shots to help us understand your question

**Comment by juliemturner** [comment]
I assume you were upgrading from v3.x.  Unfortunately, not a lot of information there.  You can force the upgrade to run again by going to the customlearningadmin.aspx page and adding the `?forceUpdate=V3` to the end of the URL (assuming you're upgrading from v3) and that will run it again in case it was just a network error.  But since it might not be, please open your browsers development console before you start the upgrade again so that we can see what errors appear there and hopefully get more details to help solve your issue.

**Comment by jamiet7611** [comment]
Sorry I didn't get back with you sooner, I was on vacation.  I just tried running ?forceUpdate=V3 and it seem to run without any errors.  I'm still getting the same error message when I go to the admin page or try to go to any page other page besides the home page.  This is the errors I'm seeing when I do an F12:

custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1 Message: TypeError: Cannot read property 'length' of undefined - DataService (refreshCache)
e.log @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
e.log @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
e.write @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
a @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
Promise.then (async)
c @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
a @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
Promise.then (async)
c @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
k @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
e.refreshCache @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
a @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
Promise.then (async)
c @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
a @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
Promise.then (async)
c @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
O @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
e.doInit @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
ft @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
t.configCDN @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
ft @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
t.firstInit @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
(anonymous) @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
ft @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
t.onInit @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
t._onInViewport @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
(anonymous) @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
t._internalFirstTimeRender @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
e._renderWebPart @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
(anonymous) @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
Promise.then (async)
e.loadWebPart @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
n._loadWebPart @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
t.componentDidMount @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
To @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
CO/T.t.unstable_runWithPriority @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
dl @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
xo @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
po @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
(anonymous) @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
CO/T.t.unstable_runWithPriority @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
dl @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
vl @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
ml @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
go @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
Jo @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
render @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
_render @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
e.render @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
t._renderSingleCanvasCore @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
t._renderCanvas @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
t._tryRenderSingleCanvas @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
t._tryRenderCanvas @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
(anonymous) @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
Promise.then (async)
a._onFieldsLoad @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
(anonymous) @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
w @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
e.processAction @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
e.dispatch @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
t._endInitialize @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
(anonymous) @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
Promise.then (async)
t.componentDidMount @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
t.componentDidMount @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
To @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
CO/T.t.unstable_runWithPriority @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
dl @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
xo @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
co @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
Ho @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
Qo @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
(anonymous) @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
go @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
Jo @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
render @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
t.onRender @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
t._renderCoreRouter @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
t.onRender @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
t._render @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
(anonymous) @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
Promise.then (async)
e._initializeApplication @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
(anonymous) @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
Promise.then (async)
e._initializeApplicationWithTelemetry @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
e.startApplication @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
e.navigate @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
e.navigateToApplication @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
e._navigateToApplication @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
e._executePlatformCode @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
e._startApplication @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
e.startApplication @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
e._startApplication @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
e._startApplication @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
(anonymous) @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
Promise.then (async)
e.start @ sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1
loaderStart @ Get-started-with-Microsoft-Teams.aspx:109
startSpfx @ Get-started-with-Microsoft-Teams.aspx:121
(anonymous) @ Get-started-with-Microsoft-Teams.aspx:148
(anonymous) @ Get-started-with-Microsoft-Teams.aspx:152
suiteux.shell.tokenfactoryiframe.910aef7b77143f90b637.js:28 Uncaught DOMException: Blocked a frame with origin "https://webshell.suite.office.com" from accessing a cross-origin frame.
    at n.getRequestInfo (https://shell.cdn.office.net/shellux/o365/versionless/suiteux.shell.tokenfactoryiframe.910aef7b77143f90b637.js:28:16132)
    at n.handleWindowCallback (https://shell.cdn.office.net/shellux/o365/versionless/suiteux.shell.tokenfactoryiframe.910aef7b77143f90b637.js:28:19948)
    at new e (https://shell.cdn.office.net/shellux/o365/versionless/suiteux.shell.tokenfactoryiframe.910aef7b77143f90b637.js:37:28280)
    at e.init (https://shell.cdn.office.net/shellux/o365/versionless/suiteux.shell.tokenfactoryiframe.910aef7b77143f90b637.js:37:29160)
    at https://webshell.suite.office.com/iframe/TokenFactoryIframe:21:65
n.getRequestInfo @ suiteux.shell.tokenfactoryiframe.910aef7b77143f90b637.js:28
n.handleWindowCallback @ suiteux.shell.tokenfactoryiframe.910aef7b77143f90b637.js:28
e @ suiteux.shell.tokenfactoryiframe.910aef7b77143f90b637.js:37
e.init @ suiteux.shell.tokenfactoryiframe.910aef7b77143f90b637.js:37
(anonymous) @ TokenFactoryIframe:21
outlook.office.com/:1 POST https://outlook.office.com/owa/ 403

Also, this is the error that I'm seeing on all of the pages:
Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.]_

Please let me know if you need anything else.  Thank you

**Comment by jamiet7611** [comment]
Sorry didn't mean to close

**Comment by jamiet7611** [comment]
I'm also seeing this error come up as well:

SEC7120: [CORS] The origin 'https://c.sharepoint.com' did not find 'https://c.sharepoint.com' in the Access-Control-Allow-Origin response header for cross-origin  resource at 'https://waconatm.officeapps.live.com/apc/trans.gif?8259c9b8786d18e30bd48df1941119f5'.

**Comment by juliemturner** [comment]
You've clearly got an error in your cache.  Please delete any items in the CustomConfig list with a title "CustomConfig".  There may be items with titles other than "CustomConfig" do not delete those.  Then go back to the CustomLearningAdmin.aspx page and refresh the page.

**Comment by jamiet7611** [comment]
Can I just rename it in case I have to go back to the previous version?  I've had to do that each time I try to upgrade to 4.1.3.  Thank you.

**Comment by juliemturner** [comment]
It gets regenerated each time the admin page loads, but the path through that load is a bit cleaner if it doesn't already exist. You can certainly rename it but it has no materialistic benefit for going back to a previous version and really isn't part of your issue.  If that makes you feel better though, yes feel free to rename it.

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
