### ISSUE TITLE
Is the Welsh Language going to be supported?

### ISSUE THREAD

**Issue by pkbullock** [pnp/custom-learning-office-365#348]
### What is the context of your question

- [X] Installation
- [ ] Administration
- [ ] Custom Content
- [ ] M365 learning pathways web part

### What is your question

Are there plans to support the Welsh Langauge? majority of my customers are based in Wales, UK, where there is an act, the Welsh Language Standards to provide software bi-lingually. I typically get asked whether certain systems, templates etc are bi-lingual. 

If not no worries, just asking.

**Comment by juliemturner** [comment]
I do not really know the plans for the future but a good way to get a hint is if support.office.com supports Welsh.  If not then probably not anytime soon, if yes, then... maybe.

**Comment by pkbullock** [comment]
Ah, it doesn'y look like the support site supports Welsh. Cool thanks, ill close, I have the answer. Thank you as always :-)
