### ISSUE TITLE
How i enable multilingual in learning pathways in sharepoint[QUESTION] 

### ISSUE THREAD

**Issue by niketapanjvani** [pnp/custom-learning-office-365#349]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [] Installation
- [] Administration
- [] Custom Content
- [] M365 learning pathways web part

### What is your question

>Provide related screen-shots to help us understand your question

**Comment by niketapanjvani** [comment]
how we enable multilingual in sharepoint

**Comment by juliemturner** [comment]
Here's the exact spot in the docs: https://docs.microsoft.com/en-us/office365/customlearning/custom_update#set-language-settings

But for more information on SharePoint multilingual publishing support I would start here: https://techcommunity.microsoft.com/t5/microsoft-sharepoint-blog/new-sharepoint-feature-multilingual-publishing-for-pages-and/ba-p/1432445
