### ISSUE TITLE
Could not find Custom Learning Web Parts

### ISSUE THREAD

**Issue by cclay29** [pnp/custom-learning-office-365#35]
It appears that CustomLearninViewer.aspx is being created but CustomLearningAdmin.aspx is not being created... what could I be missing here?

When running the manual installation of the custom learning center I receive this error.

Get-PnPAvailableClientSideComponents : Object reference not set to an instance of an object.
At line:155 char:13
+         if (Get-PnPAvailableClientSideComponents -page CustomLearning ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPAvailableClientSideComponents], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.ClientSidePages.GetAvailableClientSideComponents
 
and this error 

Get-PnPAvailableClientSideComponents : Object reference not set to an instance of an object.
At line:164 char:11
+     if (!(Get-PnPAvailableClientSideComponents -page CustomLearningAd ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPAvailableClientSideComponents], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.ClientSidePages.GetAvailableClientSideComponents

**Comment by ToddKlindt** [comment]
I screwed that up, sorry about that. I'll fix that and post an update today or tomorrow. If you want to get past it before that in lines 155 and 164 you can replace the admin page reference, CustomLearningAdmin.aspx, with the viewer page, CustomLearningViewer.aspx.

**Comment by juliemturner** [comment]
Fixed by @ToddKlindt in #36
