### ISSUE TITLE
[QUESTION] DOCS Microsoft Stream content gives "Refused to connect" error

### ISSUE THREAD

**Issue by Celestero** [pnp/custom-learning-office-365#353]
### What is the context of your question

- [] Installation
- [] Administration
- [x] Custom Content
- [] M365 learning pathways web part

### What is your question

How do you add stream videos to custom playlist? 
When I add the URL of a Microsoft Stream videa as a new asset to a custom playlist I receive a "refused to connect" error

**Comment by Celestero** [comment]
Here's a preview of the error message I receive. It doesn't matter what video I choose to add from Stream I receive the same error. Is something preventing stream videos from being added to playlist? Maybe permissions?
![streamerror](https://user-images.githubusercontent.com/55710892/92528495-796e3e80-f1ee-11ea-844f-9dfdb211f021.jpg)

**Comment by eemancini** [comment]
I am also receiving a connection error message but it is specific to docs.microsoft.com content. These pages all refuse to connect to LP:
https://docs.microsoft.com/en-us/stream/portal-get-started
https://docs.microsoft.com/en-us/stream/portal-upload-video
https://docs.microsoft.com/en-us/stream/portal-create-screen-recording
https://docs.microsoft.com/en-us/stream/portal-edit-trim
https://docs.microsoft.com/en-us/stream/portal-add-subtitles-captions
![Docs](https://user-images.githubusercontent.com/61661610/92528796-5dbb6600-f1f7-11ea-813b-4235d3846a61.PNG)

**Comment by juliemturner** [comment]
@Celestero you cannot directly embed content from Microsoft Stream as an asset, you need to create a sharepoint page, embed the stream content on the page and then use that page as an asset. I didn't understand that and thought you were referencing what @eemancini was referencing was that you can't use a docs page as an asset.

**Comment by Celestero** [comment]
@juliemturner can you directly embed videos from other platforms such as YouTube?

**Comment by juliemturner** [comment]
No, you need to embed them on a SharePoint page first.  Theoretically some content that supports being iFramed would work but I can say that Stream and YouTube are not ones.
