### ISSUE TITLE
[QUESTION] How Secure is the EnterPrise Application that gets hosted in Azure as a result of installing 'Learning Pathways'

### ISSUE THREAD

**Issue by robertwarwick** [pnp/custom-learning-office-365#355]
### How Secure is the EnterPrise Application that gets hosted in Azure as a result of installing 'Learning Pathways' ?

- [] Installation
- [] Administration
- [] Custom Content
- [] M365 learning pathways web part
- [x] Security

When we attempt to deploy Learning Pathways to our tenant it asks for a set of permissions that seem quite concerning as in the screenshot below:

![image](https://user-images.githubusercontent.com/20759063/92580571-71fa7400-f286-11ea-9b7d-66e65d4ab0b9.png)

Please advise how safe this component is to leave in place in our tenant during and beyond the provisioning process?

**Comment by juliemturner** [comment]
You're asking a question about the lookbook service not learning pathways.  I can tell you that it's fine to remove the certificate from your tenant after it's provisioned.  The lookbook service itself is run by Microsoft and the PnP Team but it's up to you to trust that group or not trust it.  If you want, you can also manually provision learning pathways but it's a reduced experience in that it doesn't include any of the "templated" pages that are intended to get you started using learning pathways and are not necessary for the functioning of the solution, but some people are confused so I thought I would mention it. You can find the manual provisioning information here: https://github.com/pnp/custom-learning-office-365/tree/master/webpart

**Comment by robertwarwick** [comment]
Many thanks Julie - This helps!
