### ISSUE TITLE
[QUESTION] Are copied list updated?

### ISSUE THREAD

**Issue by benoitfournier** [pnp/custom-learning-office-365#356]
### What is the context of your question

- [] Installation
- [x] Administration
- [x] Custom Content
- [] M365 learning pathways web part

### Details
My understanding is that if we copy a playlist, content (assets) added or removed from the original playlist will not be reflected on the copy. But, if an asset from the original playlist is updated, then it will also be updated in the copy.

Am I right? 

We will be doing custom content and the behaviour will dictate if we add our content in seperate lists or if we reuse / enhance ootb ones. We don't want to miss some new content because we used copied / custom playlists.

**Comment by juliemturner** [comment]
Yes, that is correct.

I would suggest to you that the likeliness of them adding/removing assets in playlist is very small, not that it couldn't happen but unlikely. That they might add/remove playlists is more likely.

**Comment by benoitfournier** [comment]
Thanks again for the quick answer.
