### ISSUE TITLE
Support Page Inventory

### ISSUE THREAD

**Issue by pkbullock** [pnp/custom-learning-office-365#357]
### What is the context of your question

- [ ] Installation
- [X] Administration
- [ ] Custom Content
- [ ] M365 learning pathways web part

### What is your question

Is there a list or way of getting a list of all the support article options from the website? I will be soon deploying this on a client site, to build custom playlists from articles, just wondering if there is a list somewhere of all available articles ideally, with enough metadata to setup the playlists?

**Comment by juliemturner** [comment]
I'm sorry but I'm not sure I understand your question. A list of all the articles currently included as assets or a list of all content on support.office.com?

**Comment by pkbullock** [comment]
The list of content on support.office.com. AFAIK learning pathways has select articles, looking for a reference on what else can be added, rather than sift through the site for the links.
