### ISSUE TITLE
 Playlists for Microsoft loaded content not showing with Chromium Edge Browser

### ISSUE THREAD

**Issue by RLowery-King** [pnp/custom-learning-office-365#358]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Users with latest Chromium Edge browser are getting "www.microsoft.com refused to connect" error when trying to access the built in playlist provided by Microsoft Learning Pathways.

### To Reproduce

Users click on "Get Started with OneDrive" then click on any of the embedded content that was preloaded from Microsoft when the site collection was set up and get the error.

### Expected behavior

Users should be able to see the content embedded in the iFrame when clicking on any of the assets in the playlist.

### Screenshots

>If applicable, add screenshots to help explain your problem.
[MSLP-ChromiumEdge-Issue.docx](https://github.com/pnp/custom-learning-office-365/files/5210833/MSLP-ChromiumEdge-Issue.docx)

### Learning Pathways version number

>4.1.3.0

### Additional context

>Add any other context about the problem here.

**Comment by juliemturner** [comment]
I just tested the same playlist/asset with the same version of Chromium Edge and didn't have a problem, can you test again? The issue would be with the underlying content although in certain cases with custom assets pointing to docs.microsoft.com I have seen similar issues but that is not the case here as the item in question is on the support.office.com site.

**Comment by RLowery-King** [comment]
The user is still getting the same error. As long as he is using his work profile in Edge (I don't have the issue but I don't have my Edge sync'd to a profile). If same user signs uses a guest profile, he can see the content. What could be contained in his work profile that would stop the content from being displayed?

**Comment by juliemturner** [comment]
Wow, that's an interesting issue... And for sure it must be related because the Edge instance i used was also sync'd with a profile so that would then indicate that it's not specific to that aspect. 

Can you get me an exported browser console log?

**Comment by RLowery-King** [comment]
[Console log.txt](https://github.com/pnp/custom-learning-office-365/files/5225507/Console.log.txt)

I hope this is the log you are looking for. If not, you'll need to tell me how to obtain what you are looking for in Chromium Edge browser.

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
