### ISSUE TITLE
Missing Stream workload

### ISSUE THREAD

**Issue by SofiaMaxe** [pnp/custom-learning-office-365#360]
## Describe the bug

Microsoft Stream playlists are nowhere to be found in list of workloads

### To Reproduce

Navigate to CustomLearningAdmin.aspx
Look for Stream

### Expected behavior
Stream is listed and can be hidden/shown

### Screenshots

>If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/46747966/93056356-99798400-f66c-11ea-9e7a-dd2a3958109e.png)

### Learning Pathways version number

VERSION | 4.1.3.0
-- | --
RELEASE DATE | September 2020

**Comment by juliemturner** [comment]
Yes, there is no stream content available as of yet. There had been tests for some Stream content but there is issue with the source material and so its inclusion was scrapped until those things could be solved.
