### ISSUE TITLE
Content is missing from the Teams section.  Specifically  Notifications in Teams.   Who do we report this too?   

### ISSUE THREAD

**Issue by gmhor229** [pnp/custom-learning-office-365#361]
![image](https://user-images.githubusercontent.com/67379026/93243454-36641c00-f756-11ea-9fc7-8324a3cfc893.png)

**Comment by juliemturner** [comment]
You would report it here, in general but... there is no Notifications in Teams asset in the "Intro to Microsoft Teams" playlist that I see.  Can you please provide the version of the learning pathways solution you're using?

**Comment by gmhor229** [comment]
Julie

I apologize.  How can I find out what version of Learning Pathways we are using?

Gerry

**Comment by gmhor229** [comment]
We are on version 3.0.0.0.   We are currently updating it.  However the assets were there previously.  Did it get removed?

**Comment by juliemturner** [comment]
>FYI, you may want to be careful about responding to email to post your response in GitHub as your personally identifiable information does end up in the body of the issue. 

As far as the asset being removed, based on what you showed me it would be more of a matter of the page on support.office.com or docs.microsoft.com as having been removed. That said I did just a quick search and can find no reference to us ever having an asset called "Notification in Teams"... is it possible it was a custom asset?

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
