### ISSUE TITLE
SharePoint Content Lacking

### ISSUE THREAD

**Issue by Smithenstein** [pnp/custom-learning-office-365#362]
I noticed there is no content around document management (uploading, editing, tagging, etc.) in the SharePoint area.  Are there plans to release more content in this area?  Thanks

**Comment by samanro** [comment]
Those are more user features than admin - see content and training at https://support.microsoft.com/en-us/sharepoint

**Comment by juliemturner** [comment]
If you find things you want to add then you can add the URL's as custom assets including the `?embed=true` to the end of the URL.

**Comment by Smithenstein** [comment]
> If you find things you want to add then you can add the URL's as custom assets including the `?embed=true` to the end of the URL.

Hi Julie, do you know the trick behind this as this technique doesn't appear to work for most content on support.office.com.  Case in point: https://support.microsoft.com/en-us/office/upload-files-and-folders-to-a-library-da549fb1-1fcb-4167-87d0-4693e93cb7a0?embed=true

**Comment by juliemturner** [comment]
Yep, things have changed and they're in the process of determining how to share the information... unfortunately I don't have any information I can share at this time.

**Comment by arehmani** [comment]
I felt the same way as @Smithenstein and mentioned it in our learning pathways meeting yesterday. It would be great to get more SharePoint related content in learning pathways.

**Comment by karuanag** [comment]
Pulling this feedback into our content production meeting.  We are working on snapping to a clearer content publishing ROB so thank you for this feedback.

**Comment by jellis-thrive** [comment]
Closing issue; request is not an enhancement and content production remains ongoing
