### ISSUE TITLE
Error: The value for "_instanceId" must not be undefined

### ISSUE THREAD

**Issue by F-Shad** [pnp/custom-learning-office-365#365]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

we are getting Error: The value for "_instanceId" must not be undefined when visiting 

https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md

### To Reproduce

>Steps to reproduce the behavior

Just visit: https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md

### Expected behavior

>A clear and concise description of what you expected to happen.

### Screenshots

>If applicable, add screenshots to help explain your problem.

Pwys-Err-1 is the error in the debugger
PWys-Err-2 is the screenshot of the admin page

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

4.1.3.0

### Additional context

>Add any other context about the problem here.

**Comment by juliemturner** [comment]
I'm sorry but I do not really understand your question. It appears you're saying you can't go to the markdown file in this GitHub repo?

**Comment by F-Shad** [comment]
Thanks for quick response. I am sorry for not being clear, after installation of 4.1.3.0 when we go “Learning Pathways Administration” page we get the error  “The value for "_instanceId" must not be undefined”

[cid:image001.png@01D69044.4C1AF7E0]
I have deleted and provisioned the site twice already but same issue.

Farshad

**Comment by juliemturner** [comment]
You're provisioning using the lookbook service? And then you're going to the page https://<yourtenant>.sharepoint.com/sites/<M365LPsite>/SitePages/CustomLearningAdmin.aspx?  Please delete everything out of the CustomConfig table and then navigate to that page again and refresh it. If you're still having issues then please follow the instructions [here](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) to provide more debugging information.

**Comment by F-Shad** [comment]
Problem was with site app details and tenant was not the same. deleted everything and started from scratch and it is all good now.
