### ISSUE TITLE
Will there be content update covering new features like MS Lists and new Tasks within Teams?

### ISSUE THREAD

**Issue by MarekHalfar** [pnp/custom-learning-office-365#366]
Are there plans to update the content with the above topics...so that we don't do the double work ourselves...

**Comment by peterjkrebs** [comment]
Following up on this with our content teams to give you a more complete answer.

**Comment by karuanag** [comment]
We'll be sharing new content and future plans at Ignite on March 4th on our blog at https://aka.ms/DriveAdoption

**Comment by jellis-thrive** [comment]
Closing issue; question answered, no further questions from submitter
