### ISSUE TITLE
[QUESTION] Embed Microsoft content into Learning Pathways

### ISSUE THREAD

**Issue by lindaph** [pnp/custom-learning-office-365#367]
- [] Custom Content
I am setting up learning pathways for a client who requires more bespoke content. Some of the content is being written specifically for them and some exists on various Microsoft sites such as Support. 

The challenge is to embed the content from Microsoft sites without bringing in the entire page. I have done a trawl and found a workaround for anything that is hosted as an /article/.

I also came across an old thread here which suggested using the following parameter, but this only seems to work on anything that is in docs.microsoft rather than support.microsoft
_?context=context%2Fchromeless&linktarget=true&fromOrigin=https://xxxxxxx.sharepoint.com_

Most of the urls I'm working with are in this format:

_https://support.microsoft.com/en-us/office/find-what-you-need-with-microsoft-search-d5ed5d11-9e5d-4f1d-b8b4-3d371fe0cb87_

I tried swapping out /office/ for /client/ and that just resulted in a 404 error. And I've tried add the additional parameters

_https://support.microsoft.com/en-us/office/find-what-you-need-with-microsoft-search-d5ed5d11-9e5d-4f1d-b8b4-3d371fe0cb87?context=context%2Fchromeless&linktarget=true&fromOrigin=https://xxxxxxx.sharepoint.com_

but that makes no difference at all and so I'm stumped!

Is there a workaround anyone can recommend as it's a bit disconcerting to see the 'buy Microsoft 365' link at the top of a learning content page?

![image](https://user-images.githubusercontent.com/71702803/93874620-89485100-fccb-11ea-8bd2-2b0c80c0ec70.png)

**Comment by juliemturner** [comment]
The correct query string parameter for support.office.com url's is `?embed=true`.  That said I can't guarantee that all content will work as you've already surmised.

**Comment by lindaph** [comment]
Thanks for the swift reply Julie, sadly it doesn't strip out the nav headers on the page, so all the links to the rest of the Microsoft site are still available. It's more of an aesthetic thing really as I don't want to confuse users, but they'll get over it I'm sure .. ;-)

**Comment by juliemturner** [comment]
I've seen that commonly happen as new headers are added to support.office.com that don't honor the query string parameter.  I'll tag someone internal to see if they can fix it.

**Comment by juliemturner** [comment]
So according to the internal resources you need to modify your url.  This was their answer:

>https://support.office.com/en-us/client/d5ed5d11-9e5d-4f1d-b8b4-3d371fe0cb87?embed=true
> 
>Some key elements:	
>- Use support.office.com not support.microsoft.com
>- Use client after the language
>- Just include the article GUID
>- Last part is to use ?embed=true

**Comment by lindaph** [comment]
Thanks so much for both those replies Julie, they are much appreciated. Apologies for the delay in getting back to you - I'm lucky enough to work part-time :-) I'll try them out tomorrow when I'm updating LP again and let you know what happens

**Comment by lindaph** [comment]
Hi Julie, just to let you know that the solution above works brilliantly, thanks so much for your help.
