### ISSUE TITLE
[QUESTION]: Integration with Microsoft Teams

### ISSUE THREAD

**Issue by henk167** [pnp/custom-learning-office-365#368]
### What is the context of your question

- [] M365 learning pathways web part

We integrated the Learning Patways app in Teams. It's working properly in the web app from teams, but not in the local windows app of teams. In the local apps of Teams we're getting a blank screen in the app. Any Idea how to resolve this?

![MLP](https://user-images.githubusercontent.com/71757720/93990266-36ce6980-fd8b-11ea-9fe7-90b212787e5d.png)

**Comment by juliemturner** [comment]
I would assume you have a bug in your teams manifest. If you want to share what you used then I can maybe assist.

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
