### ISSUE TITLE
Whitespace beneath Custom Learning for O365 Webpart

### ISSUE THREAD

**Issue by aisa0906** [pnp/custom-learning-office-365#37]
Large amounts of whitespace beneath the Custom Learning for O365 webpart; on any page added; ie. Scenarios: Modern workplace, Adoption Tools, Getting started with six simple steps, etc...

**Comment by juliemturner** [comment]
@aisa0906 -- Yes we're aware of this.  It was implemented this way on purpose to support a technical limitation of the underlying content.  As soon as that limitation is lifted we will make the content fit exactly in the space.

**Comment by clayjam** [comment]
This is quite annoying as we can't put any content under the web part due to this issue.

**Comment by juliemturner** [comment]
Yes, we're aware as we had to remove functionality from our solution as well.  We're hoping for a quick resolution.

**Comment by DarrellaaS** [comment]
> @lakrupka - Unfortunately the issue does not lie with the learning pathways solution. That said we have an agreed standard now to deal with it and some of the content has been fixed. A new web part release will be coming soon that will implement that partial fix and automatically support fixes to other content as it's released.

Glad to hear this too @juliemturner. I'll eagerly keep watch for the new web part.

**Comment by juliemturner** [comment]
For support.office.com content this issues has been fixed.  We are still waiting for the crew at docs.microsoft.com to implement the same fix and then content will automatically be fixed without a web part update.
