### ISSUE TITLE
One instance of Learning pathways per tenant? 

### ISSUE THREAD

**Issue by tone-sutto** [pnp/custom-learning-office-365#371]
Am I correct to assume that there can only be one instance of the Learning pathways solution per tenant?

Thanks in advance!

Tony

**Comment by juliemturner** [comment]
Yes, the solution has a master learning pathways administration site and then the viewer web part can be added to any other site collection in the tenant as a sort of hub-spoke model of managing your learning content.  For more in-depth review of the architecture and features check out the [video overview](https://github.com/pnp/custom-learning-office-365#overview-video) section.
