### ISSUE TITLE
 Manual Deployment of Web Part Browser Access #33

### ISSUE THREAD

**Issue by Iuliabolea** [pnp/custom-learning-office-365#372]
Hi,
Due to complex SharePoint Online architecture at a customer we have deployment the Web Part using the manual process. This works perfectly fine but we are seeing the following behavior on different browsers, it is always worth noting that the App Catalog resides on one site collection with a vanity domain and the sites reside on another site with a different vanity domain so the automated deployment was not possible:

IE 11 (aware this is not really compatible) - able to access the web part but no media
Chrome (the browser of choice for the customer) - this errors with a message "Failed to load the componen (AppCatalogURLfor thewebpart) Original Error: Failed to load URL. There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate"
New Edge - Works fine throughout for one person only; not other

I am focused on this being a client setting, possibly policy or proxy related. Just need confirmation that you have not seen this before or there is nothing else I should be thinking about here.

**Comment by juliemturner** [comment]
Yes, we are aware of this limitation for support of vanity domains unless the app catalog and the sites that it served in are in the same vanity URL. This is a limitation of the SharePoint Framework and not of learning pathways itself.

**Comment by Iuliabolea** [comment]
Thanks Julie- are you aware of any workarounds?

**Comment by juliemturner** [comment]
The only workaround I'm aware of, but have no personally tested, is turning on the Public CDN, which then puts the code that needs to be loading into the page in a publicly accessible URL thereby avoiding the security issue.

https://docs.microsoft.com/en-us/microsoft-365/enterprise/use-microsoft-365-cdn-with-spo?view=o365-worldwide
