### ISSUE TITLE
Is September 2020 content update available in more languages than English?

### ISSUE THREAD

**Issue by manfred-roiger** [pnp/custom-learning-office-365#377]
Hi,

I checked https://docs.microsoft.com/de-de/office365/customlearning/custom_contentupdates yesterday and noticed a content update is available. So i checked on our site and couldn't find any new content in German language. I checked the administration page and for example the new scenario "Security" was available. Next I switched my language to English and now I can see the new scenario "Security" and all the new content in "Planner", etc.

The question now, is the new content available only in English?

We are running Version 4.1.1 and I attach screenshots in English and German.

Thanks, Manfred

![pathways-en](https://user-images.githubusercontent.com/22952678/94655110-5c64f100-02fe-11eb-9cf5-ac680e42eed2.png)
<img width="1399" alt="pathways-de" src="https://user-images.githubusercontent.com/22952678/94655172-70a8ee00-02fe-11eb-8213-0ea8380300b3.png">

**Comment by juliemturner** [comment]
Yes, that sub-category does appear to be missing from the manifests, I'll reach out to that team and see what the intent was.

**Comment by benoitfournier** [comment]
Same in french.

Merci

**Comment by juliemturner** [comment]
It looks like (saw a PR) the manifests were just updated for the translations.  See if it's fixed now.

**Comment by benoitfournier** [comment]
I just tried to refresh and I do not see the new content.

**Comment by juliemturner** [comment]
By just tried a refresh I assume you mean went to the CustomLearningAdmin.aspx page, then after that loaded went to CustomLearningViewer.aspx...

**Comment by juliemturner** [comment]
Nevermind, i just looked a bit more and see that it hasn't been merged yet... so clearly the fix isn't complete.

**Comment by juliemturner** [comment]
Ok, looks like the update was merged in, try it now.

**Comment by manfred-roiger** [comment]
Allmost there. The category is now displayed but the images are only available in English language setting.
<img width="671" alt="Bildschirmfoto 2020-10-05 um 10 28 14" src="https://user-images.githubusercontent.com/22952678/95057012-d24dcb80-06f5-11eb-9686-842ac6e21078.png">
<img width="938" alt="Bildschirmfoto 2020-10-05 um 10 28 30" src="https://user-images.githubusercontent.com/22952678/95057018-d548bc00-06f5-11eb-925a-e9b543c69c31.png">

**Comment by manfred-roiger** [comment]
Hi,
is fixed, images are now also displayed.
Thank you

**Comment by benoitfournier** [comment]
Also fixed in French. Thanks!
