### ISSUE TITLE
 Accessing the admin success center breaks the whole site

### ISSUE THREAD

**Issue by X1M3N** [pnp/custom-learning-office-365#378]
## Describe the bug

Clicking on "Admin success center" brings me to a "bug" page
![image](https://user-images.githubusercontent.com/72074119/94698647-ce0e6080-0339-11eb-8d6b-a684730b4c05.png)

After that, clicking on anything does not get rid of the "bug page", a refresh is mandatory.

### To Reproduce

From the "home" menu, click on "Success admin center"
![image](https://user-images.githubusercontent.com/72074119/94698694-dbc3e600-0339-11eb-9e0c-d5bddb69c492.png)

**Comment by jsuddsjr** [comment]
This error occurs when the site template fails to "install" the Learning Pathways webpart into the site. This is different from installing the web part into the app catalog. You also need to ensure that the Microsoft 365 Learning Pathways app appears on your Site Contents page as an App. Normally, the app is installed as part of the site template, but it can sometimes fail.

1. Make sure you have installed Microsoft 365 Learning Pathways in your app catalog. See https://github.com/pnp/custom-learning-office-365#updating-the-solution
2. Add the app to your web site. See https://docs.microsoft.com/en-us/sharepoint/administration/add-apps-for-sharepoint-to-a-sharepoint-site

You can also try installing a fresh site template from the Look Book service: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239 (EASY) or use a PowerShell script to recreate the admin page (ADVANCED). See https://github.com/pnp/custom-learning-office-365/blob/master/webpart/M365lpConfiguration.ps1 and don't forget to install or update the SharePointPnPPowerShellOnline module first.

**Comment by jellis-thrive** [comment]
Closing issue due to lack of further engagement
