### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by iamnirajpandey** [pnp/custom-learning-office-365#379]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [] Installation

### Any way i can turn this into ENGLISH?

>Provide related screen-shots to help us understand your question
![learningpathwaysinspanish](https://user-images.githubusercontent.com/67551324/94802365-25c5ce00-0405-11eb-9bfe-3fb1d044fed6.jpg)

**Comment by juliemturner** [comment]
If the heading is in Spanish, then the user's language in their profile is set to Spanish. To change it to English the user needs to change their selected language to English.

https://support.microsoft.com/en-us/office/change-your-personal-language-and-region-settings-caa1fccc-bcdb-42f3-9e5b-45957647ffd7

**Comment by iamnirajpandey** [comment]
this is visible when i deployed at tenant level...and this is visible to all....and few user in India are able to see the same thing...!!

**Comment by iamnirajpandey** [comment]
this is visible when i deployed at tenant level...and this is visible to all....and few user in India are able to see the same thing...!!

**Comment by juliemturner** [comment]
I'm sorry, I'm not following what your comment means?

**Comment by iamnirajpandey** [comment]
post deploying the learning pathways, only the heading of learning pathways is displayed in Spanish(as in the screenshot) but every other article is getting displayed in English Language. don't know why this has happened and this is visible to all the users within that domain.

**Comment by iamnirajpandey** [comment]
@juliemturner i will check this and let you know..!

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
