### ISSUE TITLE
 CustomLearningAdmin Page not loading

### ISSUE THREAD

**Issue by ehuntingdon** [pnp/custom-learning-office-365#382]
Hi there,

We recently provisioned Learning Pathways directly from the SharePoint lookbook. Everything is working great, except we are unable to access the admin page. When click on our pathway to access our site's CustomLearningAdmin.aspx from site contents, a error appears:

**TypeError: Cannot read property '0' of undefined
in t in t in o in t in t in t in t in t in section in div in div in t in Styledt in t in o in t in t in t**

The error can be reproduced any time the page is visited. The expected behavior is to access the learning pathways admin site.

I don't have access to the version number, but we provisioned it from the lookbook just yesterday.

Thank you for all of your help!

**Comment by juliemturner** [comment]
Please follow [these instructions](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) to share console log so that I have understanding of the error.

**Comment by ehuntingdon** [comment]
Thank you for the help Julie,

Here's what I have pulled:

sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1 TypeError: Cannot read property '0' of undefined
    at t._ensureWebPartData (chunk.sp-pages-singlewebpartapppagelayout_en-us_52f268c07a3e5aa69568.js:1)
    at t._updateCommandBarProps (chunk.sp-pages-singlewebpartapppagelayout_en-us_52f268c07a3e5aa69568.js:1)
    at t.getCommandBarProps (chunk.sp-pages-singlewebpartapppagelayout_en-us_52f268c07a3e5aa69568.js:1)
    at t.renderCommandBar (sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1)
    at t.renderPageLayout (sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1)
    at t.render (sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1)
    at oa (sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1)
    at aa (sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1)
    at Mo (sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1)
    at ko (sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1)
Ea @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
Ra.i.componentDidCatch.n.callback @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
jl @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
Al @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
To @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
t.unstable_runWithPriority @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
dl @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
xo @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
po @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
(anonymous) @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
t.unstable_runWithPriority @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
dl @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
vl @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
ml @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
co @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
enqueueSetState @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
g.setState @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
t.onRender @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
t.onRender @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
(anonymous) @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
Promise.then (async)
t.initialize @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
t.componentDidMount @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
t.componentDidMount @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
To @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
t.unstable_runWithPriority @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
dl @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
xo @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
co @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
Ho @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
Qo @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
(anonymous) @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
go @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
Jo @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
render @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
t.onRender @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
t._renderCoreRouter @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
t.onRender @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
t._onRender @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
t._render @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
(anonymous) @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
Promise.then (async)
e._initializeApplication @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
(anonymous) @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
Promise.then (async)
e._initializeApplicationWithTelemetry @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
e.startApplication @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
e.navigate @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
e.navigateToApplication @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
c @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
(anonymous) @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
s @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
e._startApplication @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
e._startApplication @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
(anonymous) @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
Promise.then (async)
e.start @ sp-pages-assembly_en-us_8cadc1b0a139ba58aefd31f37191d1ac.js:1
loaderStart @ CustomLearningAdmin.aspx:109
startSpfx @ CustomLearningAdmin.aspx:121
(anonymous) @ CustomLearningAdmin.aspx:148
(anonymous) @ CustomLearningAdmin.aspx:152
The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.

**Comment by juliemturner** [comment]
Ok, if that's all that's in the console log, that doesn't really help.  I suspect that somehow the admin page didn't get provisioned correctly. I would suggest deleting the CustomLearningAdmin.aspx page and then recreate it by using the powershell supplied for that purpose. Follow the instructions [here](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/README.md#execute-powershell-configuration-script) specifically just the section for site admins as that, I believe is the only part you need:

`.\M365lpConfiguration.ps1 -TenantName contoso -SiteCollectionName M365LP – SiteAdminOnly`

**Comment by ehuntingdon** [comment]
Thank you so much, we'll give that a try!

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
