### ISSUE TITLE
[QUESTION] Recommended permissions of the CustomConfig list?

### ISSUE THREAD

**Issue by tkagens** [pnp/custom-learning-office-365#383]
Hello!

We faced the Webpart-Error "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance" due to missing user permissions on the CustomConfig list. I'm not sure if the permissions are missing due to an error that occurred during installation - What permissions are recommended for the CustomConfig list? Permission inheritance enabled?

**Comment by juliemturner** [comment]
So if you had provisioning errors that is more concerning than what permissions you're supposed to have, the solution should do that for you.  How did you provision, manually or with the lookbook?

But to answer your question CustomConfig should allow everyone with access to the site to edit but that doesn't break the solution, what might is if you didn't first go to the CustomLearningAdmin.aspx page.

**Comment by tkagens** [comment]
Thanks for the quick response!

Deployment was done via the Lookbook and there were no deployment errors. In fact, the CustomLearningAdmin.aspx was not accessed first - this is required without any intermediate step to complete the deployment correctly? 
Then this was definitely the "missing step", which caused the permissions of the CustomConfig list to be set incorrectly. In this case, the permission inheritance of the CustomConfig list was interrupted -> Access for visitors, members and owners of the SiteCollection was removed  -> app was not loaded correctly in enduser contexts. Once permission inheritance has been activated in the CustomConfig list, the app works without any problems.

**Comment by juliemturner** [comment]
Going to CustomLearningAdmin.aspx is not required but it gives you a better sense of what is really wrong/not wrong.  Going to that page did not cause the permission fo CustomConfig list to change, it sounds like it just didn't provision correctly. The setting for that list should not be inherited, you should break inheritance to make sure that Visitors have Edit rights as they need to be able to update the cache every 24 hours.

**Comment by tkagens** [comment]
I will set it up accordingly, thanks for your support!
