### ISSUE TITLE
[QUESTION]How to upgrade from earlier version of o365cl

### ISSUE THREAD

**Issue by mbean314** [pnp/custom-learning-office-365#384]
> I have an earlier ver of o365cl. when i am trying to upgrade to v 4 i do not have an option to deploy in admin view. Do i need to deploy ver 2 and 3 first? or will the whole site need to be deleted?
### What is the context of your question

- [✔] Installation
- [] Administration
- [] Custom Content
- [] M365 learning pathways web part

### What is your question

>Provide related screen-shots to help us understand your question

**Comment by juliemturner** [comment]
I'm not following at all how the o365cli relates.  If you have a previous version of learning pathways installed, please [follow these instructions](https://github.com/pnp/custom-learning-office-365#updating-the-solution) to upgrade it.

**Comment by mbean314** [comment]
Hello,
I’ve gone through the instructions, but I do not see deploy option available anywhere. I have the file uploaded, but not showing as tenant deployed.
[cid:image003.jpg@01D6A6D8.B1DC7450]

Looking at site content I see the package is from last year
[cid:image006.jpg@01D6A6D8.B1DC7450]
But when I look at its details, it shows updated version

[cid:image007.jpg@01D6A6D8.B1DC7450]




Thank you,

Marina Bean
CareFirst BlueCross BlueShield
Lead UC Engineer |Unified Communications Services
10455 Mill Run Cir
Owings Mills,  MD 21117
W 410-998-5495
Marina.bean@carefirst.com<mailto:Marina.bean@carefirst.com>

**Comment by juliemturner** [comment]
Unfortunately, you responded via email which means that your images do not actually get shared.  If you could please use the GitHub UI and update your response so I can see if I can help you. 

Also as a warning if you respond via email you end up putting everything in your email signature in the GitHub issues list which then becomes publicly available.  I've removed it from your post above.

**Comment by mbean314** [comment]
Hello
Here are the screenshots i was trying to share

view in SPO admin

![Snag_99daf58](https://user-images.githubusercontent.com/73130783/96738595-e1d34280-138c-11eb-992b-c44d42cb9663.png)

view of the app on o365cl site

![Snag_99e5c22](https://user-images.githubusercontent.com/73130783/96738707-fca5b700-138c-11eb-84ea-bdcfb56f776a.png)


view of the properties of the app

![Snag_99f113a](https://user-images.githubusercontent.com/73130783/96738795-17782b80-138d-11eb-9d15-ccccb0995ff8.png)

Would it be easier to just delete current app and start from scratch?

**Comment by juliemturner** [comment]
Um, so based on these screen shots you're all set... it shouldn't be tenant deployed (now that I understand what you're referencing).  Tenant Deployed in this case means that the web part is automatically added to every site collection in your tenant... the package is not set up to do that as we didn't feel that's what people would want.

**Comment by mbean314** [comment]
Great! it was strange that there was never an option to deploy. Thank you for confirming.

**Comment by juliemturner** [comment]
@mbean314 -- it's not actually as the deployment package does not have that option turned on to allow it to be automatically deployed to every site collection in your tenant.
