### ISSUE TITLE
How to set up security on a SharePoint Communication site

### ISSUE THREAD

**Issue by jp4purvis** [pnp/custom-learning-office-365#386]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [x] Installation
- [] Administration
- [] Custom Content
- [] M365 learning pathways web part

### What is your question
How can I grant all of my users access to the custom learning site I setup?  Right now when a user tries to access the site they are not allowed in until after I accept their request for access.

**Comment by juliemturner** [comment]
Please follow instructions for setting up permissions for a `Communication Site`.  In general you want to put any users that you want to have access to administrate the content of learning pathways in the "Members" group and all other users in the organization that you want to consume content should be added to the "Visitors" group.

[Sharing and permissions in the SharePoint modern experience](https://docs.microsoft.com/en-us/sharepoint/modern-experience-sharing-permissions)

**Comment by jp4purvis** [comment]
Julie,

Thank you for your response.  Let me make sure I understand, the users will have to be added one at a time for students?  I have over 500 users and was hoping there was a way to grant student access to all the users in our domain.  But what you are saying is they must be added one at a time.

Thanks!

Jennifer Purvis​​​​

Programmer/Analyst
Information Technology Division
City of Monroe

318-329-2305

________________________________

**Comment by jp4purvis** [comment]
Julie,

Thank for helping.  I reread the documentation and got it.  Thanks again.

Jennifer Purvis​​​​

Programmer/Analyst
Information Technology Division
City of Monroe

318-329-2305

________________________________

**Comment by juliemturner** [comment]
FYI, when you respond to github threads via email all your PII information is posted to the issue.  Also if you try to include screen shots they will not be uploaded.  It is best to respond to the issue using the GitHub UI but if not please make sure you remove the body of the email in your reply.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
