### ISSUE TITLE
[QUESTION] Learning Pathways. do I need to have SharePoint installed and running to be able to set up my Learning Pathways

### ISSUE THREAD

**Issue by Patricia-byte** [pnp/custom-learning-office-365#389]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [] Installation
- [] Administration
- [] Custom Content
- [] M365 learning pathways web part

### What is your question

>Provide related screen-shots to help us understand your question

**Comment by juliemturner** [comment]
Learning pathways is a SharePoint solution and only works on SharePoint online.  So, assuming by "installing" you mean on on-prem SharePoint server then it would not be deployable there.

**Comment by Patricia-byte** [comment]
Thank you Julie! 
This is what I was thinking.
