### ISSUE TITLE
'Content' option on stand-alone web part throws 'Leaving site' message

### ISSUE THREAD

**Issue by joannecklein** [pnp/custom-learning-office-365#39]
If I add the stand-alone web part to a new or existing page AND I select the 'Content Only' Webpart mode, whenever I click into any of the playlists, I get the 'Leave site? Changes you made may not be saved.' pop-up. As soon as I switch to Webpart mode 'Full', I don't get this message.

I'm using Full as an option now, but thought I'd log this. Not sure how the 'Content Only' option should behave? Should it just go to the CustomLearningViewer.aspx page without that popup?

**Comment by juliemturner** [comment]
Yes.. it was a feature request during the QA process that I think is more confusing than helpful... basically it was to stop users from using the browser back function instead of the breadcrumbs... so by design but I think it does more harm than good.

**Comment by joannecklein** [comment]
Ah, I see. Fwiw, I was confused by it so I can only assume there will be others. I couldn't find much about it in the current documentation, but may have missed it. Thanks Julie.

**Comment by joannecklein** [comment]
I am still getting the 'Leave site? Changes you made many not be saved.' pop-up even when using the Full option. Not a huge deal, but will be confusing for end-users.

**Comment by gscooper** [comment]
Is there any resolution for this issue?  I am getting it as well in every installation that I perform.  Thanks!

**Comment by juliemturner** [comment]
This is not a bug but a feature so that you don't accidentally leave the page if you're navigating the content. It will be reviewed in future releases and the feature may be removed.

**Comment by juliemturner** [comment]
There is no work around as the code is baked into the web part.  It's not only my personal decision so as soon as one has been made this issue will be updated and closed.
