### ISSUE TITLE
 Yammer as a "technology" category doesn't work, makes other Custom categories disappear if Yammer is made visible

### ISSUE THREAD

**Issue by elterotero** [pnp/custom-learning-office-365#393]
## Describe the bug
Yammer as a "technology" category doesn't work, makes other Custom categories disappear if Yammer is made visible

### To Reproduce

If I would like to make the Yammer content visible and click the (eye)visibility icon, the content doesn't appear. Also if I create a custom category (Communities by Yammer as in our example) and assign the Yammer as the technology for the Custom playlists. It does not appear. I can ignore the problem by just not adding the Yammer as the technology there, so site is still usable. But just wandering is this a general error or something in our installation part that would perhaps require a new installation?

### Expected behavior

>A clear and concise description of what you expected to happen.

### Screenshots
The Playlist and content is visible with these settings
![image](https://user-images.githubusercontent.com/35706053/97976592-90d33d80-1dd3-11eb-9b91-f512b2f40262.png)
![image](https://user-images.githubusercontent.com/35706053/97976599-929d0100-1dd3-11eb-9507-33974d89d12a.png)
![image](https://user-images.githubusercontent.com/35706053/97976607-94ff5b00-1dd3-11eb-8bfa-a208f4408f96.png)

But with this small change the content and playlist is not visible
![image](https://user-images.githubusercontent.com/35706053/97976702-b06a6600-1dd3-11eb-9152-840d19ac5c18.png)
![image](https://user-images.githubusercontent.com/35706053/97976712-b3fded00-1dd3-11eb-8302-0f813be1f40c.png)

### Learning Pathways version number

version 4.1.3 (upgraded from version 3)

**Comment by juliemturner** [comment]
If that's happening it would be because the Yammer technology was hidden, which then causes any content tagged with the Technology Yammer to be hidden and if a category has no visible playlists in it, it won't show up.  So, I would go check the Technologies view in the Admin page and make sure the Yammer Technology is not hidden.

**Comment by elterotero** [comment]
Thanks @juliemturner I'll close this down, your suggestion was the answer. My mistake, thank you for the fast support. Now it's visible.
