### ISSUE TITLE
own content as a content package

### ISSUE THREAD

**Issue by memphis11** [pnp/custom-learning-office-365#395]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [] Installation
- [] Administration
- [] Custom Content
- [] M365 learning pathways web part

Hello,
I would like to add my own content as a content package. For the test I simply downloaded the repo and uploaded it to githb: https://github.com/juliemturner/LPCDNDemo

I then selected this as the base URL. Unfortunately it doesn't work. Has anything changed in version 4 that is no longer possible?

**Comment by juliemturner** [comment]
No, this still works fine for me.

**Comment by memphis11** [comment]
That's good. Could I access your Github repo directly as a base URL for testing?
The URL would be "https://github.com/juliemturner/LPCDNDemo" ?

**Comment by juliemturner** [comment]
Sure, but that's not the URL.  If you watch the [video](https://www.youtube.com/watch?v=-sLXl_rKGxQ) I show where you go into the GitHub repo and set up and get the URL for GitHub pages... so, for my repo that's: https://juliemturner.github.io/LPCDNDemo/

**Comment by memphis11** [comment]
Thank you, it works. Then I also know what I did wrong with my config. Have a nice weekend

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
