### ISSUE TITLE
[QUESTION] Categories and Subcategories

### ISSUE THREAD

**Issue by mikedumka** [pnp/custom-learning-office-365#396]
Hi there @juliemturner ... you helped me last time, so I am hoping you will help me again 😁!

I have someone who I am working with who has made a main category, they called it abandoned and I can't for the life of me figure out how I can hide it (or the 'scenarios' category for that matter). 

Where in the admin section can we hide 'main' categories? See my screenshot for more information

![MicrosoftTeams MLP Main Category](https://user-images.githubusercontent.com/4265230/98735319-d1e5c780-2368-11eb-8079-e33fe726ae54.png)

**Comment by juliemturner** [comment]
My guess is they didn't create abandoned, "I did"... or rather they had custom playlists where those playlists were associated with categories/subcategories where the GUID was removed from the list so when the web part loads it puts them in an abandoned category so they can be fixed.  You've included a screen shot of the web part and you need to be looking in the Admin web part which should be the page "CustomLearningAdmin.aspx" in the pages library of the main learning pathways site collection.  If you go there the categories on the left, at the top should be one called Abandoned and there should be Playlists under that as a sub category with then 1 or more playlists there.  Edit those playlists and associate them with a new Category/SubCategory and save them and then you should be all set.  This is also where you would hide other categories/subcategories using the UI.  For more information I suggest you watch the getting started video for a more complete overview: https://www.youtube.com/watch?v=-sLXl_rKGxQ

**Comment by mikedumka** [comment]
God ... what a rookie mistake 😳!

Thanks for that @juliemturner, I am going to watch the video. I have been using this with clients going back to the very first release in preview and just thought I had everything figured out. I guess not!
