### ISSUE TITLE
Configuration error trying to add SharePoint Success Site playlist to M365 Learning Pathways

### ISSUE THREAD

**Issue by declawson** [pnp/custom-learning-office-365#397]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Learning Pathways is installed in the App Catalog and is at version 4.3.1 when get the configuration error when trying to add a Custom CDN for SharePoint Success Site,  using Content Pack id a748d357-1879-436f-96fc-20dd1fed87bb & Base Url  https://microsoft.github.io/customlearning_staging/SSK/  using this documentation https://docs.microsoft.com/en-us/SharePoint/add-sss-cdn#add-the-sharepoint-success-site-cdn

### To Reproduce

>Steps to reproduce the behavior

### Expected behavior

>A clear and concise description of what you expected to happen.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.

**Comment by juliemturner** [comment]
The formal docs are not something in my control, but in general they look to be incorrect. I believe the correct CDN Base URL is:

https://pnp.github.io/custom-learning-office-365/sss/

**Comment by declawson** [comment]
Looks like the Content Pack id in the documentation is also incorrect.  Now I am getting Message: CustomDataService (getCustomConfig) No configuration was found for CDN a748d357-1879-436f-96fc-20dd1fed87bb and Language en-us

Thank you for the correct Base Url though.

**Comment by declawson** [comment]
I take that back, while I did get the getCustomConfig error in the console log the CDN content was loaded.  Thank you for your help. I will pass the documentation error on to Microsoft.

**Comment by juliemturner** [comment]
Yes, I passed it along as well.  Thanks.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.

**Comment by declawson** [comment]
Julie,

Thank you, I am new to GitHub, should I have closed this?  I apologize if that is the case.

[https://webmail.atcc.org/owa/auth/image001.jpg]
Debbie Clawson
LEAD BUSINESS SYSTEMS ANALYST

10801 University Boulevard
Manassas, VA 20110-2209
Tel: (703) 365-2700 ext. 2820
Fax: (703) 365-2701
Email: declawson@atcc.org

**Comment by juliemturner** [comment]
You don't have to, but I suppose if you feel that your issue has been answered it is nice to do so as it signals to the maintainers that you are all set.

What I would be careful of is responding to GitHub issues via email especially if you have personal information like email and phone numbers in an email signature as all of that information is then posted as public information.  Better practice is to always use the GitHub UI but if not make sure to clean out all the remainder of the body of the email so only your response is sent.
