### ISSUE TITLE
How to add custom content from docs.microsoft.com?  

### ISSUE THREAD

**Issue by robert-studio365** [pnp/custom-learning-office-365#398]
### 
- [] Custom Content

### When trying to add custom content from pages on docs.microsoft.com I keep getting an error in the webpart of "**_docs.microsoft.com refused to connect_**".  Content that originates form support.microsoft.com seems to work fine when appending _?embed=true_ to the URL, but this does not seem to help with docs.microsoft.com 

>Provide related screen-shots to help us understand your question

**Comment by juliemturner** [comment]
Duplication of #367 

Additionally, some of docs.microsoft.com will allow itself to be embedded in an iFrame and some won't.  I have no visibility into why that's the case. I do have a request in to have it fixed, however at this time I have no timeline or even agreement that it will happen.

You can try this query string parameter: 
`?context=context%2Fchromeless&linktarget=true`

**Comment by naveen8408** [comment]
I tried and get error below Refused to display 'https://docs.microsoft.com/en-us/power-automate/getting-started?context=context%2Fchromeless&linktarget=true' in a frame because it set 'X-Frame-Options' to 'sameorigin'. Do you know of any learning docs from power automate that can be embedded. Thanks!

**Comment by juliemturner** [comment]
No, sorry.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
