### ISSUE TITLE
SharePoint Success Site deployment - Web part not loading 

### ISSUE THREAD

**Issue by cueball59** [pnp/custom-learning-office-365#400]
#299  Describe the bug

WebPart is not loading stating configuration issue. Looking at console it appers to be an issue finding the configuration for CDN and it could not retrieve metadata. There is also a 404 error for the graph.

Learning Pathways was deployed before adding in SharePoint Success Site. The Learning Pathways site is functioning as expected. I attempted to edit the webpart on the page and can select learning pathways as the source but no items will load. 

### To Reproduce

>Steps to reproduce the behavior

### Expected behavior

Expect the webpart to load

### Screenshots

>If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/47506540/99734392-bda07980-2a90-11eb-99c1-59252948b106.png)
![image](https://user-images.githubusercontent.com/47506540/99734470-d872ee00-2a90-11eb-8855-9e33a153d1c4.png)
![image](https://user-images.githubusercontent.com/47506540/99734515-e7f23700-2a90-11eb-9ed9-40562bb305d1.png)

### Learning Pathways version number

>4.1.3.0

### Additional context

>Add any other context about the problem here.

**Comment by juliemturner** [comment]
The graph errors are Microsofts and I cannot comment on them.

With regard to the CDN errors yes, you clearly have an issue there. I would suggest to you go the "CustomLearningAdmin.aspx" page, remove the SharePoint Success Site CDN and readd it.  When you do so it's going to open a new browser tab to provision the site collection, you can simply close that tab, go back to the "CustomLearningAdmin.aspx" tab and click the complete button which will configure the CDN entry and then you should be able to click on it and see it's content.

**Comment by cueball59** [comment]
Awesome, that worked. Thanks for the quick response.
