### ISSUE TITLE
 After Microsoft learning app update, its updated but showing error on the page

### ISSUE THREAD

**Issue by Priya-Verma-cloud** [pnp/custom-learning-office-365#401]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.]

### Expected behavior

App is updated to latest version and but showing error on the page.

>If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/74769043/99794342-03704700-2b50-11eb-98b9-d2471a382cfe.png)

### Learning Pathways version number

4.1.3.0

### Additional context

>Add any other context about the problem here.

**Comment by juliemturner** [comment]
Can you please review these instructions to provide me additional details to assist you:

>WEB PART NOT LOADING: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the Diagnosing Pre-Check guidance before submitting your bug.

**Comment by Priya-Verma-cloud** [comment]
Hi Juliemturner,
We have followed the steps and app is updated but its generating the above mentioned issue. Could you please assist us.
Thanks.

**Comment by juliemturner** [comment]
I'm sorry, but I didn't get the details of the check that I mentioned in my previous reply that you follow. Can you please check these instructions again and see if you don't see the issue? If you get to step 5 and have a report to share you can either paste it here or let me know and I'll send you a link to share the file with me.

>Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

**Comment by Priya-Verma-cloud** [comment]
Hi Julie,
I found the error while doing diagnostic check , but not getting where to fix it? Could you please check it and guide us about the solution.

Regards,
Priya Verma
Infosys - providing contract services to Toyota Motor Europe
Infosys Limited, Pune, India
(Desk) + 91 2067971097
(Phone) + 91 9637200525
Priya.Verma@external.toyota-europe.com<mailto:Priya.Verma@external.toyota-europe.com>

**Comment by Priya-Verma-cloud** [comment]
Hi Julie,
I found the error while doing diagnostic check, but could not found the cause of it. Could you please assist us for finding out the solution.
Thanks,
Priya Verma

**Comment by juliemturner** [comment]
If you have screen shots and or text files please upload them here: [Upload files](https://sympraxis-my.sharepoint.com/:f:/g/personal/julie_turner_sympraxisconsulting_com/EuxIBsASRl5Pn9fPzkaGt8sBRczrriiJn2e_ydJYbUo9yg?e=zaY9oK)

**Comment by Priya-Verma-cloud** [comment]
Hi Julie,
I have updated the log on your mentioned one drive folder. Let us know your observations.
Thanks,
Priya Verma

This e-mail may contain confidential information. If you are not an addressee or otherwise authorised to receive this message, you should not use, copy, disclose or take any action based on this e-mail. If you have received this e-mail in error, please inform the sender promptly and delete this message and any attachments immediately.

**Comment by juliemturner** [comment]
So I've looked at the error and that implies to me that you never visited the CustomLearningAdmin.aspx page after you updated the solution?  If so then visiting it now might solve the problem but you could have possibly ended up with a mis-configuration because that step was skipped. Please go to that page in you Learning Pathways main site and see if the admin web part loads correctly, if it does then try and return to the web part page and do a hard refresh.  If the admin page doesn't load please share details about it.

**Comment by gmparky** [comment]
Hi, I am having the same problem and I am getting that error on the CustomLearningAdmin.aspx page. Here is the error details in the console. 
![image](https://user-images.githubusercontent.com/40665509/100223469-717f8a00-2f13-11eb-8021-f0ba771d06d7.png)

**Comment by Priya-Verma-cloud** [comment]
![image](https://user-images.githubusercontent.com/74769043/100225592-71e44900-2f44-11eb-8a6d-55727c1ca23c.png)

On CustomLearningAdmin.aspx, i am getting above error.

**Comment by juliemturner** [comment]
Ok, @Priya-Verma-cloud  -- your issue seems to be that you either changed the URL of the learning pathways main site or you installed it a second time and the tenant app properties didn't get updated. If you read that error message note is saying the site you're running the CustomLearningAdmin.aspx page from is not the site that is configured as your main learning pathways site. You need to run [this script](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/UpdateM365lpSiteUrl.ps1) to change the main site collection url configuration.

**Comment by juliemturner** [comment]
@gmparky -- I'm sorry but each of these situations is unique, and your issue is not the same.  I would ask that you open your own bug issue and complete all the information there including this screen shot.  Unfortunately, not knowing your scenario I can't determine what that error message may mean for your environment.

**Comment by gmparky** [comment]
Thank you I have added it as #402

**Comment by Priya-Verma-cloud** [comment]
Hi Julie, I updated the site with script to change the main site collection url configuration. It worked, but on our users site its still showing same message. We tried to open the site in in private window of edge. But still same error they are getting. Could you please suggest what may be the reason for this.
Thanks in advance.

**Comment by juliemturner** [comment]
I'm not exactly sure which "same" message you mean.  If you mean the property that you changed above, it can take several minutes for a Tenant app property change to percolate to all the clients. You could try clearing the browser cache as that sometimes helps speed things up.

**Comment by Priya-Verma-cloud** [comment]
Hi Julie,
I have done the changes on 27th November and users are getting the below message:
https://user-images.githubusercontent.com/74769043/99794342-03704700-2b50-11eb-98b9-d2471a382cfe.png
Is this issue related with cache?

**Comment by juliemturner** [comment]
Nope, probably not.  Confirm that you can access the CustomLearningAdmin.aspx page and that it loads ok, if so then you have some new issue and I would need the console information for a client to tell you what that message means.

**Comment by schneika** [comment]
Same here an all our Tenants. Not working after Update. But i am on the new SharePoint Success Site Template from SharePoint Provisioning Service Lookbook Example

custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1 
Message: CustomDataService (getCustomConfig) No configuration was found for CDN a748d357-1879-436f-96fc-20dd1fed87bb and Language 

custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1 
Message: Refresh Manifest Config - DataService (refreshCache)

custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1 
Message: DataService (refreshCache) Could not retrieve metadata from CDN source: https://pnp.github.io/custom-learning-office-365/learningpathways/v4/

DevTools failed to load SourceMap: Could not load content for https://amcdn.msftauth.net/meInlineBackCompat.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1 
Message: CustomLearningWebPart (configCDN) -- Could not get a valid configuration; Please contact your learning administrator.

**Comment by juliemturner** [comment]
@schneika - This message is the issue:
>custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
Message: CustomDataService (getCustomConfig) No configuration was found for CDN a748d357-1879-436f-96fc-20dd1fed87bb and Language

I suspect you didn't complete the setup. Check out this thread for more information: #407

**Comment by bhoekstra** [comment]
@juliemturner On a different tenant from my other ticket, I can confirm that visiting /sites/O365CL/SitePages/CustomLearningAdmin.aspx is the trick to fixing the error if you see it right after updating the sppkg for the M365 learning pathways.

**Comment by juliemturner** [comment]
Yes, doing that step builds the caches for the CDN that are needed so that the web part in the SharePoint Success Site can load. If you follow the provisioning instructions to the end that step is inherent but... I think because the link to the instructions isn't obvious people are missing them.

**Comment by bhoekstra** [comment]
Yeah, I think there are just enough steps that are hidden/overlooked if you skim too quickly (I'm guilty of that!).

**Comment by juliemturner** [comment]
Aren't we all 😁

**Comment by Priya-Verma-cloud** [comment]
Hi Julie,
I encountered the following error ,when i tried to login with the my another id on the same site:
https://user-images.githubusercontent.com/74769043/99794342-03704700-2b50-11eb-98b9-d2471a382cfe.png
So, as per your instructions i visited the CustomLearningAdmin.aspx page and then i was able to overcome the above error.
But do we need to follow this step for all users? Actually this CustomLearningAdmin.aspx page does not exist in the client site. Any solution for this? 
Thanks in advance for your support.
Priya

**Comment by Priya-Verma-cloud** [comment]
Hi Julie,
One more update. As i removed my access from the "Learning Pathway main site", I started to get following Java script error:
![image](https://user-images.githubusercontent.com/74769043/101008204-a761e580-3587-11eb-9a1d-63278713b616.png)

It works if I provide at least read access, otherwise above error. Its not possible to provide read access to each user of other site. Could you please provide solution for this?
Thanks,
Priya

**Comment by juliemturner** [comment]
@Priya-Verma-cloud -- Fundamentally that is how the solution (and to be honest SharePoint works). I think that it would be extremely helpful to you if you watched the [architectural overview video](https://www.youtube.com/watch?v=-sLXl_rKGxQ) that explains how learning pathways works and might help you understand what's happening better. 

In a nutshell you need to effectively add all users you want to have access to learning content to the Viewers group of the main learning pathways site.  You can do this by adding the "Everyone except external users" group to the viewers group or by using other AAD groups, or manually adding them, obviously using the everyone or AAD groups is the most effective and easy to manage.

With regard to your question about CustomLearningAdmin.aspx page, there should only be one instance of that page and it exists in the main Microsoft 365 learning pathways site.  Again the video overview might help you understand this better.

**Comment by Priya-Verma-cloud** [comment]
Hi Julie,
I provided them the read access to the main site ,so they are able to  view the page on which learning app is used. But for the person who wants to edit it, they require edit permission for the main site also. Before updating to the latest version for the learning app, the same user with read access, was able to load and work with the learning app. But now its not possible after updating it. I saw the video provided by you, I guess it is according to learning app feature. Is it correct? 
Thank you for your support,
Priya Verma

**Comment by juliemturner** [comment]
I'm not following what you mean by
>load and work with the learning app
If you mean the CustomLearningAdmin.aspx page, then no, since v2 of the web part no users in the Viewers group were able to load the web part embedded on that page and that is by design since users need to have read access to the site to load the learning content but you don't want all users to have the ability to change the learning configuration.

**Comment by Priya-Verma-cloud** [comment]
Hi Julie,
Hope you are doing well. Thank you so much for your help. The issue is solved after sharing the page.
Happy New Year
Thanks,
Priya Verma
