### ISSUE TITLE
 Learning pathway - CORS request did not succeed

### ISSUE THREAD

**Issue by ukpkumar** [pnp/custom-learning-office-365#403]
## Describe the bug

Learning pathway in our deployment works for a few users, but failing for a few others:

•	some of the users are facing an error that says " Configuration issue" 
•	The console logs shows CORS request did not succeed for specific URLs 
•	Tried from different network, outside /inside office networks, and not working for these users

The error from logs shows:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pnp.github.io/custom-learning-office-365/learningpathways/v4/manifest.json. (Reason: CORS request did not succeed).

Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified 3
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pnp.github.io/custom-learning-office-365/learningpathways/v4//metadata.json. (Reason: CORS request did not succeed).

### To Reproduce

>Steps to reproduce the behavior
a. Access https://<Tenant>.sharepoint.com/teams/M365LP
b. Click on 'Get Started with Admin Center'

### Expected behavior

Expected to see the Admin center pages, as we see from the test environment

### Screenshots

![image](https://user-images.githubusercontent.com/36161182/100265051-1aa49f80-2f69-11eb-9419-dfc3e997f654.png)

### Learning Pathways version number

4.1.3.0

**Comment by juliemturner** [comment]
Whatever network those users are on has some type of proxy that is blocking their access to that path... 

`https://pnp.github.io/custom-learning-office-365/`

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
