### ISSUE TITLE
[QUESTION] own content

### ISSUE THREAD

**Issue by memphis11** [pnp/custom-learning-office-365#404]
Hello, I have to ask again because I can't add my own content. I also just downloaded your content from github and added it to me. I only get the message "Microsoft 365 learning paths have a configuration problem" If I embed your content on your Github, it works. Could it be that it is because I can no longer set the branch to "Master"?

**Comment by juliemturner** [comment]
Did you configure GitHub pages? If not please review the video that explains how to set it up in your repo. Here's the video queued up to the correct spot: https://youtu.be/-sLXl_rKGxQ?t=1074

**Comment by memphis11** [comment]
Hello,

yes I did that, but I don't get the branch set to "Master" as it is in the video.
for me it says "main" "root" and the address is https://memphis11.github.io/lars/

**Comment by memphis11** [comment]
Hello, I found the error, it was actually due to the wrong settings in Github. Thank you
