### ISSUE TITLE
O365 Learning Pathways - Permission bug 

### ISSUE THREAD

**Issue by fouadgbg** [pnp/custom-learning-office-365#405]
Users with Contributor Permission / Read Only are unable to view the page
![image](https://user-images.githubusercontent.com/74716591/100732089-2d353380-33c4-11eb-8d7e-3bf4f3b254ae.png)

**Comment by fouadgbg** [comment]
browser.pipe.aria.microsoft.com/:1 Failed to load resource: net::ERR_CONNECTION_CLOSED
/sites/abc_Microsoft_Learning_Resources/_api/web/lists/getByTitle('CustomConfig')/items?$select=Id,Title,JSONData&$filter=Title%20eq%20%27CustomCDN%27&$top=1:1 Failed to load resource: the server responded with a status of 404 (Not Found)
custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1 Message: Error making HttpClient request in queryable [404] Not Found ::> {"odata.error":{"code":"-1, System.ArgumentException","message":{"lang":"en-US","value":"List 'CustomConfig' does not exist at site with URL 'https://xyz.sharepoint.com/sites/abc_Microsoft_Learning_Resources'."}}} Data: {"response":{},"status":404,"statusText":"Not Found","isHttpRequestError":true}
e.log @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1 Message: Error: Error making HttpClient request in queryable [404] Not Found ::> {"odata.error":{"code":"-1, System.ArgumentException","message":{"lang":"en-US","value":"List 'CustomConfig' does not exist at site with URL 'https://xyz.sharepoint.com/sites/abc_Microsoft_Learning_Resources'."}}} - CustomDataService (getCustomCDN)
e.log @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
/sites/abc_Microsoft_Learning_Resources/_api/web/lists/getByTitle('CustomConfig')/items?$select=Id,Title,JSONData&$orderby=Id%20desc&$filter=(Title%20eq%20%27CustomConfig%27)%20and%20(CDN%20eq%20%27Default%27)%20and%20(Language%20eq%20%27en-us%27)&$top=1:1 Failed to load resource: the server responded with a status of 404 (Not Found)
custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1 Message: Error making HttpClient request in queryable [404] Not Found ::> {"odata.error":{"code":"-1, System.ArgumentException","message":{"lang":"en-US","value":"List 'CustomConfig' does not exist at site with URL 'https://xyz.sharepoint.com/sites/abc_Microsoft_Learning_Resources'."}}} Data: {"response":{},"status":404,"statusText":"Not Found","isHttpRequestError":true}
e.log @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1 Message: Error: Error making HttpClient request in queryable [404] Not Found ::> {"odata.error":{"code":"-1, System.ArgumentException","message":{"lang":"en-US","value":"List 'CustomConfig' does not exist at site with URL 'https://xyz.sharepoint.com/sites/abc_Microsoft_Learning_Resources'."}}} - CustomDataService (getCustomConfig)
e.log @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
/sites/abc_Microsoft_Learning_Resources/_api/web/lists/getByTitle('CustomConfig')/fields?$select=Title&$filter=Title%20eq%20%27JSONData%27:1 Failed to load resource: the server responded with a status of 404 (Not Found)
custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1 Message: Error making HttpClient request in queryable [404] Not Found ::> {"odata.error":{"code":"-1, System.ArgumentException","message":{"lang":"en-US","value":"List 'CustomConfig' does not exist at site with URL 'https://xyz.sharepoint.com/sites/abc_Microsoft_Learning_Resources'."}}} Data: {"response":{},"status":404,"statusText":"Not Found","isHttpRequestError":true}
e.log @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1 Message: ConfigService (validateConfig) -- User does not have appropriate rights to create custom config list.
e.log @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1 Message: CustomLearningWebPart (configCDN) -- Could not get a valid configuration; Please contact your learning administrator.
e.log @ custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1
activitymonitor.js:25 Uncaught ReferenceError: exports is not defined
    at activitymonitor.js:25
sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1 Uncaught RangeError: Maximum call stack size exceeded
    at Function.e._handleWindowError [as _globalErrorHandler] (sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1)
    at Function.e._handleWindowError [as _globalErrorHandler] (sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1)
    at Function.e._handleWindowError [as _globalErrorHandler] (sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1)
    at Function.e._handleWindowError [as _globalErrorHandler] (sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1)
    at Function.e._handleWindowError [as _globalErrorHandler] (sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1)
    at Function.e._handleWindowError [as _globalErrorHandler] (sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1)
    at Function.e._handleWindowError [as _globalErrorHandler] (sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1)
    at Function.e._handleWindowError [as _globalErrorHandler] (sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1)
    at Function.e._handleWindowError [as _globalErrorHandler] (sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1)
    at Function.e._handleWindowError [as _globalErrorHandler] (sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1)

**Comment by juliemturner** [comment]
Is the URL for your learning pathways main site is `https://xyz.sharepoint.com/sites/abc_Microsoft_Learning_Resources`?

Because according to the screen shot you included that URL is returning 404... which would indicate that is not the correct URL.  If you renamed the URL of the site after you provisioned, then you will need to run the script to fix the tenant app property for the Site URL and update it to the correct one. https://github.com/pnp/custom-learning-office-365/blob/master/webpart/UpdateM365lpSiteUrl.ps1

**Comment by fouadgbg** [comment]
https://gbgplc.sharepoint.com/sites/GBG_Microsoft_Learning_Resources

this is the correct Path name as I don’t publish the name online and I had to replace it with “xyz” and “abc”



Regards,

Fouad Chahin
User Productivity Specialist

M: +44 (0) 7790 899 088 | L: +44 (0) 11 5857 2882
GBG (London Hub)

**Comment by fouadgbg** [comment]
I still haven't received any updates on the above request 

is there any solution, please

**Comment by juliemturner** [comment]
Ok, so that is the url for your main learning pathways site?  Then if that's the case the permissions for the CustomConfig list have been broken to the point that users cannot access it.  If this is a new deployment, and you haven't customized it in any way I would suggest you delete the CustomConfig, CustomPlaylist, CustomAssets lists navigate to the CustomLearningAdmin.aspx page which will reprovision those lists setting up the permissions appropriately.

If you have customizations etc, then you'll have to manually fix the permissions.  Basically, CustomPlaylists and CustomAssets should inherit permissions from the site, CustomConfig list breaks inheritance but only to make the Visitor's group a contributor so that they can update the cache if they're the first person to hit it after the 24hour mark.

**Comment by fouadgbg** [comment]
Thanks for the advice and I have followed the instruction as I have not customized the site before

So this error still showing:

See attached

Regards,

Fouad Chahin
User Productivity Specialist

M: +44 (0) 7790 899 088 | L: +44 (0) 11 5857 2882
GBG (London Hub)

**Comment by juliemturner** [comment]
Unfortunately, @fouadgbg you've responded via email and image attachments don't make it through that interface, plus you're ending up including your email signature with your personal information in the issue, so I've been removing that. I'm assuming you're still having issues, if you navigate to the GitHub issue in a browser you'll be able to insert images if you have more to share.

**Comment by fouadgbg** [comment]
apologies I was replying back to you using my work email. here is the image
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/74716591/101505942-c63bef80-396c-11eb-8908-964cd5f6948f.png)


I have followed the instruction and still the same issue. 

let me know the outcomes, please 

thanks in advance

**Comment by juliemturner** [comment]
So unfortunately, I do not have enough information to assist you.  I would suggest at this point that you follow these [instructions](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) and upload the information to the following shared location so that I can review the logs: https://sympraxis-my.sharepoint.com/:f:/g/personal/julie_turner_sympraxisconsulting_com/EuxIBsASRl5Pn9fPzkaGt8sBRczrriiJn2e_ydJYbUo9yg?e=XSJARv

Also include a screen shot of your configuration settings in the "CustomLearnginAdmin.aspx" page. You can get that by clicking on the ... and then selecting `About Web Part` which will display a panel that tells about your particular configuration.

![image](https://user-images.githubusercontent.com/7570936/101507883-0ab39500-3945-11eb-8380-b393d1a3228c.png)

**Comment by fouadgbg** [comment]
![image](https://user-images.githubusercontent.com/74716591/101508589-c4bff680-396f-11eb-8506-5d337b9f3351.png)

**Comment by fouadgbg** [comment]
is there any updates on that, I appreciate that

**Comment by juliemturner** [comment]
I saw that you posted the screen shot of the about screen but you didn't upload any diagnostics that I asked for so I was waiting.

>I would suggest at this point that you follow these instructions and upload the information to the following shared location so that I can review the logs: https://sympraxis-my.sharepoint.com/:f:/g/personal/julie_turner_sympraxisconsulting_com/EuxIBsASRl5Pn9fPzkaGt8sBRczrriiJn2e_ydJYbUo9yg?e=XSJARv

**Comment by fouadgbg** [comment]
Hi there

I have uploaded the log as per request, please let me know.

thanks

**Comment by juliemturner** [comment]
The errors you're seeing in the console for customlearningadmin.aspx are not related to the solution they're errors with M365... sadly... 

So although this is useful information in that we know you have no issues loading the admin area, but I really need to see the logs for a page where you are having the issue as well as a screen shot like you gave me for CustomLearningAdmin.aspx.

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
