### ISSUE TITLE
URLs that need to be whitelisted

### ISSUE THREAD

**Issue by rhajj19** [pnp/custom-learning-office-365#406]
i have a customer that is technically not able to access the app while logged in from the network, yet they can access it from their home network. The customer is asking what are the URLs that need to be whitelisted other than the Sharepoint URLs but i can't find any documentation about that. Can someone assist me please ?

**Comment by juliemturner** [comment]
The external URL we're accessing is GitHub, specifically this site.

The URL that needs to be whitelisted is: https://pnp.github.io

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
