### ISSUE TITLE
[QUESTION] How to create custom boxes in the Product list?

### ISSUE THREAD

**Issue by SharomSh** [pnp/custom-learning-office-365#408]
M365 learning pathways - the customer in Italy is having issues in creating a new box in the product list (next to Word, PPT, Teams etc) as they are creating a new page with ad-hoc custom content. Note: the site is set up in Italian.
![SS Learning Smart](https://user-images.githubusercontent.com/75375133/100879713-0d793a80-34ac-11eb-83b0-fa257a7e12f2.jpg)

**Comment by juliemturner** [comment]
Unfortunately, you have not provided enough information for me to assist you. Please provide the following information.

-Do you have multilingual enabled on the site (see the site settings page), if so, what is the default language and what other languages do you have enabled.

-By the empty square I'm assuming you're suggesting that you've created a new sub-category?  Can you please include a screen shot of the set-up of that sub-category.  A consideration will be if the sub-category has any playlists associated with it, if not then the sub-category will not be displayed. The sub-category will also not be displayed if your site's default language is something other than Italian (i.e. English) and you have not included a translation for Italian, same with playlists.  If you have a playlist but it doesn't have an Italian translation then the playlist will not show up.  Please include screen shots of the playlist as well.

**Comment by SharomSh** [comment]
Hi Julie, as explained I am unable to see the settings as it's on customer tenant and they only have access to it.. As explained, to go through your questions it would be necessary to see this directly with customer on a call so they can share their screen etc.. I am not a technical person so it would really help to have this call...Do you think this could be arranged? Thanks a lot

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
