### ISSUE TITLE
Intermittently all Products load in webpart 

### ISSUE THREAD

**Issue by garyIRL** [pnp/custom-learning-office-365#409]
## Describe the bug

Some Products are hidden in configuration in SitePages/CustomLearningAdmin.aspx. Sometimes all products load in webpart when page load (/SitePages/Get-started-with-Microsoft-365.aspx). Other times only products that are not hidden load.

### To Reproduce

Intermittent issue, sometime page loads correctly with selected products hidden as required  

### Expected behavior

Only products not hidden should show.

### Screenshots
Incorrect behavior
![image](https://user-images.githubusercontent.com/75382071/100899006-466bdc00-34b9-11eb-9c85-6ea318fc0e97.png)

Correct Behavior
![image](https://user-images.githubusercontent.com/75382071/100899232-803ce280-34b9-11eb-9a85-2b350970d9a0.png)

### Learning Pathways version number

4.1.3.0
--

**Comment by FormerlyJelly** [comment]
I see that you are on the latest version. Does the Learning Pathways installation use multiple languages, or only a single language?

**Comment by garyIRL** [comment]
> I see that you are on the latest version. Does the Learning Pathways installation use multiple languages, or only a single language?

Multiple languages is turned on but not bring used.

**Comment by FormerlyJelly** [comment]
Thanks - some further questions:

Is this something that end users see, or only administrators? 
How frequently does this occur?
Would users in your organization have a browser or user profile set to a default other than English?
When did the issue begin?

**Comment by garyIRL** [comment]
Thanks.
The issue is happening intermittently, might not happen for days, then more frequently for a few hours. It affect admins and standard users.
Browsers would be set to English as default, many users utilise Citrix desktops, so standard setup. A user might have the page load correctly one day and not later that day.
I'll turn off multi language on the site and see if it occurs less.

**Comment by FormerlyJelly** [comment]
This is a good next step. Language settings will change the user experience based on their default or selected language from the LP landing page. As this is intermittent and others have not reported the same in the latest version, we are unable to reproduce the behavior at this time.  I will watch out for updates.

**Comment by juliemturner** [comment]
To me this implies that you have multiple caches with the same parameters... I would clear the cache out... i.e. delete all entries in the main sites `CustomConfig` list with a title of "CustomConfig"... so **don't** delete any entries with a title of CustomCDN or CustomSubCategories.  After deleting all those entries return the the CustomLearningAdmin.aspx page and refresh it which will reset the cache and see if that doesn't fix it.

**Comment by garyIRL** [comment]
Thanks @juliemturner and @FormerlyJelly 
I've set the site to just English and deleted the CustomConfig files, so now there is just one newly create CustomConfig file for us-en.
I'll monitor page loads and see how it goes.

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
