### ISSUE TITLE
Something went wrong - Custom Learning Office 365

### ISSUE THREAD

**Issue by jonathanpurdy** [pnp/custom-learning-office-365#41]
Provisioned the custom learning through the SPO Provisioning Service Setup after creating the tenant app catalog. No errors during the provisioning, but once I received the notification email, I am unable to view any of the pages. Here is what I see when browsing the training or trying to access the Custom Learning Administration:
![2019-04-23_15-45-14](https://user-images.githubusercontent.com/49923166/56612067-5afba900-65e1-11e9-8eed-87afce8682fd.png)

**Comment by jonathanpurdy** [comment]
I wanted to update you on this reported issue. I wish I could say I fixed it, but not quite sure what happened. After toying around with permissions and redeploying the app package, it started working this afternoon.

**Comment by juliemturner** [comment]
It was probably a result of you redeploying the app package as the error indicates the webpart wasn’t available in the site..
