### ISSUE TITLE
 Users unable to access M365 Learning Pathways webpart, but can access SharePoint site page

### ISSUE THREAD

**Issue by sameer-panuganti** [pnp/custom-learning-office-365#410]
## Describe the bug: Users can view the SharePoint site page (that hosts the pathways webpart) but cannot see content in the webpart. 

**A clear and concise description of what the bug is**.
Users in the organization (multiple domains) have been given VIEW access to the SharePoint portal where we installed/enabled the pathways webpart. The users can access the SharePoint portal, but cannot view content on the webpart. They are requesting access to view the content to the site owners. 

### To Reproduce

>Steps to reproduce the behavior: Users click a URL of webpart playlist > the webpart doesnt open, instead asks to "request access". The site owner 

### Expected behavior

>User clicks on the product icon/webpart > Should open playlists & assets in the webpart

### Screenshots

>If applicable, add screenshots to help explain your problem.
![Screenshot 2020-12-03 152351](https://user-images.githubusercontent.com/69909621/100993642-ab880600-357b-11eb-832e-11a272a90db4.jpg)

### Learning Pathways version number: 

>Please share the version number of learning pathways in your tenant app catalog. **It is version 4.1.3**

### Additional context

>Add any other context about the problem here.

**Comment by juliemturner** [comment]
Make sure any users you want to view content are in the Viewers group of the main Microsoft 365 learning pathways site.  This can be done by utilizing AAD groups or just by using the "Everyone except external users" group.

**Comment by juliemturner** [comment]
Another point, you do not have to give people a link back to the Microsoft 365 learning pathways site, the web part is meant to be deployed to other site collections by adding the Microsoft 365 learning pathways app to those other sites... my previous comment still applies as the web part gets it's content from lists in that site but it's a better way to configure the solution. You might benefit from watching the [architectural/overview video](https://www.youtube.com/watch?v=-sLXl_rKGxQ) mentioned in the readme

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
