### ISSUE TITLE
SharePoint Success Site and Microsoft 365 Learning Pathways 

### ISSUE THREAD

**Issue by mikedumka** [pnp/custom-learning-office-365#411]
Hello, 

I have just provisioned the new SharePoint Success site announced in the following article:

https://techcommunity.microsoft.com/t5/microsoft-sharepoint-blog/introducing-the-sharepoint-success-site-drive-adoption-and-get/ba-p/1927436

But after I get this error ... I am not sure what to do next. Thanks!

![image](https://user-images.githubusercontent.com/4265230/101212982-4a296b00-363f-11eb-97ae-d366b6216b83.png)

**Comment by juliemturner** [comment]
Please review this [provisioning video](https://www.youtube.com/watch?v=HZjxBAKVnJs) or [documentation](https://docs.microsoft.com/en-us/sharepoint/provision-sss), I suspect you missed a step in adding the content pack into the learning pathways admin web part.

**Comment by mikedumka** [comment]
Thank you again @juliemturner ... just had to follow your instructions 👍

**Comment by juliemturner** [comment]
Glad you're all set. I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
