### ISSUE TITLE
Attaching items to a playlist no longer works

### ISSUE THREAD

**Issue by bianca-git** [pnp/custom-learning-office-365#412]
**APP DETAILS:**
VERSION | 2.0.14.0
RELEASE DATE | May 2019

When we create a new playlist:
- we can’t link content (URL/document) to the playlist, so it creates a new tile and playlist
-  A message shows for 2-3 seconds, confirming that the ‘asset has been successfully linked’
- when we click the new tile, there is no asset attached

Noticed this around a month ago, thought it was a minor glitch initially, but it's now effecting our ability to update the site effectively.

Please advise what steps we can take to test/resolve.

**Comment by juliemturner** [comment]
So, first you need to get to the most recent version of the solution, we are way beyond supporting version 2 of the solution.  For instructions on how to update to the latest version (4.1.3) please see the following documentation: https://github.com/pnp/custom-learning-office-365#updating-the-solution

If you have lots of customizations, I would suggest you back up, the above link tells you about doing a back up and links you to documentation on ways you can back up information.

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
