### ISSUE TITLE
Can't use "SharePoint Success Site" next to "Microsoft 365 Learning Pathways"

### ISSUE THREAD

**Issue by ollimenzel** [pnp/custom-learning-office-365#414]
I have a SharePoint Page where I want to display two Microsoft 365 learning pathways Webparts 
The first should show Content from Microsoft 365 Learning Pathways (Content only, Sub-Category, SharePoint)
The other should show content from SharePoint Sucess Site (Content only, Category, SharePoint Sucess Site)
What happens is, that in the Properties Sections I can only assign Values from the SharePoint Sucess Site 
![Webpart Configuration](https://user-images.githubusercontent.com/11551755/101372148-dcce4200-38ab-11eb-832e-40dfcd69c54e.jpg)

**Comment by juliemturner** [comment]
So, the answer is yes you can, but sometimes when the webpart is first added to the page the loading of the categories is a bit flaky, it's not consistently so, but something we should look into. Regardless the screen shot above has a bit of a flaw, to switch between content packs you need to change the "learning source" at the top. Just to be super clear here's my page and the configuration for each web part.

![image](https://user-images.githubusercontent.com/7570936/101504317-11400d80-3941-11eb-8d3d-94dcc37df1aa.png)

![image](https://user-images.githubusercontent.com/7570936/101504759-97f4ea80-3941-11eb-91b9-b7305ddc4b86.png)

![image](https://user-images.githubusercontent.com/7570936/101504785-9deacb80-3941-11eb-8f28-5519a1c1b6e9.png)
![image](https://user-images.githubusercontent.com/7570936/101505045-e99d7500-3941-11eb-9121-905943f55337.png)

**Comment by juliemturner** [comment]
The new release has been pushed and this bug should be solved.

**Comment by ollimenzel** [comment]
I just updated the solution and now it works like charm!
Thanks for this early Christmas present!!
Happy holidays to you!!

**Comment by juliemturner** [comment]
Thanks, same to you.
