### ISSUE TITLE
Can't add LP webpart to SharePoint-site even after adding LP app to that site 

### ISSUE THREAD

**Issue by apptemplatequestions** [pnp/custom-learning-office-365#415]
The LP app is only working for some websites on my tenant.
After adding the LP app, it works on some sites to add the webpart to a site, but on others it simply does not.
How can I fix this issue?

**Comment by juliemturner** [comment]
I'm going to need a bit more to go on then it simply does not work.

We have issue templates to try and guide you to give details that will help us help you, but in lieu of that maybe you could explain more about your install, what you've done to get it working in the sites where it doesn't work and what exactly isn't working.

**Comment by apptemplatequestions** [comment]
Hi @juliemturner,

thanks a lot for getting back to me so quickly. 
We deployed the Learning Pathways as explained in the documentation and also created an app catalog for this. Then, we went to an already existing SharePoint page and added the app to the site. The app got added to the site without any problems. Then, we opened an existing site and clicked on "edit" and then on the "+" to add a webpart to the site. 
Unfortunately, the LP web part icon did not show up in the pop-up menu, and we were unable to add the LP webpart. 

We then went to a different, less frequented SharePoint site with the same user (SharePoint admin) and added the LP app to this site as well. Afterwards, we again tried to add the LP webpart, and on this site it showed up in the pop up menu and we were able to add it.

As a result, on the more frequented site which is a main communications site at the customer, we were unable to add the LP webpart but were able to add the LP app.
In the less frequented site, we were able to add the LP webpart and the LP app as regular.

Thanks a lot for your help and looking into this!

**Comment by juliemturner** [comment]
I think you're missing the step that you need to add the Microsoft 365 learning pathways app to the site, once you do that then the web part will be in the gallery.  The solution isn't deployed to the whole tenant by default so you need to add the app on a site collection by site collection basis.

**Comment by apptemplatequestions** [comment]
Hi @juliemturner,

as written, we have added the LP app to each site we wanted to add the web part to.
For one site, where the LP webpart needs to be deployed, the web part nevertheless did not show up in the pop-up menu for adding a new webpart.
At another site, we followed the same steps (adding the app to the site, then adding a web part), and here the LP webpart did show up in the list of all available web parts. 

How can we ensure that for the site where the LP web part did not show up in the list of all web parts, that it will be available?

**Comment by juliemturner** [comment]
um... the only reason I can think of is that you didn't wait long enough for the app to get deployed.  Validate that the Microsoft 365 learning pathways app is in the site collection... if that's true then if you navigate to a page and edit it and then add the web part it should be there.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
