### ISSUE TITLE
 Learning Pathways not working in MS Teams and German translation leads to an error

### ISSUE THREAD

**Issue by MB-Podella** [pnp/custom-learning-office-365#416]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug
A couple of days ago, everything worked fine. 
**SharePoint Online Bug: **
-> Go to a Page with M365LP Webpart enabled. 
-> Trying to receive German content (automatically loaded through DELVE Profile setting) leads to an error. English Content works fine. 
**MS Teams Bug**
-> While launching the M365 Pathways from a custom Teams App an error occurs. Both Languages (DE/EN). See screenshot. 

### To Reproduce
-> Adding the M365 Webpart to a SharePoint online page. 
-> Enable Multilanguage Support. 
-> Try to reach out to the German content. 
-> Build an App in App Studio. Create a personal tab. Link the tab to the SharePoint Online page. https://<tenantname>.sharepoint.com_layouts/15/teamslogon.aspx?SPFX=true&dest=/sites/<ourSitecollection>/SitePages/Training.aspx

### Expected behavior

A couple of days ago everything worked fine and multilanguage support also worked out in the custom teams app. 
This is how it looked like last week
![image](https://user-images.githubusercontent.com/75801041/101802547-db04b880-3b0f-11eb-880a-04b174ca1501.png)

### Screenshots
**Win10 Teams App does not work**
![image](https://user-images.githubusercontent.com/75801041/101801575-ca077780-3b0e-11eb-8a8f-454e5742382b.png)

**Teams App within the Browser works fine in EN**
![image](https://user-images.githubusercontent.com/75801041/101802004-3e421b00-3b0f-11eb-954e-3a73cf27e276.png)

### Learning Pathways version number

4.1.3.0

### Additional context

On mobile Apps (iOS) the custom Teams App with the personal works fine as well.

**Comment by juliemturner** [comment]
I've seen this type of error happen when the CDN is having trouble serving content. Are you still having the problem?

**Comment by kurtsoeser** [comment]
Hi!

I get also an error with using the MSLP in German. Can you help me where to start?

![image](https://user-images.githubusercontent.com/77322986/104289003-e2c1cf00-54b8-11eb-931f-15b7b8803063.png)

**Comment by juliemturner** [comment]
Do you get the same error when you try and load CustomLearningAdmin.aspx page?  Again, this error normally indicates a M365 issue not an issue with the solution.

**Comment by MB-Podella** [comment]
> I've seen this type of error happen when the CDN is having trouble serving content. Are you still having the problem?

Thanks for reaching out. We "solved" this issue by signing out and signing in within the MS Teams Client (Win10). We've updated our documentation for end users accordingly.

**Comment by jellis-thrive** [comment]
User advised issue has been resolved through behavior change and documentation update on their side. 
Closing issue.
