### ISSUE TITLE
[ENHANCEMENT] Tag content to Microsoft License Types

### ISSUE THREAD

**Issue by eemancini** [pnp/custom-learning-office-365#418]
**Describe the solution you'd like**
Ability to tag the different playlists to license type (E3, E5, F1, etc). For organizations with mixed licensing, this would allow for better filtering for what each employee has access to.

**Describe alternatives you've considered**
This can be done with a sub category manually though it requires a ton of research for the business owner to find out which solutions are available for each license. Given the consistency of licensing across organizations, it would be wonderful for Microsoft to provide this support instead and help improve transparency in licensing options.

**Comment by dcashpeterson** [comment]
Thank you for contributing your ideas. At this point we are focusing our efforts on expanding our existing content and are unable to support this at this time. Thanks for using Microsoft 365 learning pathways!
Thanks for using Microsoft 365 learning pathways and your contribution to making this a better tool! We love this suggestion but at this point we are focusing our efforts on expanding our existing content and are unable to support this at this time.
