### ISSUE TITLE
Manual Deployment vs Automated Provisioning issue

### ISSUE THREAD

**Issue by MSFT-MarcoEs** [pnp/custom-learning-office-365#42]
I used the automated provisioning in a trial tenant and worked fine. Then I moved to the production tenant doing the manual deployment and the script worked fine as well, but the "Site Assets" library and "Site Pages" are not deployed (except for CustomLearningx2 and Home pages). What step I'm I missing or what I'm a doing wrong? Thanks!

**Comment by juliemturner** [comment]
if you don't use the automated provisioning then you don't get all the pages and configuration you do with the PnP provisioning process.  The manual process is only for those that don't want all that configuration done.  If you want to have those pages then I suggest you remove the site collection as well as the app from the tenant app catalog.... and then provision using the PnP provisioning process... that should create the site collection for you with all the additional pages.  Then you can update the web part to the latest version using the instructions in the README.

**Comment by juliemturner** [comment]
Closed due to inactivity.
