### ISSUE TITLE
Content Questions

### ISSUE THREAD

**Issue by dlapierr** [pnp/custom-learning-office-365#420]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [] Installation
- [] Administration
- [] Custom Content
- [] M365 learning pathways web part
- [x] Content

### What is your question

Hello, my customer is trying to customize a playlist for Power Automate - it shows up in the Product list but he does not have the ability to customize/edit it.  He has not had issues customizing other playlists, just Power Automate  .  It appears as if MS has provided it but with no content.  We know where to add  the content from, just no ability to edit for that product specifically.  Also, is the new version 4.1.3 needed to receive updates for the new Yammer experience.  ?

**Comment by juliemturner** [comment]
I will bring it to the content creation teams attention that they included a sub-category for "Power Automate" but no playlists, this is most likely an oversight and the sub-category was left in even though they have no playlists ready for that category.

With regard to your question about Yammer experience I really don't know what you're referencing.

**Comment by dlapierr** [comment]
Thanks so much for the quick response.  How should he proceed in the interim - hide it and not use the sub-category , and create a custom playlist of his own?

**Comment by juliemturner** [comment]
Either, however I'm a bit confused, and maybe this is implied with your answer about upgrading to 4.1.3, but in v4.x of the solution a sub-category would be hidden for the users if it has no playlists... so effectively they shouldn't have to do anything.

**Comment by cah-kamal-deiratany** [comment]
I followed the steps to upgrade to version 4.1.3 but when I get to the last step it says I'm up to date.

**Comment by juliemturner** [comment]
This content bug has been fixed. We've also released 4.1.4.

**Comment by cah-kamal-deiratany** [comment]
Power Automate suddenly disappeared today and is listed under abandond 
![image](https://user-images.githubusercontent.com/47454331/102636610-de58ff00-4122-11eb-88ec-19d743fedf71.png)

**Comment by juliemturner** [comment]
Yes, that's a custom playlist for a sub-category that should not have been included in the official content set as Microsoft has not released any content for it.

To resolve the issue create a new custom sub category and assign this playlist to it.
