### ISSUE TITLE
[QUESTION] How to start clean with Learning Pathways/SharePoint Success Site?

### ISSUE THREAD

**Issue by pgdrews** [pnp/custom-learning-office-365#428]
Is there a documented method for completing removing LP and start clean?  I have a non-Prod tenant and things are just not working right, and even after going through troubleshooting steps, it seems easiest to back everything out and start over. 

Please advise.  Thanks!

**Comment by juliemturner** [comment]
Sure, delete the site collection and remove customlearning.spfx from the tenant app catalog. There are also three tenant app properties, but they'll get overwritten when you reinstall.

If you have the app installed in any other site collections you could also remove it from them but, again that won't really make a difference.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
