### ISSUE TITLE
 Microsoft 365 learning pathways has a configuration issue. 

### ISSUE THREAD

**Issue by barryxu117** [pnp/custom-learning-office-365#429]
the bug is earning pathways has a configuration issue.

**Comment by juliemturner** [comment]
Can you please review these instructions to provide me additional details to assist you:

>WEB PART NOT LOADING: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check guidance](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) before submitting your bug.

**Comment by smcclements** [comment]
I'm getting the same error and the link to the instructions above doesn't work.

**Comment by juliemturner** [comment]
The links changed when we update the repository to open source the code, the new link is: [Diagnosing Pre-Check guidance](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md)

**Comment by smcclements** [comment]
Here are the errors I have: 
![image](https://user-images.githubusercontent.com/57961998/103678276-514edc00-4f51-11eb-9bf9-e016c6b6ab93.png)
![Error](https://user-images.githubusercontent.com/57961998/103678302-5ca20780-4f51-11eb-8698-687425e93cb4.jpg)

**Comment by juliemturner** [comment]
Looks like you have a content pack added and the url for the content pack is either incorrect or the contents of the content pack aren't valid for the version of the web part you have... since you're not the originator of this issue, I'd suggest you open a new "bug" issue and completely fill out the details to provide me enough information to help you. You can reference this issue when you do.

**Comment by smcclements** [comment]
@juliemturner I deleted the first site I provisioned since I realized that I needed to add as a content pack in my current Learning Pathways site. I followed the directions and the site provisioned correctly. Thank you.

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity from the original poster. If you're still having issues, please feel free to open a new issue and reference this one providing more details.
