### ISSUE TITLE
[QUESTION] When will we get M365 Learning Pathways in Dutch?

### ISSUE THREAD

**Issue by harmsze** [pnp/custom-learning-office-365#430]
Earlier, Dutch was announced, but it seems to have dropped from the language list. Any update when Dutch will be added?

Currently I can find a Dutch version of assets when I replace en-us with nl-nl in the asset URL. However, that means I have to create separate custom playlists for the Dutch users. So I hope Dutch will soon be added to the current languages (listed on https://docs.microsoft.com/en-us/office365/customlearning/custom_overview_ml)

**Comment by juliemturner** [comment]
Duplicate #432

**Comment by harmsze** [comment]
Hi Julie, is this the same thing as the subtitles? What I mean in this question is: when will Dutch be added to the languages we have now, in that same way that we now see German, French etc in the CustomLearningAdmin. I haven't found a roadmap for additional languages. 
The subtitles can be a workaround alternative, while we don't have smooth video sound in Dutch. 
![Asset-Languages](https://user-images.githubusercontent.com/76995147/103682061-a35f2400-4f88-11eb-9ed8-d978811e10db.png)

**Comment by juliemturner** [comment]
Yes, you're asking when Dutch will be a supported language... I don't know as I'm not in charge of content I'm in charge of the web part.
