### ISSUE TITLE
[QUESTION] In a M365LP update, are assets updated or replaced by new versions?

### ISSUE THREAD

**Issue by harmsze** [pnp/custom-learning-office-365#431]
We are using many M365 Learning Pathways assets provided by Microsoft, but all of them are displayed via custom playlists. So it is important for us to know for sure if the actual assets are updated, so that we can keep our custom playlists.

Or will only the standard Microsoft playlists keep working, because the assets are replaced by new versions?

**Comment by juliemturner** [comment]
Assets will not be changed in that way although the page that they link to may be updated.  We currently have no way to notify you if the underlying content for the asset changes.

**Comment by harmsze** [comment]
Thanks Julie! But just to be sure I understand it correctly: 
- The underlying content in the non-custom asset pages (text and/or video) gets updated by Microsoft (or somebody else) if anything changes in that M365 app, so that my custom playlist gathering those assets will be kept up-to-date automatically, when the content gets updated? 
- But I won't be notified of those updates in the underlying content, so I should trust the editors of the underlying content (and maybe keep an eye on it from time to time)?

**Comment by juliemturner** [comment]
Yes and Yes... Microsoft is the editors of the underlying content... it's just iFraming pages from support.office.com or docs.microsoft.com.

**Comment by harmsze** [comment]
Great. Thank you Julie!
