### ISSUE TITLE
[ENHANCEMENT] Other language subtitles in the English M365 Learning Pathways videos (Dutch)

### ISSUE THREAD

**Issue by harmsze** [pnp/custom-learning-office-365#432]
Can we get the option to activate closed captions / subtitles in other languages  than the "big" languages at the bottom of English videos? For us, Dutch would be particularly useful.

Currently, I can select closed captions in English, German, French and Chinese (I think). Dutch has been added as a language in the site collection language settings, but I cannot select it in the closed captioning options.

Currently, I can only select Dutch closed captions / subtitles for the nl-nl version of assets found online: subtitles that go with the automated translation (the 'robot lady').

However, many of our users prefer Dutch subtitles to accompany an English voice, rather than the 'robot lady' of the automated translation found online. So while we don't have a smooth Dutch voice over in the videos, subtitles would be very helpful: Dutch users are accustomed to reading Dutch subtitles to an English movie anyway. 

![Video-Subtitles-Dutch-ann](https://user-images.githubusercontent.com/76995147/103668984-17450080-4f78-11eb-8068-0fccf08ae37b.png)

![Video-Subtitles-English-ann](https://user-images.githubusercontent.com/76995147/103668679-a6054d80-4f77-11eb-80b2-932db56d6ed9.png)

**Comment by peterjkrebs** [comment]
We are looking to add support for Dutch in Learning Pathways in the Feb 21 timeframe.

**Comment by juliemturner** [comment]
I am closing this issue as we have released support for Dutch as of the March Content update. 
Here's a link to the article of supported languages: https://docs.microsoft.com/en-us/office365/customlearning/custom_overview_ml
