### ISSUE TITLE
How can I create new Playlist content without headers and footers

### ISSUE THREAD

**Issue by arnostac** [pnp/custom-learning-office-365#437]
I would like to know how can I create new **Playlist Custom Content** without headers and footers and all of the overhead of SharePoint. I want to just create a step by step how-to. 

[**Like This Link**](https://support.microsoft.com/en-us/office/sign-in-to-sharepoint-324a89ec-e77b-4475-b64a-13a0c14c45ec)
https://support.microsoft.com/en-us/office/sign-in-to-sharepoint-324a89ec-e77b-4475-b64a-13a0c14c45ec
Pulls this Layout
![image](https://user-images.githubusercontent.com/42629081/104383317-3fdb7600-54f5-11eb-8509-82b7fea56b16.png)
[**And This Link** ](https://support.office.com/en-us/client/sign-in-to-sharepoint-324a89ec-e77b-4475-b64a-13a0c14c45ec)
https://support.office.com/en-us/client/sign-in-to-sharepoint-324a89ec-e77b-4475-b64a-13a0c14c45ec
Pulls this Layout
![image](https://user-images.githubusercontent.com/42629081/104383671-cf812480-54f5-11eb-9853-826a1f65d7b5.png)

**Comment by juliemturner** [comment]
This is a duplicate of #367

The answer there walks you through changing the url so that it'll work...

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
