### ISSUE TITLE
 Access denied: custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js

### ISSUE THREAD

**Issue by juanfhp** [pnp/custom-learning-office-365#438]
I provisioned the Learning Pathway in my Tenant and when I access in my home computer I don't have any problem to display the content, but  when I try to access in my office computer the content shows an error message. 
I reviewed it with developer tools and I see the next error message:

custom-learning-web-part_2006fa002acf0704e63648563f176ecf.js:1 Message: Error making HttpClient request in queryable [403] Forbidden ::> {​​"odata.error":{​​"code":"-2147024891, System.UnauthorizedAccessException","message":{​​"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."}​​}​​}​​ Data: {​​"response":{​​}​​,"status":403,"statusText":"Forbidden","isHttpRequestError":true}​​

Do I need to do a special requests to the Security Department like "Access to some special URL's", "Change a security configuration in the Explorer"?

### Learning Pathways version number: 4.1.3.0
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/77420648/104535108-2876b880-55db-11eb-9c96-5d7139c38b8a.png)

**Comment by juliemturner** [comment]
Given the error message, which is a 403 forbidden, that implies that the user account you're logging in with doesn't have access to the lists... could also be a proxy issue further up the chain trying to get to GitHub pages url, that's a common issue we see with users when they're behind the firewall of their organization vs home.  So 2 questions:
1. Is it possible you're using a different user from home vs when in the office
2. Is that the full list of errors in the console? -- the scroll bar on the right is cut off so I can't really be sure if there isn't errors above that I'm not seeing. It might be better to export the console.log (right mouse click in the console area) and then attach that file.

**Comment by juanfhp** [comment]
If I access to the SharePoint site using the Global Admin or SPO Admin then I can see the content but if I access using a user account, I can't see the content.

**Comment by juliemturner** [comment]
All users that should be able to view content need to be added to the visitors group of the learning pathways communication site.  If this is everyone in the org you can used the "Everyone except External Users" group.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
