### ISSUE TITLE
Installed Microsoft 365 learning pathways without any issues but after adding the SharePoint Success Site my users are getting an error

### ISSUE THREAD

**Issue by udhar4675** [pnp/custom-learning-office-365#439]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Hello, Installed Microsoft 365 learning pathways without any issues but after adding the SharePoint Success Site my users are getting an error - Microsoft 365 Learning Pathways has a configuration issue. I followed the instructions to the letter and I have both Microsoft 365 learning Pathways tab and the SharePoint Success Site tab when I go to the Custom Admin page. 

### To Reproduce

>Steps to reproduce the behavior

### Expected behavior

>A clear and concise description of what you expected to happen.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.

**Comment by udhar4675** [comment]
![image](https://user-images.githubusercontent.com/76971617/104763524-0775ab00-5734-11eb-8f36-3b6874c36585.png)

**Comment by juliemturner** [comment]
Please validate
- On the "CustomLearningAdmin" page if you go to the SharePoint Success Site tab, the content loads properly?
- If you go to a SharePoint success site page you get the same error, i.e. is the issue only with some users or all users?

**Comment by udhar4675** [comment]
@juliemturner , Yes the content loads properly when I go to both the CustomLearningAdmin page and also when I go to the SharePoint Success Site page. I'm an admin on both the Microsoft 365 Learning pathways site and the SharePoint Success Site. I have added a Microsoft 365 Learning Pathways webpart to training site and it doesn't show up for the other users either.

**Comment by juliemturner** [comment]
Yep, so your problem is permissions... All users who you want to have access to learning pathways content must be in the viewers group of the learning pathways site collection... I would suggest you consider adding "Everyone but External Users" to the viewers group of the learning pathways site.

**Comment by udhar4675** [comment]
Thank you @juliemturner . I will try that.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.

**Comment by udhar4675** [comment]
Julie,
Thank you for all your help. I'm sorry I forgot to close this.
