### ISSUE TITLE
SharePoint PnP Provisioning Service

### ISSUE THREAD

**Issue by jharveysummit** [pnp/custom-learning-office-365#44]
Fail repeated saying I need an App Catalog in the Tenant and one already exist.  Please advise.

**Comment by juliemturner** [comment]
I’m sorry I don’t have enough information to help you.  What exactly is failing, what are you trying to do exactly?

**Comment by jharveysummit** [comment]
Setup the SharePoint learning portal.

Thanks,
jbh

________________________________

**Comment by juliemturner** [comment]
Again, i'm happy to try and assist you if you give me some detailed explanation of what steps you've taken and where you are.  There are two ways to get the custom learning solution into your tenant... by using the pnp provisioning service, which is what we recommend or by a manual method using powershell and other manual steps.  You need to provide me detailed information about what steps you've already taken and where you're seeing the error message.

**Comment by jharveysummit** [comment]
I've attempted to use the service (as my subject line would suggest) w/ this link...

https://aka.ms/CLO365.

I get an e-mail saying "Unfortunately, request to provising "Custom learning for Office 365" template failed."

If that same e-mail it states...

"In order to provision the template you need to have an App Catalog in your tenant.  Please create one, wait 30 mins, and try again"

We already have one (see below).  Please advise.

[cid:e45c5ec5-4b77-4287-af57-9a1726bcf85b]

Thanks,
jbh

________________________________

**Comment by juliemturner** [comment]
Ok thank you hat helps a lot and explains my confusion as support for the provisioning service needs to go to their support issues list. Unfortunately I cannot offer you any support for the provisioning service itself only with the custom learning solution.  I can however transfer this issue to that site or you can submit it there yourself. https://github.com/SharePoint/sp-dev-docs/issues

**Comment by jharveysummit** [comment]
Please transfer it.

Thanks,
jbh

________________________________

**Comment by juliemturner** [comment]
I will and link to it here but be aware since I’ll be entering it for you you will not be notified of updates to it unless you specifically follow the issue.

**Comment by juliemturner** [comment]
Transferred to so-dev-docs for support

https://github.com/SharePoint/sp-dev-docs/issues/3842
