### ISSUE TITLE
[QUESTION] Error: Provisioning could not be completed...

### ISSUE THREAD

**Issue by pgdrews** [pnp/custom-learning-office-365#440]
Strange issue I've not run into before.  I get an error of "In order to provision the template you need Tenant Admin rights. Please ask a Tenant Admin to provision the template for you or to promote yourself to a Tenant Admin." when provisioning the Learning Pathways on a new tenant.  

I created a new E5 dev tenant last week, and I am the GA of the tenant.  I made sure to create the app catalog and then waited over the weekend to attempt to create the Learning Pathways from Look Book.   I had no issues using the PnP provisioning for other Look book templates.  I validated that I'm an admin for the app catalog.  

I created another Global Admin user, and added as admin of the App Catalog, and still get same results trying to provision from the Look Book.  

If I do the manual provisioning steps of creating a communication site, and then adding the Customlearning.sppkg, and then running the M365lpConfiguration.ps1 script, followed by opening the CustomLearningAdmin.aspx file....all completes as expected.     However, that method doesn't give you a nice finished/policed LP site like the PnP Look Book method.  

Is there something I'm missing or is there an issue with Look Book provisioning for this today?  I've done this multiple times in different tenants recently without issue and at a bit of a loss.   Thanks!

Patrick

![image](https://user-images.githubusercontent.com/7563343/104962041-33e03000-599d-11eb-88bc-9dc5825ce263.png)

**Comment by juliemturner** [comment]
Unfortunately, I cannot help you here, you're question would need to be addressed by the provisioning service team:

**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

**Comment by pgdrews** [comment]
Thanks Julie!  Sorry about that...I have reposted over there.  You can close this out/delete as you see fit.  Thanks!

**Comment by juliemturner** [comment]
No worries! Closing it out!
