### ISSUE TITLE
[ENHANCEMENT] When/how do we get assets about new Teams features like breakout rooms?

### ISSUE THREAD

**Issue by harmsze** [pnp/custom-learning-office-365#441]
When will we get assets about the new features in MS Teams that were rolled out end of 2020, like breakout rooms and the option to poll attendees? 
Or do we have to do something from our end to pull them in?

I did find this page online, but I could not find it within Learning Pathways: https://support.office.com/en-us/client/7de1f48a-da07-466c-a5ab-4ebace28e461?embed=true

**Comment by eemancini** [comment]
New content is added in batches so when the next content update happens, whatever additions the Learning Pathways team makes to the content packs will automatically available in your Learning Pathways instance. I see you have the URL formatted correctly to add manually as an asset now too. I just tested in my environment and that page works beautifully :)

**Comment by karuanag** [comment]
We'll be publishing a list of content updates on March 4th during Microsoft Ignite on our blog at https://aka.ms/DriveAdoption When we publish new content as mentioned above it will simply stream into your experience but your custom playlists will not be disrupted.

**Comment by jellis-thrive** [comment]
Content focused question
User received an answer, no follow up responses
Closing issue
