### ISSUE TITLE
Unable to load SharePoint Success Site into M365 Learning Pathways

### ISSUE THREAD

**Issue by dtsmith1984** [pnp/custom-learning-office-365#442]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [X] Installation
- [ ] Learning Pathways Content
- [X ] SharePoint Success Content
- [ ] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### What is your question
Upon attempting to provision the SharePoint Success Site into M365 Learning Pathways I receive the following error:

Sorry, something went wrong
There was an unexpected issue.
Could not load file or assembly 'OfficeDevPnP.Core, Version=3.28.2012.0, Culture=neutral, PublicKeyToken=5e633289e95c321a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

>Provide related screen-shots to help us understand your question

**Comment by juliemturner** [comment]
Unfortunately, we cannot help you with provisioning issues so you would need to submit your issue there... see the following notice.  That said, I have heard that they had a rather big issue and provisioning wasn't working at all for anyone.  The last I heard was that they were able to fix it over night last night, not sure where that is in the rollout but I would follow the provisioning service GitHub repo linked below to follow the progress.

**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).
