### ISSUE TITLE
"Microsoft 365 learning pathways" Web Part Provisioning issue for Mac Users (OS - Mohave & Big Sur)

### ISSUE THREAD

**Issue by GandhiAmit** [pnp/custom-learning-office-365#443]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

"Microsoft 365 learning pathways" Web Part is not working for Mac users (Users are on Mac OS Mohave & Big Sur). They are getting following error message – "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance"

Users are getting error message on page where "Microsoft 365 learning pathways" Web Part is enabled. Error is showing up while loading up page.

>Steps to reproduce the behavior

### Expected behavior
![Expected Behaviour](https://user-images.githubusercontent.com/24833618/106188267-9b476e00-615b-11eb-8fcb-1c4a51d34539.png)

>A clear and concise description of what you expected to happen.

### Screenshots
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/24833618/106186865-b87b3d00-6159-11eb-8a38-02d0ca0320a8.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/24833618/106186868-b913d380-6159-11eb-959a-b509c0adee46.png)

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number
Version | 4.1.3.0
Release Date | October 2020

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

"Microsoft 365 learning pathways" Web Part is not working for Mac users (Users are on Mac OS Mohave & Big Sur). They are getting following error message – "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance"

>Add any other context about the problem here.

**Comment by juliemturner** [comment]
Unfortunately, your screenshot of the actual error from the browser console is too small for me to read.  Could you please capture the log in a text file and share it:

>WEB PART NOT LOADING: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check guidance](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) before submitting your bug.

**Comment by juliemturner** [comment]
Also... I did test this in Safari 14 on Big Sur and it worked for me without a problem.

Is it possible the users in question don't have access to the learning pathways site rather than an issue with the browser/OS? Honestly there is nothing in the code that could have impact on a particular OS, but maybe a particular version of a browser, but even then pretty remote.

**Comment by Tom-Robbins-COL** [comment]
Tried with Chrome and Firefox (private sessions).  Same issue.  Just Provisioned both the M365 Learning Pathway and SharePoint Success yesterday and trying to go through them.

**Comment by juliemturner** [comment]
So, this is just an issue with the tool period and not really about the browser.  

Can you please share the diagnostic information I asked for... you shared a screen shot but it's too small and I can't read it.

**Comment by GandhiAmit** [comment]
I am working with user to get diagnostic information, I will share info as soon as I have it.

**Comment by juliemturner** [comment]
so it works for you?  If so then maybe you just have a permission issue.

**Comment by GandhiAmit** [comment]
We noticed that it was an untrusted certificate issue. Users were not able to load "Microsoft 365 learning pathways" Web Part because they were part of specific OU in AD Group which had an untrusted certificate issued.

Thanks for your help.

**Comment by jellis-thrive** [comment]
User advised issue was resolved due to security configuration
No further responses, all thanked within thread
Closing issue
