### ISSUE TITLE
Issue after installation

### ISSUE THREAD

**Issue by chasquad** [pnp/custom-learning-office-365#444]
Provisioning went fine.  But then when I attempt to navigate to the CustomLearningAdmin.aspx page I get this:

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
[SPLoaderError.loadComponentError]:
Failed to load component "c6062b6a-f22c-4475-897b-25081673c54a" (CustomLearningAdminWebPart). Original error: Failed to load URL 'https://publiccdn.sharepointonline.com/uif.sharepoint.com/sites/UIFAPPS/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/webpart-m365lpstrings_en-us_5ebf05c87596e5efe5e691d313907759.js' for resource 'M365LPStrings' in component 'c6062b6a-f22c-4475-897b-25081673c54a' (CustomLearningAdminWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

INNERERROR:
Failed to load URL 'https://publiccdn.sharepointonline.com/mysite/sites/UIFAPPS/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/webpart-m365lpstrings_en-us_5ebf05c87596e5efe5e691d313907759.js' for resource 'M365LPStrings' in component 'c6062b6a-f22c-4475-897b-25081673c54a' (CustomLearningAdminWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
CALLSTACK:
t@https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6aa2fc520591708ec0b2ff861ee40b72.js:1:870055
t@https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6aa2fc520591708ec0b2ff861ee40b72.js:1:1013808
ff4n/c</e.buildErrorWithVerboseLog@https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6aa2fc520591708ec0b2ff861ee40b72.js:1:1036982
ff4n/c</e.buildLoadComponentError@https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6aa2fc520591708ec0b2ff861ee40b72.js:1:1033027
t/</<@https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_06fb90fbb103ba8a0bb1.js:1:66114

**Comment by juliemturner** [comment]
This is a network or CDN problem with your tenant... there isn't really anything I can do to help.  I will say that others that have experienced it report that it normally clears itself up.

**Comment by chasquad** [comment]
Thanks for the quick response.

The issue wasn't network or CDN, but although the solution appeared to
provision correctly without error, I found that in the App Catalog the
solution was not deployed as the Deployed column was a value of "No."  So,
I selected the solution and clicked "Deploy" in the ribbon and then the
pages started working without error on the site.

Thank you.

**Comment by juliemturner** [comment]
excellent!
