### ISSUE TITLE
 CDN Errors on "Launch and Manage Your Site" Page

### ISSUE THREAD

**Issue by Ukiman1014** [pnp/custom-learning-office-365#445]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug
Receiving "Microsoft 365 learning pathways has a configuration issue" error when loading the "Launch and Manage Your Site" page.  Provisioning went okay but this is the first error I found.  Seems to be related to the CDN in some way.  I'm not very familiar with how that works, other than what a CDN is.

### To Reproduce
Attempt to load the "Launch and Manage Your Site" page.

### Expected behavior
Not sure!  I've never been able to load the page.

### Screenshots
[LandM Error](https://user-images.githubusercontent.com/22643106/106299106-c8ab1f00-6222-11eb-81a5-5373cd15e752.jpg)
![Errors](https://user-images.githubusercontent.com/22643106/106299348-0c9e2400-6223-11eb-8218-86d0a355e464.jpg)

### Learning Pathways version number
I just installed it today.  Unfortunately I'd have to get our tenant admin to look at the version - I'm prevented from seeing it in Azure.

### Additional context
Browser Dev Logs:
[custbank.sharepoint.com-1611936235889 - all.log](https://github.com/pnp/custom-learning-office-365/files/5894845/custbank.sharepoint.com-1611936235889.-.all.log)
[custbank.sharepoint.com-1611936201389 - errors.log](https://github.com/pnp/custom-learning-office-365/files/5894847/custbank.sharepoint.com-1611936201389.-.errors.log)

**Comment by juliemturner** [comment]
First try to go to the CustomLearningAdmin.aspx page first. If you provision from the provisioning service, the page is linked under the Home menu -> Learning pathways administration.

See if that loads correct, if it does that I think you're probably all set.

**Comment by Ukiman1014** [comment]
Hi Julie,
I went to the admin page but I'm getting the same error.  It has a slightly different URL than you described, "Success-site-administration.aspx" but I'm pretty sure I'm in the right place.  Is there something else I can try, as a next step?

![AdminErrors1](https://user-images.githubusercontent.com/22643106/106316425-b3da8580-623a-11eb-848a-4d1222b07bf0.jpg)
![AdminErrors2](https://user-images.githubusercontent.com/22643106/106316429-b63cdf80-623a-11eb-86db-5c64f84eab87.jpg)

**Comment by juliemturner** [comment]
Sorry, I didn't understand that you were talking about the SharePoint Sucess site not Learning pathways site, my directions were based on the learning pathways site.

Anyway, watch [this video](https://youtu.be/HZjxBAKVnJs) to see what the process is for deploying the SharePoint success site, I believe you skipped the last step which is to add the content pack to learning pathways administration.

**Comment by Ukiman1014** [comment]
Ah, that was it!  I forgot to go back to Learning Pathways and click “Complete”. Thanks for the help!
