### ISSUE TITLE
[QUESTION] Error adding Content Pack

### ISSUE THREAD

**Issue by jeffwllms** [pnp/custom-learning-office-365#447]
>**WEB PART NOT LOADING**: Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.].

## Submit your question
I get an error adding content pack.  Looking at dev tools. it appears it is looking for a manifest.json.  I only had a metadata.json.  I have tried renaming the metadata.json to manifest.json.  It didn't work.  I have tried creating a manifest that is copy of metadata.json.  it isn't working.  When I go to developer tools, network it does appear that the manifest.json is giving a 404.  which i dont understand becasue i can hit the same url  just fine in a couple of browsers.  File is being served by github.io.  Is there possible a weird cache thing going on?

### What is the context of your question

- [ ] Installation
- [ ] Learning Pathways Content
- [ ] SharePoint Success Content
- [ ] Administration
- [x] Custom Content
- [ ] Viewer Web Part

### What is your question

>Provide related screen-shots to help us understand your question

**Comment by jeffwllms** [comment]
So i cleared browser cache and cookies, gave it another shot.  Now i get a different error.  Same error from withing the webpart.  but in developer tools I get a failed to load response data. as well as an odata error "The expression "web/lists/getByTitle('CustomConfig')/items(NaN)" is not valid."

**Comment by jeffwllms** [comment]
Okay, I also think i am seeing something interesting.  for some reason it is looking for the manifest.json in a directory above by the base url I gave. 
i gave the url of "<organization>.github.io/<repo>/learning/v4/en-us/"

it appears to be looking for a manifest.json in ""<organization>.github.io/<repo>/learning/v4/"
i looked at the documentation and didnt notice anything about a manifest file.  But i took a second look at this repo and see the manifest now pulled from the metadata.  is this new with how multi-lingual is being handled.  Anyway, I have seemed to work through it. 
the [docs](https://docs.microsoft.com/en-us/office365/customlearning/custom_partnerguide_contint) might need to be updated.

**Comment by juliemturner** [comment]
You're looking at documentation that is out of date for version 4 which supports multilingual and therefore the structure is different.  If you look at this repo's docs folder and follow that structure it'll be more obvious what you need to do.
https://github.com/pnp/custom-learning-office-365/tree/main/docs/learningpathways/v4

**Comment by jellis-thrive** [comment]
Guidance provided; issue relates to procedure from established documentation
No further response from requestor
Closing issue
