### ISSUE TITLE
CustomLearningAdmin.aspx is empty

### ISSUE THREAD

**Issue by vsolanes** [pnp/custom-learning-office-365#448]
![image](https://user-images.githubusercontent.com/78366777/106475987-d8d33080-64a6-11eb-8629-d3da1c930381.png)

**Comment by juliemturner** [comment]
Can you please review these instructions to provide me additional details to assist you:

>WEB PART NOT LOADING: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check guidance](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) before submitting your bug.

**Comment by pb762** [comment]
I am also seeing this issue in our tenant. The error I see in the developer console is
Access to XMLHttpRequest at 'https://waconatm.officeapps.live.com/apc/trans.gif?fde6f60ee9c5c7a072198fe8859b7aeb' from origin 'https://<mysharepointenant.com>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Not sure what has changed in the meantime for this to have stopped working...
Any guidance?

**Comment by jellis-thrive** [comment]
Requestor has not returned for assistance
No further question(s) or follow up
Closing issue due to lack of engagement
