### ISSUE TITLE
Outook subcategory just showing playlist items related to Outlook Mobile

### ISSUE THREAD

**Issue by Josex1975** [pnp/custom-learning-office-365#449]
Hi!
We have a custom installation based on Spanish as a default language. Not another language supported. We used this guide to setup the environment:

https://docs.microsoft.com/en-us/office365/customlearning/custom_manualsetup#option-3---you-want-multilingual-support-but-want-a-different-default-language-for-the-site

Everything went in appearance ok, but we noticed that when we insert the viewer webpart in a new page and try to get the items from the Outlook subcategory, the webpart just show the playlists that are related to Outlook Moblie, although there are another play lists related to another Outlook tips. This is hapening wih the standar content, no customizations. 
We've find a workaround: copy the playlists that are not showing and assign them the Outlook Mobile technology.
It seems that is a bug, in another tenants with the installation in English from the lookbook everything goes as expected.

**Comment by juliemturner** [comment]
Please share screen shots:
- What you're seeing in the web part and what settings in the property pane for the web part are
- What the CustomLearningAdmin.aspx page looks like for the outlook category
- What the "About" page shows in CustomLearningAdmin.asp -- find it by selecting the ... button on the right side near the top of the screen, just to the left of the ? help button, and then selecting "About Web Part"

**Comment by Josex1975** [comment]
Hi Julie! Thank you very much for your support. We switched to Technology and hidden/show the "Outlook" category and it started to work!
