### ISSUE TITLE
Adding New Content?

### ISSUE THREAD

**Issue by clayjam** [pnp/custom-learning-office-365#45]
I noticed in the admin section in the Technology Tab there is a section for Windows 10. 

I have created a Windows 10 page but how do I go about configuring the web part to automatically pull Windows 10 content through ?

I created a new Windows 10 sub-category but it doesn't seem to connect to any Windows 10 content.

**Comment by juliemturner** [comment]
The technology tab is meant to filter out playlists and assets flagged with a particular technology.  For those organizations who have not rolled out Teams, or OneDrive or some other facet of Office 365.  

Sub categories are meant to allow you to group a set of custom created playlists together for your own purposes.  The web part, through web part properties will allow you to pin to a particular sub category, either a custom one or one provided through the solution.

To create a custom playlist and have it be part of the windows 10 sub category you created you need to create a custom playlist and then set the Category and Sub Category values to (let's assume you create the Windows 10 custom sub category in Products category) to the Products and Widows 10 values.

To add Microsoft provided assets to your playlist that are specific to Windows 10, you would search for Windows 10 when adding the assets to the custom playlist.  That said I don't believe at this time there is any Windows 10 content, but there may be in the future.  If you have found articles on support.microsoft.com or some other Microsoft site that you would like to use you can create a custom asset, which creates a page in SharePoint and then you can embed that article in the page and then that will become an asset in that playlist.

**Comment by clayjam** [comment]
Thanks Julie. Is there a way to find material in the in the content catalog ? BTW, we are really liking the custom learning centre and are customising the interface to suit our company. Looking forward to future enhancements.

**Comment by juliemturner** [comment]
When adding assets to a playlist there is a search function. Type a keyword and it searches the text of the assets metadata (not the asset itself)
