### ISSUE TITLE
 SharePoint menu item referencing a SharePoint page with Web part must be clicked twice for the page to appear

### ISSUE THREAD

**Issue by peterjkrebs** [pnp/custom-learning-office-365#451]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug
Customer has created custom product pages with the Learning Pathways web part and a SPO global menu with menu items pointing to the product page. The menu items must be selected twice for the page to appear.

### To Reproduce

>Create several new SPO pages and add the Learning Pathways Web part to them. Filter the Web part as appropriate.
Create a menu item with sub menu items referencing the custom pages.

### Expected behavior
When the menu item is clicked the page specified in the menu item should appear.

**Comment by juliemturner** [comment]
I need more details about 

>the menu item should appear

Can you please include a screen shot of the behavior of the page.. is there an error, is the entire screen blank, does only the web part not appear?

Also, why type of navigation, MegaMenu or Cascading?

**Comment by chrchris** [comment]
Hi, there is no error message.

We have created a dropdown menu in Learning Pathways, linking to various O365 products.

![image](https://user-images.githubusercontent.com/78826712/107435317-f8e39f00-6af9-11eb-99c1-0bcf24d61ed3.png)

The first click takes you to the selected product page (Excel in the screenshot). Subsequently, if you wish to navigate to another product you need to click twice on the dropdown, with the first click doing nothing.

**Comment by juliemturner** [comment]
@chrchris -- I need details on what the URL is in those product links... are they links to individual pages or something else?

**Comment by chrchris** [comment]
@juliemturner -- The URL's on those products links came from each products (i.e Excel) page link panel

![image](https://user-images.githubusercontent.com/78826712/107561000-035e7100-6bac-11eb-8ba7-a803a1e7a2ce.png)

**Comment by juliemturner** [comment]
So unfortunately, the issue you're running into isn't related to learning pathways it's an issue with page optimization code in SharePoint. I assume that you got the link all from the same page, which is fine when you're linking from elsewhere. What I believe is happening is that the SharePoint page optimization code triggers the link but then sees the base of the url is the same and thereby doesn't actually fully reload the page which means the web part on the page isn't reloaded which means it's not being triggered to load different content. 

_For more technical, dev related information on this issue you can review this blog post: [SPFx Anchor Tags - Hitting the Target](https://julieturner.net/2018/08/spfx-anchor-tags-hitting-the-target/)_

All is not lost, but it'll mean a bit more work. If you create a page for each product and then put the learning pathways web part on it and then filter it, using the web part properties, to the sub-category you want to show, then use the link to that page in the nav everything will work correctly.

**Comment by chrchris** [comment]
Thank you so much for the update Julie! It seems we will have to do a little more work, create a page per product and filter it from the web part properties.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
