### ISSUE TITLE
Learning pathways Admin Success Center issue

### ISSUE THREAD

**Issue by Damnit9** [pnp/custom-learning-office-365#453]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

When I go to home --> admin succes center or learning pathways administration I got thos messages

Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.]

### To Reproduce

go to home --> admin succes center or learning pathways

### Expected behavior

display the administrative settings
### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

4.1.3.0

### Additional context

Not sure if I opened the case at the proper place but please can you help me?

**Comment by juliemturner** [comment]
Yes, you posted it to the right place but you didn't include enough detail for me to assist.

You mention SharePoint Success site, but also learning pathways... So, when you say you go to learning pathways administration do you mean to say that the root tab for Microsoft 365 learning pathways gives you that error or the SharePoint Success Site content pack give you that error?  

- Can you please include a screen shot of the learning pathways admin area?
- Follow this guidance for submitting more detail about the error:
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

**Comment by Damnit9** [comment]
Here is some screenshot where are the error:


[cid:image001.jpg@01D6FEED.6E287DE0]


[cid:image002.jpg@01D6FEED.6E287DE0]


Regards

**Comment by juliemturner** [comment]
So I suspect you posted the above by replying via email, unfortunately that is not a great experience and the images you include do not come through, also be aware when you post that way that all your PII included in the email gets posted to the issue list, I only mention that because lots of people have information in their signatures, anyway, I still do not have enough information to assist you.

**Comment by Damnit9** [comment]
Sorry I didn't know that, here are the screen
![learning](https://user-images.githubusercontent.com/78730658/107382218-ee240c80-6aef-11eb-9898-fc871eb9c831.PNG)
![learn](https://user-images.githubusercontent.com/78730658/107382222-eebca300-6aef-11eb-8f60-36d4ac991fad.PNG)

**Comment by juliemturner** [comment]
Ok, thank you, that helps a lot.  

What I suspect your issue is, is that although you provisioned the SharePoint Success Site you didn't complete the installation.  Please check out this super short video which explains [How to provision the SharePoint Success Site](https://youtu.be/HZjxBAKVnJs)

**Comment by Damnit9** [comment]
Sorry for the late answer

But I am not able to provisioned the sharepoint site as I have on the issue on the learning pathways administration pages

Regards

**Comment by juliemturner** [comment]
I am not following what your comment means. Please navigate to your main learning pathways site and then go to the site pages library and then view the CustomLearningAdmin.aspx page.  Please let us know if you have issues loading that page.  If so, then we will address that, if not then I think you have just missed a step with

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
