### ISSUE TITLE
LP Admin page broken following change of site URL

### ISSUE THREAD

**Issue by hsolsc** [pnp/custom-learning-office-365#455]
I recently changed the site URL of our Learning Pathways site, following this support article (https://github.com/pnp/custom-learning-office-365#changing-the-url-of-your-microsoft-365-learning-pathways-site). 

A support engineer and I have 40mins trying to update the Tenant App property (using/modifying the UpdateM365lpSiteUrl.ps1. script) but have had no success. Most elements on the site still work - and the LP web part can be deployed on pages without issue. But the LP admin page (CustomLearningAdmin.aspx), is not working. It now loads as follows:

"TypeError: Cannot read property '0' of undefined
in t in t in o in t in t in t in t in t in section in div in div in t in Styledt in t in o in t in t in t"

Expected behavior for the LP admin page to load properly, so that we can customise the learning pathways. 

Would appreciate help resolving.
Thanks
Hans

Learning Pathways version number: {26C9CD9F-DB62-49B1-B102-7F0DAD281EA0}

**Comment by juliemturner** [comment]
You said you had no success executing the PowerShell script UpdateM365lpSiteUrl.ps1? Could you provide some details? I would ask if the user you are using is a site collection admin of your tenant app catalog?

Also, if you could provide the console log information from the CustomLearningAdmin.aspx page that would be helpful. Here are some instructions:

>WEB PART NOT LOADING: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check guidance](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) before submitting your bug.

**Comment by hsolsc** [comment]
Hi Julie, 
We're still stuck with this one. See more info below. We've tried this as a tenant administrator and app catalog site collection owner. We were getting a lot of errors with the code as provided so we slimmed it down to the bare essentials but still no success. Thanks in advance,
Hans



### Slimmed down code
`Install-Module -Name "PnP.PowerShell"
Connect-SPOService -Url https://[tenant].sharepoint.com 
Set-PnPStorageEntity -Key MicrosoftCustomLearningSite -Value “https://[tenant].sharepoint.com/sites/[site name]” -Description "Microsoft 365 learning pathways Site Collection"
Get-PnPStorageEntity -Key MicrosoftCustomLearningSite
Disconnect-PnPOnline
`

### Subsequent error message
Set-PnPStorageEntity : The term 'Set-PnPStorageEntity' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ Set-PnPStorageEntity -Key MicrosoftCustomLearningSite -Value “https:/ ...
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-PnPStorageEntity:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32> Get-PnPStorageEntity -Key MicrosoftCustomLearningSite
Get-PnPStorageEntity : The term 'Get-PnPStorageEntity' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ Get-PnPStorageEntity -Key MicrosoftCustomLearningSite
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-PnPStorageEntity:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


### LP Admin page console error
sp-pages-assembly_en-us_4d5f6335cbb13d1d54c800033a544f59.js:65 TypeError: Cannot read property '0' of undefined
    at t._ensureWebPartData (chunk.sp-pages-singlewebpartapppagelayout_en-us_838eeffbf59440cf2299.js:1)
    at t._updateCommandBarProps (chunk.sp-pages-singlewebpartapppagelayout_en-us_838eeffbf59440cf2299.js:1)
    at t.getCommandBarProps (chunk.sp-pages-singlewebpartapppagelayout_en-us_838eeffbf59440cf2299.js:1)
    at t.renderCommandBar (sp-pages-assembly_en-us_4d5f6335cbb13d1d54c800033a544f59.js:1)
    at t.renderPageLayout (sp-pages-assembly_en-us_4d5f6335cbb13d1d54c800033a544f59.js:1)
    at t.render (sp-pages-assembly_en-us_4d5f6335cbb13d1d54c800033a544f59.js:65)
    at Ua (sp-pages-assembly_en-us_4d5f6335cbb13d1d54c800033a544f59.js:65)
    at Aa (sp-pages-assembly_en-us_4d5f6335cbb13d1d54c800033a544f59.js:65)
    at bo (sp-pages-assembly_en-us_4d5f6335cbb13d1d54c800033a544f59.js:65)
    at wu (sp-pages-assembly_en-us_4d5f6335cbb13d1d54c800033a544f59.js:65)

**Comment by juliemturner** [comment]
So you've changed the script?  What you pasted above is not the correct command for connecting to the site with PnP Powershell, the command is Connect-PnPOnline... What errors do you get if you try running the script as is?

**Comment by hsolsc** [comment]
Hi Julie, 
Obviously I / we / our MS Partner support desk didn't know that. Thanks for the correction. Here's a re-run using the original code, with 'contoso' standing in for the actual tenant name used. 
Thanks again, 
Hans

[Error.txt](https://github.com/pnp/custom-learning-office-365/files/6090444/Error.txt)

**Comment by juliemturner** [comment]
The error messages show that you tried to connect to contoso.sharepoint.com... and then basically the error messages show that it failed to connect to that tenant (which makes sense).

You need to pass in the tenant name and site collection you're trying to connect to...

**Comment by hsolsc** [comment]
That's not the case. As I explained in my last message, I redacted the actual tenant name with 'contoso' because I wasn't comfortable posting the actual tenant name to this open forum. Rest assured, we entered the correct tenant name.

**Comment by juliemturner** [comment]
Yep I know... but I have no other way to communicate your error message to you then the redacted name you used.

The error message is still that it can't connect to your tenant... I have no way of helping you with that. That's an issue with your tenant and using PowerShell to connect to it now with learning pathways script.

**Comment by hsolsc** [comment]
Hi Julie, 

Apologies for the delay, I’ve been following up with a Microsoft Support Ambassador. They supported us to run the original script, which still failed to update the LP admin page. They reviewed the page source and network trace data for our LP admin page, and confirmed the script was successful in setting the PNPStorageEntity. The errors seen in the logs are provided below for reference.

handleFailure({message:"Can\u0027t load the application on this page. Use the browser Back button to retry. If the problem persists, contact the administrator of the site and give them the information in Technical Details.", error: new Error("SPFx loader is not present in the page.")});

spfxAssemblyScriptTag.onerror = onerror || function(e) {

handleFailure({message:"Can\u0027t load the application on this page. Use the browser Back button to retry. If the problem persists, contact the administrator of the site and give them the information in Technical Details.", error: new Error(e.message)});

They have recommended we revert to you. Although it would cause significant disruption, at this point I am tempted to remove and reinstall the LP app on our tenant. Do you have any other recommendations that could save me a lot of hassle before I do so? 

Thanks
Hans

**Comment by juliemturner** [comment]
My gut tells me that somehow the the `PageLayoutType` of the CustomLearningAdmin.aspx page got set to something other than SingleWebPartAppPage. 

I can cobble together the script pieces here you need to recreate it...
1. Delete the CustomLearningAdmin.aspx page from the main learning pathways site's pages library (this is the site you sent the tenant app property `MicrosoftCustomLearningSite`)
2. Create the following script and have a user who is a site collection admin of the main learning pathways site run it. Where $clSite variable is the site collection url (e.g https://contoso.sharepoint.com/sites/M365lp)

```powershell
Connect-PnPOnline -Url $clSite -UseWebLogin

$claPage = Add-PnPClientSidePage "CustomLearningAdmin" -Publish
$claSection = Add-PnPClientSidePageSection -Page $claPage -SectionTemplate OneColumn -Order 1
Add-PnPClientSideWebPart -Page $claPage -Component "Microsoft 365 learning pathways administration"
Set-PnPClientSidePage -Identity $claPage -Publish
$cla = Get-PnPListItem -List $sitePagesList -Query "<View><Query><Where><Eq><FieldRef Name='FileLeafRef'/><Value Type='Text'>CustomLearningAdmin.aspx</Value></Eq></Where></Query></View>"
$cla["PageLayoutType"] = "SingleWebPartAppPage"
$cla.Update()
Invoke-PnPQuery
``` 

This code snippet was extracted from the larger [M365lpConfiguration.ps1](https://github.com/pnp/custom-learning-office-365/blob/main/installation/M365lpConfiguration.ps1) script which alternatively could be run using the `-SiteAdminOnly` switch and achieve the same outcome (and it would take care of deleting the existing page).

**Comment by hsolsc** [comment]
YES JULIE!! You've solved it!! The LP admin page is back and even our custom pathways are present and correct. I am delighted. 
Sincere and humble thanks,
Hans

**Comment by juliemturner** [comment]
SWEET! Glad it's solved. 

Going to close this issue, if you have any further issues please feel free to open up a new one. Have a great day!
