### ISSUE TITLE
 Cannot run UpdateM365lpSiteUrl.ps1 with MFA

### ISSUE THREAD

**Issue by Bones5279** [pnp/custom-learning-office-365#456]
Hi,
We unfortunately have multiple site collections setup for LP. I need to change the path to the correct one and delete the other. While trying to run the script "pnponline not found"
![image](https://user-images.githubusercontent.com/50229488/108047207-355d5080-704e-11eb-96e3-52cc4441c1f3.png)
It is installed. I am global admin and SP Owner.
![image](https://user-images.githubusercontent.com/50229488/108048705-0647de80-7050-11eb-90d9-b0939ca3278a.png)

**Comment by ToddKlindt** [comment]
I goofed up the logic on the module check. Sorry about that. I fixed it and submitted the PR. You should be good to go now.

**Comment by Bones5279** [comment]
Thank You Very Much
