### ISSUE TITLE
 Configuration error - webpart not working for some users

### ISSUE THREAD

**Issue by hkuu** [pnp/custom-learning-office-365#457]
## Describe the bug

Newly provisioned M365 Learning Pathways site (created last week), the webpart returning configuration error message for some users (Swedish profile language, other user site owner and the other reader). 

The site and the app is working fine for me as admin and one other test user (the test user is a site owner and both of our profile languages are English). Not sure if the language makes a difference or not. 

Multilingual support has been disabled. The site is in English. CustomConfig list has been emptied. 

### To Reproduce

Haven't been able to reproduce the issue on my end. 

### Screenshots

![image](https://user-images.githubusercontent.com/79146420/108064386-45345f00-7065-11eb-8803-c9e73415fc05.png)

### Learning Pathways version number

4.1.3

### Additional context

Snippets from the logs provided by the affected user: 

DevTools failed to load SourceMap: Could not load content for https://xxx.sharepoint.com/sites/Apps/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/en-us.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
custom-learning-admin-web-part_7b54fdb5adf76a68373a127035fc2de3.js:1 Message: [b4d2eebb-f1ae-44c3-a84d-7f878abed365] (1613476025295) Beginning GET request (https://xxx.sharepoint.com/sites/LearningPathways/_api/web/getStorageEntity('MicrosoftCustomLearningSite')) Data: {}
custom-learning-admin-web-part_7b54fdb5adf76a68373a127035fc2de3.js:1 Message: [b4d2eebb-f1ae-44c3-a84d-7f878abed365] (1613476025297) Sending request.
custom-learning-admin-web-part_7b54fdb5adf76a68373a127035fc2de3.js:1 Message: [b4d2eebb-f1ae-44c3-a84d-7f878abed365] (1613476025665) Completing GET request. Data: {}
custom-learning-admin-web-part_7b54fdb5adf76a68373a127035fc2de3.js:1 Message: [b4d2eebb-f1ae-44c3-a84d-7f878abed365] (1613476025666) Returning result from pipeline. Set logging to verbose to see data. Data: {}
custom-learning-admin-web-part_7b54fdb5adf76a68373a127035fc2de3.js:1 Message: [270889b6-1a10-44e2-ac50-60f334d694ca] (1613476025672) Beginning GET request (https://xxx.sharepoint.com/sites/LearningPathways/_api/web/getStorageEntity('MicrosoftCustomLearningCdn')) Data: {}
custom-learning-admin-web-part_7b54fdb5adf76a68373a127035fc2de3.js:1 Message: [270889b6-1a10-44e2-ac50-60f334d694ca] (1613476025673) Sending request.
custom-learning-admin-web-part_7b54fdb5adf76a68373a127035fc2de3.js:1 Message: [270889b6-1a10-44e2-ac50-60f334d694ca] (1613476025848) Completing GET request. Data: {}
custom-learning-admin-web-part_7b54fdb5adf76a68373a127035fc2de3.js:1 Message: [270889b6-1a10-44e2-ac50-60f334d694ca] (1613476025849) Returning result from pipeline. Set logging to verbose to see data. Data: {}
custom-learning-admin-web-part_7b54fdb5adf76a68373a127035fc2de3.js:1 Message: [478e5071-d421-4f68-b361-5a772cefec86] (1613476025857) Beginning GET request (https://xxx.sharepoint.com/sites/LearningPathways/_api/web/lists/getByTitle('CustomConfig')/items?$select=Id,Title,JSONData&$filter=Title eq 'CustomCDN'&$top=1) Data: {}
custom-learning-admin-web-part_7b54fdb5adf76a68373a127035fc2de3.js:1 Message: [478e5071-d421-4f68-b361-5a772cefec86] (1613476025858) Sending request.
custom-learning-admin-web-part_7b54fdb5adf76a68373a127035fc2de3.js:1 Message: [478e5071-d421-4f68-b361-5a772cefec86] (1613476026195) Completing GET request. Data: {}
custom-learning-admin-web-part_7b54fdb5adf76a68373a127035fc2de3.js:1 Message: [478e5071-d421-4f68-b361-5a772cefec86] (1613476026195) Returning result from pipeline. Set logging to verbose to see data. Data: {}
chunk.tti-polyfill_none_656e1f8d35f0ecfabd8a.js:1 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: Paint Timing. https://www.chromestatus.com/features/5637885046816768.

CustomLearningAdmin.aspx:1 Access to fetch at 'https://pnp.github.io/custom-learning-office-365/learningpathways/v4/manifest.json' from origin 'https://xxx.sharepoint.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
sp-pages-assembly_en-us_f2a6d5a2ddacad6fe99f72579e74f146.js:65 GET https://pnp.github.io/custom-learning-office-365/learningpathways/v4/manifest.json net::ERR_FAILED

custom-learning-admin-web-part_7b54fdb5adf76a68373a127035fc2de3.js:1 Message: TypeError: Failed to fetch - InitService (getManifest)

DevTools failed to load SourceMap: Could not load content for https://amcdn.msftauth.net/meInlineBackCompat.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
chunk.vendors~search-page-main_none_95f2c68413e2b2768693.js:1 Some icons were re-registered. Applications should only call registerIcons for any given icon once. Redefining what an icon is may have unintended consequences. Duplicates include: 
GlobalNavButton, ChevronDown, ChevronUp, Edit, Add, Cancel, More, Settings, Mail, Filter (+ 1791 more)

activitymonitor.js:223 Error: Error: Idle tracking cookie is missing.
    at IdleSessionActivityMonitor.GetCookieValue (activitymonitor.js:360)
    at IdleSessionActivityMonitor.InitializeSettingsFromCookie (activitymonitor.js:344)
    at IdleSessionActivityMonitor.GetTimeToNextCheck (activitymonitor.js:308)
    at Function.RunISSO (activitymonitor.js:216)
    at Function.Run (activitymonitor.js:111)
    at activitymonitor.js:419
RunISSO @ activitymonitor.js:223
Run @ activitymonitor.js:111
(anonymous) @ activitymonitor.js:419
DevTools failed to load SourceMap: Could not load content for https://statica.akamai.odsp.cdn.office.net/bld/_layouts/15/16.0.21003.12008/ActivityMonitor.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
fp-min.js:1 GET https://ca57c2d5829b3d4fe1b39a6b900a2d00.fp.measure.office.com/apc/trans.gif?db8962c5355988fecd4c59e751f0ff78 net::ERR_CONNECTION_REFUSED

activitymonitor.js:132 Error: Error: Idle tracking cookie is missing.
    at IdleSessionActivityMonitor.GetCookieValue (activitymonitor.js:360)
    at IdleSessionActivityMonitor.InitializeSettingsFromCookie (activitymonitor.js:344)
    at LogIssoActivity (activitymonitor.js:125)
LogIssoActivity @ activitymonitor.js:132

**Comment by FormerlyJelly** [comment]
Hi Hkuu,

What do you mean by "Custom config list has been emptied?" Is there heavy security in this environment? Are the users who are unable to load the page using the same machine setup and group policy as your other users?

In reviewing the logging you have provided (thank you for that by the way) I see a lot of connection refused, unable to load content, and 404. This is generally due to security settings preventing the program from getting the assets it needs to function.

**Comment by FormerlyJelly** [comment]
Hello again Hkuu,

Please also review the security configuration of your Visitors group on the Comm site. It is likely that the people who are having issues have not been given access rights. If that is the case, generally "Everyone" is given Read rights through that group in most deployments.

**Comment by hkuu** [comment]
Hi, 

Emptying the sites custom config list was mentioned in some older cases when the problem was related to multilingual support and that was a wild card we tried when trying to fix this. 

Heavy security in a way I guess. I'll have to check the machine setups and group policies.  These three test users (two are seeing the error and for one everything is working fine) are all from the same country and using the same VPN and network. 

The other affected user is a site collection admin + site owner (same permissions as the user who has no issues with the webpart) and the other affected is a reader. 

Regarding that "Everyone" - won't that include also the external users? There's also the group everyone except externals which I prefer using instead of the everyone :)

**Comment by amazinjoey** [comment]
For my experience this usually happens due to having two learning pathways sites, and the parties not having access to both.

**Comment by FormerlyJelly** [comment]
Hi Hkuu,

Yes, "Everyone" would contain external users but I'm glad that you are catching my drift with security anyhow! "Everyone except external" should and could also be used, but everyone's tenants and security requirements are different as you know. Please let me know how things are going if you can.

**Comment by jellis-thrive** [comment]
No response after information delivery and further questions to provide aid
Closing issue due to non engagement
