### ISSUE TITLE
How is content updated automatically?

### ISSUE THREAD

**Issue by clayjam** [pnp/custom-learning-office-365#46]
My understanding is that the custom learning webpart will automatically pull information through to the correct sub-categories i.e. MS Team, Outlook.

Are playlists automatically added when new content is available ?

**Comment by clayjam** [comment]
Also, I don't seem to be able to delete a custom subcategory ?

I created a Windows 10 subcategory and when I edit the subcategory the delete icon is greyed out. It has no playlists.

**Comment by juliemturner** [comment]
Every 24 hours, if you never visit the CustomLearningAdmin page, or every time you visit the CustomLearningAdmin page a new manifest is pulled from the source.  If the manifest has new content in it you will see it.

The in ability to delete a sub category when there is no playlists in it appears to be a bug.
