### ISSUE TITLE
Custom Category not appearing to a set of users, although everyone has Read access to the Site 

### ISSUE THREAD

**Issue by IvanM365** [pnp/custom-learning-office-365#463]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

### To Reproduce

>Steps to reproduce the behavior

### Expected behavior

>A clear and concise description of what you expected to happen.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.

**Comment by juliemturner** [comment]
@IvanM365 -- In the future it would be very helpful if you could fill out the issue template, as that assists the team in being able to assist you.

If you mean a custom sub-category is not showing up... there are a few reasons why this could happen.
- There are no playlists in the subcategory
- You are using multilingual features (aka have multilingual feature turned on in SharePoint with >1 language enabled) and you have a playlist in your custom sub-category but you didn't create the translation for one or more of the other languages you support.  For those languages this sub-category will not be shown as you have no playlists in it in that language.

If you could provide some more details and maybe even some screen shots (even if redacted) that would help us assist more.

**Comment by karuanag** [comment]
HI @IvanM365 - I am closing this issue for now.  Please reopen an issue using our template if you continue to encounter difficulty.  We are happy to help.
