### ISSUE TITLE
[QUESTION] - Installing the app on SiteCollection App Catalog

### ISSUE THREAD

**Issue by sairao77** [pnp/custom-learning-office-365#465]
### What is the context of your question

- [X ] Installation
- [ ] Learning Pathways Content
- [ ] SharePoint Success Content
- [ ] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### What is your question
In the future will the manual installation or automatic provisioning support SiteCollection App catalog?

https://docs.microsoft.com/en-us/sharepoint/dev/general-development/site-collection-app-catalog

this will help with restricting web parts and app installation to only a specific site collection, I am assuming currently the app can't be restricted to a specific site collection.

>Provide related screen-shots to help us understand your question

**Comment by FormerlyJelly** [comment]
Hello sairao77,

I will work to get an answer for this and update you as soon as more information is available

**Comment by sairao77** [comment]
@juliemturner and @FormerlyJelly - thank you!

@juliemturner  - Thank you for the info! it is helpful.
