### ISSUE TITLE
Chapters are hard to identify

### ISSUE THREAD

**Issue by clayjam** [pnp/custom-learning-office-365#47]
Many users are not aware that other chapters exist in playlists. The only idetifier is a small triangle located top right of the page.

Make this more prominent - maybe include a table of contents for each playlist at the top of each chapter.

**Comment by juliemturner** [comment]
There is a table of contents for each playlist, click the burger icon to display it.  This also allows you to navigate to specific assets in the playlist.  

More design changes can be forthcoming when the content size issue (#37) is corrected.

**Comment by clayjam** [comment]
Thanks Julie, we found it. It would great if this is more contextual as it only shows the TOC when at the chapter level.

**Comment by juliemturner** [comment]
I’m sorry I don’t under what you means. Each playlist has a TOC under that burger menu. It’s always available when you’re in the playlist.  I’m not sure I understand what you mean when you say chapter.
