### ISSUE TITLE
When creating playlists, how do you know which videos are for the learning levels?

### ISSUE THREAD

**Issue by HayleySoftcat** [pnp/custom-learning-office-365#472]
Hi all, 

I am working with a customer to setup learning pathways and have stumbled across an issue:

When Adding Content (Different Audience & Learning Levels : End User or Admin…, Intermediate, Advanced, etc… )
https://docs.microsoft.com/en-us/office365/customlearning/custom_addassets
Once its created Subcategories & Playlists… how do you differentiate the Level of “Assets” ? As it appears all videos come up and you have to add the videos in, come out of it and go in to view it. Then click each category and see what levels they are. 
Is there an easier way to do this? 
                ( See screenshot below )
![playlist assett](https://user-images.githubusercontent.com/80051972/109980734-1ae6d080-7cf8-11eb-9da6-d50e81782f47.jpg)

Also when adding our own Training content…
Does anyone have any guidance on how this is done, where does the content need to reside, Best practices, etc…

Thank you!

**Comment by TimlinJake** [comment]
We are currently reviewing the behavior and we will get back to you with our findings

**Comment by eemancini** [comment]
I recommend saving training content on the sites where the content creator has access to edit and update. One of the big benefits of Learning Pathways is centralizing the content that is decentralized to give content owners direct access. The Category, Level, and Audience are all related to the playlist only. You cannot relate this information to each asset in the playlist.

**Comment by karuanag** [comment]
Emily is correct.  The content currently does not relate to the levels, only the playlists.  Customizing the playlists with your own design that works for your users is the flexibility M365LP offers.  Most content that comes from our web experience at support.microsoft.com is not deeply advanced content.  From my history training I would not say any content there is beyond level 200 at this time.

**Comment by jellis-thrive** [comment]
User information was delivered
No further questions from submitter
Closing ticket - if new information is requested, this can always be done in a fresh issue
