### ISSUE TITLE
-SiteAdminOnly Switch fails

### ISSUE THREAD

**Issue by Samatusen** [pnp/custom-learning-office-365#473]
Have confirmed that the user has site owner permissions but still getting the below error. 

Get-PnPApp : {"odata.error":{"code":"-2147024891,
System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to
perform this action or access this resource."}}}
ServerErrorTraceCorrelationId: ab27b19f-e056-b000-d94d-50e083e211ea
At C:\users\chris\desktop\M365lpConfiguration.ps1:107 char:10
+   $id = (Get-PnPApp | Where-Object -Property title -Like -Value "Micr ...
+          ~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPApp], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Apps.GetApp
WARNING: Could not find "Microsoft 365 learning pathways" app. Please install in it your app catalog and run this
script again.

I did notice that the CustomConfig, CustomPlaylist, and CustomAsset list files were not created and there is no CustomLearningAdmin.aspx page that was created after adding the app to the Communication Site. Deployed 4.1.4.0 version of the app.

**Comment by Samatusen** [comment]
Sorry copy and paste fail. 

Get-PnPApp : {"odata.error":{"code":"-2147024891,
System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to
perform this action or access this resource."}}}
ServerErrorTraceCorrelationId: ab27b19f-e056-b000-d94d-50e083e211ea
At C:\users\chris\desktop\M365lpConfiguration.ps1:107 char:10
+   $id = (Get-PnPApp | Where-Object -Property title -Like -Value "Micr ...
+          ~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPApp], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Apps.GetApp
WARNING: Could not find "Microsoft 365 learning pathways" app. Please install in it your app catalog and run this
script again.

**Comment by Samatusen** [comment]
Deleted the original Site and created a new communication site. Added the app and tried to run the powershell again. Still provides the same error. Attached image that the user is site admin and that the app is installed in the site.

![AppInstalled](https://user-images.githubusercontent.com/49350674/110067805-ae88c300-7d31-11eb-9b07-909a5a8e2330.jpg)
![SiteAdmin](https://user-images.githubusercontent.com/49350674/110067807-af215980-7d31-11eb-86e8-37e207a365c3.jpg)

**Comment by Samatusen** [comment]
![AppCatalogAdminOnly](https://user-images.githubusercontent.com/49350674/110068147-4d152400-7d32-11eb-8d9b-ba6aeacb9d3a.jpg)

**Comment by juliemturner** [comment]
Ok, well the issue I think you're running into is that it's trying to add the app from the tenant app catalog to the site and you don't have permissions to the tenant app catalog to do that... based on what you shared you don't actually need it to do that.

In the [M365lpConfiguration.ps1](https://github.com/pnp/custom-learning-office-365/blob/main/installation/M365lpConfiguration.ps1) script, if you comment out lines 107-116
these:
```
$id = (Get-PnPApp | Where-Object -Property title -Like -Value "Microsoft 365 learning pathways").id 
  if ($id -ne $null) { 
    # Found the app in the tenant app catalog
    # Install it to the site collection if it's not already there
    Install-PnPApp -Identity $id -ErrorAction SilentlyContinue 
  }
  else { 
    Write-Warning "Could not find `"Microsoft 365 learning pathways`" app. Please install in it your app catalog and run this script again."
    break
  }
```
And then run it again with the `-SiteAdminOnly` switch I think it'll probably work for you.

**Comment by karuanag** [comment]
Thanks @juliemturner - Following up here with @Samatusen - Did this guidance resolve your issue?

**Comment by Samatusen** [comment]
I ended up deleting it all out and then used the web deployment tool vs
trying to go this manual route.

**Comment by jellis-thrive** [comment]
User advised they deployed with a different procedure to manage the issue
Closing issue
