### ISSUE TITLE
External URLs for Custom Playlist not loading 

### ISSUE THREAD

**Issue by vsams** [pnp/custom-learning-office-365#474]
Admin>>Custom Playlist >> Add Asset >> Add URL >> Publish>> 

User Open Playlist >>Page Not Loading

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Creating custom playlist. Adding external URL (non support.microsoft.com) as a playlist asset.  User view page is not loading.
Error message - "xxx.com" refused to connect
Recreated error in 
Microsoft Edge
Google Chrome
Also tried on 3 different tenants. 

### To Reproduce
>Steps to reproduce the behavior
Admin -- Create a custom playlist  -- add assets --- add any external URL link

User -- go to custom playlist --visit asset -- **error** 'xxx.com refused to connect

### Expected behavior

>A clear and concise description of what you expected to happen.
User -- go to custom playlist -- page is loaded in window
![LP GitHub error](https://user-images.githubusercontent.com/52332155/110703763-c640cb00-81b9-11eb-84a8-ae0f9f629a4b.png)

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>4.1.4

### Additional context

>Add any other context about the problem here.

**Comment by juliemturner** [comment]
You cannot add external urls as a playlist asset unless that external url supports being iFramed, YouTube videos do now. So you need to create a SharePoint page and embed the YouTube video on it and that will become the asset.

**Comment by LisaJo48** [comment]
@juliemturner I am experiencing this even for webpages for Microsoft documentation . Seems like that should not be the case, to me. 
![image](https://user-images.githubusercontent.com/46016140/110827886-7e2ab280-8264-11eb-9b25-80fad24f5684.png)

**Comment by juliemturner** [comment]
Most docs.microsoft.com content cannot be iFramed either as the platform doesn't allow for it. 
There are some exceptions and if you want to you can try using it by appending the following query string parameter to the url, but if that doesn't fix it, you are trying to use one of the pages that is not supported.

`?context=context%2Fchromeless&linktarget=true`

It is on the backlog to fix this but it's out of the control of the team working on learning pathways, so I cannot give you any timeline on if/when it will be fixed.

**Comment by LisaJo48** [comment]
Thank you @juliemturner . I thought I was doing something wrong! The string didn't help in my case so, to work around this (if any can benefit), I created a page for each page of content I wanted to view in Learning Pathways and used the Link webpart on it. Then added the dedicated page I'd created to the Asset list. Not the best but at least it allowed me to include those pages in my LP content.

**Comment by jnewgard-thrive** [comment]
Workaround accepted.
