### ISSUE TITLE
Integration with Microsoft Teams  - blank page

### ISSUE THREAD

**Issue by RSebastian-Signet** [pnp/custom-learning-office-365#477]
Hi, we could use some help!

On September 23rd, a user commented the following - "We integrated the Learning Pathways app in Teams. It's working properly in the web app from teams, but not in the local windows app of teams. In the local apps of Teams we're getting a blank screen in the app. Any Idea how to resolve this?"

We are seeing the same error, and cannot resolve it.  We can see Learning Pathways on our mobile devices and if we navigate to Sharepoint directly, but not within our Teams environment.  There, we get a blank page.  We were able to see it on Friday just fine, but now our entire org gets a blank.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/80765569/111317657-58b9f200-8632-11eb-85eb-d3cc82ebd095.png)

Our Admin also saw this error, maybe it is part of the issue?
![image](https://user-images.githubusercontent.com/80765569/111317847-84d57300-8632-11eb-9131-ecf1145275b2.png)

This is a brand new Pathways deployment. Thank you for any assistance!!
Russell

**Comment by RSebastian-Signet** [comment]
Note:  The error code may or may not be related.  It is simply an observation we had during the install.

**Comment by karuanag** [comment]
Normally this occurs when you are not using the Teams App template for M365 Learning Pathways.  We've updated the authentication model so this blank screen experience does not happen.  You can download it here at https://aka.ms/M365LPTeamsApp  and then edit it to include other SharePoint tabs or experiences from that tenant.  Give that a try and let us know if you still have any difficulty.

**Comment by karuanag** [comment]
Please let us know if using the supported app template resolves the problem. Closing this issue for now.  Please reopen or open a new one if the problem persists with our template.
