### ISSUE TITLE
[ENHANCEMENT] Add Polish to the supported languages

### ISSUE THREAD

**Issue by manfaria** [pnp/custom-learning-office-365#479]
Do you have any roadmap for make Polish available for the supported languages?
https://docs.microsoft.com/en-us/office365/customlearning/custom_overview_ml

**Comment by jellis-thrive** [comment]
Hi manfaria

This is not one that I am able to answer, but I will ensure the request is reviewed by the appropriate resources who may be able to provide commentary. Thank you for the feedback!

**Comment by karuanag** [comment]
Hello @manfaria We have not put a date on any additional languages at this time.  Our next backlog review will be in April.  Stay tuned for announcements of this type on our blog at https://aka.ms/DriveAdoption
