### ISSUE TITLE
[QUESTION] Sharing M365 LP site with other domains

### ISSUE THREAD

**Issue by sbayli** [pnp/custom-learning-office-365#481]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [ ] Installation
- [X ] Learning Pathways Content
- [ ] SharePoint Success Content
- [ ] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### What is your question
I am trying to share the M365 LP SharePoint site with our other domains (which are other tenants in O365), however, they are getting a restricted page where it asks them to request access. I have adjusted the settings on the SharePoint admin center to allow the specific domains access, however, it is still not letting them in. Can M365 LP sites be shared with other domains?
>Provide related screen-shots to help us understand your question

**Comment by jnewgard-thrive** [comment]
Hi sbayli,

Assuming External Sharing is properly configured and the users in the other Tenants are able to access the Site, they will also need Read access to the Tenant App Catalog as outlined here:

https://techcommunity.microsoft.com/t5/sharepoint-developer/site-collection-app-catalog-external-users/m-p/153777/highlight/true#M4280

**Comment by eemancini** [comment]
Learning Pathways cannot span tenants so it sounds like you are trying to add external access to the Learning Pathways site on one tenant, is that correct? Adding the domains in SharePoint admin will allow you to add the individuals to the Learning Pathways site. It sounds like you might not have taken the next step to add the specific users to the Learning Pathways site for visitor access.

**Comment by sbayli** [comment]
Hi all,
Thank you for the responses! In the Sharepoint admin center, I have set our sharing policies to be open fully, and I have whitelisted the domains in question on the site's settings on the SharePoint admin center. 

When I created the M365 LP SharePoint site, I was getting access requests even from teammates that shared my domain. Luckily, we have a security group for all teammates that I was able to add to the SP site. However, I need to allow anyone with companyB.com and companyC.com accounts to be able to access our M365 LP site.

**Comment by eemancini** [comment]
Thanks for the clarification, sbayli. You will need to individually add all of those external users to the Learning Pathways site as well :)

**Comment by jnewgard-thrive** [comment]
Hi sbayli,

From your description, you have Enabled sharing with the External Domains but have not invited the External Users/Guests. Any user who does not exist in your Tenant will need an invitation.

You can invite them by sharing the Site with them:
https://support.microsoft.com/en-us/office/share-a-site-958771a8-d041-4eb8-b51c-afea2eae3658

Or invite them via Azure AD and then assign them permissions on the Site:
https://docs.microsoft.com/en-us/azure/active-directory/external-identities/add-users-administrator

They will also still require Read access on the Tenant App Catalog:
https://techcommunity.microsoft.com/t5/sharepoint-developer/site-collection-app-catalog-external-users/m-p/153777/highlight/true#M4280

**Comment by sbayli** [comment]
All,
Thank you for the comments. Looks like I will need to create a M365 LP site for each tenant then as adding thousands to the site is not very feasible.

Thank you again for the collaboration!
