### ISSUE TITLE
Is there a way that we can integrate this webpart with MS Power Virtual Agent?

### ISSUE THREAD

**Issue by Abhishek-Bharadwaj-24** [pnp/custom-learning-office-365#488]
We are developing a chatbot and we need to integrate the chatbot with the MS learning Pathway webpart. SO that the chat bot should give away the links to articles in the webpart with respect to the topic that is asked in the bot.

**Comment by juliemturner** [comment]
You can do that... You need to reference a Sharepoint page that has the web part on it... you could use the CustomLearningViewer.aspx page in the learning pathways main site, but you don't have to... and then you can formulate a query string that links directly to the content you want to show.  If you use the link aspect of the web part you can figure out what the links are.

**Comment by Abhishek-Bharadwaj-24** [comment]
Hello Julie,

Thanks for the reply!
Is there any static list where all these links are stored, so that I can call them through API. I am particularly looking to integrate Virtual Agent with this learning webpart in such a way that, if anyone searches for 'Check in Check out in SharePoint' the VA should fetch the page related to the topic not just the tab of the sharepoint in the webpart.
Waiting for you response!

From: Julie Turner ***@***.***>
Sent: 31 March 2021 20:16
To: pnp/custom-learning-office-365 ***@***.***>
Cc: Abhishek Bharadwaj ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [pnp/custom-learning-office-365] Is there a way that we can integrate this webpart with MS Power Virtual Agent? (#488)


Caution: EXT Email

You can do that... You need to reference a Sharepoint page that has the web part on it... you could use the CustomLearningViewer.aspx page in the learning pathways main site, but you don't have to... and then you can formulate a query string that links directly to the content you want to show. If you use the link aspect of the web part you can figure out what the links are.

-

**Comment by juliemturner** [comment]
I think you're somewhat confused about how learning pathways works.  The web part is iFraming content from https://support.office.com (SOC), so if all you want is a list of pages that learning pathways uses in its playlists so that you can surface them some other way then certainly you can just browse SOC website or take what links are useful from the [assets.json](https://github.com/pnp/custom-learning-office-365/blob/main/docs/learningpathways/v4/en-us/assets.json) files in the docs directory.

**Comment by Abhishek-Bharadwaj-24** [comment]
Hello Julie,

Sorry to re-open this topic, may I know how the content from SOC are fetched, is it through API access? If So, can we fetch that from our end through Power Automate, so that we could establish some sort of connection between our power virtual agent and the content from SOC site ( ultimately this is what iFramed in Learning Pathway).

Please let me know if you can help me with this query. Thanks and looking forward for your response.


Thanks & Regards
Abhishek Bharadwaj
SharePoint Managed Services Team
NXP Semiconductors
Bangalore, India
Email: ***@***.******@***.***>
Mobile: +91 9591355965
"For training/information about SharePoint & Office365 at NXP please visit the SharePoint Community Site<https://nxp1.sharepoint.com/sites/CollaborationServices>"
***@***.***D7594F.D1893E80]



From: Julie Turner ***@***.***>
Sent: 07 April 2021 20:17
To: pnp/custom-learning-office-365 ***@***.***>
Cc: Abhishek Bharadwaj ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [pnp/custom-learning-office-365] Is there a way that we can integrate this webpart with MS Power Virtual Agent? (#488)


Caution: EXT Email

I think you're somewhat confused about how learning pathways works. The web part is iFraming content from https://support.office.com<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.office.com%2F&data=04%7C01%7Cabhishek.bharadwaj%40nxp.com%7Cc2579a63922a416daa6d08d8f9d40abd%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637534036420108022%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uRXTSilqNDDzbTak2obUnhHebRffUYiQIJrsofteGSc%3D&reserved=0> (SOC), so if all you want is a list of pages that learning pathways uses in its playlists so that you can surface them some other way then certainly you can just browse SOC website or take what links are useful from the assets.json<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpnp%2Fcustom-learning-office-365%2Fblob%2Fmain%2Fdocs%2Flearningpathways%2Fv4%2Fen-us%2Fassets.json&data=04%7C01%7Cabhishek.bharadwaj%40nxp.com%7Cc2579a63922a416daa6d08d8f9d40abd%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C637534036420118018%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YqzEwCzmZshq%2Bx4IkzFG6gQyfiiSYbPy9%2FDUpkU4104%3D&reserved=0> files in the docs directory.

-

**Comment by juliemturner** [comment]
First, please be careful responding to issues via email as it puts all your PII into the GitHub issue, I've edited your entry to remove that information... 

To answer your question the iFrame source is set to the url of the asset on SOC. As I stated previously this is from the assets.json file in the docs folder, there is no API.
