### ISSUE TITLE
[QUESTION] Language selected in the dropdown won't match content language

### ISSUE THREAD

**Issue by jaricharte** [pnp/custom-learning-office-365#489]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [ ] Installation
- [x] Learning Pathways Content
- [ ] SharePoint Success Content
- [ ] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### What is your question

>Provide related screen-shots to help us understand your question

Not sure if this is a bug or a feature but I just deployed the LP site and immediately noticed there's a language selector on the top-right corner of the screen. I wanted to check how good the translations were but I noticed something odd. When I try switching from the default language (English) to Italian, for instance, only the titles will get translated but the content itself will be in English. I'm attaching a screenshot that shows the "issue".
![LP_language](https://user-images.githubusercontent.com/10515032/113571503-c85e4400-9616-11eb-967e-021c5d91cc8c.png)

Is this expected behavior? I know LP picks the language from the user profile but having a selector that doesn't work as expected could rise questions.

Thank you very much for your help!

**Comment by jnewgard-thrive** [comment]
Hi @jaricharte,

Yes, this is expected. The language dropdown is a component of the SharePoint Translation Feature (used but not managed by the Learning Pathways solution) and does not control the display language of Learning Pathways. More on Learning Pathways and SharePoint Translation can be found below.

[Learning Pathways Multilingual](https://docs.microsoft.com/en-us/office365/customlearning/custom_overview_ml#what-you-should-know-before-getting-started)

[SharePoint Multilingual](https://support.microsoft.com/en-us/office/create-multilingual-communication-sites-pages-and-news-2bb7d610-5453-41c6-a0e8-6f40b3ed750c?ui=en-us&rs=en-us&ad=us)
