### ISSUE TITLE
subcategories 

### ISSUE THREAD

**Issue by davepae** [pnp/custom-learning-office-365#49]
Repro steps:

1. Using Chrome on Windows 10. Visit CustomLearningAdmin.aspx, add a new Sub Category: Foo Cat
2. Click Save
3. Add new Playlist: Foo List
4. Add new Asset to Foo List: Foo Asset1. Pick adding new site page, publish.
5. Save Asset
6. Close Playlist
7. Refresh Office 365 Training page (Get-started-with-Office-365.aspx). Ctrl+F5.

Foo Cat does not appear on the Get-stared..aspx page. Please advise.

**Comment by juliemturner** [comment]
@davepae ... can you confirm that you're using at least version 2.0.11 of the webpart.  I just released 2.0.12.  If not can you update the sppkg file and see if the problem is resolved?

**Comment by juliemturner** [comment]
Assuming this is closed since the bug described was fixed in an earlier version.
