### ISSUE TITLE
What is the difference from version 4.1.3 and 4.2?

### ISSUE THREAD

**Issue by FadyJaradat** [pnp/custom-learning-office-365#497]
### What is the context of your question

- [ ] Learning Pathways Content

### What is your question

>What is the difference from version 4.1.3 and 4.2? and is there difference in content?

**Comment by jnewgard-thrive** [comment]
Hi @FadyJaradat 

Content Updates and Version Updates occur separately and details for each can be viewed at the below locations.

[Content Updates](https://docs.microsoft.com/en-us/office365/customlearning/custom_contentupdates)
[Version Updates](https://github.com/pnp/custom-learning-office-365/blob/main/CHANGELOG.md)

**Comment by jellis-thrive** [comment]
Closing as no response has been received for 30 days past the given information
