### ISSUE TITLE
 Add content pack returned Something went wrong

### ISSUE THREAD

**Issue by maiomardesouki** [pnp/custom-learning-office-365#498]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

We are getting error in Learning pathway app, and advised to add content pack to fix, when trying to add content pack, we got "Error, something went wrong, the tenant is not allowing this solution" as  per attached screen shot.

### To Reproduce

When adding Content Pack. by clicking the SharePoint Success Site.

### Expected behavior

Expecting the error we see everyday in App to be fixed or solved.

### Screenshots

Added, Please find attached below.

### Learning Pathways version number

4.1.3.0

### Additional context

>Add any other context about the problem here.
![Jamal](https://user-images.githubusercontent.com/8101820/115395514-40666580-a1e4-11eb-8c9d-f0c6f401c292.png)

**Comment by jnewgard-thrive** [comment]
Hi @maiomardesouki 

Could I have you confirm the steps you used to get to the URL in your screenshot?
_https://spprovisioningapp-test.azurewebsites.net_

Additionally, please attempt to provision using the link below. Please note, you will still need to complete Steps 8 and 9 in the provisioning outline: [Provisioning Steps](https://docs.microsoft.com/en-us/sharepoint/provision-sss#provision-the-sharepoint-success-site-1)

**Comment by maiomardesouki** [comment]
Yes this steps are done. I need someone to login with me and the customer to support in solving this issue. can someone start communicating via mails to me on maoma@microsoft.com so we can proceed faster.

**Comment by jnewgard-thrive** [comment]
GitHub is the official path to receive support for Learning Pathways; we would be glad to help with the information that you provide here.

You have not confirmed how you reached this URL for provisioning: https://spprovisioningapp-test.azurewebsites.net

Could you provide a screenshot of the behavior when you try provisioning from this location: https://lookbook.microsoft.com/details/0b860749-56a0-4c4c-992c-536d56d9accf

![image](https://user-images.githubusercontent.com/80363676/117028435-f341c380-acba-11eb-9204-357e8353f981.png)

If this location still fails and you have validated the pre-requisites, please repost your issue to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues) as we are unable to assist here with Provisioning Service issues.

**Comment by juliemturner** [comment]
It looks like there was a content bug that was pointing users to the wrong url for provisioning the SharePoint Success Site.  That has been corrected and so adding the content pack should now work. Please let us know if your problem has not been solved by this correction. The link should take you to: https://lookbook.microsoft.com/details/0b860749-56a0-4c4c-992c-536d56d9accf

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket.
