### ISSUE TITLE
Search box report a lot of CustomConfig and not asset 

### ISSUE THREAD

**Issue by wackou72** [pnp/custom-learning-office-365#499]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

When searching content, the result returned is a lot of CustomConfig and not pages of actual assets

### To Reproduce

1. Click on the search "Search this site"
2. type a keyword
3. this will display a lot of CustomConfig instead of the content.

### Expected behavior

The result should return the assets

### Screenshots

![2021-04-22 11_17_01-Window](https://user-images.githubusercontent.com/21340779/115689488-6adb2e80-a35c-11eb-8d79-469efaa3cf18.png)

### Learning Pathways version number

4.1.4.0

### Additional context

Learning Pathway was deployed on 23/03/2021

**Comment by jnewgard-thrive** [comment]
Hi @wackou72 

This is expected as you are using **SharePoint Search** in your screenshot and the Learning Pathways Web Part loads the majority of its pre-packaged content from other locations such as the [Office Support Site](https://support.microsoft.com/). The content stored locally are the configuration lists you mentioned and the Site Pages from the navigation menu and hero web parts. Additionally, if you have created your own custom content and stored it on the site, it should also be searchable.

[SharePoint Search Overview](https://docs.microsoft.com/en-us/sharepoint/overview-of-search)

The Learning Pathways Web Part does have its own search function which can be accessed via the magnifying glass icon in the upper left corner of the web part.

![image](https://user-images.githubusercontent.com/80363676/115731669-8df9e400-a344-11eb-8ffd-8441c6d5b3ff.png)

**Comment by wackou72** [comment]
Hello,
Thanks for your help.
I understand the technical part, but its not very user friendly.
Regards

**Comment by juliemturner** [comment]
Unfortunately, we have absolutely no way to effect search in the way you want as the content is not part of your tenant. You can however configure the custom lists to not be shown in search results if you feel that would be beneficial in your environment.
Option 2 in this [article](https://sharepointmaven.com/3-ways-prevent-documents-appearing-search-results-sharepoint/) explains how to do so.

**Comment by jellis-thrive** [comment]
User provided feedback on the information given
No further actions at this time
Close ticket
