### ISSUE TITLE
Learning Pathways and Viva Learning

### ISSUE THREAD

**Issue by Kikaider** [pnp/custom-learning-office-365#501]
### What is the context of your question

- [ ] Installation
- [X] Learning Pathways Content
- [ ] SharePoint Success Content
- [ ] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### What is your question

What is the relationship between Microsoft Learning Pathways and Microsoft Viva Learning besides licensing? For Viva Learning customers, will Learning Pathways content (i.e. the content provided by Microsoft on O365) be available in Viva Learning?

**Comment by mhollinshead** [comment]
Great question Kikaider. We frame this in a good, better, best narrative. A few things for you to consider: 

- The default learning content that you see in Learning Pathways will also surface in Viva Learning. So if you just need that content to be successful, then Viva Learning is the recommended solution for you to leverage. 
- That being said, if you have a need for content customization (modifying existing learning content, adding your own, branding it for your company) then Learning Pathways is the recommended option to do so. Especially if you are working with one of our wonderful Adoption Partners who have built customized learning services, based on Learning Pathways.
- The key to all of this - is that we (Microsoft) are working on integrating Learning Pathways with Viva Learning. So if you've made an investment in customized content - then that will show up in Viva Learnings. Bringing the good, better, best narrative back around... 
 
So the vision here is that these experiences are complimentary and build on one another. Hope that helps


-

**Comment by Kikaider** [comment]
That is helpful. Thank you!

About 40% of my customer's content is custom. Nothing fancy, just in-house stuff, but they do want to leverage it going forward.

My customer uses Learning Pathways not just for O365, but for business process training, NEO, training on custom apps, and complex topics like MFA setup.
