### ISSUE TITLE
 Menu missing from CustomLearning Admin page

### ISSUE THREAD

**Issue by MCMatStoryals** [pnp/custom-learning-office-365#508]
## Describe the bug

Parts of the CustomLearning Admin portal are missing.

### To Reproduce

Browsing through the CustomLearning Admin page.

### Expected behavior

The left menu panel is missing from the CustomLearning Admin page.

### Screenshots

![image](https://user-images.githubusercontent.com/48782895/117290516-f2598f00-ae7e-11eb-8b44-55ffc481f88b.png)

### Learning Pathways version number

v3.0.4 - I know this is outdated, but I haven't seen this issue before on our other tenants. Would updating fix the problem?

### Additional context

Browser console: 
[M365 LP SOSE console.log](https://github.com/pnp/custom-learning-office-365/files/6434015/M365.LP.SOSE.console.log)

**Comment by MCMatStoryals** [comment]
Hi @jnewgard-thrive 

I have already tried deleting the CustomConfig list, but that didn't change anything in the Admin web part. I will try to see if upgrading would fix the issue.

Thanks!

**Comment by juliemturner** [comment]
Your other option is to view the browser's console to see if any errors are being shown related to learning pathways. We will phase out support for content updates with v3 soon though so I do encourage you to update to v4.

**Comment by MCMatStoryals** [comment]
Hi @juliemturner and @jnewgard-thrive, the webpart is now updated to v4.2, but the issue still persists

Here's the browser console:

[M365 LP SOSE console 2.log](https://github.com/pnp/custom-learning-office-365/files/6488740/M365.LP.SOSE.console.2.log)

**Comment by juliemturner** [comment]
I looked over the logs, but nothing really stood out to me... 
Diagnostically you might try adding a new custom content pack pointing at the source learning pathways library just to validate that it's not any configuration parameter. In other words, set the Base URL property on the custom content pack to: https://pnp.github.io/custom-learning-office-365/learningpathways/

**Comment by MCMatStoryals** [comment]
The issue still persists unfortunately :(
![image](https://user-images.githubusercontent.com/48782895/118398441-b5a14b00-b669-11eb-974d-02d2f312aa26.png)
[M365 LP SOSE console 3.log](https://github.com/pnp/custom-learning-office-365/files/6489271/M365.LP.SOSE.console.3.log)

**Comment by juliemturner** [comment]
Ok. well, given there are not errors in the logs I can't see any obvious reason why that content isn't visible, but it would suggest it's there but not displayed.  
-Does the viewer web part work correctly?
-I am only looking at a partial screen shot is it possible that the content is pushed down and there are scroll bars visible?
-Do you have other SPFx customizations installed/enabled in the tenant/site collection?

-If the answers are Yes, No, No then the only solution I would have would be to inspect the html/css and see if the control that holds the content on that left side is hidden either with display = none in css and if so try to determine why, or alternately if the content is not even in the DOM.

**Comment by MCMatStoryals** [comment]
The answer is Yes, No, No. I did inspect the html/css and there are some discrepancies compared to another tenant with the content visible. But I'm not sure how to solve this issue. 
The main purpose of this would be to hide a few topics that the end-users do not use. Is there a way to hide them by editing the CustomConfig list?

**Comment by juliemturner** [comment]
>The main purpose of this would be to hide a few topics that the end-users do not use. Is there a way to hide them by editing the CustomConfig list?

Yes, but that really has nothing to do with your problem. You definitely have something else loading on that page (maybe a tenant wide ext or something else) that is causing that menu not to display... the fact that it isn't is at this point almost definitely an HTML/CSS issue specific to your tenant... if we could replicate the issue I could certainly help figure it out...

Based on your previous comment I'm guessing you're only seeing this in this tenant? Is this a production tenant? Is this M365LP instance in production?

**Comment by MCMatStoryals** [comment]
This is one of our customer's tenant where M365LP is deployed. None of our other customers are facing this issue and neither are our demo tenants. You're right this can be a tenant specific issue.

**Comment by MCMatStoryals** [comment]
Hi @juliemturner and @jnewgard-thrive I have finally found a fix to the issue, there was a custom SharePoint theme that was interfering with the navigation, removing it fixed the issue. I thank you both for your help 😊.
