### ISSUE TITLE
Empty training asset content 

### ISSUE THREAD

**Issue by sscarcella** [pnp/custom-learning-office-365#509]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

In Learning Pathways OneDrive > Intro to OneDrive (work or school) the Asset: Set up your iPhone or iPad is empty.  We need to be able to hide assets that do not work or apply.

### To Reproduce

>click OneDrive > Intro to OneDrive (work or school) > Set up your iPhone or iPad

### Expected behavior

>there should be content here or allow us to hide the asset

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version

>4.2.0.0

### Additional context

>Add any other context about the problem here.

**Comment by jellis-thrive** [comment]
Hi ssscarcella,

We will review the content and see if this is something reproducible. Once done, we will circle back with you.

**Comment by jellis-thrive** [comment]
Hello ssscarcella,

Assets cannot be hidden - only a playlist or a category/subcategory may be hidden. If you want to customize a particular playlist, a good path would be to copy it and remove the unwanted asset, then hide the original playlist.

**Comment by jellis-thrive** [comment]
Hello @sscarcella  - if there is any other way we can help, please let us know. This is a current limitation of the platform itself and the Copy path is the best avenue available.
