### ISSUE TITLE
How to update the metadata.json file please?

### ISSUE THREAD

**Issue by Badajoz95** [pnp/custom-learning-office-365#51]
My users do not like "End User" which I can see is in "metadata.json". Is it possible to update this please? I've had a pretty good look but without the actual source code (is that available?) I can't reverse engineer where it might be.

**Comment by juliemturner** [comment]
The metadata.json file is not available for editing and there is no plans to have it be available for editing.  The point of the solution is that the manifest will be updated regularly by Microsoft to keep the content displayed in the solution fresh. The source code for the webpart, although not currently available will be made so in the future, although that will in general not help you with this particular request, although I suppose you could create a custom version of it with the purpose of overriding that term.  I'm sorry your users don't like the term "End User", do you have some term you think is more appropriate for content directed at the users of the tools?

**Comment by Badajoz95** [comment]
Thanks - appreciate your reply.

**Comment by karuanag** [comment]
Hello @Badajoz95 would the term "employee" work for your scenario?
