### ISSUE TITLE
The app version is not updating on the site

### ISSUE THREAD

**Issue by ashmsport** [pnp/custom-learning-office-365#510]
>Hi, Just updated the package version 4.2 by logging in as tenant SP Admin but when I'm logged in as the Learning pathway site collection admin I do not see the latest version. It still shows 3.0.3.0

### What is the context of your question

- [ ] Installation
- [ ] Learning Pathways Content
- [ ] SharePoint Success Content
- [x] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### What is your question

>
This is what I see when I login as a tenant SP admin:
![image](https://user-images.githubusercontent.com/33230123/117500281-6319ad80-af4a-11eb-857b-7aef60acb38d.png)

This is what I see when I log in as Site owner, Site collection admin
![image](https://user-images.githubusercontent.com/33230123/117499917-eab2ec80-af49-11eb-8ac5-7455222e98fc.png)

**Comment by jellis-thrive** [comment]
Hello ashmsport,

The solution itself needs to be updated in the App Catalog for your tenant. More information about updating Learning Pathways is available here:

https://github.com/pnp/custom-learning-office-365#updating-the-solution

**Comment by ashmsport** [comment]
I'm able to reproduce this in a different (Developer) tenant as well.

**Comment by jellis-thrive** [comment]
Hi @ashmsport 

The green check mark on the left of the screenshot indicates that the solution is not checked in. The upgrade is not complete until this action occurs. Please review when you've a moment; its likely to be the same issue in the Dev environment.

**Comment by ashmsport** [comment]
_The green check mark on the left of the screenshot indicates that the solution is not checked in. The upgrade is not complete until this action occurs. Please review when you've a moment; its likely to be the same issue in the Dev environment._
-Jellis-thrive
