### ISSUE TITLE
 Multi-language Learning pathways only display content in English

### ISSUE THREAD

**Issue by Erithano** [pnp/custom-learning-office-365#511]
### To Reproduce
Deploy Learning Pathways in a demo tenant. Open "Get started with Microsoft Teams" (or any other basic course). Switch language to a non-English language. 

### Expected behavior
All content in the learning modules should show in chosen language.

### Screenshots
![image](https://user-images.githubusercontent.com/65014935/117829900-7478f780-b273-11eb-8882-fdef2d117103.png)

### Learning Pathways version number
4.1.4.0
![image](https://user-images.githubusercontent.com/65014935/117830459-f2d59980-b273-11eb-8a74-6dd5ad47fedc.png)

### Additional context

Same for any language other than English. Headings are translated content remains in English.
Large multi-national customer deploying to 20K users this month. Needs to work for them.

**Comment by thechrissou** [comment]
Same issue. Nothing else than English content available on my tenant.

**Comment by jellis-thrive** [comment]
Hello @Erithano   - is the content that you are trying to display in another language custom content, created by the organization,  or content deployed by default? What processed was used to install Learning Pathways? Do you have your browser profile set to a specific language? As much information as you could provide would be helpful for us to follow up.

**Comment by jellis-thrive** [comment]
Hello agian @Erithano , and @thechrissou 

Upon further review of your screenshot, you may be missing some key points on how Learning Pathways is intended to function with different languages. I am able to see that the menu item language that you are using is English; that is why the content is displaying in English.

The language displayed in the learning pathways web part will depend on user's personal language and region settings. Please review the documentation linked below.

https://docs.microsoft.com/en-us/office365/customlearning/custom_overview_ml

**Comment by jellis-thrive** [comment]
Hello @Erithano - did this info help to resolve your issue?

**Comment by Erithano** [comment]
@jellis-thrive - Thanks - I will review your suggested link!

Expected behavior however is to choose translation - pick a language - and thus get LP in that language. 
Like clicking a language option on a company home page. 
 
Many users are multi-language users. It seems very confusing to be able to pick a language if region settings then just block that action (browser or IP-address or OS region settings?)

**Comment by juliemturner** [comment]
If they remove all languages from the Delve profile and just use the language in the browser (i.e. switch their default language in the browser the language SharePoint shows will change with the browser basically real time.  If you have multilingual users who want that ability that is what they should do.

We are considering trying to write code to override the default behavior of SharePoint framework solutions which get the language based on what is called the MUI, which is a complicated cascading process based on what languages they have set in delve, what languages they have set in the browser and what the default language of the site collection is. The multilingual page selector has 0 impact unfortuantly on what language SharePoint Framework understands... that is where the disconnect is.

**Comment by Erithano** [comment]
Thanks @juliemturner now we understand! 🙏🙏🙏
