### ISSUE TITLE
[QUESTION] Is there a way to include the playlist content in Immersive Reading?

### ISSUE THREAD

**Issue by harmsze** [pnp/custom-learning-office-365#514]
We are trying to make our M365LP portal more accessible. The Immersive Reader on the SharePoint page, seems helpful, but that only includes the content that is added directly to the page. Not the playlists displayed in the M365LP web part. (see the screenshots)

Is there a way to include the playlist content in the Immersive reader? Or is it hopeless, because that content does not live inside our tenant and our SharePoint, but in a Microsoft website?
![ImmersiveReader-Page with button](https://user-images.githubusercontent.com/76995147/118633442-c8cf2a80-b7d1-11eb-92f3-060d17d48203.png)
![ImmersiveReader-ReaderView](https://user-images.githubusercontent.com/76995147/118633460-cd93de80-b7d1-11eb-8814-56a505e41d33.png)

**Comment by jellis-thrive** [comment]
hello @harmsze 

It sounds like the functionality you are looking for is likely not possible at this time. You are correct, the content that Learning Pathways displays, with few exceptions, is not present in your tenant. The Learning Path ways web part may be embedded in site collections other than the primary Communications site that is first setup however.

**Comment by harmsze** [comment]
Thank for your answer @jellis-thrive ! It's a pity it does not work, but I suppose we can't have everything, both content managed by Microsoft and content that can be searched and immersively read in our site... 
Yes, I have seen that we can add the M365LP web parts in other sites as well. But for now, we try to make it all work in the original Communications site :-)

**Comment by jellis-thrive** [comment]
You are welcome @harmsze - I will ensure this feedback is passed to the right people! Features and enhancements are always evolving. Thank you for your understanding.
