### ISSUE TITLE
Error Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance.

### ISSUE THREAD

**Issue by MasemolaTMB** [pnp/custom-learning-office-365#516]
Good day all, 
can you please assist, our learning pathways now just gives error:

Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.]
There were no modifications done.
<img width="625" alt="error" src="https://user-images.githubusercontent.com/57560781/118772604-3dfb3800-b884-11eb-9957-2bdb76c147dd.PNG">

![image](https://user-images.githubusercontent.com/57560781/118772299-e3fa7280-b883-11eb-94a0-566768f71cd9.png)

**Comment by jellis-thrive** [comment]
Hello @MasemolaTMB 

Can you please detail your installation process for us? 
Is this a new installation?
Is the tenant you have installed this in a standard Microsoft tenant?

**Comment by HiltonGiesenow** [comment]
I am seeing this as well, on a relatively new customer tenant, with LP installed a few days ago. Admins can see it fine, but end users are experiencing this. I haven't tested with a user yet, but so far have upgraded to latest LP version.

**Comment by jellis-thrive** [comment]
hi @HiltonGiesenow - please start your own ticket so we can help you directly there instead!

If you do so, please provide us with the information referenced below so we can efficiently help:
https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md

**Comment by dcashpeterson** [comment]
Closed due to inactivity
