### ISSUE TITLE
Adding Custom Technologies

### ISSUE THREAD

**Issue by clayjam** [pnp/custom-learning-office-365#52]
We are trying to add some extra products to be displayed in the web part. For example, Microsoft Project and Visio.

We can create new sub-categories under products and playlists for these items but they never show with the other products in the web part.

It looks like because they are not part of a Technology they don't show in the CL web part?

If we can't implement this at present can you please propose how we might show these items in the Learning Centre ?

**Comment by juliemturner** [comment]
Please verify, using the instructions in the [README](https://github.com/pnp/custom-learning-office-365/blob/master/README.md#updating-the-solution) - Updating the Solution section that you  have the most recent version of the web part.  It sounds like you're experiencing a bug that was fixed, unless i'm not understanding your issue, custom sub-categories and playlists do show up in the web part.
