### ISSUE TITLE
Primary navigation language changed when upgrading to 4.2 

### ISSUE THREAD

**Issue by robertcaretta** [pnp/custom-learning-office-365#520]
## Describe the bug
Performed a new installation which provisioning v 4.1.4.  After initial installation upgraded to v4.2.  The primary navigation switched to non-english even through the site was configured for english.

### To Reproduce
Using LookBook service performed a new installation which provisioning v4.1.4.  After initial installation then upgraded to v4.2.  

### Expected behavior
Navigation language should not change.

### Screenshots
![image](https://user-images.githubusercontent.com/1613085/119564047-ecfcaf80-bd6d-11eb-8a45-0518cb6dbb7b.png)

![image](https://user-images.githubusercontent.com/1613085/119566046-4cf45580-bd70-11eb-9622-ac96ee7e20e4.png)

### Learning Pathways version number
4.1.4.  Then 4.2

### Additional context
NA

**Comment by jellis-thrive** [comment]
Hi @robertcaretta - when you completed the installation and testing, was your own profile set to a language? Please review the info below, specifically the section on updating and language settings labeled "Set Language Settings"

https://docs.microsoft.com/en-us/office365/customlearning/custom_update

**Comment by robertcaretta** [comment]
I guess I'm not understanding why the navigation would display a different
language if my settings are set to English. This was an initial install in
a TEST tenant. I will set the language settings prior to upgrading in our
PROD tenant. Will set that to English only prior to upgrading.

Yes, my O365 profile had a Display Language assigned to English. This is
managed by the organization and can not be changed. Regional format is also
set to English (United States)

**Comment by juliemturner** [comment]
The languages you see in the menus are depending on a cascading set of settings... it's often referred to as the MUI. It starts with the languages that you have set up in your Delve profile, if you have none it'll default back to the settings you have in your browser, and if none, reverts to the default language of the site collection.  One of those places you have a language other than English, therefore that is your MUI and that is the language learning pathways will try and show the web part in.. if that language is not one we support we default back to English.
