### ISSUE TITLE
Issue with Microsoft 365 Learning Pathways After Update

### ISSUE THREAD

**Issue by SeanCatVH** [pnp/custom-learning-office-365#522]
## Describe the bug

**We updated the Microsoft 365 learning pathways app from version 4.1.4.0 to 4.2.0.0. Now we are unable to see some of the categories and playlists with the web part. Please contact us for assistance. Thanks.**

![365LearningIssue](https://user-images.githubusercontent.com/84815852/119684198-ee7bb580-be09-11eb-8907-bb855e8fda65.PNG)

>Steps to reproduce the behavior

### Learning Pathways version number

4.2.0

### Additional context

>Add any other context about the problem here.

**Comment by jellis-thrive** [comment]
Hello @SeanCatVH 

Could you please check the admin page within the Learning Pathways site? It is located within Site Pages. We want to ensure there is not an abandoned category at the top. Please post a screenshot when possible.

**Comment by SeanCatVH** [comment]
Thanks for your response.

The admin page looks good to me. It's just the 365 learning pathways web part that is not displaying correctly.



[cid:34a4fba4-70a6-42fe-adb0-430083d726cc]

Please let me know if you need further information.

Thanks for your time and assistance.
Sean
________________________________

Sean Cowherd
SharePoint Analyst
913.354.6492
This E-mail is covered by the Electronic Communications Privacy Act, 18 U.S.A. 2510-2521 and is legally privileged. This is confidential information and is intended only for the individual(s) or entity(ies) named above. If the reader of this message is not the intended recipient, please contact Sender immediately. You are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited.

**Comment by jellis-thrive** [comment]
Hello @SeanCatVH 

Could you be more specific when you say that it is not displaying correctly?

Are these out of the box categories / playlist assets, or custom?

Are you using more then one language?

**Comment by SeanCatVH** [comment]
There are some slight customizations but most are out of the box. We made copies of most the playlist in case we wanted to tweak them. Only using English. All was working fine before update. Prior to upgrade, the categories on the admin page where also showing up in the Get-started-with-Microsoft-365.aspx page as well. Now it is missing items such as First Days, Modern Workplace, Security, Hybrid Workplace. It is only showing Recommended and Products.


[cid:c2aaba2b-c4a5-4a55-b2ba-16e378ea4036]



[cid:bc8e15d4-a504-4f18-a12d-90161df31a00]

I hope this helps. Thanks.
________________________________

Sean Cowherd
SharePoint Analyst
913.354.6492
This E-mail is covered by the Electronic Communications Privacy Act, 18 U.S.A. 2510-2521 and is legally privileged. This is confidential information and is intended only for the individual(s) or entity(ies) named above. If the reader of this message is not the intended recipient, please contact Sender immediately. You are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited.

**Comment by jellis-thrive** [comment]
Hello @SeanCatVH 

Screenshots will not post to GitHub if you do a reply directly from email. Could you post the screenshots within GitHub directly for review?

**Comment by SeanCatVH** [comment]
Hi @jellis-thrive - I've added the screenshots. Thanks.

**Comment by SeanCatVH** [comment]
Any updates on this issue or a fix? Also just noticed that other playlists aren't displaying. 

![image](https://user-images.githubusercontent.com/84815852/120849296-83ce2680-c53b-11eb-8ed6-298493bc1153.png)

![image](https://user-images.githubusercontent.com/84815852/120849391-a52f1280-c53b-11eb-83f1-02fb6ff1a266.png)

Thanks for your time and assistance.

**Comment by jellis-thrive** [comment]
Hello @SeanCatVH - unfortunately the screenshots don't contain any red flags that would case the assets to stop displaying. Were there any changes made to the configuration files in the Communication site that were done by hand? Were any changes made to the permissions model on the Communication site? I understand that you said this happened during an upgrade; I am trying to find anything else that may be a contributing factor.

**Comment by SeanCatVH** [comment]
@jellis-thrive - No changes were made to the configuration files or to the permissions. We simply ran the upgrade using the instructions list on this site.

**Comment by SeanCatVH** [comment]
The only thing we did which I failed to mention is that we made a copy of the site within the tenant using a different name. However, the copied/backup site didn't really work either as the Microsoft 365 learning pathways features did not transfer. Could that have possibly affected the update?

Is there any harm in deactivating and reactivating the features?

Thanks.

**Comment by jellis-thrive** [comment]
@SeanCatVH before circling back to what you said last, is there any security that would prevent your infrastructure from reaching GitHub? Eg, is GitHub whitelisted? Are there any warnings or other info displayed in the Admin page?

**Comment by SeanCatVH** [comment]
@jellis-thrive - I'm posting these messages to GitHub so I don't see that being an issue. Also, it worked prior to update. There are no warnings or other information displayed on the Admin page.

**Comment by SeanCatVH** [comment]
Any other ideas? Thanks.

**Comment by jellis-thrive** [comment]
@SeanCatVH - could you post the information in the "About" section of the Admin web part? We want to ensure that the information there matches your deployment. If it does not, the cache which LP uses to operate may have become corrupted.

**Comment by SeanCatVH** [comment]
![image](https://user-images.githubusercontent.com/84815852/121392734-44c21b80-c915-11eb-89b2-98aa443c6082.png)

**Comment by jellis-thrive** [comment]
@SeanCatVH 

You could try deleting the content of the CustomConfig list in Site Contents, then refresh the Admin web part. This will refresh the config.

You cannot delete the contents of CustomConfig list; you may delete the items with the title "CustomConfig" from the CustomConfig list to force a refresh. There are other configuration items in that list that if they are deleted will break things, namely CustomSubCategories and CustomCDN.

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
