### ISSUE TITLE
 Learning pathways permission Issue

### ISSUE THREAD

**Issue by ahmedmahmoudR** [pnp/custom-learning-office-365#529]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Can you please assist, our learning pathways now just gives error.
 
When I try to create Custom sub-Category and give specific group of users  custom  permission to view the playlist

Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.]

### Expected behavior

>every specific group of users can  access specific  playlist

### Learning Pathways version number

Last version

**Comment by jellis-thrive** [comment]
Hello @ahmedmahmoudR 

Please review and complete the Diagnosing Pre-Check instructions below. We need this information to further assist.
https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md

**Comment by jellis-thrive** [comment]
Hello @ahmedmahmoudR 

The permissions must be read for everyone in the customplaylists ,  and assets list, and read/write for the customconfig list. Learning Pathways does not support the permissions model you are trying to use, where certain users can have rights to certain things only. 

Please try to remove the custom permissions and let us know if it begins working correctly once they are removed.

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
