### ISSUE TITLE
Risk of provisioning in production environment

### ISSUE THREAD

**Issue by donavanmarais** [pnp/custom-learning-office-365#53]
#### Category

- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

What are the known risks of provisioning the Custom Learning for Office 365 Beta Preview in a  production environment?

**Comment by karuanag** [comment]
Hello @donavanmarais As with any Beta solution our service management team reserves the right to make changes to the service and its components.  As we are actively resolving bugs and UX issues you would likley need to update the WebPart.  At this point I'd advise that you test the solution but not in production as we are quickly moving toward coming out of our Beta phase.   Stay tuned on our Driving Adoption blog to learn more about this timing.  (https://aka.ms/DriveAdoption)

**Comment by donavanmarais** [comment]
Thank you for your response. Perhaps I should ask the question this way rather: would you recommend provisioning this solution to a production tenant knowing that it contains bugs and UX issues or would you rather contain it to a test environment until such time as this solution comes our of your beta phase? Thanks

**Comment by karuanag** [comment]
The best practice is to deploy to a test tenant as you work through the solution.  Both for the fixes we are creating and to familiarize yourself with the solution.   Technically there is no reason not to put it to production but practically speaking you don't want to reserve the site name with a "test".

**Comment by benmurph** [comment]
> Hello @donavanmarais As with any Beta solution our service management team reserves the right to make changes to the service and its components. As we are actively resolving bugs and UX issues you would likley need to update the WebPart. At this point I'd advise that you test the solution but not in production as we are quickly moving toward coming out of our Beta phase. Stay tuned on our Driving Adoption blog to learn more about this timing. (https://aka.ms/DriveAdoption)

Hi @karuanag , I've checked the Adoption blog but couldn't see anything regarding the timeframe for coming out of Beta. Could you provide a rough timescale? That would be really useful for our roadmap to roll this out to Production.
