### ISSUE TITLE
 URL link added to playlist not working.

### ISSUE THREAD

**Issue by Kaika084** [pnp/custom-learning-office-365#530]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

when i add a URL link as an asset to playlist it doesnt show up properly. The whole section post republish comes out to be just a grey box 

### To Reproduce

add below link as an asset in a playlist 
https://techcommunity.microsoft.com/t5/yammer-blog/new-conversation-insights-help-you-measure-the-reach-and-impact/ba-p/2381246

### Expected behavior

content doesnt show up - it only comes out as a grey box with no content in it 

### Screenshots

![image](https://user-images.githubusercontent.com/85275236/120595055-6d529d00-c45f-11eb-8f24-9a30d5b27526.png)

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.

**Comment by jellis-thrive** [comment]
Hello @Kaika084 

We can test to see if this reproduces, but it may depend on how you created the asset, if you created a page to host this content, or how you linked the URL you provided as an asset.

**Comment by jellis-thrive** [comment]
Hello @Kaika084 
Many of Microsoft's sites block them from being iFramed. We have no information that I can share about how to embed content from Tech Community or if this is achievable - this may be expected behavior.

**Comment by Kaika084** [comment]
Yes you are right - its still not supported to add external URLs except for SP sites to the pathways

**Comment by juliemturner** [comment]
@Kaika084  - Just to make sure any person who reads this in the future is clear. You can put any path you want as a URL, the barrier isn't learning pathways, it's the destination of that URL and weather the host allows it's content to be iFramed. It appears techcommunity doesn't support being iFramed or if it does, requires query string parameters to make it behave properly.

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
