### ISSUE TITLE
M365LP home page still showing communication webpart

### ISSUE THREAD

**Issue by mgmjtech** [pnp/custom-learning-office-365#531]
- [x] Installation
I have followed the "Manually installing and configuring Microsoft 365 learning pathways" on a vanity URL as well as on a non-vanity URL. However, I am not getting the Microsoft 365 learning pathways home page. My M365PL site is still showing the communication home page.
I can only see CustomlearningViewer.aspx, CustomlearningAdmin.aspx and homepage pages. 

1. I do not see the rest of get-started aspx pages. I assumed using the manual installation will not install the rest of the aspx pages. - is this correct?
2. How do I get the rest of the aspx added?
3. Once I have all the aspx pages, I assumed you have to add all the webparts manually? Is there a script that can deploy those webparts on the home pages. Similar to using lookbook.

**Comment by jellis-thrive** [comment]
Hello @mgmjtech 

1) That is correct. With the manual installation, you only get the features that allow the solution to operate.
2) These can be moved from another installation that has the full install. You may have to use PowerShell / PnP to accomplish this, and use your client machine as an in between for the files themselves.
3) There is not a script that accomplishes this with official support. The intention of the Manual install, to the best of my knowledge, was to support Vanity URLs and high levels of customization.

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
