### ISSUE TITLE
Issue with configuration error

### ISSUE THREAD

**Issue by thomasdaggett** [pnp/custom-learning-office-365#532]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug
Error appearing on multiple pages, in the browser log it shows the following:
**M365LP:CustomLearningWebPart (configCDN) -- Could not get a valid configuration; Please contact your learning administrator**

Error appears on multiple pages including the admin page - "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance."

### To Reproduce

>Steps to reproduce the behavior
Visit any page that pulls content, including the admin page.

### Expected behavior

>A clear and concise description of what you expected to happen.  Content such as videos and other material is not loading, just the error message is appearing to all users.  

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.
Updated to the latest version 4.2.0.

### Additional context

>Add any other context about the problem here.

**Comment by jellis-thrive** [comment]
Hello @thomasdaggett 

Could you provide a bit more info about this issue please?

Was the deployment running before this issue occurred? If so, what was changed?
Do you use your own Content Delivery Network, or is this an out of the box installation that uses Microsoft content?
Do you have any environment security that may be preventing assets from loading?
Have you reviewed a network trace while receiving this error?

**Comment by thomasdaggett** [comment]
Hi,

Was the deployment running before this issue occurred? If so, what was changed?
We have a Prod tenant and non-prod tenant.  We are in the process of updating the LP solution to 4.2.0 in Prod – only have deployed it to the app store.  We saw the issue prior and it remains.  In non-prod we saw the issue prior, updated to 4.2.0 with the exception of the Data update not completing correctly (listed in another Bug request).

Do you use your own Content Delivery Network, or is this an out of the box installation that uses Microsoft content?  This is using the OOB install that uses Microsoft content.

Do you have any environment security that may be preventing assets from loading?  I unaware if there is any impact caused by our security measures, can you share guidance on what endpoints are needed to be available and how I could test to see if they are accessible.  I can check with being both and off the company VPN.

Have you reviewed a network trace while receiving this error?  Yes, below are our non-prod errors, this environment has the 4.2.0 solution deployed. Below are some images I captured from my analysis.

Let me know if you need anything else or if I can host a webex.

Thanks,

Thomas
***@***.***D75D36.A2698340]
***@***.***D75D36.A2698340]
***@***.***D75D36.A2698340]

 see this -
Upgrade Log
Level
Message

Upgrade Custom Config from v3 to v4 - CustomDataService (doDataUpgrade)

No Customizations to Upgrade - UpgradeService (doUpgradeCustomization)

Start Upgrading Playlists - UpgradeService (doUpgradePlaylists)

Fix playlists - UpgradeService (uPlaylistsV3V4)

Complete Upgrading Playlists - UpgradeService (doUpgradePlaylists)

Start Upgrading Assets - UpgradeService (doUpgradeAssets)

Fix assets - UpgradeService (uAssetsV3V4)

Complete Upgrading Assets - UpgradeService (doUpgradeAssets)

Upgrade Cache Config from v3 to v4 - CustomDataService (doDataUpgrade)

Start Upgrading Cache Config - UpgradeService (doUpgradeCacheConfig)

Remove Custom Values and Manifest - UpgradeService (uCacheConfigV3V4)

Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"The type SP.ListItemEntityCollection does not support HTTP PATCH method."}}}

🎓 M365LP:undefined (modifyConfig) - Error: Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"The type SP.ListItemEntityCollection does not support HTTP PATCH method."}}}

Complete Upgrading Cache Config - UpgradeService (doUpgradeCacheConfig)

Thomas Daggett, Ph.D.
Mobile: 860 449 2927 | Office: 860 686 9766
***@***.***D75D36.A2698340]

From: jellis-thrive ***@***.***>
Sent: Wednesday, June 9, 2021 11:04 AM
To: pnp/custom-learning-office-365 ***@***.***>
Cc: Daggett, Thomas ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [pnp/custom-learning-office-365] Issue with configuration error (#532)


Hello @thomasdaggett<https://urldefense.com/v3/__https:/github.com/thomasdaggett__;!!H9nueQsQ!p8ErbnjosdBNG230Wov7E-w6hUhL35bOuFh0xOTQxfnuGS7swCHpvoKwcJ3FSQRgL3q6$>

Could you provide a bit more info about this issue please?

Was the deployment running before this issue occurred? If so, what was changed?
Do you use your own Content Delivery Network, or is this an out of the box installation that uses Microsoft content?
Do you have any environment security that may be preventing assets from loading?
Have you reviewed a network trace while receiving this error?

**Comment by jellis-thrive** [comment]
Hello @thomasdaggett 

The whitelist target should be:
https://pnp.github.io/custom-learning-office-365/

By whitelisting that you should be able to get learning pathways plus any official content packs that might be published such as the SharePoint Success Site.

Please review the [Diagnosing Pre-Check]
(https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) - with this info we can further assist.

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
