### ISSUE TITLE
"Top of page" link is not working, do not jump to top section in page. 

### ISSUE THREAD

**Issue by SandeshGawdeLSEG** [pnp/custom-learning-office-365#534]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

"Top of page" link on learning pathway webpart page is not working. It does not jump to top section in page.

### To Reproduce

Go to Learning pathway webpart then > Excel > Formatting > Display or hide zero values > Office 2010 > click on "Top of Page" link.

### Expected behavior

After clicking on Top of Page link, focus should go to top of particular section. This functionality works well in original Microsoft article page.

### Screenshots

![TopOfPageError](https://user-images.githubusercontent.com/85348498/121336406-1a825500-c939-11eb-977d-ef42ecfb5f10.png)

### Learning Pathways version number

4.1.4.0

### Additional context

>Add any other context about the problem here.

**Comment by jellis-thrive** [comment]
Hello @SandeshGawdeLSEG 

We will work to reproduce this in an unchanged Learning Pathways installation and let you know if we experience the same.

**Comment by juliemturner** [comment]
@SandeshGawdeLSEG - Anchor tags which is how that "top of page" link works do not reliably work within an iFrame because the content is cross domain. Unfortunately, becuase this is an issue with the support.office.com page itself and how it behaves inside an iFrame there isn't anything we can do within the webpart to mitigate the situation. I have tagged this for the content team.

**Comment by SandeshGawdeLSEG** [comment]
@juliemturner  Thank you for your reply. 
However, Back to Top works fine on original Microsoft article page https://support.microsoft.com/en-us/office/display-or-hide-zero-values-3ec7a433-46b8-4516-8085-a00e9e476b03#top

**Comment by dcashpeterson** [comment]
Closed as inactive and not fixable.
