### ISSUE TITLE
Page not found error  

### ISSUE THREAD

**Issue by SandeshGawdeLSEG** [pnp/custom-learning-office-365#536]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Clicking on hyperlink on Learning pathway webpart gives 404 page not found error.

### To Reproduce

Go to Learning Pathway webpart > Security > Cybersecurity fundamentals > What is: Multi-factor Authentication? > click 'Learn more and get it here' hyperlink.
After clicking on link, we receive 404 page not found error.

### Expected behavior

After clicking on 'Learn more and get it here' hyperlink on Learning Pathway webpart, correct page should be displayed. 
This hyperlink works correctly in original microsoft article page (https://support.microsoft.com/en-us/topic/what-is-multifactor-authentication-e5e39437-121c-be60-d123-eda06bddf661). 

### Screenshots

![PageNotFound](https://user-images.githubusercontent.com/85348498/121342771-9aabb900-c93f-11eb-8b91-d96f50d3e278.png)

### Learning Pathways version number

4.1.4.0

### Additional context

>Add any other context about the problem here.

**Comment by jellis-thrive** [comment]
Hello @SandeshGawdeLSEG 

We will work to reproduce this in an unchanged Learning Pathways installation and let you know if we experience the same.

**Comment by juliemturner** [comment]
@SandeshGawdeLSEG  - Unfortunately upon further review the content that is shown in the iFrame the link to the "Learn more and get it here" is broken. The source article you point to is similar but is not actually the same, the content shown in the iFrame is this page: https://support.office.com/en-us/client/c97b3170-2c05-44a6-9c7d-15953ff2a024

**Comment by SandeshGawdeLSEG** [comment]
The link to the "Learn more and get it here" works perfectly on original Microsoft article page https://support.microsoft.com/en-us/topic/what-is-multifactor-authentication-e5e39437-121c-be60-d123-eda06bddf661

**Comment by SandeshGawdeLSEG** [comment]
@juliemturner Thank you for your reply.
Link "Learn more and get it here" on Microsoft article page which you provided is itself not working and giving page not found error. How will it be resolved?

**Comment by juliemturner** [comment]
@SandeshGawdeLSEG - The content of the page is iFramed... that link you shared is NOT the link that is being iFramed. Even though the content looks the same it is not the same and the link doesn't work. 

https://support.microsoft.com/en-us/topic/what-is-multifactor-authentication-e5e39437-121c-be60-d123-eda06bddf661
is not
https://support.office.com/en-us/client/c97b3170-2c05-44a6-9c7d-15953ff2a024

**Comment by SandeshGawdeLSEG** [comment]
This issue seems to be fixed by Microsoft content team.

**Comment by dcashpeterson** [comment]
This has been resolved by the content team.
