### ISSUE TITLE
Upgrade to 4.2.0 fails with Data Upgrade from v3 -> v4 

### ISSUE THREAD

**Issue by thomasdaggett** [pnp/custom-learning-office-365#537]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

upgrade log

Level | Message
-- | --
 | Upgrade Custom Config from v3 to v4 - CustomDataService (doDataUpgrade)
 | No Customizations to Upgrade - UpgradeService (doUpgradeCustomization)
 | Start Upgrading Playlists - UpgradeService (doUpgradePlaylists)
 | Fix playlists - UpgradeService (uPlaylistsV3V4)
 | Complete Upgrading Playlists - UpgradeService (doUpgradePlaylists)
 | Start Upgrading Assets - UpgradeService (doUpgradeAssets)
 | Fix assets - UpgradeService (uAssetsV3V4)
 | Complete Upgrading Assets - UpgradeService (doUpgradeAssets)
 | Upgrade Cache Config from v3 to v4 - CustomDataService (doDataUpgrade)
 | Start Upgrading Cache Config - UpgradeService (doUpgradeCacheConfig)
 | Remove Custom Values and Manifest - UpgradeService (uCacheConfigV3V4)
 | Error making HttpClient request in queryable [400] Bad Request ::&gt; {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"The type SP.ListItemEntityCollection does not support HTTP PATCH method."}}}
 | 🎓 M365LP:undefined (modifyConfig) - Error: Error making HttpClient request in queryable [400] Bad Request ::&gt; {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"The type SP.ListItemEntityCollection does not support HTTP PATCH method."}}}
 | Complete Upgrading Cache Config - UpgradeService (doUpgradeCacheConfig)

## Describe the bug

Upgrade to 4.2.0 fails with Data Upgrade from v3 -> v4, seems the upgrade process fails in two steps and then does not complete as data upgrade option remains.

### To Reproduce

>Steps to reproduce the behavior

### Expected behavior

>A clear and concise description of what you expected to happen.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.
Going from 3.0.0 to 4.2.0

### Additional context

>Add any other context about the problem here.

**Comment by jellis-thrive** [comment]
Hello @thomasdaggett 

We are reviewing the log provided and will come back with more information as soon as it is available.

**Comment by juliemturner** [comment]
@thomasdaggett - The errors in the upgrade don't make a ton of sense, implies a communication issue.  The upgrade can be run again over and over without causing issue so I suggest you navigate to the customlearningadmin.aspx page and then add the query string parameter to the page url `?forceUpdate=v3` which indicates it should go to the upgrade page again. See if it runs successfully the second time.  If not then we should get a copy of the browser console log for more information.

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
