### ISSUE TITLE
Clicking on hyperlink does not route anywhere.

### ISSUE THREAD

**Issue by SandeshGawdeLSEG** [pnp/custom-learning-office-365#538]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Clicking on hyperlink inside learning pathway webpart does not route anywhere

### To Reproduce

After clicking on hyperlink, it does not route anywhere.
Go to Learning Pathway webpart, then
1. Excel >Cells > Import or export text > Office 2010 - Office 2016 > Change the default list separator for new text files (affects all programs) > click 'Change the default list separator for saving files as text (.csv) in Excel'
2. Excel >Cells > Import or export text > Newer versions > Change the default list separator for new text files (affects all programs) > click 'Change the default list separator for saving files as text (.csv) in Excel'
3. Excel > Common use of functions > Automatically number rows > What do you want to do? >All the hyperlinks under this section are nonfunctional.
4. Excel > Common use of functions > Automatically number rows > Fill a column with a series of numbers > click 'Display or hide the fill handle'
5. Excel > Common use of functions > Automatically number rows > Use the ROW function to number rows > click 'Display or hide the fill handle'
6. PowerPoint > Animation, video & audio > Morph your slides > click 'Is my Office Click-to-Run or MSI-based'
7. PowerPoint > Animation, video & audio >  Insert a video from YouTube or another site > macOS click 'Click here'
8. Hybrid workplace > Reach large audiences with live events > Get started using Microsoft Teams for live events > In this article >Clicking on all the hyperlinks below 'In this article', none of them route to its respective page
9. Hybrid workplace > Reach large audiences with live events > Schedule a live event in Yammer using Teams > Step 1: Schedule your live event produced in Teams > click '3. Teams event group roles' > Clicking on the hyperlink 'Teams event group roles' does not route to its respective section.
10. Hybrid workplace > Reach large audiences with live events > Organize a live event in Yammer > Reasons to choose this production method > External app or device > Clicking on hyperlink 'steps' does not route anywhere
11. Hybrid workplace > Reach large audiences with live events > Organize a live event in Yammer > Reasons to choose this production method > Teams > Clicking on hyperlink 'steps' does not route anywhere.
12. Hybrid workplace > Reach large audiences with live events > Organize a live event in Yammer > Steps for broadcasting an event using an external app or device > Step > Clicking on any of the hyperlinked step under step does not route correctly to the respective step.
13.  Planner> Use Planner -> Create a plan with Planner in Teams > Click on hyperlink "Remove a Planner tab or delete a plan" or  any of the link on page > clicking on hyperlink does not route anywhere.
14. SharePoint -> SharePoint Online Quick Start -> Sign in > " targeted release options in Office 365 " this link on page is not opening 
15. SharePoint -> SharePoint Online Quick Start -> Discover >  " targeted release options in Office 365 " this link on page is not opening 
16. Excel > Charts > Add a trend or moving average line to a chart > click 'Office 2010 steps?' > Does not route anywhere.
17. Security > Top threats > Protect yourself from tech support scams > click 'Recovery options in Windows 10' >Clicking on link 'Remove an installed Windows update' it doesnot route the user to its section below with its respective heading. 
18. Security > Top threats > Protect yourself from tech support scams > click 'Recovery options in Windows 10' > After clicking on link, focus goes at the bottom of "Recovery options in Windows 10" section

### Expected behavior

After clicking any of the the hyperlink on Learning Pathway webpart page it should route to respective page or section.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

4.1.4.0

### Additional context

>Add any other context about the problem here.

**Comment by SandeshGawdeLSEG** [comment]
Any update on above raised issues regarding hyperlink redirection? Thank you

**Comment by jellis-thrive** [comment]
good morning @SandeshGawdeLSEG 

We are working through trying to reproduce these issues within Learning Pathways, and will update you as soon as we can confirm each provided. Thanks much!

**Comment by jsuddsjr** [comment]
Internal bookmark links are not currently supported in learning pathways. The page would normally jump to a location within the same page but hosting in iframe is preventing the page from adjusting. In some cases, the link is referring to another expando region on the same page. I would expect the expando to open, but again there is no response to the user click.

**Comment by dcashpeterson** [comment]
as @jsuddsjr said that isn't supported. Closing this issue
