### ISSUE TITLE
 New Learning Pathways installation in English is provisioned with navigation links and content in Dutch

### ISSUE THREAD

**Issue by bryanhart73** [pnp/custom-learning-office-365#539]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Created a new Learning Pathways installation in a tenant that has never had it before.  Followed the instructions at https://docs.microsoft.com/en-us/office365/customlearning/custom_provision .  Using this resulted in an English site collection but the navigation links were in a mix of English and Dutch. 

### To Reproduce

1) Follow the instructions at https://docs.microsoft.com/en-us/office365/customlearning/custom_provision to setup Learning Pathways from the look book in a new tenant.
2) Check the navigation links created
3) Check the News story headlines

### Expected behavior

An English site should have English navigation links.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.

**Comment by juliemturner** [comment]
I've heard of this before but the same people deploying again can't get it to happen a second time.  I suspect this is an issue with the provisioning service but since it can't be replicated it's pretty hard to track down. Sadly, it's also a chore to reprovision it which is the only real fix other than manually fixing the menu options.

**Comment by juliemturner** [comment]
You could try submitting an issue to the provisioning service issue list: 

>PROVISIONING NOTE: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to SharePoint/sp-provisioning-service GitHub Issues List.

**Comment by bryanhart73** [comment]
@jsuddsjr @karuanag

**Comment by bryanhart73** [comment]
Submitted to https://github.com/SharePoint/sp-provisioning-service/issues/542 as requested.

**Comment by dcashpeterson** [comment]
Consolidating all of the Dutch related issues into #566 .
