### ISSUE TITLE
Look book is deploying an out of date version 

### ISSUE THREAD

**Issue by bryanhart73** [pnp/custom-learning-office-365#540]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Deploying Learning Pathways using the look book instructions from https://docs.microsoft.com/en-us/office365/customlearning/custom_provision results in an old version being deployed that must be immediately upgraded.

### To Reproduce

>Steps to reproduce the behavior

### Expected behavior

>A clear and concise description of what you expected to happen.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.

**Comment by juliemturner** [comment]
Yes... that's known as the two are maintained separately and by separate people... eventually they'll be back in sync.

**Comment by bryanhart73** [comment]
@jsuddsjr @karuanag

**Comment by dcashpeterson** [comment]
consolidating with other update issues #589 updating coming soon.
