### ISSUE TITLE
How can I hide Admin Center category only for Learning Pathway admins?

### ISSUE THREAD

**Issue by kavitajoshi** [pnp/custom-learning-office-365#541]
This issue is duplicate of #170. Answer provided in 170 is not correct and satisfactory. Question is showing Adoption Tools category for selected users / group only who are admins. This must be common scenario and looking for practical answer.

**Comment by juliemturner** [comment]
@kavitajoshi - the answer to #170 was absolutely correct... what I think was missing is that I took the question to mean the Learning Pathways Admin "view" but in reality the question was specific to a category of learning pathways content. Unfortunately learning pathways doesn't have a way to target/secure content to an audience. 

A work around would be to add a second content pack also pointing to the learning pathways CDN and hide everything but the admin content and then hide the admin content in the main learning pathways content pack.  Then create a special page that has the viewer web part on it targeted to the admin content pack.

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
