### ISSUE TITLE
Microsoft 365 learning pathways has a configuration issue (user in China)

### ISSUE THREAD

**Issue by MCMatStoryals** [pnp/custom-learning-office-365#545]
A user in China is receiving the "Microsoft 365 learning pathways has a configuration issue" error. But when we access the site (outside China) we do not receive any errors and the webpart works as it should.

Does M365 Learning pathways not work in China? If so, is there a way to go about this and have users in China access the Learning pathways content?

## Describe the bug

Error message on the page is Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. 

M365LP:CustomLearningWebPart (configCDN) -- Could not get a valid configuration; Please contact your learning administrator.e.log @ custom-learning-web-part_9f36b4992c3974449682ffe4b8867764.js:1

### Learning Pathways version number

4.2.0

### Additional context

The end-user facing the issue is based in Shanghai, China.

**Comment by juliemturner** [comment]
We have no knowledge of limitations with using learning pathways in China one way or the other. Can they access the pages in support.office.com? That said, I would suggest reviewing the browser console in more detail as the message you posted suggests that the users are not able to access GitHub urls.  You can review the network tab to see if it's being blocked.

**Comment by MCMatStoryals** [comment]
Hi @juliemturner, here's the browser console from the user in China who is not able to access Learning pathways 
[M365LP browser console (user in China).txt](https://github.com/pnp/custom-learning-office-365/files/6684276/M365LP.browser.console.user.in.China.txt)

**Comment by juliemturner** [comment]
Sorry I guess I wasn't clear... Browser console -> network tab. I don't really need to see it myself I'm telling you that those users are being blocked from GitHub and you can get details of why on the network tab.  So this isn't really a learning pathways issue (at least at this point) it's an issue with users getting access to GitHub url: `pnp.github.io/custom-learning-office-365/learningpathways/v4/manifest.json`

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
