### ISSUE TITLE
 Most of the users are unable to view content in Learning path webpart

### ISSUE THREAD

**Issue by RohitKarri225** [pnp/custom-learning-office-365#546]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Most of the users from one of our SP Online site, are unable to view content from Learning path web part. Whereas, it is working fine for, other users and admins. 

### To Reproduce

Login to the site and navigate to the Page with Learning path web part

### Expected behavior

>A clear and concise description of what you expected to happen.
[GET IT ISSUE.log](https://github.com/pnp/custom-learning-office-365/files/6670191/GET.IT.ISSUE.log)

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.

**Comment by Andra-shi** [comment]
@RohitKarri225 : I'm having the same issue. Did you solve this problem?
