### ISSUE TITLE
Change the image of a custom subcategory

### ISSUE THREAD

**Issue by tiapatel** [pnp/custom-learning-office-365#55]
I cannot find anywhere to change the image for a new subcategory. Is there a way to not use the default image?

**Comment by juliemturner** [comment]
Not at the moment no.

**Comment by tiapatel** [comment]
@juliemturner Thanks for getting back to me. Is it on the roadmap? If so, when is that enhancement expected?

**Comment by juliemturner** [comment]
It's not on the roadmap this is the first request I've had for it, so I can't speak to delivery timeline.

**Comment by tiapatel** [comment]
That's surprising! It would be a great feature as it would enable us to extend the usage of playlists/assets to products currently not covered by the CLP (e.g. Windows 10) whilst ensuring that the look and feel is consistent with the MSFT-provided products.

**Comment by technoteach** [comment]
Is there a way to vote on this?  I would love this as well.

**Comment by juliemturner** [comment]
If the item has been included in the UserVoice topic then you can vote on it: https://microsoftteams.uservoice.com/forums/913429-learning-solutions

**Comment by markuspelto** [comment]
@tiapatel, if you are open for workarounds, there is a json column in one of the support lists (in site contents) that has the image url for your custom subcategory. You can find the correct place using browser search or copy pasting the code to some text editor and searching there.

**Comment by juliemturner** [comment]
@markuspelto -- yes you can do that, but there is no way to do it through the UX.

**Comment by kyleg11** [comment]
MS actually entered this tread for me. What this is to clarify is that when added a new section for PowerBI and Stream (since these are not included) you get a default icon that is inconsistent with other which are there application logo (or if you want a custom logo). What you get here and can not change in the UI is the icon that is a blue ribbon with speed (lines) as if it is flying in (or are those suppose to be text content lines) not sure what that icon is suppose to be) I do see here there is some workaround that I will read and try now as we are promoting stream currently and want people to see a real "stream" icon

**Comment by bybytaren** [comment]
> MS actually entered this tread for me. What this is to clarify is that when added a new section for PowerBI and Stream (since these are not included) you get a default icon that is inconsistent with other which are there application logo (or if you want a custom logo). What you get here and can not change in the UI is the icon that is a blue ribbon with speed (lines) as if it is flying in (or are those suppose to be text content lines) not sure what that icon is suppose to be) I do see here there is some workaround that I will read and try now as we are promoting stream currently and want people to see a real "stream" icon

Did the workaround work for you? Something you can share?

**Comment by kyleg11** [comment]
Currently no workaround for this. Custom images/icons still seem to not be allowed for sections. Actually our section for stream is gone now as of 12 days ago. The content is there on the backend, but seems like a max of 12 product icons is allowed now? Stream was #13.

**Comment by juliemturner** [comment]
Yes, V3 still doesn't allow you to add/edit custom subcategory images from the UI.
There is no limit to the number of subcategories (aka in your case product icons). What version of the product are you now working with? Stream was added to the content update that happened at Ignite. And, unless there is a bug there is no limit to the number of subcategories you can have.

**Comment by johncallaway58** [comment]
@markuspelto We tried the workaround and no matter where we point to, it doesn't seem to load the custom image that we want. Did you actually get this workaround to work or was it just a suggestion on your part. Where are you storing the custom image you are linking to?

**Comment by johncallaway58** [comment]
@juliemturner The user voice link provided above isn't working. Is there a UserVoice topic for the Learning Pathway extension? Is the ability to add custom image on the roadmap at all?

**Comment by juliemturner** [comment]
@johncallaway58  - Yes, I've changed the image several times by modifying the JSONData field for CustomSubCategories in the CustomConfig list. There is an Image property, you must adjust that to be a full URL to a valid image file that everyone can get to. The ability to modify it through the UX will come in the next major version release.  Officially, I don't know when that will be.

Here's a link to the Feedback and Support page, the link to the UserVoice channel is there. https://docs.microsoft.com/en-us/office365/customlearning/feedback

**Comment by johncallaway58** [comment]
Thanks for the quick response. I have tried the suggested work around and I have been unable to get it to work, even if it is pointing to a library in the site with the image. I will keep plugging away.

John Callaway
SharePoint Operations Engineer
W: 801-353-5311 or 35311
M: 425-638-3659

Have you heard about the new Yammer?a
Attend a Webinar on January 30th<https://aka.ms/NewYammerWebinar>

**Comment by juliemturner** [comment]
I suspect you're just not refreshing the cache via the admin web part, but if you continue to have issues please open up a separate issue.

>Note: Please be careful responding via email as your email signature ends up in the github issue body. I've removed it from your previous response.

**Comment by 67nmark** [comment]
@juliemturner, can you please clarify how to 'refresh the cache via the admin web part'. Thanks very much. Cheers, Mark

**Comment by juliemturner** [comment]
Every time the web part loads (when you're on the admin page) the cache is refreshed in the CustomConfig list.  The viewer web parts then use that cache, they don't actually load data from the lists, etc...

**Comment by 67nmark** [comment]
Thanks - I think I was just the victim of a delay :). Sorted now. Thanks again.
