### ISSUE TITLE
Bug with subcategory's not being created

### ISSUE THREAD

**Issue by rthompson0** [pnp/custom-learning-office-365#553]
updating to 4.2.0 will not let me create subcategories under the product and get started categories but will let me create subcategories under Adoption Tools.

**Comment by jellis-thrive** [comment]
Hello @rthompson0 

Could you please provide some screen shots of what it looks like working, as well as the section that is not working?

**Comment by BR-github1** [comment]
I'm having this same issue as well. Creating a new subcategory in Get Started or Scenarios and clicking the save button doesn't save the new subcategory or heading. Working correctly under Products and Adoption Tools.

**Comment by dcashpeterson** [comment]
@BR-github1

Could you please provide some screen shots of what it looks like working, as well as the section that is not working? We would need more information to help work on this so if you can provide some instructions on how best to reproduce, errors you might get from the console, etc.

**Comment by BR-github1** [comment]
Sure, screenshots attached of creating a new sub-category, and the result after clicking save. 

Error message in console is: 

"Message: 🎓 M365LP:CustomLearningAdmin (upsertSubCategory) - TypeError: Cannot read property 'SubCategories' of undefined
e.log @ custom-learning-admin-web-part_a856afe0e07b13cfeb87.js:1
(anonymous) @ custom-learning-admin-web-part_a856afe0e07b13cfeb87.js:1
e.log @ custom-learning-admin-web-part_a856afe0e07b13cfeb87.js:1
e.write @ custom-learning-admin-web-part_a856afe0e07b13cfeb87.js:1
n.upsertSubCategory @ custom-learning-admin-web-part_a856afe0e07b13cfeb87.js:1
(anonymous) @ custom-learning-admin-web-part_a856afe0e07b13cfeb87.js:1
(anonymous) @ custom-learning-admin-web-part_a856afe0e07b13cfeb87.js:1
(anonymous) @ custom-learning-admin-web-part_a856afe0e07b13cfeb87.js:1
(anonymous) @ custom-learning-admin-web-part_a856afe0e07b13cfeb87.js:1
Dn @ custom-learning-admin-web-part_a856afe0e07b13cfeb87.js:1
n.saveSubCategory @ custom-learning-admin-web-part_a856afe0e07b13cfeb87.js:1
n.onUpdate @ custom-learning-admin-web-part_a856afe0e07b13cfeb87.js:1
n._onClick @ custom-learning-admin-web-part_a856afe0e07b13cfeb87.js:1
o @ sp-pages-assembly_en-us_5e6c9ac2363a3937de6ee9b2930e840a.js:65
p @ sp-pages-assembly_en-us_5e6c9ac2363a3937de6ee9b2930e840a.js:65
(anonymous) @ sp-pages-assembly_en-us_5e6c9ac2363a3937de6ee9b2930e840a.js:65
v @ sp-pages-assembly_en-us_5e6c9ac2363a3937de6ee9b2930e840a.js:65
lt @ sp-pages-assembly_en-us_5e6c9ac2363a3937de6ee9b2930e840a.js:65
nt @ sp-pages-assembly_en-us_5e6c9ac2363a3937de6ee9b2930e840a.js:65
it @ sp-pages-assembly_en-us_5e6c9ac2363a3937de6ee9b2930e840a.js:65
ft @ sp-pages-assembly_en-us_5e6c9ac2363a3937de6ee9b2930e840a.js:65
L @ sp-pages-assembly_en-us_5e6c9ac2363a3937de6ee9b2930e840a.js:65
V @ sp-pages-assembly_en-us_5e6c9ac2363a3937de6ee9b2930e840a.js:65
Xt @ sp-pages-assembly_en-us_5e6c9ac2363a3937de6ee9b2930e840a.js:65
Yt @ sp-pages-assembly_en-us_5e6c9ac2363a3937de6ee9b2930e840a.js:65
t.unstable_runWithPriority @ sp-pages-assembly_en-us_5e6c9ac2363a3937de6ee9b2930e840a.js:65
jl @ sp-pages-assembly_en-us_5e6c9ac2363a3937de6ee9b2930e840a.js:65
D @ sp-pages-assembly_en-us_5e6c9ac2363a3937de6ee9b2930e840a.js:65
$t @ sp-pages-assembly_en-us_5e6c9ac2363a3937de6ee9b2930e840a.js:65


![Capture2](https://user-images.githubusercontent.com/88503606/128386678-c4568725-2e51-4b41-91be-34becf255f4f.PNG)
![Capture](https://user-images.githubusercontent.com/88503606/128386681-fa1d5e0a-dc83-4a35-8c4a-967c78333621.PNG)

**Comment by dcashpeterson** [comment]
@BR-github1  do you know what version you are using?

**Comment by BR-github1** [comment]
Version 4.1.4.0

**Comment by dcashpeterson** [comment]
I would strongly suggest that you upgrade to the latest version of Learning Pathways. This link includes the instructions. We are currently at version 4.3 and this version includes various bug fixes. https://github.com/pnp/custom-learning-office-365#updating-the-solution

**Comment by dcashpeterson** [comment]
@BR-github1  is this still an issue?

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
