### ISSUE TITLE
Will upgrading delete custom pages and assets 

### ISSUE THREAD

**Issue by sigmosh** [pnp/custom-learning-office-365#554]
### What is the context of your question

- [ ] Upgrading

### What is your question

Hello
Will upgrading the Microsoft 365 Learning Pathway from version 4.1.3 to version 4.3.0 delete all the custom changes and additions made to the site?

I modified the site to include tutorials about other platforms we use in our organisation and added some pages to the Microsoft Teams section.

Many thanks
Moshe

**Comment by jellis-thrive** [comment]
Hello @sigmosh 

No, it will not. Only the assets that allow Learning Pathways to operate are touched in an update. Here is more information about the update process:

https://docs.microsoft.com/en-us/office365/customlearning/custom_update

Any previously created custom playlists and assets are maintained
Settings to hide or show content are maintained
The learning pathways SharePoint template is left unchanged
The learning pathways site pages aren't translated. This work must be done manually

**Comment by sigmosh** [comment]
Many thanks for the quick reply @jellis-thrive
