### ISSUE TITLE
Unable to provision M365 learning pathways

### ISSUE THREAD

**Issue by venkateshwaran2k** [pnp/custom-learning-office-365#555]
We are unable to provision the M365 learning pathways to my tenant. Below error throws when attempting to provision
Could you please assists to provision the learning pathway site to my tenant.

![image](https://user-images.githubusercontent.com/87026435/124622118-7688bc80-de98-11eb-8832-a5ab114c9e33.png)
![image](https://user-images.githubusercontent.com/87026435/124622281-991ad580-de98-11eb-8b77-1a11567082fa.png)

**Comment by jellis-thrive** [comment]
Hello @venkateshwaran2k 

Please review and make sure that you meet each of the pre-requisites defined below. You may be missing permissions or other setup needs to deploy Learning Pathways.
https://docs.microsoft.com/en-us/office365/customlearning/custom_provision#prerequisites-for-multilingual-support

If confirming the pre-requisites and ensuring they each have been met does not resolve the Provisioning issue, please create a new request here:

https://github.com/SharePoint/sp-provisioning-service/issues

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
