### ISSUE TITLE
Query Regarding Permissions

### ISSUE THREAD

**Issue by chandni-agarwal** [pnp/custom-learning-office-365#556]
Hi Team, I had some queries, I hope this is the right place to put them up.
1. How the data(that we are permitting during the installation via look book) is being used?
2. Can we revoke the permissions from the azure enterprise application after the development is complete. What impact will it do to my existing LP?
3. If we do manual setup, do we still get all the content updates automatically?

**Comment by jellis-thrive** [comment]
1) I will follow up with staff and see if any other information is available about what is done with the telemetry data.
2) After the solution is deployed, the specific security principle used to install the Learning Pathways solution can be revoked. It will not change existing Learning Pathways setup.
3) Manual setup does not provision the same content as the automated installation; it will provision the solution alone. I would suggest doing a Test install in another tenant to see the difference between the full solution and the Manual solution.

**Comment by juliemturner** [comment]
1. I don't know what "data" you're referring to; can you be more specific.
2.  - Answered
3. Manual provisioning only means that you will not have the provisioned template pages provisioned, but that doesn't affect getting content updates.

**Comment by chandni-agarwal** [comment]
Thanks @jellis-thrive and @juliemturner . 

@juliemturner,
in the first point, I wanted to understand, about the data that is being accessed via permissions that we give during the setup of learning pathways.

**Comment by juliemturner** [comment]
You mean via the lookbook.microsoft.com site... there is no data accessed, it just needs permissions of a very high level to access, install, and deploy the customlearning.sppkg file to the tenant app catalog.  That said we do not write, maintain, or support the provisioning service it is, to us, only a service that can provisioning a custom site template with a solution in this manner.  You can get more information and ask more questions by reaching out to that team in the GitHub repository for the provisioning service: [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

**Comment by chandni-agarwal** [comment]
Get it!. Thanks @juliemturner 😊
