### ISSUE TITLE
 issue with sharepoint success site 

### ISSUE THREAD

**Issue by cdlpty** [pnp/custom-learning-office-365#557]
![image](https://user-images.githubusercontent.com/65040031/124803019-3409c300-df1e-11eb-9488-95eab89f28f3.png)

hi im having issue deploying sharepoint success site, yesterday i installed learning pathways and sharepoint success site, but when i tried to access sharepoint success site  the page didnt load  ok

this is the error
Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.]

**Comment by jellis-thrive** [comment]
Hello @cdlpty 

Please review the Diagnosing Pre-Check and submit the information to us to further assist.
https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md

**Comment by juliemturner** [comment]
@cdlpty - you probably should also review that you completed the provisioning steps for the SharePoint Success Site; many, many people miss the final step of confirming the content pack setup. Please see this short video for more information: https://www.youtube.com/watch?v=HZjxBAKVnJs

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
