### ISSUE TITLE
[QUESTION] 365 Tenant permissions; can we grant for installation of Learning Pathways, then revoke?

### ISSUE THREAD

**Issue by panderson25** [pnp/custom-learning-office-365#558]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [X] Installation
- [ ] Learning Pathways Content
- [ ] SharePoint Success Content
- [X] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### What is your question

The tenant permissions requested to install Learning Pathways are significant, including access to all site collections.  Can we admin consent for Learning Pathways installation, then revoke the consent a day later, while retaining functionality?  We do not want to leave permissions in place at that level on a production tenant that are not needed ongoing.

**Comment by jellis-thrive** [comment]
Hello @panderson25 

Yes, you may do that. The permission set used for automated installation is a one time set that allows PnP to complete provisioning. It will not affect Learning Pathways nor the ability to update the solution once removed.

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
