### ISSUE TITLE
Why does the multilingual feature not change the learning content?

### ISSUE THREAD

**Issue by schumaho** [pnp/custom-learning-office-365#559]
## Submit your question

Why does the multilingual feature not change the learning content?

### What is the context of your question

- [x ] Learning Pathways Content

### What is your question

We implemented the Learning Pathway solution (thanks for the hint regarding the Dutch language: https://github.com/pnp/custom-learning-office-365/issues/539 :) )

But when a user (with profile language set to German) changes the language of the SharePoint site this does not affect the learning content as you can see in the attached image.

![image](https://user-images.githubusercontent.com/87187038/125126670-ba2f3080-e0fb-11eb-96f8-972c796f33f4.png)

I also tried to deactivate the multilingual feature, but then the learning content is shown in English only (see following screenshot). 

![image](https://user-images.githubusercontent.com/87187038/125127265-8bfe2080-e0fc-11eb-86d6-edc962421f63.png)

Can anybody explain this behaviour to me? That does not make any sense.

I am looking forward to your comments and experiences.

Best regards
Max

**Comment by jellis-thrive** [comment]
Hello @schumaho 

To confirm, this is the out of the box content which comes with Learning Pathways and not _custom_ content?
Also, where is their profile set to German, please?

**Comment by schumaho** [comment]
Hello @jellis-thrive,
yes, this happens with the out of the box content!
The office profile in Delve is set to German:

![image](https://user-images.githubusercontent.com/87187038/125247628-6e46dc00-e2f3-11eb-8fdb-57e8cf86ea15.png)

Please let me know, if you need further information!

**Comment by jellis-thrive** [comment]
Thanks @schumaho 

Is this the only language this happens in? Could you try to check other languages, as well as someone else's account?

**Comment by dcashpeterson** [comment]
combining this issue with #566. If this is different please submit a new issue.

**Comment by schumaho** [comment]
@jellis-thrive : This happens in all languages.

But as I found out now the content shown in the learning content is depending on your profile language! 

This does not make sense to me at all, but can be read [here](https://docs.microsoft.com/en-us/office365/customlearning/custom_overview_ml):
"The language displayed in the learning pathways web part will depend on their user's personal language and region settings. ..."

Thanks for all your suggestions!
