### ISSUE TITLE
 Microsoft 365 learning pathways has a configuration issue for some users after reinstalling.

### ISSUE THREAD

**Issue by MCMatStoryals** [pnp/custom-learning-office-365#560]
## Describe the bug

> Our customer is not able to access Microsoft 365 Learning Pathways webpart. But we have an account in our customer's tenant and we are able to access the webpart.

The customer was able to access the Learning Pathways previously. But after uninstalling the old version and reinstalling the new version, the configuration issue exists.

### Learning Pathways version number

> 4.3.0

### Additional context

> Here's the browser console from the customer 
[mmh_lp_issue.txt](https://github.com/pnp/custom-learning-office-365/files/6800801/mmh_lp_issue.txt)

Please let me know if you need additional info.

**Comment by juliemturner** [comment]
Based on the console log you shared it appears you have a networking problem. 

I would start with the CustomLearningAdmin.aspx page and make sure that's loading properly.  If it isn't, I would take a look at the network tab when you're trying to load the Admin page.  If it is then you have either a networking or a security issue with those users who are getting this error.

Basically, the key is this line:
Failed to load resource: net::ERR_CONNECTION_TIMED_OUT pnp.github.io/custom-learning-office-365/learningpathways/v4/manifest.json:1

**Comment by MCMatStoryals** [comment]
@juliemturner Thank you for your diagnosis on this. But what I do not understand is that the CustomLearningAdmin page works for us perfectly well using the customer account provided to us, but the customer themselves are not able to access any of the pages. Could it be a VPN issue?

The customer already had Learning Pathways installed prior to us uninstalling and reinstalling the webpart through a third-party provisioning tool. And they were able to access Learning Pathways without any issues.

Also, we are not able to add the webpart to other SharePoint sites. Is it because the app may not be tenant deployed? Would re-deploying the webpart through the SharePoint lookbook solve this?

**Comment by MCMatStoryals** [comment]
Thank you for your insights @juliemturner :)

I believe the same as well that it is a network issue, we will take a look as to why they are not able to access the GitHub site.

I did add the solution to each site collection. But when the customer tried to add the web part to a SharePoint page, Microsoft 365 learning pathways was not listed as one of the available web parts.

**Comment by juliemturner** [comment]
Validate that Microsoft learning pathways shows up in the site contents and then try again, you may just have a timing issue because if the app is added to the site collection the web part will show up.
