### ISSUE TITLE
Microsoft teams -  Videos not loading in SharePoint tab app 

### ISSUE THREAD

**Issue by SubbaReddi** [pnp/custom-learning-office-365#561]
Hi Team,
Using https://aka.ms/M365LPTeamsApp app template to create manifest for SharePoint tab app. It is working fine in Web teams client. But videos are not loading in Desktop teams. 

### To Reproduce
Issue is reproducible in customer environment only. But could not able to reproduce in our dev tenant.

### Expected behavior

Videos should be shown as below:
![image](https://user-images.githubusercontent.com/69682598/125755013-5921b0da-223e-4df0-81c2-9230ec907679.png)

But showing blank in video placeholder. Don't see any errors in console logs.
Could you please suggest what could be wrong.

**Comment by juliemturner** [comment]
I believe it's a known issue that content doesn't render in the iframe in the Teams app, but the content team will need to comment, I've tagged them.

**Comment by SubbaReddi** [comment]
@peterjkrebs : Could you please help to resolve above issue

**Comment by dcashpeterson** [comment]
Closed as inactive
