### ISSUE TITLE
Issues upgrading from 2.x to 4.x (latest) 

### ISSUE THREAD

**Issue by Rangeball** [pnp/custom-learning-office-365#563]
I have a organization that have used the solution extensively and customized it quite a bit. They've been running the earliest version with no upgrades for a while when in June this year they started to have some issues with content updates (or at least that is when they noticed). They tried to upgrade to the newer 4.0 version but that seems to have created all kinds of problems for them. 

We're looking for general guidance on how to move from 2.x->3.x->4.x (latest), particularly given some of their interface customizations. We can't seem to find the older packages either to try and test this out, to upgrade incrementally and try and replicate in a non-prod environment. Will get more details on issues, but appreciate any guidance.

**Comment by jellis-thrive** [comment]
Hello @Rangeball 

Understood. Is this setup currently only in a single environment, or is the same setup mirrored in a Development and Production environment? What issues arose from the attempted upgrade, and what steps were taken to initiate the upgrade?

**Comment by Rangeball** [comment]
It's a single environment, they've restored to get back to 2.x, their original state. They originally followed the 4.x [instructions](https://docs.microsoft.com/en-us/office365/customlearning/custom_update#:~:text=If%20you%20have%20an%20existing%20Learning%20Pathways%20site%2C,previously%20created%20custom%20playlists%20and%20assets%20are%20maintained) to upgrade, and get the following error when they go to the Custom Learning Admin portal. Error: The value for "_manifest" must not be undefined...(see the attached image).
![issue](https://user-images.githubusercontent.com/39935100/126178163-66cbe44f-6a89-46ee-97c8-b00383cdfbaa.jpg)
We're thinking to upgrade incrementally from 2.x to 3.x to 4.x but unable to find the 3.x binaries, is there a location for that?

**Comment by jellis-thrive** [comment]
Thanks @Rangeball - an incremental upgrade would be the best path for this definitely. I will work to surface the version updates for you.

**Comment by jellis-thrive** [comment]
@Rangeball - Each of these is the last package of the respective version.

https://github.com/pnp/custom-learning-office-365/tree/main/installation/Archive

**Comment by Rangeball** [comment]
Thanks @jellis-thrive, we'll try with the link/packages you provided and share how it goes.

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
