### ISSUE TITLE
 Language config is missing when loading Learning Pathways web part

### ISSUE THREAD

**Issue by thrive-jquast** [pnp/custom-learning-office-365#567]
Hi,

We have M365 Learning Pathways setup, and only some users are getting error trying to load the learning pathways web part.

The error message is "No configuration was found for CDN Default and Language"

I looked at console logs, and here is the GET request that is leading to error.
https://contoso.sharepoint.com/sites/TheDRC/_api/web/lists/getByTitle('CustomConfig')/items?$select=Id,Title,JSONData&$orderby=Id desc&$filter=(Title eq 'CustomConfig') and (CDN eq 'Default') and (Language eq '')&$top=1

Notice that Langage eq '', this is empty
After this GET Request, it generates error about no configuration being found.
Here is the configuration trying to be loaded that cannot be found
https://pnp.github.io/custom-learning-office-365/learningpathways/v4//metadata.json

Notice that after v4/ the language is missing. Above link returns 401 file not found, however if I modify it to v4/en-us/metadata.json then file is found successfully

Any ideas on why Language for user is not being passed as part of query for the configuration file?
We have checked the language settings for user in Office profile and it's configured to English.
https://support.microsoft.com/en-us/topic/change-your-display-language-and-time-zone-in-microsoft-365-for-business-6f238bff-5252-441e-b32b-655d5d85d15b

**Comment by jellis-thrive** [comment]
Hello @thrive-jquast 

Thank you for reaching out. I understand that you have some data pending an engagement later today and will watch for that. In the meantime, I will review similar cases and see if the issue is reproducible within our Test environment.

**Comment by thrive-jquast** [comment]
Hi jellis, 

We can close issue. For an impacted user it was resolved after navigating to customlearningviewer.aspx page. Now when user goes to load page with learning pathways web part it's loading without configuration error.
