### ISSUE TITLE
[QUESTION] How to create a new category?

### ISSUE THREAD

**Issue by BostonO365** [pnp/custom-learning-office-365#568]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [ ] Installation
- [ ] Learning Pathways Content
- [ ] SharePoint Success Content
- [X] Administration
- [X] Custom Content
- [ ] Viewer Web Part

### What is your question

I hope I'm missing something really simple, in which case I'm sorry for wasting your time, but I can't find this anywhere.  
**Where's the button to create a new category?**  Not sub-category, but top level category.

Thank you.

**Comment by jellis-thrive** [comment]
Hello @BostonO365 

Top level categories cannot be created without hosting and connecting to a Content Delivery Network that has them defined. 

More info about deployment is available here:
https://docs.microsoft.com/en-us/office365/customlearning/custom_partnerguide_contint#content-pack-guidelines

**Comment by dcashpeterson** [comment]
Closed as answered. If you are still having an issue please create a new issue.
