### ISSUE TITLE
 Learning Pathways content not rendering in Teams client

### ISSUE THREAD

**Issue by RebeccaHallO365** [pnp/custom-learning-office-365#569]
## Describe the bug
Content not loading in Teams client. Sometimes just get a blank screen, and sometimes getting error: **WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance".

Seems to render from direct link on web and in Teams on the web, but shows multiple errors in the console (see screenshot of errors below)

### To Reproduce
Launch Learning Pathways from within Teams using link in Teams nav bar

### Expected behavior
When launched from the nav link in Teams, the full Learning Pathways page opens with links to all catalogs.

### Screenshots
![image](https://user-images.githubusercontent.com/88344495/127909998-5ed4461c-82b8-4cc3-bf81-7b75f63b4acf.png)
![image](https://user-images.githubusercontent.com/88344495/127910107-dd3e1d0c-bf41-4922-bb0e-5a6c9eb49d69.png)
![image](https://user-images.githubusercontent.com/88344495/127910176-037e2294-3486-4ef3-82ef-438d4507d0b4.png)

### Learning Pathways version number
Version 1.0.0

**Comment by dcashpeterson** [comment]
@RebeccaHallO365 Thanks for reporting this. I am not exactly sure from your explaination what the issue is. Are you having issues with viewing Learning Pathways in the Teams web client and SharePoint or the Teams desktop client? Or is it both? Are you using version 1.0.0? 

I just checked with the latest installation using V 4.1.4 and I was able to see the content find in all of the above. I don't have a copy of build 1.0.0 so I can only go back to V 2.0.17 and I can see something similar to what you are sharing. My suggestion would be to upgrade the web part and see if this resolves the issue. We provided links to archived versions and instructions for upgrade in issue #563. Let me know if I got this wrong. I might need more information.

**Comment by dcashpeterson** [comment]
@RebeccaHallO365 I double checked this one and have a few suggestions.

1. Can you go to the admin page for Learning Pathways. That will regenerate the cache. Let me know if you can access this page.
2. If you can access the admin page. Try this page https://<yourtenant>.sharepoint.com/sites/<LearningPathwaysSite>/SitePages/CustomLearningViewer.aspx and see if you can load this page. 

Check both of those things and let me know what happened.

**Comment by RebeccaHallO365** [comment]
Hi Derek,

Thanks for your follow-ups.

I did upgrade to version 4.3.0.0 and that seemed to fix the issues.

Thanks,

Becca

______________________________________________
Rebecca Hall
Domain Architect - Collaboration
IT Employee Experience
Eversource Energy
860-665-3494
***@***.******@***.***>




The information contained in this e-mail and any files transmitted with it may be a confidential attorney-client communication or may otherwise be privileged and confidential.  If the reader of this message, regardless of the address or routing, is not an intended recipient, you are hereby notified that you have received this transmittal in error and any review, use, distribution, dissemination or copying is strictly prohibited.  If you have received this message in error, please delete this e-mail and all files transmitted with it from your system and immediately notify the sender by sending a reply e-mail to the sender. Thank you.

**Comment by RebeccaHallO365** [comment]
Hi Kevin,

We thought this issue was resolved by doing the upgrade and content refresh, but it’s not.

We’re wondering if there is a permissions issue.

Two other admins and I have Global Reader, and it works for us. However, it’s not working for others who don’t have Global Reader.

Are there specific permissions we should be assigning so all users can see the content in this app?

Thanks,

Becca

______________________________________________
Rebecca Hall
Domain Architect - Collaboration
IT Employee Experience
Eversource Energy
860-665-3494
***@***.******@***.***>




The information contained in this e-mail and any files transmitted with it may be a confidential attorney-client communication or may otherwise be privileged and confidential.  If the reader of this message, regardless of the address or routing, is not an intended recipient, you are hereby notified that you have received this transmittal in error and any review, use, distribution, dissemination or copying is strictly prohibited.  If you have received this message in error, please delete this e-mail and all files transmitted with it from your system and immediately notify the sender by sending a reply e-mail to the sender. Thank you.

From: Hall, Rebecca L
Sent: Monday, August 9, 2021 11:47 AM
To: pnp/custom-learning-office-365 ***@***.***>; pnp/custom-learning-office-365 ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [pnp/custom-learning-office-365] Learning Pathways content not rendering in Teams client (#569)

Hi Derek,

Thanks for your follow-ups.

I did upgrade to version 4.3.0.0 and that seemed to fix the issues.

Thanks,

Becca

______________________________________________
Rebecca Hall
Domain Architect - Collaboration
IT Employee Experience
Eversource Energy
860-665-3494
***@***.******@***.***>




The information contained in this e-mail and any files transmitted with it may be a confidential attorney-client communication or may otherwise be privileged and confidential.  If the reader of this message, regardless of the address or routing, is not an intended recipient, you are hereby notified that you have received this transmittal in error and any review, use, distribution, dissemination or copying is strictly prohibited.  If you have received this message in error, please delete this e-mail and all files transmitted with it from your system and immediately notify the sender by sending a reply e-mail to the sender. Thank you.

**Comment by RebeccaHallO365** [comment]
Hi Kevin,

We were looking at the log and found there’s a failure trying to access github. We didn’t realize the app would still be making calls to github once it’s installed on our tenant. Our security policies block github for the majority of users. Could that be causing the issue?

How can I go about those directions in line 3 below to set the request to “no-cors”?

***@***.***

Thanks,

Becca

______________________________________________
Rebecca Hall
Domain Architect - Collaboration
IT Employee Experience
Eversource Energy
860-665-3494
***@***.******@***.***>




The information contained in this e-mail and any files transmitted with it may be a confidential attorney-client communication or may otherwise be privileged and confidential.  If the reader of this message, regardless of the address or routing, is not an intended recipient, you are hereby notified that you have received this transmittal in error and any review, use, distribution, dissemination or copying is strictly prohibited.  If you have received this message in error, please delete this e-mail and all files transmitted with it from your system and immediately notify the sender by sending a reply e-mail to the sender. Thank you.

From: Hall, Rebecca L
Sent: Monday, August 16, 2021 10:11 AM
To: 'pnp/custom-learning-office-365' ***@***.***>; 'pnp/custom-learning-office-365' ***@***.***>
Cc: 'Mention' ***@***.***>; Fitterman, Brian D ***@***.***>
Subject: RE: [pnp/custom-learning-office-365] Learning Pathways content not rendering in Teams client (#569)

Hi Kevin,

We thought this issue was resolved by doing the upgrade and content refresh, but it’s not.

We’re wondering if there is a permissions issue.

Two other admins and I have Global Reader, and it works for us. However, it’s not working for others who don’t have Global Reader.

Are there specific permissions we should be assigning so all users can see the content in this app?

Thanks,

Becca

______________________________________________
Rebecca Hall
Domain Architect - Collaboration
IT Employee Experience
Eversource Energy
860-665-3494
***@***.******@***.***>




The information contained in this e-mail and any files transmitted with it may be a confidential attorney-client communication or may otherwise be privileged and confidential.  If the reader of this message, regardless of the address or routing, is not an intended recipient, you are hereby notified that you have received this transmittal in error and any review, use, distribution, dissemination or copying is strictly prohibited.  If you have received this message in error, please delete this e-mail and all files transmitted with it from your system and immediately notify the sender by sending a reply e-mail to the sender. Thank you.

From: Hall, Rebecca L
Sent: Monday, August 9, 2021 11:47 AM
To: pnp/custom-learning-office-365 ***@***.******@***.***>>; pnp/custom-learning-office-365 ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [pnp/custom-learning-office-365] Learning Pathways content not rendering in Teams client (#569)

Hi Derek,

Thanks for your follow-ups.

I did upgrade to version 4.3.0.0 and that seemed to fix the issues.

Thanks,

Becca

______________________________________________
Rebecca Hall
Domain Architect - Collaboration
IT Employee Experience
Eversource Energy
860-665-3494
***@***.******@***.***>




The information contained in this e-mail and any files transmitted with it may be a confidential attorney-client communication or may otherwise be privileged and confidential.  If the reader of this message, regardless of the address or routing, is not an intended recipient, you are hereby notified that you have received this transmittal in error and any review, use, distribution, dissemination or copying is strictly prohibited.  If you have received this message in error, please delete this e-mail and all files transmitted with it from your system and immediately notify the sender by sending a reply e-mail to the sender. Thank you.
