### ISSUE TITLE
Content that is created or added in Subcategories does not appear on the training page

### ISSUE THREAD

**Issue by beatrizlourenco7** [pnp/custom-learning-office-365#571]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Submit your question
 I have been working with a customer with the Learning pathways app. Thank you for providing support on it. We were working on a customer environment and the app looks great. After provisioning the Learning Pathways on their environment, we are able to add custom content on the page but it's not appearing.. we have tried a couple of times in our CDX environments and it works like a charm. However, it doesn't work in the customer environment.  We checked permissions and it is all fine. Do you have the recommended environment policies that they need to have for not having this issue, please? [QUESTION] 

### What is the context of your question

- [ ] Installation
- [x] Learning Pathways Content
- [ ] SharePoint Success Content
- [ ] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### What is your question

>Provide related screen-shots to help us understand your question
Content that is created or added in Subcategories does not appear on the training page, only copied playlists.

**Comment by dcashpeterson** [comment]
@beatrizlourenco7 we will need some additional information to help troubleshoot this issue. Based on your response you are trying to add custom content to the page. It works in your development/integration environment but it doesn't work in the customer environment. Are there any errors showing up in the console? Can you share those errors. Have you gone through the custom content configuration instructions on the customer environment? https://docs.microsoft.com/en-us/office365/customlearning/custom_partnerguide_contint#content-pack-guidelines. Try those and feel free to get back to me with any additional questions or when you have errors in the console.

**Comment by beatrizlourenco7** [comment]
I followed the instructions, but there is no error that I can share, because it does not appear, but the client has some policies in the environment, do you think there is some policy that would affect the custom content? we can't list the policies here, because they're testing new policies in their environment and they would like to know which policies could affect the custom content.

**Comment by dcashpeterson** [comment]
We had an issue similar to this #545. Without any errors I can't really trouble shoot. There might be something in the network tab in developer tools. In the previous issue it was a networking issue where the URL was being blocked.

**Comment by beatrizlourenco7** [comment]
Hello again, I think maybe you didn't understand the issue, because I saw the issue you commented that was similar, I didn't find similar. 
I will explain a little better with screenshots.
So how you can see, in this screenshot there is a customized content subcategory with 2 playlists, the first is a Customized Playlist and the second is a copy playlist from Microsoft Teams subcategory. 
![image](https://user-images.githubusercontent.com/73603489/129759875-eea6bd73-0699-4741-abf7-6c7a855f8d1c.png)
When we go to see the playlists in the Customized Content Subcategory at the beginning of the site where the training is, it only shows the playlist copied from Microsoft Teams. I have done many tests, deleting and adding again and it only shows the playlist of copies from Microsoft subcategories.
![image](https://user-images.githubusercontent.com/73603489/129760111-e0919d38-26d7-4701-b517-5a23cce14212.png)
I also tested to add a custom asset to the copied playlist, as you can see here in this screenshot. 
There is an asset added with the name Customized Asset.  
![image](https://user-images.githubusercontent.com/73603489/129760746-4c223c73-1f06-4ab7-bc92-e4ee0be9a4af.png)
and again when we go to see the playlists in the Customized Content Subcategory in that playlist copied at the beginning of the training site, it doesn't show up.
![image](https://user-images.githubusercontent.com/73603489/129761156-9f5faf38-dc8f-4526-98c3-d501b0fd9fe6.png)
I also did some tests to try to change the photo of this copied playlist, and when I upload a photo to add to the playlist, it doesn't change, it only changes if it is one of the recommended photos in Sharepoint. 

I have tried to explain it as best I can, so if you have any doubts about my explanation, let me know, and I can try to explain it again. 
I thank you in advance for all your help.

**Comment by benoitfournier** [comment]
Is it in a multilingual installation? We just had a similar issue where the language from a sub-category was missing. We had the content but it was not showing in the alternate language.

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new issue and reference this one.
