### ISSUE TITLE
Cannot display content from docs.micorosoft.com

### ISSUE THREAD

**Issue by harshalgite11** [pnp/custom-learning-office-365#573]
I am unable to display content from _**docs.microsoft.com**_ on any of the pages. I have gone through past issues and added query strings to the URL as suggested in those issues but this did not solve my issue. Please check the details below:

### Steps To Reproduce

1. Add an asset to the playlist and enter a URL from docs.microsoft.com
For Example https://docs.microsoft.com/en-us/powerapps/powerapps-overview?context=context%2Fchromeless&linktarget=true&fromOrigin=https://ranosys0.sharepoint.com/
![PlaylistURL](https://user-images.githubusercontent.com/8374331/128702907-d9856f92-bb00-4be3-a72c-38570669a24e.PNG)

2. Display the playlist on a SharePoint Page

Screenshots of the issue are shown below

![Page](https://user-images.githubusercontent.com/8374331/128702923-010819f2-be44-45bd-9d40-adf1dba1b733.PNG)

![PageConsole](https://user-images.githubusercontent.com/8374331/128702929-88afa335-9634-4877-9810-1fb83da13b99.PNG)

### Learning Pathways version number

4.3.0.0

### Additional context

I face no issues while displaying from _support.microsoft.com_.

Can you please help resolve this issue or suggest any work arounds?

**Comment by dcashpeterson** [comment]
@harshalgite11 Thank you for reporting this and for giving great details. Unfortunately there isn't a whole lot we can do with this. The content in Learning Pathways is pulled in via an IFrame and the content on docs.microsoft.com doesn't always play nice with IFrames. I assume that you have already tried the tricks on #295. If you tried that there isn't much else I can suggest you try as it is a limitation of the content and not Learning Pathways.

**Comment by harshalgite11** [comment]
@dcashpeterson Thank you for your reply. Yes I have tried the tricks but it did not help. Is there a work around or some other URL to access docs.microsoft.com?

**Comment by dcashpeterson** [comment]
The tip outlined in #295 is the work around but it doesn't always work it really depends on how the content was created. It is an issue with the content not being allowed in an IFrame.

**Comment by dcashpeterson** [comment]
Closed as answered. If you are still having an issue please create a new issue.
