### ISSUE TITLE
Sharepoint app Microsoft 365 Learning Pathway removed and created again from lookbook- (CustomLearningAdmin.aspx still not working)

### ISSUE THREAD

**Issue by jasmarwaha** [pnp/custom-learning-office-365#574]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.
Hello,
	We had issue upgrading the M365 LP app which was created in 2019 with the first version of the application. It was recommend to delete the site completely and remove the solution from the app catalog and recreate the site from look book (http://lookbook.microsoft.com/ ) and upgrade teh solution to the latest version but we are still having error 
	
Background:
	1.	Backup the  Learning pathways site (version 2.1) – Site Contents and customization 
	2.	Deleted the Learning pathways site completely ( Reason for deletion – we wanted to keep the same URL)
	3.	Provision the New Site Learning pathways using look book ( http://lookbook.microsoft.com/ )  (version 4.1)
	4.	Upgraded the solution to the latest (4.3)
	5.	Restore the contents
	Site is up and running and functional but we are still seeing error message below on the “CustomLearningAdmin.aspx”.
	
Issue:
	error message: 
	Error: The value for "_manifest" must not be undefined
	in t in t in n in t in t in t in t in t in section in div in div in t in Styledt in t in n in t in t in t
	
Thanks a lot,
Jas

### To Reproduce

>Steps to reproduce the behavior

### Expected behavior

>A clear and concise description of what you expected to happen.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

4.3

### Additional context

>Add any other context about the problem here.

**Comment by dcashpeterson** [comment]
Hello @jasmarwaha,
The content schema changed from V2 to V4 to support multi-lingual capabilities. We provided support instructions for upgrading from V3 to V4 here. https://docs.microsoft.com/en-us/office365/customlearning/custom_update.

Based on the way you explained things my suggestion is that you delete what you have and reinstall the latest version. You can do that manually or via the LookBook. Don't restore the site contents and ensure that things work properly. You might need to recreate the site content to the new version or try moving individual pages that you need rather than restoring the entire site contents. If you need to do an incremental upgrade you could also try using previous builds of LP. https://github.com/pnp/custom-learning-office-365/tree/main/installation/Archive

**Comment by jasmarwaha** [comment]
Thank you for prompt reply. Can I create a test LP SharePoint site now that latest version is in app catalog just to test out the functionality before I plan to do the whole process again?
Will this work?

**Comment by dcashpeterson** [comment]
You can try creating a new test site side by side. They will both pull the same app from the app catalog so if you are running 4.3 things should be ok. Personally, if the other site if broken I would just delete everything and start again. This is also related to #563 for continuity sake.

**Comment by jasmarwaha** [comment]
Good Morning,
Can you please provide manual steps for creating test LP Sharepoint site blank using the app (4.3) from my app catalog which has (4.3)?

Regards,
Jas

**Comment by jasmarwaha** [comment]
Sorry I one more question . Can I create a blank SharePoint  site using communication template and add app from site contents will this work?

**Comment by dcashpeterson** [comment]
Here is a direct link to the manual install instructions. https://docs.microsoft.com/en-us/office365/customlearning/custom_manualsetup. If you have additional questions review the documentation here. It should answer your questions about setup and install. https://docs.microsoft.com/en-us/office365/customlearning/

**Comment by dcashpeterson** [comment]
Closed as answered. If you are still having an issue please create a new issue.
