### ISSUE TITLE
Learning Pathways App auto install on Teams

### ISSUE THREAD

**Issue by PamAm87** [pnp/custom-learning-office-365#579]
[ ] Installation

I am at the end of getting Learning pathways setup for our Tennant, I have it on SharePoint and loading in Teams but what i would like to do is have it auto install for all staff.  I am unsure how to go about this and on trying to look it up appear to be going in circles. 
At the moment the learning pathways app appears in Teams apps under "Built for your org" which a user can then click to add the app.
On Teams admin > Teams Apps > Manage Apps i have Learning Pathways Published and Allowed
                                                       Permission Policies - under Custom Apps - Allow Specific Apps and Block all others Learning 
                                                                                        Pathways is listed as allowed
                                                       Setup Policies > Global i have the learning pathways app listed under Installed Apps

I feel i have the settings all correct but maybe i am missing something obvious - if anyone could point me in the right direction i would greatly appreciate the help.

**Comment by dcashpeterson** [comment]
Closed as answered. If you are still having an issue please create a new issue.
