### ISSUE TITLE
Page scheduling, FirstPublishedDate = NULL, Page doesn't  display at top of Highlighted Content 

### ISSUE THREAD

**Issue by gfrick** [pnp/custom-learning-office-365#580]
When I setup approval and page scheduling in the SitePages library of the Microsoft Learning Pathways solution provisioned through the provisioning service. The page is published on the scheduled date, but the First Published Date column contains a null value so the page does not display at the top of the Highlighted Content web part. Is this a know problem? Is there a solution? I have bee setting the dates prior approval with powershell, but I am looking for a more automated process. Thanks - Greg

**Comment by gfrick** [comment]
@dcashpeterson - I posted here on the recommendation Premier Support.  While working with Support, scheduling + approvals worked as expected on two other non-SP provisioned sites.

**Comment by gfrick** [comment]
@sympmarc - Thanks. It certainly does walk like a bug and talk like a bug :-)

**Comment by dcashpeterson** [comment]
Closed as answered. If you are still having an issue please create a new issue.
