### ISSUE TITLE
Event category drop-down is grayed out on Events page

### ISSUE THREAD

**Issue by NancySkaggs2020** [pnp/custom-learning-office-365#584]
## Describe the bug

On our tenant's Learning Pathways site, the Category drop-down for our Events list is grayed out and does not function. This has never worked correctly since the site was set up over a year ago. 

### To Reproduce

Go to the Events page and observe the grayed-out Category drop-down

### Expected behavior
Category drop-down should allow selection of Event categories

### Screenshots

![Learning-Pathways-calendar-issues](https://user-images.githubusercontent.com/62143391/131694293-24ac5961-34e8-4a4f-a61f-c9cebf92dee7.jpg)

### Learning Pathways version number

4.3.0.0

### Additional context

This occurs regardless of browser and regardless of incognito mode

**Comment by dcashpeterson** [comment]
@NancySkaggs2020 Thanks for bringing this to our attention. I took a look at this and it looks like an issue with how the site was provisioned not with the Learning Pathways code. I was able to replicate it in one of my test environments. I assume that you provisioned this via the LookBook? If you did my suggestion would be to post it to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues) and see if you can get some insight there. If you didn't provision with the LookBook let me know.

**Comment by NancySkaggs2020** [comment]
@dcashpeterson - We did not provision via LookBook; we were led through the setup process with Microsoft folks alongside and AFAIK provisioned in the optimal manner.

**Comment by dcashpeterson** [comment]
Thanks for letting me know. In that case please don't post to the provisioning issues list. Can you replicate the issue if you create a SharePoint site without using Learning Pathways? Learning Pathways doesn't do anything with the Events list. I checked the content type when I could replicate it and it looks like it's an issue with the Events list and Events content type/ category site column. 

Can you provide details on the steps you followed to provision the site?

**Comment by dcashpeterson** [comment]
@NancySkaggs2020 I was able to replicate the issue but only when I provisioned the site from the LookBook and I encountered this issue #566. The good news is that issue is currently being worked on. This isn't an issue with the Learning Pathways web part unfortunately. You could try to delete and recreate the events list but the OOTB Events list template is no longer in the UI so you would probably need to do that with PowerShell.

**Comment by NancySkaggs2020** [comment]
I appreciate that update- I'll see what we want to do next. Thanks!
