### ISSUE TITLE
[QUESTION] - Content upgrade process for SharePoint Success Site

### ISSUE THREAD

**Issue by robertcaretta** [pnp/custom-learning-office-365#585]
## Submit your question
Is there an upgrade process for the SharePoint Success Site add-on content pack? In the event the playlists change, or additional content is available. 
- https://docs.microsoft.com/en-us/office365/customlearning/custom_contentupdates
- https://docs.microsoft.com/en-us/sharepoint/customize-sss

### What is the context of your question
- [ ] Installation
- [ ] Learning Pathways Content
- [x] SharePoint Success Content
- [ ] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### What is your question
Is there an upgrade process for the SharePoint Success Site add-on content pack? In the event the playlists change, or additional content is available. 
- https://docs.microsoft.com/en-us/office365/customlearning/custom_contentupdates
- https://docs.microsoft.com/en-us/sharepoint/customize-sss

**Comment by dcashpeterson** [comment]
@robertcaretta Are you asking what is the process for the content to be updated? We try to keep on a quarterly update schedule. We are a little behind. The last update to the content was in May of 2021. There is another one slated to come out in the next few weeks.

If you are looking for updates to the templates themselves we don't usually update those unless there is an issue with them. If there is something specific you are looking for feel free to make a request and we can put it on the list of enhancements to be triaged. 

Thanks,
Derek

**Comment by robertcaretta** [comment]
I was just wondering what the overall process is for the content add-on pack(s),  When a Learning Pathways update is released would that potentially also include updates for the SharePoint Success Site?  Or would updating that content be a separate process?

**Comment by dcashpeterson** [comment]
The content for all of the assets are updated quarterly. We are looking at a new release in a few weeks.

**Comment by dcashpeterson** [comment]
Closed as answered. If you are still having an issue please create a new issue.
