### ISSUE TITLE
Learning Pathways contents language not displaying the language selected in Delve

### ISSUE THREAD

**Issue by mort0pyro** [pnp/custom-learning-office-365#586]
Hello,

I've recently deployed a Learning pathways sharepoint site (multi-language) through lookbook, and am trying to get the learning contents to show in portuguese.
To achieve this, I've read that the Delve language setting for each user accessing the contents needs to be set to portuguese.
I've tried this on a test user and waited up to 24 hours to see the changes take effect, but as of now, I'm still seeing the contents in English.
Am I missing something? I've also tried to change the language on the user's Microsoft Account and browser for good measure, and clearing the cache, but am still not getting the contents in portuguese. Any help would be greatly appreciated!

Thank you!

SCREENSHOTS
Language setting on Delve
<img width="520" alt="language on delve" src="https://user-images.githubusercontent.com/88200309/133417850-833fbae2-3c11-4c93-b7ba-90ef86458a01.png">

Language displayed on my sharepoint site
<img width="907" alt="language on site" src="https://user-images.githubusercontent.com/88200309/133418614-2bf80ecd-aeb4-430b-9875-b07595157538.png">

Language settings on the Microsoft Account
<img width="757" alt="Language in microsoft" src="https://user-images.githubusercontent.com/88200309/133419262-1f8e49c4-5bef-482b-a777-20cdd992a7a2.png">

Language on the browser
<img width="691" alt="Language on browser" src="https://user-images.githubusercontent.com/88200309/133419414-73fef48f-2bb6-4740-beb7-e822111fb756.png">

**Comment by dcashpeterson** [comment]
@mort0pyro Are you able to get this to work with other languages in the Delve profile? The reason I am asking is that your language is set in Delve to Portuguese (Portugal) which is the language code PT-PT. The playlists in Learning Pathways is translated to Brazilian Portuguese which is PT-BR. See what happens if you change your language in Delve to Brazilian Portuguese. I tried this in my environment and I was able to get it to display PT-BR. Unfortunately, Learning Pathways doesn't support Portuguese for Portugal right now.

**Comment by mort0pyro** [comment]
@dcashpeterson, thank you for your feedback!
I've made the suggested changes, and now have Portuguese (Brasil) as the chosen language in Delve. But it still hasn't changed the language of the contents. I will wait a few hours to see if this helps, as it might take some time for the language settings to take effect.
I'll get back to you as soon as possible.

**Comment by dcashpeterson** [comment]
It does take an hour or two for the changes to take affect on the language. Another thing to check is the see if you can get to the admin screen.  https://<yoursite>.sharepoint.com/sites/<Yoursitecollection>/SitePages/CustomLearningAdmin.aspx. This will reset the cache and make sure you have the latest version of the cached date. But I think it is most certainly an issue with pt-pt vs pt-br.

**Comment by mort0pyro** [comment]
@dcashpeterson , I can confirm my contents are now in portuguese, this worked perfectly. 

Thank you very much for your help!
