### ISSUE TITLE
Stream not display properly within the Custom Learning webpart in IE

### ISSUE THREAD

**Issue by reginaju** [pnp/custom-learning-office-365#59]
#### Category

- [ ] Question
- [ ] Typo
- [ X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Creation of custom article which is a page containing the Stream webpart configured to display a single video should display the selected video

#### Observed Behavior

For everyone but me, the webpart displays with with the following text in IE. (see attached screen shot)
![screen shot](https://user-images.githubusercontent.com/50672675/57792350-cb8f7480-770c-11e9-874a-523a161064bf.png)

                                  Microsoft Stream
                             To see this content, sign in
                          New to Microsoft Stream? Sign-up
For me, the owner of the Stream content and the site, it displays fine in IE.  For everyone it displays fine in Chrome.

#### Steps to Reproduce

Create a new page
Add Stream webpart configured for a single video
Save page
Add the created page to a playlist
Add playlist to a page
View page in IE, have others with read only access to the Stream channel and Sharepoint site view the page in IE

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by juliemturner** [comment]
To verify, the page that has the stream video on it, if the user's try and view that page directly IE 11 they get the same issue, correct?

**Comment by juliemturner** [comment]
Closed due to lack of response.
