### ISSUE TITLE
Updating the site page customlearningadmin.aspx received 2 errors 

### ISSUE THREAD

**Issue by Jeepster1107** [pnp/custom-learning-office-365#591]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.
>**Customerlearningadmin.aspx log errors**: 2 errors in the site page update logs

## Describe the bug

In the app catalog site collection the learning package was successful in updating to the newest 4.3 version. Then went to site content app and was successful in the "Get it" update. Then went to Site Pages library to run the Data Upgrade, in the Upgrade Logs there was 2 errors:
1. Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"The type SP.ListItemEntityCollection does not support HTTP PATCH method."}}}

2. 🎓 M365LP:undefined (modifyConfig) - Error: Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"The type SP.ListItemEntityCollection does not support HTTP PATCH method."}}}

### To Reproduce

Ran through these steps twice and both times got the same 2 errors.

### Expected behavior

Excepted results was to receive no errors

### Screenshots
![LearningPathways-ErrorUpdateLog](https://user-images.githubusercontent.com/20136049/134528601-5527fa13-5eec-4489-a7b4-5fc2dbf6f516.PNG)

added screenshot.

### Learning Pathways version number

4.3.0.0

### Additional context

>Add any other context about the problem here.

**Comment by dcashpeterson** [comment]
@Jeepster1107 This is an issue with the cache during the upgrade. It looks like something failed in the middle. The upgrade is meant to be run more than once. You can try running that again and see if that fixes the issue. If it doesn't, then my best advice would be to go to the CustomConfig list and delete all the CustomConfig items. Be sure to ONLY delete the CustomConfig ITEMS in the list and then go to the https://<tenant>.sharepoint.com/sites/<site>/SitePages/CustomLearningAdmin.aspx 

This should regenerate the cache.

**Comment by dcashpeterson** [comment]
Closed as answered. If you are still having an issue please create a new issue.
