### ISSUE TITLE
[ENHANCEMENT] Hide Social bar when content comes from SharePoint

### ISSUE THREAD

**Issue by benoitfournier** [pnp/custom-learning-office-365#592]
If we include custom content from a SharePoint page, there will be 2 social bars on the page. One from the container and one from the content.

 
![image](https://user-images.githubusercontent.com/49032965/134585280-76d66e18-c45e-4c8e-9ef4-a73a9a647d20.png)

Since we cannot control that social bar per pages, there should be a way prevent the webpart to display it for content pages. That way, it would lokk the same no matter if it is coming from Microsoft or from us.

A switch on the webpart properties would be a good implementation..

**Comment by dcashpeterson** [comment]
@benoitfournier sorry for the delay on this one. Unfortunately, this isn't something that is possible with the endpoints we have available today. There is not a pages API so we can't show or hide comments on a page by page basis client side. It can be turned off via PowerShell on a site by site basis so if you have custom assets you are creating in SharePoint you could create those in a single site collection and turn off. Here is the link if you need it. https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpsite?view=sharepoint-ps
