### ISSUE TITLE
Hello Team, what URLs need to be whitelisted for the above learning pathways solution to work ?

### ISSUE THREAD

**Issue by margot-eva** [pnp/custom-learning-office-365#594]
Hello Team, what URLs need to be whitelisted for the above learning pathways solution to work ?

_Originally posted by @rhajj19 in https://github.com/pnp/custom-learning-office-365/issues/344#issuecomment-736518812_

**Comment by v-harishd** [comment]
Hi @margot-eva,
Below  Urls need to be whitelisted
https://pnp.github.io
https://support.office.com/
https://docs.microsoft.com
