### ISSUE TITLE
 Cannot add new custom Subcategory

### ISSUE THREAD

**Issue by alxjtlTE** [pnp/custom-learning-office-365#595]
## Describe the bug
If I try to add a new custom scenario subcategory nothing happens after clicking on the save icon. 
There is no error, just nothing will be added. 

In debugging mode it shows after clicking the save icon for the subcategory:
![m365lp](https://user-images.githubusercontent.com/92087382/136360519-62b277fd-1f1f-4d08-b55a-e3c4f9d34810.jpg)

The user is in the list of "Microsoft 365 learning pathways Owners". 
Is there any additional permission necessary or could any other policy interfere?

### Learning Pathways version number
Version 4.2.0

**Comment by dcashpeterson** [comment]
@alxjtlTE in looking at the logs you provided it looks like you are getting an access denied error on the CustomConfig list. Can you check the permissions on that list for the user or users that are having the error? Does this error for all users or just some users?

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
