### ISSUE TITLE
Custom Learning Webpart fails to size properly

### ISSUE THREAD

**Issue by reginaju** [pnp/custom-learning-office-365#60]
#### Category

- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Text does not get cutoff based on the sizing percentage chosen on the browser. 

#### Observed Behavior

When using Chrome, the amount of content displayed within the Custom Learning Webpart varies based on browser sizing.  At 100% the bottom of letters are cut off.  Any other %, as well as IE, appear to display fine. 

See screen shots of two different sizings of the same content
![bad](https://user-images.githubusercontent.com/50672675/57792902-18277f80-770e-11e9-80ed-7a8f4e0fb728.png)
![good](https://user-images.githubusercontent.com/50672675/57792910-1b227000-770e-11e9-856a-01a7f57a72c0.png)

#### Steps to Reproduce
1. Create a page
2. Add an embbeded web part using the following code
<iframe src="https://support.office.com/en-us/client/meetings-and-calls-d92432d5-dd0f-4d17-8f69-06096b6b48a8?ui=en-US&amp;rs=en-US&amp;ad=US#ID0EAABAAA=Set_up_a_meeting&#10;&amp;embed=true&amp;ns=trainingservices&amp;version=1" style="border:0px #ffffff none;" name="myiFrame" scrolling="no" frameborder="1" marginheight="0px" marginwidth="0px" height="100%" width="600px" allowfullscreen=""></iframe>
3. Save page
4. add this page to a playlist
5. Add playlist to a page and view page using Chrome at 100% and 110% to notice how the link to "Whiteboard" is missing the bottom part of its letter when viewed at 100%

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by juliemturner** [comment]
We cannot reproduce this issue and it's not an issue with custom learning.
