### ISSUE TITLE
[QUESTION] Admin Success Center > What's New playlist not updated. How should we do that?

### ISSUE THREAD

**Issue by harmsze** [pnp/custom-learning-office-365#600]
In the category 'Adoption tools' we have a subcategory 'Admin Success Center' with a playlist called 'What's New, What's Changed'. This is standard content. This playlists contains assets explaining what was updated. 

I expected new updates to be displayed in new assets in this playlists.
However, the newest asset is 'September 2020 content update', and I do not see any more recent content in this standaard playlist. Should we do something specific to get the info on the new updates in this  playlist?

![AdminSuccessCenter-WhatsNew-OnlyOld20211026](https://user-images.githubusercontent.com/76995147/138908858-269cc155-b354-429c-b27c-db02b7989e95.png)

![AdminSuccessCenter-CustomLearningAdmin-WhatsNew](https://user-images.githubusercontent.com/76995147/138908993-27b31488-eb76-4d0c-a903-ecf238ab2b64.png)

The app has been updated in July and now has version 4.3.0.0. 
![M365LP-AppDetails20211026](https://user-images.githubusercontent.com/76995147/138908797-5a273bfb-7fa1-445a-94fd-6d3950b470ff.png)

I do see some new assets that appeared in other standard playlists (e.g. MS Teams > Create Approvals >  Create org-wide templates. A colleague gave me a URL with more up-to-date information about the updates and that was mentioned as a new asset https://docs.microsoft.com/en-us/office365/customlearning/custom_contentupdates). 

But I do not see any new content in Admin Success Center.
To be sure: new assets should appear in standard playlists, right?
Not just when you update the app itself, but any time Microsoft updates the content?

![AdminSuccessCenter-CustomLearningAdmin](https://user-images.githubusercontent.com/76995147/138909037-ec49c28d-1200-4d0d-a806-c1bca0d83627.png)

**Comment by dcashpeterson** [comment]
@harmsze the Success Center What's Updated content has been updated.
