### ISSUE TITLE
[QUESTION] Removing Leaning Pathways

### ISSUE THREAD

**Issue by eiNetwork** [pnp/custom-learning-office-365#601]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Submit your question
We're planning the installation of Learning Pathways for our tenant.    If we decide not to use Learning Pathways and we abandon it, is there a way to remove it from the tenant entirely?     Do we just delete the site collection?

### What is the context of your question

- [X ] Installation
- [ ] Learning Pathways Content
- [ ] SharePoint Success Content
- [ ] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### What is your question

>Provide related screen-shots to help us understand your question

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
