### ISSUE TITLE
Error "Exception while invoking endpoint" when trying to provision from Lookbook service

### ISSUE THREAD

**Issue by glblinck** [pnp/custom-learning-office-365#603]
We are running into an issue creating a Learning Pathways site from the Lookbook service. This comes up even before filling out the form for naming the LP site. The error message is "Exception while invoking endpoint https://graph.microsoft.com/v1.0/sites/root." Any idea on the cause? It's a global admin account being used for the deployment.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/61463212/140396539-b89da8a8-0b83-4f7b-96cb-b5ad8e1ec5cc.png)
 
Seems others have had a similar issue: https://github.com/SharePoint/sp-provisioning-service/issues/411

**Comment by dcashpeterson** [comment]
Hi @glblinck, thanks for using Learning Pathways. As you pointed out this is most likely an issue with the Provisioning service based on the link to the issue there. It looks like the Provisioning team is working on that. We work closely together so if there is an issue with the template they will let us know and we can resolve it but it is not something that is Learning Pathways related. I would follow that issue and see what the resolution is there. I am going to close this issue but if you have any questions about Learning Pathways feel free to raise an issue here.

**Comment by glblinck** [comment]
Odd thing. Changing the site permissions to the home site got this working. The call to /sites/root would go to the home site, so this is what fixed the problem. If the installer doesn't have permission to the home site, this is the failure. It's unlikely unusual as the home site would generally have everyone as site visitors, at least. But if the admin account doesn't have any permission to the home site, this seems to be how it fails.

**Comment by dcashpeterson** [comment]
Great. I'm glad that worked. The install account does need to be a global admin so if it didn't have access that makes sense. Thanks for sharing the solution.
