### ISSUE TITLE
 Issue when updating from 4.1.4 to 4.3.0 - webparts not updated

### ISSUE THREAD

**Issue by J-Liner** [pnp/custom-learning-office-365#604]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

After updating the latest version from 4.1.4 to 4.3.0, I am getting an error information in the CustomLearningAdmin.aspx page that the verion is not latest. When looking at the content packs, the latest updates are not there for 2021. The appcatalog package has been updated and published. The information about the webparts in the CustomLearningAdmin.aspx still shows as 4.1.4, but the app on the site shows 4.3.0 with no ability to get the latest content or update

### To Reproduce

Run all pre-reqs and install 4.1.4.
Install package 4.3.0

### Expected behavior

Webpart version is updated, and the latest content is available

### Screenshots

![image](https://user-images.githubusercontent.com/93741138/140425847-0030afce-c24f-4e7c-ac98-7cf9820c38b3.png)
![image](https://user-images.githubusercontent.com/93741138/140425896-c2846c21-e412-498d-9340-0a9e3e80b90e.png)

### Learning Pathways version number

4.3.0

**Comment by dcashpeterson** [comment]
Hello @J-Liner, If you could check a few things it would be helpful. 1) Can you check in the App Catalog where you installed the new SPPKG file that there were no errors. 2) When you go to the CustomLearningAdmin.aspx page do you get any error in the browser console or on the screen other than the upgrade message? If there are errors in the console please provide those. You may also want to try updating the cache. You can do this by deleting the entries in the CustomConfig list. Let me know what comes up.

**Comment by J-Liner** [comment]
@dcashpeterson really appreciate the quick response. I've been looking into your suggestions, and here is what I have so far.

- The SPPKG didnt have errors when installing/publishing
- The CustomLearningAdmin.aspx page loaded without errors (validated through F12)
- I am trying to clear our the CustomConfig list, but I keep getting an error when loading the page. 
 
I'll post back once I get the CustomConfig list sorted

**Comment by J-Liner** [comment]
@dcashpeterson really appreciate the quick response. I've been looking into your suggestions, and here is what I ahve so far.

- The SPPKG didnt have errors when installing/publishing
- The CustomLearningAdmin.aspx page loaded without errors (validated through F12)
- I am trying to clear our the CustomConfig list, but I keep getting an error when loading the page. 
 
I'll post back once I get that sorted

**Comment by J-Liner** [comment]
I was able to clear out the CustomConfig list, and it repopulated. The JSON was interfering with the page load, possibly too much content for a list entry. I created a new list view, and removed the column. Clearing the list did not resolve the version issue.
Additional things I've tried:

- re-installed the app (cleared the recycle bin just in case).
  - Validated` App Instances details that the app installed correctly with the right version
- forcing an update using "SitePages/CustomLearningAdmin.aspx?forceUpdate=v3"
- Validated the CDN, and Site URL tenant properties (still correct)
- Validated properties stored on the site
  - App installed for Microsoft 365 learning pathways. InError: False
  - _PnP_ProvisioningtemplateInfo {"TemplateId":"CUSTOMLEARNING","TemplateVersion":0.0,"TemplateSitePolicy":null,"ProvisioningTime":"2021-09-23T04:24:08.7145208+00:00","Result":true}

I still cannot find where the CustomLearningAdmin.aspx is pulling the "Current Web Part Version" from the image above.
The major problem is that the content is only through Sept 2020. I dont know that fixing the webpart version will resolve that issue.

**Comment by dcashpeterson** [comment]
@J-Liner you have definitely checked all the things I would have asked you to check. It sounds like there are a few issues here. 1) the webpart version number doesn't seem to be updating and 2) the content isn't getting picked up. Let's tackle number 2 first. Check if you have the following playlist https://<yourtenanthere>.sharepoint.com/sites/<Yoursitehere>/SitePages/CustomLearningViewer.aspx?cdn=Default&playlist=479705db-2e50-4a8b-8a2e-a2a3d59ce61b&asset=8c923c9d-4ef2-849d-a399-4de716ecbbaf That was part of the latest update. Unless you are using a custom content pack that is a copy of the previous version you should get the updates automatically. There is an issue we are working through with the Success Center that hasn't been updated but the rest of the playlists have.

For number 1, the webpart version is stored in the webpart manifest but also in the customconfig list. Look at the entry in there. You can use the network tab and look for WebPartVersion. My guess is that there was an issue in the update and something errored out.

Try that and let me know what you see.

**Comment by J-Liner** [comment]
The playlist above did load:
![image](https://user-images.githubusercontent.com/93741138/141011672-285534fa-024b-455f-b714-93a2c67dff8e.png)

I had cracked open the SPPKG earlier to validate we had the right package (sometimes that happens), and it is indeed the Version="4.3.0.0". I didn't see an entry for updating the app package but that isn't necessarily required.
The CustomConfig JSON is outside the boundry for the field at 32k characters. Inspecting the JSONData field looked well formed, and the site is working so that isn't the problem. Do you want me to include the config value here? it is really long.

Viewing network/console there were several CORS errors when view the webpart.
The Admin page always loads clean.
From the CustomLearningViewer.aspx link above:
![image](https://user-images.githubusercontent.com/93741138/141015528-36d980b0-7673-427f-b3a7-73087fd72549.png)


From work-remotely.aspx:
![image](https://user-images.githubusercontent.com/93741138/141015495-8c7dd10c-d7e6-4c14-9a0c-abc3cf8b2caa.png)

**Comment by J-Liner** [comment]
The webpart is loading just fine. I couldn't find the version number in its response. What I did find is that there are old resources from previous versions in the client side assets for the app. Maybe that is related?
![image](https://user-images.githubusercontent.com/93741138/141017718-ced195a5-7fbb-4b99-abcf-d798c8b69182.png)

**Comment by dcashpeterson** [comment]
@J-Liner I need to do some more digging into the code. I will let you know what I find out.

**Comment by dcashpeterson** [comment]
@J-Liner The web part version gets set through the manifest of the webpart. When the webpart loads on the page the manifest for the webpart is loaded into the context of the page. The admin webpart retrieves that value from the context and puts it in the cache. What you are seeing in the Client Side Assets library are indeed old file and those are not the current files. This leads me to believe that there was an error when the webpart was installed. Have you tried updating the sppkg file in the app catalog already? If the update was successful you would see files named m365LPString_en-us-GUID.js. If you haven't try that and check the console while you are doing it. Are you using a site collection app catalog or the tenant app catalog?

**Comment by J-Liner** [comment]
@dcashpeterson I did not try re-installing/republishing through the app catalog because I dont have permissions for that. I'll get that done today and post back the findings.

**Comment by dcashpeterson** [comment]
@J-Liner Did you get the web part reinstalled and did that resolve the issue?

**Comment by J-Liner** [comment]
@dcashpeterson Still working on getting a GA. Just responded to an email 5mins ago.

**Comment by J-Liner** [comment]
@dcashpeterson We were able to redeploy the package, and the assets are now correct. The admin page is referencing the old webpart now. Will fix that and post an update

**Comment by dcashpeterson** [comment]
@J-Liner I am going to go ahead and close this. If this is still an issue feel free to open a new issue and address this one.
