### ISSUE TITLE
[QUESTION] When does new content become available?

### ISSUE THREAD

**Issue by harmsze** [pnp/custom-learning-office-365#605]
I am looking for up-to-date content, in particular on Viva Insights. 

1. Do you know when the content about Insights will become available? 
I thought it would be there after Ignite, but I do not see it. I only found this, and this asset does not work well in a playlist: https://support.microsoft.com/en-us/office/viva-insights-in-teams-436b9928-5867-433a-abd5-188e0262e5e3

2. How does the "content updating" work? 
I've heard there is a quarterly update. Is the catalog of the assets you can find inside M365LP updated quarterly from content that was already made available on https://support.microsoft.com ? And does Microsoft keep https://support.microsoft.com up to date continuously, or is there some rhythm as well?

**Comment by amitkh22** [comment]
Hello @harmsze, Please allow me sometime to get answers for your queries, I'll update you at the earliest. Thank you for your patience.

**Comment by harmsze** [comment]
Thank you @amitkh22 !

**Comment by dcashpeterson** [comment]
assigning to @peterjkrebs for answers on content.

**Comment by robertcaretta** [comment]
I see there is documentation stating there is new content for September, however the latest release v4.3 appears to be from June.
https://docs.microsoft.com/en-us/office365/customlearning/custom_contentupdates
https://github.com/pnp/custom-learning-office-365/tree/main/installation

**Comment by harmsze** [comment]
So content becomes available on a quartely basis? And that applies to both the catalog within M365LP and the underlying website  support.microsoft.com?
Any idea when the new "wave" will arrive? December maybe?
I am missing a lot of content: Viva Insights in Teams, and things like presenter modes, emoticons and thing in Teams Meetings...

**Comment by dcashpeterson** [comment]
@harmsze and @robertcaretta, The content is updated quarterly and was last updated at the end of September 2021. We are currently working on the updates for this quarter. We are working on defining what content will be added and when that release will happen but it should be before the end of the year. If you are using the learning pathways CDN for your content you should get all the updates automatically. 

@robertcaretta The webpart has not been updated past V 4.3.0. I am working on some bug fixes for issues and when I have critical mass of issues that are fixed I will roll out an updated webpart release and update the version.  

I hope that helps.

**Comment by harmsze** [comment]
Thanks @dcashpeterson! So it is no use me searching support.microsoft.com for the required content, to add it manually as an asset before the end of the year, is there?
And is there a place where we can vote on or suggest content additions? If that is the case, I will get to it rightaway :-)

**Comment by dcashpeterson** [comment]
@harmsze if you see content on support.microsoft.com that is not in our content pack you can certainly try to add it. Keep in mind that some of the content on docs and support isn't allowed to be Iframed by the source. This is true for support content as well as other sites on the internet. This is a browser security limitation not a learning pathways issue. You can try to add this to the url ?context=context%2Fchromeless&linktarget=true. If you are using multiple languages you would also be responsible for providing the translations. So it's possible, just a lot more work and if that content is added to the repo in the future you might have duplicates so you would have some clean up.

**Comment by harmsze** [comment]
Yes @dcashpeterson, I have added quite a few assets manually from support.microsoft.com. Is that site still getting updates earlier than the quarterly updates of the M365LP catalog/content pack?

I use the following this recipe:
• Replace microsoft in the root url with office
• Replace client after the language with office
• Just include the article GUID, not the title
• Add at the end ?embed=true
• For the Dutch version, replace en-us with nl-nl
For example: 
https://support.microsoft.com/en-us/office/poll-attendees-during-a-teams-meeting-9923b7d4-ea97-4aa2-b8b8-b45fefe7d454 becomes
https://support.office.com/en-us/client/9923b7d4-ea97-4aa2-b8b8-b45fefe7d454?embed=true

So if I cannot find some specific urgent info in the catalog within M365LP, I search support.microsoft.com. 
However I could not find what I was looking for there either :-( Specifically, details on Insights in Teams (there is only a startpage).
And yes, I have just done some clean-up: replace a manual version of an asset by the standard catalog version :-).

**Comment by dcashpeterson** [comment]
If that process is working that is great. I don't have any visibility into the timeline that folks update content on support or docs so I can't comment on when they do their updates. Sorry, I can't me more helpful on that front. Thanks for using learning pathways.

**Comment by harmsze** [comment]
ok, thanks @dcashpeterson ! Sometimes it is a bit of a puzzle, but nevertheless: I am happy with Learning Pathways :-)
