### ISSUE TITLE
 Display issue in playlist selector when webpart embedded in other pages

### ISSUE THREAD

**Issue by nmtoblum** [pnp/custom-learning-office-365#606]
## Describe the bug
We use the "Learning Pathways" web part in other site collections to embed playlists in pages. That works very well, but in recent versions of the pathways the playlist selector has display issues (transparent background), especially in full screen mode.

### To Reproduce
Add the "Learning Pathways" web part to another site collection (tested with communication sites) and add it to a site page, configure it to display a playlist. Publish the page and open the full screen mode. Check how the playlist selector is displayed.

### Expected behavior
Items of the playlist selector should be readable. The selector should have a background color.

### Screenshots
![image](https://user-images.githubusercontent.com/57751598/140963701-64024169-36bb-4d12-9466-196f92af9bf0.png)

In full screen mode it looks like this:
![image](https://user-images.githubusercontent.com/57751598/140963901-3640bd1d-507d-4c9e-8e53-fcc6afe4d4a6.png)

### Learning Pathways version number
Tested with latest 4.3.0, did not happen with 4.1.x

### Additional context
Let me know if there is anything missing in my description.

Thank you in advance for your help!  
Tobias

**Comment by amitkh22** [comment]
Hi @nmtoblum, Thanks for submitting this issue. Please allow us sometime to investigate. We'll get back to you at the earliest. Thank you for your patience.

**Comment by dcashpeterson** [comment]
@nmtoblum Thanks for brining this to our attention. I have released an update to this today. You can update the webpart to version 4.3.1 https://github.com/pnp/custom-learning-office-365/blob/main/installation/customlearning.sppkg

**Comment by dcashpeterson** [comment]
Closed, Fixed

**Comment by nmtoblum** [comment]
Great! Thank you for getting this fixed so fast. We'll test it out soon.

Greetings,
Tobias
