### ISSUE TITLE
The search only finds content from standard playlists now?

### ISSUE THREAD

**Issue by harmsze** [pnp/custom-learning-office-365#607]
The search only finds content from standard playlists now?
I searched some information via the search option inside the M365LP web part and I got no results. However, I saw the search term "manually" in the asset. See the attached screenshots.
![M365LP-Search-Privately-ann](https://user-images.githubusercontent.com/76995147/141460043-3f3d9e00-48b8-46bf-9f48-bf540f56c351.png)
![M365LP-Search-Reactions-ann](https://user-images.githubusercontent.com/76995147/141460494-f13e6ac4-5c20-4eac-84b1-4fdaabce8dac.png)

- These are standard assets, from the content pack/catalog inside M365 LP
- These standard assets are included in custom playlists.
- The search does seem to find content in standard playlists
- I am convinced that previously I was able to find information from custom playlists, although I cannot prove it now. 

Was something changed on purpose, to exclude content in custom playlists? Or is it broken...?

**Comment by v-saikirang** [comment]
Hi @harmsze,

Please allow us some time. We will look in to your query and get back to you at the earliest.
Thanks.

**Comment by dcashpeterson** [comment]
@harmsze The search for learning pathways only searches the metadata that it knows about for each asset or playlist. This means that it can only search within the title, description or other metadata when you create a playlist or custom asset. All assets are Iframed into the page so learning pathways doesn't know about the actual content just the metadata attached to it. Try adding some keywords to the playlist or asset title and it should show up in the search.

**Comment by harmsze** [comment]
Aha I misunderstood what the M365LP search can do - I probably just got lucky in the past... I thought the search could tie into an index of these Microsoft materials somehow...
So even for standard assets in standard playlists, the M365LP search cannot see the content, but only the following metadata:
ASSET
- Title of the asset, 
- Technology label of the asset
- Maybe the URL of the asset? 
PLAYLIST
- Title of the playlist
- Description of the playlist
- technology label of the playlist
- Category label of the playlist
- and maybe the Level and Audience of the playlist.
- We can NOT add keywords in a hidden field, like the metadata in SharePoint.

Is that correct @dcashpeterson ? 
Tricky... Because the users' ability to find the relevant content is key. Can I submit a request or vote for it in the way we could vote in uservoice, so that hopefully somebody can come up with a clever solution for this problem?

**Comment by dcashpeterson** [comment]
@harmsze  It will search the title and technology of the asset, title, description, and technology of the playlist but not any hidden keywords. The application doesn't know anything about it. If you would like to make a feature request here for custom keywords we can put it on our list but I can't promise any type of timeline. This is an open source initiative now so if you or someone you know would like to contribute that type of functionality we will certainly review the pull request. Unfortunately, we can't index the contents of the assets as we would have no way of reading that data or storing that information.

**Comment by harmsze** [comment]
Thanks for the clarification @dcashpeterson ! I will do a feature request like you described. That seems to be a feasible way of making the content easier to find. I am very untechnical myself, so I cannot develop it. But I will try to be a specific as possible in the request. And yes I know, I can do a request, but not demand a quick solution. I can only hope that someone can add this functionality...
