### ISSUE TITLE
Images for Office 365 Training

### ISSUE THREAD

**Issue by MichaelMontMoore** [pnp/custom-learning-office-365#61]
#### Category

- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Product images are not displaying on our deployed solution.  They were at one time, but now they are not.  For example, the Outlook training icon appears to point to this location:  https://pnp.github.io/custom-learning-office-365/v2/images/categories/outlook_training.png 
but the page is not available and as a result, the image is not displayed on the site.  I am seeing this for Outlook, Word, Excel, PowerPoint, Office 365, Forms and others.  However, after deployment, these images rendered fine.
[CustomLearningImages.docx](https://github.com/pnp/custom-learning-office-365/files/3188290/CustomLearningImages.docx)

**Comment by juliemturner** [comment]
@MichaelMontMoore -- I'm not seeing this issue elsewhere.  What might be happening is that you have some sort of network policy or other firewall issue that is blocking the download of those files?  Can you validate in your browser's developer tools, network tab (Img filter), what the status of those files are.  You may want to either disable, or clear your browser cache as well.  I've attached a screen shot from Chrome to show what I mean.
![ImagesLoading](https://user-images.githubusercontent.com/7570936/57929626-cd2e7900-7881-11e9-898e-82f79f9856a4.png)

**Comment by MichaelMontMoore** [comment]
Thanks.  I believe it is a network policy or GPO setting somewhere because it works fine "off" network, using the same machine/same browsers.  What's odd is that some staff on my team do not have the problem when on the network, while others do.  Clearing cache did not resolve.

**Comment by juliemturner** [comment]
I have seen this very same behavior in various organizations I've worked with. I believe you're going to have to discuss the issue with your IT department.  Sorry I can't be of more assistance.
