### ISSUE TITLE
[ENHANCEMENT] Allow LearningPathway to access docs.microsoft.com

### ISSUE THREAD

**Issue by hhmaity** [pnp/custom-learning-office-365#613]
**Is your feature request related to a problem? Please describe.**
There is some excellent information in docs.microsoft.com that we would like to be able to add as page in custom playlists, for example, the Teams Limitation ( Chat, meetings etc.. ) is hosted on this link https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams . When we try to add this link as a page in a playlist we get the error "docs.microsoft.com refused to connect"

**Describe the solution you'd like**
Allow the LearningPathway Webpart to connect to docs.microsoft.com

**Describe alternatives you've considered**
Copying and pasting information from the docs.microsoft.com pages and creating custom page ( has to be maintained if there are changes from Microsoft )

**Additional context**

![image](https://user-images.githubusercontent.com/56085301/145268720-a1dbb118-1efb-4c87-8c94-36cd80f2603d.png)

**Comment by amitkh22** [comment]
@hhmaity Thank you for reporting this and for giving great details. Unfortunately there isn't a whole lot we can do with this. The content in Learning Pathways is pulled in via an IFrame and the content on docs.microsoft.com doesn't always play nice with IFrames. You can have a look on #295 . If you already tried that, there isn't much else I can suggest you to try as it is a limitation of the content and not Learning Pathways.

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new issue.
