### ISSUE TITLE
[QUESTION] When & where new content update?

### ISSUE THREAD

**Issue by harmsze** [pnp/custom-learning-office-365#619]
I was expecting the quarterly content update, new content for Microsoft 365 Learning pathways, in December 2021, with an overview of what's new on https://docs.microsoft.com/en-us/office365/customlearning/custom_contentupdates. However, on that page the latest content update I see so far is September 2021. 

- Has new content, after September 2021, been made available and am I looking in the wrong place?
- Or has the update been delayed? Does anybody know when the update will become available?

**Comment by dcashpeterson** [comment]
@harmsze you are correct the last quarter is a little delayed due to holiday schedules. We are working on getting that out as soon as we can. Thanks for the reminder. I will leave this here as an open issue I can update so you get notified.

**Comment by harmsze** [comment]
Thank you @dcashpeterson !

**Comment by harmsze** [comment]
Hi @dcashpeterson! Any idea when we might expect the content update? I am trying to determine if I can wait for that update or if I should create my own custom content on what we're missing. And of course I prefer to use your playlists ;-)

**Comment by dcashpeterson** [comment]
@harmsze The update was delayed due to illness so it is a bit on hold. Right now the content updates that are coming are more based on updates to OneNote content. If there is specific content you need then I would suggest that you create custom content to fill that gap. We are looking for our next update after this one to have some Viva related content but that is still being worked on.

**Comment by harmsze** [comment]
Thanks for the update @dcashpeterson ! I will do that.... 
By the way, talking about Viva: the content in docs.microsoft is quite nice. Just not in the right format to embed it inside M365LP. https://docs.microsoft.com/en-us/viva/insights/personal/teams/viva-insights-protect-time and associated pages.

**Comment by dcashpeterson** [comment]
The latest content update was merged. Closing.
