### ISSUE TITLE
[QUESTION] SharePoint Page Style to Match Custom Content pages to Learning Pathways 

### ISSUE THREAD

**Issue by KRReilly** [pnp/custom-learning-office-365#622]
### SharePoint Page Style to Match Custom Content pages to Learning Pathways 
- [ ] Installation
- [ ] Learning Pathways Content
- [ ] SharePoint Success Content
- [ ] Administration
- [x] Custom Content
- [ ] Viewer Web Part

**Comment by amitkh22** [comment]
Hi @KRReilly, Learning pathways just pulls the content from the source and displays it in the iFrame. There isn't any custom styles that is getting applied. If you want to style your pages, you may need to use SPFx application customizer to style them. There isn't any out of the box way to add the CSS file to the pages.
Please let me know if I answered your question.

**Comment by KRReilly** [comment]
Thank you, I believe what we are looking for is not available using the SPFx application customizer.

**Comment by dcashpeterson** [comment]
@KRReilly could you provide a screen shot of what styles you are trying to change and to what? A picture with arrows is fine. That way we can better assist. As @amitkh22 mentioned the content styling comes from the source (support.microsoft.com) but if it's something else on the page maybe we can point you in the right direction.

**Comment by amitkh22** [comment]
@KRReilly, please let us know if we can close this issue or do you need any other inputs from us?

**Comment by KRReilly** [comment]
@dcashpeterson @amitkh22 apologies for the delay - please see the annotated screenshots below of the Github linked pages compared to a custom page

![MicrosoftContent](https://user-images.githubusercontent.com/93666495/151401599-c7c214f0-ceb9-464e-8c41-f7020450ebfe.png)
![MicrosoftContent2](https://user-images.githubusercontent.com/93666495/151401611-e95d7785-a04f-462c-843c-827d81b29f66.png)

![CustomPage](https://user-images.githubusercontent.com/93666495/151401581-0e0b8cc9-25db-4b99-8da4-61156bea466c.png)

**Comment by dcashpeterson** [comment]
@KRReilly Thank you for the screen shots. That is super helpful. All the content that is under the drop down and Prev/next buttons is pulled in via an Iframe so the Learning Pathways app has no control over that. All the content is styled in the source. So for the Microsoft provided content that is styled in support.microsoft.com and if you have custom content in SharePoint that is governed by the styles in SharePoint. If you had custom content in another source they would be styled using that source. Learning Pathways has no way to use or expose any of the styles.

**Comment by dcashpeterson** [comment]
Answered and closed
