### ISSUE TITLE
All Learning Pathways Site Pages Now Blank 

### ISSUE THREAD

**Issue by AnnaEAbba** [pnp/custom-learning-office-365#624]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

I logged onto our Learning Pathways site collection today, and all the pages are now blank. There is no error. Just no content beyond the header image. There are no web parts or anything else when I edit the pages. This includes CustomLearningAdmin.aspx

I tried upgrading to the latest version of the package but it did not help.

### To Reproduce

Go to any page, see nothing.

### Expected behavior

>A clear and concise description of what you expected to happen.

I expected my site collection and pages to keep working like they did after set up. 

>If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/51713646/150002434-283964e8-3394-4cdb-98e4-092df7261c99.png)

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

Started with 4.1.4.0. Tried upgrading to 4.3.1.0

### Additional context

It just stopped working out of no where from what I can tell.

**Comment by amitkh22** [comment]
Hi @AnnaEAbba, Thank you for reporting this issue. We would need some more details to figure out the reason behind this.
When you navigate to customlearningadmin.aspx page, do you see any error in the browser **console**. If yes, please share the screenshot of that error.
When you say, you tried upgrading to the latest version, is the upgrade successful and now are you using the latest version of Learning Pathways?

**Comment by AnnaEAbba** [comment]
Hello!
Thanks so much for your response.
When I navigate to CustomLearningAdmin.aspx I don't see any error on the
page. The Dev Tools console in chrome shows two errors that appear to point
to my user image.
[image: image.png]

I believe the upgrade was successful. I got no errors during the process.
However, this issue with blank pages was present before and after the
upgrade. Here's the app screen from my Learning Pathways site:
[image: image.png]

Thanks!
Anna

**Comment by amitkh22** [comment]
Hi @AnnaEAbba, unfortunately the screenshots that you shared didn't come through, **can you please re-share them.** But as you mentioned the errors are pointing to your user image so we might not be able to get much information from that. There are many things behind this but without some details we can't go in correct direction. Can you please provide below information as well - 

1.  Is this issue happening for other users as well?
2. Can you confirm that the Learning Pathways package is present in the app catalog? And are you using tenant app catalog or a site collection app catalog?
3. Can you confirm if you have access to the cache list Custom Config, Custom Playlists, Custom Assets?
4. Are you using any custom content pack?

**Comment by AnnaEAbba** [comment]
Hi there,
Sorry about that - see attached for the screenshots. Also, my answers are
below.


   1. Is this issue happening for other users as well? Yes, all users
   2. Can you confirm that the Learning Pathways package is present in the
   app catalog? And are you using tenant app catalog or a site collection
   app catalog? I am using the app catalog that appears to be a site
   collection. But it is found under SharePoint  Admin > Most Settings > Apps.
   Url is /sites/appcatalog/AppCatalog/Forms/AllItems.aspx
   3. Can you confirm if you have access to the cache list Custom Config,
   Custom Playlists, Custom Assets? Yes, I can see those lists under Site
   Contents on the learning pathways site.
   4. Are you using any custom content pack? No, we are not. When I
   initially deployed the site, I customized some of the pages and the
   pathways, but it was all Microsoft content built into the Learning Pathways
   app. It worked for several months, but now all the pages are empty and I am
   unable to return to the set up screens. The pages themselves are also empty
   when I try editing them - no web parts.

Thanks!
Anna

**Comment by dcashpeterson** [comment]
@AnnaEAbba when you say there are no web parts on the page do you mean when you put the page in edit mode they are there and not showing anything or the web parts are totally gone. If they are totally gone please check the in Site Contents and let me know if you see Microsoft 365 learning pathways as an App. If you don't then add it to that site collection. I am wondering if the app somehow got uninstalled from the site collection.

**Comment by AnnaEAbba** [comment]
Hi Derek,
I do see Microsoft 365 Learning Pathways under site contents, so to me it
appears to be installed.

Also, I mean that when I put the page in edit mode, there are no web parts
and it is empty. It is also empty when in view mode. It's almost like
something completely removed the Learning Pathways web parts. Which is odd
because it does seem to be installed still.

Let me know if I can provide more details or screenshots etc.

Thanks!
Anna

**Comment by SylvM1** [comment]
Hi all, I have exactly the same issue. All learning pathways webparts are suddenly not loading. I get the following error message in the browser (MS Edge) dev tools overview:

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at Function.ParseAbtCookie (https://statica.akamai.odsp.cdn.office.net/bld/_layouts/15/16.0.22105.12004/activitymonitor.js:182:34)
    at Function.Run (https://statica.akamai.odsp.cdn.office.net/bld/_layouts/15/16.0.22105.12004/activitymonitor.js:106:48)
    at https://statica.akamai.odsp.cdn.office.net/bld/_layouts/15/16.0.22105.12004/activitymonitor.js:424:32

Error: Error: Idle tracking cookie is missing.
    at IdleSessionActivityMonitor.GetCookieValue (statica.akamai.odsp.cdn.office.net/bld/_layouts/15/16.0.22105.12004/activitymonitor.js:365)
    at IdleSessionActivityMonitor.InitializeSettingsFromCookie (statica.akamai.odsp.cdn.office.net/bld/_layouts/15/16.0.22105.12004/activitymonitor.js:349)
    at IdleSessionActivityMonitor.GetTimeToNextCheck (statica.akamai.odsp.cdn.office.net/bld/_layouts/15/16.0.22105.12004/activitymonitor.js:313)
    at Function.RunISSO (statica.akamai.odsp.cdn.office.net/bld/_layouts/15/16.0.22105.12004/activitymonitor.js:221)
    at Function.Run (statica.akamai.odsp.cdn.office.net/bld/_layouts/15/16.0.22105.12004/activitymonitor.js:112)
    at statica.akamai.odsp.cdn.office.net/bld/_layouts/15/16.0.22105.12004/activitymonitor.js:424

![image](https://user-images.githubusercontent.com/57954528/150781335-adcee6bd-6040-44eb-bcdd-1daf906c46d6.png)

Hope you all can help!

**Comment by dcashpeterson** [comment]
@AnnaEAbba If you put the page in edit mode can you add the webpart again to the page and try to configure it. I am wondering if for some reason the webpart was uninstalled and reinstalled at some point.

@SylvM1 Thanks for adding this in. I am not sure if this is the same issue or not. Do you see any errors with a symbol like graduate cap? Those are Learning Pathways issues. These issues in your screen shot are not from Learning Pathways but rather from M365 in general.

**Comment by SylvM1** [comment]
Hi @dcashpeterson ,

What we experience is a page which seems load the webpart (it is blinking) but it never loads. See an example in the screenshot below:

![image](https://user-images.githubusercontent.com/57954528/150792647-272576e6-f19d-4353-866b-0f73060e5a65.png)

If you have any ideas what could be causing this, let me know. If you would like me to create a seperate request, that is also OK.

With kind regards,

Sylvester

**Comment by dcashpeterson** [comment]
@SylvM1 please create a separate issue and see if there is anything in the console logs with a graduation cap next to it. Those are Learning Pathways errors. This happens when the content in the repo can't be reached so my guess based on the other errors you showed is that there is some firewall blocking the content. github isn't allowed but we can work through this in a separate issue.

**Comment by AnnaEAbba** [comment]
Hello!
When I edit the page, I do see the normal list of web parts I'd see on any
SharePoint page. However, I am not seeing any Learning Pathways specific
web parts. Should I? If so, what would they be called?

Thanks,
Anna Ewart

**Comment by dcashpeterson** [comment]
@AnnaEAbba Sorry, I think there is a disconnect here. Can you please send a few screen shots. Can you please send an image of Site Contents screen showing that the Learning Pathways app is installed and can you please send a screen shot of the page in edit mode. Please redact anything that you don't want shared but I want to see those details.

**Comment by AnnaEAbba** [comment]
Hi Derek,
See attached Word doc with a bunch of screenshots. I appreciate your help
and happy to provide anything else that might help. If I just need to start
over with a new site collection, it's not the end of the world. Just
confused about what happened here.
Thanks!
Anna

**Comment by dcashpeterson** [comment]
@AnnaEAbba the attachment didn't come through. Could you please add screen shots to the issue with the description.

**Comment by AnnaEAbba** [comment]
Hi Derek,
See below. I also added the attachments again.

Site page no content:
[image: image.png]


Site Page Edit Mode:
[image: image.png]



Site Contents
[image: image.png]



Learning Pathways App:
[image: image.png]

**Comment by dcashpeterson** [comment]
@AnnaEAbba The images are not coming through. It looks like you are responding to the message via email. Images and attachments don't come through when you use email. Please use the web interface and add the images and I can review. Thanks.

**Comment by kcooksley** [comment]
I've been following this thread since we had the exact same issue.  Someone had done a checkout on ....sites/AppCatalog/AppCatalog/Forms/AllItems.aspx.  When he either discarded or checked that page back in, all was well.  Perhaps this will help others.....

**Comment by dcashpeterson** [comment]
@kcooksley interesting, i hadn't thought of that. Thanks! My guess in that case was that someone upgraded the solution and didn't check the package. @AnnaEAbba can you check that as well before you add the screen shots? Check the app catalog and see if the package is checked out.

**Comment by AnnaEAbba** [comment]
Hi Derek, sorry about the email/screenshot confusion. I am not replying via github. See the attached file with all my screenshots. I also included one of the app catalog site collection, and both packages appear to be checked in.

Please let me know if I missed anything, and thanks for your help!

[Site Page with no content.docx](https://github.com/pnp/custom-learning-office-365/files/7943278/Site.Page.with.no.content.docx)

**Comment by dcashpeterson** [comment]
@AnnaEAbba That I was able to see. You have two instances of the package installed? There should only be one package so it could very well be that the App that is installed in the site isn't the app that is being hit. Regardless, this is a very strange state. My thought is you need to remove one of the packages. Then uninstall the app at the site collection and reinstall it and then add the webparts to the page. It might be easier if you don't have any custom assets or playlists to start over. With that said, the Lookbook is down for maintenance for another week or so. In the future if you need to update the webpart you replace the package file in the app catalog.

Good luck.

**Comment by amitkh22** [comment]
Hi @AnnaEAbba, were you able to resolve this issue? Please let me know in case you need further help on this.

**Comment by Durksweb** [comment]
Hi all, we are facing the same issue here. When i look with my normal company account (read access) is see no webparts with scenario's. When i look as owner i see all the webparts with the scenario's. I updated last week the app to version 4.3.1. The app is cheked-in and published. I have no error messages on .../SitePages/CustomLearningAdmin.aspx.

![image](https://user-images.githubusercontent.com/65964495/155534086-15f8f4a5-343a-4dac-8bfc-686ecb83fbde.png)

Company account:
![image](https://user-images.githubusercontent.com/65964495/155534283-57e906ce-3a49-4c0c-bfd5-2a802c914827.png)

Owner:
![image](https://user-images.githubusercontent.com/65964495/155534392-1097fa78-59ab-4484-933c-270777198195.png)

**Comment by dcashpeterson** [comment]
@Durksweb this feels like a different issue. It feels permission related. Can you ensure that there are no errors in the console when the content won't show? There is no security on the content being iframed so it's a security issue with either the app are you using a tenant app catalog or a site collection app catalog or the lists that hold the cache data. Check the permissions on those things. Users need the ability to read and write to the lists in the root learning pathways site.

**Comment by AnnaEAbba** [comment]
I'm sorry for my delayed response. It's quite a busy time of year for us so I have not done any more troubleshooting. At this point I expect I will have to completely start over with a new site collection. That's a bummer because I did have some minor custom stuff set up.
There are two packages because I installed it again in my attempts to resolve this issue.

**Comment by amitkh22** [comment]
Hi @Durksweb, was there any changes done in permissions while upgrading the webpart? Also, can you check if you have edit access to all the lists in the root learning pathways site collection or your normal company account as well.
Along with this, can you check if there are any errors in the browser's console(press F12--> go to console) if you access the site using your normal account?

**Comment by Durksweb** [comment]
Hi @amitkh22 , as far as i know there were no changes made in permissions. 
With my company account i have access to all the lists in the root learning pathways site collection but no edit rights. That is also as i it should be.
With my admin account i have access to all the lists in the root learning pathways site collection and i have also edit rights.

With my company account i see a lot of warnings and errors. Here are a few:
![image](https://user-images.githubusercontent.com/65964495/155691061-e77c8d24-cde3-4c5d-9667-9ea81c214ae6.png)

![image](https://user-images.githubusercontent.com/65964495/155691077-765964a9-8da8-42ea-80e4-448485f3b383.png)

![image](https://user-images.githubusercontent.com/65964495/155691091-9b784516-b493-4f72-9a97-e2fd890f53d0.png)

![image](https://user-images.githubusercontent.com/65964495/155691101-423ac148-df77-4874-99e8-bdae13d80974.png)

**Comment by amitkh22** [comment]
Hi @Durksweb, you should have edit rights on the CustomConfig list, not on the entire site. Also, can you please let me know if you have created any custom content pack? Or you have created custom Assets/Playlists?
If you have edit access on CustomConfig and still getting the error, it could potentially be a data corruption issue. Could you try clearing out entries from CustomConfig list and navigate to CustomLearningAdmin.aspx page again, and after that try to see if that resolves you issue.

**Comment by Durksweb** [comment]
Hi @amitkh22 you mention that i should have edit rights on the CustomConfig list. Do you mean with my Company account?
We created **no** custom content pack but we have created custom Assets/Playlists.

Normaly company members that use our Learn-site do not have edit access, so that acounts also  for my company account. Witj my admin account i have edit access and the are not the red-errors, only the yellow warnings.

In the CustomConfig i have now 14 entries. If i understand you well you want me to delete that entries?

**Comment by amitkh22** [comment]
Hi @Durksweb, yes, you should have edit rights with your company account. When the learning pathways site gets provisioned, CustomConfig list will have unique permissions and Viewers group will have "Contribute" access on it.

Yes, you can delete the entries from CustomConfig list and navigate to CustomLearningAdmin.aspx page, which will regenerate the cache.

**Comment by Durksweb** [comment]
Hi @amitkh22 i checked again and indeed have edit rights on CustomConfig list.
I deleted all the entries but that was not right. There was a CustomSubCategories which i had to restore. Otherwise our subcategories were gone.
![image](https://user-images.githubusercontent.com/65964495/155728546-a39ef66c-7b58-4660-883a-d15e717b38a6.png)

I did not resolve the issue. On company account still no data. The red errors are gone.

**Comment by Durksweb** [comment]
Hi @amitkh22 have you looked at the above yet?

**Comment by amitkh22** [comment]
Hi @Durksweb, yes, just saw it. So only custom playlists/assets data is not visible with company account and it is visible with admin account?

**Comment by Durksweb** [comment]
Hi @amitkh22 thats correct

**Comment by amitkh22** [comment]
Hi @Durksweb, from this scenario, it looks like permission issue or the pages not being published. Could you please check the permissions on CustomAssets and CustomPlaylists list and share screenshots of it?

**Comment by Durksweb** [comment]
Hi @amitkh22 

**Permissions for CustomAssets :**
- Microsoft 365 learning pathways Members (Edit) => empty
- Microsoft 365 learning pathways Owners (Full controll) => admins of our team
- Microsoft 365 learning pathways Visitors (Read) => Everyone except external users

**Permissions for CustomConfig :**
Same as CustomAssets.

So there are no specific permissions. Both lists inherit the permissions from the site.

**Comment by Durksweb** [comment]
@dcashpeterson this is what we have and is different at what you mentioned.

Custom Config - Unique
![image](https://user-images.githubusercontent.com/65964495/156004018-182bd37b-bb19-40f2-94a4-d88ed51df01f.png)

Custom Asset - Inherit
![image](https://user-images.githubusercontent.com/65964495/156004181-23e84743-eba5-4e17-bb0b-5e9e67d3abc6.png)

Custom Playlists - Unique
![image](https://user-images.githubusercontent.com/65964495/156004282-69393a51-300b-49ee-a9d7-993e999e243e.png)

**Comment by Durksweb** [comment]
Morning @dcashpeterson , did you already had a change to look at my last post?

**Comment by Durksweb** [comment]
@dcashpeterson i changed for Custom Playlists the permissions to inherit. Unfortunately this had no effect.

**Comment by Durksweb** [comment]
@dcashpeterson and @amitkh22 i still keep seeing this errros
![image](https://user-images.githubusercontent.com/65964495/156183104-36cbc999-5b21-4f09-bde3-74f7906145e3.png)

**Comment by amitkh22** [comment]
Hi @Durksweb, right now I'm not sure what could be the possible reason behind this other then permissions issue. Could you double check if your company company account is added to the visitors group. Also could you check if there are any item level permissions granted for the items in the CustomConfig List (check for the item with title "CustomSubCategories"). Check this for CustomAssets and CustomPlaylists lists as well.

Also, could you try creating one new subcategory and add playlists/assets to that and see if it is visible?

**Comment by Durksweb** [comment]
Hi @amitkh22 my company account is member of the visitors group. I also added my account separately to the visitors group. That too had no effect.

CustomConfig List
![image](https://user-images.githubusercontent.com/65964495/156343495-0e294c77-4501-4c71-b701-ffecffc2821b.png)

CustomAssets List
![image](https://user-images.githubusercontent.com/65964495/156344204-d487067e-f4cf-4481-8679-651e5cc44c57.png)

I checked most of the items in CustomAssets List and there are having all the same permissions as shown in the picture.

CustomPlay List
![image](https://user-images.githubusercontent.com/65964495/156344570-0b810639-b131-41fb-b19c-47e27db2a48a.png)

I checked most of the items in CustomPlay List and there are having all the same permissions as shown in the picture.

I made new subcategory and added a playlist and that a can see now with my company account. 
![image](https://user-images.githubusercontent.com/65964495/156348837-d77c594d-306c-4b64-8439-4bf54f85a753.png)

**Comment by Durksweb** [comment]
Hello @amitkh22 i think i know what the issue is here. Its the language. When i open a subcategory, i add our own language to the subcat, then open the playlist and add there our own language and when i als add our own language to the Playlist Assets then the subcats that we made are selfs ore shown again. So its a language issue.

But is there an other option to set everything by default in our own language? Now i have to change every subcat, playlist en playlist assets.

**Comment by Durksweb** [comment]
@amitkh22 so if i understand you right we have to change the languages at each subcategories/playlists we made?

**Comment by amitkh22** [comment]
Hi @Durksweb, when a site is provisioned, we set the default language and it can't be changed after that. So for e.g., if the default language was set to English, you need to have an English version of all the content that you want to create as well as in other languages that you want to support.
So if you want to change the language for existing subcategories/playlists, you need to make that change for each subcategories/playlists that you made.

**Comment by dcashpeterson** [comment]
Just to add in here. You can have additional languages (e.g. English, Spanish, and French) but once the default language for a site is set you can't change it. It looks like when your site was created it was created with English as the default. So you can have a custom subcategory with English (default) and Spanish, and/or English (default) and French but you always need an English version once the default is set to English.

If you need your default language to be in a different language then you need to use the manual instal instructions to create a new site with a different language as the default. https://docs.microsoft.com/en-us/office365/customlearning/custom_manualsetup

**Comment by Durksweb** [comment]
Hello @dcashpeterson and @amitkh22,sorry for the late response. We have decided that we will do a new manual installation in the Dutch language like explained in https://docs.microsoft.com/en-us/office365/customlearning/custom_manualsetup. 

Thanks for all your help.

**Comment by dcashpeterson** [comment]
@Durksweb great. We'll close this issue then. You can always open a new issue.
