### ISSUE TITLE
Kindly help us to provision the sharepoint with lookbook template

### ISSUE THREAD

**Issue by HarishDivya** [pnp/custom-learning-office-365#629]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [x] Installation
- [ ] Learning Pathways Content
- [ ] SharePoint Success Content
- [ ] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### What is your question

>Provide related screen-shots to help us understand your question

**Comment by amitkh22** [comment]
Hi @HarishDivya, Lookbook is down for maintenance for sometime. If you want to provision the Learning Pathways web part, please install it manually following [these](https://github.com/pnp/custom-learning-office-365/blob/main/installation/README.md) instructions.

**Comment by dcashpeterson** [comment]
@HarishDivya - There is currently a service disruption for the Look Book. Here is the notification below.
 
**Important! Service Interruption - Impacted Service:** Provisioning from SharePoint Look Book.
**Experience Impact:** Site & solution provisioning unavailable including Microsoft 365 Learning Pathways.

**Details:** The provisioning capability from the SharePoint Look Book is currently undergoing maintenance. Manual implementation of the M365 Learning Pathways webpart can be accomplished and instructions exist in our documentation (https://aka.ms/M365LPDocs). There is no impact to currently operating customers, previously provisioned templates or streaming content for Learning Pathways. There is no current workaround for site template provisioning.

**Expected Resolution:** February 4, 2022 or earlier

**Comment by amitkh22** [comment]
@HarishDivya, do you need any other information on this? If not, please let me know if I can close this issue.

**Comment by dcashpeterson** [comment]
@HarishDivya the LookBook provisioning service is back up and running. Feel free to use that to provision your Learning Pathways Site. Closing this issue. If you have others please create a new issue.
