### ISSUE TITLE
We are unable to provision new M365 Learning pathways portal

### ISSUE THREAD

**Issue by anilalladi** [pnp/custom-learning-office-365#630]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [x] Installation

### What is your question
We are unable to provision M365 learning pathways portal, as we are getting a site maintenance page after clicking on "Add to your tenant" button from "https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239" Please find the attached image.

We just want to know when will the SharePoint provisioning page will be UP & running, so that we can proceed further. We appreciate your quick response on this.

>Provide related screen-shots to help us understand your question

![image](https://user-images.githubusercontent.com/85885061/151521952-16d7b342-84ca-4b7e-a4e2-2f381b47c4f3.png)

**Comment by dcashpeterson** [comment]
@anilalladi  - There is currently a service disruption for the Look Book. Here is the notification below. Manual instructions for installing Microsoft 365 learning pathways webpart can be found (https://github.com/pnp/custom-learning-office-365/tree/main/installation)
 
**Important! Service Interruption - Impacted Service:** Provisioning from SharePoint Look Book.
**Experience Impact:** Site & solution provisioning unavailable including Microsoft 365 Learning Pathways.

**Details:** The provisioning capability from the SharePoint Look Book is currently undergoing maintenance. Manual implementation of the M365 Learning Pathways webpart can be accomplished and instructions exist in our documentation (https://aka.ms/M365LPDocs). There is no impact to currently operating customers, previously provisioned templates or streaming content for Learning Pathways. There is no current workaround for site template provisioning.

**Expected Resolution:** February 4, 2022 or earlier

**Comment by anilalladi** [comment]
@dcashpeterson Thanks for the update.

I followed the manual installation through the PS script and successfully installed it. However I am getting the webpart version banner as shown in the below image. I have uploaded the current version 4.3.1 into appcatalog and the appl from site contents also showing that its version is 4.3.1 but still I am getting this banner. Any idea on why I am getting this banner?

![image](https://user-images.githubusercontent.com/85885061/151367076-f9255076-e9e8-4043-9b61-bb779eaeeec0.png)

Below image is from the SiteCollection
![image](https://user-images.githubusercontent.com/85885061/151367200-d32f3a5c-8186-444c-a631-fd4068acc248.png)

Below image is from Tenant's AppCatalog
![image](https://user-images.githubusercontent.com/85885061/151367425-3aaa56c7-a0e6-4c6b-ade3-5e37abd6e659.png)

**Comment by amitkh22** [comment]
Hi @anilalladi, If you could check a few things it would be helpful -

1. Can you check in the App Catalog where you installed the new SPPKG file that there were no errors.
2. When you go to the CustomLearningAdmin.aspx page do you get any error in the browser console or on the screen other than the upgrade message? If there are errors in the console please provide those.
3. You may also want to try updating the cache. You can do this by deleting the entries in the CustomConfig list. Let me know what comes up.

you can refer to [this](https://github.com/pnp/custom-learning-office-365/issues/604) issue as well for your reference.

**Comment by anilalladi** [comment]
Hello @amitkh22  I am able to fix the above issue by following the below steps

1. Deleted the app from site collection
2. Deleted the app from Tenant's app catalog
3. Add the app again to app catalog
4. Created a new communication site
5. Ran the script M365lpConfiguration.ps1 on the above site.

I can see only 2 new pages (CustomLearningViewer.aspx and CustomLearningAdmin.aspx) in Site pages library. 

But the Home page was not updated as expected and no other administrative pages were added. Do I need to run any other scripts in order to get them?

**Comment by anilalladi** [comment]
@dcashpeterson Thanks for this information and your support. I appreciate you and @amitkh22.
I will wait for the Lookbook service to be UP & Running.

**Comment by amitkh22** [comment]
@anilalladi, I'll go ahead and close this issue. If you have any other queries, please open a new issue.
