### ISSUE TITLE
MS pathways not working in chrome but it does in brave browser

### ISSUE THREAD

**Issue by grillaertr** [pnp/custom-learning-office-365#631]
## Describe the bug
We had the webpart running for a long time on our tenant. Recently we get a notification that there was an error. After investigation, we noticed that it could be browser depending. I'm using Brave browser and I have no issues. However when I login with the same account in chrome, it is not working. I have collected the logs of this.

### To Reproduce
Downloading the .spkkg file and add it to the tenant (chrome browser).

### Expected behavior
Not showing any issues (screenshot brave)

### Screenshots
Chrome: 
![error](https://user-images.githubusercontent.com/83367519/151539172-aa0f58fd-b7c9-4924-b833-57dbb2897da6.png)

Brave:
![working](https://user-images.githubusercontent.com/83367519/151539189-5285aec8-2cb5-47d8-b59f-d87bb06223f0.png)

### Learning Pathways version number

4.3.1.0

**Comment by amitkh22** [comment]
Hi @grillaertr, thank you for reporting this issue.. Can you please check below points - 

- Is this issue happening just for you or other users as well.
- Learning Pathways Package file is uploaded in tenant level app catalog without any errors and is checked in.
- There should be only one Learning Pathways package file in the app catalog.
- Are you using any custom content pack?

**Comment by grillaertr** [comment]
Hi @amitkh22 this issue is happening for other users as well (not sure if all of them but I guess it is). De package file (only one) is uploaded without errors and also checked in. I also tried to just get the .spkkg file from the repo and upload it on a new tenant with the same result (no other packages were installed on that tenant).

**Comment by amitkh22** [comment]
Hi @grillaertr, when you open the site in Chrome, can you please check and share any errors that you are getting in the browser **console**. Press F12->Navigate to console tab.

**Comment by grillaertr** [comment]
Hi @amitkh22  this is what I find in the console: 
![console errors](https://user-images.githubusercontent.com/83367519/152674861-583f1e72-1cc5-4975-bbb2-c54f5c30f7d7.png)

**Comment by amitkh22** [comment]
Hi @grillaertr, was there any changes made related to Learning Pathways webpart configuration - for e.g. - is the URL of the site collection where Learning Pathways webpart is deployed is updated? Or was there any changes done related to permissions?
Also, Can you confirm if the CustomLearningAdmin.aspx page is also not working in Chrome?

**Comment by grillaertr** [comment]
Hi @amitkh22, I just uploaded the .sppkg file to my tenant and added it a new communication site. There a put the webpart on a page and changed the configuration:
![Configuration webpart](https://user-images.githubusercontent.com/83367519/152786669-75a6e5b4-99ea-4868-8201-051ea0a9928a.png)

To my knowledge, I am using basic permissions and the account I'm using on this tenant is a global admin account. Just a question, should there be anything created when this webpart is added? A list or page?

**Comment by amitkh22** [comment]
Hi @grillaertr, did you manually install Learning Pathways or installed it using Lookbook?

If you installed it manually, can you confirm you followed all the steps mentioned here - https://github.com/pnp/custom-learning-office-365/tree/main/installation

**Comment by amitkh22** [comment]
Hi @grillaertr, do you still have this issue? If not, please let me know if I can close this?

**Comment by dcashpeterson** [comment]
Closed due to inactivity.
