### ISSUE TITLE
 Language issue with Microsoft 365 learning pathways

### ISSUE THREAD

**Issue by jean-luc-chatton** [pnp/custom-learning-office-365#634]
**Describe the issue**
After provisioning, there are 2 multi-language issues:

9 languages can be chosen although I removed all but English, French and Spanish
The contents of the training pages are not translated (text and videos)

**Expected behavior**
Only the selected languages should appear in the language menu
Contents of training pages are supposed to be translated

**Screenshots**
![image](https://user-images.githubusercontent.com/55661955/152324397-3b75121b-4dcd-43a8-8bbc-d90de8631d8f.png)
![image](https://user-images.githubusercontent.com/55661955/152324447-a1e94c1b-6dcf-4f12-9544-16893b29ac92.png)
![image](https://user-images.githubusercontent.com/55661955/152324665-2bf34fe5-d49d-4e72-a4be-41e30254c35f.png)

**Details (please complete the following information):**
PnP Correlation ID: N/A
Reference Template :Microsoft 365 learning pathways
Primary language of the target tenant: Englsih
Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by amitkh22** [comment]
Hi @jean-luc-chatton, thank you for reporting this issue. Please allow me sometime to go analyze it, will get back to you at the earliest.

**Comment by amitkh22** [comment]
Hi @jean-luc-chatton, thank you for patience. The language displayed in the learning pathways web part will depend on the user's personal language and region settings. For more information about setting up a user profile for language and region, please see the below:

https://support.microsoft.com/en-us/office/change-your-personal-language-and-region-settings-caa1fccc-bcdb-42f3-9e5b-45957647ffd7

You can refer to [this](https://github.com/pnp/custom-learning-office-365/issues/550) issue for more details. Please let me know if you think the issue is something else.

**Comment by jean-luc-chatton** [comment]
Hello,

Thank you for your answer. 

Based on the test I've done, the display language of the webpart is only defined by the display language of the browser. So the https://support.microsoft.com/en-us/office/change-your-personal-language-and-region-settings-caa1fccc-bcdb-42f3-9e5b-45957647ffd7 is incorrect (language can be defined by the language of the O365 user profile).

For the second problem (all languages still appear in the language selector, although languages other than English, French and Spanish have been removed from the administration page), do you have a solution?

**Comment by pgriziotti** [comment]
> Hello,
> 
> Thank you for your answer.
> 
> Based on the test I've done, the display language of the webpart is only defined by the display language of the browser. So the https://support.microsoft.com/en-us/office/change-your-personal-language-and-region-settings-caa1fccc-bcdb-42f3-9e5b-45957647ffd7 is incorrect (language can be defined by the language of the O365 user profile).
> 
> For the second problem (all languages still appear in the language selector, although languages other than English, French and Spanish have been removed from the administration page), do you have a solution?

Goto to the site contents-> site pages folder and delete the corresponding language folder

**Comment by jean-luc-chatton** [comment]
Thank you. Done it and it solved the issue.
