### ISSUE TITLE
Link to Adoption Kit loads external non-related website 

### ISSUE THREAD

**Issue by MandyMcPhail** [pnp/custom-learning-office-365#635]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Clicking on links to the "downloadable Adoption Kit" - https://teamworktools.azurewebsites.net/m365lp/m365lpadoptionkit.zip loads a non-related website: https://tempmailo.com/bl/

### To Reproduce

Go to the Admin Success Centre > Drive Adoption > Drive adoption of learning pathways > Use the downloadable Adoption Kit section > in the first sentence, click on the link to the "downloadable adoption kit".

### Expected behavior

I would expect the link to download the zip file, not open a website.

### Screenshots

![image](https://user-images.githubusercontent.com/99344519/153228851-1dcc8f2c-9337-4856-91dc-c6d4c035bee0.png)

### Learning Pathways version number

4.3.1.0

### Additional context

>Add any other context about the problem here.

**Comment by amitkh22** [comment]
Hi @MandyMcPhail, Thank you for bringing this issue to our attention. However this is not a Learning Pathways webpart issue but a content issue as we are just pulling the underlying content and displaying it. We will try to work with content team to sort this out.

**Comment by MandyMcPhail** [comment]
Thanks for the response @amitkh22

**Comment by dcashpeterson** [comment]
@MandyMcPhail The link in the document has been fixed. In testing it I realized that there is also a link in the right side quick links to the adoption kit in the Success center. Make sure you change it there as well. We will need to make an update of the template to make it available in the LookBook but here is the url of the toolkit.

https://adoption.microsoft.com/files/m365lp/m365lpadoptionkit.zip

**Comment by MandyMcPhail** [comment]
That's great, thanks very much!

**Comment by dcashpeterson** [comment]
@MandyMcPhail It took a while but we updated the template on the LookBook and this issue was resolved. Thanks for bringing this to our attention.

**Comment by dcashpeterson** [comment]
Putting the correct links here in case others need to reference this. 
Learning pathways documentation | https://aka.ms/M365LPDocs
Feedback and support (issues list) | https://aka.ms/M365LPIssues
Adoption resources | https://aka.ms/M365LP
Downloadable adoption kit | https://aka.ms/M365LPAdoptionKit

Link	Target URL	AKA
Learning pathways documentation 	[https://docs.microsoft.com/office365/customlearning/ ](https://docs.microsoft.com/office365/customlearning/%c2%a0)	https://aka.ms/M365LPDocs
Feedback and support (issues list)	https://github.com/pnp/custom-learning-office-365/issues	https://aka.ms/M365LPIssues
Adoption resources 	https://adoption.microsoft.com/microsoft-365-learning-pathways/	https://aka.ms/M365LP
Downloadable adoption kit 	https://adoption.microsoft.com/files/m365lp/m365lpadoptionkit.zip	https://aka.ms/M365LPAdoptionKit
