### ISSUE TITLE
 Training Videos not Playing

### ISSUE THREAD

**Issue by brightmatt** [pnp/custom-learning-office-365#637]
We have just deployed LP and we were in the process of reviewing content and my users are stating that the video's never load.  I have confirmed that whether in Edge or Chrome, the video web part just says "Please wait while the media loads" but it never does.  Any ideas?

![image](https://user-images.githubusercontent.com/20801566/154328915-54a6610c-a193-4b9c-ac10-5b1cfeb9da21.png)

**Comment by cwales-bry** [comment]
Same issue here.

 I haven't run the UpdateM365lpCDN script yet though.

**Comment by Scu-OSN** [comment]
We are experiencing the same problem. We have an existing installation, not newly deployed, and the videos used to work. Now the don't. Let me know if I can help with debug information.

**Comment by dcashpeterson** [comment]
Hi all,
Thanks for bringing this to our attention. This is an issue with the content on support.microsoft.com. I have been able to replicate it in our test environment. I will bring it to the content team and report back when I have an answer.

**Comment by dcashpeterson** [comment]
Hello all,
This issue has been resolved. Thank you for using Learning Pathways and thank you for reporting this issue.
