### ISSUE TITLE
Connection of Learning Pathways to Cornerstone On-Demand

### ISSUE THREAD

**Issue by nrrdgirljenn** [pnp/custom-learning-office-365#638]
I have a customer that is wondering if Learning Pathways can connect with a 3rd party LMS, Cornerstone On-Demand

**Comment by dcashpeterson** [comment]
hi @nrrdgirljenn, there are not direct connectors here. There are a few options you could try. If this is a web based LMS you could create assets that link to pages in your LMS. Then you could create a custom playlist just for your content. If you wanted some sort of LMS type quiz or test you could create an asset and add that at the end of your playlist. Hope that helps.
