### ISSUE TITLE
 Microsoft 365 learning pathways SharePoint WebPart won't load

### ISSUE THREAD

**Issue by PrimeGrp** [pnp/custom-learning-office-365#639]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

The page we have the WebPart on is no longer loading (it was performing successfully for many months prior)

The error code generated in console it:

custom-learning-web-part_4fc2df45795b191c799dbe64b0d6be53.js:26 
        
       Message: TypeError: Cannot read properties of undefined (reading 'Telemetry') - CacheController (doInit)

### To Reproduce

Simply navigating to the page to attempt to load the web part.

### Expected behavior

Expect it to load successfully.

### Screenshots

![0365webparterror](https://user-images.githubusercontent.com/100237583/155213905-a50ddf40-8e68-444a-b5fd-871a0effbd4a.png)

### Learning Pathways version number

unknown

**Comment by amitkh22** [comment]
Hi @PrimeGrp, thank you for reporting this issue. I'll need some more information to be able to assist you.

- Is this issue happening for all users?
- Is CustomLearningAdmin.aspx page is loading correctly?
- Are you using any custom content pack?
- Can you share the Learning Pathways version number?

**Comment by PrimeGrp** [comment]
Hello,

•	Is this issue happening for all users? Yes
•	Is CustomLearningAdmin.aspx page is loading correctly? No
•	Are you using any custom content pack? No
•	Can you share the Learning Pathways version number? Where do I locate this.

**Comment by dcashpeterson** [comment]
@PrimeGrp I'm looking into this as well. If the webpart isn't loading then you can get the version number from the app catalog where it was provisioned. I am curious, are there any other errors in the console other than the telemetry error you showed in the screen shot?

**Comment by PrimeGrp** [comment]
Hello,

Can you please advise how to look up the version number and/or can we set up a Teams meeting to help us get this accomplished?

Yes, but now on load it is spitting out different errors:

Failed to load resource: the server responded with a status of 404 ()
media.akamai.odsp.cdn.office.net/eastus1-mediap.svc.ms/transform/thumbnail?provider=url&inputFormat=svg&docid=https%3A%2F%2Fres-1.cdn.office.net%3A443%2Ffiles%2Fsp-client%2Ficn_card_designer_card_afb025ac9293b90e3915192b84c0e56d.svg&w=400:1 

       Failed to load resource: the server responded with a status of 405 ()
custom-learning-web-part_4fc2df45795b191c799dbe64b0d6be53.js:26 
        
       Message: TypeError: Cannot read properties of undefined (reading 'Telemetry') - CacheController (doInit)
e.log @ custom-learning-web-part_4fc2df45795b191c799dbe64b0d6be53.js:26

**Comment by dcashpeterson** [comment]
@PrimeGrp you can get the version number two ways. 

If you can get the the admin page https://<YourTenant>.sharepoint.com/sites/M365LP/SitePages/CustomLearningAdmin.aspx
![image](https://user-images.githubusercontent.com/45491456/156025694-d4a9d1b9-baad-4e70-b9fd-69db0d619b16.png)
![image](https://user-images.githubusercontent.com/45491456/156025734-ad4101fe-2cc5-4213-814a-9317a823ae7d.png)

If you can't get the admin screen you need to go to the app catalog where you installed learning pathways and search in that list for 365. You should see something like this.
![image](https://user-images.githubusercontent.com/45491456/156026172-a49b0a10-d80b-4807-99f3-6b1798fc2b22.png)


Unfortunately, we don't offer one on one support. This is a community project and we don't have the ability to do that so all the support is here through GitHub.

**Comment by PrimeGrp** [comment]
![image](https://user-images.githubusercontent.com/100237583/156036155-f9aea30d-b571-470e-8d74-f27635641e55.png)

**Comment by dcashpeterson** [comment]
Closed for inactivity. If you are still having issues please open a new issue and reference this one.
