### ISSUE TITLE
SharePoint PNP (Custom Learning for Office 365) app

### ISSUE THREAD

**Issue by AdityaALPS** [pnp/custom-learning-office-365#64]
1. **Issue Category:** SharePoint PNP (Custom Learning for Office 365) app.

2. **Question**: how to get Custom Learning for Office 365 App in French language.

3. **Expected or Desired Behavior:** When I add Playlist on SharePoint modern Communication site for French site collection, then playlist appears in English only, not in French. Although the language has been chosen as French while creating the SharePoint Modern Communication site.

4. **Current Version we are using:** VERSION | 2.0.13.0 | RELEASE DATE | May 2019

<img width="829" alt="PlayListNotAppearsFrench_crop" src="https://user-images.githubusercontent.com/50898002/58147845-f8e2a200-7c79-11e9-956f-178212c2bdaf.png">

**Comment by justin-lisi** [comment]
Hello,

We are currently working on multilingual support for the following languages and are looking to have this released for CY19 Q3 (French being among them):

Chinese (Simplified)
Dutch (Netherlands)
French
German
Italian (Italy)
Japanese (Japan)
Portuguese (Brazilian)
Russian (Russian)
Spanish

Please let us know if you have any other questions or concerns. Apologies for any inconvenience this may cause  in the meantime. Thank you!

Regards,
Justin

**Comment by AdityaALPS** [comment]
Hello Justin,

Thank you so much for your quick response. I am really glad to see that you did feedback this to Microsoft team back in.

I have few more questions, will open new issue/thread.

Thanks again!

Regards,
Aditya
