### ISSUE TITLE
Looking for someone to speak with my customer about product capabilities, installation guidance, features, integration points, etc.

### ISSUE THREAD

**Issue by mreagan65** [pnp/custom-learning-office-365#642]
### What is your question

>Looking for someone to speak with my customer about product capabilities, installation guidance, features, integration points, etc.

**Comment by amitkh22** [comment]
Hi @mreagan65, thank you for reaching out. Unfortunately, we don't offer one on one support. This is a community project and we don't have the ability to do that so all the support is here through GitHub.

You can go through below links to get better understanding of Learning Pathways - 
https://docs.microsoft.com/en-us/office365/customlearning/
[Everything you need to know about Microsoft 365 learning pathways - YouTube](https://www.youtube.com/watch?v=aqwdY65M7aE)

**Comment by dcashpeterson** [comment]
@mreagan65 the links @amitkh22 posted are a great place to start. We can certainly answer general questions about the tool here but if you have specifics around your situation you might need a little more guidance. For that I would suggest that you reach out to a Learning Pathways partner. You can find a few here. https://adoption.microsoft.com/partner-solution-gallery/

**Comment by mreagan65** [comment]
@amitkh22 and @dcashpeterson - thanks for the prompt responses.  Much appreciated.
