### ISSUE TITLE
[QUESTION] disable messages in Yammer home feed to join champion program

### ISSUE THREAD

**Issue by DaveTheTeamsGuy** [pnp/custom-learning-office-365#643]
### What is the context of your question

- [ ] Installation
- [ ] Learning Pathways Content
- [ ] SharePoint Success Content
- [x] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### What is your question
We installed a new instance of Learning Pathways yesterday.  Since then, I'm noticing messages in random languages from Learning Pathways in my Yammer home feed to join the Champions network.  Is Learning Pathways doing this, and how can we disable it?

>Provide related screen-shots to help us understand your question
It looks like it has stopped, so no screenshot available.

**Comment by dcashpeterson** [comment]
@DaveTheTeamsGuy The Learning Pathways webpart doesn't post anything anywhere. It just pulls data in from the other sources. Can you provide an example of one of the messages? What account is it coming from?

**Comment by DaveTheTeamsGuy** [comment]
It stopped after I kept refreshing, but fortunately I saved a screenshot.  This was duplicated for about 8 different languages (not including English):
![MicrosoftTeams-image](https://user-images.githubusercontent.com/99212416/156601393-ef2b893e-fa8a-43e6-a50e-d2d59cabd5c6.png)

**Comment by dcashpeterson** [comment]
@DaveTheTeamsGuy I did some digging. This is a default news post that is included in the Learning Pathways site collection. While it doesn't do it by default. I am guessing someone clicked the Send to Yammer button under Promote on that page. By default nothing is pushed anywhere but if someone pushed the promote button that could absolutely happen. Because you provisioned through the LookBook you have all 10 languages installed. If you are not planning on using them all you should turn off the ones you are not using. Hope that helps.

**Comment by DaveTheTeamsGuy** [comment]
Interesting and good to know.  My team indicated they didn't do anything, so I'll poke around and see who was out there pushing buttons.  Thanks for the response!

**Comment by DaveTheTeamsGuy** [comment]
Reopening for further conversation - Clicking on Promote > Send to Yammer requires you to select to post to a community, and when you do it comes from your name.  What's odd about this is, it only shows up in the home feed, and appears to come from "Microsoft 365 learning pathways".  Maybe I'm missing something simple.

**Comment by dcashpeterson** [comment]
We looked some more and the way this was pushed out was by selecting "Send To" > "Yammer". We were able to replicate it. I think you are out of the woods as it was probably done manually. There is nothing in the provisioning code or the web part that publishes anything to Yammer.

**Comment by DaveTheTeamsGuy** [comment]
When you tested, did the message come from the tester's account, or from "Microsoft 365 learning pathways"?

**Comment by dcashpeterson** [comment]
It came from Microsoft 365 Learning Pathways.

**Comment by DaveTheTeamsGuy** [comment]
That's not how ours is functioning, however thanks for the testing and response.  We will keep looking around.

**Comment by amitkh22** [comment]
Hi @DaveTheTeamsGuy, Do you have any other questions on this? If not, can we close this issue?  You can always open a new one if you need some other information.

**Comment by DaveTheTeamsGuy** [comment]
I'll close this one out, thanks.
