### ISSUE TITLE
[QUESTION] Can you repress content from the Learning Pathways homepage without repressing it from the entirety of the site?

### ISSUE THREAD

**Issue by spwingal** [pnp/custom-learning-office-365#645]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [ ] Installation
- [X] Learning Pathways Content
- [ ] SharePoint Success Content
- [ ] Administration
- [ ] Custom Content
- [X] Viewer Web Part

### What is your question
Can you repress Yammer from the Learning Pathways homepage (because we have a separate sharepoint page dedicated to internal business rules around it)? We don't want to suppress all of the Yammer learning content (still want to be able to access the content through learning pathways), just not show it on the homepage. Is this possible?

>Provide related screen-shots to help us understand your question

**Comment by v-ashrirao** [comment]
@spwingal , Unfortunately the description provided is not sufficient for us to understand the problem statement correctly.

As per our understanding, you wish to hide Yammer to restrict users from sending anything via Learning Pathways to yammer, however you wish to show content related to yammer which Learning Pathway provided. 

Please confirm if our understanding is correct and provide us more details related to this.

**Comment by spwingal** [comment]
What we are trying to do is we have a branded resource site we built in SharePoint Online that has a page on each product, and on those pages pull in the appropriate learning pathway for that product.  We have a page for Microsoft 365 for Enterprise Apps that we want to be able to show just those appropriate apps in the learning pathways.  However, to do that it is pulling in Yammer, Teams, and SharePoint as well which ends up being a little confusing. Is there a way to hide the pathways (Yammer, Teams, and SharePoint)  just on the Microsoft 365 for Enterprise Apps page so it is just showing the appropriate pieces? In other words, what we're really trying to get to is being able to hide the products in the Learning Pathways webpart. We can currently reorder the products in the web part, but are unable to hide the products without globally hiding it across all of the pages (through hiding it in the admin page). Does this help clarify?

**Comment by amitkh22** [comment]
Hi @spwingal, thank you for clarifying it. Unfortunately there is no other way to hide the products other than hiding it from admin page. You can use filters to show a particular subcategory/playlist on that page. That way it will show only that subcategory/playlist.

**Comment by amitkh22** [comment]
Hi @spwingal, Can we close this issue if you don't have any other questions for us?

**Comment by spwingal** [comment]
@amitkh22 , yes thanks!
