### ISSUE TITLE
 App Catalog Error: Deployment Failed. Correlation ID:8dd8d09f-5076-c000-2af7-2116a2556ced

### ISSUE THREAD

**Issue by IvorDavies59** [pnp/custom-learning-office-365#646]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

### To Reproduce

>Steps to reproduce the behavior

### Expected behavior

>A clear and concise description of what you expected to happen.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.

**Comment by IvorDavies59** [comment]
[SPLoaderError.loadComponentError]:
Failed to load component "141d4ab7-b6ca-4bf4-ac59-25b7bf93642d" (CustomLearningWebPart). Original error: Failed to load URL 'https://tsacb.sharepoint.com/sites/AppCatalog/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/custom-learning-web-part_9f36b4992c3974449682ffe4b8867764.js' for resource 'custom-learning-web-part' in component '141d4ab7-b6ca-4bf4-ac59-25b7bf93642d' (CustomLearningWebPart). The file was not found in the server.

INNERERROR:
Failed to load URL 'https://tsacb.sharepoint.com/sites/AppCatalog/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/custom-learning-web-part_9f36b4992c3974449682ffe4b8867764.js' for resource 'custom-learning-web-part' in component '141d4ab7-b6ca-4bf4-ac59-25b7bf93642d' (CustomLearningWebPart). The file was not found in the server.
CALLSTACK:
Error
    at t [as constructor] (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:70:214295)
    at new t (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:71:8874)
    at Function.e.buildErrorWithVerboseLog (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:71:45955)
    at Function.e.buildLoadComponentError (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:71:42072)
    at https://res-1.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_c13a3fd9296251f1459f.js:1:60147

**Comment by dcashpeterson** [comment]
Hi @IvorDavies59 thanks for using learning pathways. Unfortunately, we need more information in order to try to help you. If you could please fill out the template with as much detail as you can that would be great. Without that information we won't be able to help you troubleshoot.

**Comment by IvorDavies59** [comment]
![image](https://user-images.githubusercontent.com/44751974/157937493-e24ae340-9237-4358-ad39-dc898f0e6482.png)
![image](https://user-images.githubusercontent.com/44751974/157937533-ca96764d-94d5-422f-a105-1f7730fde087.png)
 Do these images help? 

The first image is the actual error that is shown when you try to access any of the Learning Pathways content.
The second image is of the SharePoint Application Catalog error for customlearning.sppklg package in the catalog.

**Comment by IvorDavies59** [comment]
I cannot access any diagnostic log information due to my limited access on the site.

There were four Learning Pathways sites that were provisioned over the last two years by various internal SharePoint resources (most of whom have left the organization). None of the Learning Pathways sites work since about June 2021. I just recently started at the organization (I have used Learning Pathways with other clients / customers and highly promoted it's use internally), and I wanted to get at least one of the provisioned sites working for our internal Productivity Team & End User Trainers (we have an EMail migration project starting and we would like to supplement the Learning Pathways content for training purposes. Please advise if you require any additional information. Thank You, Ivor Davies

**Comment by dcashpeterson** [comment]
If you could fill out the template and answer the questions that help us. Based on the screen shots it looks like the webpart didn't deploy properly. You should try to deploy it again and see if it works. You are also not using the most recent version of the webpart. We are currently at 4.3.1.

**Comment by IvorDavies59** [comment]
The version that they uploaded is 4.2.0.0. Please advise where I can find the template - I don't seem to see it on this page. Thank You. Ivor

**Comment by IvorDavies59** [comment]
I downloaded the latest version from GitHub - should we try to deploy that version in our App Catalog?

**Comment by dcashpeterson** [comment]
The template is the first message in this thread but I pasted it below. I would deploy the latest version. Without it being deployed properly it will never work on the page.

PROVISIONING NOTE: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to SharePoint/sp-provisioning-service GitHub Issues List.
WEB PART NOT LOADING: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the Diagnosing Pre-Check guidance before submitting your bug.
Describe the bug

A clear and concise description of what the bug is.

To Reproduce

Steps to reproduce the behavior
Expected behavior

A clear and concise description of what you expected to happen.
Screenshots

If applicable, add screenshots to help explain your problem.
Learning Pathways version number

Please share the version number of learning pathways in your tenant app catalog.
Additional context

Add any other context about the problem here.

**Comment by IvorDavies59** [comment]
Describe the bug - Learning Pathways content does not load. Site is available but we cannot access the content.

A clear and concise description of what the bug is.

To Reproduce

Steps to reproduce the behavior
Expected behavior
![image](https://user-images.githubusercontent.com/44751974/157947179-f4610461-5960-4d43-aaf6-78ca1e22a583.png)

A clear and concise description of what you expected to happen.
Screenshots

If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/44751974/157947525-2c998718-4c97-48a1-9968-b69b91dc3867.png)

Learning Pathways version number

Please share the version number of learning pathways in your tenant app catalog.
![image](https://user-images.githubusercontent.com/44751974/157947575-7e1bafd4-a13c-4e77-96dc-5bcf2172b1a0.png)

4.2.0.0

**Comment by IvorDavies59** [comment]
Quick question - To upload version 4.3.1 of the customlearning.sppkg package in the App Catalog site of our Office 365 tenant, do you need Tenant Admin or SharePoint Admin rights?

**Comment by dcashpeterson** [comment]
You need to be a SharePoint admin to update the package. But if the site was deployed using the lookbook you needed to be a tenant admin for it to work properly.

Once you redeploy the package if it still isn't working we'll need reproduction steps to help. Have a great weekend.

**Comment by IvorDavies59** [comment]
Thank you sir so very much for your help! Hope you have a great weekend too! Cheers!
