### ISSUE TITLE
What URLs within pnp.github.io are used?

### ISSUE THREAD

**Issue by glblinck** [pnp/custom-learning-office-365#650]
If someone wasn't willing to whitelist all of https://pnp.github.io, is there a set of URLs under this which could be whitelisted instead? https://pnp.github.io/custom-learning-office-365 didn't seem to be enough, even with https://support.office.com/ and https://docs.microsoft.com/ both whitelisted.

**Comment by amitkh22** [comment]
Hi @glblinck, unfortunately there is no set of individual URLs which can be used here. You need to whitelist entire repo https://pnp.github.io/ for this to work.
