### ISSUE TITLE
 M365 LP we part does return error

### ISSUE THREAD

**Issue by abpolspoel** [pnp/custom-learning-office-365#652]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

External Ushers  with german language set do not se the content of ms365 LP.
 

### To Reproduce

Any guest user connecting to sharepoint site does see ervoor instemde of content on MD365 LP. All have German set as language.

### Expected behavior

M365 LP webpart displays the videos from playlist.

### Screenshots

![MicrosoftTeams-image](https://user-images.githubusercontent.com/101874838/160913783-31354376-5de6-4b1c-8239-c54600e821bc.png)
![MicrosoftTeams-image2](https://user-images.githubusercontent.com/101874838/160913855-88377dd0-943f-4a44-899e-984eef288d75.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/101874838/160913863-c46f5505-b136-4f17-9b1a-8b8ce996980f.png)

### Learning Pathways version number

4.3.1.0

### Additional context

>Add any other context about the problem here.

**Comment by v-ashrirao** [comment]
@abpolspoel, Thank you for reporting this.

This happens when the user doesn't have access to your Tenant App Catalog and you haven't turned on the SharePoint public CDN. This is a common occurrence with Guest accounts as they would by default not have access to the Tenant App Catalog

Request you to refer below issue for more reference,
https://github.com/pnp/custom-learning-office-365/issues/258

Please let us know if additional details are required.

**Comment by v-ashrirao** [comment]
@abpolspoel, Do you need more information on this? If not, can we close this?

**Comment by dcashpeterson** [comment]
Answered and closed
