### ISSUE TITLE
Video content is not visible on iOS devices  

### ISSUE THREAD

**Issue by AVPTKevin** [pnp/custom-learning-office-365#654]
## Describe the bug
Open Learning Pathways site in Safari, Edge or Chrome. From iOS device (iPhone and iPad)
Browse to the Microsoft 365 training
Pick some content that has a video
When browsing Learning Pathways content on iOS the video loading screen is briefly shown for a fraction of a second and then disappears leaving a white gap. No video content is loaded. Similar to a previous ticket.
tried on latest version of iOS, 15.4.1

1) The pathway video does not load If launched from iOS SharePoint App
2) If launched from Chrome browser it will route to SharePoint App
![b7e04b93-b3a7-4827-ad78-8e6eec281edc](https://user-images.githubusercontent.com/103234096/162356604-48cf5419-fab5-44a3-a2c0-1046eecc6e4d.jpg)
3) The videos do not load If opened from iOS Safari
4) Video does not load even if the link is directly coped from microsoft on iOS: [Video: What is Microsoft Teams? - Office Support](https://support.office.com/en-us/client/4422bf3aa-9ae8-46f1-83a2-e65720e1a34d?embed=true&fromOrigin=https://sympjulie.sharepoint.com)
5) Video cant load if sign in & open from edge browser
### Expected behavior

When launching the Learning Pathways site on iOS, to be able to view all the pathway videos. Windows and Android devices do not seem to experience this issue. What can be done? 

### Additional context

Is it possible to change the URL? We tested this on different tenants, without any restrictions this bug still occurs.

**Comment by v-ashrirao** [comment]
@AVPTKevin,
Thanks for reporting this issue.
Please allow us some time. We will get back to you ASAP.

**Comment by v-ashrirao** [comment]
@AVPTKevin, 

This is an existing bug. Team is currently working on this. 
https://github.com/pnp/custom-learning-office-365/issues/496
