### ISSUE TITLE
Assets become not visible in CustomLearningAdmin

### ISSUE THREAD

**Issue by awaller98** [pnp/custom-learning-office-365#655]
## Describe the bug

>Duplicate of #615 (auto locked)

Several playlists clearly have assets within them and can be accessed as a user in the CustomLearningViewer.aspx but when you look at that playlist in CustomLearningAdmin.aspx, assets are invisible and "+ New Asset" button is not present.

The custom playlist in question is a copy of one created by Microsoft, the original by Microsoft currently being hidden. Here is the playlist in question:
![image](https://user-images.githubusercontent.com/10248309/163059233-e7520dfe-a44d-4c7e-9082-b4ed61e23969.png)

Here is the section to view the assets and the missing "+ New Asset" button.
![image](https://user-images.githubusercontent.com/95828431/145302213-c03ec3f9-1900-44bd-9e48-62b401d63f3d.png)

### Expected behavior

>We should be able to see the assets and be able to add/remove them. Here's what other, still functioning, playlists look like:
![image](https://user-images.githubusercontent.com/95828431/145302445-91c72159-435c-47ef-8e9a-cab14f9c14c2.png)

### Learning Pathways version number
4.3.1

### Additional context

>Some of our custom playlists simply contain different combinations of the Microsoft Provided Assets with no custom assets. It seems likely however that some of the Microsoft assets contained in the custom playlist have changed. Are we doomed to have to re-create our custom playlists (or hunt down and update GUIDS in JSON) whenever changes occur to the Microsoft assets?

<img width="2057" alt="Screen Shot 2022-04-12 at 4 58 07 PM" src="https://user-images.githubusercontent.com/10248309/163061707-cc777235-feb5-467a-b347-0af24d4eac43.png">

**Comment by v-ashrirao** [comment]
@awaller98, thank you for raising the query.
Whenever you face such issue, the best way is to verify the GUIDs in JSON since this is most likely a data issue.

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new issue and reference this one. We would be happy to help you.
