### ISSUE TITLE
Microsoft 365 learning pathways site plugin has stopped working

### ISSUE THREAD

**Issue by Satpaul692** [pnp/custom-learning-office-365#658]
The Microsoft 365 training plugin for our MS Teams application has stopped working. We are not aware of any changes made that could have caused this issue.

Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.]

The web developer tools through MS Edge is bringing up a lot of errors. Most notable the failure to load the resource, which suggests that something has changed with the Microsoft's site?

Failed to load resource: the server responded with a status of 403 ()
custom-learning-web-part_6afa454923dcfaa35ca0.js:1 
        
       Message: Error making HttpClient request in queryable [403]  ::> {"odata.error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Attempted to perform an unauthorized operation."}}} Data: {"response":{},"status":403,"statusText":"","isHttpRequestError":true}
e.log @ custom-learning-web-part_6afa454923dcfaa35ca0.js:1
custom-learning-web-part_6afa454923dcfaa35ca0.js:1 
        
       Message: 🎓 M365LP:CustomDataService (getCustomConfig) - Error: Error making HttpClient request in queryable [403]  ::> {"odata.error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Attempted to perform an unauthorized operation."}}
![LearningPathwaysTrainingSiteErrorMessage](https://user-images.githubusercontent.com/104211232/165986086-7c28b090-fe46-45ee-95d7-a8f11dc9aa0d.png)
}

**Comment by dcashpeterson** [comment]
@Satpaul692 Thanks for reaching out. That error you are referencing has to do getting the cache from the customconfig list. That list lives in the Learning Pathways admin site. Check the permissions on that library and see if anything has changed and that the user in question has access. Everyone needs the ability to read from that list in order to get the data from the cache.
