### ISSUE TITLE
No Microsoft Playlists work "refused to connect" with Chrome Browser 

### ISSUE THREAD

**Issue by luvsql** [pnp/custom-learning-office-365#660]
I have tried a playlist from Outlook, Word, OneNote ie the builtin ones available from Microsoft and none of them play.  I see "www.microsoft.com refused to connect" on them all.  

They do play with Edge, however, none of our users use Edge and Chrome is the default browser.  I've updated the browser to current (100.0.4896.127) but still doesn't work.

**Comment by v-ashrirao** [comment]
@luvsql, Thank you for reporting this.
Please allow us some time to analyze this issue. We will look into this and get back to you ASAP.

**Comment by luvsql** [comment]
Error from console:
Failed to load resource: the server responded with a status of 404 ()
chromewebdata/:1 Refused to display 'https://www.microsoft.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by dcashpeterson** [comment]
@luvsql we will need more information that that from the error logs. Can you copy a few lines above and below that error? Any error being trapped by Learning Pathways will have this emoji next to it. If you don't see a 🎓 next to it that isn't an error for Learning Pathways, it is an error from M365 in general.

**Comment by luvsql** [comment]
Here are the errors above and below:

Message: [132fe4d8-776d-4bd3-ab9c-9b7ea99724d7] (1651754280002) Completing GET request. Data: {}
custom-learning-web-part_712b39223638b5bf32af.js:1 Message: [132fe4d8-776d-4bd3-ab9c-9b7ea99724d7] (1651754280002) Returning result from pipeline. Set logging to verbose to see data. Data: {}
custom-learning-web-part_712b39223638b5bf32af.js:1 Message: 🎓Initialized Microsoft 365 learning pathways - Tenant: e809a90a-34a6-4b64-85f9-f437574fec79
sp-pages-assembly_en-us_6a9fc923dbf437f4eee354018aebbc71.js:71 there is no paired service worker qos start event for this end event: {"resultType":0,"extraData":{"app":"SitePages","stats":{"version":"odsp-web-prod_2022-04-22.001","durations":[2,1041,1],"pageFromConfig":true,"siteFromConfig":true,"navigationResultFromConfig":false,"lkgFromConfig":false,"offline":false,"site":{"caches":3,"databases":5,"lastMaintained":"2022-05-03T12:47:21.662Z","pages":6,"routes":49,"sites":5,"states":9,"storage":{"quota":151919156428,"usage":1457067496,"usageDetails":{"caches":1445630720,"indexedDB":11213227,"serviceWorkerRegistrations":223549}},"version":"odsp-web-prod_2022-04-22.001"},"scriptSyncPending":false},"name":"BaseNavigationHandler.navigate","id":"b8fd728b-21d0-46e2-90b1-a63c9f33e284"}}
sp-pages-assembly_en-us_6a9fc923dbf437f4eee354018aebbc71.js:71 there is no paired service worker qos start event for this end event: {"error":"ApiError","resultCode":"Missing header","resultType":2,"extraData":{"stack":"ApiError\n    at t.i (https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:54644)\n    at new t (https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:54935)\n    at c (https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:23167)\n    at https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:13244","name":"Router.readResponseHeader","id":"6086f7b2-8ccd-4950-824a-483604944d6a"}}
sp-pages-assembly_en-us_6a9fc923dbf437f4eee354018aebbc71.js:71 there is no paired service worker qos start event for this end event: {"error":"ApiError","resultCode":"Missing header","resultType":2,"extraData":{"stack":"ApiError\n    at t.i (https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:54644)\n    at new t (https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:54935)\n    at c (https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:23167)\n    at https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:13244","name":"Router.readResponseHeader","id":"aea2db9f-a344-41e3-bb8a-e3695b61779b"}}
sp-pages-assembly_en-us_6a9fc923dbf437f4eee354018aebbc71.js:71 there is no paired service worker qos start event for this end event: {"error":"ApiError","resultCode":"Missing header","resultType":2,"extraData":{"stack":"ApiError\n    at t.i (https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:54644)\n    at new t (https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:54935)\n    at c (https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:23167)\n    at https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:13244","name":"Router.readResponseHeader","id":"2c4c3fbe-b299-4605-90c8-9a15e6dee5b2"}}
sp-pages-assembly_en-us_6a9fc923dbf437f4eee354018aebbc71.js:71 there is no paired service worker qos start event for this end event: {"error":"ApiError","resultCode":"Missing header","resultType":2,"extraData":{"stack":"ApiError\n    at t.i (https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:54644)\n    at new t (https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:54935)\n    at c (https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:23167)\n    at https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:13244","name":"Router.readResponseHeader","id":"98a422a9-39dd-40ef-99c7-3e00c94e3c4a"}}
sp-pages-assembly_en-us_6a9fc923dbf437f4eee354018aebbc71.js:71 there is no paired service worker qos start event for this end event: {"error":"ApiError","resultCode":"Missing header","resultType":2,"extraData":{"stack":"ApiError\n    at t.i (https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:54644)\n    at new t (https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:54935)\n    at c (https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:23167)\n    at https://res-1.cdn.office.net/files/odsp-web-prod_2022-04-22.001/spserviceworker.js:2:13244","name":"Router.readResponseHeader","id":"bc06a476-b1b3-4cae-8ef5-d514e93ce39c"}}
chromewebdata/:1          Failed to load resource: the server responded with a status of 404 ()
chromewebdata/:1 Refused to display 'https://www.microsoft.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
(index):6772 crbug/1173575, non-JS module files deprecated.
(anonymous) @ (index):6772
DevTools failed to load source map: Could not load content for https://skygridconstructioninc.sharepoint.com/sites/appcatalog/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/en-us.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://amcdn.msftauth.net/meInlineBackCompat.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
activitymonitor.js:211 DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at Function.ParseAbtCookie (https://statica.akamai.odsp.cdn.office.net/bld/_layouts/15/16.0.22420.12007/activitymonitor.js:182:34)
    at Function.Run (https://statica.akamai.odsp.cdn.office.net/bld/_layouts/15/16.0.22420.12007/activitymonitor.js:106:48)
    at https://statica.akamai.odsp.cdn.office.net/bld/_layouts/15/16.0.22420.12007/activitymonitor.js:424:32
activitymonitor.js:228 Error: Error: Idle tracking cookie is missing.
    at IdleSessionActivityMonitor.GetCookieValue (activitymonitor.js:365:23)
    at IdleSessionActivityMonitor.InitializeSettingsFromCookie (activitymonitor.js:349:57)
    at IdleSessionActivityMonitor.GetTimeToNextCheck (activitymonitor.js:313:18)
    at Function.RunISSO (activitymonitor.js:221:75)
    at Function.Run (activitymonitor.js:112:52)
    at activitymonitor.js:424:32

**Comment by luvsql** [comment]
Is there any updates on this?  We can't force a person to watch these videos with Edge as we'd like to simply add shortcuts to the site in Teams, SharePoint etc.  If they open SharePoint with Chrome, site opens in Chrome, same if they have Chrome as default browser.  

No videos play at all in Chrome.

**Comment by dcashpeterson** [comment]
@luvsql we do our best to answer issues in a timely fashion. This is a volunteer effort and I am happy to do my best to help resolve the issue quickly. Unfortunately, I'm not able to do the research on this right now. I will get to it as soon as I can and give you an update. It could be a known issue related to this issue. https://github.com/pnp/custom-learning-office-365/issues/496

**Comment by dcashpeterson** [comment]
@luvsql I reviewed the log you provided from the console.

If you look at the following error it is saying that it can't find the file from the app catalog. That unique ID is Learning Pathways. So I would check the permissions for the app catalog. Users in question need to be able to read from that location. 

https://skygridconstructioninc.sharepoint.com/sites/appcatalog/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/en-us.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

There is another error in there with a CORs related error not loading Microsoft.com but that is not a Learning Pathways error as far as I can tell. 

My suggested next steps would be to make sure that the user(s) that are experiencing the error are able to access the app catalog. If they can then I would be helpful to a) get a screen shot of what the page looks like for the broken assets and b) get the output of the logs on that page. 

Also, what operating system are your users using? Are they on PC or Mac. Is this happening on the desktop or mobile. There is a known issue #496 where the videos don't work on IOS for some assets that the content team is working on.

**Comment by luvsql** [comment]
We have zero issues running the same playlists which are built-in Microsoft ones on the same pag
![Side by Side Playlist between Edge and Chrome](https://user-images.githubusercontent.com/104849149/168842996-1d9fcb84-6401-46d0-b5d2-5a537b42ff6d.png)
e using Edge browser.  The same users, same playlists all run fine in Edge. 

We use Windows 10/11 here only.  

Attached is the side by side with Edge and Chrome.  Same PC, same user.  ALL Microsoft ones do the same thing in Edge.

**Comment by dcashpeterson** [comment]
@luvsql sorry for the delay here. I am sort of stumped on this one. I have tried to replicate it and am not able to replicate it. The way that this works is that the What is Outlook page (or any of the other pages) are being IFramed into the Learning Pathways web part from the source. What is being blocked in Chrome is only a part of that page from docs.microsoft.com. So that page is being loaded. Given that it is working in one browser but not the other I am wondering if there is some sort of proxy issue with Chrome in your organization. Can you check with the network folks in your organization and see if there is any policy that is preventing double hops or any kind of IFramed content that is specific to Chrome? At the end of the day this feels like a network issue rather than a web part issue as it is not occurring in any other environments.

**Comment by luvsql** [comment]
Yes I'm the network folk lol.  We have no customizations, settings or scripts setup for Chrome so they're all default settings.  We also don't have a network as we mostly work from home and any data we have is cloud-based, no VPNs or firewalls either.

**Comment by luvsql** [comment]
Okay weird.  Opened Chrome incognito, logged in with O365 account and videos play.  Non-Incognito but as Guest Google account and videos play.  Non-Incognito with my google account, videos don't play.  I don't have any weird settings.  It works for a colleague with their google account so something in my settings must be causing this.

So sorry to bug.  I can live with me not using it.

**Comment by dcashpeterson** [comment]
@luvsql no problems at all. If you figure out what the setting was let us know so we can post it.
