### ISSUE TITLE
Hidden content is showing even after refresh in multiple browsers multiple users

### ISSUE THREAD

**Issue by luvsql** [pnp/custom-learning-office-365#661]
I have hidden categories and content yet they still keep showing.  Sometimes a refresh will hide it but now I have it open in 2 browsers and it's showing.  All the ones I have hidden show.  Multiple users affected.  Multiple refreshes does not fix issue.

![Screenshot (1744)](https://user-images.githubusercontent.com/104849149/166543226-f163327b-f114-448b-b081-e827e4dd3d86.png)

**Comment by v-ashrirao** [comment]
@luvsql, thank you for reporting this.
We will need few details from you to understand this better.

1. Are you getting any error when trying to hide playlist from Admin Portal?
2. Are you facing this issue with all playlists?

**Comment by luvsql** [comment]
Yes the issue happens with all playlists.  If I change one category to show, let it save, then hide again, it seems to fix all of them.

**Comment by luvsql** [comment]
The issue seemed to have been fixed this AM but after adding a new playlist to an existing category, all the categories are now visible again.  Showing a category again, letting is save, then hiding again then refreshes all the categories.

**Comment by dcashpeterson** [comment]
This is most likely due to the cache not being refreshed. If it continues to happen check the console for errors. You can also delete any entries in the custom config list with a title of CustomConfig. This will force the cache to refresh.

**Comment by dcashpeterson** [comment]
Closed and answered
