### ISSUE TITLE
Issue Updating MLP

### ISSUE THREAD

**Issue by Felie9** [pnp/custom-learning-office-365#662]
- [ ] Installation

### What is your question

After upgrading the version to 4.3.1 i get the following error for MLP. Do you have any idea what am i doing wrong? 
After I installed the new version, i ran the .\M365lpConfiguration.ps1 with telemetry false option.
![image](https://user-images.githubusercontent.com/104972835/166882927-560e594e-4d98-4db3-8650-7891146817d8.png)
![image](https://user-images.githubusercontent.com/104972835/166891336-7506740a-de93-41ad-88f2-36b0fea4d033.png)

I also tried with the ?forceUpdate=V2 and the error changed a bit:
![image](https://user-images.githubusercontent.com/104972835/166917377-f8b3f747-823a-473e-9591-2413b562f4c2.png)
(Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.) Probably this is triggered because we already tried updating this too many times and the app in the app catalogue has lots of versions?
![image](https://user-images.githubusercontent.com/104972835/166932064-0af73398-0745-4153-9f34-9c9551849cb8.png)

Many thanks!

**Comment by v-ashrirao** [comment]
@Felie9, Thank you for reporting this. Please allow us some time, we will get back to you ASAP.

**Comment by v-ashrirao** [comment]
@Felie9,

 Please let us know from which version you are trying to upgrade to 4.3.1?

We are assuming this issue is related to cache, please delete all entries with title 'CustomConfig' from CustomConfig list and open Admin page. it will force cache update.

**Comment by dcashpeterson** [comment]
If you ran the PowerShell script you might have also accidentally set the tenant app property incorrectly. There are 4 properties you need to set when you run the script TenantName, SiteCollectionName, AppCatalogAdminOnly SiteAdminOnly.

**Comment by Felie9** [comment]
> If you ran the PowerShell script you might have also accidentally set the tenant app property incorrectly. There are 4 properties you need to set when you run the script TenantName, SiteCollectionName, AppCatalogAdminOnly SiteAdminOnly.

I ran the script with my admin account (which has SHP admin rights and is also in site collection administrator in the Learning Site) 
Where can I check the Tenant properties if they are correct?

**Comment by dcashpeterson** [comment]
@Felie9 did you follow these instructions?

https://docs.microsoft.com/en-us/office365/customlearning/custom_update#:~:text=If%20you%20have%20an%20existing,the%20SharePoint%20tenant%20App%20Catalog.

If you did did you then go to the administrative site and run the upgrade script?

**Comment by Felie9** [comment]
> @Felie9 did you follow these instructions?
> 
> https://docs.microsoft.com/en-us/office365/customlearning/custom_update#:~:text=If%20you%20have%20an%20existing,the%20SharePoint%20tenant%20App%20Catalog.
> 
> If you did did you then go to the administrative site and run the upgrade script?

OK. I did not do this instructions because we are going still to use the site in EN version exclusively. However now i went and siwtched the toogle on then off then clicked Save. Now i should go again for the .\M365lpConfiguration.ps1 with the telemetry off?

**Comment by Felie9** [comment]
One question Though...the initalization of the Admin page should be done with the admin I ran the script? With the admin i seem to get more errors:
![image](https://user-images.githubusercontent.com/104972835/167172447-53a48673-5ef1-400d-bcad-2f7f7d349702.png)

**Comment by dcashpeterson** [comment]
@Felie9 If you are only using an English site then you don't need to have the Enable pages and news to be translated into multiple languages toggle on. You only need that if you are going to use more than one language.

For the upgrade to work you need to follow the instructions on the page I referenced AND the [Updating the Solution](https://github.com/pnp/custom-learning-office-365#updating-the-solution) documentation.

I would recommend running the M365lpConfiguration script again as well using an account that is a tenant admin.

Following that you should navigate to the Learning Pathways Admin page in your Learning Pathways site. This should force an upgrade. If it doesn't then you need to try and do it manually by going to customlearningadmin.aspx?forceUpdate=v2 if you are upgrading from V2 or v3 if you are upgrading from v3. When you go to the admin screen you need to be logged in as a user who is an Owner on the site. The user doesn't need to be a tenant admin like with the PowerShell script as that this is only updating the data in cache.

I hope this helps. If you still run into issues make sure that both the PowerShell script and the upgrade data complete with no errors. If there are any errors in those processes let us know.

**Comment by Felie9** [comment]
![image](https://user-images.githubusercontent.com/104972835/167348443-9e99304b-c089-44a9-baf9-1273d4f0c3fa.png)
Hey,
I followed the exact steps from there, I got no errors except the one with the page above. Force update does not work. You can see in my post the errors I got. 
What I see in the CustomConfig list is that the JSON data for CustomConfig default item points to v2 links. (for e.g https://pnp.github.io/custom-learning-office-365/v2/images/technologies/customfeatured.png" ) same for CustomSubCategories.

**Comment by Felie9** [comment]
Sooo, for anyone having that issue, I copied the JSON data from CustomConfig and for Custom SubCategories from a tenant on which i succesfully installed V4. This did the trick. (i suppose the script was not really deleting the items in the CustomConfig list, thus updating only the language column).
