### ISSUE TITLE
Add New Audience Items

### ISSUE THREAD

**Issue by luvsql** [pnp/custom-learning-office-365#663]
We would love to have an option to create our own Audience items for the drop-down to match our Employee's Roles.  This would allow our users to then find training materials related to them.

**Comment by v-ashrirao** [comment]
@luvsql, Thank you for your suggestion. Please allow us some time, we will provide you update on this ASAP.

**Comment by dcashpeterson** [comment]
@luvsql That is a great suggestion. We weighed this when we were architecting the solution. While we could technically make this possible we elected to not do this due to potential performance impacts. This is an open source project so if you are a developer or have access to a development team you are welcome to try and incorporate that. I would be happy to provide some guidance on this if you wanted to give this a try and submit a pull request.

**Comment by luvsql** [comment]
If we can't add, can we edit the existing descriptions?

**Comment by dcashpeterson** [comment]
You can't edit the descriptions on the Microsoft provided content unless you make a copy of the playlist. That is certainly supported but know that if you do that and Microsoft updates that playlist you will not get the updates automatically.

**Comment by luvsql** [comment]
Here is why it's so crucial for people.  When we post a bunch of training videos, not all Employees need to watch all of them.  We'd like to avoid having to create unique Categories per Role (because then the content is just repeated).  

You have one category listing all the videos and if I'm say a Project Manager, I select my role which is the audience and all the videos I need to watch are then filtered.  Currently we will have to list out in an email all the titles they need to watch per role. 

![Audience](https://user-images.githubusercontent.com/104849149/167170281-af899190-d5d8-497e-b96f-9e3fce8b90b1.png)

**Comment by dcashpeterson** [comment]
You can create a separate playlist for each role (eg project manager training) and create a SharePoint page for each role. On that page add the learning pathways webpart and set it to only show the project manager playlist. This way you can have them only see the trainings you want them to see. You can even host that page on a different SharePoint site like the PMO site. You can do what your asking for just not with a custom audience.

**Comment by luvsql** [comment]
I'm also going to be creating an app in Teams for this single site so I'm not sure if adding all these other SharePoint pages will cause an issue.  

How does the user invoke the different pages from the main site i.e. when do they choose their role that then filters the pages?

**Comment by dcashpeterson** [comment]
I don't know your use case but you can customize the learning pathways site so you can add a landing page with links to the difference role pages right on the home page or trade out the links in the hero web part. It's up to you. If you create a Teams app then I would create a landing page with all the roles on it and have that be the main page for the Teams App.
