### ISSUE TITLE
Add Duration Field to Playlist Item

### ISSUE THREAD

**Issue by luvsql** [pnp/custom-learning-office-365#664]
When we add a new playlist it would be very helpful for the viewers to know the duration so either have it pull from the uploaded content or a manual field we can type it in.  This will help our Employees plan their time.

**Comment by v-ashrirao** [comment]
@luvsql, Thank you for your suggestion. Please allow us some time, we will provide you update on this ASAP.

**Comment by dcashpeterson** [comment]
@luvsql  That is a great suggestion. Unfortunately, we don't have any way of knowing either the read time or the length of the content in Learning Pathways. The content is pulled in through an IFrame so we have no programatic knowledge of the content regardless if it is coming from SharePoint or Microsoft. It treats it all the same. Thank you for the suggestions but this isn't technically possible. I am going to close this item.

**Comment by luvsql** [comment]
Right so if it can't be calculated, could there at least be a field to fill in so it can be used?

**Comment by dcashpeterson** [comment]
It can't be as we don't support custom metadata on assets. If that was the case we would end up with an awkward user experience where all the Microsoft provided content would not have that information and the custom content would which would be very confusing for the user as the source of the content is not apparent to them and you can mix and match.
