### ISSUE TITLE
Sort on Subcategory Setup not matching 

### ISSUE THREAD

**Issue by luvsql** [pnp/custom-learning-office-365#665]
Does anyone know what the sort behaviour should be or how we sort the playlists?  On the right is the configuration setup and the left is how the playlists open.  Both sorts completely different.  I'd either like to choose the sort or at least have it sorted alphabetically.  
![Sort Issue](https://user-images.githubusercontent.com/104849149/167689547-f2b4b19f-fbd3-4106-ba35-d1112bfd5128.png)

**Comment by v-saikirang** [comment]
Hi @luvsql,

Thanks for your feedback. Please allow us some time. We will check and get back to you on this.
Thanks.

**Comment by v-saikirang** [comment]
Hi @luvsql,

Can you please check this link and see if it helps you. 
https://docs.microsoft.com/en-us/office365/customlearning/custom_sortsubplay
Thanks.

**Comment by luvsql** [comment]
I'm desperate to get another issue with Chrome fixed but haven't received any reply since last week.  Can someone help with that one?  NO Microsoft content plays with Chrome.

**Comment by v-ashrirao** [comment]
@luvsql, 
Can you please refer below link and let us know if that help? 
https://docs.microsoft.com/en-us/office365/customlearning/custom_linking

**Comment by v-ashrirao** [comment]
@luvsql, Is there any other information you need on this? If not, can we close the issue?

**Comment by luvsql** [comment]
Yes you can close.  I'm living with the sort issue.
