### ISSUE TITLE
 Microsoft 35 learning pathways has a configuration issue. Ask your administrator for assistance. 

### ISSUE THREAD

**Issue by pvittaltx** [pnp/custom-learning-office-365#672]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

We have 2 domains in our enterprise -HHS and DSHS. When users in the DSHS domain attempt to access the Microsoft 365 learning pathways they get the error mesage saying "Microsoft 35 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators Please use the browser console for detailed logs For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues]

There isnt much info here for me to help troubleshoot. Please help!

### To Reproduce

>Steps to reproduce the behavior

### Expected behavior

>A clear and concise description of what you expected to happen.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.
![image](https://user-images.githubusercontent.com/107137516/172681089-69f33ecc-09bc-45f6-923d-24f0f157f04d.png)

**Comment by dcashpeterson** [comment]
@pvittaltx I am not 100% clear on your setup. Do you have one tenant or two? If you have one tenant with two URLs associated with it I am assuming that this is a result of the tenant app property. You can check for errors in the browser console. You can reference #572. The tenant app property tells Learning Pathways where all the configuration data is and it needs to match the tenant that the user is coming in from. We do not support a scenario where you have multiple URLs for the same tenant. If you have two tenants then you need Learning Pathways installed in both tenants with the app property set correctly in both tenants. I hope this helps. Let me know if you have any any additional questions.

**Comment by Satpaul692** [comment]
@dcashpeterson  I raised a similar issue back in April, from which you provide the following response regarding permissions, however this was n/a. We have a shared O365 tenancy, one of the other tenants inadvertently broke the learning pathways site.  Out of the 3 tenants we are the only tenant that actually use this for our user base, through a link within the MS Teams app. So the question what do we need to do to rectify this issue for our tenant? I can send you the F12 developer tools logs if required.

@Satpaul692 Thanks for reaching out. That error you are referencing has to do getting the cache from the customconfig list. That list lives in the Learning Pathways admin site. Check the permissions on that library and see if anything has changed and that the user in question has access. Everyone needs the ability to read from that list in order to get the data from the cache.

![image](https://user-images.githubusercontent.com/104211232/174311673-c877568b-f29d-4275-a28b-7f7163e44695.png)

**Comment by Satpaul692** [comment]
@dcashpeterson please find attached the logs from F12 developer tools - I've hidden the name of our tenancy with XYZ, however this should not stop you from troubleshooting. Much appreciated if you can provide us with a fix. Thanks.
[MS365LearningPathwayErrors.log](https://github.com/pnp/custom-learning-office-365/files/8928392/MS365LearningPathwayErrors.log)
.

**Comment by dcashpeterson** [comment]
@Satpaul692 I took a look at this. Can you get this value from PowerShell? Get-PnPStorageEntity -Key MicrosoftCustomLearningSite see if it matches the URL of your site?

**Comment by Oegl** [comment]
Hi! I have the same issue. I'm using version 4.3.0.
When checking the console log, there is a 404 exception for: https://....sharepoint.com/sites/applications/_api/web/lists/getByTitle('CustomConfig')/items?$select=Id,Title,JSONData&$filter=Title%20eq%20%27CustomCDN%27&$top=1

When clicking on this link, and open it in a new tab - I get the following displayed
![image](https://user-images.githubusercontent.com/65904352/176655952-959c99aa-6a9d-4208-a19f-cb2d8478afce.png)

**Comment by Oegl** [comment]
I checked the lists and recognized that the list "CustomConfig" had broken permission inheritance - with enabling it, everything worked as expected!!!

**Comment by dcashpeterson** [comment]
@Oegl glad things worked out. That's a common issue if people edit permissions on those lists.
