### ISSUE TITLE
Unable to access the SharePoint lookbook M365LP 

### ISSUE THREAD

**Issue by Emilie-Garnaud** [pnp/custom-learning-office-365#673]
## Describe the bug

I have 2 issues : 

1. I tried, this morning, to provision de M365LP, unfortunately I didn't know that a site with the same URL already exists in my tenant and I had an issue during the povisioning. I cheched in my App Catalogue, and "Microsoft 365 learning pathways" is in my applications list. But not deployed on a site collection. So I wanted to start again the process.

1. But now, I'm unable to access this link https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239  to install learning pathways into my tenant. this link redirect me on th SharePoint look book home page.

### To Reproduce

go to https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239

### Learning Pathways version number

4.3.0.0

**Comment by dcashpeterson** [comment]
@Emilie-Garnaud  This is an issue with the provisioning service. You can report it in this repo. They have access to it and can help you. 
[SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues)

**Comment by Emilie-Garnaud** [comment]
@dcashpeterson thank you for your reply, I'll report it here.
