### ISSUE TITLE
Learning Pathways content not loading 

### ISSUE THREAD

**Issue by jefmeyer** [pnp/custom-learning-office-365#681]
## Describe the bug

All Learning Pathways content is not displaying.  

### To Reproduce

1. Navigate to any Learning Pathways page, the page header and footer load, however external content is not appearing.  All users are impacted by this issue and is not browser specific.

### Expected behavior

1. The external content for Learning Pathways should appear.

### Screenshots

![image](https://user-images.githubusercontent.com/22027681/178500316-0584eb95-edb7-4c3b-8100-c1dbba9e8963.png)
![image](https://user-images.githubusercontent.com/22027681/178500568-2e3afb5b-85db-4857-9db3-a109801393ef.png)
![image](https://user-images.githubusercontent.com/22027681/178500991-45e846f2-a1b0-4610-8acd-044365486f71.png)

### Learning Pathways version number

4.3.0

### Additional context

N/A

**Comment by v-ashrirao** [comment]
@jefmeyer, Thank you for reporting this. Please allow us some time, we will get back to you ASAP.

**Comment by v-ashrirao** [comment]
@jefmeyer, we will need few more details to understand this issue,

Is CustomLearningAdmin.aspx page is loading correctly?
Are you using any custom content pack?
Are there any other errors also in console?

**Comment by jefmeyer** [comment]
Hi @v-ashrirao -

Thanks for the response.

1. CustsomLearningAdmin.aspx is loading, however it's a blank page in the content area.
![image](https://user-images.githubusercontent.com/22027681/179238876-0092345d-728b-4f29-9f0c-868b2028a64e.png)

2. We are not using a custom content pack.
3. These are the only errors in the console: 
![image](https://user-images.githubusercontent.com/22027681/179238834-be7efd6d-0589-45eb-9af5-15bbab0e1a6b.png)

Thanks for your assistance.  Please let me know if you need anything else.

**Comment by jefmeyer** [comment]
Hi @v-ashrirao 

1. The LP package is in our tenant app catalog. 
![image](https://user-images.githubusercontent.com/22027681/179245590-a08a1853-5056-4032-ae21-0f4f8b08f21e.png)
2. Site Contents: 
![image](https://user-images.githubusercontent.com/22027681/179245850-35d29f9f-ef21-42bd-a5db-edb1c5a000c3.png)
3. I'm not able to open in Edit mode.  There is an uncaught exception:
![image](https://user-images.githubusercontent.com/22027681/179246126-60625405-d03d-4ddb-a060-45ece7a75505.png)

Please let me know what else you may need.
