### ISSUE TITLE
[ENHANCEMENT] Invoke "Next" asset button 

### ISSUE THREAD

**Issue by 51iMM** [pnp/custom-learning-office-365#683]
It would be great to have a webpart that invokes the Next asset in playlist.
Or as an alternative have an option in Microsoft 365 learning pathways web part to also add the Next button on the bottom of the page.
If I have a fairly long text/guide it requires a lot of scrolling to go to top of page and invoke the next asset.
It kind of breaks the intuitive workflow.

**Comment by v-prigunasek** [comment]
Hi @51iMM ,

Thank you for your suggestion for an enhancement.

**Comment by dcashpeterson** [comment]
@51iMM we have just released the V5 beta for testing that includes a sticky header for the assets to on assets that have a long page you will still have the ability to see the next and previous buttons. We invite you test the new version.
