### ISSUE TITLE
learning content from the learning pathway Microsoft is not available for our users

### ISSUE THREAD

**Issue by Ang2022** [pnp/custom-learning-office-365#686]
Good morning,

We have made available the Microsoft
<img width="413" alt="image" src="https://user-images.githubusercontent.com/110174128/181511949-d89aad5a-08fa-4d44-a243-02e65ac65aa7.png">
t Learning Pathway site but when users try to view a pathway, they get this error message

Here the error message : the Microsoft Learning path has a configuration problem, ask your administrator for help

Microsoft learning pathway vesion  : 4.3.1.0
release date : July 2022

**Comment by v-prigunasek** [comment]
Hi @Ang2022, 

Thank you for reporting this issue here. This error is generally caused by a few things.

1. The installation wasn't done with an administrative account so the tenant app property didn't get set properly.
2. The site was renamed and the tenant app property wasn't changed to go with it.
3. Permissions to the config list have been changed.

Can you please validate these and let me know if you are still seeing the error message?

Additionally, can you provide some more information about whether this issue is happening for all users or guest/external users. If you attach the browser console logs, that would be helpful for us to figure out more details about the error. Thanks!

**Comment by Ang2022** [comment]
Hello V-Pringunasek,

thank you for your answer, concerning the causes that you describes
[Error.docx](https://github.com/pnp/custom-learning-office-365/files/9221163/Error.docx)

1. The installation was done by an administrative account tenant
2. No, the sharepoint site has not been renamed and neither the tenant
3. Concerning your last point : we don't know what is this Config list and where is it ? and what we have to do about ? can you help us with more information 

Only the administrative account tenant ( the account that we used to create the site can watch the pathways ) 
We tested to pass some internal users as site admin and after as visitor and as editor and we have always the same error (all people have access to the site but not at the pathways)

Thank you so much for your help ( we expend a lot of time triging to fixe this issue and we don't know what more to do.

**Comment by dcashpeterson** [comment]
Have you tried the DiagnosisPreCheck first?
https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md

Please follow the instructions there.

**Comment by v-prigunasek** [comment]
Hi @Ang2022,

Would like to know whether you are able to run the DiagnosisPreCheck ?

Thanks

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new issue and reference this one.

**Comment by Ang2022** [comment]
Hi @dcashpeterson 

Sorry for my late answer,
We have always the same error after the diagnostic and we don't know how to fix it.
Please find here the screenshoot.

![Issue learning pathway](https://user-images.githubusercontent.com/110174128/184838982-19ca4673-7a9b-4fba-9841-336ba310a6ae.png)

Could you help us ? thank you in advance.

**Comment by dcashpeterson** [comment]
@Ang2022 from the errors you can see that the user in question doesn't have access to the configuration lists. So either the config lists don't exist in the site collection that the app thinks they should synergies365 or the current user doesn't have access to those lists. All users need read/write access to the config lists and we break inheritance when those lists are created.

**Comment by Ang2022** [comment]
Hello @dcashpeterson thank you for your answer.
We dont know where are those configuration lists
could you tell me where we can give access to the configuration list to users ?
Thank you

**Comment by dcashpeterson** [comment]
The webpart is looking for the config lists in the Synergies365 site collection.

**Comment by ralphberenics** [comment]
I've encountered the exact same error message as Ang2022.  I'm accessing the learning pathway via Airforce DAF365 Hub.  Will you be correcting the Microsoft 365 learning pathway soon.. i'm trying to find some old MS Teams New User training.  Thank you!

**Comment by ralphberenics** [comment]
![Capture](https://user-images.githubusercontent.com/111446936/185179067-4674b701-01d0-4871-a376-5728b7368de7.PNG)

**Comment by dcashpeterson** [comment]
@ralphberenics I'm not sure what the issue you are experiencing. As you can see from the responses above the issue that @Ang2022 reported is that when the webpart loads it can't find the lists either based on permissions or that the lists are not there. Based on what you are showing me I can't assume that this is the same issue. That is a generic error. Are you able to see errors in the console? We can't really assist based on what you are showing in your screenshot. It also looks like your tenant might be experiencing a service outage as well.

**Comment by Ang2022** [comment]
Hello @ralphberenics I'm looking in the site collection but I dont know what to do ? where I have to click to fix the problem.
you said : The webpart is looking for the config lists in the Synergies365 site collection...in this case, where I have to click and what I have to do ? sorry I'm lost.

Im looking in the collection site where I shared with you my screenshot and the next steps are ?

<img width="1092" alt="error" src="https://user-images.githubusercontent.com/110174128/185182476-dc7df57e-819b-430d-bb37-be4043f36677.png">

**Comment by dcashpeterson** [comment]
@Ang2022 The configuration lists are there CustomAssets, CustomConfig, and CustomPlaylists. CustomAssets and CustomPlaylists inherit permissions from the site. CustomConfig needs to have Members - Edit, Owners - Full Control, Visitors - Contribute. Permissions for the site should be like this Members - Edit, Owners - Full, Visitors - Read.

It looks like the lists exist in the site collection you are showing in the previous screen shot. What site collection is that?

**Comment by Ang2022** [comment]
Hello @dcashpeterson THANK YOU SO MUCH !!
We finnally undertood the problem and finally that is fixed :) our users can use the site.

thanks, thanks :)

**Comment by jeancapi** [comment]
hi @dcashpeterson and @Ang2022 ,

I am from Ecuador, I have the learning pathway installed but it is generating this error when accessing, it worked normally, suddenly this error appears, can you help me please,

they do not load the playlists and do not allow the site administrator to enter

Please can you help me!!

![image](https://user-images.githubusercontent.com/111772061/185964394-5fbf0ad4-c38c-4be7-b84f-0312d3a805c6.png)

**Comment by dcashpeterson** [comment]
@jeancapi If you could please open another issue, follow the template and provide all the necessary information that would be great. That is a generic warning/error so you should run through the process in the issue template to give us more information so we can better assist.

**Comment by jeancapi** [comment]
thank you very much, i just opened it https://github.com/pnp/custom-learning-office-365/issues/694
