### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by Matt-Mueller-MSFT** [pnp/custom-learning-office-365#687]
Is Learning Pathways no longer supported by the SP Provisioning service? I noticed today that Learning Pathways was not on the SharePoint Lookbook Provisioning service site. I know it was there Friday as shared the link with a customer. Today when going there to show them how, it was missing. Please advise.

**Comment by dcashpeterson** [comment]
@Matt-Mueller-MSFT let me talk with the team that manages the lookbook and get back to you. Thanks for bringing this up.

**Comment by dcashpeterson** [comment]
There was an unplanned issue with the synchronization in the LookBook that caused Learning Pathways to show up. The issue has been resolved. Thank you for reporting it.
