### ISSUE TITLE
Adding a custom product and playlist 

### ISSUE THREAD

**Issue by NadegeG64** [pnp/custom-learning-office-365#691]
**## Describe the bug**
I created a custom product for a software that we use.
I can see it at the bottom of the Product menu (attachment 1)
![1](https://user-images.githubusercontent.com/110918692/183687401-d5ff2ddc-190e-4e46-9af0-600ed27ccdcd.JPG)
I added content on that playlist.
![2](https://user-images.githubusercontent.com/110918692/183687467-eaadecff-025f-4fc2-8bb1-48ffd9a6f1c1.JPG)

**A clear and concise description of what the bug is.**
This product doesn't appear for users though visibility is on.
![3](https://user-images.githubusercontent.com/110918692/183688246-5d79f5ab-cb0a-4582-98e0-0e766680538e.JPG)
![4](https://user-images.githubusercontent.com/110918692/183688423-9fe5e9ce-dbdf-45bf-9df9-b98ecc7ff9f2.JPG)

Same trouble with adding a playlist to an existing product (ie to Teams).

**### To Reproduce**

**>Steps to reproduce the behavior**
-> Administration success center
+ Add a new sub categorie (bottom of the page)
Enter a name for that category
Add an image. Save.
+ to add a playlist

### Expected behavior

>A clear and concise description of what you expected to happen.
I expected this new product or  to appear in my product list or my playlist to show at the end of by default playlists.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number
>Please share the version number of learning pathways in your tenant app catalog.
4.3.1
![7](https://user-images.githubusercontent.com/110918692/183697236-7bea2978-d33c-4e86-8568-a20fe58d7b9f.jpg)

### Additional context

>Add any other context about the problem here.

**Comment by dcashpeterson** [comment]
@NadegeG64 Do you have a French version of the subcategory, category etc? If you don't it will not show for you as your language is set to French. You need both an English version of the content and French version. Try adding in the additional language support and see if that works.

**Comment by NadegeG64** [comment]
A huge thank you Dereck, for your quick response but also for the solution.
This was indeed the origin of the problem.
I thought it was automatic because I had selected the automatic translation option...
Have a great day and thanks again for your help.

Cordialement,

Nadège Guilbert
Office Manager
Office Manager
+33 (0)1 81 80 24 50
16 rue brancion 75015 - France | +33 (0)1 81 80 24 50

***@***.***<https://observia-group.com/fr/>
***@***.******@***.***<https://www.youtube.com/channel/UCqLh4GlUG64IT59RFqCLfjQ/videos> ***@***.*** <https://twitter.com/Observia_Esante>
Observia-group.com
Améliorons la santé de notre planète également ! Merci de n'imprimer ce courriel qu'en cas de nécessité.

De : Derek Cash-Peterson ***@***.***>
Envoyé : mardi 9 août 2022 18:41
À : pnp/custom-learning-office-365 ***@***.***>
Cc : Nadège Guilbert ***@***.***>; Mention ***@***.***>
Objet : Re: [pnp/custom-learning-office-365] Adding a custom product and playlist (Issue #691)


@NadegeG64<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNadegeG64&data=05%7C01%7Cnadege.guilbert%40observia-group.com%7C5ab281db766d46e59cec08da7a25e356%7Cdb94e56f10944017a53d2cb857b9d5b8%7C0%7C0%7C637956600399366465%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kOgvS71fJIKLBLtcxUZmvN%2BgxDbmLRHLWW5rf%2BzNZIM%3D&reserved=0> Do you have a French version of the subcategory, category etc? If you don't it will not show for you as your language is set to French. You need both an English version of the content and French version. Try adding in the additional language support and see if that works.

-
