### ISSUE TITLE
Multi lingual issue 

### ISSUE THREAD

**Issue by NadegeG64** [pnp/custom-learning-office-365#693]
## Describe the bug
Good afternoon,
I have installed a multi lingual version of the learning pathways (English and French).
When I select the starting page and Language English, the menu still appears in French though the page is in English
![1](https://user-images.githubusercontent.com/110918692/185646810-fdca8735-4fdf-4535-9ccc-fbdb43c4984f.JPG)
Note that the default menu IS in English
![3](https://user-images.githubusercontent.com/110918692/185648343-2cfa2fff-6964-4cc0-a912-b35e1f924933.JPG)

Same problem with the dynamic pages such as recommended playlists:
though the selected langage is English, the dynamic part appears in French
![2](https://user-images.githubusercontent.com/110918692/185647480-e75b88f9-d9d4-4616-baf5-079fb682ced1.JPG)

Thanks in advance for your help

### To Reproduce

>Steps to reproduce the behavior

### Expected behavior

I expected the dynamic content and menu to be in the selected language.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.

**Comment by dcashpeterson** [comment]
@NadegeG64 that is as designed. Learning Pathways uses the SharePoint Framework to determine the users language and determining what language to show the content in. Your language preference is set to French in your profile so regardless of what setting you change the language interface on the page to you will see French. If you would like to see the English content you would need to change your language preference in your Delve profile.

**Comment by NadegeG64** [comment]
Thank you so much for your help, Derek. I'll check that point.

I have a last trouble: I shared the learning website but people in my organization get an error message.
***@***.***
Microsoft 365 learning pathways have a configuration issue. Ask your administrator for help (Administrator: for more information, see the browser console).

I do not understand the reason of this trouble as I did as I do for all other sharepoint sites.


Cordialement,

Nadège Guilbert
Office Manager
Office Manager
+33 (0)1 81 80 24 50
16 rue brancion 75015 - France | +33 (0)1 81 80 24 50

***@***.***<https://observia-group.com/fr/>
***@***.******@***.***<https://www.youtube.com/channel/UCqLh4GlUG64IT59RFqCLfjQ/videos> ***@***.*** <https://twitter.com/Observia_Esante>
Observia-group.com
Améliorons la santé de notre planète également ! Merci de n'imprimer ce courriel qu'en cas de nécessité.

De : Derek Cash-Peterson ***@***.***>
Envoyé : mardi 23 août 2022 11:47
À : pnp/custom-learning-office-365 ***@***.***>
Cc : Nadège Guilbert ***@***.***>; Mention ***@***.***>
Objet : Re: [pnp/custom-learning-office-365] Multi lingual issue (Issue #693)


@NadegeG64<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNadegeG64&data=05%7C01%7Cnadege.guilbert%40observia-group.com%7C5b8e58cf16224f9129e808da84ec85ee%7Cdb94e56f10944017a53d2cb857b9d5b8%7C0%7C0%7C637968448636912298%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FsNxbZ8l7JiKngKxkDbapiY7WOMRukY5hOqUx9YX2ws%3D&reserved=0> that is as designed. Learning Pathways uses the SharePoint Framework to determine the users language and determining what language to show the content in. Your language preference is set to French in your profile so regardless of what setting you change the language interface on the page to you will see French. If you would like to see the English content you would need to change your language preference in your Delve profile.

-

**Comment by dcashpeterson** [comment]
If you are receiving that warning before we can assist we ask that you follow the following.
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

In addition, if there are any errors in the browser console we need to see those. That is a generic error message and we can't troubleshoot based on that.

**Comment by dcashpeterson** [comment]
@NadegeG64 I can't really tell from these screen shots. From the look of things it looks like you did not see the metadata.json file. Is that correct? And can you confirm you are checking this from the CustomLearningAdmin.aspx page? Are there any other errors in the console?

**Comment by NadegeG64** [comment]
Hi Derek,

Thank you for your quick answer.


  *   Yes I didn't see the metadata.json.
  *   Yes, I activated the console from the Customlearningadmin.aspx page.

All I see in the console is that:

***@***.***


Cordialement,

Nadège Guilbert
Office Manager
Office Manager
+33 (0)1 81 80 24 50
16 rue brancion 75015 - France | +33 (0)1 81 80 24 50

***@***.***<https://observia-group.com/fr/>
***@***.******@***.***<https://www.youtube.com/channel/UCqLh4GlUG64IT59RFqCLfjQ/videos> ***@***.*** <https://twitter.com/Observia_Esante>
Observia-group.com
Améliorons la santé de notre planète également ! Merci de n'imprimer ce courriel qu'en cas de nécessité.

De : Derek Cash-Peterson ***@***.***>
Envoyé : lundi 29 août 2022 12:15
À : pnp/custom-learning-office-365 ***@***.***>
Cc : Nadège Guilbert ***@***.***>; Mention ***@***.***>
Objet : Re: [pnp/custom-learning-office-365] Multi lingual issue (Issue #693)


@NadegeG64<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNadegeG64&data=05%7C01%7Cnadege.guilbert%40observia-group.com%7C4eb88aaa8c9b4038448b08da89a750bb%7Cdb94e56f10944017a53d2cb857b9d5b8%7C0%7C0%7C637973648944320973%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LfxloDKR7P7%2FYwndU%2BuCYawanOVBWQWf2phtpV7gKq8%3D&reserved=0> I can't really tell from these screen shots. From the look of things it looks like you did not see the metadata.json file. Is that correct? And can you confirm you are checking this from the CustomLearningAdmin.aspx page? Are there any other errors in the console?

-

**Comment by NadegeG64** [comment]
Hope this will be more useful :

***@***.***

Cordialement,

Nadège Guilbert
Office Manager
Office Manager
+33 (0)1 81 80 24 50
16 rue brancion 75015 - France | +33 (0)1 81 80 24 50

***@***.***<https://observia-group.com/fr/>
***@***.******@***.***<https://www.youtube.com/channel/UCqLh4GlUG64IT59RFqCLfjQ/videos> ***@***.*** <https://twitter.com/Observia_Esante>
Observia-group.com
Améliorons la santé de notre planète également ! Merci de n'imprimer ce courriel qu'en cas de nécessité.

De : Derek Cash-Peterson ***@***.***>
Envoyé : lundi 29 août 2022 12:15
À : pnp/custom-learning-office-365 ***@***.***>
Cc : Nadège Guilbert ***@***.***>; Mention ***@***.***>
Objet : Re: [pnp/custom-learning-office-365] Multi lingual issue (Issue #693)


@NadegeG64<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNadegeG64&data=05%7C01%7Cnadege.guilbert%40observia-group.com%7C4eb88aaa8c9b4038448b08da89a750bb%7Cdb94e56f10944017a53d2cb857b9d5b8%7C0%7C0%7C637973648944320973%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LfxloDKR7P7%2FYwndU%2BuCYawanOVBWQWf2phtpV7gKq8%3D&reserved=0> I can't really tell from these screen shots. From the look of things it looks like you did not see the metadata.json file. Is that correct? And can you confirm you are checking this from the CustomLearningAdmin.aspx page? Are there any other errors in the console?

-

**Comment by NadegeG64** [comment]
Here is the complete log.
Thank you for your help and time Derek.


Cordialement,

Nadège Guilbert
Office Manager
Office Manager
+33 (0)1 81 80 24 50
16 rue brancion 75015 - France | +33 (0)1 81 80 24 50

***@***.***<https://observia-group.com/fr/>
***@***.******@***.***<https://www.youtube.com/channel/UCqLh4GlUG64IT59RFqCLfjQ/videos> ***@***.*** <https://twitter.com/Observia_Esante>
Observia-group.com
Améliorons la santé de notre planète également ! Merci de n'imprimer ce courriel qu'en cas de nécessité.

De : Derek Cash-Peterson ***@***.***>
Envoyé : lundi 29 août 2022 13:25
À : pnp/custom-learning-office-365 ***@***.***>
Cc : Nadège Guilbert ***@***.***>; Mention ***@***.***>
Objet : Re: [pnp/custom-learning-office-365] Multi lingual issue (Issue #693)


Sorry to be a pest but can you remove the filters and click on the tab that says console in the developer tools. If there are no error there then I don't really have anything else to go on. The site was working and now it isn't so something changed. If you are getting the contact your admin error that means the webpart is loading so it should be throwing something into the condole.

-

**Comment by dcashpeterson** [comment]
If you respond via email sometimes attachments don't come through. I didn't get any log information.

**Comment by NadegeG64** [comment]
[LOG1661776590782.log](https://github.com/pnp/custom-learning-office-365/files/9444591/LOG1661776590782.log)

Meanwhile, I tested with another colleague: she could access to the page.
I will check again with the manager that experienced the troubleshooting...

**Comment by dcashpeterson** [comment]
I looked through the logs and there is only one error in there and it isn't coming from learning pathways. What you are showing in the example is the same web part configuration as is on the getting started page and you can see that it has Welcome and Products on it. It looks like you have customized content here (showing/hiding, adding new playlists) which is all great but because the site was set up with English as the default language (this is the default if you used the LookBook) you will need the english content as well as the french content for it to show up. This sounds like a permissions or a translation related issue to me.

**Comment by dcashpeterson** [comment]
Closed due to inactivity.
