### ISSUE TITLE
 error in playlists "learning pathway Microsofr 365 have a configuration error. ask for administrator for help" 

### ISSUE THREAD

**Issue by jeancapi** [pnp/custom-learning-office-365#694]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

When entering learning training or any playlist I get the error "Microsoft 365 learning paths has a configuration problem. Please ask your administrator for help". and when trying to enter the "learning via administration" it stays loading without opening. It should be noted that the site opened without problems but it is giving an error, I tried to restore to an earlier date but the problem persists.

### Expected behavior

the site worked normally for me and for other users but from one moment to another the error appears and it does not allow to review the native playlists

### Screenshots

![image](https://user-images.githubusercontent.com/111772061/185968939-cb1cf80b-b5ec-48c0-88f0-7aff58ac466d.png)
![image](https://user-images.githubusercontent.com/111772061/185972378-c987371c-3dca-4a52-a052-4d460fff47b5.png)

### Learning Pathways version number

![image](https://user-images.githubusercontent.com/111772061/185972856-ff390190-2cd9-4f1e-9afb-39007464523e.png)

**Comment by jeancapi** [comment]
please @dcashpeterson

**Comment by dcashpeterson** [comment]
in order to help can you please follow the Diagnosis pre-check and provide any results from that 
WEB PART NOT LOADING: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

and if there are any errors in the console please provide that.

**Comment by dcashpeterson** [comment]
closed due to inactivity. If this is still an issue feel free to create a new issue and reference this one.
