### ISSUE TITLE
Problem with the Learning pathway template

### ISSUE THREAD

**Issue by maye-vargas** [pnp/custom-learning-office-365#695]
At the moment I enter the link https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
It doesn't let me log in or it doesn't show me the LP template, which doesn't let me generate the learning pathway template.
At the moment is there any other link that I can use to implement the learning pathway?
![image](https://user-images.githubusercontent.com/86726190/187255843-23dd2405-c3b0-424a-9dc2-e510ca487b8f.png)

**Comment by v-prigunasek** [comment]
Hi @maye-vargas,

The direct URL to Learning Path template is the one you have mentioned - https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239

If that doesn't work, alternatively you can access it from here - https://lookbook.microsoft.com/ page. Scroll down on this landing page, you can find the Learning Pathways template under "Solutions" tab.

![image](https://user-images.githubusercontent.com/98514691/187341674-e509aa72-682d-4911-8a9f-f34a75b0af94.png)

**Comment by dcashpeterson** [comment]
@maye-vargas This was a temporary issue with the provisioning engine and has been resolved.
