### ISSUE TITLE
Learning Pathways no longer available in the Look Book Service

### ISSUE THREAD

**Issue by shirazgaff** [pnp/custom-learning-office-365#696]
Learning Pathways no longer available in the Look Book Service. Unable to provision

**Comment by v-prigunasek** [comment]
Hi @shirazgaff ,

Thanks for reporting the issue. This might be a temporary glitch with the provisioning engine, can you please try after few hours?

Thanks!

**Comment by dcashpeterson** [comment]
It is back online
