### ISSUE TITLE
 Reprise: "I can't create subcategories under the Scenarios category"

### ISSUE THREAD

**Issue by tandrasi** [pnp/custom-learning-office-365#697]
## Describe the bug

@juliemturner, I'm bringing you in directly due to your correspondence on the virtually identical bug previously posted on August 5, 2020: **"I can't create subcategories under the Scenarios category**" (https://github.com/pnp/custom-learning-office-365/issues/334).

Hi, I've been working with a client to set up a custom learning pathways experience. The idea was to simply set up three content packs, each only containing high-level categories so that they could create sub-categories, playlists, and assets via the UI on their own without assistance or any intervention from our end.

Now, the three content packs are

1. Technical
2. Business
3. Interpersonal

I mention this because only the "Technical" content pack is experiencing the issue **of not being able to create subcategories under certain categories**.

Currently, the "Technical" content pack looks like this:

- Company Knowledge
-- Company direction
-- Office 365: Excel
-- Tender writing
-- [working subcategories exist here and we can create more]
- Computer Science
-- [working subcategories exist here and we can create more]
- Data Science
-- [working subcategories exist here and we can create more]
- Industry Knowledge
-- [working subcategories exist here and we can create more]
- Modelling
-- [working subcategories exist here and we can create more]
- LITERALLY ANY OTHER CATEGORY THAT IS CREATED
-- [cannot create subcategories via UI]

When attempting to create any subcategories under any categories as depicted above in the CustomLearningAdmin site, I get a console error in dev tools:

>🎓 **M365LP:CustomLearningAdmin (upsertSubCategory) - TypeError: Cannot read properties of undefined (reading 'SubCategories')**

### To Reproduce

I cannot say exactly what triggered it, but:

- The "Technical" content pack was the first one to get provisioned;
- It has seen the most changes due to a shift in requirements leading us to end up with a vastly different approach to layout/structure;
- I don't believe any Categories have had their IDs changed;
- Categories have had their names changed;
- Audiences were added, removed, and generally shifted around the categories

### Way To Fix (by way of reset and data loss - NOT an option)

Simply recreating the content pack from https://infexious-dev.github.io/tf-learning-pathways-technical/custom/ resets everything, giving the content pack a new Id in the CustomConfig list and everything works as expected, without a single issue. This is not an option due to the sheer amount of data currently present as custom config.

**I think the cause is because the existing content pack has seen quite a few changes that something is inherently broken with in the CustomConfig list**.

### Screenshots

These are the items in "CustomConfig" from which I have exported the "JSONData" field.

![image](https://user-images.githubusercontent.com/72114492/188428827-59cb60ac-e1e4-4284-b717-62011ccfdf46.png)

### Learning Pathways version number

4.3.1.0 (fresh install via look book service)

### Attachments

I've attached five files spread across two .zip files:

A "metadata.json" which dictates the layout of the "Technical" content pack. There are no assets or playlists directly in the content pack. Note please that I have removed the additional categories that aren't working as the client needed to go live with their users.

I've also attached a .zip "CustomSubCategories.json", "CustomConfig-1.json", "CustomConfig-2.json", and "CustomConfig-3.json" are all exports of respective JSONData fields from the "CustomConfig" list. See the screenshot above for context.

>[TechnicalContentPack-metadata.json.zip](https://github.com/pnp/custom-learning-office-365/files/9489104/TechnicalContentPack-metadata.json.zip)
>[CustomConfig.zip](https://github.com/pnp/custom-learning-office-365/files/9489102/CustomConfig.zip)

**Comment by v-prigunasek** [comment]
Hi @tandrasi , 

Just to inform you, we are still looking into this issue. Will keep you posted. Thanks!

**Comment by lamargardner565** [comment]
Good morning, any update on this?  I have a customer that is experiencing the same exact issues.

**Comment by v-prigunasek** [comment]
Hi @lamargardner565 ,

This seems to be a bug and Derek would be checking on that to fix it. 

The issue happens when I have some Categories and SubCategories already created in the custom content pack and then if I try to add new Category in Metadata.json file as given below.
{
      "Id": "f4874a2c-8788-4631-93ac-d5203a888009",
      "Name": "Business Management",
      "Image": "",
      "TechnologyId": "",
      "SubjectId": "",
      "Source": "",
      "SubCategories": []
    }

Once I refresh the admin webpart after adding the new Category in the metadata.json file, an entry for the above category will be automatically added to the JSONData of the "CustomConfig" item but not to the "CustomSubCategories" item. This missing entry in the CustomSubCategories item is throwing an error.

![image](https://user-images.githubusercontent.com/98514691/228467868-bb8b5e76-f7d3-4e50-afea-8c25e38de1fc.png)

As a workaround, I have manually added the below entry in the JSONData of the CustomSubCategories item and refreshed the webpart. Then tried to add a SubCategory under this new Category from UI and it worked as expected.
{
            "Id": "f4874a2c-8788-4631-93ac-d5203a888009",
            "Name": "Business Management",
            "Image": "",
            "TechnologyId": "",
            "SubjectId": "",
            "Source": "",
            "SubCategories": [],
            "Path": [
                "f4874a2c-8788-4631-93ac-d5203a888009"
            ]
        }

**Comment by lamargardner565** [comment]
Thank you for the update.  Once this is fixed will it update in my environment, or will I have to redeploy the learning pathways solution?  My concern is that my customer will lose all their customizations if they must redeploy the solution.

Lastly,  is there anything that I need to do on my end ?
________________________________

**Comment by v-prigunasek** [comment]
Okay, @lamargardner565. This issue was originally created for content packs and since you have mentioned the user is experiencing the same exact issue, I assumed it would be a content pack. In this case, could you please create a separate issue to track it and share us the screenshots and logs to troubleshoot the error? Thanks

**Comment by lamargardner565** [comment]
Do I have to resubmit if this is technically separate from the post I replied to regarding the content packs?  The screen shots and the information that I provided doesn’t show anything with content packs in it.

V/R
Lamar R. Gardner
Cloud Solution Architect – Engineering
Microsoft Federal | Business Applications
SharePoint | Dynamics 365 CRM
E: ***@***.******@***.***> | E: ***@***.******@***.***>
[Graphical user interface, application  Description automatically generated]

**Comment by v-prigunasek** [comment]
> Good morning, any update on this? I have a customer that is experiencing the same exact issues.

I got confused with this post. Could you please confirm whether the user is facing the issue that you have recently created? https://github.com/pnp/custom-learning-office-365/issues/726
Thanks!

**Comment by lamargardner565** [comment]
I will create a different ticket.  I am not sure how issue #697 and #726 combined.

V/R
Lamar R. Gardner
Cloud Solution Architect – Engineering
Microsoft Federal | Business Applications
SharePoint | Dynamics 365 CRM
E: ***@***.******@***.***> | E: ***@***.******@***.***>
[Graphical user interface, application  Description automatically generated]

**Comment by lamargardner565** [comment]
Good morning,

New request submitted:

(Not a Content Pack) Edits to a custom category/playlist/Asset within Microsoft 365 Learning Pathways doesn't hide properly after its saved · Issue #727 · pnp/custom-learning-office-365 (github.com)<https://github.com/pnp/custom-learning-office-365/issues/727>

V/R
Lamar R. Gardner
Cloud Solution Architect – Engineering
Microsoft Federal | Business Applications
SharePoint | Dynamics 365 CRM
E: ***@***.******@***.***> | E: ***@***.******@***.***>
[Graphical user interface, application  Description automatically generated]



From: Lamar Gardner
Sent: Wednesday, March 29, 2023 10:10 AM
To: pnp/custom-learning-office-365 ***@***.***>; pnp/custom-learning-office-365 ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [pnp/custom-learning-office-365] Reprise: "I can't create subcategories under the Scenarios category" (Issue #697)

I will create a different ticket.  I am not sure how issue #697 and #726 combined.

V/R
Lamar R. Gardner
Cloud Solution Architect – Engineering
Microsoft Federal | Business Applications
SharePoint | Dynamics 365 CRM
E: ***@***.******@***.***> | E: ***@***.******@***.***>
[Graphical user interface, application  Description automatically generated]

**Comment by dcashpeterson** [comment]
@lamargardner565 let me know if this issue is resolved with your other post.

**Comment by lamargardner565** [comment]
Good morning,

My customer is in the process of testing this and will let you know what I get.

V/R
Lamar R. Gardner
Cloud Solution Architect – Engineering
Microsoft Federal | Business Applications
SharePoint | Dynamics 365 CRM
E: ***@***.******@***.***> | E: ***@***.******@***.***>
[Graphical user interface, application  Description automatically generated]
