### ISSUE TITLE
No playlists playing on any PC with any browser

### ISSUE THREAD

**Issue by luvsql** [pnp/custom-learning-office-365#698]
We've been using this for some time now and now no playlists are playing.  We get the refused to connect.  This used to be because of Chrome then had to use Edge but now Edge gives this error.  We rely on this site for our user training so now no one can get training.  

The videos that I have uploaded to our own SharePoint site that I've used on this site give the error "companyname.sharepoint.com refused to connect" error.  These videos play fine inside of SharePoint using the link but they don't play inside of this site with the exact same link used on the playlist so it can't be SharePoint.

How do we fix this?

**Comment by luvsql** [comment]
These videos were all mp4 files that I manually created then uploaded to SharePoint.  They play currently in SharePoint using Stream just fine so I'm not sure why a video file would no longer be supported in an iFrame?  Was there a change recently?  They were working up until 1.5 weeks ago.

**Comment by luvsql** [comment]
We are desperate here.  Our entire company relies on this site for its education and none of the videos that are from a SharePoint link work anymore.  Is this because of the new Stream update?

**Comment by v-saikirang** [comment]
Hi @luvsql,

Thanks for reaching out to us. Please allow us some time. We will look in to this and get back to you ASAP.

Thanks.

**Comment by v-prigunasek** [comment]
Hi @luvsql ,

Can you please share us the console logs to get more insights about the errors? 
I see you have a similar issue with Chrome browser earlier, have you tried these scenarios to narrow down the issue this time?
 https://github.com/pnp/custom-learning-office-365/issues/660#issuecomment-1133132564

Could you please let us know the below additional details?
1. Does everyone in the organization is facing this issue or is it limited to set of users?
2. Have you tried any other OS / browsers /mobile and seeing the same issue everywhere?

Thanks!

**Comment by luvsql** [comment]
The issues before were only with the Microsoft videos (docs.microsoft.com) that were fixed by using Edge.  

These are videos are from our own SharePoint tenant that give the errors on every browser on every PC we have tried.  There is no workaround for them other than to not use the Learning Centre and access them from SharePoint since those videos play.

So basically, I copied the link from SharePoint and added it as a playlist to the Learning Centre.  Those videos were working fine for months but now they don’t play at all in the Learning Centre.

These exact same links run the videos fine from ewihtin SharePoint on any browser on any PC.  Issue is just with Learning Centre.


Could you please let us know the below additional details?
1.	Does everyone in the organization is facing this issue or is it limited to set of users? – yes every user has the issue.
2.	Have you tried any other OS / browsers /mobile and seeing the same issue everywhere? – yes we have tried 3 different browsers on 5 different PCs.  

Can you direct me to how to collect a console log for the Edge Browser?

**Comment by luvsql** [comment]
I figured out how to get the log and is attached.  I removed our domain name with xxxxxxx.
[skygridconstructioninc.sharepoint.com-1662733870597.log](https://github.com/pnp/custom-learning-office-365/files/9536295/skygridconstructioninc.sharepoint.com-1662733870597.log)

**Comment by v-prigunasek** [comment]
Thanks for sharing the logs, @luvsql. 

I see this error from the log  -  Refused to display 'https://xxxxx.sharepoint.com/' in a frame because it set 'X-Frame-Options' to 'deny'.

Let me check on this error and get back to you ASAP. Thanks!

**Comment by v-prigunasek** [comment]
Hi @luvsql,

Can you please share the video link that you have embedded in the iframe? Is it from the same or different domain/tenant?
If it is from different domain, please check whether that domain is added under the allowed domains in HTML Field Security?
![image](https://user-images.githubusercontent.com/98514691/189382270-8c3f2d84-99c0-45f6-96fa-c45ce69bd200.png)

Thanks!!

**Comment by luvsql** [comment]
It's the same domain and same tenant.  Nothing has changed.  You won't be able to access the link since it's internal and we do not allow external sharing on our SharePoint site.

**Comment by v-prigunasek** [comment]
Thanks for that information. 
I assume, you have a .mp4 file uploaded to a SharePoint library and created a new SharePoint Page to embed that video file. Then provided that SharePoint Page URL to an Asset of a Playlist in Learning Pathways. Is that right?

If so, which webpart you have used or how you have embedded the video into the SharePoint page? 

I just want to know the format of the URL that you have provided to embed it. You can mask it and paste it over here if you could. Thanks!

**Comment by luvsql** [comment]
No I don't have a dedicated SharePoint page that have these embeded.  I never have.  I uploaded these to a SharePoint library and copied the link for the video and added it as a playlist.  There have never been issues until now.  They have been played from the Learning Centre hundreds of times until they stopped working last week.

**Comment by luvsql** [comment]
Here is one of the links.  If we click on the link in SharePoint now, the video plays.  SharePoint opens it with Stream but when it was played from the Learning Centre, it was embedded but not sure what video player it used.  
![Video plays in SharePoint](https://user-images.githubusercontent.com/104849149/189393897-51e16533-71c0-4ff4-b66f-c1f29d50a0ae.png)


https://companyname.sharepoint.com/:v:/s/sharepointsite/ERrASfFzx0BMvMRmWLfVoBQBD1CreTHN2mO9VRrk1RF5Tw?e=kZokui

**Comment by luvsql** [comment]
The link I pasted changed to a fingers emoji so not sure why it did that.  It was a : then v then : that it converted.

**Comment by v-prigunasek** [comment]
That's fine. I'm able to replicate it if I directly use the video file URL for the assets in the playlist.
![image](https://user-images.githubusercontent.com/98514691/189394981-77ddf404-8f92-4fc2-b180-c57ec71b6817.png)

Earlier I tried creating a SharePoint page in the Site Pages library (in Learning Pathways site) and added that video using the File viewer webpart. Then used that page URL in the assets and it was working fine. That's why I was wondering how this error came up for you.

Now that I'm able to replicate it, I will try to find the rootcause of it and let you know my findings. Thanks

**Comment by luvsql** [comment]
Amazing thank you.

**Comment by v-prigunasek** [comment]
When I use the direct link of the video file in the assets, it is working fine. You can try this as well, until I find the root cause of the issue with the Copy Link URL.

You can get the direct URL of the file by selecting that file -> Click on info icon at the top right from the ribbon -> Copy direct link from Path.

![image](https://user-images.githubusercontent.com/98514691/189397237-24859133-1cb4-4a40-9055-11f3218ddde5.png)

Thanks

**Comment by luvsql** [comment]
That works!!  I will modify the URLs for all the playlists and we should be good to go.  Thank you!
