### ISSUE TITLE
Outlook > Organize your inbox screenshots out of date[ENHANCEMENT] 

### ISSUE THREAD

**Issue by HughMcCracken** [pnp/custom-learning-office-365#700]
Screen shots that illustrate the Outlook desktop UI in the "Organize your inbox" have search located above the inbox, which is out of date

![image](https://user-images.githubusercontent.com/115505811/194951362-3b2c74e2-fb44-414a-8313-6852347eb752.png)

It would be great if the screen shots could be updated, showing the search box in the Office365 nav bar at the top of the screen

many thanks

**Comment by dcashpeterson** [comment]
@HughMcCracken Thanks for using Learning Pathways. The content for Microsoft 365 Learning Pathways is pulled in from other sources so we don't have any control over when they update that content. I agree that the misaligned images are confusing. I think the best course of action would be for you to use the link below. On the bottom of the page click the Was This Information Helpful button and select no. This spawns a form to enter feedback on the content. Give that a shot. I am also talking with the content team to see if there are other avenues.
https://support.microsoft.com/en-us/office/set-categories-flags-reminders-or-colors-a894348d-b308-4185-840f-aff63063d076

**Comment by HughMcCracken** [comment]
Hi, thanks for the recommendation, I've completed and submitted feedback on the content on that page, thanks for sharing the link for that. Keen to hear if there are any other avenues to alerting (or helping out!) when content or screen shots need updating.
Thanks again
