### ISSUE TITLE
Unable to create subcategory in "Adoption Tools" section in Learning pathways

### ISSUE THREAD

**Issue by AndieDML** [pnp/custom-learning-office-365#701]
- [ ] Custom Content
Is this really not allowed? I can't create subcategory in "Adoption Tools" section in Learning pathways.
If I press the + sign (Add new subcategory) then type the Subcategory Heading then press the save button - it's not doing anything. There is no error. It just goes back to the beginning "add new subcategory". It is not a network issue as well, I tested it on other internet connection. 

Learning Pathways version 4.1.4

I hope someone can help. Thank you

**Comment by dcashpeterson** [comment]
@AndieDML You should be able to add a new subcategory under Adoption Tools. Can you please look in the console and see if there are any errors with this symbol in there 🎓

**Comment by AndieDML** [comment]
Where should I look this error? I checked in our learning pathways portal and checked the backend (github) - I don't see that symbol.
It's weird that I can add subcategory under the Get Started, Scenarios, Products section but not under Adoption Tools section.

**Comment by dcashpeterson** [comment]
You need to look in the console. That is under Developer Tools. In Chrome, if you right click the screen with Learning Pathways on it you should see Inspect. Once you click Inspect the dev tools interface will load and there will be a tab for Console. Then refresh the page and try to add the subcategory again and look for errors in the console. Learning Pathways errors all have the cap next to them to distinguish it from other errors.

A few other questions while you are working on the console errors. 
1. Are you using any custom content packs?
2. Do you already have any custom playlists or sub-categories under Adoption Tools? 
3. Have you tried clearing out the CustomConfig items from the CustomConfig list to force reset the cache?

**Comment by AndieDML** [comment]
Yes I am getting an error.

[OrgAssetsService.getOrganisationAssetsLibraries]: Err='Cannot read properties of null (reading 'DecodedUrl')'

I'll check what causing this error but I found a way around by adding the subcategories on the metadata script. So far it is workable.
