### ISSUE TITLE
Admin page links are suspect 

### ISSUE THREAD

**Issue by LisaJo48** [pnp/custom-learning-office-365#704]
## Describe the bug

On the Learning Pathways Admin Success Center page, 2 of the links appear to be inaccurate:

1. "Adoption Resources" does not open anything. It times out saying 'page cannot be reached'.
2. "Download Adoption Kit" leads to a non-Microsoft website. URL = https://tempmailo.com/bl/

### To Reproduce

Clicking on "Adoption Resources" returns
          ![image](https://user-images.githubusercontent.com/46016140/201175163-4ae14657-b620-4ff7-8b2b-f2e2d878ef2c.png)

Click on "Download Adoption Kit"

          First shows this link:
         
![image](https://user-images.githubusercontent.com/46016140/201176718-8eee4694-d5ed-4e5e-9eaf-79ba80d8b752.png)

          Then automatically changes to: 
![image](https://user-images.githubusercontent.com/46016140/201174840-6a95ec5e-9011-4832-a0fb-a8a4c6b7e2e3.png)
        
          Which displays
![image](https://user-images.githubusercontent.com/46016140/201175001-29f01eb7-3d80-412b-ba1d-c2cc26c9010d.png)

### Expected behavior

I expect the links to lead to content Microsoft has supplied.

### Screenshots

>Current state of Learning Pathways Admin Success Center page
![image](https://user-images.githubusercontent.com/46016140/201175848-be3c703e-45dc-4959-9410-408535694a0d.png)

### Learning Pathways version number

>4.3.1.0

### Additional context

>I upgraded, today, to 4.3.1 (no errors), following the instructions including the reference to the potential update for the Admin Success Center page, but no opportunity to upgrade was offered. It's not checked out, unpublished, etc. so I am assuming it is up to date, but maybe it's not? If not, how do I get it updated properly?

**Comment by dcashpeterson** [comment]
@LisaJo48 This was an issue with some links that were broken in the Success Center Page. We corrected the issue with the template but didn't document a fix for users who already provisioned the site. To fix this issue go to the Admin Success Center Page in our Learning Pathways site. Edit the page and change the bottom 4 links associated with the quick links web part on the right side of the page. 

Learning pathways documentation | https://aka.ms/M365LPDocs
Feedback and support (issues list) | https://aka.ms/M365LPIssues
Adoption resources | https://aka.ms/M365LP
Downloadable adoption kit | https://aka.ms/M365LPAdoptionKit

**Comment by LisaJo48** [comment]
Thank you.
