### ISSUE TITLE
Update manual configuration to use latest PnP PowerShell

### ISSUE THREAD

**Issue by kevmcdonk** [pnp/custom-learning-office-365#706]
The current manual configuration PowerShell requires the legacy PnP PowerShell which many people no longer have installed.

I would like to see a new version of this that uses the latest PnP PowerShell - 1.12.0.

This would be needed at some point and could either replace the existing Configuration file or provide an alternative version of it (possibly the better option for supporting both scenarios).

I am happy to work on this (seeing as I started doing it already on my machine) but wanted to make sure that it fits with the longer term goals.

**Comment by dcashpeterson** [comment]
@kevmcdonk reach out to @ToddKlindt he was working on updating the script to support both in one script a while back. The challenge here is that the updated version will require the app reg to run the PowerShell which many folks don't have the ability to do. This will end up causing troubleshooting issues on our end. If you are offering we will gladly accept the update as long as you can make one script to support both depending on what is installed. We should also update the documentation after the script is updated. Thanks.

**Comment by kevmcdonk** [comment]
So would a single script that supported both be preferable to two script that allows the user to pick?

(And thanks for the quick response!)

**Comment by dcashpeterson** [comment]
Yes, a single script would be better.

**Comment by kevmcdonk** [comment]
Added PR #709 for this one

**Comment by dcashpeterson** [comment]
Merged the PR and closing this. Thanks for the assistance
