### ISSUE TITLE
[QUESTION] Learning Content can be crawled by the default Search functionality in SharePoint

### ISSUE THREAD

**Issue by BrinthaAnbalagan** [pnp/custom-learning-office-365#707]
>I would like to know if the content inside the learning pages can be crawled and made available to users in the default Search results page in that site collection. I have seen the search option inside the web part. Nevertheless checking if there is option to enable crawling for learning contents inside the webpart. 

#Learning content not available in the Search results within the site collection.

**Comment by dcashpeterson** [comment]
@BrinthaAnbalagan custom content you create in a SharePoint page is crawled by M365 search. The Microsoft provided content is not possible to be crawled as that content is served in a iframe. Keep in mind that for the custom content search will link you to the page of content not to Learning Pathways player.

**Comment by dcashpeterson** [comment]
answered
