### ISSUE TITLE
Page header visible in Teams (not SharePoint)

### ISSUE THREAD

**Issue by Romain-eXalt** [pnp/custom-learning-office-365#710]
Dear all,

I'm facing an issue now I'm deploying my website as an intranet in Teams since the display of the learning pathways is sadly very different from what we had when using sharepoint on web navigator (Chrome).

Maybe I'm missing something ? Thanks a lot for your help !

## Describe the bug

In SharePoint when I add a "aspx" file (= SharePoint page) as a new asset in a playlist and I view it using a web navigator (Chrome), it displays only the page content when I'm reading the playlist (which is very fine) :

<img width="636" alt="image" src="https://user-images.githubusercontent.com/115587346/204671728-1ab85a67-c817-4737-9833-55fd24b8f82c.png">

Note : this behavior is seen using either a web navigator with SharePoint or Teams (Sharepoint site accessible with Viva Connection).

However when I look at the same asset in the same playlist but using Teams application **on desktop** (using Viva Connection connector), it displays all the site headers / action buttons at the top of the page :

<img width="619" alt="image" src="https://user-images.githubusercontent.com/115587346/204671336-0a4dc55b-934b-4d57-a0ff-66c5268563fc.png">

### To Reproduce

Quite easy to reproduce : just add an aspx asset (= SharePoint page) in a playlist and view it through Teams Desktop VS Sharepoint (or Teams) web navigator (Chrome in my case). The user experience is very different.

### Expected behavior

For me the view through Teams desktop should be the same as using a SharePoint or Teams online.
Both views should show only the page content (not the site navigation, the action buttons...).

### Learning Pathways version number

The version 4.3.1.0

**Comment by v-prigunasek** [comment]
Hi @Romain-eXalt ,

Can you please try the below steps? 
1. Update the asset URL in the playlist with **?env=WebView**  at the end of the page URL 
2. Save Asset and then test that in Teams desktop

Please let us know if you still see any issues.

**Comment by dcashpeterson** [comment]
Closed and answered
