### ISSUE TITLE
[QUESTION] Opening external links in custom playlists

### ISSUE THREAD

**Issue by CKWGA** [pnp/custom-learning-office-365#712]
I created a custom playlist in Learning Pathways and one of the assets I created includes links to external web sites. When a link is clicked, the web site opens in the same frame. Is it possible to have links to external web sites open in a new browser tab instead of in the frame?

**Comment by v-prigunasek** [comment]
Hi @CKWGA ,

Thanks for submitting your query here. Could you please provide us some additional details?
1. Are you using a SharePoint page for the asset in your custom playlist?
2. If yes, what is the type of webpart that has the external links?

In SharePoint page, most of the webparts like Link, Button, Call to Action etc.. will open the links in the new tab by default. Text webpart has the option to select "Open link in new tab" as shown below when adding a link in it.
![image](https://user-images.githubusercontent.com/98514691/209326436-4e60d6d2-41b1-4a0f-a765-b1badf71828c.png)

**Comment by dcashpeterson** [comment]
Closed due to inactivity
