### ISSUE TITLE
 "Something went wrong"

### ISSUE THREAD

**Issue by SteviebabesUK** [pnp/custom-learning-office-365#713]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Clicking on any of the panels on the main page leads to the following error:

[SPLoaderError.loadComponentError]:
Failed to load component "141d4ab7-b6ca-4bf4-ac59-25b7bf93642d" (CustomLearningWebPart). Original error: Failed to load path dependency "M365LPStrings" from component "141d4ab7-b6ca-4bf4-ac59-25b7bf93642d" (CustomLearningWebPart). Original error: Error loading https://component-id.invalid/141d4ab7-b6ca-4bf4-ac59-25b7bf93642d_4.3.1/M365LPStrings
	Unable to load script https://oneymca.sharepoint.com/sites/appcatalog/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/M365LPStrings_en-us_acb00a81f471bc93e4b4042805412586.js

INNERERROR:
Failed to load path dependency "M365LPStrings" from component "141d4ab7-b6ca-4bf4-ac59-25b7bf93642d" (CustomLearningWebPart). Original error: Error loading https://component-id.invalid/141d4ab7-b6ca-4bf4-ac59-25b7bf93642d_4.3.1/M365LPStrings
	Unable to load script https://oneymca.sharepoint.com/sites/appcatalog/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/M365LPStrings_en-us_acb00a81f471bc93e4b4042805412586.js
CALLSTACK:
Error
    at t [as constructor] (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_49d37ded9db4e12f19a385ada4e9abe3.js:70:540775)
    at new t (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_49d37ded9db4e12f19a385ada4e9abe3.js:70:798693)
    at e.buildErrorWithVerboseLog (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_49d37ded9db4e12f19a385ada4e9abe3.js:70:835977)
    at e.buildLoadComponentError (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_49d37ded9db4e12f19a385ada4e9abe3.js:70:832068)
    at https://res-1.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_c9d296eaa8490acee6b3.js:1:6036

### To Reproduce

>Clicking on any of the panels on the main page

### Learning Pathways version number

4.3.1

**Comment by v-prigunasek** [comment]
Hi @SteviebabesUK ,

Thanks for reaching out to us. Can you please confirm whether you have access to Tenant appcatalog site? If you are able to access the app catalog site, check whether you have this file  "M365LPStrings_en-us_acb00a81f471bc93e4b4042805412586.js"in the ClientSideAssets library in appcatalog site and let us know.

https://{tenantname}.sharepoint.com/sites/appcatalog/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/

![image](https://user-images.githubusercontent.com/98514691/209329478-1e2f1638-e071-40f5-9481-b599d5bb3029.png)

**Comment by SteviebabesUK** [comment]
Thanks for the swift reply
Yes that is present.

I forgot to mention - everything works with the account that provisioned it 
It doesn't work with a regular user account

**Comment by v-prigunasek** [comment]
Thanks for providing those details. Can you please check whether that regular user account that you are using has the Read access to App catalog site collection?

**Comment by SteviebabesUK** [comment]
Apologies for the slow reply - XMAS happened!
No accounts had permission so I added an Azure group of all licensed users and it is now working :)

Why arent the permissions set correctly "Out of the box"?

**Comment by dcashpeterson** [comment]
The installation of Microsoft Learning Pathways doesn't touch the permissions for the app catalog. That would be incredibly invasive for one app to make global changes to the app catalog. We respect the permissions that are set up by the admins for the tenant.

**Comment by dcashpeterson** [comment]
closing as answered and solved.
