### ISSUE TITLE
Unable to access Learning Centre from Microsoft Teams Tab 

### ISSUE THREAD

**Issue by luvsql** [pnp/custom-learning-office-365#714]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

This was working but not the page no longer opens when added (the URL) as a tab in Microsoft Teams.  What happens now is we see a SharePoint icon like it's trying to load then "This site won't load in our desktop app" and we have to open it in a browser.  Since Microsoft Teams is authenticated and SharePoint is and the website is, why is it no longer opening in Teams?  

### To Reproduce

In any Microsoft Teams Channel click + choose Website and paste in the website.

### Expected behavior

It should open the website.  It used to work a few months ago.  

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.
![Second Error](https://user-images.githubusercontent.com/104849149/212088380-9c75b281-cd7a-411e-895e-08bc2b5db352.png)
![First Error](https://user-images.githubusercontent.com/104849149/212088381-e20dbe87-078e-4c86-976c-07cce0ba2e5e.png)

**Comment by v-prigunasek** [comment]
Hi @luvsql ,

Yes, this seems to be an issue when we use SharePoint sites/links in "Website" tab. Can you please add the Learning Pathways site using the "SharePoint" or "SharePoint Pages" tab.

![image](https://user-images.githubusercontent.com/98514691/212291889-d2f66716-e25a-42a1-a04a-72d1b60a8caf.png)

**Comment by luvsql** [comment]
Fantastic it works as a SharePoint page thank you!
