### ISSUE TITLE
Unable to log into Learning Center when accessed through managed app in InTune 

### ISSUE THREAD

**Issue by luvsql** [pnp/custom-learning-office-365#715]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

We manage all Office apps in work profiles on Android through Intune.  When I open the Learning Center from within a managed app (Teams) it prompts to login which is normal.  If I do this through a browser, I get the authentication prompt and the site opens.  However, through Teams I don't the authentication prompt then an error "you cannot access this right now" and "your sign in was successful but does not meet the criteria to access this resource" which I'm assuming is because authentication ie MFA was not triggered.  

### To Reproduce

Add site as tab in channel in Teams.  Install Teams in managed profile (work) from Intune.  

### Expected behavior

>A clear and concise description of what you expected to happen.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.

**Comment by v-prigunasek** [comment]
Hi @luvsql ,

Is this related to the same issue in accessing Learning Pathways from Website tab as mentioned in [#714](https://github.com/pnp/custom-learning-office-365/issues/714) ? If so, please try to add the Learning Pathways site using SharePoint tab and see if that fixes this issue. Thanks!

**Comment by luvsql** [comment]
Yes adding it as a SharePoint page vs site now fixes this issue as well.  Thank you!
