### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by dellis65** [pnp/custom-learning-office-365#716]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [x] Installation
- [x ] Learning Pathways Content Update
- [ ] SharePoint Success Content
- [ ] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### What is your question
Performed the auto installation update per instructions from v3 to v4.3.1.0, now when I open the admin page it reverts to 
Data Upgrade from v3 -> v4
You have updated to a major new release of Microsoft 365 learning pathways. To begin the upgrade process press 'Start'.

I click start and it successfully updates but every time I open the admin page it shows the same thing.
 
All web parts in pages on the site give the error>"Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance"
>Provide related screen-shots to help us understand your question
I am getting an error trying to upload the screenshots, continues to say something went really wrong.
![DevConsoleErrors](https://user-images.githubusercontent.com/32459030/214886895-c99291b8-7ab4-436f-b856-b6e04d5bd19b.PNG)
![LPAdminPage](https://user-images.githubusercontent.com/32459030/214886963-d17fd23f-fd1b-4e11-a20b-6f03afdf4587.PNG)
![LPWebPartError](https://user-images.githubusercontent.com/32459030/214887010-f075cfd2-4bef-4d05-8f03-7872f80079aa.PNG)

**Comment by v-prigunasek** [comment]
Hi @dcashpeterson ,

Could you please provide some guidance on this issue? Thanks!

**Comment by dcashpeterson** [comment]
The first thing I would check would be to make sure that there were no errors in the web part deployment and that the web part is updated properly in the site.

It looks like there were no errors with the upgrade. My suggestion would be to try deleting everything in the CustomConfig list with a title of CustomConfig and then go to the admin page https://mytenant.sharepoint.com/sites/mysite/SitePages/CustomLearningAdmin.aspx. This should refresh the cache. You can also try to clear the cache and then re-run the upgrade tool.

**Comment by dellis65** [comment]
Clearing the CustomConfig entires resolved the errors. The admin page and webparts are all working now.

Thank you for your help!
Dana

**Comment by dcashpeterson** [comment]
Resolved. Closing
