### ISSUE TITLE
Some Videos are available only in English 

### ISSUE THREAD

**Issue by uxwcs23** [pnp/custom-learning-office-365#717]
Hi, 
We are using Learning Pathways at our global company and we have enabled multilingual support for the Learning Pathways. The availability of these translated versions of the learning materials is very important to us. We have discovered that some of the video materials embedded in the articles are only available in English with no subtitles, audio or other options to translate them. In the first screenshot (Example_english version only) you can see an example of an article with a video embedded; even though the user is displaying all the contents, including the article, in German, (following his language settings) the video is only available in English, without any translation possibility: no subtitles, no audio translation and no visuals in german available.
In the second screenshot (List of Videos available only in English) we have noted down a list of assets whose videos are available only in English. Are there plans to convert these videos to ensure they have at least one translation option available for each? 
Thanks for your help!

![Example_english version only ](https://user-images.githubusercontent.com/124048162/215808357-d4017816-6b1b-4401-bafd-21bda611ea66.png)

![List of Videos available only in English](https://user-images.githubusercontent.com/124048162/215808361-14c15b50-25e6-447b-8ffe-656015887b61.png)

**Comment by dcashpeterson** [comment]
@uxwcs23 unfortunately, the content on those pages is pulled into Learning Pathways so we don't have any control over contents of the pages. My suggestion would be to visit the pages in question (e.g. https://support.office.com/de-de/client/2eb1d51f-a897-4d73-ba76-c550f005e5ef) and at the bottom of the page there is a feedback link. Fill in the feedback link that there should be German subtitles or transcript, etc. and let the content authors know.

**Comment by uxwcs23** [comment]
Thank you for you quick response and support 😊
We will contact Microsoft as suggested.
