### ISSUE TITLE
Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance.

### ISSUE THREAD

**Issue by fiszuu** [pnp/custom-learning-office-365#719]
Hello,

I'm trying to fix the Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. error. 
I've read previous issues and restored broken permissions to CustomConfig list. 

Additionally, when this did not work, we removed the solution from our environment and redeployed it. The error persisted.

Please let me know what information you might need to help with troubleshooting and restoring the full functionality of the solution. I'll gladly provide those.
![image](https://user-images.githubusercontent.com/48495609/216991061-051699ff-2342-48b6-b00a-471b78af9370.png)

**Comment by gmparky** [comment]
I am seeing this issue too. Started this week.

**Comment by dcashpeterson** [comment]
From the errors I am seeing it looks like the tenant app property isn't set correctly. Depending on how you removed it from your environment things may or may not be set up correctly. In general uninstalling the entire application isn't something we recommend unless you do it 100% (e.g. removing the web part, deleting the site collection, removing the tenant app property).

The error is saying that it can't get a valid configuration. That means that either the tenant app property is not set properly and the web part doesn't know where to get the configuration or that it knows but it can't access it. Check the tenant app property using PowerShell and make sure that it matches the site you are using for Learning Pathways. Also check that the permissions are set up properly for the config lists in the Learning Pathways site https://github.com/pnp/custom-learning-office-365/issues/686#issuecomment-1218201343

**Comment by gmparky** [comment]
Sorry mine was a dumb issue as I wasn't on our corporate network correctly.

**Comment by fiszuu** [comment]
I've just checked the permissions and those are as listed in the https://github.com/pnp/custom-learning-office-365/issues/686#issuecomment-1218201343

Also App properties are as follows:
![image](https://user-images.githubusercontent.com/48495609/220666021-f67eea3b-b11b-40a6-9f29-4685f42ee285.png)

The site is the correct one, as Learning Pathways is deployed there.

**Comment by dcashpeterson** [comment]
@fiszuu The webpart is not getting the configuration from github. Is it possible that github is being blocked in your organization?

**Comment by fiszuu** [comment]
I doubt that. Reason behind the doubt is that some users in the same network location are experiencing this issue and others can access the Learning Pathways without any issue.

**Comment by dcashpeterson** [comment]
@fiszuu if you could check the network tab on a page that isn't working and show any errors or items that are not loading from there that would be appreciated.

**Comment by fiszuu** [comment]
Hi, sorry for the delay. Here is the network tab outcome:

![image](https://user-images.githubusercontent.com/48495609/224704440-24632740-5881-4cd5-a8a2-f7e069b45e6b.png)
![image](https://user-images.githubusercontent.com/48495609/224704534-f9d352c4-a4c0-4871-a0c4-2bf1ade6b621.png)

This is the only error I see

**Comment by dcashpeterson** [comment]
Close due to lack of activity. If this is still an issue please create a new issue and reference this one.
