### ISSUE TITLE
Custom content disapear for a random time when a change is made to custom content

### ISSUE THREAD

**Issue by Rafou2** [pnp/custom-learning-office-365#72]
Custom content is disappearing whenever there is a change to a playlist, with a random time for the content to show up again, from 2 mn to more than 10 mn
![Portal bug](https://user-images.githubusercontent.com/50907271/59049857-34d85280-8889-11e9-8ac1-d9fbb018f0b0.png)

#### Category

- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
This is happening even in the lastest 2.0.15 version. 
Screen refresh doesn't do anything. This is a show stopper for creating custom content for an important MS client bank !
Thks

**Comment by juliemturner** [comment]
Can you please share the browsers console log?

**Comment by Rafou2** [comment]
Hi Julie,
How do I get the console log ?
Thks

Raphael Monnot
+33 620723451

**Comment by Rafou2** [comment]
Julie,
Here is a copy of what I found in the log file for the browser (EDGE) where no content displayed

Raphael Monnot
0620723451

From: Raphael Monnot
Sent: 07 June 2019 11:45
To: pnp/custom-learning-office-365 <reply@reply.github.com>
Subject: RE: [pnp/custom-learning-office-365] Custom content disapear for a random time when a change is made to custom content (#72)

Hi Julie,
How do I get the console log ?
Thks

Raphael Monnot
+33 620723451

**Comment by Rafou2** [comment]
[Log.docx](https://github.com/pnp/custom-learning-office-365/files/3271486/Log.docx)
Copying again the log file from the failing page (not sure attachment worked last time)

**Comment by Rafou2** [comment]
New copy of the log file after following exactly the instructions:
[Log 2.docx](https://github.com/pnp/custom-learning-office-365/files/3273582/Log.2.docx)

**Comment by juliemturner** [comment]
Thanks @Rafou2 ... by seeing the screen shot it provided me enough to figure out how and try to reproduce the error and I was able to.  The issue seems to be a bug when updating the custom playlist that corrupts the cache.  By refreshing the admin page after making a change that will fix the cached data and the viewer should work correctly.  We'll try and get a fix created as soon as we can.

**Comment by juliemturner** [comment]
Please update to Build 2.0.16. My testing shows this bug has been corrected. If you have further issues please submit a new issue.
