### ISSUE TITLE
M365 Learning Pathway Full Screen Issue

### ISSUE THREAD

**Issue by chillininmtl** [pnp/custom-learning-office-365#720]
We noticed that with the default/regular view, when we try to see all the steps/assets in a M365 Learning pathway playlist, in order to jump to specific steps/assets directly, the background of the steps is in black which is good because it's easy to read. Unfortunately, when you expand the view of the playlist so that it's in full screen mode, the background of the steps are no longer black but rather transparent, so it's very difficult to read the steps. Could you please have a look into this:

 View when not in full screen mode with black background for steps/assets (print screen shot 1)

View when in full screen mode with transparent background for steps/assets: (print screen shot 2)

Could you please have a look into this as this is affecting multiple users.

I can be reached on:

oumari.yorke@nielseniq.com
![m365 playlist working](https://user-images.githubusercontent.com/125512198/219178806-2e1a3a73-70c5-410c-a109-0627d52f0ed9.png)
![m365 playlist not working](https://user-images.githubusercontent.com/125512198/219178866-2441bc74-7411-4c0c-9e08-86d50d461f4e.png)

**Comment by dcashpeterson** [comment]
@chillininmtl this is an issue that was resolved in a fix for #606. Please check your version of Learning Pathways. The latest version with that fix is version 4.3.1
