### ISSUE TITLE
Manual configuration for M365 learning pathways. - suggest updated/more automated process

### ISSUE THREAD

**Issue by lamargardner565** [pnp/custom-learning-office-365#721]
**Is your feature request related to a problem? Please describe.**
For GCCH tenant environments/ manual non look book installs.  Legacy PowerShell PNP commands

**Describe the solution you'd like**
I successfully configured this for a customer that has a GCCH environment, The problem is that there a lot of references to the PowerShell script that has legacy PNP commands that are no longer used. Because of this it causes multiple errors and prevents for a smooth install.  Is there a way to automate this process more in the script or solution. also, can we update/automate this for the updated PNP commands? Is there a way to add in the script to look at the new commands and properly uninstall/install them within the script?

**Describe alternatives you've considered**
updating the script

**Additional context**

**Comment by dcashpeterson** [comment]
@lamargardner565 Thanks for the request. We currently have a pull request in review that updates the script to use the more modern PnP PowerShell commands. I hope that it will be reviewed and merged soon. That should aleviate some of the issues you describe. I will update this issue when #709 is merged.

**Comment by lamargardner565** [comment]
Thank you for the update and your response..

**Comment by dcashpeterson** [comment]
@lamargardner565 I wanted to give you an update. I have merged in the PR with the fix. The manual install script now supports both the older SharePoint PowerShell commands and the new PnP.PowerShell commands.

**Comment by lamargardner565** [comment]
Thank you sir,

This is great news!!!  Have a great day.

V/R
Lamar R. Gardner
Cloud Solution Architect
Microsoft Federal | Business Applications
SharePoint | Dynamics 365
Phone: 540-273-6989
E: ***@***.******@***.***> | E: ***@***.******@***.***>
[Graphical user interface, application  Description automatically generated]

**Comment by lamargardner565** [comment]
Good afternoon,

What is the best way to open a ticket with your team?  I am having a configuration issue that cause the M365 Learning Pathways to go down.  Please see below for additional information.  Also,  would you need to see the HAR file?

“We are running into an issue where the M365 Learning Pathways from Teams Home tab as well as the site collection where LP is installed, throw errors intermittently for us and all users.

The fix for these errors are to close/re-open Teams for the teams rendering of the LP content, and clearing browser cache for the browser rendering of these sites. This is becoming a daily issue for many users and seems to be a problem with cached content.

Permissions as well as the site and app have not changed in months. We do see references to https://res-1.cdn.office.net<https://res-1.cdn.office.net/> URL locations in F12 dev tools with errors when this occurs.

Do you have any ideas why the content stops loading properly when Teams has been open for a time? We save a HAR file from the dev tools when we were broken if that might help.

Errors from Teams:
***@***.***

Errors within the site collections:
***@***.***


V/R
Lamar R. Gardner
Cloud Solution Architect
Microsoft Federal
Business Applications | Modern Work
Dynamics 365 | SharePoint
Phone: 540-273-6989
E: ***@***.******@***.***> | E: ***@***.******@***.***>
[Graphical user interface, application  Description automatically generated]
