### ISSUE TITLE
[QUESTION] Can this solution be installed multiple times in the same M365 tenant?

### ISSUE THREAD

**Issue by eKnave** [pnp/custom-learning-office-365#722]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [x] Installation
- [ ] Learning Pathways Content
- [ ] SharePoint Success Content
- [ ] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### What is your question

>Provide related screen-shots to help us understand your question

**Comment by dcashpeterson** [comment]
@eKnave You can not have more than one Learning Pathways administration site in any tenant. You can use the webpart on any SharePoint page regardless of site collection. I'm not sure what the use case is here but you could also look at custom content packs which allow you to have a custom data and the webpart can be configured to use a specific content pack.

**Comment by eKnave** [comment]
Thanks for the response. I found out almost as soon as I posted this question. It is already answered in the forum. Not sure why there couldn’t be verbiage to this effect provided on the site where folks go to do the download/install.

Peace out, Stephen
