### ISSUE TITLE
 Error performing data upgrade from v3 to v4, when CustomConfig list has been modified

### ISSUE THREAD

**Issue by alinefmr** [pnp/custom-learning-office-365#723]
After updating the webpart and navigating to CustomLearningAdmin.aspx in order to start the upgrade process, the upgrade completes with 2 errors, and the pages CustomLearningAdmin.aspx and CustomLearningViewer.aspx will not load the webpart as expected.

### Troubleshooting
Running F12 indicates that the upgrade fails during the following querying, returning 404: https://[contoso].sharepoint.com/sites/M365LP/_api/web/lists/getByTitle('CustomConfig')/items(1) 

The list CustomConfig exists, but there is no entry with ID 1. Instead, the ID for the CustomConfig item is 5. There are other entries in the list (with ID 4, 5, and 6), and nothing in the recycle bin with ID 1. 

Would it be possible to query the item pending update by its Title? And what would be the implications of recreating this list, considering this site already has populated content/playlists?

### Screenshots
<img width="1244" alt="upgradelogv4" src="https://user-images.githubusercontent.com/40579000/221016152-8ffcdd94-60a6-42d4-b244-aa8da11a993e.png">

### Learning Pathways version number
4.3.1

**Comment by dcashpeterson** [comment]
@alinefmr thanks for using Learning Pathways. Have you tried to run the upgrade more than once? It is designed to pick up where it left off if it failed so try to do that and see if the issue resolved itself. It is trying to upgrade the schema and the cache and it failed on that step.

**Comment by alinefmr** [comment]
@dcashpeterson yes, we've tried it many times. Considering the issue seems to be related to the id of the list item (hardcoded as 1), I don't see how it can fix itself after further attempts.

**Comment by dcashpeterson** [comment]
@alinefmr The value you are talking about isn't hard coded into the upgrade script it is getting the config entries out of the CustomConfig list and then it loops through. When you upgraded did you turn on multilingual? Also if you could share a screen shot of what you see in the CustomConfig list? Redact anything that is identifying, I want to see the items in the list.

**Comment by alinefmr** [comment]
@dcashpeterson here's how the list looks like. Please note that the CustomConfig list item has "5" as its ID. The query performed during the upgrade routine is https://[contoso].sharepoint.com/sites/M365LP/_api/web/lists/getByTitle('CustomConfig')/items(1) 

<img width="866" alt="customconfig" src="https://user-images.githubusercontent.com/40579000/222586549-963545df-b475-4cb1-b2b4-d55bc74f7a5e.png">

No, this installation does not have the multilingual feature enabled. Also, I'm not the one who originally deployed LP at this tenant. I appreciate your time and efforts in assisting us.

**Comment by juliemturner** [comment]
Is that everything that is in the CustomConfig list, it appears to be missing some things? If that is it, then I would manually adjust the JSONData for the list item entitled 'CustomConfig' with ID 5 so that value starts with {"Id":5,... instead of {"Id":1,
Once you make that change then try running the upgrade again.

**Comment by alinefmr** [comment]
@juliemturner the problem is not in the JSONData column, but in the REST query used to read the list item in the first place: _api/web/lists/getByTitle('CustomConfig')/items(1) - updating the JSONDATA does not solve the issue.
