### ISSUE TITLE
Learning Pathways app is not loading on Microsoft Teams

### ISSUE THREAD

**Issue by daustaz** [pnp/custom-learning-office-365#725]
Our M365 Learning Pathways app is not loading on Microsoft Teams. However, when you click on the "Go to the website" button on the app, it loads up the Learning Pathways web page on the browser, but within Teams, it's stuck.

We have checked everything and couldn't find a possible cause for this errror.

Please help. Thanks!

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [ ] Installation
- [x] Learning Pathways Content
- [ ] SharePoint Success Content
- [ ] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### What is your question

>Provide related screen-shots to help us understand your question

**Comment by v-prigunasek** [comment]
Hi @daustaz ,

Thanks for reaching out to us! I believe you are using the M365 Getting Started App in Teams?

![image](https://user-images.githubusercontent.com/98514691/228448236-253b921f-1f95-456e-971f-5584f2ab08fb.png)

Could you please share us the screenshot of the issue that you are seeing and the Manifest file of the Teams App to troubleshoot further? Thanks

**Comment by daustaz** [comment]
![image](https://user-images.githubusercontent.com/128620129/229864475-f821089f-f9de-4fc7-a66a-8dfab414f1a1.png)
Here is it.

**Comment by v-prigunasek** [comment]
Hi @daustaz, 

Would like to know whether you are still facing the above-mentioned issue, if yes, please share us the manifest file that you have used for the LP teams app.

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If you need further assistance please create a new issue and reference this one.
