### ISSUE TITLE
(Not a Content Pack) Edits to a custom category/playlist/Asset within Microsoft 365 Learning Pathways doesn't hide properly after its saved

### ISSUE THREAD

**Issue by lamargardner565** [pnp/custom-learning-office-365#727]
ISSUE:
Editing an Asset within LP site causes all LP content to be viewable to all users, regardless of view settings.

DESCRIPTION:
When a playlist is edited within the LP site, once the asset is saved, all tiles in the MS Learning Pathways solution is viewable to site visitors, even where many of those assets should be hidden. 

**(This is not a Content Pack.  This is an out of the box creation of Categories and subcategories) **

APP DETAILS:
Microsoft 365 Learning Pathways version 4.3.1.0, release date February 2023

![image](https://user-images.githubusercontent.com/105717854/228566623-ac532044-39d1-4fd7-90e2-955779e9af50.png)

image

STEPS TO REPRODUCE:

Ensure the LP Home page, or [Learning Pathways Viewer page], is displaying the correct tiles
image

![image](https://user-images.githubusercontent.com/105717854/228566807-5ca9488b-1bdb-4a8c-99cb-d93e148dec4a.png)

Navigate to the [CustomLearningAdmin]) Page in LP, select a subcategory and select a Playlist within that subcategory

![image](https://user-images.githubusercontent.com/105717854/228566945-078d85d7-25cb-4831-822f-483c27605bc0.png)

image

Scroll down to Playlist Assets and make a change and revert (in order to trigger/unghost the Save Asset button). In the example below, I changed “Teams” to “Teamz” and back to “Teams” to allow a new save, just for testing. Note that any change/addition/deletion, whether reverted or kept, will introduce this issue.

![image](https://user-images.githubusercontent.com/105717854/228567093-b5e66f6d-d4ef-4d08-9d77-9872c5560c0c.png)

Navigate back to the Home/HUB page, or [Learning Pathways Viewer page], and note the web part now displays ALL content, even though the admin page indicates they should be hidden.

![image](https://user-images.githubusercontent.com/105717854/228567210-ae91c12c-501d-43f2-ba14-d985b529035d.png)

WORKAROUND:

To remediate this issue, navigate to the [Customer Learning Admin] page in LP and toggle the visibility of a subcategory to trigger the admin page to auto save. Note this is not a viable workaround solution, as customers will be able to view all hidden content until they reload the page.

![image](https://user-images.githubusercontent.com/105717854/228567264-fe3d6a6c-bcab-405c-b1ff-488aa068a447.png)

The Home tiles then display the correct viewable content:

![image](https://user-images.githubusercontent.com/105717854/228567324-30fb0549-546b-42bb-8ba4-906d750753c4.png)

Additional context

Can you please provide context to why this is happening? Is this normal behavior?

**Comment by juliemturner** [comment]
Duplicate #726
