### ISSUE TITLE
[QUESTION] Content updates are behind schedule

### ISSUE THREAD

**Issue by DmitryVorobyov** [pnp/custom-learning-office-365#730]
### Context 

- [ ] Installation
- [x] Learning Pathways Content
- [ ] SharePoint Success Content
- [ ] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### The facts

1. According to the [official documentation](https://learn.microsoft.com/en-us/office365/customlearning/custom_contentupdates), content updates for the Learning Pathways app are supposed to happen quarterly. According to the same article, last content update happened in August 2022 - over 8 months ago - which is clearly behind the quarterly cadence.

2. According to [another similar thread](https://github.com/pnp/custom-learning-office-365/issues/619) from January 2022, this issue isn't a one-off, and the previous content update was provided behind schedule as well.

### Question(s)

- When can the next content update be expected? I am primarily interested in the content around Teams Premium, but I am sure I am not the only one who has this question.
- In the future, if an update is running late, would it be possible to clearly communicate this via the documentation? Otherwise it creates a feeling that the solution may have been abandoned. 
- Would it be possible to reassess the update cadence, commit to a more realistic update schedule and then reflect the new cadence in the documentation?

Thank you very much! I greatly appreciate the solution's functionality, but I also wish there was more consistency and clarity around content updates.

**Comment by dcashpeterson** [comment]
@DmitryVorobyov Thanks for the feedback and you are 100% correct. The team is behind on the content updates. We will work to be more transparent on when content will be coming. We do not have a date for when that will be right now. We are working as a group to redefine that cadence and will update the documentation when that happens. Thank you for using Learning Pathways.

**Comment by dcashpeterson** [comment]
@DmitryVorobyov We pushed out a content update in June 2023 and updated the official documentation. We are in process of resetting our update cadence and we will communicate that in our documenation. For an update on what was release please check the [release notes](https://learn.microsoft.com/en-us/office365/customlearning/custom_contentupdates). Thank you for keeping us accountable.

**Comment by dcashpeterson** [comment]
@jhwang-ms if we can add our updated cadence when defined to the release notes that would be a benefit.

**Comment by dcashpeterson** [comment]
@DmitryVorobyov I wanted to alert folks following this issue that we recently had a content update in September. This included Viva Engage content. As we are working towards more regular release you can get the latest here. https://learn.microsoft.com/en-us/office365/customlearning/custom_contentupdates

**Comment by dcashpeterson** [comment]
I am going to close this issue as it is tied to #786. Content updates will resume when we have the technical issues worked out.
