### ISSUE TITLE
Will we ever be able to paste YouTube video links as Playlist URLs?

### ISSUE THREAD

**Issue by luvsql** [pnp/custom-learning-office-365#735]
Our new software has at least 25 YouTube videos for its training that I now need to add into a new subcategory on the learning centre.  If I just use the youtube URL we get www.youtube.com refused to connect.

YouTube is the most popular video streaming site so is there any "quick and easy" way to incorporate these into this site?  The only way I've gotten past this in the past is to literally record the screen while the video plays, convert to mp4 then upload mp4 into SharePoint then share the link.

**Comment by dcashpeterson** [comment]
@luvsql Learning Pathways consumes page based content. You have the ability to add YouTube or other videos to Learning Pathways. You need to create a page in a SharePoint site and add the video via the Embed or YouTube web part.

**Comment by luvsql** [comment]
I created a new SharePoint page and added 3 videos using the YouTube webparts, however, in order to add as a playlist, each video requires a separate URL but can only get the main page's URL from SharePoint.  Does this mean each video must be on a separate page (I have 25 to add to that's 25 pages)?

**Comment by dcashpeterson** [comment]
@luvsql Technically you could group videos together on one SharePoint page and use that one page in a playlist but my recommendation would, be to create a new page for each video. That way you can mix and match the different videos in different playlists as needed.
