### ISSUE TITLE
Search box in Learning Pathways

### ISSUE THREAD

**Issue by AndieDML** [pnp/custom-learning-office-365#737]
Hi,

Is there a way we can set the search box to be visible all the time in Learning Pathways rather than it is auto hiding? Refer to the screenshot below. Appreciate any help on this. :)

![hidden](https://github.com/pnp/custom-learning-office-365/assets/106976142/f97e93a3-2433-436c-b355-ffa8a28e48f1)
![Showing](https://github.com/pnp/custom-learning-office-365/assets/106976142/1d22e81d-7547-46b0-8d8c-857154256b86)

Regards,
[Andie]

**Comment by v-prigunasek** [comment]
Hi @AndieDML ,

Thanks for reaching out to us and sorry for the delay in response. 
As per the current design, the search box and the link box will open only on click of the respective (search or link) icons. So currently, there is no way to have it always visible in screen unless it is clicked. Thanks!
