### ISSUE TITLE
[QUESTION] Can guests view Microsoft content on the Learning Pathways site?

### ISSUE THREAD

**Issue by Magali12345** [pnp/custom-learning-office-365#740]
Hi all,

I am wondering if guests that are invited to a Microsoft Learning Pathways site can view the training content? 

I work in a Group with several tenants. I would like to be able to create a single site (on the French tenant) and invite all the employees of the subsidiaries (from different tenants) as visitors to the site. After a test, I have the impression that the guests see all the content of the site EXCEPT the Microsoft training modules (page Microsoft 365 training). 
Can you please confirm that it is indeed the case? 

Thank you in advance
Magali

**Comment by StfBauer** [comment]
The content of Microsoft Learning Pathways is publicly available on Microsoft Sites.

However, if they can view the web parts of Microsoft Learning Pathways is a question of the tenant configuration.

If the tenant has CDN enable, then yes.
https://learn.microsoft.com/en-us/sharepoint/dev/spfx/enable-microsoft-365-content-delivery-network?tabs=msposh

If CDN is not enabled, they cannot access the resources of the web parts, and only people with proper user accounts can access the information.

It also depends on the configured sharing options of the Microsoft Learning Pathways site collection.

**Comment by v-prigunasek** [comment]
Hi @Magali12345,

Thanks for reaching out to us!
Could you please let us know whether the guest user is seeing any error in the Microsoft 365 training page?
Generally Guest users might receive an error while using the SPFX webpart as they will not have access to AppCatalog site unless the access is provided explicitly.

**Comment by Magali12345** [comment]
Hello @v-prigunasek 

Thank you for your answer. 
This is what the guest user sees in the Microsoft 365 training page : 
<img width="801" alt="image" src="https://github.com/pnp/custom-learning-office-365/assets/136699809/ca5858cb-e5f1-47b6-85c5-7c0e59a757c6">

Do you think that it is linked to the non access to AppCatalog?

**Comment by v-prigunasek** [comment]
Yes, right. It is related to the access issue for external users on "Client Side Assets" library in the App Catalog site.  

If you have a business need to allow external users to access your SPFX webparts in your tenant, then they should be added to the "Client Side Assets" library with Read permissions.

You can follow below steps to add permissions for external users:

1. Turn ON external sharing for your M365 tenant.

2. Download & open SharePoint Online Management Shell and run below commands using administrator account:
    **Connect-SPOService -Url https://<tenant>-admin.sharepoint.com**
    
    **Set-SPOTenant -ShowAllUsersClaim $true**

3. Grant "Read" permissions to All Users(membership) group on App Catalog site (https://<tenant>-admin.sharepoint.com/sites/AppCatalog/_layouts/user.aspx) or on "Client Side Assets" library (https://<tenant>-admin.sharepoint.com/sites/AppCatalog/ClientSideAssets/AllItems.aspx) in App Catalog site as shown below:
![image](https://github.com/pnp/custom-learning-office-365/assets/98514691/bd03564c-a686-4ea0-936a-e56c473a2ba9)

4. Incase, if you don't want to provide read access to All Users except few guest users, then you can skip step 2, and add the set of guest users directly to the library with Read permissions.

Let me know if you need any additional information.

**Comment by Magali12345** [comment]
It works! Thank you @v-prigunasek for your help!

**Comment by Magali12345** [comment]
Granted Read permissions to the AppCatalog to guest users solved the problem.
