### ISSUE TITLE
[ENHANCEMENT] Make the Search box in Learning Pathways noticeable

### ISSUE THREAD

**Issue by AndieDML** [pnp/custom-learning-office-365#742]
Most of our users do not notice that there is a search box in Learning Pathways and having difficulty finding the instructions they are looking for.

**Describe the solution you'd like**
Make the search box visible instead of auto hidden.

![239892427-f97e93a3-2433-436c-b355-ffa8a28e48f1](https://github.com/pnp/custom-learning-office-365/assets/106976142/e864ffb4-da93-4d81-aef2-2b53736cc47d)

**Comment by v-prigunasek** [comment]
Hi @AndieDML , 
Thanks for the above suggestion.

@dcashpeterson,
Please check on this enhancement request.

**Comment by AndieDML** [comment]
Any news about this enhancement?

**Comment by dcashpeterson** [comment]
merging this issue with #570
