### ISSUE TITLE
The OOTB playlist "Modern Workplace > Day in your digital life with Office 365 > Start your digital day" with the asset link to "https://learn.microsoft.com/en-us/office365/customlearning/dayinthelife?context=context%2Fchromeless&linktarget=true" is not loading

### ISSUE THREAD

**Issue by PanchamiM** [pnp/custom-learning-office-365#743]
On navigating to some of the OOTB playlist the iframe is not loading. Manily these links are related to docs.microsoft.com.

Navigate to below path to reproduce the issue.
"Modern Workplace > Day in your digital life with Office 365 > Start your digital day"

One of the link that is giving issue is : https://learn.microsoft.com/en-us/office365/customlearning/dayinthelife?context=context%2Fchromeless&linktarget=true

Expected Behaviour : The iframe should load the content of the link.
Current Issue Behaviour: It is blank screen with the error as **"login.microsoft.com refused to connect"**

The issue is being experienced in all the tenants and also in all networks. Both personal and Company network.
The issue is reproducible in both chrome and edge.

Learning Pathways version number : 4.3.1.0

Console Error : Refused to display 'https://learn.microsoft.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
Message: Origin https://docs.microsoft.com is not responding in a timely manner to "help_getClientHeight" post message. Default iFrame height set. - AssetView (resizeIFrame)

![Console_Error](https://github.com/pnp/custom-learning-office-365/assets/117371226/da4e5643-61ed-4040-b5f2-d4300ef97ca6)
![PageName](https://github.com/pnp/custom-learning-office-365/assets/117371226/cc9cf4b1-1500-4064-a976-07cbe8d3b060)
![ScreenError](https://github.com/pnp/custom-learning-office-365/assets/117371226/3a5cc635-63e9-4184-8b99-d8ceb4eaaa7f)

**Comment by PanchamiM** [comment]
Referred this issue raised **"https://github.com/pnp/custom-learning-office-365/issues/617"** and followed the steps.
Tried adding the domains to the "HTML field security" in site settings. But no use.
The links are already concatinated with "?context=context%2Fchromeless&linktarget=true".
Please guide on this.

**Comment by v-prigunasek** [comment]
Hi @PanchamiM ,

Thanks for reaching out to us. 
Let me check on this issue and get back to you. Thanks!

**Comment by PanchamiM** [comment]
Any update on this?

**Comment by v-prigunasek** [comment]
Hi @PanchamiM ,

Can you please confirm whether you are getting this error for all the assets that are pointing to learn.microsoft.com? If yes, can you please add that domain (learn.microsoft.com) in the Site Settings --> Html Field Security settings
![image](https://github.com/pnp/custom-learning-office-365/assets/98514691/438a0109-17f7-421d-8b2c-4b5abe609c7f)

Would also like to know whether these links are not working in your tenant since the Learning Pathways site is provisioned or it was working as expected earlier and suddenly throwing error.

**Comment by PanchamiM** [comment]
@v-prigunasek  Both the solutions are not working. And answering the question, we recently checked this path and it was not working,

**Comment by v-prigunasek** [comment]
Hi @PanchamiM ,

Can you please update the URL of the asset to the below and see if that works?

https://learn.microsoft.com/en-us/office365/customlearning/dayinthelife?context=context%2Fchromeless&linktarget=true&embedded=true

**Comment by PanchamiM** [comment]
@v-prigunasek Tried the solution provided. But no luck.

**Comment by v-prigunasek** [comment]
Hi @PanchamiM ,

Actually, this is not an issue with the Learning Pathways solution as it is just pulling the content from learn.microsoft.com domain. It is a CORS/security feature related issue, that is blocking the content from being IFramed from different domain. I'm not able to replicate this issue in our tenant so I could not even try any fixes at my end.

Can you check with the network folks in your organization and see if there is any policy that is preventing any kind of IFramed content? You can also try to access this page in different machines/browsers/network to see if you are facing the same issue in other environments too.

I will also try to see if there is any other way to alter the URL to embed the content from learn.microsoft.com and I will let you know if I find something. Thanks!

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If there is more on this issue please open a new issue and reference this one.
