### ISSUE TITLE
 DP-900 Practice test does not show results

### ISSUE THREAD

**Issue by kryshr** [pnp/custom-learning-office-365#745]
## Issue Writeup: DP-900 Practice Test on Microsoft Learn

**URL:** [DP-900 Practice Test on Microsoft Learn](https://learn.microsoft.com/en-us/certifications/exams/dp-900/practice/assessment?assessment-type=practice&assessmentId=24)

### Description
When taking the DP-900 practice test on the Microsoft Learn platform, users are experiencing an issue where the test does not display results at the end and gets stuck on the "compiling assessment" stage indefinitely.

### Steps to Reproduce
1. Visit the [DP-900 Practice Test](https://learn.microsoft.com/en-us/certifications/exams/dp-900/practice/assessment?assessment-type=practice&assessmentId=24) page on the Microsoft Learn platform.
2. Begin the practice test.
3. Answer all the questions in the test.
4. Complete the test and submit the answers.
5. Observe that the test does not display the results and remains stuck on the "compiling assessment" stage.

### Expected Behavior
After submitting the practice test, users should see the results of their assessment, including the number of correct and incorrect answers, as well as an overall score.

### Actual Behavior
The practice test does not display the results after submission. It remains stuck on the "compiling assessment" stage indefinitely, preventing users from viewing their performance.

### Additional Information
- This issue occurs consistently and has been reproduced by multiple users.
- Clearing browser cache and trying different browsers did not resolve the issue.
- The issue persists across different devices and operating systems, indicating it is not device-specific.
- No error messages or notifications are displayed, making it difficult to determine the cause of the problem.

### Impact
The inability to view practice test results prevents users from evaluating their performance and identifying areas for improvement. This hinders the effectiveness of the practice test in preparing users for the DP-900 certification exam.

### Workaround
Currently, there is no known workaround for this issue. Users are unable to access their practice test results until the issue is resolved.

### Next Steps
To resolve this issue and restore the functionality of the DP-900 practice test, the Microsoft Learn platform team should investigate the underlying cause of the problem and implement the necessary fixes. It is recommended to prioritize this issue to ensure a seamless user experience and effective preparation for the DP-900 certification exam.

![Capture](https://github.com/pnp/custom-learning-office-365/assets/91001275/a3fd4283-e64a-4319-a686-099198faafae)

**Comment by dcashpeterson** [comment]
@kryshr it looks like this is an issue with Microsoft Learn content and not Learning Pathways. This is a forum for support for Learning Pathways. I would look for a feedback link on the test page and submit your issue there. For what it's work the test worked for me using chime on a mobile.
