### ISSUE TITLE
Something Went Wrong

### ISSUE THREAD

**Issue by jphipps72** [pnp/custom-learning-office-365#751]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Something went wrong message when someone tries to access the webpart, other that the person that deployed the app.  I have given access to the test user by adding the permissions in the apps management portal. 

### To Reproduce

Navigate to the site the webpart is loaded on. 

### Expected behavior

The webpart to load and accessed by end users. 

### Screenshots

![Screenshot 2023-08-31 172826](https://github.com/pnp/custom-learning-office-365/assets/143757129/d594cfa8-c234-4c57-81a4-792f234ae5fc)

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Learning Pathways version number

4.3.1.0

### Additional context

Something went wrong

If the problem persists, contact the site administrator and give them the information in Technical Details.

TECHNICAL DETAILS

ERROR:
Script error for: 141d4ab7-b6ca-4bf4-ac59-25b7bf93642d_4.3.1/M365LPStrings
http://requirejs.org/docs/errors.html#scripterror

CALL STACK:
Error: Script error for: 141d4ab7-b6ca-4bf4-ac59-25b7bf93642d_4.3.1/M365LPStrings
http://requirejs.org/docs/errors.html#scripterror
at B (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_ee1069bd208bb1b13c96744812889950.js:78:271194), <anonymous>:8:252)
at HTMLScriptElement.onScriptError (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_ee1069bd208bb1b13c96744812889950.js:78:271194), <anonymous>:30:244)

Common Errors

**Comment by dcashpeterson** [comment]
@jphipps72 Please check to make sure that the users that are trying to access the webpart have read access to the app catalog. See the instructions on #713.
