### ISSUE TITLE
[QUESTION] Question about articles on learn.microsoft.com

### ISSUE THREAD

**Issue by asechko** [pnp/custom-learning-office-365#752]
Hello,

I apologize for the offtopic, but honestly can't find another place to post it (maybe someone could guide me as well)

For a long time, we have been using Microsoft Learning Pathways for internal training. Since we are doing it inside our SharePoint environment, but without using the solution that is described here on GitHub: we put the pages from the MLP into iframe for them to be shown. So we are not using this custom web part.

However, lately we are facing the following issue:

- majority of pages still are displayed correctly – those that are from support.office.com, for example, https://support.office.com/en-us/client/3f4bb0ff-58de-2188-55c0-f560b7e20bea?embed=true can be put in iframe without any issues;
- but content that was located on docs.microsoft.com became unavailable after it has been transferred to learn.microsoft.com

It looks like learn.microsoft.com pages cannot be put in iframe because “x-frame-options” in the header is set to ‘sameorigin’

![MicrosoftTeams-image](https://github.com/pnp/custom-learning-office-365/assets/113890335/04b6c5a9-5292-4bac-bf5f-40066b5975e4)

So, the questions are the following (hoping that somebody still could help me):

- can this header be altered/removed from your side, at least for pages that are used in MLP, for example, this - https://docs.microsoft.com/office365/customlearning/dayinthelife?context=context%2Fchromeless&linktarget=true
- if not, can you offer any workaround for embedding content from learn.microsoft.com?
- if there are any plans to move content from support.office.com to learn.microsoft.com as well?

Thanks in advance.

**Comment by dcashpeterson** [comment]
@asechko I am not sure I am following what you are trying to do. Are you using the Learning Pathways web part to embed content on a page or are you using the embed web part to embed a Learn.microsoft.com page. I just checked and the Day in the Life content you referenced works fine and is an asset called Start Your Digital Day in the Modern Work Category. Home > Modern workplace > Day in your digital life with Office 365. There are issues with learn.microsoft.com and docs.microsoft.com where you can't bring that content in via an IFrame. There isn't a work around for that unfortunately.

**Comment by asechko** [comment]
> @asechko I am not sure I am following what you are trying to do. Are you using the Learning Pathways web part to embed content on a page or are you using the embed web part to embed a Learn.microsoft.com page. I just checked and the Day in the Life content you referenced works fine and is an asset called Start Your Digital Day in the Modern Work Category. Home > Modern workplace > Day in your digital life with Office 365. There are issues with learn.microsoft.com and docs.microsoft.com where you can't bring that content in via an IFrame. There isn't a work around for that unfortunately.

exactly @dcashpeterson, we are using embed web part to embed a Learn.microsoft.com page, so basically we are not using the web part that is a part of this solution.

so do you know why content from learn.microsoft.com and docs.microsoft.com can't be embedded anymore, as it was previously possible?

and will all content be moved there from support.office.com as well?

**Comment by dcashpeterson** [comment]
@asechko, This is not an issue that is specific to Learning Pathways. Unfortunately, there is content in learn, docs, and support that has the header that specifically prohibits iframing. There is no work around for that. The Microsoft provided assets in Learning Pathways work within the Learning Pathways webpart so if you wanted to create a custom playlist with a single asset in it you could then use the Learning Pathways webpart and show that playlist.

Hope that helps.
