### ISSUE TITLE
When saving custom assets, resets hidden categories to be visible 

### ISSUE THREAD

**Issue by clarelcampbell** [pnp/custom-learning-office-365#754]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

When saving custom assets, resets hidden categories to be visible. Same as bug #728 which has a resolution in version 4.4

### To Reproduce

>create a custom asset. Save.

### Expected behavior

>hidden content is made visible 

### Screenshots
Screenshots show the tools adoption content showing in products for users to see after I have saved a copy of a custom playlist, second screen shot shows it hidden. 

>
![MLP error 12oct23](https://github.com/pnp/custom-learning-office-365/assets/123638166/9cc67a84-4e94-4a50-9aa5-8972eebdcf5f)

![MLP error 12oct23 1](https://github.com/pnp/custom-learning-office-365/assets/123638166/c31b36ac-301b-426a-a231-4ee233aca79a)

### Learning Pathways version number

> believe we are on v4 however version numbers different in the MLP admin - see screenshot in additional content

### Additional context
![MLP error 12oct23 2](https://github.com/pnp/custom-learning-office-365/assets/123638166/12494cdc-ac74-4bd8-8ea1-27059bd16162)

>resolution, as was before with previous bug #726, seems to work: go to any hidden content. Unhide. hide. refresh screen on home page and all hidden is back to being hidden.

**Comment by dcashpeterson** [comment]
@clarelcampbell you are using version 4.3.1. To get the fix you need to update to v4.4.
