### ISSUE TITLE
Is MS Bookings app is available as standalone app like outlook/Teams.

### ISSUE THREAD

**Issue by PanchamiM** [pnp/custom-learning-office-365#755]
Is MS Bookings app is available as standalone app like outlook/Teams.
There is MS Bookings inside the Teams in Learning space, but thats secondary and its for Teams . We need to have like a standalone.
![image](https://github.com/pnp/custom-learning-office-365/assets/117371226/22a2f62a-0fef-4f81-b395-80be96212a4f)

**Comment by v-asshrirao** [comment]
@PanchamiM, This is not the correct channel, so we will not be able to answer your question.
Thank you.

**Comment by PanchamiM** [comment]
@v-prigunasek We are asking about the content part. Like Teams is available as a separate tile under products. Can we have the Bookings also under products.
