### ISSUE TITLE
Microsoft Teams and few other tiles are not displaying under Products in CustomLearningViewer.aspx, it is set to visible in CustomLearningAdmin.aspx page 

### ISSUE THREAD

**Issue by ramkumarvaratharajan** [pnp/custom-learning-office-365#757]
Microsoft Teams and few other tiles are not displaying under Products in CustomLearningViewer.aspx, it is set to visible in CustomLearningAdmin.aspx page. When we made changes to visibility in the customlearningadmin page, the CustomConfig list is getting updated, but the tiles are not displaying.

>Steps to reproduce the behavior,
1.  Go to CustomLearningAdmin.aspx page, click on the Products in left menu
2.  Click on the eye icon right Microsoft Teams.
3.  Navigate back to CustomLearningVIewer.aspx page.
4.  Microsoft Teams tile is not displayed under Products.

**Comment by v-asshrirao** [comment]
@ramkumarvaratharajan, Thank you for reporting this.
Please allow us some time, we will get back to you asap.

**Comment by v-asshrirao** [comment]
@ramkumarvaratharajan, 
We are not able to reproduce this issue,
Can you please try to clear the cache and let us know if its the same behaviour. 
If this does not work can you please provide more details on the error.

**Comment by dcashpeterson** [comment]
@ramkumarvaratharajan  The log files included personal information so i have removed them from your post.

**Comment by dcashpeterson** [comment]
@ramkumarvaratharajan when you cleared the cache did you clear the browser cache or did you clear the Learning Pathways cache files. You need to clear all the items in the CustomConfig list with the title of CustomConfig. Then open the Learning Pathways Admin page, make your change and then navigate to customviewer. This will recreate the cache.

Also, are you using more than one language? If you are not using more than one language make sure that multilingual is turned off and you do not have other languages installed.

**Comment by ramkumarvaratharajan** [comment]
@dcashpeterson After clearing the items from CustomConfig list, it worked. Thanks for your support.
