### ISSUE TITLE
One Drive training videos & documentation is NOT updated in the Learning Pathways playlists under One drive Products  

### ISSUE THREAD

**Issue by RaghuramanVenu** [pnp/custom-learning-office-365#758]
It is observed that One Drive cloud videos and documentation details in the Learning Pathways webpart or in the One Drive video are outdated which is not aligned with the latest Modern UI of One Drive cloud. 
How to get updated with latest videos /documentation in learning pathway of One Drive products.

1. Go to CustomLearningViewer.aspx page, click on the One Drive under Products.
2. Click any subcategory learning of One Drive for to check Videos & steps("Manage your files with  One Drive"  "One Drive Quick Start" )
3. Compare with  you current One Drive cloud Home page UI and you will find training videos & documentation are NOT matched and outdated.

_Learning Pathways version number_ - 4.3.1.0

**Comment by dcashpeterson** [comment]
@jhwang-ms Can you pass this on to the content team for OneDrive. It looks like they need a refresh.

**Comment by RaghuramanVenu** [comment]
> @RaghuramanVenu, Thank you for reporting this. Please allow us some time, we will get back to you ASAP.

Thanks, waiting for reply!

**Comment by RaghuramanVenu** [comment]
> @jhwang-ms Can you pass this on to the content team for OneDrive. It looks like they need a refresh.

Any update on the learning tutorials updates?

**Comment by dcashpeterson** [comment]
@RaghuramanVenu This has been passed on to the appropriate content team at Microsoft. Learning Pathways consumes this content but is not responsible for the updates. You can also get the URL for the specific asset and view that page outside of Learning Pathways and leave feedback on that page of what is not correct.

**Comment by RaghuramanVenu** [comment]
Any update on this One Drive Tutorial update from MS appropriate learning 
[
[Upload files and folders in OneDrive (work or school) - Microsoft Support](https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.microsoft.com%2Fen-us%2Foffice%2Fupload-files-and-folders-in-onedrive-work-or-school-5bd927ad-d186-495c-93e8-7ca116fe7b83&data=05%7C02%7CRaghuraman.Venugopal%40cognizant.com%7C3c0b23efa16249d7924508dc12b9eaf4%7Cde08c40719b9427d9fe8edf254300ca7%7C0%7C0%7C638405836985778376%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=G2yqtq8aL2EPIrb%2BQ3dFQapOtBc2lkf0dC5%2FhdCg%2FTc%3D&reserved=0)
](https://support.microsoft.com/en-us/office/upload-files-and-folders-in-onedrive-work-or-school-5bd927ad-d186-495c-93e8-7ca116fe7b83)

**Comment by dcashpeterson** [comment]
@RaghuramanVenu we don't have an update for that and the content owners don't notify us when they update content. Learning Pathways only consumes the content we do not create it. We don't have any insight into the content update schedule for that team. The request has been passed on. If you are looking for an update I would suggest logging feedback directly on that page (by clicking the Yes or No button under "was this content helpful" at the bottom of the page.
