### ISSUE TITLE
Content pack for Model Driven Apps or connecting to MS Learn [QUESTION] 

### ISSUE THREAD

**Issue by hsolsc** [pnp/custom-learning-office-365#761]
### What is the context of your question
[ ] Learning Pathways Content
[ ] Custom Content

### What is your question
My organisation is implementing Dynamics 365 / Model Driven Apps, for which we need to create a library of generic and custom support resources. **Are there any plans to add learning content for Dynamics 365 / Model Driven Apps?**

Assuming there are no plans to add this content as standard, I have experimented adding MS Learn articles as custom content in the SP Learning Pathways app (ver 4.0.0.0). The best resources I've found are at https://learn.microsoft.com/en-us/power-apps/. I have tried adding a specific learning article (https://learn.microsoft.com/en-us/power-apps/user/navigation) as custom content but it doesn't work. I have also tried embedding the learning article on a SharePoint page, but it seems MS Learn is preventing embedding. 

**Can you offer any advice for using MS Learn pages as custom content in the Learning Pathways app?**

Thanks again,
Hans

**Comment by v-asshrirao** [comment]
@hsolsc,
Thank you for reporting this. We will check with content team regarding content update plan.
Can you please let us know what issue you are getting while adding custom content?

**Comment by dcashpeterson** [comment]
@hsolsc This is not an issue that is specific to Learning Pathways. Unfortunately, there is content in learn, docs, and support that has a header that specifically prohibits iframing. All the content in Learning Pathways is pulled in from the source using an IFrame so these pages can't be pulled in. There is no work around for that. Sorry.
