### ISSUE TITLE
How to edit dropdown list showing available learning pathways in the upper left

### ISSUE THREAD

**Issue by mirimay** [pnp/custom-learning-office-365#763]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Submit your question
How can I edit the dropdown list showing available learning pathways in the upper left of the Home page?
I would like to change the title of the dropdown list items and also would like to know why/how some playlists are showing here and others not. 

### What is the context of your question

- [x ] Administration
- [x ] Custom Content

### What is your question

>Provide related screen-shots to help us understand your question
 
<img width="946" alt="image001" src="https://github.com/pnp/custom-learning-office-365/assets/155154065/d1c0e498-687f-41d5-971e-5c416074aaa6">

Thanks a lot in advance for any support!

**Comment by dcashpeterson** [comment]
@mirimay the navigation you referenced in your image is the site navigation. To edit those links you need to click the "edit" button to the right of the navigation. The link is to the right of Ask A Question or Request Help in your example. Here is a link to the documentation for that functionality [link](https://support.microsoft.com/en-au/office/customize-the-navigation-on-your-sharepoint-site-3cd61ae7-a9ed-4e1e-bf6d-4655f0bf25ca). 

I am not sure about your second question, if you are referring to playlists not being seen or playlists not being in the navigation. If you could please clarify the second part of your request we can try to assist.

**Comment by dcashpeterson** [comment]
Answered and closed
