### ISSUE TITLE
External users unable to view content 

### ISSUE THREAD

**Issue by TylerTweedy** [pnp/custom-learning-office-365#765]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

A Teams group has been added to a SharePoint Site. Within the Teams group, internal users have various permissions and ALL external users have visitor permissions. All internal users with visitor permissions are able to view M365LP content while all external users are unable to view M365LP content.   

### To Reproduce

>Adding external users to a Teams group and then adding the Teams group to a SharePoint Site. 

### Expected Behavior

>All members of the Teams group should be able to view all content within the associated SharePoint Site. 

### Screenshot
 
> External Visitor View
![image](https://github.com/pnp/custom-learning-office-365/assets/100965920/51803fa7-2713-4fb5-8e7e-3ca7e7471045)
> Internal Visitor View
![image](https://github.com/pnp/custom-learning-office-365/assets/100965920/7434d062-a054-4272-b2e1-36fca3cf9e7b)

### Learning Pathways version number

>4.3.0.0

### Additional context

>Add any other context about the problem here.

**Comment by dcashpeterson** [comment]
@TylerTweedy If you need assistance with Learning Pathways please fill out the rest of the information in the issue template so we can diagnose things better. We can't assist with a title only.

**Comment by TylerTweedy** [comment]
@dcashpeterson Just filled out the rest of the rest of the form. Hopefully this helps.

**Comment by dcashpeterson** [comment]
@TylerTweedy ahhhh, ok. This makes a lot of sense. The challenge here isn't a Learning Pathways issue it's a security issue with the App Catalog where the code for Learning Pathways lives in your tenant. The reason that internal users can see the webpart is that All Users Except for External has read only access to the app catalog. To fix this you (or an admin in your tenant) would need to ensure that the All Users group has read access to the app catalog. Alternately you can also turn on the public CDN. 

You can also check out issue #740. [Specifically this comment](https://github.com/pnp/custom-learning-office-365/issues/740#issuecomment-1601998882)

**Comment by TylerTweedy** [comment]
@dcashpeterson Thanks Derek! I don't have access to that and had a feeling it was something our IT admin would need to address but I was hoping I could be proactive and handle it myself. On a side note, will M365LP be retired as part of the "add-in" retirements on April 2, 2026?

**Comment by dcashpeterson** [comment]
@TylerTweedy no problem. Happy to help and I love that folks are using Microsoft 365 Learning Pathways. To answer your question about SharePoint Add-In model. M365 Learning Pathways is created as a webpart using SPFx. It was not created using the Add-In model so it will be unaffected. Closing this issue as answered. If you have any other questions feel free to open another issue.
