### ISSUE TITLE
Cannot add any custom subcategories, playlists, or assets

### ISSUE THREAD

**Issue by ryanmccutchen** [pnp/custom-learning-office-365#77]
#### Category

- [ ] Question
- [ ] Typo
- [ x ] Bug
- [ ] Additional article idea

When adding a custom Sub-Category, Playlist, or asset via the 'Microsoft Learning administration' it breaks all web parts in the site so they no longer render any content. All web parts in the site just show blank. Once the custom item is deleted, the content shows back up.

We also have the same experience trying to add a new playlist to any existing category.

We have the most recent version deployed.  No errors in the dev tools console. Tried across multiple machines and browsers. 

#### Steps to Reproduce

Go to the administration page / web part. Add anything. Content disappears from all web parts. Remove custom entry and content displays.

**Comment by ryanmccutchen** [comment]
I should clarify * all the learning content web parts stop displaying content. Not all web parts.

**Comment by juliemturner** [comment]
Since you said you're running the most recent version, can you confirm that this is 2.0.16 and that you updated your site collection as well as deploying that version to the tenant?

**Comment by ryanmccutchen** [comment]
I have version 2.0.15. I installed yesterday so I assumed I had the latest. Let me update to .16 and try again

**Comment by ryanmccutchen** [comment]
It looks like the new version 2.0.16 fixed the issue. Thank you
