### ISSUE TITLE
 Unable to Display content 

### ISSUE THREAD

**Issue by huiyatkin** [pnp/custom-learning-office-365#772]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

we found that there are some contents unable to load (please refer to screenshot), after checking, some embedded URL was wrong, for example, For the application - Word, insert a table of contents, the default embedded URL is https://support.office.com/en-us/client/882e8564-0edb-435e-84b5-1d8552ccf0c0?embed=true ,  if we copy and paste to a new web browser, the page is error. 

### To Reproduce

>Steps to reproduce the behavior

### Expected behavior

>A clear and concise description of what you expected to happen.

### Screenshots

![image](https://github.com/pnp/custom-learning-office-365/assets/159101542/ea2def77-631b-41db-84f9-10e383c58c06)

![image](https://github.com/pnp/custom-learning-office-365/assets/159101542/14c29a18-dc36-4305-b77b-bbd71b303d7e)

### Learning Pathways version number

4.4

### Additional context

>Add any other context about the problem here.

**Comment by v-asshrirao** [comment]
@huiyatkin, Thank you for reporting this. Please allow us some time, we will get back to you ASAP.

**Comment by clarelcampbell** [comment]
![image](https://github.com/pnp/custom-learning-office-365/assets/123638166/c0522dd4-f885-4068-927a-64664831d432)
Hi - to add that we have the same issue as well, here is the Word product

**Comment by clarelcampbell** [comment]
@jhwang-ms Hi - do you have any update please? thanks

**Comment by jhwang-ms** [comment]
Hi @clarelcampbell and @huiyatkin - thank you for flagging this with us. We're trying to work through these issues but it's not as easy of a fix as we thought and are working as fast as we can. I hope to be able to get a solution in this month, and we really appreciate everyone's patience and grace as we jump through technical hoops here.

**Comment by dcashpeterson** [comment]
@clarelcampbell  and @huiyatkin we are experiencing some technical challenges in our content updates. Please see #786 for further updates.

**Comment by dcashpeterson** [comment]
@clarelcampbell and @huiyatkin this looks like it has been resolved by the content team. Both the Change the Margins and the Table of contents content is loading correctly. I'm closing this issue but if you see it on other pages please create a new issue and reference this one.
