### ISSUE TITLE
 Metadata/ Playlist/ Asset titles are not fetched in UI but is displayed in Admin Centre 

### ISSUE THREAD

**Issue by Jeyeline** [pnp/custom-learning-office-365#773]
## Describe the bug

We have added a few categories and its relevant sub categories are added in the json file (metadata/ its playlist / its asset), and the code is pushed and committed. However, it is not being reflected the learning centre. However, in admin centre it is displayed. As it is not solved after multiple pushes, we were in a situation to create manually in UI.

We are raising the issue, since we faced this issue every incremental pushes

### To Reproduce

In the published page, add few categories and its relevant title and push it again

### Expected behavior

Once the code is pushed, the change has to be relflected

### Screenshots

![Admin](https://github.com/pnp/custom-learning-office-365/assets/104207461/7bffef7a-321a-46d6-9692-a60a327b1dbe)
The subcategory list is displayed here

![sharepoint](https://github.com/pnp/custom-learning-office-365/assets/104207461/fbfa2452-ed36-41c5-a0a0-2bb13284b0c0)
It is not reflected here

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

**Comment by dcashpeterson** [comment]
@Jeyeline Are you using a custom content pack for this content so when you say pushes and commits you have a custom content pack and you make changes and commit them to a private GitHub repo? If so have you tried emptying the cache in the lists in the backend? This sounds like a caching issue because the webpart doesn't have any understanding that the content has updated.

**Comment by Jeyeline** [comment]
@dcashpeterson We are using a public repo forked from here. If it is about the cache, how it should be cleared?

**Comment by dcashpeterson** [comment]
@Jeyeline a fork of this repo where you are directly editing the JSON would be considered a custom content pack. So there are a few things you should try.

First check your Learning Pathways Admin. In the webpart you should see a second tab next to Microsoft 365 Learning Pathways as shown in the picture below. Take note of the display name. The URL should be pointing to you fork.
![image](https://github.com/pnp/custom-learning-office-365/assets/45491456/09276ebc-a6b7-4afa-af16-d3b68d80737c)

On the page that you have your webpart added edit the page and edit the properties of the webpart. Make sure that the Learning Source is set to your custom content pack display name from the previous step.
![image](https://github.com/pnp/custom-learning-office-365/assets/45491456/e2db269f-3a0f-4c0f-be99-6c3e1b7f44e9)

If both of these are set up properly then you should manually empty the cache.

In the Administration site for Learning Pathways go to Site Contents > CustomConfig list.

Filter all the items by title CustomConfig. Select all of the items and delete them.

In a separate browser window/tab navigate to the home page for Learning Pathways Admin. As the webpart starts to load you should see the CustomConfig items start to regenerate. After that you can navigate to the page with the webpart on it and do a hard refresh of the page. This should fix the issue.

**Comment by Jeyeline** [comment]
Hello @dcashpeterson , we have performed the first two steps. 
If we perform a hard refresh by removing the custom configuration, will it impact my pages, or does it solely affect the cache?

**Comment by dcashpeterson** [comment]
There will be a short performance hit while the cache is being regenerated but that will be it. Another thing would be to remove any languages that you are not using. That will minimize the length of time it takes to regenerate the cache.

**Comment by Jeyeline** [comment]
@dcashpeterson , only 30 items are loaded by default, if we scroll down, the page gets hung. Shall we delete the custom configuration that is in the image? Will it be regenerated?



![custom](https://github.com/pnp/custom-learning-office-365/assets/104207461/b13b89d5-5529-4a19-8f1e-3176e04f2de6)

**Comment by Jeyeline** [comment]
@dcashpeterson / Team,

After deleting the cache, still facing the same issue. In the admin, all the titles are displayed, not in my custom-created path. attaching the screenshot.
![admin](https://github.com/pnp/custom-learning-office-365/assets/104207461/16b3a862-b792-4999-8cb6-13fa8c1fee5c)
![custom](https://github.com/pnp/custom-learning-office-365/assets/104207461/b85b1b56-0fa7-4418-802f-57473a3a1aa2)

**Comment by dcashpeterson** [comment]
@Jeyeline are you sure you deleted all the items with the title CustomConfig from the CustomConfig list? There are over 3000 items in that list and if you had deleted all the custom config items there shouldn't be that many event with a custom content pack. Also, can you please provide a screenshot showing the default language of the site Site Setting > Language Settings and a screen shot of one of the assets that isn't showing.

**Comment by Jeyeline** [comment]
@dcashpeterson , I deleted that file itself. Please find the SS of language settings and Category-Sub Category- Playlist-Asset in admin page

![image](https://github.com/pnp/custom-learning-office-365/assets/104207461/72ffff37-a799-450f-a23c-9371ab4c2941)

![language](https://github.com/pnp/custom-learning-office-365/assets/104207461/c61aa4c7-f952-426a-9526-831a4c6545b6)

**Comment by dcashpeterson** [comment]
@Jeyeline Can you create a view in the CustomConfig list and group the items by Title and then show the count of the different items? I am not sure what all 3000 items are in that list.

**Comment by Jeyeline** [comment]
@dcashpeterson we deleted the file. since it will re-generate, will take a snapshot share

**Comment by dcashpeterson** [comment]
Just to be clear this is what I am looking for
![image](https://github.com/pnp/custom-learning-office-365/assets/45491456/4f694761-1f89-4c40-bff5-11e5625b337f)

**Comment by Jeyeline** [comment]
@dcashpeterson , please find the same
![github](https://github.com/pnp/custom-learning-office-365/assets/104207461/a4580390-aee0-4931-ab96-03887765a9e9)

**Comment by dcashpeterson** [comment]
@Jeyeline if you only have one language are the 30 CustomConfig items recent? Also can you post a few more screen shots. For your Admin screen can you show the top of the webpart like this
![image](https://github.com/pnp/custom-learning-office-365/assets/45491456/e346f5ac-1f84-47c5-a2a1-ca5dcdeaf554)

and on the webpart that isn't working show the webpart configuration screen?
![image](https://github.com/pnp/custom-learning-office-365/assets/45491456/80586687-4775-41a5-9d3d-0de3e1f14dc3)

Also, on the page where the webpart isn't working can you please check the console and let me know if there are any errors that have an icon like this 🎓 near it.

**Comment by Jeyeline** [comment]
Hi @dcashpeterson ,

Please find the information
![image1](https://github.com/pnp/custom-learning-office-365/assets/104207461/76c7630f-588f-4693-8409-6ccfdd05224c)
![image2](https://github.com/pnp/custom-learning-office-365/assets/104207461/ef4affaf-d7a3-401f-b07d-5ff82f5b083a)


In console, we are not having error with that icon, rather having a message stating the tenant id with that icon

**Comment by dcashpeterson** [comment]
@Jeyeline sorry for the delay on this. I didn't forget. I'm trying to think of the best way to tackle this. It is most likely a caching or configuration issue. Question, when you look in the json in the CustomConfig items in the CustomConfig list do you see any of your assets in there? The values should be in the JSON.

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new issue and reference this one.
