### ISSUE TITLE
Error code with my VBA 

### ISSUE THREAD

**Issue by Miata-Lover** [pnp/custom-learning-office-365#776]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Garbled Chinese fonts

### Screenshots

![image](https://github.com/pnp/custom-learning-office-365/assets/152668569/e7a63dc1-5156-4726-a461-a6e4e8c0ae1e)

**Comment by dcashpeterson** [comment]
@Miata-Lover does this relate to Microsoft Learning Pathways? If so please complete the issues template and provide details on the issue with Learning Pathways.

**Comment by dcashpeterson** [comment]
Closing this as unrelated. @Miata-Lover  if this is Learning Pathways related please create a new issue and fill out the issues template to provide more information on how it is related to Microsoft Learning Pathways and what the error is.
