### ISSUE TITLE
 Image gallery webpart is not working

### ISSUE THREAD

**Issue by Jeyeline** [pnp/custom-learning-office-365#779]
## Describe the bug

We could not use the component/web part - Image Gallery is not working.

### To Reproduce

Add Image Gallery web part.

### Expected behavior

The component should be working fine.

### Screenshots

![image](https://github.com/pnp/custom-learning-office-365/assets/104207461/5df9a5e6-3078-4bdb-8ab4-6587cf0b2d75)

**Comment by dcashpeterson** [comment]
@Jeyeline this is not an issue with Microsoft Learning Pathways. It is an issue with an out of the box web part. Unfortunately, we can't assist in troubleshooting with this. For more information about the Image Gallery Web Part you can look here. https://support.microsoft.com/en-gb/office/use-the-image-gallery-web-part-bbcbe560-14a7-4369-8ef5-3255845e3bfd
