### ISSUE TITLE
An error occurred while processing your request. 

### ISSUE THREAD

**Issue by Tyr03** [pnp/custom-learning-office-365#780]
## Describe the bug

The following error appear on every playlist since today 

![image](https://github.com/pnp/custom-learning-office-365/assets/45770560/2e02d528-5fb6-4186-b440-7ffce44b5bf7)

Direct link also get me the error : https://support.office.com/fr-fr/f1/topic/set-categories-flags-reminders-or-colors-a894348d-b308-4185-840f-aff63063d076?embed=true

### Learning Pathways version number

4.4.0.0

**Comment by dcashpeterson** [comment]
@Tyr03 Thank you for letting us know. I have let the team know but they are in Redmond and are not online for a while. I will keep things posted here.

**Comment by Saskia-RHP** [comment]
Hi! I'm ffacing the issue too, just added learning pathways to our M365 tenant today.

**Comment by DevAncile** [comment]
Hello.
Looks like this behavior is caused by updates to Microsoft Support URL address. Non-working videos have "http://support.office.com/client/". 

The following video does not work "https://support.office.com/en-us/client/aee9c7ff-f9c5-415f-80dc-103ad5e344d7?embed=true". However, if you replace "http://support.office.com/client/" with "https://support.microsoft.com/en-us/office/"...the video works; "https://support.microsoft.com/en-us/office/aee9c7ff-f9c5-415f-80dc-103ad5e344d7?embed=true"

Will an update for all playlist, with new URLs, be available to the M365 Learning Pathways user community?

**Comment by dcashpeterson** [comment]
@Tyr03 It looks like this was a temporary issue and it is now resolved. I am no longer able to reproduce this on my end. Can you please check and see if you are still experiencing it? 

@DevAncile Unfortunately changing the URL doesn't provide a chromeless experience which is why we use the support.office.com url. They are just different endpoints to the same content.
![image](https://github.com/pnp/custom-learning-office-365/assets/45491456/5a79b3f0-a685-4feb-bd23-5a209b37a397)

**Comment by Saskia-RHP** [comment]
I myself am still running into the error, after the articles take an enternity to load.
![image](https://github.com/pnp/custom-learning-office-365/assets/161476906/7f5cc278-b932-4ab5-accf-ff16e315e936)

**Comment by Tyr03** [comment]
> @Tyr03 It looks like this was a temporary issue and it is now resolved. I am no longer able to reproduce this on my end. Can you please check and see if you are still experiencing it?
> 
> @DevAncile Unfortunately changing the URL doesn't provide a chromeless experience which is why we use the support.office.com url. They are just different endpoints to the same content. ![image](https://private-user-images.githubusercontent.com/45491456/308308059-5a79b3f0-a685-4feb-bd23-5a209b37a397.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDM4NjgsIm5iZiI6MTcwOTEwMzU2OCwicGF0aCI6Ii80NTQ5MTQ1Ni8zMDgzMDgwNTktNWE3OWIzZjAtYTY4NS00ZmViLWJkMjMtNWEyMDliMzdhMzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA2NTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNTMwMGI2ZjYzNzYwYmRlZTFkYzIzYTBkMjA4ODE4MTJmNTI2ODBkYmJkOTU3NzZlYjBiNmVlZmJkNDA4N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yDS079kPB5R1qAy9MfA1f9rgG9Z-B05O1sdoD0sug_k)

Thanks for your answer.

Unfortunately we still experience the error here, using one of the OOB playlist

![image](https://github.com/pnp/custom-learning-office-365/assets/45770560/5b174cf2-a096-4f07-8bb0-78b3b047e0d8)

**Comment by Tyr03** [comment]
> @Tyr03 It looks like this was a temporary issue and it is now resolved. I am no longer able to reproduce this on my end. Can you please check and see if you are still experiencing it?
> 
> @DevAncile Unfortunately changing the URL doesn't provide a chromeless experience which is why we use the support.office.com url. They are just different endpoints to the same content. ![image](https://private-user-images.githubusercontent.com/45491456/308308059-5a79b3f0-a685-4feb-bd23-5a209b37a397.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDM4NjgsIm5iZiI6MTcwOTEwMzU2OCwicGF0aCI6Ii80NTQ5MTQ1Ni8zMDgzMDgwNTktNWE3OWIzZjAtYTY4NS00ZmViLWJkMjMtNWEyMDliMzdhMzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA2NTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNTMwMGI2ZjYzNzYwYmRlZTFkYzIzYTBkMjA4ODE4MTJmNTI2ODBkYmJkOTU3NzZlYjBiNmVlZmJkNDA4N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yDS079kPB5R1qAy9MfA1f9rgG9Z-B05O1sdoD0sug_k)

Thanks for your answer.

[dcashpeterson](https://github.com/dcashpeterson) Unfortunatly we still experience the error here, using one of the OOB playlist

![image](https://github.com/pnp/custom-learning-office-365/assets/45770560/5b174cf2-a096-4f07-8bb0-78b3b047e0d8)

**Comment by dcashpeterson** [comment]
@Tyr03 and @Saskia-RHP Can you please try to clear the Learning Pathways cache as well as the browser cache and see if the issue persists. I checked my non-english users and was not able to still see the issue. I provided instructions below if you need them.

### To Reset Learning Pathways Cache
To clear the Learning Pathways cache, go to the Learning Pathways Admin site click on the gear and go to Site Contents > CustomConfig list. 

In the Custom Config list delete anything with a title of CustomConfig. (I normally filter the list by title and only show the CustomConfig titled items)

Go back to the Learning Pathways Admin screen and refresh the page. This will start the cache to rebuild. 

### To Clear Browser Cache
Navigate the to the Learning Pathways page where you are seeing the error
For Chrome Right click the page and select Inspect
Right click the refresh button and select Empty Cache and Hard Reload

Then go back to your page and see if the error persists.

Let me know how this works for you.

**Comment by Tyr03** [comment]
@dcashpeterson for information I just went back to the communication site where the learning pathway app is used, and the content is now visible again.

Seems the issue was not related to the Learning Pathways or Browser cache but it is now fixed

**Comment by Saskia-RHP** [comment]
@dcashpeterson Clearing the Learning Patchways Cashe seem to have helped on my side. Contents are actually loading and sites are loading in super-highspeed compared to before. Thanks :)

**Comment by dcashpeterson** [comment]
Happy to help. Thanks for using Learning Pathways, reporting the issue, and being part of the solution.
