### ISSUE TITLE
M£65 Learning Pathways on the sharepoint iPad app is showing "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance." 

### ISSUE THREAD

**Issue by Infoblox23** [pnp/custom-learning-office-365#785]
### What is the context of your question

- [ ] Installation
- [X ] Learning Pathways Content
- [ ] SharePoint Success Content
- [ ] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### What is your question

Hi All,

I am currently having an issue with my deployment of my m365 learning pathways sharepoint site. Everything works correctly when users are using sharepoint through a web browser on a PC, however all of my end users are getting this error message when accessing this site via the sharepoint app (Except the Global Admin who deployed the site). As this relates to the iPad app I am unable to provide a log, I'm hoping this is a quick fix

![Learningpathways](https://github.com/pnp/custom-learning-office-365/assets/166695486/917b3ac7-b126-4d67-9393-c647c4a70e70)

Any help would be much appreciated!

**Comment by dcashpeterson** [comment]
@Infoblox23 are you referring to the Teams App for Learning Pathways running on an IPad or are your users having an error accessing the SharePoint site from a web browser.

https://github.com/msft-teams/tools/tree/master/M365%20Learning%20Pathways

**Comment by Infoblox23** [comment]
Hi,

Thanks for getting back to me so quickly! 

the issue happens when the end user users the Sharepoint iPad App to access the M365 Learning Pathways Sharepoint Site we have deployed with the sharepoint look book. As I said previously it works completed fine for the global admin that pushed the site out but not for our end users, which is quite odd

Many thanks

**Comment by StfBauer** [comment]
Which IPad version are you experiencing this problem. Tested multiple iPads and my installation always worked.

**Comment by Infoblox23** [comment]
My iPad IOS version is 17.3

My Sharepoint App is the most recent up to date version on the app store

Thanks

**Comment by StfBauer** [comment]
So you are using the SharePoint App for MLP? I tried it in the browser.
What happens if you open Microsoft Learning Pathways direclty in the browser?

**Comment by Infoblox23** [comment]
Hi All,

Just to let everyone know I've found the problem! Our filtering meant that the URL: https://pnp.github.io/ was blocked.
How embarrassing!! Hopefully this will be helpful for anyone having this issue in the future

Thanks for the help everyone!!

**Comment by dcashpeterson** [comment]
@Infoblox23 Thanks for letting us know. Blocking PnP.github.io would definitely stop things from working. Closing the issue as resolved.
