### ISSUE TITLE
[QUESTION] Limit the App usage to only one site

### ISSUE THREAD

**Issue by flaghub** [pnp/custom-learning-office-365#787]
Hello,

Is there a way to limit the usage of the customlearning app ?
We don't want our users to be able to add it to their sites.

Do you think It could work inside a Site Collection App Catalog ? (not the Tenant App Catalog)
Or Do-you see any other option?

Thank you

**Comment by dcashpeterson** [comment]
@flaghub if you are doing a new manual install then yes putting it in a site collection app catalog would be the best way to do this. The other way would be to deploy it in the tenant app catalog and not check the box that says deploy to all site collections. The difference is that in a Site Collection app catalog the web part will only be visible in the Site Collection it is installed in. With the second option users could manually go to Add an App and then add the web parts from there.

I'm sure there is a valid reason for this but one of the benefits of Learning Pathways is that you can provide in-context learning for users and create custom content on those pages. By limiting the use of the webpart you can only use it in the Learning Pathways admin site and so for instance you would not be able to show say content about your expense reporting process on the HR page. 

I hope this helps.

**Comment by flaghub** [comment]
@dcashpeterson Thanks for your help.

I'll try the Site-coll app catalog
