### ISSUE TITLE
Can no longer "Add your tenant" to provision a Learning Pathways site

### ISSUE THREAD

**Issue by kris10bradley** [pnp/custom-learning-office-365#789]
On this page: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239, which looks like this: 

![LP1](https://github.com/pnp/custom-learning-office-365/assets/165331318/133beafe-fb73-4967-b2ed-b849023fd7bd)
, the button circled in red does not take you where it should and where it used to. 

Now it takes you to this page: https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/applying-pnp-templates

Whereas, it used to and is SUPPOSED to take you to a page that looks like this in order to build a Learning Pathways site: 
![LP 2](https://github.com/pnp/custom-learning-office-365/assets/165331318/e9d40275-69fd-4997-9255-5ce3e74f00be)

Please help!

**Comment by dcashpeterson** [comment]
@kris10bradley unfortunately the provisioning has been removed from the LookBook. This is true for Learning Pathways as well as all other solutions in that tool. The recommended advice is to follow the PnP Provisioning instructions that is linked to when you click the Add to my tenant button and follow the manual installation instructions for Learning Pathways. https://github.com/pnp/custom-learning-office-365/tree/main/installation

**Comment by kris10bradley** [comment]
Why was it removed? I'm a Change Manager with Core BTS, a Microsoft partner. Until that change me and my peers were able to set up a Learning Pathways site ourselves with SharePoint admin access alone. Now we would need access to PowerShell and to have more technical skills, which means we can't do it anymore and have to find a tech who may be able to. Is a better solution in the works? TY!

**Comment by dcashpeterson** [comment]
@kris10bradley unfortunately this was a decision that was made by Microsoft folks that I have no control. The links above are the best place to register your feedback and hopefully the powers at be will turn it back on. The PowerShell option is currently the only installation option available to us as you need PnP Provisioning in order to set up the template and to set the tenant app properties.

**Comment by dcashpeterson** [comment]
Closing this as answered. Pinned for other folks to see.
