### ISSUE TITLE
Manual web part - Could not find Microsoft 365 learning pathways Web Parts - Web part name changed

### ISSUE THREAD

**Issue by jreed336** [pnp/custom-learning-office-365#79]
#### Category

- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Running powershell script for new installation.  Have completed all pre-reqs and should install without error.

#### Observed Behavior

**Getting Error:**
......Could not find Microsoft 365 learning pathways Web Parts.
Please verify the Microsoft 365 learning pathways Package is installed and run this installation script again.

#### Steps to Reproduce
Install Version:
PS C:\temp\M365Learning\custom-learning-office-365-master\webpart> Get-PnPApp | Where-Object -Property title -Like -Value "Microsoft 365 learning pathways"

Id                                   Title                           Deployed AppCatalogVersion InstalledVersion
--                                   -----                           -------- ----------------- ----------------
94ce4d9a-3133-4340-9940-de6a1e1e5d56 Microsoft 365 learning pathways True     2.0.16.0          2.0.16.0

Run M365lpConfiguration.ps1

Looking at commands in script, the following looks like the problems are with the web parts changing names.
Running:
```
Get-PnPAvailableClientSideComponents -page CustomLearningViewer.aspx
Comes back with:
{141D4AB7-B6CA-4BF4-AC59-25B7BF93642D} **Microsoft 365 learning pathways**                CustomLearningWebPart
{C6062B6A-F22C-4475-897B-25081673C54A} **Microsoft 365 learning pathways administration** CustomLearningAdminWebPart
```

Line 154
`    if (Get-PnPAvailableClientSideComponents -page CustomLearningViewer.aspx -Component "Microsoft 365 learning pathways **Web Part**")`

Line 187
`Add-PnPClientSideWebPart -Page $claPage -Component "Microsoft 365 learning pathways **Web Part**"`

Changing them to the below seems to work:
Line 154
`    if (Get-PnPAvailableClientSideComponents -page CustomLearningViewer.aspx -Component "Microsoft 365 learning pathways")`

Line 187
`Add-PnPClientSideWebPart -Page $claPage -Component "Microsoft 365 learning pathways"`

Thanks!

**Comment by juliemturner** [comment]
Thanks, for your feedback. We are aware of the issue and looking into it. I'm not sure your fix will actually work as it doesn't appear that you're adding the administration web part to the administration page.  As soon as we have corrected the issue we'll update the script and close this issue.

**Comment by juliemturner** [comment]
The issue has been corrected, thanks for reporting it.
