### ISSUE TITLE
Video "Save a post or a message" not loading

### ISSUE THREAD

**Issue by matu007** [pnp/custom-learning-office-365#793]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

The video "Save a post or a message" in "Products -> Microsoft Teams -> Work with posts and messages" doesn't work.

### To Reproduce

Click on the following link: https://support.office.com/en-us/f1/topic/3f63e7d0-0011-47fa-99c0-98af60a71357

### Expected behavior

The video should load

### Screenshots

![Capture](https://github.com/pnp/custom-learning-office-365/assets/169249624/d4e476f1-dc0d-4d76-ac8f-748219278d9f)

### Learning Pathways version number

We installed Learning Pathways two months ago

### Additional context

>Add any other context about the problem here.

**Comment by dcashpeterson** [comment]
@matu007 thanks for reporting this. It looks like this is an issue with the [source content](https://support.microsoft.com/en-us/office/save-a-post-or-a-message-3f63e7d0-0011-47fa-99c0-98af60a71357). I have alerted the content owners of that page but other than that we don't have control over the content. I suggest that you log the issue using the "was this content useful" form at the bottom of the page as well.

**Comment by matu007** [comment]
@dcashpeterson : I understand that you are not responsible for the content, thank you for alerting the content owners.
I have sent them a feedback via the  "was this content useful" as suggested.
Hope this will solve the problem...
