### ISSUE TITLE
 Start-with-Six-Simple-Steps.aspx contains a long webpart

### ISSUE THREAD

**Issue by AndreaBelcastro** [pnp/custom-learning-office-365#794]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

When using the template , the page Start-with-Six-Simple-Steps.aspx created is not well defined since it have a long webpart that seems empty for the majority of the occupied space.

### To Reproduce

Create a page using the template

### Expected behavior

The webpart is rendered based on the content.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

4.4.0.0

### Additional context

>Add any other context about the problem here.

![immagine (1)](https://github.com/pnp/custom-learning-office-365/assets/169350677/53b77981-bdcf-49f5-a902-866d505847f2)
![immagine](https://github.com/pnp/custom-learning-office-365/assets/169350677/8da31b23-04b6-44b5-9539-f7864d296613)

**Comment by v-asshrirao** [comment]
@AndreaBelcastro , Thank you for reaching out to us. We will check this issue and get back to you ASAP
