### ISSUE TITLE
[QUESTION] Is it possible to prevent users from skipping assets in a playlist?

### ISSUE THREAD

**Issue by robsoto1** [pnp/custom-learning-office-365#796]
## Submit your question
Is it possible to prevent users from skipping assets inside a playlist by using the dropdown menu?

![LP-dropdown](https://github.com/pnp/custom-learning-office-365/assets/67113184/d8e4bb9a-f9d9-40f5-87e5-8e5c76a05c54)

### What is the context of your question
More often than not, the creator of a playlist wants the learners to go through the playlist in the order defined, but the dropdown menu allows the learners to skip forward without consequence.

- [ ] Installation
- [ ] Learning Pathways Content
- [ ] SharePoint Success Content
- [X] Administration
- [ ] Custom Content
- [X] Viewer Web Part

**Comment by dcashpeterson** [comment]
@robsoto1 there is no way to prevent users from skipping from one asset to another. Ideally they would click the next/previous button but from a user experience perspective, users need to feel like they have control over their environment so allowing them to skip around helps them to discover new content and also skip the content that they already know.

**Comment by dcashpeterson** [comment]
Closed as answered
