### ISSUE TITLE
Video does´nt play in Learning pathways in Teams, but in the web. 

### ISSUE THREAD

**Issue by PiaStider** [pnp/custom-learning-office-365#798]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

The video  is posted as a link from Stream, and I am the owner. Neither I, nor other people in the organisation kan play the video. The link is posted as "View" for everyone within the organisation. There are several similar videos posted by link showing the same issue. 

### To Reproduce

I was noticed by a user, and have the same issue myself and a colleague. I tried restarting Teams, same issue. Have not yet tried restarting the computer... 

### Expected behavior
I expected the video to play. 

### Screenshots
![image](https://github.com/pnp/custom-learning-office-365/assets/157601940/af4f73fe-deea-4d18-9037-a6baf61953b7)

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.

**Comment by dcashpeterson** [comment]
@PiaStider I am not sure based on this description what the issue is. Can you please provide more details on how you are using Learning Pathways, how to replicate the issue, and how this relates to the video you are referencing?

**Comment by dcashpeterson** [comment]
Closed as inactive
