### ISSUE TITLE
provisioning service fails

### ISSUE THREAD

**Issue by davepae** [pnp/custom-learning-office-365#8]
https://customlearningdemo.sharepoint.com

PnP provisioning fails to work on this new tenant. Provisioning started and then sent the admin this exception email:

Type = System.Exception Message = {"error":{"code":"-1, Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot find resource for the request SP.RequestContext.current/web/tenantappcatalog/."}}} Source = OfficeDevPnP.Core TargetSite = Void MoveNext() StackTrace = at OfficeDevPnP.Core.ALM.AppManager.<BaseAddRequest>d__39.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at OfficeDevPnP.Core.ALM.AppManager.<AddAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at OfficeDevPnP.Core.ALM.AppManager.Add(Byte[] file, String filename, Boolean overwrite, AppCatalogScope scope, Int32 timeoutSeconds) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant tenant, ProvisioningTenant provisioningTenant, FileConnectorBase connector, TokenParser parser, PnPMonitoredScope scope, ProvisioningTemplateApplyingInformation applyingInformation, ProvisioningMessagesDelegate messagesDelegate) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ProvisioningTemplateApplyingInformation provisioningInfo) at Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ProvisioningTemplateApplyingInformation applyingInformation) at SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext() in C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line 333 HResult = -2146233088

Note: After the PnP process failed. I followed the manual steps and was able to deploy the custom learning web part, ps1 and access the viewer/admin aspx pages.

**Comment by karuanag** [comment]
Transferring to SharePoint/SP-dev-docs repo for follow upl

**Comment by ksagala** [comment]
I've got other kind of error:
Here is the exception that occurred:
Type = Microsoft.SharePoint.Client.ServerException Message = List does not exist. The page you selected contains a list that does not exist. It may have been deleted by another user. Source = Microsoft.SharePoint.Client.Runtime ServerStackTrace = ServerErrorCode = -2130575322 ServerErrorTypeName = Microsoft.SharePoint.SPException ServerErrorTraceCorrelationId = afa9c89e-e09c-8000-56c4-b49595e814eb TargetSite = Void ProcessResponseStream(System.IO.Stream) StackTrace = at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream) at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse() at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceSites.ProvisionObjects(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser tokenParser, ProvisioningTemplateApplyingInformation applyingInformation) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ProvisioningTemplateApplyingInformation provisioningInfo) at Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ProvisioningTemplateApplyingInformation applyingInformation) at SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext() in C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line 333 HResult = -2146233088

**Comment by peterjkrebs** [comment]
Just repo'd Dave's Use Case. Created new tenant, created app catalog, logged in, provisioned service, got this exception: 

SharePoint Online       Provisioning Service       Unfortunately, your       request to provision       "Custom       learning for Office 365"        template failed.                                                                                       Here is the exception that occurred:       Type = System.Exception Message =       {"odata.error":{"code":"-1,       Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot       find resource for the request       SP.RequestContext.current/web/tenantappcatalog/."}}} Source = OfficeDevPnP.Core       TargetSite = Void MoveNext() StackTrace = at OfficeDevPnP.Core.ALM.AppManager.<BaseRequest>d__38.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       OfficeDevPnP.Core.ALM.AppManager.<DeployAsync>d__20.MoveNext() ---       End of stack trace from previous location where exception was thrown ---       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.Deploy(AppMetadata appMetadata,       Boolean skipFeatureDeployment, AppCatalogScope scope) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant       tenant, ProvisioningTenant provisioningTenant, FileConnectorBase       connector, TokenParser parser, PnPMonitoredScope scope,       ProvisioningTemplateApplyingInformation applyingInformation,       ProvisioningMessagesDelegate messagesDelegate) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       333 HResult = -2146233088                                                                                       PnP       Correlation ID: 8a680089-ff48-4129-9e23-27abdfa941a6              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues                                                                          SharePoint Online Provisioning Service     This is an automatic email and you shouldn't reply to it. |   | SharePoint Online       Provisioning Service       Unfortunately, your       request to provision       "Custom       learning for Office 365"        template failed. | SharePoint Online       Provisioning Service       Unfortunately, your       request to provision       "Custom       learning for Office 365"        template failed. |   | Here is the exception that occurred:       Type = System.Exception Message =       {"odata.error":{"code":"-1,       Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot       find resource for the request       SP.RequestContext.current/web/tenantappcatalog/."}}} Source = OfficeDevPnP.Core       TargetSite = Void MoveNext() StackTrace = at OfficeDevPnP.Core.ALM.AppManager.<BaseRequest>d__38.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       OfficeDevPnP.Core.ALM.AppManager.<DeployAsync>d__20.MoveNext() ---       End of stack trace from previous location where exception was thrown ---       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.Deploy(AppMetadata appMetadata,       Boolean skipFeatureDeployment, AppCatalogScope scope) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant       tenant, ProvisioningTenant provisioningTenant, FileConnectorBase       connector, TokenParser parser, PnPMonitoredScope scope,       ProvisioningTemplateApplyingInformation applyingInformation,       ProvisioningMessagesDelegate messagesDelegate) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       333 HResult = -2146233088 | Here is the exception that occurred:       Type = System.Exception Message =       {"odata.error":{"code":"-1,       Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot       find resource for the request       SP.RequestContext.current/web/tenantappcatalog/."}}} Source = OfficeDevPnP.Core       TargetSite = Void MoveNext() StackTrace = at OfficeDevPnP.Core.ALM.AppManager.<BaseRequest>d__38.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       OfficeDevPnP.Core.ALM.AppManager.<DeployAsync>d__20.MoveNext() ---       End of stack trace from previous location where exception was thrown ---       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.Deploy(AppMetadata appMetadata,       Boolean skipFeatureDeployment, AppCatalogScope scope) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant       tenant, ProvisioningTenant provisioningTenant, FileConnectorBase       connector, TokenParser parser, PnPMonitoredScope scope,       ProvisioningTemplateApplyingInformation applyingInformation,       ProvisioningMessagesDelegate messagesDelegate) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       333 HResult = -2146233088 |   | PnP       Correlation ID: 8a680089-ff48-4129-9e23-27abdfa941a6              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues | PnP       Correlation ID: 8a680089-ff48-4129-9e23-27abdfa941a6              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues | SharePoint Online Provisioning Service     This is an automatic email and you shouldn't reply to it.
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
 
SharePoint Online       Provisioning Service       Unfortunately, your       request to provision       "Custom       learning for Office 365"        template failed. | SharePoint Online       Provisioning Service       Unfortunately, your       request to provision       "Custom       learning for Office 365"        template failed.
SharePoint Online       Provisioning Service       Unfortunately, your       request to provision       "Custom       learning for Office 365"        template failed.
 
Here is the exception that occurred:       Type = System.Exception Message =       {"odata.error":{"code":"-1,       Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot       find resource for the request       SP.RequestContext.current/web/tenantappcatalog/."}}} Source = OfficeDevPnP.Core       TargetSite = Void MoveNext() StackTrace = at OfficeDevPnP.Core.ALM.AppManager.<BaseRequest>d__38.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       OfficeDevPnP.Core.ALM.AppManager.<DeployAsync>d__20.MoveNext() ---       End of stack trace from previous location where exception was thrown ---       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.Deploy(AppMetadata appMetadata,       Boolean skipFeatureDeployment, AppCatalogScope scope) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant       tenant, ProvisioningTenant provisioningTenant, FileConnectorBase       connector, TokenParser parser, PnPMonitoredScope scope,       ProvisioningTemplateApplyingInformation applyingInformation,       ProvisioningMessagesDelegate messagesDelegate) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       333 HResult = -2146233088 | Here is the exception that occurred:       Type = System.Exception Message =       {"odata.error":{"code":"-1,       Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot       find resource for the request       SP.RequestContext.current/web/tenantappcatalog/."}}} Source = OfficeDevPnP.Core       TargetSite = Void MoveNext() StackTrace = at OfficeDevPnP.Core.ALM.AppManager.<BaseRequest>d__38.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       OfficeDevPnP.Core.ALM.AppManager.<DeployAsync>d__20.MoveNext() ---       End of stack trace from previous location where exception was thrown ---       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.Deploy(AppMetadata appMetadata,       Boolean skipFeatureDeployment, AppCatalogScope scope) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant       tenant, ProvisioningTenant provisioningTenant, FileConnectorBase       connector, TokenParser parser, PnPMonitoredScope scope,       ProvisioningTemplateApplyingInformation applyingInformation,       ProvisioningMessagesDelegate messagesDelegate) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       333 HResult = -2146233088
Here is the exception that occurred:       Type = System.Exception Message =       {"odata.error":{"code":"-1,       Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot       find resource for the request       SP.RequestContext.current/web/tenantappcatalog/."}}} Source = OfficeDevPnP.Core       TargetSite = Void MoveNext() StackTrace = at OfficeDevPnP.Core.ALM.AppManager.<BaseRequest>d__38.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       OfficeDevPnP.Core.ALM.AppManager.<DeployAsync>d__20.MoveNext() ---       End of stack trace from previous location where exception was thrown ---       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.Deploy(AppMetadata appMetadata,       Boolean skipFeatureDeployment, AppCatalogScope scope) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant       tenant, ProvisioningTenant provisioningTenant, FileConnectorBase       connector, TokenParser parser, PnPMonitoredScope scope,       ProvisioningTemplateApplyingInformation applyingInformation,       ProvisioningMessagesDelegate messagesDelegate) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       333 HResult = -2146233088
 
PnP       Correlation ID: 8a680089-ff48-4129-9e23-27abdfa941a6              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues | PnP       Correlation ID: 8a680089-ff48-4129-9e23-27abdfa941a6              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues
PnP       Correlation ID: 8a680089-ff48-4129-9e23-27abdfa941a6              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues
SharePoint Online Provisioning Service     This is an automatic email and you shouldn't reply to it.

**Comment by michaelblumenthal** [comment]
I get two different problems when trying to provision Custom Learning. 
First, I get an endless authentication loop.  The page never renders but I can see the URL changing.  Here are two URLS that I copied from the loop.
https://login.microsoftonline.com/common/oauth2/authorize?client_id=5d9fff84-5b34-4204-bc91-3aaf5f298c5d&response_mode=form_post&response_type=code%20id_token&scope=openid%20profile&state=OpenIdConnect.AuthenticationProperties%3Deo0rgYFsd-LtCz8U2ipQHuOc7fPeQI7KISzJLw5lOaFCqYaKXszHNDmvpbL1oyuwYVFP1OQSJoEvuCfgYLL9lc5ZHg8YKC7h-FvmHtquV5jjdLmt3di4YAabw37IjSNnOtD3ae-r0f-bPauROAV_TVOd29tQL7B-H_JpZnkZ7JyAm7mtZk9A9s7FjPkNv1rWrvn5iUZBNyqLy-IsrZR8mABUtaeDZTIGheYwVhV7q48&nonce=636881760175004898.ZTk2ZTAyMzUtZTA5Ny00ZDRkLWE1YjYtNmIxZWYxY2YyMzE0OTQ4NTBjOWQtNzA4My00ZThjLWI5MGEtZmJkOTAyNzU3NWI2&x-client-SKU=ID_NET451&x-client-ver=5.2.1.0

https://login.microsoftonline.com/common/oauth2/authorize?client_id=5d9fff84-5b34-4204-bc91-3aaf5f298c5d&response_mode=form_post&response_type=code%20id_token&scope=openid%20profile&state=OpenIdConnect.AuthenticationProperties%3Dmmzovp7NLR0EBoiCaiAuYR5YmBa_HWRZr6sLvrGglHa9vPv1hcSn6Jig4aC2YuQ3RCdMyS4_qmCj9bgKNJjKG-L0jv-fxvDaVtYcBY2-KKZ3ZofXhkyY693GTTpTdSIhhRC-uZVDLoIdemGnOn17FK5yGZyYz3-zoyvGUeYqU_MUgSNoEkBPt1ySGlX9n_mRazr0naSGVV03mc4Gj6_DdRWI6DrxAeHYph-almYLOlo&nonce=636881760354865886.NDI3N2U4YjctNWFkMy00MzY2LWI0YWQtMWM0NTZiOTkzOWMwN2QzN2FkNDItNWJlNy00OGRlLWFhYTUtZmU2ZmMxNDJkNjQw&x-client-SKU=ID_NET451&x-client-ver=5.2.1.0

**Comment by michaelblumenthal** [comment]
Second, I opened Edge in a private browser session and tried provisioning.  This time, after logging in with my tenant admin account, it gave me the following error.  

Sorry, something went wrong
There was an unexpected issue. Please try again after a while.
IDX21323: RequireNonce is '[PII is hidden]'. OpenIdConnectProtocolValidationContext.Nonce was null, OpenIdConnectProtocol.ValidatedIdToken.Payload.Nonce was not null. The nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'. Note if a 'nonce' is found it will be evaluated. 


at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator.ValidateNonce(OpenIdConnectProtocolValidationContext validationContext) at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator.ValidateAuthenticationResponse(OpenIdConnectProtocolValidationContext validationContext) at Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationHandler.<AuthenticateCoreAsync>d__1a.MoveNext()

**Comment by juliemturner** [comment]
Please submit issues with Provisioning service completing to https://github.com/SharePoint/sp-dev-docs/issues.  If you have issue with the site or webpart after it's provisioned please post those to this issue list.
