### ISSUE TITLE
Some parts of a course link to wrong content? 

### ISSUE THREAD

**Issue by Take4aWalk** [pnp/custom-learning-office-365#800]
Hi, i described below, if more info is needed, please tell me
thanks in advance

## Describe the bug

Some Courses Link to wrong Content - a good example is the "One Note" Course - when Navigating to the "Intro to OneNote" piece i get redirected to some Excel Content? Was the link changed or is there and issue at the root? 
If the link was updated, how do we get info about actions like this?

### To Reproduce

Check OneNote Course and select "Intro to OneNote"

### Expected behavior

to open the right content?

### Screenshots

![image](https://github.com/pnp/custom-learning-office-365/assets/157599958/f821f52e-3cb8-4357-81e8-60cd79537df7)
![image](https://github.com/pnp/custom-learning-office-365/assets/157599958/a8627950-da49-4252-8bf7-8ded05ab3df7)

### Learning Pathways version number

4.4.0.0

**Comment by dcashpeterson** [comment]
@Take4aWalk Thanks for brining this to our attention. I have assigned it to @jhwang-ms who is on the content team to relay to the correct people.

**Comment by Take4aWalk** [comment]
@dcashpeterson Thanks for bringing the right person to the thread, 
@jhwang-ms, Is there a time frame in which I can expect an response?

kind regards and thanks in advance

**Comment by Rosie-EAH** [comment]
We are seeing the same issue in the Teams content, when clicking the link for "Microsoft Teams help":
![image](https://github.com/user-attachments/assets/5dca730d-eeb4-44b2-a90f-482ce4bd04f2)

We get this:
<img width="264" alt="image" src="https://github.com/user-attachments/assets/9326879c-6c91-4a4f-b55e-05073d3e0613">

**Comment by dcashpeterson** [comment]
@Take4aWalk I have rolled out a fix for the OneNote content issues. You will need to clear the cache in Learning Pathways to see the changes. This should be rolled out to all languages. @Rosie-EAH I am working through the other content issues. If you wouldn't mind creating a new issue for the Teams content. I can resolve that one seperatly.

**Comment by Rosie-EAH** [comment]
> @Take4aWalk I have rolled out a fix for the OneNote content issues. You will need to clear the cache in Learning Pathways to see the changes. This should be rolled out to all languages. @Rosie-EAH I am working through the other content issues. If you wouldn't mind creating a new issue for the Teams content. I can resolve that one seperatly.

Hi Derek - thanks for the update.  We've sadly had to move on from MLP due to the issues, but may return in the future to link to the content from our new "destination" once it's been resolved.

**Comment by Take4aWalk** [comment]
@dcashpeterson  thanks alot for taking care, in order to also fix that issue inside of the teams course, do i need to open a new issue? or can you solve that without?

and will this change be refelected somewhere in a official documentation or kind or update log?

thanks in advance

**Comment by dcashpeterson** [comment]
@Take4aWalk if you wouldn't mind I would appreciate a separate ticket for different content. Then I can track it appropriately.
