### ISSUE TITLE
 Beta V5 - CustomLearningAdmin.aspx not load

### ISSUE THREAD

**Issue by KaveSys** [pnp/custom-learning-office-365#803]
Hello,
I have just update the package from 4.4 to 5.0.0 and CustomLearningAdmin.aspx load blank.I have followed the instruction, see screenshoot:

![image](https://github.com/pnp/custom-learning-office-365/assets/152485719/29d609c0-1874-4d3b-94b7-2326352a38e2)

**Comment by dcashpeterson** [comment]
@KaveSys hi there, Thanks for helping with the testing. Can you please provide us with the contents of the developer console to see if there are any errors?

**Comment by KaveSys** [comment]
Hello @dcashpeterson,
You mean these below?

![image](https://github.com/pnp/custom-learning-office-365/assets/152485719/b2b6ed91-e4f1-4010-b31f-94e0967b7fbd)

I have tried to delete cookies/cache but with no luck

**Comment by dcashpeterson** [comment]
@KaveSys is your tenant on targeted release? I have been able to replicate the issue when using a targeted release tenant but not standard release. The fix is to delete the sppkg file and add the new V5 version. If you are not on targeted release that might be something different.

**Comment by javalila** [comment]
Hi @dcashpeterson i got exactly the same issue as @KaveSys described. In our case we are using standard release and I added the app to the tenant app catalog.

**Comment by dcashpeterson** [comment]
@javalila thanks or chiming in. do you have any errors in the console? Also, how did you do the install of the new version. Was it a clean install in a new environment of was it over an existing install (please provide version number)

**Comment by javalila** [comment]
@dcashpeterson It was a update from the version 4.4 to 5.0. I do have these errors in my console: 
![image](https://github.com/pnp/custom-learning-office-365/assets/82218567/b2c9c431-8dae-4e15-95d6-0272ea9a9bee)

**Comment by dcashpeterson** [comment]
@javalila and @KaveSys I have a version of the sppkg file that you can try to see if it fixed your issue. One other thing you will need to do, I realized it's missing from the instructions is approve the API access for the file picker. Try this version and let me know if it fixes the issue.
https://github.com/pnp/custom-learning-office-365/tree/v5/installation/Beta/V5_0_0_Beta

**Comment by javalila** [comment]
@dcashpeterson I've just installed the new verision and approved the API access (did this before installing aswell). But the CustomLearningAdmin.aspx is still emtpy with the same errors in console.

**Comment by dcashpeterson** [comment]
@javalila can you check and see in Site Content > Microsoft 365 Learning Pathways > click details from the elipsis and if it asks you to get the latest version and the version number listed in the details? I was previously able to replicate the issue you were both describing however with the latest build I have been unable to make it happen again in 4 different tenants.

**Comment by javalila** [comment]
@dcashpeterson It shows me this: 
![image](https://github.com/pnp/custom-learning-office-365/assets/82218567/1224e567-b1a5-41f4-9f76-df81f24b76dd)

**Comment by KaveSys** [comment]
Removing the "old" sppkg and tried the new provided is working!
![image](https://github.com/pnp/custom-learning-office-365/assets/152485719/5b9e0de9-2fbd-4ecc-ac66-26a6d20b8442)
 
 On top of that, please fix the issues that comes out after updating to 4.0.0 version, like described and listed here: https://github.com/pnp/custom-learning-office-365/issues/786
 
 Thanks @dcashpeterson 🥇

**Comment by dcashpeterson** [comment]
@KaveSys glad that worked for you. @javalila did you try removing the old package and adding the new one?

**Comment by javalila** [comment]
Removing, was the key to success. 
 
Thanks a lot @dcashpeterson for your support! 💯

**Comment by dcashpeterson** [comment]
great. I am going to close this. If this issues pops up again folks can reference this issue.
