### ISSUE TITLE
 Custom content pages displaying a copy of the suite bar

### ISSUE THREAD

**Issue by wmowenwm** [pnp/custom-learning-office-365#804]
## Describe the bug

There is now a copy of the suite bar displaying on pages that we've created as part of our range of custom learning content. Not exactly sure when this started appearing but we noticed it on the 5th July 2024.

While it doesn't break any functionality, this extra bar may confuse users.

### To Reproduce

>Steps to reproduce the behavior

### Expected behavior

The pages were previously loading without this suite bar.

### Screenshots
![image](https://github.com/pnp/custom-learning-office-365/assets/175004206/d8c567e7-93a0-4a4a-ac52-ccfd2a8a11c8)

### Learning Pathways version number

4.3.0.0

### Additional context

The app launcher is displaying blank. The search box doesn't work. The profile pic just shows a sign out option.

**Comment by v-asshrirao** [comment]
@wmowenwm, Thank you for using LP.
Please allow us some time to go through the issue, we will get back to you ASAP.

Meanwhile can you try to upgrade to latest 4.4 version.

**Comment by dcashpeterson** [comment]
@wmowenwm I agree that this is confusing for the user and thanks for bringing this to our attention. This change was part of a security update that Microsoft made to SharePoint pages. Unfortunately, there isn't anything we can do on the Learning Pathways side to get around this.

**Comment by wmowenwm** [comment]
Thanks for looking into this @dcashpeterson. It's a shame to hear it's here to stay. One other thing I noticed is that SharePoint seems to keep scroll positioning when you select a playlist, so you start partway down your page. I think this may have been the case before the security update though.

**Comment by dcashpeterson** [comment]
@wmowenwm that has been the case for a while. Unfortunately, we can't detect the height of the page that is being Iframed in so we need to make the iframe longer to accommodate any content. V5 has a sticky header so it's easier to navigate when you are farther down the page.

**Comment by dcashpeterson** [comment]
closing as answered
