### ISSUE TITLE
Playlist dropdown menu behavior is unexpected (v5 beta)

### ISSUE THREAD

**Issue by joshtransient** [pnp/custom-learning-office-365#810]
## Describe the bug

The assets for a playlist can only be selected by clicking the downward-pointing chevron on the right side of the dropdown menu that appears between the "Previous" and "Next" buttons on an asset page. With such a large menu element, I'd expect to click anywhere on the menu to see its dropdown options.

The behavior, instead, acts like a plain text field. If this menu is to have text field powers, I'd expect it to:
- Either have an "x" button to clear the existing text, or to automatically highlight the text so I can start typing to replace the highlighted text
- Autocomplete with wildcard matching, not just matching from beginning of the string (thinking about very large playlists)
- Disappear when the "Previous" and "Next" buttons are clicked.

As of the submission date of this issue, the menu currently does none of those things.

### To Reproduce

1) Open an asset from a playlist
2) Click anywhere on the dropdown menu between "Previous" and "Next" except for the downward-point chevron on the right side - the dropdown menu options don't even appear
3) Remove the text in the dropdown menu with your keyboard, then try typing a word in the middle of a playlist asset name - wildcard matching is not available
4) Remove the text in the dropdown menu again, then click "Previous" to the left, or "Next" to the right - the menu remains open and does not disappear

### Expected behavior

Common UI behaviors (as previously noted) for a dropdown menu supporting user-typed options.

### Learning Pathways version number

5.0.0.1

**Comment by dcashpeterson** [comment]
@joshtransient Thanks for helping with the testing. We will take a look at these and see the best course of action.

**Comment by dcashpeterson** [comment]
@joshtransient the drop down in the asset viewer is not meant to have auto complete so you should not have been able to type in the box. I have updated the control and pushed out an updated version 5.0.0.2. Thanks for your help testing.
