### ISSUE TITLE
 Teams application loading issue: Error initializing application (v5 beta)

### ISSUE THREAD

**Issue by joshtransient** [pnp/custom-learning-office-365#819]
## Describe the bug

When I upgraded from 5.0.0.1 to 5.0.0.2 I simply dropped the sppkg into the App Catalog and let the solution reinstall. However, when I got to the "approve access" pane, I received an error banner saying "Could not add app to Teams. You can add it later in Manage App page":

![could-not-add](https://github.com/user-attachments/assets/4465e7a5-5881-428d-9804-4d2017eb44b2)

I checked the Teams admin center to confirm that the app was enabled, which it was. However, the "Microsoft 365 learning pathway" (sic) app fails to load, but displays a classic SharePoint error page containing:

> Can't load the application on this page. Use the browser Back button to retry. If the problem persists, contact the administrator of the site and give them the information in Technical Details.
> 
> TECHNICAL DETAILS
> Error details: Error: Error initializing application. Error: TypeError: Cannot read properties of undefined (reading 'componentType')

This happens when trying to add it as a personal app to Microsoft Teams:
![personal-app](https://github.com/user-attachments/assets/bdc2d65a-db26-44a3-bdd4-ea7c974b67e3)

...or attempting to add it to a Teams channel:
![team-app](https://github.com/user-attachments/assets/22f6f1e5-3a12-4bdb-a673-e373dce4f70e)

### To Reproduce

Add the app named "Microsoft 365 learning pathway" (sic) as a personal Microsoft Teams app, or add it to a Teams channel.

### Expected behavior

The application should load, or - if Teams functionality was not intended - the app should not be present in the list of Microsoft Teams apps.

### Learning Pathways version number
5.0.0.2

### Additional context
After seeing that errors upgrading from 5.0.0.0 to 5.0.0.1 could be resolved by deleting and replacing the sppkg, I did the same, but still received the same "could not add" and "error initializing application" errors in their respective locations after a clean re-install of the solution.

During a clean re-install of the solution, the "could not add" error message is a result of a POST to `/sites/appcatalog/_api/web/TenantAppCatalog/SyncSolutionToTeams`. The response of that call is:

> { "error": { "code": "-1, System.Net.WebException", message": "The remote server returned an error: (409) Conflict." } }

**Comment by dcashpeterson** [comment]
@joshtransient thanks for reporting this. We will take a look.

**Comment by dcashpeterson** [comment]
@joshtransient thanks for bringing this to our attention. This is a documentation issue and I have updated it with the V5 release. If you want to install Learning Pathways to Teams using the app catalog you need to do a tenant wide deployment. The button in the new app catalog experience will always fail if you don't do tenant wide deployment. 

If you don't want to do a tenant wide deployment and want to deploy Learning Pathways as a Personal app you can enable it in the root site collection. If you would like to deploy it as a Teams tab you need to enable the Learning Pathways app in each team you would like to use it in. 

Thanks for your assistance in the testing. The documentation has been updated.
