### ISSUE TITLE
[QUESTION] Firewall URL/IP whitelist

### ISSUE THREAD

**Issue by jhuangz1989** [pnp/custom-learning-office-365#822]
Our network has firewall rules that is currently blocking Microsoft Learning Pathways and I am looking for a list of IPs/URL's to whitelist.

I have tried searching for this information to no luck, so hoping for some guidance here.

I do not have access to our firewall so I am not able to check via logs.

**Comment by v-ajaysahu** [comment]
@jhuangz1989 , Typically, you should whitelist the following URLs: https://support.office.com/, https://docs.microsoft.com/, and https://pnp.github.io/.

**Comment by dcashpeterson** [comment]
closed as answered
