### ISSUE TITLE
Provisioning Site Down

### ISSUE THREAD

**Issue by sltyler1** [pnp/custom-learning-office-365#823]
Using the link for [Microsoft 365 learning pathways solution page](https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239) from page [Custom Provision](https://learn.microsoft.com/en-us/office365/customlearning/custom_provision) directs you to a 'site can't be reached' error. I've tried this on several computers and browsers, plus on different networks.

**Comment by v-ajaysahu** [comment]
@sltyler1 , thank you for reporting this.
Unfortunately, Lookbook is down. Please follow the instructions in the provided link to provision Microsoft 365 learning pathways.

https://github.com/pnp/custom-learning-office-365/blob/main/installation/README.md

**Comment by sympmarc** [comment]
The Lookbook isn't down: it's no more. I did a blog post about this today when I saw this thread. https://sympmarc.com/2024/07/29/sharepoint-lookbook-whats-happened-to-it/

**Comment by AmauryVanEspen** [comment]
So, manual steps seems to be here : [Install PathWay](https://learn.microsoft.com/fr-fr/office365/customlearning/custom_manualsetup)

**Comment by dcashpeterson** [comment]
Closing as answered
