### ISSUE TITLE
'Read article in web broswer' links broken

### ISSUE THREAD

**Issue by TomMeadows1990** [pnp/custom-learning-office-365#824]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

I have webparts across several pages and a user with accessibility issues needs to view the articles in the browser. The links were working a couple of weeks ago but now I receive an error message '404: Page Not Found'

### To Reproduce

Open a webpart, scroll to the bottom of the text, click 'Read article in web browser'

### Expected behavior

The article should open in web browser

### Screenshots

![image](https://github.com/user-attachments/assets/917308a5-eea6-451b-a933-e696f74bd082)

![image](https://github.com/user-attachments/assets/03cc7d6f-a124-4b98-9593-c59f4f437821)

### Learning Pathways version number

I'm not sure how to find this. 

### Additional context

>Add any other context about the problem here.

**Comment by v-ajaysahu** [comment]
@TomMeadows1990 , thank you for reporting this issue. Please specify the pages or sections where you are encountering this issue.

**Comment by TomMeadows1990** [comment]
> @TomMeadows1990 , thank you for reporting this issue. Please specify the pages or sections where you are encountering this issue.

Thanks for your quick response. It appears to be all of them, but I'll quote some of them below - the weblinks just say https://support.microsoft.com/en-us/article/undefined?ns=null&version=undefined:

Get started with Teams
Get Started with Teams and Channels 
Overview of Teams and Channels
Get Started with Chat
Create and send an Email
Create an email signature

These are all the ones I've tried this morning and they all have the same error, so it appears to be across the board. 

I've managed to find the version of Pathways too and the screenshop is below:

![image](https://github.com/user-attachments/assets/14908b11-aa66-4987-b2ae-22ecf7d49cbd)

**Comment by v-ajaysahu** [comment]
Hi @jhwang-ms - Assigning this to you since this is a content issue.

**Comment by TomMeadows1990** [comment]
> Hi @jhwang-ms - Assigning this to you since this is a content issue.

Hi there, I've just checked and the links appear to be working again

**Comment by dcashpeterson** [comment]
closing as resolved. If there are other pages where it doesn't work please create a new issue and reference this one.
