### ISSUE TITLE
 Entire page showing in Learning Pathways web part instead of just asset (page) contents

### ISSUE THREAD

**Issue by robsoto1** [pnp/custom-learning-office-365#825]
Description:

All custom subcategories with custom playlists are showing the entire page in the web part instead of just the page content

Steps to reproduce the issue:

In a M365 tenant with LP installed and has the latest changes from Microsoft for page design, create a custom subcategory, create a playlist, then create an asset. Create a new page or use the home page of the site to place the Learning Pathways web part on the page. Filter the web part to show subcategories and choose the custom one you created. Enter the course, and you will see the entire page embedded, instead of just page contents. You will see the hub menu, M365 suite bar, profile icon, search bar, and the page title. 

Expected behavior

Only the page contents should show up, not the entire embedded browser page. This is only happening with custom assets, not built-in assets from Microsoft. In the provided screen shot, only the text "test text" should be appearing in the web part. I've highlighted the unexpected elements. None of those should be appearing. They didn't used to appear.

Screenshots

![m365lp-issue](https://github.com/user-attachments/assets/a4b88043-5240-4861-aebf-17b75a8c7901)

Learning Pathways version number

4.4.0.0

Additional context

My tenant is on targeted release, not standard release

**Comment by dcashpeterson** [comment]
@robsoto1 this is a new change from Microsoft regarding the header and suitebar. Unfortunatly there is nothing we can do about that in Learning Pathways. Please see #894 for additional details.
