### ISSUE TITLE
Microsoft.com refuses to connect

### ISSUE THREAD

**Issue by Emac725** [pnp/custom-learning-office-365#829]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Link to Microsoft article does not display

A clear and concise description of what the bug is. Same issue as #250
 https://github.com/pnp/custom-learning-office-365/issues/250

**### To Reproduce**

>Steps to reproduce the behavior

1. **** Added URLs in Customized Learning for Windows 11 topic:****

https://www.microsoft.com/en-us/windows/compare-windows-11-home-vs-pro-versions?msockid=39d026b36c7d609003bf3557687d66f5

https://support.microsoft.com/en-us/windows/how-to-use-the-taskbar-in-windows-0657a50f-0cc7-dbfd-ae6b-05020b195b07#WindowsVersion=Windows_11

https://www.microsoft.com/en-us/windows/tips/file-explorer

![M365LP issue URL in Playlist](https://github.com/user-attachments/assets/e7ba49b0-6e87-44da-b412-c6f2e63d13c6)

When I click on the link in the playlist in our training site, the URL won't display, only a grey window with a message, "microsoft.com refused to connect."

![M365LP issue Microsoft refused](https://github.com/user-attachments/assets/bec3304f-7be8-47aa-9b88-d5ceb65481b4)
Looking at the code, X-Frame options refused to display.
[
![M365LP issue XFrame code](https://github.com/user-attachments/assets/deebfc83-337f-4f54-9cbb-e08f0765bb75)
](url)
### Expected behavior
When selecting the playlist item in our training site, the URL displays like other URLs. (support.microsoft,com/)

>A clear and concise description of what you expected to happen.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.
I don't see one, not sure where to locate it.
### Additional context

>Add any other context about the problem here.

**Comment by dcashpeterson** [comment]
@Emac725 this is a security issue with browsers and not an issue with Microsoft Learning Pathways. Not all web pages allow themselves to be added to a page via an IFrame, which is how content is added to Microsoft 365 Learning Pathways. Unfortunately, there is no fix for this other than you creating a custom page in your tenant and copying the content over.
