### ISSUE TITLE
We are seeing the same issue in the Teams content, when clicking the link for "Microsoft Teams help":

### ISSUE THREAD

**Issue by Take4aWalk** [pnp/custom-learning-office-365#840]
We are seeing the same issue in the Teams content, when clicking the link for "Microsoft Teams help":
![image](https://github.com/user-attachments/assets/5dca730d-eeb4-44b2-a90f-482ce4bd04f2)

We get this:
<img width="264" alt="image" src="https://github.com/user-attachments/assets/9326879c-6c91-4a4f-b55e-05073d3e0613">

_Originally posted by @Rosie-EAH in https://github.com/pnp/custom-learning-office-365/issues/800#issuecomment-2250726446_

**Comment by Take4aWalk** [comment]
@dcashpeterson enough like this ?

**Comment by dcashpeterson** [comment]
If you could give me the path to the playlist/asset that would be great. Like Home > OneDrive > OneDrive Quick Start.

Other than that it's perfect.

**Comment by dcashpeterson** [comment]
@Take4aWalk checking in on this to see if it is still an issue or else I can close.

**Comment by Take4aWalk** [comment]
seems like no issue anymore

**Comment by Take4aWalk** [comment]
Hey @dcashpeterson, I just noticed that there is still an issue with German OneNote MLP
'OneNote Schnellstart' -> 'Einrichten ihrer mobilen apps' (https://support.office.com/de-de/client/a0628ad1-319f-429f-a79a-c188272d3c98?embed=true)
