### ISSUE TITLE
 CustomLearningAdmin.aspx is blank after 5.0.0.4 update

### ISSUE THREAD

**Issue by Tyr03** [pnp/custom-learning-office-365#843]
## Describe the bug

After updating for the 4.4 to the 5.0.0.4 Custom learning app the CustomLearningAdmin.aspx shows nothing, the CustomLearningViewer.aspx is still working.

Accessing the Graph API was approved but no Data Upgrade was asked when accessing the page

### To Reproduce

 Update from the 4.4 to the 5.0.0.4, custom installation of the 4.4 was performed to have French as default and only version and Opt out of Telemetry

CustomLearningAdmin.aspx and CustomLearningViewer.aspx was left unpublished as not instruction required to do so, I tried to publish them as major version after the update but nothing changed

### Expected behavior

Learning Admin page to show up

### Screenshots

![image](https://github.com/user-attachments/assets/31e7b360-4437-4535-869c-15fb2e00c59a)

### Learning Pathways version number

5.0.0.4

**Comment by dcashpeterson** [comment]
hello @Tyr03 we did see this with a few of our testers. You can fix it by deleting the sppkg file from the app catalog and re uploading it. https://github.com/pnp/custom-learning-office-365/blob/main/installation/V5Install.md#beta-installation-notes

**Comment by Tyr03** [comment]
Thanks the page is not showing up.

But it messed up the API access, I have approved 3 time cause I got an error. After refreshing this is what I see 

![image](https://github.com/user-attachments/assets/84ab4373-a367-4b76-b3bc-ee941baad79d)

**Comment by dcashpeterson** [comment]
@Tyr03 That is fine but if you want to clean them up you can delete the api access requests and then reinstall the package and only do it one. This api access is only used to upload custom images for your playlists/assets.

**Comment by Tyr03** [comment]
Thanks that done
