### ISSUE TITLE
In Microsoft learn website, table of content should be in the right panel

### ISSUE THREAD

**Issue by swotiendang** [pnp/custom-learning-office-365#844]
**Is your feature request related to a problem? Please describe.**
It's hard for me to keep track of the document, especially large pages, for example: https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-6.0?view=aspnetcore-8.0#aspnet-core-mvc-and-razor-improvements, I need to see where I'm in and what I'm interested in.

**Describe the solution you'd like**
Move table of content to right sidebar, instead of beginning of the page.

**Additional context**
Suggestion for changes:
![image](https://github.com/user-attachments/assets/08ada622-5f61-4f60-96c2-3fb8fc6e2d5d)

**Comment by dcashpeterson** [comment]
@swotiendang is the is related to the content you linked to or to Microsoft 365 Learning Pathways? This repo is specific to Microsoft 365 Learning Pathways. If you have feedback on Microsoft Learn content you should use the feedback link on those pages.

**Comment by dcashpeterson** [comment]
closed as unrelated to Microsoft 365 Learning Pathways.
