### ISSUE TITLE
 Unable to access CustomLearningAdmin.aspx after upgrading to version 5

### ISSUE THREAD

**Issue by luvsql** [pnp/custom-learning-office-365#845]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

After upgrading the SharePoint app in the Admin Centre to 5.0 as well as getting the new app in the Microsoft 365 Learning Pathways site contents following these instructions (https://github.com/pnp/custom-learning-office-365/blob/main/installation/UpdateV4-V5.md) I can access the main learning pathways site (...SitePages/Get-started-with-Microsoft-365.aspx) but the admin stie will not load (...SitePages/CustomLearningAdmin.aspx). There are no errors, there were no popups to upgrade so now I cannot modify the content anymore.  I've tried in cognito as well.  The page is blank with just hte heading.  

### To Reproduce

>Steps to reproduce the behavior

### Expected behavior

>A clear and concise description of what you expected to happen.

### Screenshots

>If applicable, add screenshots to help explain your problem.
![Admin Page](https://github.com/user-attachments/assets/acd2b232-3e17-4407-a153-26049fa61bfe)

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.

**Comment by dcashpeterson** [comment]
@luvsql we saw this issue in a few of our beta testers. The way to resolve the issue is to delete the sppkg file from the app catalog and add it again. I will add that to the documentation. [Beta Install Notes](https://github.com/pnp/custom-learning-office-365/blob/main/installation/V5Install.md#beta-installation-notes)

**Comment by luvsql** [comment]
We have a very customized Learning Centre solution.  Is there any risk of losing any site details, pages, customizations, playlists if we delete the app completely?

**Comment by dcashpeterson** [comment]
You should only delete the sppkg file from the app catalog. Do not delete the site or any of the lists. If you do this then the app will come back.

**Comment by luvsql** [comment]
Sorry to keep asking but to confirm, if I just delete the app from the app catalog, then upload 5.0 again, we will not lose any data, or access to the site or app itself?

**Comment by dcashpeterson** [comment]
@luvsql Deleting the app from the app catalog is separate from the data stored in the list so no you will not loose any data in the site.

**Comment by dcashpeterson** [comment]
@luvsql if you are nervous about potentially losing data you should follow the [backup instructions](https://github.com/pnp/custom-learning-office-365/blob/main/installation/BackupInstructions.md). That said replacing the package will not touch the data.

**Comment by luvsql** [comment]
Deleting and readding fixed the issue, thank you!
