### ISSUE TITLE
[QUESTION] Where do I get information on how to create a custom content pack? 

### ISSUE THREAD

**Issue by carlosebrecht** [pnp/custom-learning-office-365#846]
## Submit your question

Where do I get information on how to create a custom content pack? 

### What is the context of your question

- [ ] Installation
- [ ] Learning Pathways Content
- [ ] SharePoint Success Content
- [ ] Administration
- [X] Custom Content
- [ ] Viewer Web Part

### What is your question

>Provide related screen-shots to help us understand your question

**Comment by dcashpeterson** [comment]
@carlosebrecht thanks for using Microsoft 365 Learning Pathways. The best resource for creating a custom content pack is this [blog post](https://pnp.github.io/blog/post/adding-custom-metadata-through-a-content-pack-in-learning/).

**Comment by dcashpeterson** [comment]
Closing as answered
