### ISSUE TITLE
 Navigation Bar Not Configuring/Showing

### ISSUE THREAD

**Issue by drstrong06** [pnp/custom-learning-office-365#848]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug
I am attempting to install the Learning Pathways template on to a communication site in our tenant. We have not had the template previously. The template appears to configure all the way through and indicates in PowerShell it has completed but when it is done, the site looks correct however the navigation bar at the top is missing. 

### To Reproduce
Before install: Made sure I have Global Administrator privileges on the tenant. 

1. I connect to the site via PnP to create a session.
2. Run Invoke-PnPTenantTemplate -Path C:\Users\dstrong\Downloads\M365LP.pnp -Parameters @{"SiteUrl"="/sites/M365LearningPathways"} via PowerShell.
3. Wait for progress bars to complete, takes ~10-15 minutes.
4. Installation indicates it is complete however then shows "Applying Template to Tenant: M365LPSite:Navigation" in a new line
5. I waited for over an hour and that message never changed nor did the progress bar change
6. If you press enter or the arrow keys in PowerShell it disappears and acts like a new command line, no indication it was doing any sort of install.
7. Navigated to the SharePoint site and while all of the rest of the template appears to be installed (including the admin settings page), there is no Navigation Bar at the top. 
### Expected behavior

According to the documentation I have read I expected a navigation bar at the top with drop down menus for easy navigation. 
### Screenshots

![image](https://github.com/user-attachments/assets/6b07f006-1223-457c-9b58-1df332434ccd)

### Learning Pathways version number
5.0.0.4
### Additional context

I am the global admin on the tenant so there should be no issue with getting this applied. I have uninstalled and reinstalled the template and app in the app catalog 3 times now to see if it was an install glitch.

**Comment by dcashpeterson** [comment]
@drstrong06 you can turn this ok by going to the gear in the top right and the selecting Change The Look > Navigation > and making sure that the Site Navigation Visibility toggle is turned on and Mega menu is selected.

**Comment by dcashpeterson** [comment]
@drstrong06 also, I removed the images from the post bc they had your URL in them.

**Comment by drstrong06** [comment]
@dcashpeterson  thank you! I feel like a dolt - I could have sworn I tried enabling that and it did not work but I guess I didn't do the Mega menu. Thanks and sorry for wasting your time!
