### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by marcoschmucker** [pnp/custom-learning-office-365#853]
## Submit your question

**Microsoft help source URLs and cookie consents for users in v5?**

### What is the context of your question

- [ ] Installation
- [ ] Learning Pathways Content
- [x ] SharePoint Success Content
- [ ] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### What is your question
With the help content included from Microsoft, is there always a cookie consent window for each user when reading embedded content, like on Microsoft's websites?

Which Microsoft help source URLs are included? 

Thanks for your help!

**Comment by dcashpeterson** [comment]
@marcoschmucker I am not sure what the question is here? The content for all the Learning Pathways content is included via an IFrame. We have no control over the content (cookie consent or other content) for the pages and just pull them into the webpart. Is there something more you are asking?

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new issue and reference this one. In addition, please answer the question in the previous comment.

**Comment by dcashpeterson** [comment]
@marcoschmucker the webpart is embedded in SharePoint so it is not responsible for showing a cookie message just like the news webpart isn't required to put out a cookie menu. The pages that Learning Pathways pulls in via an Iframe are responsible for their own content and we have no control over those. I hope that answers your question.

**Comment by marcoschmucker** [comment]
@dcashpeterson Thanks a lot. This is true!
