### ISSUE TITLE
 CMD Error in Silverlight manual uninstall "Let me fix it myself"

### ISSUE THREAD

**Issue by mcpoulet23** [pnp/custom-learning-office-365#855]
The manual reolution guide on the following site contains an error in the CMD script:
https://learn.microsoft.com/en-us/previous-versions/troubleshoot/visualstudio/silverlight/clean-corrupted-silverlight-installation-reinstall-silverlight

This line contains a reg key with a space, therefore needs quotes:
reg delete HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\install.exe /f

Correction TODO:
reg delete "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\install.exe" /f

**Comment by dcashpeterson** [comment]
@mcpoulet23 This looks like an issue with the content on that page. Microsoft 365 Learning Pathways isn't responsible for updating the content on Learn. In addition, if you look at the notice at the top of the page it says that Microsoft is no longer updating the content on that page so I can't offer any way for you to provide feedback to the content creators.
