### ISSUE TITLE
 Invalid SharePoint App package:  Error: File contains corrupted data.

### ISSUE THREAD

**Issue by droogsdontrun** [pnp/custom-learning-office-365#856]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

This error message pops up no matter how many times I re-download the package file and attempt another upload:  Invalid SharePoint App package:  Error: File contains corrupted data.

### To Reproduce

Download the customlearning.sppkg, upload it to the sites/appcatalog/_layouts/15/tenantAppCatalog.aspx/manageApps section of the site, the Apps for SharePoint.  This is an upgrade from 4 to 5 of the app.  Error will show up after a successful upload.

### Expected behavior

This should update the site to 5.0

### Screenshots

![image](https://github.com/user-attachments/assets/b4c8a43b-4701-4a64-aca2-7c77c9c0818d)

### Learning Pathways version number

This is an upgrade from 4.3.0.0 to 5.0

**Comment by droogsdontrun** [comment]
Deleted the existing file and re-uploaded it, same result.  

![image](https://github.com/user-attachments/assets/3dc69d43-26fe-4855-9096-bc5969db77f0)

**Comment by droogsdontrun** [comment]
Turns out it needs to be upgraded as a global admin, not just a sharepoint admin.

**Comment by dcashpeterson** [comment]
@droogsdontrun glad it's working.
