### ISSUE TITLE
[QUESTION] Trying to install Version 5

### ISSUE THREAD

**Issue by mabaugh83** [pnp/custom-learning-office-365#857]
We are trying to install version 5 of the sppkg. We are now seeing that "Installing SharePoint add-ins from the SharePoint Store will not be possible as of July 1, 2024"

How do we deploy to our tenant now?

**Comment by dcashpeterson** [comment]
@mabaugh83 Microsoft 365 Learning Pathways is not a SharePoint add-in. It is a custom web part using the SharePoint framework. It is not effected by this announcement. You can follow the instructions in the ReadMe for installation.
