### ISSUE TITLE
Are there plans for the PowerPlatform to be included in Learning Pathways?

### ISSUE THREAD

**Issue by Mlavieri** [pnp/custom-learning-office-365#86]
#### Category

- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Are there plans for the PowerPlatform to be included in Learning Pathways, including PowerBI, Flow, and PowerApps, I will be happy to open a user voice on the matter as well just wanted to see if this was already planned or a possibility. 

Thanks

**Comment by peterjkrebs** [comment]
Plans for PowerBI, Flow, and PowerApps training content is on our radar, but we don't have an ETA for the content at this time. We are planning to publish an editorial calendar this quarter, so we can give you better insight into our content plans going forward.

**Comment by Mlavieri** [comment]
Thanks Peter
