### ISSUE TITLE
Update to V 5 broke our Learning pathways site

### ISSUE THREAD

**Issue by jamesshover** [pnp/custom-learning-office-365#860]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Submit your question
We have a MS Learning Pathways SPO site that was stood up 2/11/2020. The site had ver 3 running but was not updating information, i.e., links to information was out of date/stale for many items. I download V5 and uploaded to tenant. then I went to the Learning Pathways site and updated to V%. Now the site data will not load and all the links are broken. I'm at a total loss as I was not the person that created the site originally. I submitted a MS Premier support request, and they do not support the Learning Pathways. Internal users are submitting tickets wanting the site restored/fixed.

### What is the context of your question

- [ ] Installation
- [ ] Learning Pathways Content
- [ ] SharePoint Success Content
- [x ] Administration
- [x ] Custom Content
- [ ] Viewer Web Part

![pathways9](https://github.com/user-attachments/assets/6a519c1a-482b-404d-abd7-dda906d7c268)
![Pathways8](https://github.com/user-attachments/assets/788f7bdf-e03b-45ed-a9eb-f12bec7824a4)
![pathways7](https://github.com/user-attachments/assets/4d9dbb31-2315-4cd1-aff1-72d157f80756)
![pathways6](https://github.com/user-attachments/assets/3a8d6264-8562-4b86-904b-f0bcccf1d220)
![pathways5](https://github.com/user-attachments/assets/ab22d8c2-c3b8-44bb-9664-44e78b640d18)
![pathways4](https://github.com/user-attachments/assets/59a7bf2d-252b-4fa0-9462-3fb7c3a59c28)
![pathways3](https://github.com/user-attachments/assets/f02cdb6c-152d-4a32-a21c-dfd73350bc5b)
![pathways2](https://github.com/user-attachments/assets/0ee75d03-7d24-49ed-84a1-3fe7107ac84d)
![pathways1](https://github.com/user-attachments/assets/4ba7af2f-fd43-4ef5-832b-c123f27d4c6b)

### What is your question

>Provide related screen-shots to help us understand your question

**Comment by dcashpeterson** [comment]
@jamesshover The upgrade path from V3 to V4 was a larger change introducing multi-lingual capabilities. Did you run through the upgrade steps in this [documentation](https://github.com/pnp/custom-learning-office-365/blob/main/installation/AddingMultilingualSupport.md) without error? 

I would need to see the console errors that are being put out in order to help you but, if it is in some partially working state and it hadn't been touched since 2020 then it might be easier for you to delete the app from the app catalog, delete the learning site, and then reinstall the application using the [V5 instructions](https://github.com/pnp/custom-learning-office-365/tree/main/installation).

**Comment by dcashpeterson** [comment]
@jamesshover while the documentation doesn't specifically state not to go from V3 to V5 in the V4 to V5 upgrade instructions it does specifically call out if you are going from V3 to V5 you need to make sure that you have followed the upgrade from V3-V4 first enabling multilingual. 

PLEASE If you are upgrading from V3 to V5 review the content of [Adding Multilingual Support to Microsoft 365 learning pathways](https://github.com/pnp/custom-learning-office-365/blob/main/installation/AddingMultilingualSupport.md) document before proceeding.

With all that said, if multilingual was not set up properly with the instructions above then that would explain the issue. I can't determine the state of the configuration files at this point and without errors from the console I can't help troubleshoot. 

Your options are to backup any custom assets, playlists, etc and create a new M365 Learning Pathways site or or try to fix the one you have by following the multilingual instructions (V3-V4 instructions) and then updating from V4-V5. There are no config changes from V4 to V5.

**Comment by jamesshover** [comment]
Good afternoon @dcashpeterson 
Update and resolution.
We removed V5 from the app catalog and reinstalled V3.
We then progressed through the updates V3 to V4.0.2 to V5.0.04 (suggested by the text on screen that "app is out of date, please update to XXXX).
At each step we tested the Learning Pathways site and searched for errors, everything is working correctly.
thank you for your assistance.
Best,
Jim

**Comment by jamesshover** [comment]
Good afternoon @dcashpeterson
Update and resolution.
We removed V5 from the app catalog and reinstalled V3.
We then progressed through the updates V3 to V4.0.2 to V5.0.04 (suggested by the text on screen that "app is out of date, please update to XXXX).
At each step we tested the Learning Pathways site and searched for errors, everything is working correctly.
thank you for your assistance.
Best,
Jim
