### ISSUE TITLE
[QUESTION] I have updated the version from 4 to 5 and now CustomLearningAdmin page is not loading

### ISSUE THREAD

**Issue by AftabD** [pnp/custom-learning-office-365#863]
Hello,

Below are captures attached for all my issues. The CustomLearningAdmin page is not loading after the App upgrade from 4 to 5.

Some videos are not loading and giving the below error.

![image](https://github.com/user-attachments/assets/457e2b7f-d1d9-4d73-9b92-bfbf057525dc)
![image](https://github.com/user-attachments/assets/42e39712-6e84-41a7-a805-a5ab318b6177)
![image](https://github.com/user-attachments/assets/e207548b-3a9b-4985-805b-f121f9c145b0)
![image](https://github.com/user-attachments/assets/69d3d36b-d527-4e09-8369-1aef6af1653b)

Regards

**Comment by dcashpeterson** [comment]
@AftabD The admin screen not loading after upgrade is something we saw in testing. The resolution is to delete the app catalog and add it again. https://github.com/pnp/custom-learning-office-365/blob/main/installation/UpdateV4-V5.md#v5-update-note

The videos not showing look like custom videos that we have just had reported. See this explaination. https://github.com/pnp/custom-learning-office-365/issues/862#issuecomment-2462262990

**Comment by AftabD** [comment]
Thanks @dcashpeterson  I have deleted and added the App again from the catalog and now I can open the CustomLearningAdmin page fine.

But still, some of the videos are not loading and showing the below error.
![image](https://github.com/user-attachments/assets/95007581-28e6-4ecd-81a9-3ea7a5e9600f)

**Comment by dcashpeterson** [comment]
That was the second link I sent. It's probably how you created the link to the video.

**Comment by AftabD** [comment]
Thanks, I was able to fix it, so do I need to do it for all the videos that are not working and giving this error?

**Comment by dcashpeterson** [comment]
Yes you would need to do that for every video that isn't working.

**Comment by AftabD** [comment]
Thanks for all the help.
