### ISSUE TITLE
[QUESTION] WARNING: Could not find Microsoft 365 learning pathways Web Parts.

### ISSUE THREAD

**Issue by ryanwtwb** [pnp/custom-learning-office-365#865]
## Submit your question
Completing a fresh install of v5 after removing v2 on site. Successfully followed all instructions for installation on this site but when trying to run the PowerShell script with -SiteAdminOnly parameter, I receive the WARNING error:

.......WARNING: Could not find Microsoft 365 learning pathways Web Parts.
WARNING: Please verify the Microsoft 365 learning pathways Package is installed and run this installation script again.

This also happened for me when trying to install on a newly created test site.

### What is the context of your question

- [X ] Installation
- [ ] Learning Pathways Content
- [ ] SharePoint Success Content
- [ ] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

![Untitled](https://github.com/user-attachments/assets/d58b941a-7da2-426e-a999-30e28399775b)

**Comment by dcashpeterson** [comment]
@ryanwtwb  can you confirm if the webparts were loaded into the site collection or are there already? you should see M365 Learning Pathways when you go to Site Contents. If you don't see them can you try to add them manually?

**Comment by ryanwtwb** [comment]
@dcashpeterson yes, the web parts are visible in the Site Contents.

![image](https://github.com/user-attachments/assets/b7ec7399-a7b9-42c1-87db-bded59eedf1e)

**Comment by ryanwtwb** [comment]
@dcashpeterson I've managed to gain access to the web part by following the look book installation method instead of the manual method, but I now have a different issue that I am unable to resolve.
I removed the app from the site then followed the instructions here - https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/applying-pnp-templates

I now receive the following error when I try to load the web part on the CustomLearningAdmin.aspx page:

![image](https://github.com/user-attachments/assets/e879d37a-f75e-47f0-9ccb-99ae835e21c6)

![Screenshot 2024-11-27 114345](https://github.com/user-attachments/assets/746753f5-8218-43f3-8b37-7ed12bff16fe)

![Screenshot 2024-11-27 114400](https://github.com/user-attachments/assets/284b3289-e82f-4c08-87b8-1abd566e97f7)

**Comment by ryanwtwb** [comment]
Bump.
Still struggling with this same problem. Web parts not loading and receiving these errors in the console.
Does anyone have some idea?

**Comment by dcashpeterson** [comment]
@ryanwtwb this issue could be a few things. Did you delete the site that had the V2 on it? If you didn't then the cache in the custom lists could be corrupt. Delete everything with a title of customConfig in the CustomConfig list. Then refresh the page. It takes a bit of time to rebuild the cache but to make it faster show and then hide an asset. If that doesn't work it could also be any custom assets or custom playlist that are in the CustomAssets and CustomPlaylists lists. If it still doesn't work you might need to delete the entries in these lists.

You should also check and ensure that the tenant app property is set to the correct URL.
Get-PnPStorageEntity -Key MicrosoftCustomLearningCdn
Get-PnPStorageEntity -Key MicrosoftCustomLearningSite

If the MicrosoftCustomLearningSite value is not correct you need to reset it to the new site. [M365 LP Site URL script](https://github.com/pnp/custom-learning-office-365/blob/main/installation/UpdateM365lpSiteUrl.ps1).

**Comment by ryanwtwb** [comment]
Success!
Thank you @dcashpeterson .
The Custom Config list is what seems to have been the problem. I cleared that list out of all items and all of the web parts and pathways are loading correctly. Thank you very much for your help!

**Comment by dcashpeterson** [comment]
Good to hear. Glad things worked out.
