### ISSUE TITLE
 [INSTALLATION ISSUE] I followed the instructions for upgrade but the CustomLearningAdmin.aspx doesn't load

### ISSUE THREAD

**Issue by mrsbeata** [pnp/custom-learning-office-365#866]
## Describe the bug
I think I followed the steps to update from version 4 to 5. I probably should just record my screen when I do this because of course I don't remember exactly everything I did. 

I have the right access. I downloaded the latest version. I uploaded it to the app catalouge. I approved it. I updated the app in the Communication site. The page CustomLearningAdmin.aspx never loads. I don't get an error or anything.  

I removed it from the app catalouge and tried again. Same result. I tried it again. Same result. 

### Learning Pathways version number
5.0.0.4

### Additional context
I'm probably the issue.

**Comment by dcashpeterson** [comment]
@mrsbeata my guess is that something went wrong in removing and readding the solution to the app catalog. Make sure that it is deleted from the app catalog and then readd it. The other thing to look at is if you are using the tenant app catalog and a site collection app catalog. If that doesn't work I would need the errors that are showing up in the console to help.

**Comment by gomezcuenca** [comment]
Hello!
I have the same issue.
I followed the instructions for upgrade from version 4 to 5, but the CustomLearningAdmin.aspx doesn't load.

This is the error on my console:

Access to XMLHttpRequest at 'https://browser.pipe.aria.microsoft.com/Collector/3.0/?cors=true&content-type=application/x-json-stream&w=2' from origin 'https://xxxxxx.sharepoint.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

Thanks in advance.

**Comment by dcashpeterson** [comment]
@gomezcuenca as I mentioned in the original post. When you see that issue you need to delete the package from the app catalog and then readd it. That will fix the issue. The only instances we have seen where that doens't fix the issue is when there is an issue with the config which generally happens when an upgrade is done incorrectly.

**Comment by gomezcuenca** [comment]
Hello again.

I confirm that deleting and re-adding it for the fourth or fifth time **worked**.

Thank you very much @dcashpeterson!

**Comment by mrsbeata** [comment]
I have deleted it and re-adding it a few times now. I don't get an error but the CustomLearningAdmin page is just not loading.

**Comment by mrsbeata** [comment]
Ok, there is the old experience (Apps for SharePoint) and the new (Manage apps). I was using the old and it shouldn't matter but it might. This is what I have done.

1. Downloaded customlearning.sppkg.
2. Deleted the old learning pathways.
3. Go to the new experience, https://xxx.sharepoint.com/sites/appcatalouge/_layouts/15/tenantAppCatalog.aspx/manageApps
4. Upload customlearning.sppkg
5. Enable app.
6. _API access that must be approved after you enable this app
7. Microsoft Graph, Files.ReadWrite.All_
8. Go to https://xxxx-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/webApiPermissionManagement
9. Before I saw a pending, approved it. Now after I have done this a few times I see nothing here to approve but there is a Microsoft Graph Files.ReadWrite.All in the org wide approved requests.
10. Go to https://xxxx.sharepoint.com/sites/O365CL/SitePages/CustomLearningAdmin.aspx
11. The page never loads. Stops with grey boxes. No error. 

I will try it again.

**Comment by mrsbeata** [comment]
I tried to do the same while also remove the API access. Then I had to approve the API access. I got an error for Teams. 

_Approve access so this app works as designed

Could not add app to Teams. You can add it later in Manage App page.
For this app to work as designed, it needs additional API access. To approve the permission request now, select Go to API access page, and then look under Pending requests.

To approve access to third-party APIs, you must be signed in as an Application Administrator. To approve access to Microsoft APIs, you must be signed in as a Global Administrator._

Sure - I'm GA. Goes there, approves the API requests. Looks good. Go to CustomLearingAdmin.aspx and the page won't load.

**Comment by mrsbeata** [comment]
Ok. I'm the idiot but to be sure, I said so when opening the ticket. I had TWO Learning pathway sites in my tenant. And I guess the sort of old one didn't work. I deleted that site and all is well. I hope this will help other idiots in the future to be less idiotic. Sorry for bothering you. Keep up the good work!

**Comment by dcashpeterson** [comment]
@mrsbeata your not an idiot. That happens a lot. That was going to be one of my next questions. I am interested in your experience with the upgrade was it not working with the classic app catalog but it did work with the modern or did you notice the two LP sites after you used the modern one?
