### ISSUE TITLE
Customize Technology

### ISSUE THREAD

**Issue by techieSudeep** [pnp/custom-learning-office-365#87]
Hi, the ability to provide end users with training solution like this is going to be game changer. Kudos to the entire team, fabulous training solution indeed.

With that being said, as I was playing with the site I came across the following

1. I don't see Power BI in Technology. I tried creating new item under Product section but don't have the ability to use custom image, is this under works? (Please see attached image)
2. Can I add my own items in Technology? 
3. How often does the content update? And where can I find the documentation about content being updated? Should tenant admins run any PS scripts?
![Learning Pathways](https://user-images.githubusercontent.com/52350666/60384461-e6fbd800-9a4b-11e9-8032-2c4cdcd001a9.jpg)

Thanks,
Sudeep

**Comment by juliemturner** [comment]
@techieSudeep, I can answer your technical questions but not questions about content.

1. You can not currently set a custom image for a sub-category.  It is a requested enhancement but I don't have a date when we would implement it.
2. You cannot add your own technology at this time.
3. There are no scripts to run, content when updated will just show up within 24 hours of it being published to the CDN.

**Comment by juliemturner** [comment]
closed to inactivity
