### ISSUE TITLE
Where is the Skype for Business content?  

### ISSUE THREAD

**Issue by technoteach** [pnp/custom-learning-office-365#89]
> 

#### Category

- [x] Skype for Business is listed under the Technology available but where is the content?
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

> Skype is listed under the technology but I do not find any playlist to create.  Am I just missing it?

**Comment by peterjkrebs** [comment]
Thank you for the feedback. Skype for Business Training has been replaced with the Microsoft Teams training. Thanks for pointing out the entry is in technology. We'll updated our metadata to reflect that Skype for Business training is not available. If you're looking for Skype for Business content, send mail to ENTLEARN@microsoft.com and we'll work to accommodate your content needs.

**Comment by juliemturner** [comment]
Closed to inactivity
