### ISSUE TITLE
custom learning homepage

### ISSUE THREAD

**Issue by davepae** [pnp/custom-learning-office-365#9]
After successful manual provisioning, what are the steps to get the custom learning homepage that pnp provisioning sets up?

**Comment by karuanag** [comment]
HI Dave - did you follow the instructions here:  https://docs.microsoft.com/en-us/office365/customlearning/custom_upgrade    Then I'll know your current configuration.  Trying to assess if you already have provisioned the Admin pages for the webpart.

**Comment by karuanag** [comment]
Hello Dave - Peter is going to follow up with you and update this ticket as well.

**Comment by davepae** [comment]
Close this issue. We ran into an error running admin aspx. Reference this issue: https://github.com/pnp/custom-learning-office-365/issues/11

**Comment by davepae** [comment]
repro steps:
1. using admin@ account for all steps on a new tenant
2. confirm all pre-reqs. admin@ is tenant admin, app catalog owner and site collection admin/owner, etc.
3. follow pnp provisioning steps - which ended up not working
4. next try manual steps
5. extra steps: created learning site collection to use in ps1 step (script outputted it needed to be created when I simply entered a name).

This may be a common IT admin flow if pnp provisioning fails. Their choices are give up or try the manual step. ps1 completed successfully but the admin.aspx error is reported in issue#11.

**Comment by juliemturner** [comment]
Closing this issue as it was related to a new app catalog.
