### ISSUE TITLE
Learning Pathways Content to match MS Learning Center?

### ISSUE THREAD

**Issue by ChristineSimpson** [pnp/custom-learning-office-365#90]
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Is there a plan to have the content available through Learning Pathways match what is on the Microsoft Training Center?

For example, Planner in Learning Pathways shows two tracks, MS Training Center has four. Learning Pathways track for "Use Planner" is "Ideas for your board" on the MS Training Center. The MS Training Center "Use Planner" is not available in the Learning Pathways content.

**Comment by peterjkrebs** [comment]
We can't promise an exact match but we are planning an update this quarter to refresh our content in Learning Pathways to more closely align with what's on the Office Training Center. Thanks for the feedback.

**Comment by juliemturner** [comment]
Close to inactivity
