### ISSUE TITLE
Embed content from docs.microsoft.com

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/custom-learning-office-365#91]
#### Category

- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I would like to embed pages from docs.microsoft.com in custom playlists, the same way it works for default playlists.

#### Observed Behavior
In custom playlists, when I try to embed a page from docs.microsoft.com I get the following message:
_This content can’t be shown in a frame_
Surprising, as the exact same content is displayed just fine in a default playlist.

#### Steps to Reproduce
- copy a URL from docs.microsoft.com used in a default playlist asset. For example:
https://docs.microsoft.com/office365/customlearning/dayinthelife?context=context%2Fchromeless&linktarget=true
- paste it in a custom playlist asset

**Comment by juliemturner** [comment]
@PathToSharePoint -- you also need to include the SharePoint tenant origin... so add an additional parameter to the query string "&fromOrigin=https://contoso.sharepoint.com" -- where contoso is your tenant name.

**Comment by PathToSharePoint** [comment]
Got it, thanks! I actually tried this before, but didn't include the https part.
