### ISSUE TITLE
Trying to upgrade from Custom Learning for O365 to M365 Learning Pathways

### ISSUE THREAD

**Issue by lakrupka** [pnp/custom-learning-office-365#92]
![CL for O365 still showing](https://user-images.githubusercontent.com/50598974/60834872-529a1f80-a187-11e9-81ca-329f9b01cb4d.jpg)

#### Category

- [ ] Question
- [ ] Typo
- [ X ] Bug
- [ ] Additional article idea

I updated to the latest package in my tenant catalog as verified by attached. I also updated the site collection contents to the latest version of M365 Learning Pathways. However, the app is still showing the Custom Learning for O365 content.  Please assist.  
![Learning Pathways latest package](https://user-images.githubusercontent.com/50598974/60834874-529a1f80-a187-11e9-9eee-14d9ab10c79c.jpg)

**Comment by juliemturner** [comment]
@lakrupka  -- If by the app "still showing the Custom Learning for O365 content" you mean the pages in the provisioned site collection didn't change then that is as it has to be.  The web part is the viewer and administration for the playlists and assets that are viewed by the users.  The content that is shown in the web part is automatically up to date without you doing anything.  The pages themselves in the site collection are static and do not change, they are meant to be a guide or getting started point for you to customize.

**Comment by juliemturner** [comment]
closed to inactivity
