### ISSUE TITLE
Hidden items are shown

### ISSUE THREAD

**Issue by eriksv-ms** [pnp/custom-learning-office-365#93]
#### Category

- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Hidden items, when added, should respect that status and vice-versa when added.

#### Observed Behavior

From DANA CORP:

This is when things hidden only show and things set to show are hidden. It may last for 20 minutes or 6 hours. It not only makes it hard when I am adding content for the launch, but also something that we do not want to launch with. Example videos to use chat in teams until we intentionally turn it on and are ready. When this bug occurs it actually only shows chat as the only video.

#### Steps to Reproduce

- In admin, set an item to hidden

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by juliemturner** [comment]
@eriksv-ms -- I'm fairly sure you're issue is you're not using the most current version of the web part.  Can you validate your version using the instructions [here](https://github.com/pnp/custom-learning-office-365#updating-the-solution), and if you're out of date please update.  Then please let me know if you still have the issue.

**Comment by juliemturner** [comment]
Closed due to inactivity
