### ISSUE TITLE
Content used in playlists are pulled

### ISSUE THREAD

**Issue by eriksv-ms** [pnp/custom-learning-office-365#94]
#### Category

- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Training content that's on our public sites should continue to be available or some notice or pointer to updated content should be made available.

#### Observed Behavior

From customer DANA.COM:

I am current wasting time create links over to the missing content that is here (only using teams as example):
https://support.office.com/en-us/article/microsoft-teams-video-training-4f108e54-240b-4351-8084-b1089f0d21d7?ui=en-US&rs=en-US&ad=US

#### Steps to Reproduce

- Add link above to playlist

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by juliemturner** [comment]
@eriksv-ms  -- I'm sorry but I'm not really following what the issue is.  I think you're saying that the content that's displayed on the linked page from support.office.com has changed?

**Comment by eriksv-ms** [comment]
Correct. The customer is saying that they can't rely on content they're finding online since the content (as shown above) can move or be removed. I'm not sure what the solution is other than, possibly, a notification that the content has been moved/removed.

**Comment by juliemturner** [comment]
@eriksv-ms -- Ok, I can't comment on how the content is managed on support.office.com or docs.microsoft.com as it has really very little to do with Microsoft 365 learning pathways. I know there will be more exposure about content being added/removed from the manifests that feed the M365LP but as far as how the content on support/docs is managed I don't think that's an issue for this solution directly.

**Comment by peterjkrebs** [comment]
Thank you for the feedback. We will be releasing a quarterly update to our content in the July-Aug timeframe and then quarterly after that. We will also publish an editorial calendar so organizations are aware of changes and new content being published.

**Comment by juliemturner** [comment]
closed to inactivity
