### ISSUE TITLE
Cannot set the order of Playlists to be watched for a given product or other

### ISSUE THREAD

**Issue by itaillon** [pnp/custom-learning-office-365#96]
Order in which playlists (tiles) appear in front-end web pages and in Admin page is not configurable. We can’t control the order of Playlists to be watched, and this matters in the context of learning. 

#### Category

- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The current set of playlists is based on a single type of O365 governance model where all licensed users are free to create Teams, use the self-service site creation, etc. (a vanilla install and configuration of O365). Thankfully, we can hide playlists and add custom ones to address the need of each company's governance model, specifically those that may have adopted a more controlled governance model. 

When we add custom playlists to a product category (subcategory), whether to replace a few existing ones or to add to the existing set of playlists, we expect to be able to position the new playlists in the order to be watched against the other playlists a given product. 

#### Observed Behavior
In the Admin view, custom playlists end up at the end of the set (subcategory) where it is added.
In the learning web part filtered by subcategory, the new playlists appears in a random order. Order of tiles cannot be modified in the web part.

#### Steps to Reproduce
Add multiple playlists to a subcategory. Try to move them up or down against the other playlists (no way to do this).

**Comment by itaillon** [comment]
Screenshots
### Scenario #1 – Microsoft Teams learning
In this scenario, I needed to replace the “Teams Quick start” playlist by custom one.  I have created a new one as shown below. All custom playlists we create end up at the end of the list. This watch order will not make sense.
![Scenario 1 Admin Playlists](https://user-images.githubusercontent.com/45693216/60995803-48138d80-a321-11e9-9eb8-19d75f957aaf.png)
Below is the Learning webpart. My custom “Teams Quick Start” playlist appears at the end of the list.  I cannot change the order of the tiles here either.  This watch order is not ok.
![Scenario 1 Leaning web part result](https://user-images.githubusercontent.com/45693216/60995909-8dd05600-a321-11e9-8962-b9f936abf032.png)

### Scenario #2 – Office 365 learning
In this scenario, I have toggled off the first 2 playlists. I want the learning path to start with “What is Office 365”. I have also created a custom playlist called ”Share files” that I would like to be watched after “Store online and collaborate” in the watch sequence.  (I cannot change the order of playlists here).
![Scenario 2 Admin Playlists](https://user-images.githubusercontent.com/45693216/60996033-d556e200-a321-11e9-8f8d-71eefeb6675d.png)
Below is output in the Learning web part. My custom “Share files” playlist appears as the first tile to watch. This hardly makes sense from a learning perspective, I need to be able to set the watch order of these playlists. Compared to scenario #1, it is hard to predict how these tiles are sorted.
![Scenario 2 Leaning web part result](https://user-images.githubusercontent.com/45693216/60996221-31216b00-a322-11e9-81e6-0f03cd52e1f9.png)

**Comment by juliemturner** [comment]
@itaillon  - Yes, what you're referencing is by design because there is no good way given the variable nature of the content manifests to allow you to customize the order of those manifests on a per tenant basis that will not cause issues under a variety of different circumstances such as the removal of a playlists or the addition of new ones. Please feel free to submit an enhancement request to our User Voice channel: https://microsoftteams.uservoice.com/forums/913429-learning-solutions

**Comment by ec-alm** [comment]
Hi @juliemturner - RE the feedback that there's no good way to achieve this, could the distinction be drawn between Core content and Custom content?

With custom content able to use a specific order and core (MS supplied) content appearing in the released order?

You could also perhaps specify an option as to whether to show Custom or core content first. That way we can curate our own playlists in a specific order, but maintain the Microsoft supplied materials as is

**Comment by juliemturner** [comment]
Yes, that could theoretically be done.

**Comment by pb03873** [comment]
It would already be very useful if we could add one custom content at the top of the list.  

The purpose is to inform our users of the differences between the MS content they are going to consult and our actual situation (e.g. features which we have not yet enabled, our local request procedures, ...).  It is important that the users have these differences in mind before they work with the MS content.

BTW, new content was added in the Outlook subcategory about Outlook mobile => our custom content is now in sandwich between the former and new content.

**Comment by JudiP53** [comment]
> @itaillon - ... Please feel free to submit an enhancement request to our User Voice channel: https://microsoftteams.uservoice.com/forums/913429-learning-solutions

This link is broken. Would very much like to add a vote on this.

**Comment by SjoerdV** [comment]
It really pains me to see that the developer(s) who build this 'product' did not consider any type of architecture beforehand. The **default CRUD actions, Sorting, Ordering, Filtering** should be just there on **any Entity** as it is in any **usable** MVC setup. Am I the only one feeling very nauseated when considering this monstrosity? My advise would be: start from scratch, draw it out (ie. which entities do I have and how do they relate to each other),  so to have some solid groundwork in place and _**then**_ do some programming.

**Comment by karuanag** [comment]
When I'm customizing a learning path I normally create a new category and add those playlists in the order I want them consumed.  A popular alternative is to create a new page and deep link to the content you want with additional context/copy surrounding it.   Using standard SharePoint capabilities for customizing the content experience is by design.  Thanks

**Comment by DarrellaaS** [comment]
Like @karuanag,  I create a copy of the standard playlist and add my own content to it. 
However, I understand the request and agree that it would be really helpful to be able to set the order that content appears inside the web part, when displaying filtering to a category level. For now, I have to create seperate custom pages, avoid using the web part filtering and just use a Quick Links web part to display my playlists in the order I want people to choose from. 
![M365LP-Pages-to-present-custom-playlist-order](https://user-images.githubusercontent.com/25329544/83809878-4d34b480-a70b-11ea-9849-188fb4c6a8c6.jpg)

**Comment by juliemturner** [comment]
It seems more like the appropriate solution wouldn't be to change the ordering in the admin site but rather to have the option in the web part to decade a custom sort for the content you're pinning to.  That actually is probably quite doable.

**Comment by juliemturner** [comment]
We have address having a custom sort for the contents of a Category/Subcategory in version 4.1.1 of the learning pathways solution which was made available on July 28th, 2020. Please see more information about the feature here: https://docs.microsoft.com/en-us/office365/customlearning/custom_sortsubplay
