### ISSUE TITLE
Custom Playlist not visible in web part filtering

### ISSUE THREAD

**Issue by justdevcode** [pnp/custom-learning-office-365#97]
#### Category

- [ ] Question
- [ ] Typo
- Bug
- [ ] Additional article idea

I've created a custom playlist, added a learning pathway web part to a page, filtered the web part to only show a particular playlist, but my custom playlist is not visible. I can only choose from the provided playlists. Should custom playlists be visible?

#### Expected or Desired Behavior

See custom playlists in web part filter drop-down list

#### Observed Behavior

Custom playlist not visible in web part drop-down list, only the provided playlists are visible.

#### Steps to Reproduce

- Add learning web part to a new page.
- Configure the web part as follows:
-- Select Filter : Playlist
-- Filter  to Playlist: 

Thanks for your contribution! Sharing is caring.

**Comment by justdevcode** [comment]
I noticed I need to remove the web part from the page and re-add it to see newly added custom playlist. Would be great if we did not need to remove the web part and re-add it.

**Comment by juliemturner** [comment]
@justdevcode -- please validate that you have the most recent version of the web part based on this information: https://github.com/pnp/custom-learning-office-365##updating-the-solution

**Comment by justdevcode** [comment]
Hi Julie, I can confirm that I have the most recent version installed as I
had only just installed it when I experienced the issue.

**Comment by juliemturner** [comment]
@justdevcode  -- did you try just refreshing the page and then editing the web part again?  If you're adding playlists in one tab and then trying to consume them in another the web part is client side so it wouldn't know (until you refresh the page) that a new playlist was added.

**Comment by juliemturner** [comment]
Closed due to inactivity
