### ISSUE TITLE
Typo and Question Re:  MS Learning Pathways

### ISSUE THREAD

**Issue by Kwarlin** [pnp/custom-learning-office-365#99]
#### Category

- [ ] Question
- [ X] Typo
- [ ] Bug
- [ ] Additional article idea
In the Getting Started, Your Digital Day Playlist, Collaborating with Your Colleagues, there is an extra bullet under Tools.

**Comment by peterjkrebs** [comment]
Thank you for you feedback. We'll correct the typo.
